### ISSUE TITLE
Resolver error: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by christophermarianolumiradx** [stoicflame/enunciate#1000]
We are using Enunciate v.2.12.1 and most of the time, our API Document page shows the error banner on top. This is a bit unsightly given that it occupies most of the viewable area of the page.

<img width="1649" alt="Screen Shot 2020-01-22 at 6 45 27 PM" src="https://user-images.githubusercontent.com/33870250/72944636-7994f900-3d47-11ea-8d56-9ddb19f01d62.png">

I think we would need to upgrade the Swagger version to v 3.12.0. See github issue [here](https://github.com/swagger-api/swagger-ui/issues/3366)

**Comment by stoicflame** [comment]
Okay, thanks for the report.

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
