### ISSUE TITLE
Endpoint base class that also works stand-alone ignored in generated documentation

### ISSUE THREAD

**Issue by tiguchi** [stoicflame/enunciate#1001]
# Setup

- Enunciate v2.12.1 (via Gradle)
- JAX-RS
- Non-abstract service endpoint class `UserService` under path `/users`
- Admin service endpoint child class `AdminUserService extends UserService` under path `/admin/users` that has additional, privileged methods and overrides on top of same basic features as `UserService`

# Problem

Only the endpoint methods and descriptions of the child class `AdminUserService` are picked up. `UserService` under path `/users` does not appear in generated documentation output.

# Expected Behavior

Both service endpoints should be listed with their respective documentations.

**Comment by stoicflame** [comment]
I'm afraid I'm able to reproduce this issue. Here's a diff I applied to [enunciate-sample](https://github.com/stoicflame/enunciate-sample):

```diff
diff --git a/src/main/java/com/ifyouwannabecool/impl/AdminUserService.java b/src/main/java/com/ifyouwannabecool/impl/AdminUserService.java
index 74714a0..de0dc7b 100644
--- a/src/main/java/com/ifyouwannabecool/impl/AdminUserService.java
+++ b/src/main/java/com/ifyouwannabecool/impl/AdminUserService.java
@@ -3,5 +3,16 @@
  */
 package com.ifyouwannabecool.impl;
 
+import javax.ws.rs.GET;
+import javax.ws.rs.Path;
+import javax.ws.rs.Produces;
+
+@Path("/admin/users")
+@Produces("text/plain")
 public class AdminUserService {
+
+  @GET
+  public String get() {
+    return "hello, admin";
+  }
 }
diff --git a/src/main/java/com/ifyouwannabecool/impl/UserService.java b/src/main/java/com/ifyouwannabecool/impl/UserService.java
index 3c42fac..1cb6bb2 100644
--- a/src/main/java/com/ifyouwannabecool/impl/UserService.java
+++ b/src/main/java/com/ifyouwannabecool/impl/UserService.java
@@ -3,5 +3,16 @@
  */
 package com.ifyouwannabecool.impl;
 
+import javax.ws.rs.GET;
+import javax.ws.rs.Path;
+import javax.ws.rs.Produces;
+
+@Path("/users")
+@Produces("text/plain")
 public class UserService {
+
+  @GET
+  public String get() {
+    return "hello, user";
+  }
 }
```

Both the `/admin/users` and the `/users` endpoints are documented as expected:

![image](https://user-images.githubusercontent.com/145838/73198593-78b9e980-40f0-11ea-93fd-8ff530b80d03.png)

**Comment by tiguchi** [comment]
I forgot to mention that I have a more problematic JAX-RS server configuration that keeps end-user-space endpoints separate from admin endpoints:

Here's an excerpt from my Spring `beans.xml`
```xml
<jaxrs:server id="api" address="/v1" basePackages="com.example.api.endpoints.v1">
</jaxrs:server>

<jaxrs:server id="admin" address="/admin" basePackages="com.example.api.endpoints.admin">
</jaxrs:server>
```

I also added the following Enunciate annotation to the `AdminUserService` class to prepend the correct base path:

```java
@ServiceContextRoot("/admin")
public class AdminUserService extends UserService {
    ...
```

I'm not 100% but maybe that causes the issue in my case? Or did I make a configuration mistake?

**Comment by stoicflame** [comment]
I'll take a closer look with the new information.

If you'd like to put together a patch or diff for the enunciate-sample project that illustrates the problem, that would expedite the debugging.

**Comment by stoicflame** [comment]
Picking this up again. 

I tried with different ServiceContextRoots and I still can't reproduce the problem. I also can't think of any config mistakes that would cause this.

I'm afraid I'm going to need some way to reproduce the issue before I can pursue this further. I'm happy to reopen when you can provide that to me.
