### ISSUE TITLE
Using with source / target version 9 and above?

### ISSUE THREAD

**Issue by stamfest** [stoicflame/enunciate#1002]
I seem to be unable to track down the "official" status of enunciate for post Java-1.8 source/target version. The documentation and my experiments seem to indicate that as of today (2020-01-26) only Java 1.8 is supported. 

BTW: I am using the enunciate-maven-plugin, version 2.12.1 with openjdk 11.

So the questions are:
* Is there support for Java 9 or above? 
* If no: are there any plans to support anything beyond 1.8? If yes: Any idea for an alternative docs generator?

**Comment by stoicflame** [comment]
If there are any problems with versions older than Java 8, I'd like to hear about those problems so we can get them fixed. I've seen it work with 8, 9, and 10.

**Comment by stamfest** [comment]
You got it the wrong way around: It worked using Java 11 for running enunciate. But it did not work when setting a source version greater than 8 in pom.xml.
However, your reaction got me thinking and I finally managed to track the issue down: JAVA_HOME was not set in the environment, javac from openjdk 11 was on the path but openjdk 8 was installed in parallel. This combination caused the enunciate plugin to somehow find tools.jar from JDK 8 - which then complained about the source version being to high. Setting JAVA_HOME to the proper openjdk 11 dir fixes the problem.
