### ISSUE TITLE
Markdown table formatting not working

### ISSUE THREAD

**Issue by tiguchi** [stoicflame/enunciate#1003]
# Problem

I'm trying to use Markdown formatting for tables using the vertical bar character `|` in the API documentation's description file

```xml
<description format="markdown" file="doc/intro.md"/>
```

## Example

```
| A | B | C |
| --- | --- | --- |
| 1 | 2 | 3
```
However, above Markdown is generated into the API documentation as is

# Expected Result

Documentation generator's Markdown feature should be able to generate HTML table from Markdown table:

| A | B | C |
| --- | --- | --- |
| 1 | 2 | 3

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
