### ISSUE TITLE
The value of @ServiceContextRoot does not appear on the html docs nor it is used by the swagger module

### ISSUE THREAD

**Issue by sortel64** [stoicflame/enunciate#1004]
This is a great product!  Thank you.

While working with it, I was able to set the context for each endpoint using the @ServiceContextRoot annotation, which differs due to the user of Karaf that makes each endpoint an individual CXF context.  Awesome!  However, the context prefix /cxf/<context> does not appear in the Enunciate generated web pages that I can see.  The calls to exercise the API does include it and works well.  It seems that a viewer of the documentation would want to know the full ReST URL (e.g. /cxf/security/sessions), not just the resource (e.g. /sessions) part.

Also, the Swagger module does not seem for read the @ServiceContextRoot value and so is completely incorrect on the generated swagger docs and swagger.json.  I see the configuration of the module lets you set a single value, but in my use case it would require it to be different for each endpoint hence applying the annotation.

Thank you for any help.

**Comment by stoicflame** [comment]
Okay, thanks for the report. I'll take a closer look; the `@ServiceContextRoot` annotation was probably not designed to handle this particular case.

**Comment by stoicflame** [comment]
At 9e813a0, I fixed the Swagger module to support a config attribute like the jax-rs module to include the context root.

Including the context root in the docs is going to take more time and I'm reluctant to do it because it was originally added to configure just the endpoint links and not the docs. I could add a config option, though.

**Comment by sortel64** [comment]
Thanks Ryan.  I appreciate it.  If I make changes to completely implement my particular use case (documentation that supports multiple endpoints) would you like me to fork?

**Comment by stoicflame** [comment]
Maybe? Honestly I'm having a hard time visualizing what you'd like to see. If the context root got added as a visible part of the docs would that be enough to meet your needs? Or are you asking for a lot more customization than what a general solution can provide?

**Comment by sortel64** [comment]
I think that if the context root were added to the documentation that would help a lot.  Without that a client using the docs would not know the actual URL for each endpoint.  Luckily the enunciate docs and underlying data model seems to grasp multiple endpoints (services), and displays them as a unit (groupBy=class).  Each of our endpoints are a separate annotated Java interface:

SecurityService.java
> @ServiceContextRoot("/cxf/security")
> @Path("security")
> interface SecurityService {
> @Path("sessions") @Get
> List<Session> getSessions();
> more methods...

MetricsService.java
> @ServiceContextRoot("/cxf/metrics")
> @Path("metrics") @Put
> interface MetricsService {
> @Path("metrics")
> void addMetric(Metric m);
> more methods...

Ideally, we would have just one enunciate link to point our clients to for all of our system's ReST documentation.  The only other thing missing from the enunciate docs for my use case, is an index on the left side to make it easy to find each endpoint (class).  I can try to mock this up if that helps.

Regarding swagger.  Adding the context root will also help there for the above reasoning.  I generally like the presentation of the enunciate docs better than swagger, but some clients want swagger, especially, the swagger.json file.  However, Swagger only seems to understand exactly one ReST endpoint.  So, my proposed modification would be to have it generate an overarching summery swagger page that lists each endpoint (URL, description) and a drill-down link to the individual swagger document (and swagger.json) for each.

The next wish list item is to write a plugin that generates typescript class definitions of all of the endpoint DTOs for my angular UI guys :-)

Thanks for your interest in my use case and patience.  I'm happy to help where I can.  Enunciate is awesome!

**Comment by stoicflame** [comment]
Okay. At 6304260 I fixed some configuration so you the path will be included in the docs. The same configuration will be needed in the Swagger module.

```xml
<enunciate>
  <modules>
    <docs includeApplicationPath="true"/>
    <swagger includeApplicationPath="true"/>
```

I'm happy to consider any future enhancements you make if you'd like to submit them as a pull request.

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
