### ISSUE TITLE
Global request header documentation

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#1005]
We're using `@RequestHeaders` and `@RequestHeader` to add HTTP headers to the documentation. This is very useful for API methods that specifically have custom headers.

However, we have headers that are global for the entire API. Is it possible to configure this somehow, so it's added like all the other annotated headers.

I don't want to add this annotation to all the API methods manually. :)

**Comment by stoicflame** [comment]
You can add `@RequestHeaders` at the class-level and also at the package-level. So you'll have to add it to each package, but that's a lot better than adding it to head individual method.

**Comment by anton-johansson** [comment]
Thanks a bunch, did this the trick. Its quite a few "duplicate" annotations, but far better than annotating each method!
