### ISSUE TITLE
Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.3.0:docs (default) on project Project_Rest: Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.3.0:docs failed: A required class was missing while executing com.webcohesion.enunciate:enunciate-maven-plugin:2.3.0:docs: javax/xml/bind/annotation/XmlType

### ISSUE THREAD

**Issue by muraray** [stoicflame/enunciate#1006]
Following build is failing any help is appreciated.

------------------------------------------------------------------------
Building Project_Rest 0.0.1-SNAPSHOT
------------------------------------------------------------------------

--- enunciate-maven-plugin:2.3.0:docs (default) @ Project_Rest ---
[ENUNCIATE] Using enunciate configuration at Updated\Updated\enunciate.xml
[INFO] NETBEANS-ExecEvent:{"exc":
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 2.670 s
Finished at: 2020-01-30T12:04:22+08:00
Final Memory: 15M/57M
------------------------------------------------------------------------
Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.3.0:docs (default) on project Project_Rest: Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.3.0:docs failed: A required class was missing while executing com.webcohesion.enunciate:enunciate-maven-plugin:2.3.0:docs: javax/xml/bind/annotation/XmlType
-----------------------------------------------------
realm =    plugin>com.webcohesion.enunciate:enunciate-maven-plugin:2.3.0
strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
urls[0] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-maven-plugin/2.3.0/enunciate-maven-plugin-2.3.0.jar
urls[1] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-slim-maven-plugin/2.3.0/enunciate-slim-maven-plugin-2.3.0.jar
urls[2] = file:/C:/Users/cody/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.4/enforcer-api-1.4.jar
urls[3] = file:/C:/Users/cody/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar
urls[4] = file:/C:/Users/cody/.m2/repository/org/apache/maven/plugins/maven-install-plugin/2.5.2/maven-install-plugin-2.5.2.jar
urls[5] = file:/C:/Users/cody/.m2/repository/backport-util-concurrent/backport-util-concurrent/3.1/backport-util-concurrent-3.1.jar
urls[6] = file:/C:/Users/cody/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
urls[7] = file:/C:/Users/cody/.m2/repository/org/apache/maven/shared/maven-shared-utils/0.4/maven-shared-utils-0.4.jar
urls[8] = file:/C:/Users/cody/.m2/repository/com/google/code/findbugs/jsr305/2.0.1/jsr305-2.0.1.jar
urls[9] = file:/C:/Users/cody/.m2/repository/org/apache/maven/plugins/maven-deploy-plugin/2.8.2/maven-deploy-plugin-2.8.2.jar
urls[10] = file:/C:/Users/cody/.m2/repository/org/apache/maven/shared/maven-filtering/1.3/maven-filtering-1.3.jar
urls[11] = file:/C:/Users/cody/.m2/repository/org/slf4j/slf4j-jdk14/1.7.5/slf4j-jdk14-1.7.5.jar
urls[12] = file:/C:/Users/cody/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.5/jcl-over-slf4j-1.7.5.jar
urls[13] = file:/C:/Users/cody/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.2.1/maven-reporting-api-2.2.1.jar
urls[14] = file:/C:/Users/cody/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.1/doxia-sink-api-1.1.jar
urls[15] = file:/C:/Users/cody/.m2/repository/org/apache/maven/doxia/doxia-logging-api/1.1/doxia-logging-api-1.1.jar
urls[16] = file:/C:/Users/cody/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar
urls[17] = file:/C:/Users/cody/.m2/repository/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
urls[18] = file:/C:/Users/cody/.m2/repository/org/sonatype/plexus/plexus-sec-dispatcher/1.3/plexus-sec-dispatcher-1.3.jar
urls[19] = file:/C:/Users/cody/.m2/repository/org/sonatype/plexus/plexus-cipher/1.4/plexus-cipher-1.4.jar
urls[20] = file:/C:/Users/cody/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.4/plexus-build-api-0.0.4.jar
urls[21] = file:/C:/Users/cody/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
urls[22] = file:/C:/Users/cody/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.22/plexus-interpolation-1.22.jar
urls[23] = file:/C:/Users/cody/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
urls[24] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-core/2.3.0/enunciate-core-2.3.0.jar
urls[25] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-core-annotations/2.3.0/enunciate-core-annotations-2.3.0.jar
urls[26] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-javac-support/2.3.0/enunciate-javac-support-2.3.0.jar
urls[27] = file:/C:/Users/cody/.m2/repository/commons-configuration/commons-configuration/1.10/commons-configuration-1.10.jar
urls[28] = file:/C:/Users/cody/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
urls[29] = file:/C:/Users/cody/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
urls[30] = file:/C:/Users/cody/.m2/repository/io/reactivex/rxjava/1.0.9/rxjava-1.0.9.jar
urls[31] = file:/C:/Users/cody/.m2/repository/org/jgrapht/jgrapht-core/0.9.1/jgrapht-core-0.9.1.jar
urls[32] = file:/C:/Users/cody/.m2/repository/org/reflections/reflections/0.9.9/reflections-0.9.9.jar
urls[33] = file:/C:/Users/cody/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar
urls[34] = file:/C:/Users/cody/.m2/repository/org/javassist/javassist/3.18.2-GA/javassist-3.18.2-GA.jar
urls[35] = file:/C:/Users/cody/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar
urls[36] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-top/2.3.0/enunciate-top-2.3.0.jar
urls[37] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-jaxb/2.3.0/enunciate-jaxb-2.3.0.jar
urls[38] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-jackson/2.3.0/enunciate-jackson-2.3.0.jar
urls[39] = file:/C:/Users/cody/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.5.3/jackson-databind-2.5.3.jar
urls[40] = file:/C:/Users/cody/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.5.3/jackson-annotations-2.5.3.jar
urls[41] = file:/C:/Users/cody/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.5.3/jackson-core-2.5.3.jar
urls[42] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-jackson1/2.3.0/enunciate-jackson1-2.3.0.jar
urls[43] = file:/C:/Users/cody/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.9.13/jackson-jaxrs-1.9.13.jar
urls[44] = file:/C:/Users/cody/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar
urls[45] = file:/C:/Users/cody/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
urls[46] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-jaxrs/2.3.0/enunciate-jaxrs-2.3.0.jar
urls[47] = file:/C:/Users/cody/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar
urls[48] = file:/C:/Users/cody/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
urls[49] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-jaxws/2.3.0/enunciate-jaxws-2.3.0.jar
urls[50] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-docs/2.3.0/enunciate-docs-2.3.0.jar
urls[51] = file:/C:/Users/cody/.m2/repository/org/freemarker/freemarker/2.3.22/freemarker-2.3.22.jar
urls[52] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-idl/2.3.0/enunciate-idl-2.3.0.jar
urls[53] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-java-xml-client/2.3.0/enunciate-java-xml-client-2.3.0.jar
urls[54] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-java-json-client/2.3.0/enunciate-java-json-client-2.3.0.jar
urls[55] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-csharp-xml-client/2.3.0/enunciate-csharp-xml-client-2.3.0.jar
urls[56] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-c-xml-client/2.3.0/enunciate-c-xml-client-2.3.0.jar
urls[57] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-obj-c-xml-client/2.3.0/enunciate-obj-c-xml-client-2.3.0.jar
urls[58] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-php-xml-client/2.3.0/enunciate-php-xml-client-2.3.0.jar
urls[59] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-php-json-client/2.3.0/enunciate-php-json-client-2.3.0.jar
urls[60] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-ruby-json-client/2.3.0/enunciate-ruby-json-client-2.3.0.jar
urls[61] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-gwt-json-overlay/2.3.0/enunciate-gwt-json-overlay-2.3.0.jar
urls[62] = file:/C:/Users/cody/.m2/repository/com/google/gwt/gwt-user/2.7.0/gwt-user-2.7.0.jar
urls[63] = file:/C:/Users/cody/.m2/repository/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA.jar
urls[64] = file:/C:/Users/cody/.m2/repository/javax/validation/validation-api/1.0.0.GA/validation-api-1.0.0.GA-sources.jar
urls[65] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-spring-web/2.3.0/enunciate-spring-web-2.3.0.jar
urls[66] = file:/C:/Users/cody/.m2/repository/org/springframework/spring-web/4.2.2.RELEASE/spring-web-4.2.2.RELEASE.jar
urls[67] = file:/C:/Users/cody/.m2/repository/org/springframework/spring-context/4.2.2.RELEASE/spring-context-4.2.2.RELEASE.jar
urls[68] = file:/C:/Users/cody/.m2/repository/com/webcohesion/enunciate/enunciate-swagger/2.3.0/enunciate-swagger-2.3.0.jar
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

-----------------------------------------------------: javax.xml.bind.annotation.XmlType
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by stoicflame** [comment]
Please add JAXB to your dependencies.

```xml
      <dependency>
        <groupId>javax.xml.bind</groupId>
        <artifactId>jaxb-api</artifactId>
        <version>2.3.1</version>
      </dependency>
```
