### ISSUE TITLE
Stream return types shown as "StreamOfTypename" with no additional info

### ISSUE THREAD

**Issue by tiguchi** [stoicflame/enunciate#1008]
My API uses Java streams for returning collections of objects, instead of list collections. Those streams get serialized into regular JSON arrays of objects:

```java
/**
 * Searches existing user groups that are either public or visible to the request user.
 *
 * @param search  Optional search phrase filter by group name.
 * @param fields  Optional selected fields for filtering result.
 * @param orderBy Optional field names to order by.
 * @param page    Page number (default = 1)
 * @param limit   Items per page (default = 30).
 *
 * @return List of matching user groups.
 */
@GET
@Produces(MediaType.APPLICATION_JSON)
public Stream<UserGroup> searchGroups(@QueryParam(PARAM_SEARCH) String search,
                                      @QueryParam(PARAM_FIELDS) @DefaultValue(DEFAULT_FIELDS) SelectedFields fields,
                                      @QueryParam(PARAM_ORDER_BY) @DefaultValue("+name")
                                      @ValidOrderByFields(forType = UserGroup.class) OrderByFields orderBy,
                                      @QueryParam(PARAM_PAGE) @DefaultValue(DEFAULT_PAGE) long page,
                                      @QueryParam(PARAM_LIMIT) @DefaultValue(DEFAULT_LIMIT)
                                      @ValidPaginationLimit short limit) {
    final Stream<UserGroup> resultStream = ... // Run a query that returns a stream of user groups
    return resultStream;
}
```

Enunciate turns that into the following documentation though:

![Screenshot_20200212_080653](https://user-images.githubusercontent.com/6569525/74354090-b3b65100-4d6f-11ea-954a-4f9ac277fe2a.png)

## Problem

`StreamOfUserGroup` does not contain any information about the `UserGroup` type, no link to UserGroup and the generated examples are empty.

## Question

Is it possible to use the `@TypeHint` annotation in order to turn `Stream<UserGroup>` into `List<UserGroup>` (I couldn't figure out how)? Or is there a hidden configuration option that would turn all streams into "lists of type"?

**Comment by stoicflame** [comment]
Enunciate just doesn't have support for `Stream<T>` yet.

You can use `@TypeHint(UserGroup[].class)` as a workaround for now.

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
