### ISSUE TITLE
Swagger  format for LocalDate, LocalDateTime und OffsetDateTime not set

### ISSUE THREAD

**Issue by mnisius** [stoicflame/enunciate#1009]
Hi, 

so I have this class: 
```java
@Value.Immutable
@JsonDeserialize(as= ImmutableDateTypes.class)
public interface DateTypes {
  LocalDate getLocalDate();
  LocalDateTime getLocaldateTime();
  OffsetDateTime getOffSetDateTime();
}
```
I expected the follwing swagger spec: 
```json
"properties": {
        "localDate": {
          "readOnly": false,
          "description": "The value of the localDate attribute",
          "type": "string",
          "format": "date"
        },
        "localdateTime": {
          "readOnly": false,
          "description": "The value of the localdateTime attribute",
          "type": "string",
           "format": "date-time"
        },
        "offSetDateTime": {
          "readOnly": false,
          "description": "The value of the offSetDateTime attribute",
          "type": "string",
           "format": "date-time"
        }
      },
```
But this is what I got.
```json
"properties": {
        "localDate": {
          "readOnly": false,
          "description": "The value of the localDate attribute",
          "type": "string"
        },
        "localdateTime": {
          "readOnly": false,
          "description": "The value of the localdateTime attribute",
          "type": "string"
        },
        "offSetDateTime": {
          "readOnly": false,
          "description": "The value of the offSetDateTime attribute",
          "type": "integer",
          "format": "int32"
        }
      },
```
I can't generate Java Clients form this swagger.json because all Date Types are simple Strings. 

There was a similiar issue wich is marked as fixed. https://github.com/stoicflame/enunciate/issues/970
But I have no clue what I have to do in my application to get the correct result. 
Could you please explain it to me? (And also change the default in a new Version)?

**Comment by stoicflame** [comment]
I'll track this as an enhancement request for now.

**Comment by mnisius** [comment]
Thank you very much. 

I would also really appreciate it if you could explain a little bit to what you implemented here https://github.com/stoicflame/enunciate/issues/970. and how it helps with this problem.

**Comment by stoicflame** [comment]
In #970 we added support for the `dateFormat` parameter on the `jackson` module configuration. This will set `"format" : "date"` on the swagger configuration for *all* types of dates. There's no way to set e.g. "date" for `LocalDate` and "date-time" for `LocalDateTime`.

**Comment by mnisius** [comment]
Thanks for clarifiing. 

What do you think would be the best solution to this issue? Automatically detecting the correct format from the java types or some sort of annotation that let the user set the swagger format? 

I'm asking because there are more offiial formats but the spec also allows any value in this field.

https://swagger.io/docs/specification/data-models/data-types/
(search for: "String Formats")

**Comment by stoicflame** [comment]
I'm thinking probably some custom annotation that allows the user to set the format.

**Comment by stoicflame** [comment]
At 7c78e03 see new [`@JsonStringFormat`](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#cwemjsonjsonstringformat) annotation and [`@jsonStringFormat`](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#jsonstringformat-javadoc-tag) JavaDoc tag.

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
