### ISSUE TITLE
Documentation generation using Metro

### ISSUE THREAD

**Issue by russellhoff** [stoicflame/enunciate#101]
I've developed some web services using metro implementation of JAX-WS. Enunciate has a maven cxf plugin, but I wonder whether I'd be able to generate documentation with maven for my web services. I also find difficult to learn how to configure the enunciate.xml file for several intentions (jax-ws, jax-rs, cxf, metro......)

**Comment by stoicflame** [comment]
The default Enunciate plugin should work with Metro (a.k.a. "JAX-WS RI").
