### ISSUE TITLE
Custom example on DataType level

### ISSUE THREAD

**Issue by utchibutchi** [stoicflame/enunciate#1011]
Hi, I'm currently migrating some java projects from swagger-annotations to enunciate and get into some problems. We have a data type class with a complex field:

`private List<Map<SomeEnumType, Map<String, String>>> fieldName;`

I tried and searched a lot and didn't get @DocumentationExample to work properly. I know this is ugly json by design but we have to be compatible to a legacy api.

Is there a way to define the whole generated example output on class level for such cases for data types? In the resource class I used @requestExample and @responseExample for the rest entry points. If not, could this be an idea for a feature in a following version?

**Comment by stoicflame** [comment]
I'm not sure I understand the request yet. Are you saying this doesn't work?

```java
/**
 * @documentationExample [{"enum" : { "string" : "string" } }]
 */
private List<Map<SomeEnumType, Map<String, String>>> fieldName;
```

**Comment by utchibutchi** [comment]
No, it doesn't, maybe it is because of the values containing dots... Here what I get with different tries:
```
@DocumentationExample("[{'foo1' : { 'foo2.foo3[*].foo4': 'foo5' } }]")
private List<Map<ModalRelationConditionType, Map<String, String>>> bar;
	
  "bar" : [ {
    "[{'foo1'" : { },
    "property2" : { }
  }, {
    "[{'foo1'" : { },
    "property2" : { }
  } ]
```
```
@DocumentationExample("[{\"foo1\" : { \"foo2.foo3[*].foo4\": \"foo5\" } }]")
private List<Map<ModalRelationConditionType, Map<String, String>>> bar;
	
  "bar" : [ {
    "[{\"foo1\"" : { },
    "property2" : { }
  }, {
    "[{\"foo1\"" : { },
    "property2" : { }
  } ]
```

```
* 
* @documentationExample [{"fooA" : { "fooB.fooC[*].fooD": "fooE" } }]
*/
private List<Map<ModalRelationConditionType, Map<String, String>>> bar;
	
  "bar" : [ {
    "[{\"fooA\"" : { `},`
    "property2" : { }
  }, {
    "[{\"fooA\"" : { },
    "property2" : { }
  } ]
```

**Comment by stoicflame** [comment]
Okay, confirmed. The documentation example tags only currently apply when the members are "simple" values. We can look into enhancing this, but one of the questions will be about context. For example, if we're generated XML documentation for the class, then e.g. `@documentationExample [{"fooA" : { "fooB.fooC[*].fooD": "fooE" } }]` isn't going to make any sense.

**Comment by stoicflame** [comment]
At eab865fa4 see:

https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#jsonexampleoverride-javadoc-tag

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)

**Comment by epabst** [comment]
This isn't working for me.
Attempts:
```
  /**
   * @jsonExampleOverride {"primary": {"fullName": "Jacob Doe"}, "secondary": {"fullName": "Jake Doe"}, "tertiary": {"fullName": "Jake D"}}
   */
  public Map<NameFormType, NameForm> getNameForms() { return nameForms; }
```
produces
```
"nameForms" : {
    "property1" : {
      "fullName" : "John Albert Smith Jr."
    },
    "property2" : {
      "fullName" : "..."
    }
  }
```

```
  /**
   * @documentationExample {"primary": {"fullName": "Jacob Doe"}, "secondary": {"fullName": "Jake Doe"}, "tertiary": {"fullName": "Jake D"}}
   */
  public Map<NameFormType, NameForm> getNameForms() { return nameForms; }
```
produces
```
"nameForms" : {
    "property1" : {
      "fullName" : "John Albert Smith Jr."
    },
    "property2" : {
      "fullName" : "..."
    }
  }
```

```
  @DocumentationExample("{\"primary\": {\"fullName\": \"Jacob Doe\"}, \"secondary\": {\"fullName\": \"Jake Doe\"}, \"tertiary\": {\"fullName\": \"Jake D\"}}")
  public Map<NameFormType, NameForm> getNameForms() { return nameForms; }
```
produces
```
"nameForms" : {
    "{\"primary\":" : {
      "fullName" : "John Albert Smith Jr."
    },
    "property2" : {
      "fullName" : "..."
    }
  }
```

**Comment by stoicflame** [comment]
You didn't have the source files included; Enunciate couldn't see the JavaDocs.

**Comment by epabst** [comment]
> You didn't have the source files included; Enunciate couldn't see the JavaDocs.

It works great now using @jsonExampleOverride.
