### ISSUE TITLE
Support @label for enum values

### ISSUE THREAD

**Issue by cboehme** [stoicflame/enunciate#1014]
I have an endpoint which uses an enum type for one of its query parameters. The values of the query parameter are differently spelled than the enum values, though. In order to enable JAX-RS to map the query parameter values to the enum values, the enum type defines a `fromString(String)` method.

Now, when Enunciate generates the documentation it lists the enum values as constraints for the enum query parameter. However, because of my custom mapping these generated constraints list is, of course, not correct. 

As there is no way for Enunciate do automatically guess the correct values, I thought of specifing a `@label` Javadoc tag or annotation on each parameter value which states the query parameter value. This does not seem to be supported currently, though.  Hence, my request for adding support for `@label` on enum values:
```java
public enum {
    /**
     * @label value-for-query-param
     */
    MY_VALUE,

    @label("another-value-for-query-param")
    ANOTHER_VALUE
}
```

### Example-Endpoint

This is an example showing how I use enums in my Endpoint:
```java
@Path("/endpoint")
class Endpoint {
   @GET
   @Produces(APPLICATION_XML)
   String getData( @queryParam("chosen") MyEnum chosen) {
       // ...
    }
}

public enum MyEnum {
    MY_VALUE_A("my-value-a"),
    MY_VALUE_B("my-value-b");

   private String paramName;

   MyEnum(String paramName) {
       this.paramName = paramName;
    }

    public static MyEnum fromString(String string) {
        return stream(values())
                .filter(val -> val.paramName.equals(string)
                .findFirst()
                .orElseThrow(NoSuchElementException::new);
    }
}
```

**Comment by stoicflame** [comment]
Is there a reason that using `@javax.xml.bind.annotation.XmlEnumValue` won't work for your use case?

**Comment by cboehme** [comment]
In my actual code the enum values are indeed annotated with `@XmlEnumValue`. However, this only affects the documentation generated for the data types (which also use the enum) but not the documentation for the query parameter. And I think Enunciate behaviour is correct in doing this way because `@XmlEnumValue` is not taken into consideration by JAX-RS when mapping the query parameter string to the enum. That's why I suggested to use `@label` to define an alternate name for the query parameter.

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
