### ISSUE TITLE
@Ignore on enumeration values

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#1018]
I'd like to ignore a certain enumeration value from the documentation. I've tried the `@Ignore` annotation and also the `@ignore` JavaDoc, but it doesn't seem to work. Is it not supposed to work here? If so, is there an alternative way?

**Comment by stoicflame** [comment]
I'll track this as an enhancement request for now.

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
