### ISSUE TITLE
Improve private fields for lombok

### ISSUE THREAD

**Issue by garethmatthews-cc** [stoicflame/enunciate#1020]
If I have the @Data annotation on a @ResponseBody object > if the field is marked public then the field is picked up in the JSON section for the Pojo. If the field is private it is not picked up.

**Comment by stoicflame** [comment]
Please see [Property Visibility](https://github.com/stoicflame/enunciate/wiki/Property-Visibility).

**Comment by stoicflame** [comment]
Since I haven't heard back, I'm assuming the reference to property visibility was adequate to resolve the issue. I'm happy to reopen this issue if needed.
