### ISSUE TITLE
Support for `org.springframework.web.bind.annotation.RequestMapping#headers` for generated OpenAPI schema

### ISSUE THREAD

**Issue by soberich** [stoicflame/enunciate#1021]
Hi,

given
```java
    @PostMapping(value = "/whatever{pathExt:.*}", headers = { "REST_PASSWORD", "REST_USER" })
```
**Produces**
![image](https://user-images.githubusercontent.com/25544967/78900648-71f80d00-7a77-11ea-89b2-c6cf9fa0845b.png)

**Instead**
![image](https://user-images.githubusercontent.com/25544967/78900329-fc8c3c80-7a76-11ea-8c71-5b07343515d2.png)

(pathExt string(path) | pathExt is just below on the screenshot)

Version 2.12.1

**Comment by stoicflame** [comment]
This is for the OpenAPI module, yes? Doesn't this issue belong over at https://github.com/Jyskebank/enunciate-openapi?

**Comment by soberich** [comment]
@stoicflame no, it is not for OpenAPI module. It is Swagger module. Why did you thought it is for Jyksebank module? Something on screenshots?

**Comment by soberich** [comment]
@stoicflame probably it is more correct to say I it is spring-web module.

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
