### ISSUE TITLE
Lombok onX OnMethod issue

### ISSUE THREAD

**Issue by garethmatthews-cc** [stoicflame/enunciate#1024]
Related https://projectlombok.org/features/experimental/onX

Issue with enunciate and lombok and using the onMethod, tried both the java7 and java8 approaches and have the same issue

error

```
[WARNING] [ENUNCIATE] [javac]   @Setter(onMethod = @__({ @Truncate(length = 1) }))
[WARNING] [ENUNCIATE] [javac]                       ^
[WARNING] [ENUNCIATE] [javac]   symbol:   class __
```

**Comment by stoicflame** [comment]
Thanks for the report. I'm going to need to reproduce the problem. Can you attach a patch to the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) project that exposes it?

**Comment by garethmatthews-cc** [comment]
Wrote a sample but there is some underlying issues. Java 11 removed some old dependencies so wrote a fix for those and had to disable some features but this issue isn't reproducible on the sample branch. This could also close out https://github.com/stoicflame/enunciate/issues/911 

Java 11 has removed some deps btw https://www.oracle.com/technetwork/java/javase/11-relnote-issues-5012449.html#JDK-8190378

https://gist.github.com/garethmatthews-cc/abb61395f7ffaff8f9272bc6eecc71f8
