### ISSUE TITLE
How to generate `summary` tag explicitly?

### ISSUE THREAD

**Issue by volkanto** [stoicflame/enunciate#1025]
`summary` and `description` in `swagger.json` are generated from the entire description from javadoc. It seems Enunciate uses the first sentence as `summary` and the entire description as description `description`. Is there a way to define them explicitly? Or at least for `summary`?

```
/**
* This is summary. And also contains description.
*
* @param first the first parameter
* @param second the second parameter
*/
```

the result of this one is:

```
"summary" : "This is summary.",
"description" : "This is summary. And also contains description.",
```

**Comment by stoicflame** [comment]
You can use `@io.swagger.annotations.ApiOperation.value()`.
