### ISSUE TITLE
Add support for java.lang.Void response body

### ISSUE THREAD

**Issue by wahkara** [stoicflame/enunciate#1028]
public ResponseEntity<Void> delete() causes Enunciate to throw an exception.
public ResponseEntity<?> delete() works, but is considered bad practice by some code analyzers.

Output from maven build using Enunciate:
[DEBUG] [ENUNCIATE] Added org.familysearch.platform.users.rs.UserHistoryEntryResource as a Spring controller.
[DEBUG] [ENUNCIATE] Added java.lang.Void as a Jackson type definition.
[WARNING] [ENUNCIATE] Some source files were not found for the Java classes that define the Web service API.
[WARNING] [ENUNCIATE] Enunciate will be unable to find the documentation for the classes that are missing source files. (For details, rebuild with debug-level logging.)
[WARNING] [ENUNCIATE] In order for Enunciate to find the source files for API classes that are not being compiled in the current project, the source file must be on the Enunciate sourcepath and the class must be explicitly included in the Enunciate configuration.
[WARNING] [ENUNCIATE] For more information, see https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files
[DEBUG] [ENUNCIATE] Unable to find source file for java.lang.Void.
[DEBUG] [ENUNCIATE] Added java.lang.Void as a JAXB type definition.
[DEBUG] [ENUNCIATE] Unable to find source file for java.lang.Void.

**Comment by stoicflame** [comment]
Fix is available in 2.13.1.
