### ISSUE TITLE
Applying DocumentationExample on private fields, but not getters

### ISSUE THREAD

**Issue by AlexandrSokolov** [stoicflame/enunciate#1035]
To be able to use DocumentationExample annotation, it must be applied either to a getter or to a public field. It does not work when it is applied to a private field. 

(please correct me if I am wrong)

Is it possible to change this behavior?

1. It is a very specific requirement. Most annotations in java, if applied, do not care about visibility. For instance it is OK to add JPA/Hibernate annotation on private fields of entities. Keeping it in mind makes it a little bit more complicated and not consistent with other ones.
2. defining annotations on fields, makes code more clear (personal opinion)
3. Per each field it is possible to get its getter name from a naming convention and back, from a getter name - get the related field name. So this information can be extracted.

And the same question is about java comments. Now if I add them to the private field, they are not shown, but if I use them on getter they are displayed.

**Comment by stoicflame** [comment]
Enunciate uses the documentation the accessors used by the serialization framework. By default these are the public accessors, but you can use annotations to tell Jackson or JAXB to use different accessors. See `@com.fasterxml.jackson.annotation.JsonAutoDetect` and `@javax.xml.bind.annotation.XmlAccessorType` for example. Also any fields annotated with explicit serialization annotations (`@JsonProperty`) are used instead of their public accessors.

**Comment by AlexandrSokolov** [comment]
@stoicflame , thank you for an alternative approach providing.

I've found one issue with this. Jackson can be configured with `JsonAutoDetect` per class. And in this case, the `DocumentationExample` annotation is handled correctly, when it is applied on the private field.

At the same time that global configuration, applied via `ObjectMapper`, like:
```
    mapper.setVisibility(
      mapper
        .getSerializationConfig()
        .getDefaultVisibilityChecker()
        .withFieldVisibility(JsonAutoDetect.Visibility.ANY)
        .withGetterVisibility(JsonAutoDetect.Visibility.ANY));
```
affects jackson, but  enunciate does not know anything about this configuration. 

In general all serialization/deserialization features can be configured per class and globally. Can you add a possibility to configure the jackson module of enunciate in the same way? For instance by setting field visibility something like:
```
<enunciate ...
  <modules>
    <jackson
      dateFormat="string"
      disabled="false">
      <objectMapper>
        <serialization>
          <fieldVisibility>ANY</fieldVisibility>
        </serialization>
      </objectMapper>
    </jackson>
```
Otherwise now there is a misconsistency between jackson logic and  enunciate.

**Comment by stoicflame** [comment]
Already available:

```xml
<enunciate>
  <modules>
    <jackson>
      <accessor-visibility type="field" visibility="any">
```

**Comment by AlexandrSokolov** [comment]
Thank you, it helped
