### ISSUE TITLE
Using DocumentationExample with TypeHint

### ISSUE THREAD

**Issue by AlexandrSokolov** [stoicflame/enunciate#1036]
`@TypeHint(BigDecimal.class)` is not working when used as a part of `DocumentationExample` annotation. Probably I miss something, please correct me.  I define plain java interface and the related rest dto class in the following way:

```
public interface ExampleApi {
  BigDecimal getMoney();
  void setMoney(BigDecimal money);
}
public class ExampleDto implements ExampleApi {
  private BigDecimal money;
  @Override
  @DocumentationExample(value = MONEY_VALUE, type=@TypeHint(BigDecimal.class))
  public BigDecimal getMoney() {
    return money;
  }
  @Override
  public void setMoney(BigDecimal money) {
    this.money = money;
  }
}
```
In the generated documentation, for requests and response I see the `MONEY_VALUE` value. So it is applied. But when I open the `ExampleDto` class, the type of `money` field is marked as number, not as a `BigDecimal`.

Is it possible to use something other than number/string in this case?
Is it possible to show a warning, if not all attributes of an annotations are applied?
If it makes sense, can I configure it globally to use the current java data type, as a type hint? Now all my annotations look like:
```
@DocumentationExample(value=DATETIME_VALUE, type=@TypeHint(OffsetDateTime.class) )
@DocumentationExample(value=DATETIME_VALUE, type=@TypeHint(ZonedDateTime.class) )
@DocumentationExample(value=DATETIME_VALUE, type=@TypeHint(LocalDateTime.class) )
```

But the information about type could be extracted from a getter return value or from a field data type. Having this configuration, and the solution, described in [data type jackson configuration](https://github.com/stoicflame/enunciate/issues/1034#issuecomment-640631711) would help to avoid using explicit annotations at all.

**Comment by stoicflame** [comment]
Enunciate documents the _JSON_ for your API, not the Java. Since JSON doesn't have `BigDecimal` type, `number` is what will be documented.

**Comment by AlexandrSokolov** [comment]
@stoicflame , is it possible to show some warning about incorrect usage of enunciate, like typeHint could be only one of: String, Number, Date.

**Comment by stoicflame** [comment]
Apologies, but I'm going to decline that request. 

I'm comfortable with how clearly Enunciate is documented as an API documentation tool and not a Java documentation tool. I also think that Enunciate's output is already noisy enough. I also don't feel like it warrants a warning since it's working as designed.
