### ISSUE TITLE
Add a skip configuration option to enunciate-maven-plugin

### ISSUE THREAD

**Issue by AlexandrSokolov** [stoicflame/enunciate#1038]
Some maven plugins by nature offer a configuration to skip their execution. It might speed up a build process, when certain functionality is not required. Can you please consider to add this option.

PS: it is still possible to find a workaround for such plugins, like: [Skipping execution of Maven plugins that do not have a native skip option](https://www.igorkromin.net/index.php/2017/03/17/skipping-execution-of-maven-plugins-that-do-not-have-a-native-skip-option/)

But the ability to configure it, makes life easier:)

**Comment by stoicflame** [comment]
Global property `enunciate.skip` or property `skipEnunciate` in the plugin config.

**Comment by AlexandrSokolov** [comment]
@stoicflame , can you please update [maven config options](https://github.com/stoicflame/enunciate/wiki/Executables) page about this property? I google it but could not find the solution.

**Comment by stoicflame** [comment]
Yes. Done.
