### ISSUE TITLE
Upload documentation to Nexus

### ISSUE THREAD

**Issue by AlexandrSokolov** [stoicflame/enunciate#1039]
Probably this feature already exists, but I cannot find it. 

The solution I've found is based on docs generation, and copying the content of the docs folder to nexus via `wagon-webdav-jackrabbit` plugin. It works, but is there a less complicated version?

I would be great to have a `deploy` goal, which is by default triggered by the `deploy` Maven phase and is configured as:
```
  <configuration>
    <url>dav:https://nexus.dev.some.com/repository/documentation</url>
    <toDir>${project.groupId}/${project.artifactId}/${project.version}/rest-api</toDir>
  </configuration>
```

**Comment by stoicflame** [comment]
During its run, Enunciate generates a bunch of "artifacts". These artifacts can be deployed to Maven using the `deploy-artifact` goal of the Enunciate plugin. 

See:

https://github.com/stoicflame/enunciate/wiki/Maven-Client-Side-Artifacts
https://github.com/stoicflame/enunciate/wiki/Artifacts

So to deploy the documentation, e.g.:

```xml
  <plugin>
    <groupId>com.webcohesion.enunciate</groupId>
    <artifactId>enunciate-maven-plugin</artifactId>
    <version>${enunciate.version}</version>
    <executions>
      <execution>
        <id>assemble</id>
        <goals>
          <goal>assemble</goal>
        </goals>
        <configuration>
          ...
        </configuration>
      </execution>
      <execution>
        <id>install-and-deploy</id>
        <goals>
          <goal>install-artifact</goal>
          <goal>deploy-artifact</goal>
        </goals>
        <configuration>
          <enunciateArtifactId>docs</enunciateArtifactId>
        </configuration>
      </execution>
    </executions>
  </plugin>
```
