### ISSUE TITLE
Com.sun.mirror package is not present in java 8 tools.jar

### ISSUE THREAD

**Issue by ganeshnavdurge** [stoicflame/enunciate#1047]
We have developed some framework using java 6 and maven. Now we are upgrading that but when we change the dependency for tools.jar from java 6 to java 8 we are getting compilation error at AnnotationProcessorFactory because in java 8 tools.jar com.sun.mirror package is missing which was in java 6 tools.jar.

Could you please suggest the way so that i can continue upgrade with java 8 .

What i tried : 
I tried by adding apt-mirror-api-0.1.jar but that was not worked.

Please suggest. Thanks in advanced.

Thanks, 
Ganesh N.

**Comment by stoicflame** [comment]
Enunciate 1 does not work with Java 8. Please update to the latest version of Enunciate.

**Comment by ganeshnavdurge** [comment]
Thank you very much sir for the info , Could you please explain in details if possible that will really helpful to me.


What I need to do ?
1. Using JDK 8 
2.Yet I am not using Enunciate , could you please guide me how should i used that.

Thanks in advanced sir.

**Comment by stoicflame** [comment]
https://github.com/stoicflame/enunciate/wiki/Migration-Guide

**Comment by ganeshnavdurge** [comment]
Thanks Sir. I will try this.

Thank you very much for your time.
