### ISSUE TITLE
Primitive request parameter flagged as required despite default value setting

### ISSUE THREAD

**Issue by tiguchi** [stoicflame/enunciate#1049]
## Problem

An endpoint method such as follows:

```java
@GET
public List<User> searchUsers(@QueryParam("limit") @DefaultValue("30") int limit, ....)
```

...produces documentation where primitive type request parameters with default value are flagged as required:

## Actual Behavior

![required](https://user-images.githubusercontent.com/6569525/86964407-dd0abb80-c11a-11ea-9e7d-2d81bfeec6b6.png)

which appears a bit confusing and could lead to the assumption that these optional request parameters must be specified

## Expected Behavior

![required](https://user-images.githubusercontent.com/6569525/86964969-b13c0580-c11b-11ea-896a-3d215b182d28.png)

**Comment by stoicflame** [comment]
Fixed in `2.13.2`.
