### ISSUE TITLE
Replace deprecated Pegdown library

### ISSUE THREAD

**Issue by stevenschlansker** [stoicflame/enunciate#1051]
> Although still one of the most popular Markdown parsing libraries for the JVM, pegdown has reached its end of life.
> The project is essentially unmaintained with tickets piling up and crucial bugs not being fixed.

Currently, Enunciate suffers warnings such as:
```
WARNING: Illegal reflective access by org.parboiled.transform.AsmUtils (file:/Users/jan/.m2/repository/org/parboiled/parboiled-java/1.1.7/parboiled-java-1.1.7.jar) to method java.lang.ClassLoader.findLoadedClass(java.lang.String)
```

on any modern JDK.

Parboiled is used by the Pegdown project, which is deprecated.
Enunciate could adopt a more modern library, a quick search shows e.g. https://github.com/vsch/flexmark-java

**Comment by stoicflame** [comment]
Fixed in `2.13.2`.
