### ISSUE TITLE
Support @XmlTransient method annotation

### ISSUE THREAD

**Issue by pszemus** [stoicflame/enunciate#1052]
I have a sample class:
```
package com.example;

import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

@XmlRootElement
public class Person {
    
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @XmlTransient
    public boolean isMan() {
        return true;
    }

}
```

I don't want to serialize `isMan()` method so I annotated it as `@XmlTransient`.
Enunciate still generates documentation for that method:

![image](https://user-images.githubusercontent.com/13220781/88537843-98ce5500-d00e-11ea-90f9-78ea672d512b.png)

**Comment by pszemus** [comment]
Using [@com.webcohesion.enunciate.metadata.Ignore](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#cwemignore) annotation is a workaround for this.

**Comment by stoicflame** [comment]
You're looking at the JSON documentation. `@XmlTransient` is an XML annotation. For JSON use `@JsonIgnore`.
