### ISSUE TITLE
Swagger: Does the XML prefix(id) get translated in the enunciate XML config namespace?

### ISSUE THREAD

**Issue by mengjiann** [stoicflame/enunciate#1053]
Refer to the documentation from enunciate here: https://github.com/stoicflame/enunciate/wiki/Custom-Namespace-Prefixes#step-2-assign-the-prefix

Based on the example from the above link, the translated swagger doc should show something as below. But, it seems like the prefix is missing.

    xml:
            prefix: data
            namespace: http://api.mycompany.com/v1/data

Thanks.

**Comment by stoicflame** [comment]
I'll look into getting those prefixes applied.

**Comment by stoicflame** [comment]
Fixed in `2.13.2`.
