### ISSUE TITLE
enunciate-openapi

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#1055]
Hi @stoicflame 

It seems that Jyske Bank will be switching to OpenApi generators instead of Enunciate for new projects.

Because of this, it is hard for me to spend time on the enunciate-openapi project.

Are you interested in getting the project moved over to the stoicflame GitHub namespace?

Otherwise I will just make a note on the project that we stop making new builds of it.

Cheers,
Jesper

**Comment by stoicflame** [comment]
Sure, I'll take it on. I probably won't do much with it to enhance it, but I can put some effort into keeping it alive.

**Comment by jskovjyskebankdk** [comment]
You can see its history. Not much action after I got it fixed up for our internal needs.

But the changes that have been made, have been in the form of submissions. So that is cool. And something that would be sad to lose for those who keep using it.

You may want to change how you publish its artifacts; I manually uploaded artifacts to Maven Central, as we have no way to do it from our builder service. But I imagine you already have something automated for enunciate which could be translated to Gradle.

Thanks!
Jesper

**Comment by jskovjyskebankdk** [comment]
Hm. New plan.

I cannot transfer from an organization to other users.

Would it work for you to clone it?
I would then delete all but the README, leaving a note about the transfer.

**Comment by jskovjyskebankdk** [comment]
But then again... I can move it to my own personal namespace. And presumably from there to yours.
