### ISSUE TITLE
Is it possible to still document allowed values when serializing an enum to string?

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#1057]
I'm using enunciate to generate documentation for an API. Enunciate does not build the documentation from the actual domain model. Instead, documentation gets generated from a "shallow" domain model which simply implements the same interfaces as the actual domain model. I need to do it this way as I cannot modify (e.g. annotate) the real domain model in use.

This works well.

However, I've come across an small issue (which isn't really related to the "shallow" vs "real" domain model). The domain model uses enums for certain types of data. However, the API serializes these enums as strings. 

Is there a way to annotate an `enum`, in this case `getType()`, so that the data type becomes `string` but I somehow keep the list of enum values for documentation purposes? The consumers of the API needs to know the "allowed" values for for `getType()` / `setType()`. 

I could do this manually by adding a comment, but it isn't optimal as I'd have to maintain lists of values in comments scattered throughout the "shallow" domain model.

If I somehow could change data type from `MTReportDetailType` to `string` in the generated documentation, AND still link the `string` to a list of allowed values (just like for enums) then that would solve my problem.

Is this doable?

```
@XmlRootElement(name = "reportDetail")
public class MTReportDetail implements ReportDetail {

    public enum MTReportDetailType {
        ADV, APR, BRC, EXD
    }

    @Override
    @XmlElement(type = MTReportDetailType.class)
    public ReportDetailType getType() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    @XmlElement(type = MTReportDetailType.class)
    public void setType(ReportDetailType type) {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

   [...]
}
```

The generated documentation becomes :

![image](https://user-images.githubusercontent.com/1845372/92361224-61af9100-f0ee-11ea-89b1-a770e422ab14.png)

**Comment by stoicflame** [comment]
I'm afraid there's no way to do that.

Do you have an idea of what the annotation(s) would look like for this particular case?

**Comment by sbrattla** [comment]
@stoicflame maybe the most generic approach would be implement an `@AllowedValues(String[] values, AllowedValuesGenerator generator)` annotation which could be used on methods (in the data model)? With that annotation, an enum-like page could be generated also for non-enum data types.

The `values` argument could be taken as the definitive list of allowed/respected values for that method. Alternatively, the `generator` argument could take an implementation of `AllowedValuesGenerator` which could have a single method `getValues()` that would return an array of e.g. `Value`. Either way, the list of values could then be used to generate an enum-like page outlining allowed/respected values.

This would improve documentation needs for primitive data types, and would also solve my use case as I could simply just annotate the method `getType` with `@XmlElement(type = String.class)` and use `@AllowedValues` to document the values. 

```
public class ReportDetailTypeGenerator implements AllowedValuesGenerator {
    @Override
    public Value[] getValues() {
        List<Value> pairs = new ArrayList();
        for (ReportDetailType reportDetail : ReportDetailType.values()) {
            pairs.add(new PrimitiveValue(reportDetail.toString(), reportDetail.toString()));
        }
            
        return pairs.toArray(new Value[pairs.size()]);
    }
}

@XmlRootElement(name = "reportDetail")
public class MTReportDetail implements ReportDetail {

    @Override
    @XmlElement(type = String.class)
    @AllowedValues(generator = ReportDetailTypeGenerator.class)
    public ReportDetailType getType() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    @XmlElement(type = String.class)
    @AllowedValues(generator = ReportDetailTypeGenerator.class)
    public void setType(ReportDetailType type) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

}
```

**Comment by sbrattla** [comment]
Sorry for my slow response.

Yes, so I realize my suggestion was not very well thought through.

How about an `@AllowedValues` (or `@DocumentationValues` ?) annotation, somewhat similar to `@DocumentationExample`. The `@AllowedValues` annotation would list / document all values from the provided enum the same way as if the type of `@XmlElement` was an enum.

```
public enum SampleValue {
    Active, Inactive;
}
```

```
@XmlRootElement(name = "report")
public class Report {

    @Override
    @XmlElement(type = String.class)
    @AllowedValues(from = SampleValue.class)
    public Status getStatus() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    @XmlElement(type = String.class)
    @AllowedValues(from = SampleValue.class)
    public Status setStatus() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
```

**Comment by sbrattla** [comment]
@stoicflame I keep coming back to this issue, so I'd like to hear if the following would be technically possible with e.g. a `@AllowedValues` annotation?

```
    @Override
    @XmlElement(type = String.class)
    @AllowedValues(class = MTReportDetailType.class) // class must be an enum
    public ReportDetailType getType() {
        throw new UnsupportedOperationException("This is only a documentation implementation"); 
    }
```

In this case, enunciate would document `getType()` as a `String`, and :  

1. Either list all `enum` values in the **description** column

...or...

3. Link to a details section on the same page which lists available `String` options

![enun](https://user-images.githubusercontent.com/1845372/195296016-ae17d882-1566-4c6c-9027-8830ff5edf52.png)

**Comment by stoicflame** [comment]
Seems like something that could be done. I'll keep it as an enhancement request and look closer when I get some time.

**Comment by stoicflame** [comment]
Started looking at this.

I'm afraid the suggestion to link to a "details section" is probably too complex to be done in a reasonable time frame.

As for listing the possible values, Enunciate has support for the `@javax.validation.constraints.Pattern` annotation that can be used as [suggested by this SO question](https://stackoverflow.com/questions/4922655/javax-validation-to-validate-list-of-values). Would that be acceptable for this use case?

**Comment by sbrattla** [comment]
@stoicflame sorry for being slow to respond on this one.

I absolutely understand if this is something that will take too long. I think managing this manually is probably what I'll do going forward. The `@Pattern` annotation also seems to require that I update the allowed values manually, so I'm sure it'll be an improvement over the current approach.

Thanks for looking into it though :-)

**Comment by stoicflame** [comment]
Found some time to implement the `@AllowedValues` annotation for 2.15.0.  Here's a diff I applied to [enunciate-sample](https://github.com/stoicflame/enunciate-sample) that illustrates how to use it:

```diff
diff --git a/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/PersonsEndpoint.java b/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/PersonsEndpoint.java
index 4b5ba9e..a35e587 100644
--- a/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/PersonsEndpoint.java
+++ b/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/PersonsEndpoint.java
@@ -13,8 +13,10 @@ import javax.ws.rs.POST;
 import javax.ws.rs.Path;
 import javax.ws.rs.PathParam;
 import javax.ws.rs.Produces;
+import javax.ws.rs.QueryParam;
 import javax.ws.rs.core.MediaType;
 
+import com.webcohesion.enunciate.metadata.AllowedValues;
 import com.webcohesion.enunciate.sample.model.Person;
 import com.webcohesion.enunciate.sample.ws.PermissionDeniedException;
 
@@ -35,7 +37,7 @@ public class PersonsEndpoint {
   }
 
   @POST
-  public void createPerson(Person person) {
+  public void createPerson(Person person, @QueryParam("thing") @AllowedValues(Things.class) String thing) {
     // ... store the persona in the db...
   }
 
diff --git a/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/Things.java b/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/Things.java
index 949fe7a..7a39361 100644
--- a/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/Things.java
+++ b/enunciate-sample-webapp/src/main/java/com/webcohesion/enunciate/sample/rs/Things.java
@@ -1,4 +1,10 @@
 /*
  * © 2023 by Intellectual Reserve, Inc. All rights reserved.
- */package com.webcohesion.enunciate.sample.rs;public enum Things {
+ */
+package com.webcohesion.enunciate.sample.rs;
+
+public enum Things {
+  
+  THING1,
+  thing2
 }
```

**Comment by sbrattla** [comment]
That is awesome @stoicflame - thank you so much for taking the time to look into this. I will (hopefully) try this out very soon!
