### ISSUE TITLE
swagger includeApplicationPath="true" results in no methods 

### ISSUE THREAD

**Issue by sortel64** [stoicflame/enunciate#1060]
Related to #1004 
Sorry it has taken me so long to give this a go but I'm sure you understand.  Man, we are so close on this!

Adding includeApplicationPath="true" on the 'docs' module works well!  However, when I added it to the swagger module, it results in no methods under the endpoint.  I don't see any issues during the maven build.

I included my enunciate.xml and two screen snapshots, one with 'false' and the other with 'true'.  I hope that helps.  I can also provide you with a short Java example if that helps as well.

Thanks again for working this.  It is so helpful!

![includeApplicationPath-false](https://user-images.githubusercontent.com/6325451/95582714-05030700-0a09-11eb-891e-94384bf65f7b.jpg)
![includeApplicationPath-true](https://user-images.githubusercontent.com/6325451/95582721-08968e00-0a09-11eb-809f-7aab61a8fa82.jpg)

[enunciate.xml.txt](https://github.com/stoicflame/enunciate/files/5354860/enunciate.xml.txt)

**Comment by sortel64** [comment]
This is v2.13.2

**Comment by sortel64** [comment]
In the swagger.json file, it looks like all of the paths are correct in that they are prefix with the application path, but are empty.

**Comment by sortel64** [comment]
I did some debugging this weekend and I believe that I have found the issue.  I have included a git diff (below) of a proposed fix that I believe matches your coding pattern.  I tested it with both 'includeApplicationPath' set to true and false.  I hope this helps.

```
diff --git a/swagger/src/main/java/com/webcohesion/enunciate/modules/swagger/SwaggerModule.java b/swagger/src/main/java/com/webcohesion/enunciate/modules/swagger/SwaggerModule.java
index 1626bfede..00494d7d1 100644
--- a/swagger/src/main/java/com/webcohesion/enunciate/modules/swagger/SwaggerModule.java
+++ b/swagger/src/main/java/com/webcohesion/enunciate/modules/swagger/SwaggerModule.java
@@ -200,7 +200,11 @@ public class SwaggerModule extends BasicGeneratingModule implements ApiFeaturePr
             }
 
             for (Resource resource : resourceGroup.getResources()) {
-              if (path.equals(resource.getPath())) {
+              String resourcePath = resource.getPath();
+              if (includeApplicationPath && !StringUtils.isEmpty(resourcePath)) {
+                resourcePath = "/" + resourceGroup.getRelativeContextPath() + resourcePath;
+              }
+              if (path.equals(resourcePath)) {
                 swaggerResource.getMethods().addAll(resource.getMethods());
               }
             }
```

BTW: The documentation for both the docs and swagger modules incorrectly call the configuration parameter 'includeApplicationRoot' instead of 'includeApplicationPath'.

**Comment by stoicflame** [comment]
Thanks for the look.

That patch seems to be based off an old version. Can you confirm you're looking at the latest?

**Comment by sortel64** [comment]
Hi Ryan,

No problem.  Glad to help.

I based on a git pull from master.  I just checked and it still says that I am up to date.

My pom indicates 2.14.0.SNAPSHOT as well.  Is there another branch that I should be looking at?

Thanks,

Scott


[sortel@centos8-vm enunciate]$ git branch
* master
[sortel@centos8-vm enunciate]$ git pull
Already up to date.
[sortel@centos8-vm enunciate]$ git diff
diff --git a/swagger/src/main/java/com/webcohesion/enunciate/modules/swagger/SwaggerModule.java b/swagger/src/main/java/com/webcohesion/enunciate/modules/swagger/SwaggerModule.java
index 1626bfede..00494d7d1 100644
--- a/swagger/src/main/java/com/webcohesion/enunciate/modules/swagger/SwaggerModule.java
+++ b/swagger/src/main/java/com/webcohesion/enunciate/modules/swagger/SwaggerModule.java
@@ -200,7 +200,11 @@ public class SwaggerModule extends BasicGeneratingModule implements ApiFeaturePr
             }
 
             for (Resource resource : resourceGroup.getResources()) {
-              if (path.equals(resource.getPath())) {
+              String resourcePath = resource.getPath();
+              if (includeApplicationPath && !StringUtils.isEmpty(resourcePath)) {
+                resourcePath = "/" + resourceGroup.getRelativeContextPath() + resourcePath;
+              }
+              if (path.equals(resourcePath)) {
                 swaggerResource.getMethods().addAll(resource.getMethods());
               }
             }

**Comment by stoicflame** [comment]
Applied at 9b6215116.

**Comment by sortel64** [comment]
Hi Ryan,  Do you have a projected release date for 2.14 yet?

**Comment by stoicflame** [comment]
I'll try to get something cut within the next two weeks or so.

**Comment by stoicflame** [comment]
`2.13.3` is now available.

**Comment by sortel64** [comment]
Thank you!
