### ISSUE TITLE
A class annotated with @JsonValue, @JsonCreator seems to produce an incorrect JSON example

### ISSUE THREAD

**Issue by sortel64** [stoicflame/enunciate#1065]
I have a class that is annotated with @JsonValue,@JsonCreator that does not seem to be producing the correct example JSON in Enunciate.  I searched the tickets for an answer before submitting.  I may be doing something wrong, so I'll lay it all out.  I sincerely appreciate your help.

The simplified class:
```
public class URN {
   private final String nid;
   private final String nss;

   @JsonCreator
   public URN(String str) {
      // parse string and set nid and nss
      this.nid = "nid";
      this.nss = "nss";
   }

   @Override
   @JsonValue
   public String toString() {
      return("urn:"+nid+":"+nss);
   }
}
```

Enunciate xml:
```
<jackson>
   <accessor-visibility visibility="any" type="field"/>
   <accessor-visibility visibility="none" type="getter"/>
   <accessor-visibility visibility="none" type="setter"/>		
</jackson>
```

The Enunciate result example when used as a member of an object:
```
{
  "grantId" : "...",
  "roleId" : "...",
  "subjectURN" : { },
  "grantDt" : 12345
}
```

I expected:
```
{
  "grantId" : "...",
  "roleId" : "...",
  "subjectURN" : "...",
  "grantDt" : 12345
}
```

When I marshal it to JSON using Jackson2 with the following object mapper settings:
```
mapper.setVisibility(mapper.getVisibilityChecker()
  .withFieldVisibility(Visibility.ANY)
  .withGetterVisibility(Visibility.NONE)
  .withSetterVisibility(Visibility.NONE));
```

I get the expected result (confirmed when I hit the ReST endpoint):
```
{
  "grantId" : "g1",
  "roleId" : "r1",
  "subjectURN" : "urn:nid:nss",
  "grantDt" : 1605101960479
}
```

**Comment by stoicflame** [comment]
Thanks for the report. I'll take a look.

**Comment by stoicflame** [comment]
Started work on this. Made some progress, but the `toString()` value method messed up the java client which expects a getter of some kind.

[project diff](https://github.com/stoicflame/enunciate/files/6111755/1067.diff.txt)

[sample diff](https://github.com/stoicflame/enunciate/files/6111756/1067-sample.diff.txt)
