### ISSUE TITLE
Upgrade jquery to newest version (currently 3.5.1)

### ISSUE THREAD

**Issue by RasmusOlesen** [stoicflame/enunciate#1067]
Jquery 1.12.2 has multiple cves:
https://nvd.nist.gov/vuln/search/results?adv_search=true&query=cpe%3A2.3%3Aa%3Ajquery%3Ajquery%3A1.12.2%3A*%3A*%3A*%3A*%3A*%3A*%3A*

Last upgrade was done in
https://github.com/stoicflame/enunciate/issues/1010

**Comment by stoicflame** [comment]
Fixed in `2.13.3`.
