### ISSUE TITLE
DocumentationExample doesn't work when the field is also annotation with a type serializer

### ISSUE THREAD

**Issue by pfranza** [stoicflame/enunciate#1070]
When a Jackson bean accessor is annotated with both a Jackson serializer annotation, and an enunciate DocumentationExample.  The DocumentationExample is not rendered

     /* This case does render the example code into the enunciate docs */
    @DocumentationExample("2021-02-01T14:57:01.695Z")
    public DateTime getDate() {
	    return startDate;
    }

    /* This case does not render the example code into the enunciate docs */
    @JsonSerialize(using = JacksonDateISO8601Serializer.class)
    @DocumentationExample("2021-02-01T14:57:01.695Z")
    public DateTime getDate() {
    	    return startDate;
    }

In this case I need to us a custom serializer/deserializer for the field to make a very specific implementation.

I am using enunciate `2.13.2`

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
The Jackson `JsonSerializer` definition doesn't provide Enunciate any way to determine the _type_ that the object is being serialized to, so Enunciate has to assume a generic object which can't associate with a documentation example.

Workaround is to provide Enunciate with a `@TypeHint`:

```java
    @com.webcohesion.enunciate.metadata.rs.TypeHint(String.class) 
    @JsonSerialize(using = JacksonDateISO8601Serializer.class)
    @DocumentationExample("2021-02-01T14:57:01.695Z")
    public DateTime getDate() {
    	    return startDate;
    }
```
