### ISSUE TITLE
primitive types always appear as required in data type

### ISSUE THREAD

**Issue by brianblasko** [stoicflame/enunciate#1075]
I have a simple POJO that is used as input to an API.  When the documentation is generated, any primitive(in my case a boolean) they appear as required in the Usage column.

This is not always the case, as it will default to false and I also have logic to overrride.

Is there a way to override the usage using some annotation?

**Comment by stoicflame** [comment]
The only way right now is to box the primitive (i.e. change from `boolean` to `java.lang.Boolean`). That's probably a bug that needs to be fixed, though.

I'll use this issue to track that work.

**Comment by stoicflame** [comment]
Trying to figure out the best way to fix this. The `required` constraint is used to describe both read and write use cases. It _is_ true that if the property is primitive, it will always be written out by the serializer.

Would an adequate fix be that if the field is annotated with `@javax.annotation.Nullable` then we'll assume the primitive is not required?

**Comment by brianblasko** [comment]
I am not sure I understand how you can use @Nullable on a primitive, does not seem correct to me.   Given that int will default to 0 and boolean will default to false, could you just make those assumptions in the generation.   It is partially correct that the value is not required but it is also true that the value will default.   That has a different connotation then nullable.

How about a new javadoc annotation that I could use to override if you don't want to make the assumptions.

**Comment by stoicflame** [comment]
At d8b55b8a8 I allowed consideration of the default value when determining whether to specify `required`.

So annotating the element with e.g. `@JsonProperty(defaultValue="false")` will drop the "required" in the constraints.

**Comment by stoicflame** [comment]
Released in `2.14.0`.
