### ISSUE TITLE
Specify operationId

### ISSUE THREAD

**Issue by amberream** [stoicflame/enunciate#1081]
When the swagger docs are generated a field called "operationId" is filled in with the java method name - and numbers are appended if there are multiple methods with the same name.  In previous versions it  was something much longer and messier, but in the latest version it appears to match the method name... 
It would be nice if there was an annotation so I could create custom operationIds. i.e. instead of myMethod, I'd like to specify something like "My Method".

Also, there seems to be a bug in the current naming logic since I occasionally end up with two identical operationIds.  For example I have a class that has an overloaded method, "get".  Both of these end up with operationId "get5".

@GET
public SignatureFieldsModel get()

@GET
@Path("{fieldName}")
public SignatureFieldModel get(@PathParam("fieldName") String fieldName)

**Comment by stoicflame** [comment]
Acknowledged as an enhancement request.

What are your thoughts about the best way to explicitly specify the `operationId`? Enunciate annotation? Or maybe supporting the `@io.swagger.annotations.ApiOperation.nickname()` annotation value? Or config file?

**Comment by amberream** [comment]
I think an Enunciate annotation would be easiest (from a documentation perspective).
P.S. I probably should have made this two separate tasks, but wanted to make sure you saw the mention of the duplicate ids in the original description.

**Comment by xs2vikasyadav** [comment]
@stoicflame I too have the problem of duplicate operation ids. Here is an example of two methods which get the same operation id "greet" - 
    @Path("/to")
    @POST
    @Produces({ MediaType.TEXT_PLAIN })
    public String greet(@FormParam("name") String name, @FormParam("age") int age)

    @Path("/to/person")
    @POST
    @Consumes({ MediaType.APPLICATION_JSON })
    @Produces({ MediaType.TEXT_PLAIN })
    public String greet(Person person)
