### ISSUE TITLE
Cannot generate Jackson client with generics

### ISSUE THREAD

**Issue by marcban** [stoicflame/enunciate#1083]
(on 2.13.3)
In a dependant project, I defined a class with generics 
```public class StringServiceResult extends ServiceResult<String> {...```

ServiceResult is defined in this project as 
```
@JsonInclude(Include.NON_NULL)
public class ServiceResult<T> extends StatusResult {
	private T result = null;
}
```

I use this class in another project, Enunciate finds the correct classes but 
the generated client contains 
```
@JsonInclude( JsonInclude.Include.NON_NULL )
@JsonIgnoreProperties( ignoreUnknown = true )
public class StringServiceResult implements java.io.Serializable {
  @JsonIgnore
  private T _result;
```

which doesn't compile because of the 'T' that is not replaced with 'String'

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by marcban** [comment]
It seems to be only when using <String> generics, as I have other classes with generics in the same project that seems ok in the client

**Comment by stoicflame** [comment]
Finally getting around to looking at this, but I'm struggling to reproduce the problem. I'm wondering if there are other annotations or something not included in the description.

Here's a diff I applied to [enunciate-sample](https://github.com/stoicflame/enunciate-sample):

```
diff --git a/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Name.java b/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Name.java
index 186bd44..76e9109 100644
--- a/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Name.java
+++ b/enunciate-sample-model/src/main/java/com/webcohesion/enunciate/sample/model/Name.java
@@ -25,6 +25,7 @@ public class Name {
 
   private String givenName;
   private String surname;
+  private StringServiceResult result;
 
   /**
    * The given name.
@@ -61,4 +62,12 @@ public class Name {
   public void setSurname(String surname) {
     this.surname = surname;
   }
+
+  public StringServiceResult getResult() {
+    return result;
+  }
+
+  public void setResult(StringServiceResult result) {
+    this.result = result;
+  }
 }
```

Can you suggest anything that's different in your case?

**Comment by marcban** [comment]
Oh sorry @stoicflame I should have closed the ticket long ago...
It works now on my project but I don't even remember what I did to make it work !
I see in the history that I put the datatype-detection to "aggressive" and changed the source path detection, but I can't reproduce it now...

**Comment by matthew-pakulski** [comment]
I'm seeing this too, though a slightly different form.

I have a class:
```java
public interface InquiryTerm<T> extends Serializable {
    T getValue();
}
```
And it's "referenced from" here. Notice I'm using <?> instead of <T>:
```java
public class Inquiry {
    private Collection<InquiryTerm<?>> filterTerms;
}
```

When it generates the client for `InquiryTerm`, sometimes it compiles correctly, sometimes it does not - depending on if `InquiryTerm` was first detected from `public interface InquiryTerm<T>` or if it was detected when referenced from `Inquiry`'s `Collection<InquiryTerm<?>> filterTerms;` field. 

In the latter case, compiles `class InquiryTerm` incorrectly with missing `<T>`. 
```java
public class InquiryTerm implements java.io.Serializable {
    @JsonIgnore
    private ? _value;
}

Still searching for a workaround with this issue - going to experiment with forcing `InquiryTerm` to be detected first in the Jackson module by adding `@JsonSeeAlso`.
