### ISSUE TITLE
 enunciate 2.13.2 issue   with java 8

### ISSUE THREAD

**Issue by amrtham** [stoicflame/enunciate#1084]
i am using 2.13.2 and getting below issue

It's recommended that you customize the name of one of these types using the @XmlType annotation

 java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes.

below is my enunciate.xml
<?xml version="1.0"?>
<enunciate label="API"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.codehaus.org/schemas/enunciate-2.13.0.xsd">

        <modules>
                
                         <jaxb datatype-detection="aggressive" />
                    <jaxrs datatype-detection="aggressive"/>

        <jaxws datatype-detection="aggressive" />
  <jackson1 datatype-detection="aggressive"/>

    <jackson disabled="true"/> 
        </modules>

**Comment by stoicflame** [comment]
What's the source code on which the compile is failing?

**Comment by amrtham** [comment]
Which version do you recomned for java 8 
my earlier version was 1.26

**Comment by stoicflame** [comment]
The latest version (`2.13.3`) will work fine with Java 8.

**Comment by amrtham** [comment]
i have modified the xml as below and see below error
<enunciate label="OVM Web Services API"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.codehaus.org/schemas/enunciate-2.13.0.xsd">

        <modules>
                
                 <jackson disabled="true"/>
  <jaxb disabled="true"/>
    <jaxws disabled="true"/>


java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "resourceGroups"; see cause exception! The type of the containing value was: extended_hash+string (com.webcohesion.enunciate.modules.jaxrs.api.impl.JaxrsResourceApi wrapped into f.e.b.StringModel)

**Comment by stoicflame** [comment]
I'm afraid I still don't have enough visibility into the issue to be helpful. I'm going to need to have some way to reproduce the problem so I can see deeper into what's going on.

My best guess is that the classpath is messed up.

**Comment by amrtham** [comment]
i have verified and class path is actually having the Enunciate jars .

i see this 

Enabled modules: [docs, gwt-json-overlay, idl, jackson1, java-json-client, java-xml-client, javascript-client, jaxrs, spring-web, swagger]
Some source files were not found for the Java classes that define the Web service API.
Enunciate will be unable to find the documentation for the classes that are missing source files. (For details, rebuild with debug-level logging.)
In order for Enunciate to find the source files for API classes that are not being compiled in the current project, the source file must be on the Enunciate sourcepath and the class must be explicitly included in the Enunciate configuration.
For more information, see https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files
No JAXB XML data types: Java XML client will not be generated.


Can you please clarify me 


 <enunciate
      basedir="${javadoc.tmp.dir}"
      configFile="${basedir}/enunciate_config.xml"
      buildDir=""
      >
what is to be referred in  the buildDir  . is it the source of the files for what we need the docs to be generated.

**Comment by stoicflame** [comment]
`buildDir` is where you're telling Enunciate to write its output.

**Comment by amrtham** [comment]
earlier i was using   1.26.2 with java 7 and i defined the task as
<taskdef name="enunciate" classname="org.codehaus.enunciate.main.EnunciateTask">
Now i am using 2.13.2 with java 8 and i defined the task as
    <taskdef name="enunciate" classname="com.webcohesion.enunciate.EnunciateTask">


any issue

**Comment by amrtham** [comment]
please confirm if it is fine i will try with 2.13.3

**Comment by amrtham** [comment]
i tried with 2.13.3 and getting below error

java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes.

**Comment by stoicflame** [comment]
Please include the output of the compile failure. What's the source code failing to compile?

**Comment by amrtham** [comment]
[ENUNCIATE] Using enunciate configuration at /home/enu1.3/core/wls/management/build/enunciate_config.xml
Enabled modules: [docs, gwt-json-overlay, idl, jackson, jackson1, java-json-client, java-xml-client, javascript-client, jaxb, jaxrs, jaxws, spring-web, swagger]

Both Jackson 1 and Jackson 2 Enunciate modules are enabled.
This may cause duplicated and/or inconsistent JSON documentation.
It is recommended that you disable one of the modules by either
pruning your classpath of one of the versions of the Jackson
library, or by explicitly disabling one of the modules in the
Enunciate configuration file. For more information, see
https://github.com/stoicflame/enunciate/wiki/Two-JSON-Sections

Some source files were not found for the Java classes that define the Web service API.
Enunciate will be unable to find the documentation for the classes that are missing source files. (For details, rebuild with debug-level logging.)
In order for Enunciate to find the source files for API classes that are not being compiled in the current project, the source file must be on the Enunciate sourcepath and the class must be explicitly included in the Enunciate configuration.
For more information, see https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files
Unable to find source file for java.lang.Package.
Unable to find source file for com.oracle.xmlns.webservices.jaxws_databinding.XmlOneway.
Unable to find source file for com.oracle.xmlns.webservices.jaxws_databinding.XmlRequestWrapper.
[enunciate] /home/enu1.3/core/wls/management/build/tmp/java-json-client/src/java/lang/reflect/TypeVariable.java:22: error: illegal start of type
[enunciate]   private ? _genericDeclaration;
[enunciate]           ^
[enunciate] /home/enu1.3/core/wls/management/build/tmp/java-json-client/src/java/lang/reflect/TypeVariable.java:22: error: ';' expected
[enunciate]   private ? _genericDeclaration;
[enunciate]            ^
[enunciate] /home/enu1.3/core/wls/management/build/tmp/java-json-client/src/java/lang/reflect/TypeVariable.java:62: error: illegal start of type
[enunciate]   public ? getGenericDeclaration() {

**Comment by amrtham** [comment]
tried with 2.13.3  with below Enunciate config and getting the error
<?xml version="1.0"?>
<enunciate label="OVM Web Services API"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.codehaus.org/schemas/enunciate-2.13.3.xsd">

        <modules>
<java-json-client disabled="true" />    <jaxb disabled="true"/>
    <jaxws disabled="true"/>        
            <docs
               splashPackage="com.ovm.mgr.ws"
               title="Web Services API @version@"
               copyright="mytest" />
        </modules>

</enunciate>


 Enabled modules: [docs, gwt-json-overlay, idl, jackson, jackson1, java-xml-client, javascript-client, jaxrs, spring-web, swagger]

Both Jackson 1 and Jackson 2 Enunciate modules are enabled.
This may cause duplicated and/or inconsistent JSON documentation.
It is recommended that you disable one of the modules by either
pruning your classpath of one of the versions of the Jackson
library, or by explicitly disabling one of the modules in the
Enunciate configuration file. For more information, see
https://github.com/stoicflame/enunciate/wiki/Two-JSON-Sections

Some source files were not found for the Java classes that define the Web service API.
Enunciate will be unable to find the documentation for the classes that are missing source files. (For details, rebuild with debug-level logging.)
In order for Enunciate to find the source files for API classes that are not being compiled in the current project, the source file must be on the Enunciate sourcepath and the class must be explicitly included in the Enunciate configuration.
For more information, see https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files
Unable to find source file for java.lang.reflect.Field.
Unable to find source file for com.oracle.xmlns.webservices.jaxws_databinding.XmlFaultAction.
Unable to find source file for com.oracle.xmlns.webservices.jaxws_databinding.XmlServiceMode.
No JAXB XML data types: Java XML client will not be generated.

BUILD FAILED
/home/enu1.3/core/wls/management/build/build.xml:69: The following error occurred while executing this line:
/home/enu1.3/core/wls/management/build/javadoc.xml:189: The following error occurred while executing this line:
/home/enu1.3/core/wls/management/build/javadoc.xml:364: java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "resourceGroups"; see cause exception! The type of the containing value was: extended_hash+string (com.webcohesion.enunciate.modules.jaxrs.api.impl.JaxrsResourceApi wrapped into f.e.b.StringModel)

----
FTL stack trace ("~" means nesting-related):
        - Failed at: #list resourceApi.resourceGroups as r...  [in template "jar:file:/home/enu1.3/core/ovm-3.4.7-wls/management_tools/ThirdParty/lib/enunciate/enunciate-docs-2.13.3.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 238, column 9]
        ~ Reached through: #nested  [in template "jar:file:/home/enu1.3/core/wls/management_tools/ThirdParty/lib/enunciate/enunciate-docs-2.13.3.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 142, column 9]
        ~ Reached through: @boilerplate pagenav=pagenav  [in template "jar:file:/home/enu1.3/core/wls/management_tools/ThirdParty/lib/enunciate/enunciate-docs-2.13.3.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 193, column 3]
        - Reached through: @file name=indexPageName  [in template "jar:file:/home/enu1.3/core/wls/management_tools/ThirdParty/lib/enunciate/enunciate-docs-2.13.3.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 182, column 1]
----

Total time: 2 minutes 23 seconds

**Comment by amrtham** [comment]
Request you to help me with this issue.

**Comment by stoicflame** [comment]
The compile failure seems to be caused because Enunciate is attempting to document the `java.lang.reflect.TypeVariable` class as part of your API. I suspect you're trying to document classes that shouldn't be included in the API. You'll want to exclude those classes from the documentation. 

You can do this by looking through the output of `mvn -X` and noting all the messages that look like:

```
Added [class name] as a [IDL type].
```

Exclude any classes that shouldn't be part of your API.

The `resourceGroups` error is something I've never seen before, nor can I reproduce it locally. Again, my best guess is that you're building the Enunciate classpath incorrectly, perhaps referencing older jars.

**Comment by amrtham** [comment]
i have ensured and double checked that the enunciate class path is set to 2.13.3. Now it is unable to find jaxws_databinding

Unable to find source file for com.oracle.xmlns.webservices.jaxws_databinding.XmlHandlerChain.
Unable to find source file for com.oracle.xmlns.webservices.jaxws_databinding.XmlResponseWrapper.
Unable to find source file for com.oracle.xmlns.webservices.jaxws_databinding.XmlWebEndpoint.
[enunciate] /home/enu1.3/core/wls/management/build/tmp/java-xml-client/src/com/code/ovm/mgr/ws/impl/WsApiImpl.java:916: error: cannot find symbol
[enunciate]     return proxy.repositoryImportAssembly(repositoryId, url, proxy);
[enunciate]                 ^
[enunciate]   symbol:   method repositoryImportAssembly(Id<Repository>,String,String)
[enunciate]   location: variable proxy of type String
[enunciate] /home/enu1.3/core/ovm-3.4.7-wls/management/build/tmp/java-xml-clientsrc/com/code/ovm/mgr/ws/impl/WsApiImpl.java:926: error: cannot find symbol
[enunciate]     return proxy.repositoryImportVm(repositoryId, urls, proxy, createTemplate);
[enunciate]                 ^
[enunciate]   symbol:   method repositoryImportVm(Id<Repository>,List<String>,String,boolean)
[enunciate]   location: variable proxy of type String
[enunciate] /home/enu1.3/core/ovm-3.4.7-wls/management/build/tmp/java-xml-client/src/com/code/ovm/mgr/ws/impl/WsApiImpl.java:946: error: cannot find symbol
[enunciate]     return proxy.repositoryImportVirtualDisk(repositoryId, url, proxy, diskType);
[enunciate]                 ^
[enunciate]   symbol:   method repositoryImportVirtualDisk(Id<Repository>,String,String,DiskType)
[enunciate]   location: variable proxy of type String
[enunciate] Note: Some input files use or override a deprecated API.
[enunciate] Note: Recompile with -Xlint:deprecation for details.
[enunciate] 3 errors

BUILD FAILED
/home/enu1.3/core/wls/management/build/build.xml:69: The following error occurred while executing this line:
/home/enu1.3/core/wls/management/build/javadoc.xml:189: The following error occurred while executing this line:
/home/enu1.3/core/wls/management/build/javadoc.xml:366: java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: Compile failed of Java client-side classes.



Am i missing anything ?

**Comment by stoicflame** [comment]
Looks like you're making progress.

Now it's down to Enunciate generating bad client-side code, but I can't tell why. What does the `WsApi` class look like? The one with the `repositoryImportAssembly`, etc. methods?

**Comment by amrtham** [comment]
It is all having @XmlAccessorType ,@xmlType,@xmlElement

**Comment by stoicflame** [comment]
Can you share the source code for it?

**Comment by amrtham** [comment]
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "repositoryImportAssembly", propOrder = {
    "repositoryId",
    "url",
    "proxy"
})
public class RepositoryImportAssembly {
	//some setters and getters
}

**Comment by stoicflame** [comment]
Hmmm... still not enough for me to see what's going on.

Isn't there a class named `Ws` or `WsApi` or something like that with methods named `repositoryImportAssembly`, `repositoryImportVm`, and `repositoryImportVirtualDisk`?

**Comment by amrtham** [comment]
Yes there is a class Wsapi  and wsapiImpl in which  all these methods are referred
 as

  @WebMethod
    @WebResult(name = "job")
    Job repositoryImportAssembly(@WebParam(name = "repositoryId") @XmlElement(required = true) Id<Repository> repositoryId,
                                 @WebParam(name = "url") @XmlElement(required = true) String url,
                                 @WebParam(name = "proxy") String proxy) throws WsException;

**Comment by stoicflame** [comment]
Okay, I see now.

Tracking the bug at #1085.

Current workaround is to rename the parameter. (I.e. don't have a parameter named proxy).

**Comment by amrtham** [comment]
ok. Can you just brief me about the issue little and let me know when it can be fixed

**Comment by stoicflame** [comment]
I don't have a schedule for when it will get fixed. You're welcome to watch the issue to get updates.

**Comment by amrtham** [comment]
I tried with the rename and  it worked fine .
 i have one more issue 
eaaalier i  have some link documents generated with the naming convention as ns0-<>  and now they are generated with json-<> .How to change them
And soap documentation is not generated

**Comment by stoicflame** [comment]
> i have some link documents generated with the naming convention as ns0-<> and now they are generated with json-<> .How to change them

You can't. It's hard-coded for now.

>  And soap documentation is not generated.

Yeah, because you disabled the `jaxws` module in your config.

**Comment by amrtham** [comment]
no i have not disabled 

<?xml version="1.0"?>
<enunciate label="Web Services API"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.codehaus.org/schemas/enunciate-2.13.3.xsd">

    <modules>
              
            <docs
               splashPackage="com.mgr.ws"
               title=" Web Services API @version@"
               copyright="mydoc" />
    <docs includeApplicationPath="true"/>       </modules>

</enunciate>

**Comment by stoicflame** [comment]
Your [previous comment](https://github.com/stoicflame/enunciate/issues/1084#issuecomment-802107540) had it disabled.

When you run with debug output, you should see messages like "Added [classname] as a JAX-WS endpoint interface." Can you confirm?
