### ISSUE TITLE
application base path not showing up with request example

### ISSUE THREAD

**Issue by PhilippauxAdrien** [stoicflame/enunciate#1091]
Hi, 

I'm using the spring-web module and want to add an application base path using the following configuration : 

```
<spring-web disabled="false" groupBy="path" >
  <application path="/api" />
</spring-web>
```

But the /api is not showing up in the generated documentation. 

Here is an example of generated path : GET /apps/version

**Comment by stoicflame** [comment]
Please configure the docs module to include the application path, too:

```xml
  <docs includeApplicationPath="true"/>
```

**Comment by PhilippauxAdrien** [comment]
Thanks base path is now visible in the resource path but not in the JSON example : 
`GET /apps/version
Content-Type: */*
Accept: application/json

                
...`

Is there is way to put it there too ?
