### ISSUE TITLE
Values for enunciateArtifactId

### ISSUE THREAD

**Issue by leforthomas** [stoicflame/enunciate#1093]
This is more a question than a bug, maybe the documentation needs improving. I cannot find the list of possible values for the parameter enunciateArtifactId in the maven plugin? I want jackson generated and tried various ids but none of them seems to work.

This is what I currently have but would like to change to jackson, if at all possible?

```xml                    <execution>
                        <id>install-and-deploy</id>
                        <goals>
                            <!-- the "install-artifact" goal does a local install of the artifact -->
                            <goal>install-artifact</goal>
                        </goals>
                        <configuration>
                            <!-- the "enunciateArtifactId" element is the only thing required.
                                 other options reflect those of the maven deploy plugin, and include
                                 options to set the groupId, artifactId, version, classifier, pomFile
                                 etc. However, suitable defaults will be supplied as necessary -->
                            <enunciateArtifactId>java.json.client.library</enunciateArtifactId>
                        </configuration>
                    </execution>
```

**Comment by stoicflame** [comment]
Here's the list of artifacts:

https://github.com/stoicflame/enunciate/wiki/Artifacts

The `java.json.client.library` _is_ the library that uses Jackson for JSON serialization. So I think you have it right.

**Comment by leforthomas** [comment]
Great, thanks a lot. I understand better how this works now.

So I use the java json client artifact id. The only thing is all the jackson annotations disappear in my jar. Typically I have the date formatting and that gets removed which causes problems when using it in my client. Any idea?

**Comment by stoicflame** [comment]
It's not a direct copy of the annotations.

If you'd like to open up another issue with details about what's expected, we'll track it as an enhancement.
