### ISSUE TITLE
Swagger.json ignores @Produces annotation when spring-boot application is used

### ISSUE THREAD

**Issue by BarysDrahunou** [stoicflame/enunciate#1096]
Hello. I use spring-boot application and modules from `enunciate.xml` file are:
```
    <modules disabledByDefault="true">
        <jaxrs disabled="false"/>
        <jackson disabled="false"/>
        <spring-web disabled="false"/>
        <docs disabled="false"/>
        <swagger disabled="false"/>
    </modules>
```
Also I have multiple methods, which should produce `text/plain` MediaType, every method have `@Produces` annotation with requred type. However, swagger.json is constantly generating  `"produces": ["application/json"]` for any provided MediaType. 

At the same time I have no problem with other application which uses spring but not spring-boot, modules are also the same exclude `spring-web`-module and swagger.json is generating as it's expected.

PS. Please, take a look at #1043 issue, I left a comment about the same problem, and this problem happens only when I run spring-boot application. There is no duplication when I use spring-core app. Perhaps these guys also used spring-boot but you tried to reproduce this issue on non-spring-boot app.

**Comment by stoicflame** [comment]
Finally picking up this issue, but I'm going to need some help reproducing the issue on my end. Can you provide a patch or a minimal sample project that I can run on my end that exposes the issue?

**Comment by BarysDrahunou** [comment]
Hello! Here's a link to a small test project. https://github.com/BarysDrahunou/enunciate-produces-annotation.

Small update. If we use produces **[Within @GetMapping annotation](https://github.com/BarysDrahunou/enunciate-produces-annotation/blob/master/src/main/java/com/example/springboot/RestStatusController.java#L12)**, it works and both swagger UI and enunciate UI use TEXT_PLAIN as Content-Type. On the other hand, **[This @Produces annotation](https://github.com/BarysDrahunou/enunciate-produces-annotation/blob/master/src/main/java/com/example/springboot/RestStatusController.java#L13)** doesn't work and Content-Type is always \*/\* for both UI.

![image](https://user-images.githubusercontent.com/68003105/159952822-dd80e058-6d26-4f30-bdb9-f00b6a748154.png)
![image](https://user-images.githubusercontent.com/68003105/159953277-e2f73639-499b-47f9-b711-30020d5c9623.png)

**Comment by stoicflame** [comment]
Awesome, thanks.

**Comment by stoicflame** [comment]
Okay, so I can't find anywhere that spring-boot says it supports the `@Produces` annotation in it's API; the only method I can see that it supports is the `produces()` value in the `@GetMapping` annotation.

Is there are particular reason you want to use the `@Produces` annotation in a spring-boot app?

**Comment by BarysDrahunou** [comment]
No, no any particular reason, it appeared to be used for a long time on a project even before we started using enunciate. We're quite Ok with using `produces()` in `@GetMapping`. Probably the issue may be closed, thank you!
