### ISSUE TITLE
Duplicate properties generated with @JsonProperty and @Setter annotations used at the same time

### ISSUE THREAD

**Issue by rkondrashov** [stoicflame/enunciate#1098]
I'd like to re-raise issues #909 and #1043 with some additional details.

**Bug description**

If the jackson annotation `@JsonProperty` and lombok annotation `@Setter` used at the same time
```
@Setter
public class LombokExample {
    @JsonProperty("my_property")
    private String myProperty;
}
```
the property `my_property` appears twice in the properties-section of the generated documentation, the example-section still looks correct.

![image](https://user-images.githubusercontent.com/12693997/126514201-105ae012-8073-43ca-9f13-b1735592284b.png)

If you take a look at the delomboked class, you can see that lombok adds the `@JsonProperty` annotation to the setter as well and it seems to be a problem. 
```
public class LombokExample {
    @JsonProperty("my_property")
    private String myProperty;

    @JsonProperty("my_property")
    @java.lang.SuppressWarnings("all")
    public void setMyProperty(final String myProperty) {
        this.myProperty = myProperty;
    }
}
```

This issue could be also reproduced without lombok adding the `@JsonProperty` annotation to the setter.
```
public class PlainExample {
    @JsonProperty("my_property")
    private String myProperty;

    @JsonProperty("my_property")
    public void setMyProperty(String myProperty) {
        this.myProperty = myProperty;
    }
}
```

![image](https://user-images.githubusercontent.com/12693997/126517304-2cadad5b-7dea-4a6a-839e-926cade5e786.png)

I've expected that the generation could be controlled using settings `<accessor-visibility type="field" visibility="none"/>` or `<accessor-visibility type="setter" visibility="none"/>`, but these have no effect.

**Steps to reproduce**

I've created a sample project to reproduce this issue [https://github.com/rkondrashov/enunciate-duplicate-property](https://github.com/rkondrashov/enunciate-duplicate-property).

1. Clone the project.
2. Execute `mvn clean generate-resources`.
3. Take a look at the generated documentation for `LombokExample` and `PlainExample` data types under `target/docs/apidocs/`.

**Environment**
AdoptOpenJDK 11.0.11
Apache Maven 3.8.1
enunciate-slim-maven-plugin 2.13.3
lombok 1.18.20

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by dnash21e** [comment]
This is also happening for me generating swagger docs.  The property appears twice in swagger.json and causes a Parser error because of a "duplicated mapping key"
```
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

@Data
public class PortraitLinksDto {
  @JsonProperty("_links")
  private Map<String, LinkDto> links = new HashMap<>();

}
```
produces
```
"PortraitLinksDto": {
      "type": "object",
      "title": "PortraitLinksDto",
      "properties": {
        "_links": {
          "readOnly": false,
          "description": "",
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/LinkDto"
          }
        },
        "_links": {
          "readOnly": false,
          "description": "",
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/LinkDto"
          }
        }
      },
      "example": {
        "_links": {
          "property1": {
            "rel": "...",
            "href": "..."
          },
          "property2": {
            "rel": "...",
            "href": "..."
          }
        }
      },
      "description": ""
    },
```
enunciate-maven-plugin 2.13.3
lombok 1.18.20

**Comment by stoicflame** [comment]
f822dc708

Thanks again for the example project illustrating the problem.
