### ISSUE TITLE
The relative path in the HTML has an extra "../" in the glyphicon-new-window icon link

### ISSUE THREAD

**Issue by epabst** [stoicflame/enunciate#1099]
This is not an issue if the app is at the top-level path, but my application has a context path, so it fails to work.

See https://beta.familysearch.org/service/africa/experience/resource_InstantTreeController.html#resource_InstantTreeController_readInstantTree_GET

The link is showing up as:
```html
<a href="../instant-tree/{instantTreeId}" class="glyphicon glyphicon-new-window" target="_blank"></a>
```
That resolves to https://beta.familysearch.org/service/africa/instant-tree/

It should be: 
```html
<a href="instant-tree/{instantTreeId}" class="glyphicon glyphicon-new-window" target="_blank"></a>
```
which would resolve to https://beta.familysearch.org/service/africa/experience/instant-tree/

Here is the configuration in the pom.xml:
```xml
          <execution>
            <goals>
              <goal>docs</goal>
            </goals>
            <configuration>
              <!-- the directory where to put the docs -->
              <docsDir>${project.build.directory}/docs</docsDir>
            </configuration>
          </execution>
```

**Comment by stoicflame** [comment]
Okay, thanks for the report.
