### ISSUE TITLE
could not scan ... with scanner EnunciateReflectionsScanner

### ISSUE THREAD

**Issue by KoenDG** [stoicflame/enunciate#1101]
This seems to be the same as https://github.com/stoicflame/enunciate/issues/973

This is running under Ubuntu 16.04, x64, using JDK11, running gradle 6.8, with a command like this:

`./gradlew --no-daemon --no-build-cache war`

Using enuniciate 2.13.3

The build is ultimately successful, but produces a lot of spam DEBUG statements because of this.

Stacktrace:
```
17:10:18.832 [Execution worker for ':' Thread 4] DEBUG org.reflections.Reflections - could not scan file META-INF/maven/org.joda/joda-convert/pom.properties in url file:~.gradle/caches/modules-2/files-2.1/org.joda/joda-convert/1.7/57c2432e54dc40f871f55295c676b22672713602/joda-convert-1.7.jar with scanner EnunciateReflectionsScanner
org.reflections.ReflectionsException: could not create class object from file META-INF/maven/org.joda/joda-convert/pom.properties
        at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:32)
        at com.webcohesion.enunciate.EnunciateReflectionsScanner.scan(EnunciateReflectionsScanner.java:91)
        at org.reflections.Reflections.scan(Reflections.java:253)
```

According to the stacktrace, the execution path passes here: https://github.com/stoicflame/enunciate/blob/4cffb49ad8e37be394f2f01f388eba44ec8f5711/core/src/main/java/com/webcohesion/enunciate/EnunciateReflectionsScanner.java#L85-L93

On line 91.

The task itself first prints:

```
> Task :enunciate
16:00:00.215 [Execution worker for ':' Thread 6] DEBUG org.apache.commons.configuration.ConfigurationUtils - ConfigurationUtils.locate(): base is null, name is null
16:00:00.379 [Execution worker for ':' Thread 6] DEBUG org.reflections.Reflections - going to scan these urls:
file:~/.gradle/caches/modules-2/files-2.1/com.tdunning/t-digest/3.1/451ed219688aed5821a789428fd5e10426d11312/t-digest-3.1.jar
file:~/.gradle/caches/modules-2/files-2.1/com.rabbitmq/amqp-client/5.10.0/4de351467a13b8ca4eb7e8023032f9f964a21796/amqp-client-5.10.0.jar
file:~/.gradle/caches/modules-2/files-2.1/org.codehaus.jackson/jackson-core-asl/1.9.13/3c304d70f42f832e0a86d45bd437f692129299a4/jackson-core-asl-1.9.13.jar
file:~/.gradle/caches/modules-2/files-2.1/org.apache.pdfbox/pdfbox/2.0.16/5dce5e41fc472d02800df5ef060a1f3a58c36902/pdfbox-2.0.16.jar
...
```

The `build.gradle` file has the following setup for enunciate:

```
ext {
    enunciateVersion = "2.13.3"
}

warDep "org.reflections:reflections:0.9.12"

compile "com.webcohesion.enunciate:enunciate-core-annotations:$enunciateVersion"

ant.properties['enunciate.dependencies'] = (configurations.enunciate).asPath
ant.importBuild 'documentation/build.xml'
```

And the `documentation/build.xml` file is as follows(include and exclude removed):

```
<?xml version="1.0" encoding="UTF-8"?>

<project default="enunciate">

    <target name="enunciate" depends="compileJava">
        <path id="enunciate.classpath">
            <pathelement path="${enunciate.dependencies}"/>
        </path>

        <!--define the task...-->
        <taskdef name="enunciate" classname="com.webcohesion.enunciate.EnunciateTask">
            <classpath refid="enunciate.classpath"/>
        </taskdef>

        <delete dir="reference"/>
        <mkdir dir="reference"/>
        <enunciate basedir="../src/main" buildDir="reference" configFile="enunciate.xml">
            <include name="..."/>
            ...
            <exclude name="..."/>
            <classpath refid="enunciate.classpath"/>
            <export artifactId="docs" destination="reference"/>
        </enunciate>
        <copy todir="reference/css">
            <fileset dir="css"/>
        </copy>
    </target>
</project>
```

All includes and excludes are java files in our src dir.

No idea why this is happening. Looking in to how to suppress these messages. Ideally these messages should not appear at all.

I'm making the ticket mainly in case some clarification has come up in recent years.

**Comment by KoenDG** [comment]
After building and deploying, the documentation itself seems fine, working properly.

That said, the debug spam generates just under 100MB of text.

**Comment by stoicflame** [comment]
So is the bug here about the debug output? Because wouldn't that be a configuration/environment issue? The Enunciate project doesn't actually control that debug output, so do you have any suggested solutions?

**Comment by KoenDG** [comment]
Whatever the cause, the only thing that really happened is a version upgrade from 2.9.1 to 2.13.3, as I'm trying to move a project from jdk8 to jdk11.

**Comment by KoenDG** [comment]
Just going to note, over the past few days I've been trying several ways of changing the log level, or suppressing the logger altogether, but nothing appears to be working.

**Comment by stoicflame** [comment]
Updated Reflections API at ccec3eebf9c5cc8e75fc892696f182384f139cce and Java 11 at 26cbca6228bea6a3404daa21af73bda6b4f7d071
