### ISSUE TITLE
Jackson(2) Module Fails compile

### ISSUE THREAD

**Issue by conbon** [stoicflame/enunciate#1104]
Prior to changes in the codebase, jackson1 module had been disabled and enunciate was running correctly with jackson(2) module.

When running ```enunciate:docs``` with jackson module enabled now, I am seeing a strange issue potentially regarding generics.

A lot of messages like below are printed during the run and not only include third-party libraries but also classes from our own codebase -
```
/home/projectX/target/enunciate/java-json-client/src/java/io/Serializable.java:15: error: interface expected here
public class Serializable implements java.io.Serializable {
                                            ^
```
```
/home/projectX/target/enunciate/java-json-client/src/java/io/Serializable.java:15: error: cyclic inheritance involving Serializable
public class Serializable implements java.io.Serializable {
```
```
/home/projectX/target/enunciate/java-json-client/src/com/fasterxml/jackson/databind/ser/std/StdSerializer.java:15: error: Object is not public in java.lang; cannot be accessed from outside package
public class StdSerializer<T extends java.lang.Object> extends com.fasterxml.jackson.databind.JsonSerializer<T> {
```

```
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.11.1:docs (default-cli) on project svn-ms-replicator: Compile failed of Java JSON client-side classes.: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]
```

Current enunciate version: 2.11.1 (I have gone through all versions up to latest and issue persists)

**Comment by stoicflame** [comment]
Okay, thanks for the report.

**Comment by stoicflame** [comment]
Finally picking up this issue. I think what's going on is that one of your API classes is referencing `java.io.Serializable` and Enunciate is trying to figure out how that thing gets (de)serialized to/from JSON. 

At 80384e81d I've added support for `java.io.Serializable` as a known type, but there might still be a lingering issue around what classes Enunciate is pulling in to document.
