### ISSUE TITLE
Is there a way to override "multivalued" for a @QueryParam?

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#1105]
I've got this resource :

```
public Response search(
            @QueryParam("distribute") Boolean distribute,
            @QueryParam("statuses") Status[] status) throws Exception {}
```

The `statuses` parameter is just a single parameter which holds a comma separated list of statuses. I've then got a `ParamConverter` which converts the `statuses` query parameter into an array of `Status` instances.

This works fine, but enunciate interprets this as if the `statuses` parameter is multivalued. My understanding of a multivalued query parameter is that it can be provided multiple times, such as  `search?status=Active&status=Inactive&status=Pending`. Such a usage would not work in this case, and result in just one of the statuses being used.

![image](https://user-images.githubusercontent.com/1845372/134141192-8cd7092c-9e0b-45d4-bf14-8b4e69ae59bf.png)

Is there a way to flag a query parameter as not multivalued?

**Comment by stoicflame** [comment]
Unfortunately, accommodating custom converters is one of Enunciate's weak points.

The only option you have available for now is to change the type of the parameter from `Status[]` to `String` and do the conversion _in_ the method.

We can add a feature, though. Do you have a suggestion on the mechanism you'd like to use to specify "not multivalued"?

**Comment by sbrattla** [comment]
I don't really have a good suggestion for how this could be done. What I find somewhat confusing is that a `multivalued` can mean both : 

1. a query parameter which can occur only once, and which accepts e.g. comma separated values 
    `@QueryParam("ids") UUID[] ids`

2. a query parameter which can occur multiple times, and which accepts single values
    `@QueryParam("id") List<UUID> id`

From the above, only for the second example would Spring Boot / Jersey collect multiple `id` query parameters into a `List`. It does not do this for arrays. However, both examples would appear as `multivalued` in the documentation. Looking at the generated documentation then, it's hard to know which of the two above applies. 

I'd say that generally, I would prefer the second option above, but in some cases that can't be done. For instance, I've got a `sort` query parameter, which accepts an ordered list of fields to be sorted by : 

`sort=title:asc,number:desc`

In this case I cannot accept multiple `sort` query parameters - I would not be able to guarantee sorting.

Maybe this is something which should be solved by just mentioning this in the parameter description. The alternative would probably be yet another annotation such as `@Singular` (or similar) which would flag to enunciate that a parameter can just occur once - but I'd think the use case would be pretty rare?

**Comment by stoicflame** [comment]
The intent of the term "multivalued" is to describe use case \#2.

The comma-separated values shouldn't be described as "multivalued." So I'll take a look at how Spring and Jersey behave and make adjustments to the generated documentation.

**Comment by stoicflame** [comment]
Finally picking up this issue.

So all the documentation I've read and my own personal experience has said that Spring treats both arrays and lists the same―they're multivalued and multivalued parameters can be passed _either_ comma-separated _or_ multi-param instances. [Here's a good succinct summary](https://medium.com/@AADota/spring-passing-list-and-array-of-values-as-url-parameters-1ed9bbdf0cb2).

So I think it's still the right thing to mark these parameters as multivalued. You can tell Enunciate to treat it as a string by using the `@TypeHint(String.class)` annotation on the parameter.
