### ISSUE TITLE
Support for Jakarta EE 9?

### ISSUE THREAD

**Issue by stolp** [stoicflame/enunciate#1107]
While trying to switch my project to Jakarta EE 9 classes (jakarta.xml.bind-api in my case), I noticed that there is currently no support available for Jakarta classes in Enunciate.

I am aware of issues #1102 and #1044, but I see no progress made in that direction.

Are the plans for releasing a Jakarta EE 9 compatible version of Enunciate in the near future, or do we need to drop enunciate once required to move to EE9 and above?

The latter would be a real shame, as I really like to continue using it.

**Comment by stoicflame** [comment]
Hi!

Thanks for your support.

#1044 is the right place to track this work; I just haven't had time to apply myself to it yet and nobody else has stepped up to provide a PR for it.

I'm hoping I'll get to it within a few weeks or so, but I can't commit to anything more specific yet.

**Comment by stolp** [comment]
Thank you for *your* support! I am totally fine with the positive outlook!
