### ISSUE TITLE
Is there a way to change the URL path that enunciate is located at?

### ISSUE THREAD

**Issue by JaredCraigSmith** [stoicflame/enunciate#1109]
Is there a way to change the URL path that enunciate is located at? When I run enunciate locally it shows up at localhost:5000.  Is there a way to actually have it show up at localhost:5000/enunciate.

**Comment by stoicflame** [comment]
I _think_ you're just asking about moving the documentation to a directory and still having it resolve the links the same way:

```xml
<enunciate>
  <modules>
    <docs docsSubdir="enunciate"/>
```
