### ISSUE TITLE
enunciate-maven-plugin 2.14 - issues with relative links to resources and swagger-ui.css

### ISSUE THREAD

**Issue by francescomangiacrapa** [stoicflame/enunciate#1112]
Hi,

I just integrated the enunciate engine via `enunciate-maven-plugin` v. 2.14 in "My Web Application" (jersey based). The goal executed is `<goal>assemble</goal>`.

In the `enunciate.xml`, I added the following configuration (in order to create the documentation under the folder /**docs**/):
```
<docs docsDir="${project.build.directory}/docs" />

```

and the documentation is correctly built in my .war under the folder:

```
"My Web Application"/
   docs/
      index.html
      ....
   WEB-INF/
      ....
```

Two issues/questions.

1. The documentation navigation is OK, but the resources published in the documentation have the resource path (GET/POST LINKS) of kind

https://[my_application_url]/**docs**/[resouce_name]

they are broken due to the /**docs**/ in the path, they should be of kind: 
```
https://[my_application_url]/[resouce_name].
```
Is there a parameter in the configuration for fixing this?

2. By accessing to Swagger via _"You may also enjoy the [interactive interface] provided for this API by Swagger"_

I got an error in the console JavaScript...

```
The stylesheet https://data.dev.d4science.org/docs/ui/swagger-ui.css was not loaded because its MIME type, “text/html”, is not “text/css”.
```
and the CSS are not loaded in the page.

Many thanks in advance for any support.

**Comment by stoicflame** [comment]
Yeah, so you'd like the documentation deployed into a subfolder but your application running at the root. That's what the `docsSubdir` configuration is for. Suggested adjustment:

```xml
<docs docsDir="${project.build.directory}" docsSubdir="docs"/>
```

**Comment by francescomangiacrapa** [comment]
Hi @stoicflame,
many thanks for your answer. The configuration works as expected.
