### ISSUE TITLE
Performance issues with swagger-ui since enunciate 2.14.0 

### ISSUE THREAD

**Issue by mnisius** [stoicflame/enunciate#1119]
I noticed very bad performance with the generated swagger-ui if I call an endpoint with a big payload. The service itself is fast but I have to wait a long time before the swagger-ui displays the results. 

This does not happen with enunciate 2.13.x. Maybe its related to the new syntax highlighting in the swagger-ui? Because that’s not present in the old version. 

I created a small sample project. The swagger-ui is deployed with the application so you can open http://localhost:8080/apidocs/ui/index.html  call /greetingList and see for yourself. 

The method itself takes 1ms-3ms on the server. 

- With 5000 results the swagger-ui needs 8 seconds 
- With 10000 results the swagger-ui needs 30 seconds 
- With 50000 results the swagger-ui needs 380 seconds 

[bad-performance.zip](https://github.com/stoicflame/enunciate/files/8796690/bad-performance.zip)

**Comment by stoicflame** [comment]
Good to know, thanks for the report.

**Comment by stoicflame** [comment]
Version 2.15.0 of Enunciate has updated to the latest version of Swagger UI + OpenAPI 3.0.
