### ISSUE TITLE
Wrong Jersey package referenced in sample client code

### ISSUE THREAD

**Issue by mgardiner** [stoicflame/enunciate#112]
Under Files and Libraries the Jersey Sample code refers to Jersey 1.x package instead of Jersey 2.x package.

With Java 8 currently warning that internal packages such as com.sun.* should not be used and JDK 9 will actually fail the build if com.sun.* is referenced instead of org.glassfish.*

Example:
com.sun.jersey.api.client.Client client = com.sun.jersey.api.client.Client.create();

![jerseybug](https://cloud.githubusercontent.com/assets/1128232/9366874/2413f470-4677-11e5-9a25-1de2f30da0c9.png)

**Comment by stoicflame** [comment]
+1

**Comment by stoicflame** [comment]
Fixed at 4bcd02e
