### ISSUE TITLE
idx-user Rolesrepresentation is missing properties (grouproles, userroles, projectroles)

### ISSUE THREAD

**Issue by cemcelwee** [stoicflame/enunciate#1126]
See code here:
idx-user/blob/db40186b34394c598179637a9e44ea8b976c7115/rest-api/src/main/java/org/familysearch/idx/rest/user/api/model/RolesRepresentation.java
and docs here:
https://www.familysearch.org/service/indexing/user/json_RolesRepresentation.html
Swagger.json also missing them.

**Comment by stoicflame** [comment]
Thanks for the report.
