### ISSUE TITLE
Duplicate definition in Swagger.json prevents deserialization into JSON object and loading of Swagger UI

### ISSUE THREAD

**Issue by cemcelwee** [stoicflame/enunciate#1127]
See Swagger page (which fails to load):
https://www.familysearch.org/service/indexing/workflow/ui/index.html
See Swagger.json (definitions->xml_fsi-idx-v2_batchworkflowstate->allOf->properties->reindexType(duplicated) && state(duplicated):
https://www.familysearch.org/service/indexing/workflow/ui/swagger.json
See Enunciate docs here:
https://www.familysearch.org/service/indexing/workflow/xml_fsi-idx-v2_batchworkflowstate.html
Also the json version, which has different names:
https://www.familysearch.org/service/indexing/workflow/json_BatchWorkflowStateRepresentation.html

**Comment by cemcelwee** [comment]
idx-workflow

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
Fixed at b22310e69
