### ISSUE TITLE
Duplicate path missing from Swagger, but present in Enunciate

### ISSUE THREAD

**Issue by cemcelwee** [stoicflame/enunciate#1128]
See Enunciate docs:
https://www.familysearch.org/service/indexing/user/resource_GroupEndpointsImpl.html#resource_GroupEndpointsImpl_read_request_groupid_GET
/groups/{groupid} duplicaated GET PUT
/groups/{groupid}/users duplicaated GET 

Swagger docs have only one version of each.
idx-user

**Comment by stoicflame** [comment]
Thanks for the report.
