### ISSUE TITLE
2.14 release is missing an artifact

### ISSUE THREAD

**Issue by amberream** [stoicflame/enunciate#1130]
On the Enunciate release page there are normally 3 assets – two source and one called Enunciate-version.zip.  I noticed for the latest release (2.14) you only have the two source code zips. It would be great if the Enunciate zip was included like it was for past versions.  Otherwise can you explain how to create this myself?  I tried building myself with maven, but it doesn't give me the same structure as past release versions of the zip file which consists of the enunciate jar and a libs folder.

https://github.com/stoicflame/enunciate/releases

**Comment by stoicflame** [comment]
Looks like I missed that part of the release process. I've uploaded it to that releases page.
