### ISSUE TITLE
Why does ns0.xsd appear as a client library?

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#1134]
When i enable the `<java-xml-client disabled="false" />`, an additional client library gets created :

![image](https://user-images.githubusercontent.com/1845372/193201174-24cc70a8-f18d-435e-80ae-c054e9fc9d3b.png)

This is not really a client library, but just a single XML file. Why does it appear, and how can I make it go away?

**Comment by stoicflame** [comment]
You're right that's not _technically_ a "client library" but does define the API. I guess I just didn't know where else to put it. If you'd like to suggest somewhere better I'll consider making an enhancement.

**Comment by sbrattla** [comment]
OK, I thought it was a bug - probably mostly due to the `ns0.xsd` title. I don't think anyone will use this feature on my API, but it appears to come automatically when I enable the `java-xml-client`. Is it possible to disable it? Is it possible to set the title to something more meaningful?

**Comment by stoicflame** [comment]
I think if you disable the `idl` module it might remove that download:

```xml
<enunciate>
  <modules>
    <idl disabled="true"/>
```

Let me know if that doesn't work.
