### ISSUE TITLE
enunciate-maven-plugin does not work in Java 11

### ISSUE THREAD

**Issue by Jalonso063** [stoicflame/enunciate#1137]
We have enunciate-maven-plugin from com.webcohesion.enunciate to generate some docs for our api. With Java 8 we did not have any problem but when have upgraded to Java 11 we are having the following error:

WARNING] [ENUNCIATE] [javac] compiler message file broken: key=compiler.misc.msg.bug arguments=11.0.10, {1}, {2}, {3}, {4}, {5}, {6}, {7}
[WARNING] [ENUNCIATE] [javac] java.lang.Error: java.util.zip.ZipException: zip END header not found [WARNING] [ENUNCIATE] [javac] at jdk.compiler/com.sun.tools.javac.code.ModuleFinder.findSingleModule(ModuleFinder.java:220) [WARNING] [ENUNCIATE] [javac]   at jdk.compiler/com.sun.tools.javac.comp.Modules.setCompilationUnitModules(Modules.java:453)

Any idea why could it be happening? Is there any way to debug the error?

**Comment by stoicflame** [comment]
This is a new one for me. I can tell you there are many Enunciate Java 11 users who aren't experiencing this problem.

The output of `mvn -X` should give you the needed debug info to try the compile outside of Enunciate. If you can provide me a way to reproduce the issue I can also help debug it.

**Comment by Jalonso063** [comment]
Hi @stoicflame , it turned out to be a corrupted jar file in our dependency tree.  I tested it again removing it and it worked. Sorry to bother you by opening this issue.
