### ISSUE TITLE
Duplicate class on hidden folder

### ISSUE THREAD

**Issue by mauriole** [stoicflame/enunciate#1150]
Hi! I've been using enunciate via enunciate-maven-plugin 2.12.1 alongside enunciate-openapi module 1.1.5 to generate the API specification of some projects, which has been working fine.

I recently started a project which uses version control that creates hidden folders everywhere and started getting the duplicate class issue because enunciate is scanning these hidden folders and finding the version-controlled classes.

Configured my pom.xml file to exclude those folders in the maven compiler and enunciate-maven-plugin:
`<groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-compiler-plugin</artifactId>
                        <version>3.9.0</version>
                        <configuration combine.self="override">
                            <excludes>
                                <exclude>**/.vc_path/**</exclude>
                            </excludes>`

`<groupId>com.webcohesion.enunciate</groupId>
                        <artifactId>enunciate-maven-plugin</artifactId>
                        <version>${enunciate-version}</version>
                        <executions>
                            <execution>
                                <phase>compile</phase>
                                <goals>
                                    <goal>docs</goal>
                                </goals>
                                <configuration>
                                    <configFile>${project.basedir}/src/main/resources/enunciate.xml</configFile>
                                    <docsDir>${project.build.directory}/classes/swagger-ui</docsDir>
                                    <excludes>
                                        <exclude>**/.vc_path/**</exclude>
                                        <exclude>org.example</exclude>
                                    </excludes>
                                    <sourcepath-excludes>
                                        <sourcepath-exclude>
                                            <groupId>org.example</groupId>
                                        </sourcepath-exclude>
                                    </sourcepath-excludes>
                                    <sourcepath-includes>
                                        <sourcepath-include>
                                            <groupId>org.example.rest.jersey.web.controller</groupId>
                                        </sourcepath-include>
                                    </sourcepath-includes>
                                </configuration>
                            </execution>`

The enunciate.xml looks like this:
`<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.5.0.xsd">

    <application root="/"/>
    <modules>
        
        <jackson1 disabled="true" />
        <jaxb disabled="true" />
        <jaxws disabled="true" />
        <spring-web disabled="true" />
        <idl disabled="true" />
        <c-xml-client disabled="true" />
        <csharp-xml-client disabled="true" />
        <java-xml-client disabled="true" />
        <java-json-client disabled="true" />
        <gwt-json-overlay disabled="true" />
        <obj-c-xml-client disabled="true" />
        <php-xml-client disabled="true" />
        <php-json-client disabled="true" />
        <ruby-json-client disabled="true" />
        <swagger disabled="true" />
        <docs disabled="true" />
        <jackson disabled="true" />
        <jaxrs disabled="true" />

        
      <openapi disabled="false" removeObjectPrefix="true" disableExamples="true" host="localhost:8096" basePath="rest/v1" />

    </modules>

    <api-classes>
        <exclude pattern="org.example.**"/>
        <include pattern="org.example.rest.jersey.web.controller.**"/>
    </api-classes>
</enunciate>`

The error message I get is:
`[INFO] 
[INFO] --- enunciate-maven-plugin:2.12.1:docs (default) @ rest-jersey ---
[INFO] [ENUNCIATE] Using enunciate configuration at /src/main/resources/enunciate.xml
[WARNING] [ENUNCIATE] [javac] [ERROR] com.webcohesion.enunciate.Enunciate$URLFileObject[file:/src/main/java/org/example/.vc_path/rest/jersey/RestApplication.java]:29:8 /src/main/java/org/example/.vc_path/rest/jersey/RestApplication.java:29: error: duplicate class: org.example.rest.jersey.RestApplication
[WARNING] [ENUNCIATE] [javac] /src/main/java/org/example/.vc_path/rest/jersey/RestApplication.java:29: error: duplicate class: org.example.rest.jersey.RestApplication

[WARNING] [ENUNCIATE] [javac] public class RestApplication extends ResourceConfig {
[WARNING] [ENUNCIATE] [javac]        ^`

I have my IDE (Intellij IDEA) configured to ignore the .vc_path pattern and the integrated maven compiler also excludes this. The project also excludes these folders.

Is there a way to prevent enunciate from scanning those hidden folders?

Thanks!

**Comment by stoicflame** [comment]
I'm afraid this might be a new use case for exclusion that hasn't been accounted yet. I'll take it on as a new issue.

**Comment by mauriole** [comment]
Thank you for the information @stoicflame, seeing that this might be done for 2.15.0, it is my understanding that my current configuration (enunciate-maven-plugin 2.12.1 alongside enunciate-openapi module 1.1.5) would break, since the openapi module doesn't compile against newer versions of enunciate. 

Is there any chance of a backport or some work around you can help me think of?

Thanks again and happy 2023!!

**Comment by stoicflame** [comment]
It's my expectation that Enunciate `2.15` will include support for the OpenApi spec.

**Comment by mauriole** [comment]
Hi! Just to bring more light to the issue in case it is needed when you get to it. I enabled debug log, and this are the files the enunciate compiler is finding:

file:/src/main/java/.vc_path/org/example/rest/jersey/RestApplication.java
file:/src/main/java/org/.vc_path/example/rest/jersey/RestApplication.java
file:/src/main/java/org/example/.vc_path/rest/jersey/RestApplication.java
file:/src/main/java/org/example/rest/.vc_path/jersey/RestApplication.java
file:/src/main/java/org/example/rest/jersey/.vc_path/RestApplication.java
file:/src/main/java/org/example/rest/jersey/RestApplication.java

The versioning tool being used creates those .vc_path file system links, so maybe having a way to exclude folder patterns, or having enunciate ignore hidden folders could be a solution here.

Hope this helps. I'll be glad to provide more info if needed. Thank you!

**Comment by stoicflame** [comment]
At dfada4905 I added logic to exclude hidden files/directories from being processed.
