### ISSUE TITLE
@ResourceGroup annotation is not working

### ISSUE THREAD

**Issue by adityakr369** [stoicflame/enunciate#1158]
i wanted to implement API Grouping so i was using @ResourceGroup Annotation but it is not working. Please help me on this.

**Comment by stoicflame** [comment]
You'll need to provide more specifics on what you mean by "not working".

Please confirm you have your resources grouped by annotation, depending on whether you're using spring or jax-rs:

```xml
<enunciate>
  <modules>
    <spring-web groupBy="annotation"/>
    <jaxrs groupBy="annotation"/>
```

**Comment by adityakr369** [comment]
i need to implement definition like this https://dev.to/s2agrahari/grouping-apis-in-swagger-55kk
