### ISSUE TITLE
Any document to display apis on selecting a particular group .

### ISSUE THREAD

**Issue by adityakr369** [stoicflame/enunciate#1160]
i need to implement apis groups like this . Is there any resource in enunciate
https://dev.to/s2agrahari/grouping-apis-in-swagger-55kk

**Comment by stoicflame** [comment]
Enunciate doesn't have a feature to group by pattern, but you can use `@com.webcohesion.enunciate.metadata.rs.ResourceGroup` annotations to accomplish the same thing.
