### ISSUE TITLE
Project fails to build with Java 17

### ISSUE THREAD

**Issue by cstamas** [stoicflame/enunciate#1164]

**Comment by stoicflame** [comment]
115406ab48cad8b22c7bb7c1e58a0c34ea2c5dcc

**Comment by stoicflame** [comment]
[Enunciate 2.16.1](https://github.com/stoicflame/enunciate/releases/tag/v2.16.1) has been released.

**Comment by jdimeo** [comment]
Hugely appreciative of this! Was a pain to revert to 11 since it's 2 LTSs behind now. thank you!
