### ISSUE TITLE
Vulnerability requires update of commons-configuration2 to 2.9.0

### ISSUE THREAD

**Issue by bwlewis72** [stoicflame/enunciate#1172]
Version 2.15.1 uses commons-configuration2 version 2.8.0 which uses Commons-text version 1.9 which is vulnerable to Apache text4shell.  It is a high severity vulnerability.

You need to update the commons-configuration2 to version 2.9.0 to resolve this issue.

**Comment by bwlewis72** [comment]
Thanks for adding it to the next build.  Do you have a generic goal for releasing 2.16.0?

**Comment by stoicflame** [comment]
[Enunciate 2.16.1](https://github.com/stoicflame/enunciate/releases/tag/v2.16.1) has been released.
