### ISSUE TITLE
@FormParam parameters missing in OpenAPI definition (2.15.1)

### ISSUE THREAD

**Issue by dariokures** [stoicflame/enunciate#1175]
Hi,

Looks like @FormParam parameters are not added to OpenApi definition in 2.15+
Example (Java 17, JAX-RS Jersey 3.1.2):
```java
import jakarta.ws.rs.Consumes;
import jakarta.ws.rs.FormParam;
import jakarta.ws.rs.POST;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.core.MediaType;

@Path("/playground")
public class PlaygroundResource {

    @POST
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Produces(MediaType.TEXT_PLAIN)
    public String test(@FormParam("param1") String param1) {

        return param1;
    }
}
```
Enunciate 2.15.1 (OpenAPI)
![image](https://github.com/stoicflame/enunciate/assets/15244496/15d543c9-9c1b-4a07-b0bf-1351f0e24348)

Enunciate 2.14.0 (Swagger)
![image](https://github.com/stoicflame/enunciate/assets/15244496/951bf9e2-a45a-40bb-9fb4-0856115500a9)

**Comment by stoicflame** [comment]
Thanks for the report! I'll look into it.

**Comment by stoicflame** [comment]
[Enunciate 2.16.1](https://github.com/stoicflame/enunciate/releases/tag/v2.16.1) has been released.

**Comment by dariokures** [comment]
With 2.16.1 there is some Swagger UI rendering issue (2.16.0 is ok):
![image](https://github.com/stoicflame/enunciate/assets/15244496/24b85fcf-69a7-4d3e-bab5-7fb2feb7de58)

**Comment by dariokures** [comment]
openapi.json is the same, but there is difference in swagger-ui-standalone-preset.js:

![image](https://github.com/stoicflame/enunciate/assets/15244496/1b1a0e8a-3bb5-4c8c-9784-d1f22b1df8b4)
