### ISSUE TITLE
FreeMarker template error: The following has evaluated to null or missing

### ISSUE THREAD

**Issue by uniqueid001** [stoicflame/enunciate#118]
I am trying to use Enunciate to generate HTML documentation for a JAX-RS API.  I am using the ant task because I can't find the command-line interface in v2.

    [enunciate] Aug 28, 2015 2:53:25 PM freemarker.log._JULLoggerFactory$JULLogger error
    [enunciate] SEVERE: Error executing FreeMarker template
    [enunciate] FreeMarker template error:
    [enunciate] The following has evaluated to null or missing:
    [enunciate] ==> referenceType.label  [in template "jar:file:/tmp/enunciate-2.0.0-M.2/lib/enunciate-docs-2.0.0-M.2.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" at line 954, column 186]
    [enunciate] 
    [enunciate] ----
    [enunciate] Tip: It's the step after the last dot that caused this error, not those before it.
    [enunciate] ----
    [enunciate] Tip: If the failing expression is known to be legally refer to something that's null or missing, either specify a default value like myOptionalVar!myDefault, or use [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
    [enunciate] ----
    [enunciate] 
    [enunciate] ----
    [enunciate] FTL stack trace ("~" means nesting-related):
    [enunciate] 	- Failed at: ${referenceType.label}  [in template "jar:file:/tmp/enunciate-2.0.0-M.2/lib/enunciate-docs-2.0.0-M.2.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "referenceDataType" at line 954, column 184]
    [enunciate] 	- Reached through: @referenceDataType referenceType=(io...  [in template "jar:file:/tmp/enunciate-2.0.0-M.2/lib/enunciate-docs-2.0.0-M.2.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 596, column 17]
    [enunciate] 	~ Reached through: #nested  [in template "jar:file:/tmp/enunciate-2.0.0-M.2/lib/enunciate-docs-2.0.0-M.2.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 118, column 9]
    [enunciate] 	~ Reached through: @boilerplate title=(title + ": " + re...  [in template "jar:file:/tmp/enunciate-2.0.0-M.2/lib/enunciate-docs-2.0.0-M.2.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 464, column 5]
    [enunciate] 	- Reached through: @file name=(resourceGroup.slug + ".ht...  [in template "jar:file:/tmp/enunciate-2.0.0-M.2/lib/enunciate-docs-2.0.0-M.2.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "processResourceGroup" at line 463, column 3]
    [enunciate] 	- Reached through: @processResourceGroup resourceGroup=r...  [in template "jar:file:/tmp/enunciate-2.0.0-M.2/lib/enunciate-docs-2.0.0-M.2.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" at line 195, column 11]
    [enunciate] 	~ Reached through: #nested  [in template "jar:file:/tmp/enunciate-2.0.0-M.2/lib/enunciate-docs-2.0.0-M.2.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 118, column 9]
    [enunciate] 	~ Reached through: @boilerplate pagenav=pagenav  [in template "jar:file:/tmp/enunciate-2.0.0-M.2/lib/enunciate-docs-2.0.0-M.2.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" at line 169, column 3]
    [enunciate] 	- Reached through: @file name=indexPageName  [in template "jar:file:/tmp/enunciate-2.0.0-M.2/lib/enunciate-docs-2.0.0-M.2.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" at line 158, column 1]
    [enunciate] ----
    [enunciate] 
    [enunciate] Java stack trace (for programmers):
    [enunciate] ----
    [enunciate] freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]
    [enunciate] 	at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:116)
    [enunciate] 	at freemarker.core.EvalUtil.coerceModelToString(EvalUtil.java:346)
    [enunciate] 	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
    [enunciate] 	at freemarker.core.DollarVariable.accept(DollarVariable.java:40)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
    [enunciate] 	at freemarker.core.Environment.invoke(Environment.java:700)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
    [enunciate] 	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
    [enunciate] 	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
    [enunciate] 	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
    [enunciate] 	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
    [enunciate] 	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
    [enunciate] 	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
    [enunciate] 	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
    [enunciate] 	at freemarker.core.Environment.invoke(Environment.java:700)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
    [enunciate] 	at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:59)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:377)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
    [enunciate] 	at freemarker.core.Environment.invoke(Environment.java:700)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
    [enunciate] 	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
    [enunciate] 	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
    [enunciate] 	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
    [enunciate] 	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
    [enunciate] 	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
    [enunciate] 	at freemarker.core.Environment.invoke(Environment.java:700)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
    [enunciate] 	at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:59)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:377)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment.process(Environment.java:290)
    [enunciate] 	at freemarker.template.Template.process(Template.java:312)
    [enunciate] 	at org.codehaus.enunciate.modules.docs.DocumentationDeploymentModule.processTemplate(DocumentationDeploymentModule.java:397)
    [enunciate] 	at org.codehaus.enunciate.modules.docs.DocumentationDeploymentModule.call(DocumentationDeploymentModule.java:350)
    [enunciate] 	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
    [enunciate] 	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
    [enunciate] 	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
    [enunciate] 	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
    [enunciate] 	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
    [enunciate] 	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
    [enunciate] 	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
    [enunciate] 	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    [enunciate] 	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onCompleted(SubjectSubscriptionManager.java:232)
    [enunciate] 	at rx.subjects.ReplaySubject.onCompleted(ReplaySubject.java:404)
    [enunciate] 	at rx.Observable$35.onCompleted(Observable.java:7458)
    [enunciate] 	at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:81)
    [enunciate] 	at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
    [enunciate] 	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
    [enunciate] 	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
    [enunciate] 	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
    [enunciate] 	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
    [enunciate] 	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    [enunciate] 	at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
    [enunciate] 	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
    [enunciate] 	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
    [enunciate] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    [enunciate] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    [enunciate] 	at java.lang.Thread.run(Thread.java:745)
    [enunciate] 

    BUILD FAILED
    /tmp/redweb/build-docs.xml:88: java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: freemarker.core.InvalidReferenceException: The following has evaluated to null or missing:
    ==> referenceType.label  [in template "jar:file:/tmp/enunciate-2.0.0-M.2/lib/enunciate-docs-2.0.0-M.2.jar!/org/codehaus/enunciate/modules/docs/docs.fmt" at line 954, column 186]

**Comment by stoicflame** [comment]
Thanks! Fixed at b6cac62.

**Comment by stoicflame** [comment]
[Milestone 3 is now available for you to confirm the fix](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.3).
