### ISSUE TITLE
Release with fix for enunciate-lombok: ConcurrentModificationException

### ISSUE THREAD

**Issue by ypldan** [stoicflame/enunciate#1182]
Hello, is it possible to release the version with the fix that was introduced in this commit: https://github.com/stoicflame/enunciate/commit/cafcca8f10ae4e38a6dfad9a69e5ded8e0a81094?

Right now it's the only blocker for using enunciate in our project, so I would greatly appreciate your help.

**Comment by stoicflame** [comment]
Sorry for the delay; [Enunciate 2.16.1](https://github.com/stoicflame/enunciate/releases/tag/v2.16.1) has been released.
