### ISSUE TITLE
Swagger UI defaulting to openapi.json now or Petstore

### ISSUE THREAD

**Issue by jdimeo** [stoicflame/enunciate#1185]
Hello!
When I updated to the latest release, the Swagger UI still tries to load `swagger.json` but the generated file is now apparently `openapi.json`, leading to an error.
When I updated to the latest Swagger UI, it loads Petstore, and neither `swagger.json` or `openapi.json`.

I looked through the docs but couldn't figure out where to specify the `url` in the Swagger initial config to point it to the correct file. Am I missing something? thanks!

**Comment by jdimeo** [comment]
thank you! Yes. I'm using the latest UI from Swagger since the built in one is still 2.x (right?)
Is there any way to configure this when using a different base? I'm lost on how to get it to stop using Petstore

**Comment by jdimeo** [comment]
Wait, since that code you linked references `swagger-initializer.js` I think that is newer than 2.x ? so maybe it's jsut the docs that are out of date?
![image](https://github.com/stoicflame/enunciate/assets/1071438/875b5983-2d6f-4b9f-a07b-4778716fccad)

**Comment by jdimeo** [comment]
OK sorry for the spam, but I think we can distill this down to two requests:
- Please update the module docs to include the correct version of Swagger UI (which you seemed to update 7 months ago! thank you!)
- Please provide a way to change what gets generated into the Javascript file as a module config option so we can choose `swagger.json` or `openapi.json` or something else depending on our UI version (if this is easy/feasible)

Thank you so much!

**Comment by fhm84** [comment]
@stoicflame sorry, I missed to link my PR to this ticket.
Here a PR for updating swagger-ui to (latest) version v5.9.1: https://github.com/stoicflame/enunciate/pull/1189

**Comment by stoicflame** [comment]
Okay at 47e93bd3ec22f5bb7e2e3e3871e8ee2450308cb9 I updated to the latest Swagger UI (5.17.14).

It's not viable for Enunciate to maintain support for both the "old" swagger.json and the (new) openapi.json at the same time. If you need to maintain the old Swagger UI you can revert to an older Enunciate version.

However, at f7c3d8c4a2bd89f55af8cf089683b4862e67abbf I did overwrite `swagger-initializer.js` with an Enunciate-specific one so that custom Swagger bases will still be integrated into the Enunciate-generated file structure.

**Comment by stoicflame** [comment]
[Enunciate 2.18.0](https://github.com/stoicflame/enunciate/releases/tag/v2.18.0) has been released.

**Comment by jdimeo** [comment]
Thank you so much @stoicflame ! I always brag about how nice it is to build REST APIs in Java and Enunciate scraping Javadocs is a big part of that.
