### ISSUE TITLE
basePath set in swagger module not used in openapi.json

### ISSUE THREAD

**Issue by benjamin-cartereau** [stoicflame/enunciate#1193]
Hello,

In my "enunciate.xml" I have set the "basePath" attribute (to match the @ApplicationPath annotation of the JAX-RS Application :
```
 <modules>
    <swagger disabled="false" basePath="/api/v1" />
    ...
</modules>
```
While the "Try it out" was working well with the Swagger UI up to version 2.14 of the maven plugin since "swagger.json" was setting the basePath based on the one set in "enunciate.xml", it is not the case anymore (versions 2.15.0 & 2.15.1).
While having a look at the newly "openapi.json" created file, there is no reference to the basePath that is set in the xml file.
It looks like there is no "basePath" in the OpenAPI descriptor. But it should be set in the "servers>url" : https://swagger.io/docs/specification/api-host-and-base-path/

Thanks!

**Notes** : I am using version 2.15.1 and cannot use a more recent version because, if I understad well, 2.16 requires jakarta packages (not using Java EE 9 yet) and 2.17 requires Java 18 (still with Java 11).

**Comment by stoicflame** [comment]
Yeah... I didn't document it very well.

The `basePath` configuration isn't used since the move to OpenAPI 3. You now have to use the `server` configuration element:

```xml
<modules>
  <swagger>
    <server url="/api/v1" description="..."/>
```

Can you confirm this work for you?

**Comment by stoicflame** [comment]
Docs updated.
