### ISSUE TITLE
Automatically assign format to members of specific type

### ISSUE THREAD

**Issue by nlichtenberg** [stoicflame/enunciate#1197]
Is it possible to tell enunciate to automatically add the format property to the doc of members of specific types? 

In our use case, it would be desireable to automatically set `"format" : "uuid"` for members of type `java.util.UUID`.
E.g., `private UUID id;` should result in:
`"id" : {
            "readOnly" : false,
"description" : "",
"type" : "string",
"format" : "uuid"
            }`.
We would like to avoid annotating each member with  `@JsonStringFormat("uuid")` as it is prone to errors: developers forgetting the annotation when adding fields.

Thank you
Nils

**Comment by stoicflame** [comment]
I'm afraid not. But I'll mark this as an enhancement request to track it.

Out of curiosity, does the Jackson library have a way to globally set the `JsonStringFormat`?

**Comment by nlichtenberg** [comment]
Using the Jackson2ObjectMapperBuilderCustomizer with an implementation of StdDeserializer<UUID> might be a way to go. 
I will try, as soon as I find the time.

**Comment by nlichtenberg** [comment]
I don't see how `JsonStringFormat` could be applied globally. It might be worth looking at `Jackson2ObjectMapperBuilderCustomizer` when aiming at a global implementation of a mapper but then I don't see how Enunciate would profit from that.

**Comment by stoicflame** [comment]
As of `2.18.0`, the `jackson` module configuration supports a `type-format` subelement, e.g.:

```xml
<enunciate>
  <modules>
    <jackson>
      <type-format class="java.util.UUID" format="uuid"/>
```

**Comment by stoicflame** [comment]
[Enunciate 2.18.0](https://github.com/stoicflame/enunciate/releases/tag/v2.18.0) has been released.
