### ISSUE TITLE
cannot use verbose and debug issue with ant

### ISSUE THREAD

**Issue by emmanuellabrunye** [stoicflame/enunciate#1200]
Hi,
I am using ennunciate 2.17.0 with ant and JDK 17.
When I sue the 'debug' or 'verbose' attributes specified in https://github.com/stoicflame/enunciate/wiki/Executables#ant  I got an error message

My configuration file:

<enunciate **verbose**="true" basedir="${project.src}/subsystem/OpsLink/server/src" buildDir="${deploy.path}/enunciate/" configFile="${project.src}/subsystem/OpsLink/build/enunciate/enunciate.xml">
      <include name="**/*.java"/>
      <classpath refid="compile.classpath"/>
      <export artifactId="docs" destination="${deploy.path}/docs/"/>
    </enunciate>

The result
1> INFO: 
1> INFO: BUILD FAILED
1> INFO: d:\Opslink\JDK17\project\src\subsystem\OpsLink\build\build.xml:497: enunciate doesn't support the "verbose" attribute

same if I replace 'verbose' by 'debug'. Any idea? Thanks

**Comment by stoicflame** [comment]
Thanks for the report. I've corrected the documentation. Those options aren't supported on the task itself, instead Enunciate uses the `-v` and `-d` options on the CLI to detect verbose and debug output.

**Comment by emmanuellabrunye** [comment]
thank you.
Does it mean there is no way to get more verbose information if I trigger enunciate from ant?

**Comment by stoicflame** [comment]
If you run Ant with `ant -v` or `ant -d` Enunciate will provide more verbose information.
