### ISSUE TITLE
Enunciate 2.17.0 is not working with JDK17

### ISSUE THREAD

**Issue by ravigraj** [stoicflame/enunciate#1202]
[enunciate] [main] INFO org.reflections.Reflections - Reflections took 1605 ms to scan 188 urls, producing 147 keys and 147 values
1> INFO: Enabled modules: [docs, idl, jaxb, jaxrs, jaxws, spring-web]
1> INFO: No documentation generated: there are no data types, services, or resources to document.
1> INFO: Unknown artifact 'docs'.  Artifact will not be exported.

I am using Enunciate (2.17.0) and JDK17 to build using ANT  (2.1.3) and facing above error

**Comment by stoicflame** [comment]
It's scanning your sources and not finding any types or services or endpoints. What does your Java source API look like?

**Comment by ravigraj** [comment]
Sorry I am not a position to share that, Can you please give an example How it should be for SOAP API.? It would be very helpful.

**Comment by ric2016** [comment]
I encountered the same message when using the current enunciate version with Java/Jakarta EE 8 code (i.e. code still using javax.* packages instead of jakarta.* packages), so that is one thing to check.

**Comment by stoicflame** [comment]
You're welcome to look at the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) app. The `PersonService.java` is a SOAP endpoint. If you can send me a patch for the sample app that demonstrates the problem you're seeing, I'm happy to debug it.

**Comment by ravigraj** [comment]
resolved by upgrading "org,apache.cfx" from 3.5.2 ---> 4.0.4, some java classes asked to import jakarata.* instead of javax.* which resolved the  Unknown artifact 'docs'. Artifact will not be exported, and generated the docs.

But I am unable to run Junit test after that these are in my pom.xml
<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>5.7.2</version>
		</dependency>
		<dependency>
			<groupId>org.junit</groupId>
			<artifactId>junit-bom</artifactId>
			<version>5.8.2</version>
			<type>pom</type>
			<scope>test</scope>
		</dependency>

**Comment by NicolasMassipFP** [comment]
I get a similar error message when migrating from enunciate 2.14 with JDK11 to enunciate JDK17 with enunciate 2.17.

Adding this in configuration has solved it:
```
    <api-classes>
        <include pattern="com.stonesoft.api.**"/>
    </api-classes>
```
    
Seems that there is no default include and when there is nothing include, maybe the message is not the proper one.

So me documentation is generated, but i don't get the resources generated. ( I get only JSon syntax, instead of Resources, Json and XML ).
