### ISSUE TITLE
java.lang.StackOverflowError

### ISSUE THREAD

**Issue by emweber** [stoicflame/enunciate#1204]
java.lang.StackOverflowError in jackson module when enum constant has a javadoc tag in its comment.

[stacktrace.txt](https://github.com/stoicflame/enunciate/files/14886959/stacktrace.txt)
[src.java.zip](https://github.com/stoicflame/enunciate/files/14886997/src.java.zip)

**Comment by stoicflame** [comment]
Okay, I'll take a look.

**Comment by stoicflame** [comment]
Just wanted to note that I've confirmed this problem. I'll get it fixed in the next release.

The only workaround I can see for now is to avoid using `{@link ...}` in enum value javadoc comments.

**Comment by stoicflame** [comment]
[Enunciate 2.18.0](https://github.com/stoicflame/enunciate/releases/tag/v2.18.0) has been released.
