### ISSUE TITLE
Objects who inherit deprecated properties will not treat them as deprecated 

### ISSUE THREAD

**Issue by espenvis** [stoicflame/enunciate#1205]
Hello.

Suppose you have two objects: `Animal` and `Dog`.

```java
class Animal {
    /** A child owned by animal */
    @Deprecated
    public Animal child;
    
    /** List of children owned by animal */
    public List<? extends Animal> children;
}

class Dog extends Animal {
   // ...
}
```

The object `Dog` extends the object `Animal`. On the `Animal` object, property `child`  is deprecated.

In the generated documentation, this deprecation is reflected correctly on the `Animal` object in the documentation. However, when you take a look at `Dog`, you'll find that this inherited property displays no indicators of deprecation.

Properly identifying and handling the property as deprecated would be great!

**Comment by stoicflame** [comment]
[Enunciate 2.18.0](https://github.com/stoicflame/enunciate/releases/tag/v2.18.0) has been released.
