### ISSUE TITLE
Enum in nested class is not linked properly

### ISSUE THREAD

**Issue by vghero** [stoicflame/enunciate#1206]
Hey,
I'm using Enunciate 2.14.1 to generate Spring MVC REST resource documentation. Usually those APIs contain a couple of enums which are also referred to in the javadoc of the different models and controllers which appear then in the enunciate docs.

As it seems that enums that are not defined in its own files but are nested within another model as static classes, are not properly linked from the javadoc documentation into the resulting description. See the example below:

```java
@RestController
public class ProductController {

    @ResponseStatus(HttpStatus.CREATED)
    @PostMapping(path = "/products", consumes = APPLICATION_JSON_VALUE)
    void create(@RequestBody @Valid Product product) {
        //
    }
}

public class Product {

    /**
     * The {@link Unit#PIECE} is one piece. Link is not generated.
     */
    public Unit unit;

    /**
     * The {@link Availability#OUT_OF_STOCK} means product is sold out. Link is working.
     */
    public Availability availability;

    public enum Unit {
        PIECE,
        WEIGHTED
    }
}

public enum Availability {
    AVAILABLE,
    OUT_OF_STOCK
}
```

The output is:

![image](https://github.com/stoicflame/enunciate/assets/26437329/04272704-bc80-4c1f-a508-f9a6a95bd698)

Is this a known issue?

**Comment by stoicflame** [comment]
[Enunciate 2.18.0](https://github.com/stoicflame/enunciate/releases/tag/v2.18.0) has been released.
