### ISSUE TITLE
Invalid field "description" in Schema Object?

### ISSUE THREAD

**Issue by cw2501** [stoicflame/enunciate#1211]
Hello Ryan, we have a minor problem with the generated open-api 3.0.3 document:

In the Schema Objects of Request Body- and Response Objects, a field "description" is added whenever a component is being referenced.

```
"paths": {
    "\/actor": {
      "post": {
        "tags": [
          "ActorPoint"
        ],
        "operationId": "createActor",
        "requestBody": {
          "required": false,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/AbstractActorDto",
                "description": "" // <--- this one shouldn't exist
              }
   ...
```
ActorPoint is a Spring RestController and the endpoint definition looks like this:

```
@PostMapping(path = {"/actor"})
public AbstractActorDto createActor(@RequestBody AbstractActorDto actor)
```
According to the OpenAPI specification, this field shouldn't be there. Is this an issue on our end or a bug in the generator?

Best regards
Chris

**Comment by stoicflame** [comment]
Thanks, fixed at d831cf37f.

**Comment by cw2501** [comment]
Awesome! Thank you 👍

**Comment by cw2501** [comment]
@stoicflame I think there's a trailing comma now behind the $ref

**Comment by stoicflame** [comment]
Thanks.

a551f1b56

**Comment by stoicflame** [comment]
Enunciate `2.19.0` has been released.
