### ISSUE TITLE
OpenAPI not respecting @JsonValue on enums

### ISSUE THREAD

**Issue by jdimeo** [stoicflame/enunciate#1218]
I'm not sure if this is an OpenAPI module bug, an Enunciate bug, or just not supported. I'm using a library to code-generate POJOs from a JSON schema and it produces enums like this:
```java
    @Generated("jsonschema2pojo")
    public enum DrumSetBrand {
        DW("DW"),
        PEARL("Pearl"),
        TAMA("Tama");
    	
        private final String value;
        private final static Map<String, DrumSetBrand> CONSTANTS = new HashMap<String, DrumSetBrand>();

        static {
            for (DrumSetBrand c: values()) {
                CONSTANTS.put(c.value, c);
            }
        }

        DrumSetBrand(String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return this.value;
        }

        @JsonValue
        public String value() {
            return this.value;
        }

        @JsonCreator
        public static DrumSetBrand fromValue(String value) {
        	DrumSetBrand constant = CONSTANTS.get(value);
            if (constant == null) {
                throw new IllegalArgumentException(value);
            } else {
                return constant;
            }
        }
    }
```

If I define an endpoint:

```
	/**
	 * Gets the best brand of drums.
	 */
	@GET
	@Path("/drums")
	public DrumSetBrand getBestDrumSetBrand() {
		return DrumSetBrand.DW;
	}
```

The resulting OpenAPI model is "plain/vanilla Java enum" based and doesn't respect the Jackson annotations for `@JsonValue` even though I have the Jackson and OpenAPI modules active in my Enunciate config:
```
      "DrumSetBrand" : {
"type" : "string",
"title" : "DrumSetBrand",
"enum" : [
  "DW",
  "PEARL",
  "TAMA"
],
"description" : ""
      }
```

This mismatch causes actual serde errors like `IllegalArgumentException: Unexpected value 'Tama'` since the spec told me to expect `TAMA`.

**Comment by stoicflame** [comment]
The problem is that there aren't actually `@JsonProperty` annotations on that enum you specified. Enunciate is a compile-time tool and there's no way for it to obtain those string values passed into the constructor. Each enum value needs an annotation that Enunciate can read, e.g.:

```java
@Generated("jsonschema2pojo")
    public enum DrumSetBrand {
        @JsonProperty("DW")
        DW("DW"),
        @JsonProperty("Pearl")
        PEARL("Pearl"),
        @JsonProperty("Tama")
        TAMA("Tama");
```

So whatever tool you're using to generate the Java needs to add those annotations.

**Comment by jdimeo** [comment]
Thank you @stoicflame - that makes sense that we must do it with `@JsonProperty` on the enum constants instead of `@JsonValue`. 

I had already set up a custom jsonschema2pojo Jackson annotator for other reasons, so adding a rule to it was quite straightforward:

```java
@Override
public void enumConstant(JDefinedClass _enum, JEnumConstant constant, String value) {
	super.enumConstant(_enum, constant, value);
	constant.annotate(JsonProperty.class).param("value", value);	
}
```
In fact, this seems like reasonable default behavior because I don't think those annotations would "hurt" anything.


Thanks for the fast response!
