### ISSUE TITLE
v2.0m3 Only integer are allowed in DocumentationExample

### ISSUE THREAD

**Issue by topikachu** [stoicflame/enunciate#122]
When use no integer with DocumentationExample, enunciate give error
java.util.MissingFormatArgumentException: Format specifier 's'

**Comment by stoicflame** [comment]
Thanks for the report. I need a stack trace. Example code would be helpful too, since I don't know what you mean by "When use no integer with DocumentationExample".

If you're using Maven, please run with "mvn -e" to get the stack trace.

**Comment by topikachu** [comment]
I use ‘@DocumentationExample’ to fill the example value. For example
    @DocumentationExample("120.1")
    public double getLng() {
        return lng;
    }

When execute enunciate mvn plugin, there is an error 

Caused by: java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.util.Formatter.format(Formatter.java:2519)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2927)
        at com.webcohesion.enunciate.mojo.ConfigMojo$MavenEnunciateLogger.warn(ConfigMojo.java:494)
        at com.webcohesion.enunciate.modules.jackson.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:192)
        at com.webcohesion.enunciate.modules.jackson.api.impl.ExampleImpl.build(ExampleImpl.java:124)
...

I believe, the error is caused by two issues

1. 
https://github.com/stoicflame/enunciate/blob/v2.0.0-M.3/jackson/src/main/java/com/webcohesion/enunciate/modules/jackson/api/impl/ExampleImpl.java#L189
1. ExampleImpl doesn't accept no integer value. So an error happens here. However, in json, float is    a valid type.

2. 
https://github.com/stoicflame/enunciate/blob/v2.0.0-M.3/jackson/src/main/java/com/webcohesion/enunciate/modules/jackson/api/impl/ExampleImpl.java#L192
The second parameter (specifiedExample?) is missing in the line of log. An un-catched exception is thrown here breaking mvn compile.

**Comment by stoicflame** [comment]
Thanks! Fixed at 3adf75c.

**Comment by stoicflame** [comment]
Fix was included in [Milestone 4](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.4). Thanks for the report, and please report any new issues.
