### ISSUE TITLE
v2 template: Supported HTTP-methods for each RESTful resource

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#125]
Hi!

I really dig the look of the new version 2 template (I'm using the milestone 3 release). Great work! I just have some suggestions to it that I believe would make it even better.

When listing each RESTful resource, we have a description of the service next to it, and a set of supported HTTP methods for this resource. These HTTP methods seems to group all resources within the service. See the image below:

![docs current](https://cloud.githubusercontent.com/assets/6347803/9700008/52827d82-53f5-11e5-80ca-9db0326167dc.png)

However, I would like it to list the set of HTTP methods supported for each resource, instead. Something like this:
![docs expected](https://cloud.githubusercontent.com/assets/6347803/9700013/6f0d84b0-53f5-11e5-900b-140909361c97.png)

I guess it's a quite simple change in the freemarker template (if freemarker is still used, that is). I can try to fix this myself and submit a pull request, once I have the time to dig into it. :)

**Comment by anton-johansson** [comment]
Noticed it's just not a template change: [ResourceGroup.java](https://github.com/stoicflame/enunciate/blob/v2/core/src/main/java/com/webcohesion/enunciate/api/resources/ResourceGroup.java)

**Comment by stoicflame** [comment]
Thanks for the suggestion; I'll look into it.

It might be trickier than it seems because (as you've noticed with `ResourceGroup`) I've abstracted away the resource definition interface so that we can support other RS implementations (e.g. [Spring Web annotations](https://github.com/stoicflame/enunciate/issues/60)).

**Comment by anton-johansson** [comment]
Looking into it is good enough for me! If it's possible without ruining the abstraction, that's great, otherwise it's not that big of a deal.

**Comment by anton-johansson** [comment]
What's the gain in abstracting away the resource definition interface, by the way? I assume all RS implementations have paths/resources which in turn have one or many methods?

**Comment by stoicflame** [comment]
Fixed at 5204438.

**Comment by stoicflame** [comment]
Fix was included in [Milestone 4](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.4). Thanks for the report, and please report any new issues.
