### ISSUE TITLE
Deprecated properties of data types should be strikethrough

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#132]
In v1, deprecated fields was marked as deprecated in the documentation (red background, if I remember correctly). This is no longer the case in v2. I suggest we add a strikethrough to the deprecated properties to match the format of deprecated REST-operations.

I also reopened #53 for v2.

**Comment by stoicflame** [comment]
Closed with merge of #133.

**Comment by stoicflame** [comment]
Fix was included in [Milestone 4](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.4). Thanks for the report, and please report any new issues.
