### ISSUE TITLE
M4: java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by uniqueid001** [stoicflame/enunciate#139]
Testing with 2.0.0-M.3, I manually updated swagger.fmt in enunciate-swagger.jar (see #119).  That worked, producing the docs in less than 20 seconds.

Now with 2.0.0-M.4, generating docs runs out of memory.  (the JVM's automatic max heap size is 4GB on this machine)

    [ENUNCIATE] Using enunciate configuration at enunciate.xml
    [enunciate] Sep 11, 2015 1:47:36 PM freemarker.log._JULLoggerFactory$JULLogger error
    [enunciate] SEVERE: Error executing FreeMarker template
    [enunciate] FreeMarker template error:
    [enunciate] An error has occurred when reading existing sub-variable "body"; see cause exception! The type of the containing value was: extended_hash+string (com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl wrapped into f.e.b.StringModel)
    [enunciate] 
    [enunciate] ----
    [enunciate] FTL stack trace ("~" means nesting-related):
    [enunciate] 	- Failed at: ${type.example.body?xhtml}  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processDataType" at line 948, column 58]
    [enunciate] 	~ Reached through: #nested  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 119, column 9]
    [enunciate] 	~ Reached through: @boilerplate title=(title + ": " + ty...  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processDataType" at line 842, column 5]
    [enunciate] 	- Reached through: @file name=(type.slug + ".html")  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processDataType" at line 841, column 3]
    [enunciate] 	- Reached through: @processDataType type=type  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processDataSyntax" at line 826, column 13]
    [enunciate] 	~ Reached through: #nested  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 119, column 9]
    [enunciate] 	~ Reached through: @boilerplate title=(title + ": " + sy...  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processDataSyntax" at line 807, column 5]
    [enunciate] 	- Reached through: @file name=(syntax.slug + ".html")  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "processDataSyntax" at line 806, column 3]
    [enunciate] 	- Reached through: @processDataSyntax syntax=syntax  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 261, column 9]
    [enunciate] 	~ Reached through: #nested  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" in macro "boilerplate" at line 119, column 9]
    [enunciate] 	~ Reached through: @boilerplate pagenav=pagenav  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 170, column 3]
    [enunciate] 	- Reached through: @file name=indexPageName  [in template "jar:file:tools/enunciate-2.0.0/lib/enunciate-docs-2.0.0-M.4.jar!/com/webcohesion/enunciate/modules/docs/docs.fmt" at line 159, column 1]
    [enunciate] ----
    [enunciate] 
    [enunciate] Java stack trace (for programmers):
    [enunciate] ----
    [enunciate] freemarker.core._TemplateModelException: [... Exception message was already printed; see it above ...]
    [enunciate] 	at freemarker.ext.beans.BeanModel.get(BeanModel.java:199)
    [enunciate] 	at freemarker.core.Dot._eval(Dot.java:40)
    [enunciate] 	at freemarker.core.Expression.eval(Expression.java:78)
    [enunciate] 	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
    [enunciate] 	at freemarker.core.BuiltInForString._eval(BuiltInForString.java:26)
    [enunciate] 	at freemarker.core.Expression.eval(Expression.java:78)
    [enunciate] 	at freemarker.core.Expression.evalAndCoerceToString(Expression.java:82)
    [enunciate] 	at freemarker.core.DollarVariable.accept(DollarVariable.java:40)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
    [enunciate] 	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
    [enunciate] 	at freemarker.core.Environment.invoke(Environment.java:700)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
    [enunciate] 	at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:59)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:377)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
    [enunciate] 	at freemarker.core.Environment.invoke(Environment.java:700)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
    [enunciate] 	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
    [enunciate] 	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
    [enunciate] 	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
    [enunciate] 	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
    [enunciate] 	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
    [enunciate] 	at freemarker.core.Environment.invoke(Environment.java:700)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
    [enunciate] 	at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:59)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:377)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
    [enunciate] 	at freemarker.core.Environment.invoke(Environment.java:700)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.IteratorBlock$Context.runLoop(IteratorBlock.java:159)
    [enunciate] 	at freemarker.core.Environment.visitIteratorBlock(Environment.java:559)
    [enunciate] 	at freemarker.core.IteratorBlock.accept(IteratorBlock.java:67)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visitByHiddingParent(Environment.java:333)
    [enunciate] 	at freemarker.core.ConditionalBlock.accept(ConditionalBlock.java:48)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment.invokeNestedContent(Environment.java:535)
    [enunciate] 	at freemarker.core.BodyInstruction.accept(BodyInstruction.java:56)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Macro$Context.runMacro(Macro.java:178)
    [enunciate] 	at freemarker.core.Environment.invoke(Environment.java:700)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:84)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment$NestedElementTemplateDirectiveBody.render(Environment.java:2255)
    [enunciate] 	at com.webcohesion.enunciate.util.freemarker.FileDirective.execute(FileDirective.java:59)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:377)
    [enunciate] 	at freemarker.core.UnifiedCall.accept(UnifiedCall.java:104)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.MixedContent.accept(MixedContent.java:62)
    [enunciate] 	at freemarker.core.Environment.visit(Environment.java:312)
    [enunciate] 	at freemarker.core.Environment.process(Environment.java:290)
    [enunciate] 	at freemarker.template.Template.process(Template.java:312)
    [enunciate] 	at com.webcohesion.enunciate.modules.docs.DocsModule.processTemplate(DocsModule.java:349)
    [enunciate] 	at com.webcohesion.enunciate.modules.docs.DocsModule.call(DocsModule.java:302)
    [enunciate] 	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:31)
    [enunciate] 	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:10)
    [enunciate] 	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:79)
    [enunciate] 	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:109)
    [enunciate] 	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
    [enunciate] 	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
    [enunciate] 	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
    [enunciate] 	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    [enunciate] 	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onCompleted(SubjectSubscriptionManager.java:232)
    [enunciate] 	at rx.subjects.ReplaySubject.onCompleted(ReplaySubject.java:404)
    [enunciate] 	at rx.Observable$35.onCompleted(Observable.java:7458)
    [enunciate] 	at rx.observers.SafeSubscriber.onCompleted(SafeSubscriber.java:81)
    [enunciate] 	at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
    [enunciate] 	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:110)
    [enunciate] 	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:140)
    [enunciate] 	at rx.internal.operators.TakeLastQueueProducer.emit(TakeLastQueueProducer.java:100)
    [enunciate] 	at rx.internal.operators.TakeLastQueueProducer.startEmitting(TakeLastQueueProducer.java:45)
    [enunciate] 	at rx.internal.operators.OperatorTakeLast$1.onCompleted(OperatorTakeLast.java:59)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:658)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.drainAndComplete(OperatorMerge.java:521)
    [enunciate] 	at rx.internal.operators.OperatorMerge$MergeSubscriber.completeInner(OperatorMerge.java:486)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.emit(OperatorMerge.java:673)
    [enunciate] 	at rx.internal.operators.OperatorMerge$InnerSubscriber.onCompleted(OperatorMerge.java:600)
    [enunciate] 	at rx.internal.util.ScalarSynchronousObservable$ScalarSynchronousAction.call(ScalarSynchronousObservable.java:117)
    [enunciate] 	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
    [enunciate] 	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
    [enunciate] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    [enunciate] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    [enunciate] 	at java.lang.Thread.run(Thread.java:745)
    [enunciate] Caused by: java.lang.reflect.InvocationTargetException
    [enunciate] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [enunciate] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [enunciate] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [enunciate] 	at java.lang.reflect.Method.invoke(Method.java:497)
    [enunciate] 	at freemarker.ext.beans.BeansWrapper.invokeMethod(BeansWrapper.java:1458)
    [enunciate] 	at freemarker.ext.beans.BeanModel.invokeThroughDescriptor(BeanModel.java:255)
    [enunciate] 	at freemarker.ext.beans.BeanModel.get(BeanModel.java:159)
    [enunciate] 	... 152 more
    [enunciate] Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
    [enunciate] 	at com.sun.tools.javac.util.Convert.utf2string(Convert.java:163)
    [enunciate] 	at com.sun.tools.javac.util.Name.toString(Name.java:147)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.model.util.MapType.findMapTypeDeclaration(MapType.java:127)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.model.util.MapType.findMapType(MapType.java:85)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.model.Accessor.getAccessorType(Accessor.java:100)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.model.Member.getAccessorType(Member.java:247)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.model.Accessor.getJsonType(Accessor.java:135)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:133)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:157)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:189)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:133)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:157)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:189)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:133)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:157)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:189)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:133)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:157)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:133)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:157)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:189)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:133)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:157)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:133)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:157)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:133)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:157)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:189)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:133)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:157)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.build(ExampleImpl.java:133)
    [enunciate] 	at com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl.exampleNode(ExampleImpl.java:157)
    [enunciate] 

    BUILD FAILED
    ant-run-enunciate.xml:47: java.lang.RuntimeException: com.webcohesion.enunciate.EnunciateException: freemarker.core._TemplateModelException: An error has occurred when reading existing sub-variable "body"; see cause exception! The type of the containing value was: extended_hash+string (com.webcohesion.enunciate.modules.jackson1.api.impl.ExampleImpl wrapped into f.e.b.StringModel)

**Comment by stoicflame** [comment]
Wow.

At first I thought this might be an infinite loop due to a self-referencing class, but I've added a test case at 602c24f and confirmed that's not the case. My only explanation is that your object graph is too big, and we're running out of memory in an effort to build it.

However, that still doesn't explain how it worked before.

Well, at e288791 I've added a check to the example-generating code so it doesn't go deeper than two levels. I'm hoping that will fix your problem. Please re-open if you find it still happens.

**Comment by uniqueid001** [comment]
I just tested Milestone 5: it works.  

I see what you are saying regarding the example data structures.  Most of our data types are JPA Entities with bi-directional relationships for foreign keys.  That could certainly result in an infinitely deep graph traversal.

**Comment by vghero** [comment]
Hmm any plans to make the level configurable :)?
