### ISSUE TITLE
JavaDoc from Super Class located in separate maven module

### ISSUE THREAD

**Issue by gmtwc** [stoicflame/enunciate#140]
I looked at the FAQ on Multi-Module Projects and followed the first option with specifying pattern in <api-classes>  section of enunciate.xml.  I think the second option documentation in FAQ is outdated for v2 branch (the goal "export" does not exist).

I have the bean extending from the super class located in a separate maven build module.  I see that the super class maven module compilation produces both binary and source jars.  I do not see the JavaDoc data present in the super class  or the sub class enunciate documentation (I expected description fields populated accordingly).

My understanding is that the enunciate plugin is doing a separate javac compiler pass and the classpath is controlled by maven plus I supplied the api-classes section data.  In v2 branch source I see the examples of super class and sub class located in the same module which works fine but I don't see the case when they are in a separate compilation units.

Is there a specific configuration I am missing in such case?

Thanks!

**Comment by gmtwc** [comment]
This was solved by adding explicit source jar dependency:

<dependency>
   <groupId>${base_class_module_group_id}</groupId>
   <artifactId>${base_class_module}</artifactId>
   <version>${project.version}</version>
   <type>jar</type>
   <classifier>sources</classifier>
</dependency>

**Comment by stoicflame** [comment]
A better solution would be to tell Enunciate to download the sources from the depending `groupId`. By default, Enunciate only uses the sources that are in the same `groupId` of the current project. This is an effort to reduce the overhead of an attempt to download the sources of the entire dependency tree.

Here's how you do that:

```xml
      <plugin>
        <groupId>com.webcohesion.enunciate</groupId>
        <artifactId>enunciate-maven-plugin</artifactId>
        <version>${enunciate.version}</version>
        <executions>
          <execution>
            <id>assemble</id>
            <goals>
              <goal>assemble</goal>
            </goals>
            <configuration>
              <sourcepath-includes>
                <include>
                  <groupId>com.mycompany.group.id.of.dependency</groupId>
                </include>
              </sourcepath-includes>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
