### ISSUE TITLE
Do you have an ETA for supporting api-import?

### ISSUE THREAD

**Issue by rlc72** [stoicflame/enunciate#143]
I want to use enunciate 2.0 with a multi-module project. The classes that get mapped to JSON objects are in a different module than the resource classes. When I generate documentation it contains pages for the JSON objects but does not contain any of the object or attribute descriptions (beyond the binary type information). I am using the api-import directive and have a source code jar for the JSON classes in the same directory as the corresponding binary jar. I notice that the 2.0.0-M.4 code does not include Java to process the 'api-import' directive. 

Could you let me know roughly which milestone will make this functionality available, please?

Thank you in advance.

**Comment by stoicflame** [comment]
See #140.

**Comment by rlc72** [comment]
Thank you! The solution in 140 worked well.
