### ISSUE TITLE
Swagger UI shows only DELETE operation on resource with multiple operations.

### ISSUE THREAD

**Issue by gmtwc** [stoicflame/enunciate#145]
As  in example from the Enunciate v2 branch the resource with multiple operations for example 
GET /personext/{id}
DELETE /personext/{id} 

![screen shot 2015-09-15 at 1 16 53 pm](https://cloud.githubusercontent.com/assets/5023269/9887414/c0ae5cf4-5bac-11e5-9bc0-09f192cb876c.png)

shows properly on the Enunciate doc page.
The Swagger UI page shows only DELETE operation:

![screen shot 2015-09-15 at 1 17 57 pm](https://cloud.githubusercontent.com/assets/5023269/9887565/885a6518-5bad-11e5-8ca0-e326c44caa6a.png)

**Comment by stoicflame** [comment]
Bug. Thanks for the report.

**Comment by stoicflame** [comment]
Fixed at 5eaf9d9.
