### ISSUE TITLE
@XmlTransient fields are excluded from XML docs but not from JSON docs

### ISSUE THREAD

**Issue by ewan-chalmers** [stoicflame/enunciate#149]
I have JAXB classes with `@XmlRootElement @XmlRootElement @XmlAccessorType(XmlAccessType.PROPERTY`. Some get methods are marked `@javax.xml.bind.annotation.XmlTransient`

In the output docs, the transient properties are correctly excluded from the XML data types. But they are included in the JSON data types.

I'm using 2.0.0-M5 with the enunciate Ant task.

build.xml:

        <enunciate dir="${src.java.dir}" buildDir="${build.dir}" configFile="enunciate.xml">
            <include name="**/*.java"/>
            <classpath>
                <path refid="compile.classpath"/>
                <path refid="enunciate.classpath"/>
        	</classpath>
        </enunciate>

enunciate.xml:

    <enunciate>
          <title>My API</title>
          <description>My API description/description>
          <modules>
                  <jaxrs groupBy="path"/>
                  <jaxb/>
                  <jackson honourJaxb="true"/>
                  <docs/>
                  <swagger/>
          </modules>
    </enunciate>

ivy.xml configuration for the enunciate.classpath:

     <dependency org="com.webcohesion.enunciate" name="enunciate-core-annotations" rev="2.0.0-M.5"/>

     <dependency org="com.webcohesion.enunciate" name="enunciate-core" rev="2.0.0-M.5" conf="enunciate->default"/>
     <dependency org="com.webcohesion.enunciate" name="enunciate-rt-util" rev="2.0.0-M.5" conf="enunciate->default"/>
     <dependency org="com.webcohesion.enunciate" name="enunciate-jaxrs" rev="2.0.0-M.5" conf="enunciate->default"/>
     <dependency org="com.webcohesion.enunciate" name="enunciate-jaxb" rev="2.0.0-M.5" conf="enunciate->default"/>
     <dependency org="com.webcohesion.enunciate" name="enunciate-jackson" rev="2.0.0-M.5" conf="enunciate->default"/>
     <dependency org="com.webcohesion.enunciate" name="enunciate-docs" rev="2.0.0-M.5" conf="enunciate->default"/>

**Comment by stoicflame** [comment]
Enunciate 2.0 split out the JSON model from the XML model. The annotation to exclude JSON data types is `@JsonIgnore`.

**Comment by ewan-chalmers** [comment]
OK thanks. FWIW, I think it's a pity, as from a JAX-RS application point of view, `@XmlTransient` (and other jaxb annotations) is all that's needed to control both XML and JSON serialization. Here, I'll need to include an Enunciate dependency in the service code in order to get documentation to behave as the service does.

**Comment by stoicflame** [comment]
Fair enough, but don't you have that annotation already as a dependency if you're producing JSON at all?
