### ISSUE TITLE
Question: JAX-RS annotations used for enunciate doc?

### ISSUE THREAD

**Issue by chibi03** [stoicflame/enunciate#152]
Hi, 
I'm new to enunciate and was wondering what annotations are used in enunciate to generate the RESTdoc? Or is it using JavaDoc?

Thanks!

**Comment by stoicflame** [comment]
Pretty much all of [the standard JAX-RS annotations](https://docs.oracle.com/javaee/6/api/javax/ws/rs/package-summary.html), plus any of the [JAXB annotations](https://docs.oracle.com/javaee/5/api/javax/xml/bind/annotation/package-summary.html) if you're using JAXB, plus any of the [Jackson annotations](https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations) if you're using Jackson, plus any of the [JAX-WS annotations](http://docs.oracle.com/cd/E13222_01/wls/docs103/webserv_ref/annotations.html) if you're using SOAP.

**Comment by chibi03** [comment]
Thanks!
