### ISSUE TITLE
Documentation of enum-values

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#154]
I'm still using the v2.0.0-M3, so this might be fixed. Haven't had the time to check further.

Documentation of enum-values are not showing.

**Comment by stoicflame** [comment]
I'm seeing it show up for both XML and JSON. Attaching a screenshot.

![screenshot from 2015-09-24 09 46 00](https://cloud.githubusercontent.com/assets/145838/10078292/3902c514-62a1-11e5-8c42-a0a10aa5cc1c.png)
