### ISSUE TITLE
Change resource name in documentation

### ISSUE THREAD

**Issue by nuevedientes** [stoicflame/enunciate#157]
Is there a way to display a different name for a resource in the enunciate documentation other than the class name?
For example, if my code looks like:

@Path("services/user")
public class UserResource
{
...
}

Then in the documentation under REST resources it shows up as "UserResource".  Is there a way I can make it show up as simply "User"?

**Comment by stoicflame** [comment]
Yep.

```java
import com.webcohesion.enunciate.metadata.rs.ResourceLabel;

@ResourceLabel("User")
@Path("services/user")
public class UserResource
{
...
}
```

**Comment by nuevedientes** [comment]
Cool thanks.  Looks like as of 2.0 @ResourceLabel is available on classes.  1.3 seems like it's only available on methods.

**Comment by stoicflame** [comment]
Correct.
