### ISSUE TITLE
Minor default layout change request

### ISSUE THREAD

**Issue by gmtwc** [stoicflame/enunciate#159]
In V2 default front page layout the paragraph containing references to WADL and Swagger UI is in the bottom of the Resource page.  Can it be moved to the top of the page so that those links are easily discovered by the users?

Thanks!

**Comment by stoicflame** [comment]
Done at fd7885b. I've deployed 2.0.0-SNAPSHOT; you're welcome to try it out if you want to use the [OSSRH snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/).

**Comment by gmtwc** [comment]
Thank you !
