### ISSUE TITLE
Unknown artifact 'docs'

### ISSUE THREAD

**Issue by nuevedientes** [stoicflame/enunciate#160]
After upgrading to Enunciate 2.0 I'm getting the following message when I build with ant.  The war is already built, and I'm following the instructions here: https://github.com/stoicflame/enunciate/wiki/Executables#ant

Skipping documentation source generation as everything appears up-to-date...
[javac] 
Unknown artifact 'docs'.  Artifact will not be exported.

I have the enunciate jars on the classpath, here's what my target looks like:

	<target name="enunciate2">
	    <path id="enunciate.classpath">
 		 	<fileset dir="${enunciate.home}/lib">
   		 		<include name="*.jar"/>
  			</fileset>
 		 	<fileset dir="WebContent/WEB-INF/lib">
				<include name="*.jar" />
			</fileset>
			<fileset dir="build-output">
				<include name="*.jar" />
			</fileset>
			<fileset dir="${java.home}">
				<include name="lib/tools.jar" />
			</fileset>
			<fileset dir="${tomee.home}">
				<include name="lib/cxf*.jar" />
			</fileset>
		</path>

		<taskdef name="enunciate" classname="com.webcohesion.enunciate.EnunciateTask">
 		 	<classpath refid="enunciate.classpath"/>
		</taskdef>

		<enunciate basedir="src">
 		 	<include name="**/*.java"/>
  			<classpath refid="enunciate.classpath"/>
  			<export artifactId="docs" destination="build-output/docs"/>
 		 	<javacArgument argument="-g"/>
		</enunciate>
	</target>

**Comment by stoicflame** [comment]
Would specifying a `buildDir` fix it?

```xml
<enunciate basedir="src">
  <include name="**/*.java"/>
  <classpath refid="enunciate.classpath"/>
  <export artifactId="docs" destination="build-output/docs"/>
  <javacArgument argument="-g"/>
</enunciate>
```

That parameter needs to be required, and the documentation needs to be fixed. I'm going to fix the Ant task to throw an error if that attribute isn't there.

**Comment by stoicflame** [comment]
Doh! Forgot to specify a buildDir in my example... Editing that comment...

**Comment by stoicflame** [comment]
The wiki has been updated and the `buildDir` made a requirement at 1804963. Please re-open if that doesn't fix the problem.

**Comment by nuevedientes** [comment]
That worked.  The new format of 2.0 looks great!
