### ISSUE TITLE
addition of invalid data type to the model

### ISSUE THREAD

**Issue by stoicflame** [stoicflame/enunciate#161]
```java
  @XmlAttribute
  @XmlJavaTypeAdapter(SelectionPluginAdapter.class)
  public Class<? extends SelectionPlugin> getPlugin()
```

```SelectionPluginAdapter``` is an ```XmlAdapter<String, Class<? extends SelectionPlugin>>``` and the user only ever interacts with the String so I don't think enunciate should expose Class<?> in the documentation or even scan it.

**Comment by stoicflame** [comment]
The JAXB module was handling this fine. The problem was in the Jackson module, which doesn't recognize `@XmlJavaTypeAdapter` unless you do one (any) of the following:

1. Make sure you've got `com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector` if you're using Jackson 2.
2. Make sure you've got `org.codehaus.jackson.xc.JaxbAnnotationIntrospector` if you're using Jackson 1.
3. Configure Enunciate jackson module to honor JAXB annotations using the `honorJaxb` attribute of the `<jackson>` or `<jackson1>` configuration element.
4. Use the native Jackson 2 adaptation technique using an instance of `com.fasterxml.jackson.databind.util.Converter` and the `@JsonSerialize` annotation.

**Comment by rcpoison** [comment]
Could you please elaborate?

```
<plugin>
				<groupId>com.webcohesion.enunciate</groupId>
				<artifactId>enunciate-maven-plugin</artifactId>
				<version>2.0.0-SNAPSHOT</version>
				<configuration>
					<configFile>src/conf/enunciate.xml</configFile>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>assemble</goal>
						</goals>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>com.fasterxml.jackson.module</groupId>
						<artifactId>jackson-module-jaxb-annotations</artifactId>
						<version>2.6.1</version>
					</dependency>
				</dependencies>
			</plugin>
```
No change, Class gets added.

```
<modules>
		<jackson honorJaxb="true" />
</modules>
```
No change, Class gets added.


Also updated the test project at https://github.com/rcpoison/enunciate2test

**Comment by rcpoison** [comment]
Uhm, please ignore ... I should hit save before compiling ...
