### ISSUE TITLE
JSON Section is listed twice

### ISSUE THREAD

**Issue by nuevedientes** [stoicflame/enunciate#165]
I have two identical JSON sections in my Enunciate 2 generated documentation under DataTypes & in the navigation bar. Both links for each type takes me to the same json_mytype.html page.  Also, when I click either of the JSON sections in the navigation, both JSON items are highlighted in the nav bar and it always takes me to the first one in the documentation.  

Is there a way to make this show up just once like the xml section shows up only once?

I had a similar problem in enunciate 1 where there was a DataType section and a DataElement section, but at least the links took me different places.

Also, in Enunciate 1.3, the names of my types matched whatever I set as the @XmlType(name="") and @XmlRootElement(name="").  In Enunciate 2 it's the class name that shows up in the docs.

**Comment by stoicflame** [comment]
That's weird. Can you attach a screenshot?

It might be because you've got both Jackson 1 and Jackson 2 on your classpath, so there are two different JSON models being documented. Could you eliminate your dependencies on one or the other?

> Also, in Enunciate 1.3, the names of my types matched whatever I set as the @XmlType(name="") and @XmlRootElement(name=""). In Enunciate 2 it's the class name that shows up in the docs.

Yes, that's because Enunciate 2 added first-class support for JSON. So the JSON data types don't take into account the JAXB annotations. AFAIK, Jackson doesn't have a way to "name" a data type. Do you happen to know of a way to use Jackson annotations to name a data type? Or can you suggest a good way to name a JSON data type?

**Comment by nuevedientes** [comment]
I'm building with the sample build.xml on the "invoking enuncate" page.  

<path id="enunciate.classpath">
  <fileset dir="${enunciate.home}/lib">
    <include name="*.jar"/>
  </fileset>
</path>

I see that enunciate.home/lib contains jars from both jackson 1 and 2.  There are also 2 jars "enunciate-jackson.jar" and "enunciate-jackson1.jar".  I am not adding any additional jackson jars to my classpath.

I'm new to jackson so I don't know off the top of my head, but if I come across some way to name a JSON data type I'll let you know.

![screenshot](https://cloud.githubusercontent.com/assets/1459928/10150313/d3d4305a-660c-11e5-8c6f-5763faa4301a.png)

**Comment by stoicflame** [comment]
Okay, so I updated the [docs on the Executables page](https://github.com/stoicflame/enunciate/wiki/Executables#example-1) to reflect the fact that the classpath you use to compile your Java sources should be different from the classpath you use to define the Enunciate task. The latter will have both Jackson 1 and Jackson 2 jars on the classpath; the former shouldn't.

**Comment by stoicflame** [comment]
I've opened up #169 as an enhancement request to be able to adjust the label. It's currently scheduled for 2.1.0.
