### ISSUE TITLE
Docs export fail on second run

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#168]
I'm working on a Gradle plugin for Enunciate, so this problem may be because I don't understand the Enunciate programmatic API rather than a bug per se.

I'm trying to generate docs output only, so I add an export for 'docs' to a folder.

On first run, enunciate will generate the documentation. So everything is peachy.

But on second run, it outputs:
```
[ENUNCIATE] Skipping documentation source generation as everything appears up-to-date...
[ENUNCIATE] Unknown artifact 'docs'.  Artifact will not be exported.
```

I can see why it would not do anything, as everything is already done (in respect to the enunciate build dir, anyway).
But it then fails to handle the docs export.

When I delete the export target folder, I would expect a re-export.
Am I missing something?

**Comment by stoicflame** [comment]
Fixed at 4f7463f. Thanks for the report.
