### ISSUE TITLE
REST mountpoint in 2.0

### ISSUE THREAD

**Issue by rcpoison** [stoicflame/enunciate#172]
Hi ^^
How do you specify the rest mountpoint in 2.0? 
```services.rest.defaultRestSubcontext``` is gone, ```application.root``` doesn't seem to do anything and the docs module only has the option to disable it.

**Comment by stoicflame** [comment]
As described in [JAX-RS Module Docs](https://github.com/stoicflame/enunciate/wiki/Module-JAXRS):

```xml
<enunciate>
  <modules>
    <jaxrs>
      <application path="/contextpath"/>
```

Also, if you've got a class annotated with `@ApplicationPath`, Enunciate will pick that up.
