### ISSUE TITLE
Invoking enunciate with Enunciate.java requirements

### ISSUE THREAD

**Issue by chibi03** [stoicflame/enunciate#173]
What are the required settings (i.e. setting Classpath, modules, etc) for the invocation via Enunciate.java to work? Is a enunciate.xml still required? 

Thanks!

**Comment by stoicflame** [comment]
I've updated the [Executables page](https://github.com/stoicflame/enunciate/wiki/Executables#programmatic-interface) to reflect additional documentation.

Here's a summary of the configuration properties that might be worth using:

property|description
--------|-----------
`buildDir`|The working directory where Enunciate will put its output files. There is no default; this property needs to be set.
`modules`|The list of [[Enunciate modules|Modules]] to use. The default is an empty set, but the `loadDiscoveredModules` method will set the module list to be the list of those discovered on the thread classpath.
`configuration`|The Enunciate configuration. This is a read-only property, but a file can be loaded using the `loadConfiguration` method.
`exports`|The map of artifacts ids to files to which to export the artifacts generated by Enunciate.
`sourceFiles`|The list of source files on which to invoke the compiler and the Enunciate engine. The default is an empty set.
`classpath`|The classpath to use for the compiler used to invoke the Enunciate engine. The default is the empty set.
`sourepath`|The sourepath to use for the compiler used to invoke the Enunciate engine. The default is the empty set.
`compilerArgs`|The list of extra arguments to pass to the compiler used to invoke the Enunciate engine.
`logger`|The logger to which Enunciate writes its messages.
`includePatterns`|The list of patterns of classes to include with the Enunciate engine. The default is the empty set.
`excludePatterns`|The list of patterns of classes to exclude from the Enunciate engine. The default is the empty set.
