### ISSUE TITLE
Including Other Json Objects

### ISSUE THREAD

**Issue by theCompanyDream** [stoicflame/enunciate#175]
Hello It's me again I was wondering if I could include other libraries in the enunciate documentation and is it possible to specify multiple typehints? Our Event Service takes multiple inherited objects of an event object and  I was trying to add oEvents inherited types in the current project, but it will only generate the rest resources and any objects associated with it

My questions are
1. How do you tell Enunciate what packages to build documentation on?
2. Can I use more than one typehint?
3. Can I generate documentation on a class that my api isn't currently using?

**Comment by stoicflame** [comment]
> How do you tell Enunciate what packages to build documentation on?

Use `api-classes`:

```
<enunciate>
  <api-classes>
    <include pattern="com.mycompany.package.*"/>
    <include pattern="com.mycompany.other.*"/>
```

> Can I use more than one typehint?

No, but I'll track that feature request at #177.

> Can I generate documentation on a class that my api isn't currently using?

Yes, but you'll probably need to use "aggressive" datatype detection on the JAXB and/or Jackson modules:

```xml
<enunciate>
  <modules>
    <jaxb datatype-detection="aggressive"/>
    <jackson datatype-detection="aggressive"/>
```

If your classes are in the same project as the one Enunciate is getting invoked on, then you might be able to get away with "local" datatype detection.
