### ISSUE TITLE
support for javadoc inheritance

### ISSUE THREAD

**Issue by rcpoison** [stoicflame/enunciate#178]
Javadoc from implemented interfaces and superclasses is not inherited in the resources/models.

**Comment by stoicflame** [comment]
Acknowledged. Tracking this as an enhancement request.

**Comment by stoicflame** [comment]
This enhancement is currently seeking a sponsor. If anybody is willing to sponsor the work, [reach out to me](http://webcohesion.com/#contact) and I'd be happy to pick it up.

**Comment by stoicflame** [comment]
Thanks to the support of a generous sponsor, this issue has been implemented and will be included in 2.9.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
