### ISSUE TITLE
XmlSchemaType DateTime results integer value in JSON example

### ISSUE THREAD

**Issue by waytooearly** [stoicflame/enunciate#179]
We are using CXF for our restful services.  Enunciate is not honoring the annotation XmlSchemaType of dateTime.

```java
/**
     * Indicates whether the object is active.
     */
    private boolean active; 

 /**
     * The date and time that the object was created.
     */
    @NotNull
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    private Date creationTimestamp;
```

Results with:
```
{
  "active" : true,
  "creationTimestamp" : 12345.0
}
```

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
So [Jackson doesn't support the `@XmlSchemaType` annotation](http://wiki.fasterxml.com/JacksonJAXBAnnotations#JAXB_annotations_very_unlikely_to_ever_be_supported). How does the Jackson processor know that the `creationTimestamp` field is serialized as a String?

**Comment by stoicflame** [comment]
At #187, I added support for using `@TypeHint` to specify data types. So this case can now be covered by applying `@TypeHint(String.class)`.

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)
