### ISSUE TITLE
Description is not provided in the responseBody for Restful endpoints

### ISSUE THREAD

**Issue by waytooearly** [stoicflame/enunciate#180]
Enunciate is not showing the javadoc @return value in the response body for restful methods using CXF.  It does though, show them for XML types in the documentation.

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
Fixed at 31cf7f1.

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)
