### ISSUE TITLE
Duplicate Java source file - location not being printed

### ISSUE THREAD

**Issue by chibi03** [stoicflame/enunciate#184]
Hi,
I noticed that the location of the duplicate Java source files isn't being printed:
`[ENUNCIATE] Java source file com/internal/rt/jaxrs/resteasy/providers/JsonMessageBodyWriter.java will not be included on the classpath because it is found in multiple locations: `

One of the format specifies seems to be missing:
`getLogger().warn("Java source file %s will not be included on the classpath because it is found in multiple locations: ", javaFile, locations);`

Thanks.

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
Fixed at 22e7212.

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)
