### ISSUE TITLE
Documentation-only goal for Enunciate 2?

### ISSUE THREAD

**Issue by Mykro** [stoicflame/enunciate#188]
I'm attempting to retrofit Enunciate 2 to a pre-existing app with standard JAX-RS annotations.    Note that the app uses a Jersey2 + Grizzly HttpServer container and jar packaging - there is no HttpServlet or WAR involved.

My POM has the following blocks:

			<plugin>
				<groupId>com.webcohesion.enunciate</groupId>
				<artifactId>enunciate-maven-plugin</artifactId>
				<version>2.0.0</version>
				<executions>
					<execution>
						<goals>
							<goal>assemble</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

and 

		<dependency>
			<groupId>com.webcohesion.enunciate</groupId>
			<artifactId>enunciate-maven-plugin</artifactId>
			<version>2.0.0</version>
		</dependency>

My build produces the error:

[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.0.0:assemble (default) on project MY_PROJECT: The 'assemble' goal requires 'war' packaging. -> [Help 1]

The FAQs indicate that there was a "Docs" goal for Enunciate 1 which might have addressed my need, but it doesn't seem to be supported in Enunciate 2.  Is there some other way to go about this?  All I'm after is compile-time generation of nice documentation.  I'd be very grateful for any assistance anyone can offer, thanks!

**Comment by stoicflame** [comment]
Enunciate 2 is documentation-only by design.

https://github.com/stoicflame/enunciate/wiki/Migration-Guide

If you're not using `war` packaging, you'll probably want to use the `docs` goal.

https://github.com/stoicflame/enunciate/wiki/Executables

```xml
<plugin>
  <groupId>org.webcohesion.enunciate</groupId>
  <artifactId>maven-enunciate-plugin</artifactId>
  <version>2.0.0</version>
  <executions>
    <execution>
      <goals>
        <goal>docs</goal>
      </goals>
      <configuration>
        <!-- the directory where to put the docs -->
        <docsDir>${project.build.directory}/docs</docsDir>
      </configuration>
    </execution>
  </executions>
</plugin>
```

**Comment by Mykro** [comment]
First, thank you for updating the wiki.  Could you please check the groupId and artifactId you've listed here and in the wiki for Enunciate 2?  For me only 'com.webcohesion.enunciate' and 'enunciate-maven-plugin' actually work.

**Comment by stoicflame** [comment]
Yep. Thanks.
