### ISSUE TITLE
Multiple MediaType support 

### ISSUE THREAD

**Issue by dorotaradomanska** [stoicflame/enunciate#189]
When I Introduce 
```java
@Consumes({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
```
I don't get a proper documentation, because there is only one param
```java
@param authentication The {@link AuthenticationRequest} representing the input payload.
```
and enunciate expects two.
the current outcome is:
```html
Request Body media type 	data type 	description
application/json 	(custom) 	The {@link AuthenticationRequest} representing the input payload.
application/xml 	(custom) 
```

```java
@Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
```
also doesn't work.

**Comment by stoicflame** [comment]
The documentation isn't saying there are multiple parameters; it's saying there are multiple options for the request body (xml and json).

**Comment by dorotaradomanska** [comment]
![enunciate_multiplemediatype](https://cloud.githubusercontent.com/assets/2460882/10599782/8443e42c-7705-11e5-94a6-5bd914e9ad11.png)
Should empty line be read as 'as above' regarding the param description?

**Comment by stoicflame** [comment]
So it's hard to notice, but the description spans all the rows...
