### ISSUE TITLE
Jaxb property & data type description not populated

### ISSUE THREAD

**Issue by chibi03** [stoicflame/enunciate#191]
Hi, 
I have a lot of JavaDoc in my classes but other that the class JavaDoc of the `@XmlRootElement` none of them show up. The description in the property tables is empty regardless of which class type and the class Javadoc of my non root elements is not used.

Are there specific areas I should be adding the Javadoc to or should I be using some specific annotations?

Thanks.

**Comment by stoicflame** [comment]
It should work. I'm going to need some sample code or other way to reproduce the issue to identify this particular problem.

**Comment by chibi03** [comment]
I put an example here: https://github.com/chibi03/enunciateJaxbBug
If you look at the class BookViral the JavaDoc I added doesn't show up. On contrary there is no problem in the classes annotated wit `@XmlRootElement`.

**Comment by stoicflame** [comment]
Okay. How do I run it? It's neither Ant nor Maven.

**Comment by chibi03** [comment]
Apologies, I'm running it via Java so I neglected to add a build.xml, I've added it now.

I've also tested some more, and when I run enunciate over source code I do get the class level JavaDoc of `@XMLElements`, but still no descriptions of the properties.
When I run enunciate over packaged (JAR) source code, it doesn't show any of the JavaDoc in the `@XMLElements`.

**Comment by nikboyd** [comment]
I've run into similar problems with both the model class descriptions and property descriptions. You can find a working example here. https://github.com/nikboyd/axiom-lib-java

**Comment by chibi03** [comment]
Do you know what exactly fixed the issues for you?

**Comment by nikboyd** [comment]
Sorry I was not clearer. The problems still exist. The working example shows the problems you've described in the docs generated by enunciate and served up by the example service. But, the service needs to be built and run in order to see the results.

**Comment by stoicflame** [comment]
So your JAXB annotations are on the _field_, not the property. That means that the fields are getting used for JAXB accessors, and Enunciate is looking for the JavaDoc on the field, not the getter.

```java
/**
 * 
 * states if the Book is currently viral
 */
 @XmlElement(name="viral")
 private boolean isViral;
```

**Comment by xkacer** [comment]
I have an opposite problem (with the same symptoms). Both annotations and JavaDoc are present on private fields but Enunciate seems to take them from getters/setters only, which leaves most of the attribute descriptions empty.
Is the javadoc on _fields_ supposed to work with the **JAX-RS** module?
(sorry I ask here but it seems to be a very similar issue)

**Comment by stoicflame** [comment]
Enunciate's documentation is pulled from whatever is getting used by the implementation. So if you annotated your fields in such a way that they are being used by JAX-RS, Enunciate will use the documentation on those fields. Likewise for properties.

**Comment by xkacer** [comment]
Thanks for a quick response (and for developing enunciate, in the first place). It is not hundred-percent exact however, as it assumes a _default_ configuration of JAX-RS (and Jackson).
Meanwhile, I already searched the enunciate source codes and found out that the behavior is controlled by `JsonAutoDetect` annotation - which is basically what you said.
There is one important difference, though: JAX-RS may be configured to use a different field visibility (default value of `JsonAutoDetect`) without the need to annotate each class individually. Which is impossible with enunciate I'd say.
I even consider implementing that feature by myself - would you be interested? If so, what is a correct way? Creating an issue for it, eventually implementing, and then asking for a pull/merge?

**Comment by stoicflame** [comment]
Enunciate should pick up private fields if they're annotated correctly (e.g. `@QueryParam`, `@HeaderParam`, etc.).

Are you observing otherwise?

**Comment by xkacer** [comment]
Well, it works for JAX-RS attributes (`@QueryParam`, `@BeanParam`, etc.). It does not work for Jackson fields (e.g., `@JsonProperty`) - sorry if I was unclear in this.
In particular, if there is a documented private field with an undocumented getter and setter, no JavaDoc is found and the field has no description (it is still displayed, as the getter/setter pair is detected, but no JavaDoc).
The behavior changes if `@JsonAutoDetect` is applied to the class changing the `fieldVisibility` to `PRIVATE`. Then the JavaDoc on the field is found and used as a description.
For obvious reasons, I do not want to annotate each of my classes individually.
What I suggest is adding a new config option (in the same place as `honorJaxb`, for instance) that would change the default visibility value. Jackson allows this too, by configuring it's `ObjectMapper`. It is definitely an enhancement, not a bug.

**Comment by stoicflame** [comment]
So you want a configuration option to tell Enunciate to prefer the private the fields instead of the public properties, even if Jackson itself is using the public properties at runtime. Is that accurate?

If so, you're welcome to open up a separate issue. I'll mark it as an enhancement request and assign it to 2.9.

**Comment by xkacer** [comment]
Not to _prefer_ them. I just want to make them _visible_ - the same way `JsonAutoDetect` does (and also Jackson).
Enough of it here. I will begin a separate issue with more details. Will need some time to check a few things and come up with a meaningful proposal (possibly a little bigger than just this), which will be consistent with Jackson.
Thanks again for your response.

**Comment by xkacer** [comment]
Sorry it took me some time to get back to it.
New issue created as #627.
