### ISSUE TITLE
Why does "JSON" section show up twice?

### ISSUE THREAD

**Issue by stoicflame** [stoicflame/enunciate#194]
Add a section to the FAQ explaining that if you're seeing double on the JSON sections, it's because you've got both Jackson 1 and Jackson 2 on your classpath and you need to disable one or the other.

**Comment by waytooearly** [comment]
This can also occur if you have jackson enabled and don't include {{honorJaxb="true"}} in the tag.

**Comment by stoicflame** [comment]
https://github.com/stoicflame/enunciate/wiki/Two-JSON-Sections

**Comment by guyh-tointv** [comment]
Hi,
I have the same problem. I have read the WIKI about it, but, unfortunately, I cannot understand how to handle it.

How do I remove the Jackson module? Or, alternatively, how do I disable it?

Thanks
H Guy

**Comment by stoicflame** [comment]
I've added example configuration to the wiki. Try it again.

**Comment by guyh-tointv** [comment]
Thanks.
It works :+1: 

H Guy
