### ISSUE TITLE
Maven multi module - getting "no source files or class names"

### ISSUE THREAD

**Issue by brunuh** [stoicflame/enunciate#196]
Hello,

First off, congratulations on the excellent work you have accomplished.

Now for the issue, I'm getting a "no source files or class names" when executing 

```
$ mvn clean enunciate-slim:docs -DskipTests
````

My project structure is as follows:

```
├── module1
├── module2
├── root
````

I'm executing the command on the root directory, which is the parent project for both module1 and module2.

There are no source files for the root project, this probably is what's causing the issue. Only when I add a Fake class with a jax-rs @Path annotation is the build able to continue to the modules.

Is there a way to bypass "empty" modules and still be able to process the child modules?

**Comment by stoicflame** [comment]
So if I understand correctly, you're trying to have Enunciate generate the documentation for module1, module2, and root, correct?

Which module is the "top-level" module? If you have an API, there would presumably be a module that depends on all of the other modules. This is the "top-level" module and the only one that should need Enunciate applied.

**Comment by brunuh** [comment]
The top-level module would be the module2.
We have an api for both module1 and module2, and that's probably why the configuration is on the root module (no sure on the story behind it :) ).

On enunciate 1 this would work, guess I'll give it a shot on moving the enunciate to module2 and see how it works out.

**Comment by brunuh** [comment]
I gave it a shot, and it doesn't work as I would have wanted it to work. I have module2 depending on module 1.

I have set up the the configuration for enunciate on module2.
```
 1             <plugin>
  2                 <groupId>com.webcohesion.enunciate</groupId>
  3                 <artifactId>enunciate-slim-maven-plugin</artifactId>
  4                 <version>${enunciate.version}</version>
  5
  6                 <executions>
  7                     <execution>
  8                         <phase>none</phase>
  9                         <goals>
 10                             <goal>docs</goal>
 11                         </goals>
 12                         <configuration>
 13                             <sourcepathIncludes>
 14                                 <include>
 15                                     <groupId>module1groupid</groupId>
 16                                 </include>
 17                             </sourcepathIncludes>
 18                         </configuration>
 19                     </execution>
 20                 </executions>
 21                 <dependencies>
 22                     <dependency>
 23                         <groupId>com.webcohesion.enunciate</groupId>
 24                         <artifactId>enunciate-docs</artifactId>
 25                         <version>${enunciate.version}</version>
 26                     </dependency>
 27                     <dependency>
 28                         <groupId>com.webcohesion.enunciate</groupId>
 29                         <artifactId>enunciate-jaxrs</artifactId>
 30                         <version>${enunciate.version}</version>
 31                     </dependency>
 32                 </dependencies>
 33             </plugin>
```

Have module1 configured with "attach-sources" and deployed to local repository.

```
  1                 <groupId>org.apache.maven.plugins</groupId>
  2                 <artifactId>maven-source-plugin</artifactId>
  3                 <version>2.2.1</version>
  4                 <executions>
  5                     <execution>
  6                         <id>attach-sources</id>
  7                         <phase>package</phase>
  8                         <goals>
  9                             <goal>jar</goal>
 10                         </goals>
 11                     </execution>
 12                 </executions>
 13             </plugin>
```
I have added module1's groupId to the sourcePathIncludes includes.

So, currently I don't have documentation for module1 and I'm left with two options:
1) stick with the initial option (create a fake class on root)
2) duplicate the configuration on module1

I'm sure there's a 3rd option involving the documentation on https://github.com/stoicflame/enunciate/wiki/Multi-Module-Projects but it's currently not working, any idea on what I'm missing?

**Comment by stoicflame** [comment]
Probably because you don't have all the needed modules.

Are you using JAXB? Are you using Jackson 1 or Jackson 2?

```
 1             <plugin>
  2                 <groupId>com.webcohesion.enunciate</groupId>
  3                 <artifactId>enunciate-slim-maven-plugin</artifactId>
  4                 <version>${enunciate.version}</version>
  5
  6                 <executions>
  7                     <execution>
  8                         <phase>none</phase>
  9                         <goals>
 10                             <goal>docs</goal>
 11                         </goals>
 12                         <configuration>
 13                             <sourcepathIncludes>
 14                                 <include>
 15                                     <groupId>module1groupid</groupId>
 16                                 </include>
 17                             </sourcepathIncludes>
 18                         </configuration>
 19                     </execution>
 20                 </executions>
 21                 <dependencies>
 22                     <dependency>
 23                         <groupId>com.webcohesion.enunciate</groupId>
 24                         <artifactId>enunciate-docs</artifactId>
 25                         <version>${enunciate.version}</version>
 26                     </dependency>
 27                     <dependency>
 28                         <groupId>com.webcohesion.enunciate</groupId>
 29                         <artifactId>enunciate-jaxrs</artifactId>
 30                         <version>${enunciate.version}</version>
 31                     </dependency>
 32                    <dependency>
 33                         <groupId>com.webcohesion.enunciate</groupId>
 34                         <artifactId>enunciate-jaxb</artifactId>
 35                         <version>${enunciate.version}</version>
 36                     </dependency>
 37                     <dependency>
 38                         <groupId>com.webcohesion.enunciate</groupId>
 39                         <artifactId>enunciate-jackson1</artifactId>
 40                         <version>${enunciate.version}</version>
 41                     </dependency>
 42                 </dependencies>
 43             </plugin>
```

**Comment by brunuh** [comment]
Thank you for helping out.
Unfortunately, I'm sure that's not the case, the issue must be something else, we don't use jaxb or either jackson. And with the configuration set up on root (with the class "hack"), I'm able to generate separate documentation for both module1 and module2.

**Comment by stoicflame** [comment]
Well Enunciate only supports JAXB, Jackson 1, and Jackson 2, so if you have any documentation generated, you're using one of those. Is it XML or JSON? If it's XML, you're using JAXB. If it's JSON, you're using one of the Jackson modules.

You may need to aggressively include data types as described at #175.

**Comment by brunuh** [comment]
The documentation we're generating is for the Resources only not for the data types.

Never the less your tip was great, in the end I changed the jars datatype-detection to aggressive and that solved the issue.

```
<jaxrs datatype-detection="aggressive"/>
```

Thansk alot.
