### ISSUE TITLE
Text formatting in Javadoc preformatted text blocks

### ISSUE THREAD

**Issue by gmtwc** [stoicflame/enunciate#203]
It appears that Enunciate strips the space / tabs in Javadoc preformatted text blocks:

```java
/**
* ...
*<pre>
Test line1
    - Text line 2
    - Text line 3
*</pre>
*/
```

procuces comment:

Text line 1
- Text line 2
- Text line 3

**Comment by stoicflame** [comment]
Duplicate of #77.

**Comment by gmtwc** [comment]
Thanks for the reference.

As a workaround I did include the line containing "&nbsp;" annotation after \<pre> and the whole block text formatting is preserved now.
