### ISSUE TITLE
@Ignore does not appear to have an effect on methods

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#206]
I have a rest resource with:

```
	@GET 
	@Path("account/get")
	@Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON})
	@Deprecated
	@Ignore
	public Account getAccountDeprecated(@Pattern(regexp="\\d{1,4}", message="Invalid regnr") @QueryParam("regnr") String regnr,
			                  @Pattern(regexp="\\d{1,10}", message="Invalid ktonr") @QueryParam("ktonr") String ktonr) {

```

It gets rendered (with 2.1.0) in the html documentation, marked as deprecated.

I would have expected it to be removed altogether.

Also, I did not find any documentation for the @Ignore annotation in https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations

**Comment by stoicflame** [comment]
I've updated the [Enunciate-Specific Annotations](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations) with some documentation on `@Ignore`:

> Used to suggest to Enunciate that the annotated class should be ignored, if possible. The class may not be able to be ignored if it's explicitly referenced from a service, resource, or data type that is not excluded.

It's not used to exclude methods or properties or other API elements; it's a processor directive. To exclude methods or properties or other API elements, use [Facets](https://github.com/stoicflame/enunciate/wiki/Facets).

**Comment by jskovjyskebankdk** [comment]
Thanks!
