### ISSUE TITLE
@link javadoc should be filtered

### ISSUE THREAD

**Issue by stoicflame** [stoicflame/enunciate#213]
Enunciate 2.1.1 isn't stripping out the `@link` javadoc tags.

**Comment by xpapad** [comment]
Is there a target date for this?

**Comment by stoicflame** [comment]
I'm hoping to get 2.2 out in the next week or two.

**Comment by stoicflame** [comment]
Fixed at 4c49093.

**Comment by stoicflame** [comment]
[Enunciate 2.2 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.2.0).
