### ISSUE TITLE
support for multiple path variables in same path segment

### ISSUE THREAD

**Issue by stoicflame** [stoicflame/enunciate#214]
Spring Web supports multi-variable path segments, e.g.:

```java
@RequestMapping("/spring-web/{symbolicName:[a-z-]+}-{version:\\d\\.\\d\\.\\d}{extension:\\.[a-z]+}")
    public void handle(@PathVariable String version, @PathVariable String extension) {
        // ...
    }
}
```

What about JAX-RS? If it does support this, we've got a bug.

**Comment by stoicflame** [comment]
I can't see where JAX-RS supports this, so I'm going to close this until I hear otherwise.

**Comment by manzke** [comment]
Hey JAX-RS supports it.

Example:
@Path("{who:current|me}")
public Response me(){}

This would allow a path /current or /me. who is the variable you inject into the method.
