### ISSUE TITLE
XmlTransient handling issue

### ISSUE THREAD

**Issue by samion** [stoicflame/enunciate#215]
We use inheritance in our project dto structure together with XmlTransient annotations for abstract parent class. We don't want to expose the abstract parent class in generated xsd. When upgrading from Enunciate 1.29 to 2.1.1 the handling of XmlTransient-annotation seems to be very different.

I created examples which show how the documentation and generated xsd are different when using the XmlTransient either in class level, field level or method level. In each case the parent type is shown in generated xsd. With 1.29 version it was not. What is the correct way to hide the abstract parent class from the xsd? At the end, ParentC - ChildC seems to provide the best behaviour out of the three.

Example material available here: https://github.com/samion/enunciate-xmltransient-issue

We also found out the generated documentation and xsd don't always match, depending on how the XmlTransient is used.

**Comment by stoicflame** [comment]
Thanks for the report. I'll take a look and get back to you.

**Comment by vguna** [comment]
Same here. Thanks for looking into this.

I could ignore the superclass with a facet, but it is still contained in the
details of a JSON subclass:

"Properties inherited from AbstractClassDto"
id

Would be cool if that info (that a superclass exists) could be hidden.

**Comment by stolp** [comment]
+1 for getting this resolved. IMHO in a perfect world the class model should not be visible to the consumer of the service.

Thanks for your efforts!

**Comment by stoicflame** [comment]
Fixed at cc67cd2.

**Comment by stoicflame** [comment]
[Enunciate 2.2 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.2.0).
