### ISSUE TITLE
support for enunciate xml config file validation

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#216]
Hi.

I'm migrating from Enunciate 1.29 to 2.1.1 and try to configure the new enunciate.xml. Some attributes have been renamed (e.g. enunciate's label to slug?), some have been removed (deployment tag?), some are new. While figuring this out, it seems that the XML isn't validated against the XSD. So it's really hard to tell, whether settings in the XML are wrong, ignored or simply mis-typed.
A build just runs through without an ERROR. If I break well-formedness, It correctly complains about that - just to make sure I'm working with the correct file.

BTW: is there any chapter in the migration guide that says something about the changed xml?

**Comment by vguna** [comment]
Ok. Found this in the XSD itself:

"The Enunciate configuration schema. This is provided primarily for documentation purposes and to support code editors that support XML schema validation. When Enunciate parses the configuration file, there is no validation performed. This is because Enunciate can be extended with other modules that might have additional configuration options not shown in this schema."

What about putting custom modules to a separate tag within the XML and define them with xs:any?

Like:

```xml
<customModules>
   <myFancyNonValidatedConfigForModuleDoe />
</customModules>
```

**Comment by stoicflame** [comment]
So is this a request for Enunciate to do the validation?

**Comment by vguna** [comment]
Yes, please :). I think that would help much. In the end I configured the XML Catalog in Eclipse to get content assist. Before, I was never sure if my settings were ok.

BTW: Great work you've done with the 2.x release. Looks very promising!

**Comment by stoicflame** [comment]
This issue has been stale for over a year, and I'm pretty comfortable with the choice to not do config file validation.
