### ISSUE TITLE
application.wadl appears under REST Resources overview

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#217]
Generating the enunciate docs with 2.1.1 and idl module enabled, seems to add the generated application.wadl to the Resources overview on the start page - where the other REST resources are listed. It looks like this:

/application.wadl                GET
/applicaiton.wadl/{path}      GET

I wonder where that comes from :). I can remember, that it worked before, but suddenly it appeared somehow.

**Comment by stoicflame** [comment]
Thanks for the report. Scheduled for 2.2.

**Comment by stoicflame** [comment]
Fixed at 5bcf3c5.

**Comment by stoicflame** [comment]
[Enunciate 2.2 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.2.0).
