### ISSUE TITLE
duplicate HTTP methods under resource

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#218]
Generating the enunciate docs with 2.1.1 leads to duplicate HTTP method listings under the select resource. For example:

/account     GET, POST

Selecting that from the Resource overview, will lead to the details page of that resource where the HTTP methods are listed. There, as well as in the sidebar on the left, there are 4 entries.

GET
POST
GET
POST

I'm using the REST grouping by path.

I can remember that it worked some time, but now it stays broken :).

Any idea what I'm facing here?

**Comment by vguna** [comment]
Ok, I found out what's happening here.

I've got two separate maven projects:

app-api: contains only the JAX-RS interfaces and the models, including the javadoc documentation
app-impl: contains the impls of the app-api and creates the war and the REST documentation using enunciate

In addition, I've applied explicit includes on the app-api interface classes in the enunciate.xml. If I've read the docs of the enunciate jax-rs module correctly, this switches the datatype-detection from passive to aggressive. I think this leads to the effect, that it recognizes the endpoints twice (?). One time on the app-api module and another time on the app-impl module. I've tried to exclude the impl packages, but that didn't work out.

Finally what worked out was, to set the detection to "local" on the jax-rs module. So there aren't any duplicates anymore and the application.wadl mentioned in #217 is also gone.

What is the best practice in situations like these?

**Comment by stoicflame** [comment]
Finally visiting this issue, I'm unclear what a good fix might be. Setting "local" datatype detection seems like a good idea to me; I'm not sure how to otherwise detect duplicates.

Thoughts?

**Comment by vguna** [comment]
Hm. When `local` is the way to go in this situations I'm OK with that.
To detect duplicate resources one could check if a class or interface already exists having the same  `@Path` annotation. But that sounds too easy I guess ;).

**Comment by stoicflame** [comment]
> one could check if a class or interface already exists having the same `@Path` annotation.

The problem with that is that some JAX-RS implementations might actually allow that as a valid case. I haven't found any statements in the spec that says resource classes must have unique `@Path` values. I understand that _Jersey_ requires unique `@Path` values, but what about all the other implementations?

**Comment by stoicflame** [comment]
Okay, so I see a bit better now. It should be pretty safe to remove resources with the same class, same path.

Fixed at b242116.

**Comment by stoicflame** [comment]
[Enunciate 2.2 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.2.0).

**Comment by ke5stl** [comment]
I am seeing duplicates again appearing in the wadl.

**Comment by stoicflame** [comment]
Getting around to looking at this. @ke5stl can you provide come details about how to reproduce this?

**Comment by ke5stl** [comment]
I am working on an example to demonstrate this issue.

**Comment by ke5stl** [comment]
I have a sample that demonstrates the issue I'm seeing.  Can I email it to you?

**Comment by ke5stl** [comment]
email has been sent with zip of sample for this issue.  did you receive it?

**Comment by stoicflame** [comment]
Yes. Thank you.

In your case, the duplication is in your own code because you've got two classes annotated with the same path. One is an interface (`IThing1Resource`) and the other implements that interface (`Thing1Resource`). Removing the `@Path` annotation on the interface removed the duplication. 

At 8b18aa7 I added logic that caught this case.

**Comment by ke5stl** [comment]
interesting.  thank you!
peter

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
