### ISSUE TITLE
Description for app in enunciate.xml cuts off at first comma

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#219]
With 2.1.1 I tried to set a description for the start page - since the package-info.java doesn't seem to get taken into account anymore (coming from 1.x).

But setting the description in the enunciate.xml via <description> tag cuts off the text at the first comma (,) it encounters.

BTW: is it still possible to document the main page description via javadoc somehow? Maybe on the root resource or something?

**Comment by stoicflame** [comment]
I have no idea why the description would get cut off at the first comma, so I'll look into that for 2.2.

You can pass a package-info JavaDoc as the description like this:

```xml
<enunciate>
  <description package="com.mycompany.mypackage"/>
```

**Comment by vguna** [comment]
Sweet! RTFM, I guess ;).

But this doesn't seem to work. It just prints "WebApp".
Maybe it has something todo with my separate maven projects?
app-api and app-impl? I've already did the attach-source as mentioned in the FAQ. It's already getting the javadoc from there for the resource/model documentation. So why is it failing for the package-info?

**Comment by stoicflame** [comment]
At 52156f2, I added a package description and verified that it's showing up correctly in the generated documentation.

There must be something specific to your project. Maybe there are multiple `package-info` files for that package? The only think Enunciate is doing to look up the description is [asking the underlying Javac engine for the JavaDocs of the configured package](https://github.com/stoicflame/enunciate/blob/master/core/src/main/java/com/webcohesion/enunciate/EnunciateConfiguration.java#L85-L90).

So for whatever reason, the Java compiler thinks that "WebApp" is the JavaDoc for that package.

**Comment by stoicflame** [comment]
At bbf06c1, fixed the cut-off at first comma.

**Comment by stoicflame** [comment]
[Enunciate 2.2 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.2.0).
