### ISSUE TITLE
Two embedded enums with same name - one is lost in documentation

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#222]
I'm using 2.1.1 to generate the REST documentation for my DTOs. There are two DTOs which have an
embedded State enum. When generating the documentation, one enum is missing.

Obviously this is due to a name clash, I guess. I've applied different @JsonRootElement and @Label to both of them. But with the same result.

So I think the naming could be more flexible. Either, take the "labels" and check if there are duplicates. If so, complain. If there are no "labels" set, at least prepend the parent's class name to the enums name, maybe with a delimiter.

Does this make sense :)?

**Comment by stoicflame** [comment]
Using `@Label` worked for me, as proved at 847af78.
