### ISSUE TITLE
Javadoc from @BeanParam's @QueryParams missing

### ISSUE THREAD

**Issue by pswvg** [stoicflame/enunciate#225]
Creating the REST documentation with 2.1.1 seems to ignore the javadoc on `@QueryParam`s which are nested within `@BeanParam`s. Example:

```java
    /**
     * Returns a list of available foos for the current account.
     *
     * @param query
     *            a query to select specific foos.
     * @param paging
     *            the paging parameters like "limit" and "offset".
     * @param sorting
     *            the sorting parameters like "sort".
     * @return the foo list.
     */
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    Set<FooDto> list(@BeanParam Query query, @BeanParam Paging paging, @BeanParam Sorting sorting);
```

```java
public class Paging {
    /**
     * The offset to use for the paging. It defines at which position within the results to start.
     */
    @QueryParam("offset")
    private int offset;

    /**
     * The maximum number of results to return. Defines how many results should be contained within a page.
     */
    @QueryParam("limit")
    private int limit;

    public int getOffset() {
        return offset;
    }

    public void setOffset(int offset) {
        this.offset = offset;
    }

    public int getLimit() {
        return limit;
    }

    public void setLimit(int limit) {
        this.limit = limit;
    }
}
```

Descriptions of the query params are empty in the documentation. It works, if the `@QueryParam` is directly used in a method signature.

`@BeanParam` seems basically supported since enunciate extracts the right params from it - which is great!

**Comment by stoicflame** [comment]
After further investigation, I'm going to declare this working as designed.

Enunciate pulls the documentation from the members (fields or properties) that are being used as parameters. So in the example above, the _fields_ are being used as the parameters, but only the _properties_ have documentation. So the solution is to either document the fields or annotate the properties.

**Comment by pswvg** [comment]
Hi Ryan.

I can't quite follow you :). Just to be sure we're talking about the same things here:

- field: the java field itself as declared private
- property: the getter/setter method for the field

You say: "So in the example above, *the fields* are being used as the parameters, but only the properties have documentation".

If you're talking about the `list` method above, I'm using the `Paging` *object* as parameter. If you're talking about the Paging class above, currently the *fields* are documented not the *properties*. I'm confused :).

Do you mean I should move the documentation from *fields* to the *properties*?

**Comment by stoicflame** [comment]
Huh. I must have read it wrong. For some reason, I was thinking the properties were commented and not the fields.

Enunciate will take the documentation from whatever member is annotated. The `@param` documentation on the `list` method will not be used, since it's used to document a set of parameters and not a single parameter.

I'll reopen and revisit this one.

**Comment by stoicflame** [comment]
Revisited this today, but it works for me. Confirmed with the "edge case" example with a [service method annotated with `@BeanParam`](https://github.com/stoicflame/enunciate/blob/master/examples/full-api-edge-cases/src/main/java/com/webcohesion/enunciate/examples/jaxwsrijersey/genealogy/services/PersonService.java#L81) and [associated bean parameter](https://github.com/stoicflame/enunciate/blob/master/examples/full-api-edge-cases/src/main/java/com/webcohesion/enunciate/examples/jaxwsrijersey/genealogy/services/PersonQuery.java). The JavaDoc on the field shows up as expected in the generated documentation.

**Comment by pswvg** [comment]
Mkay, I'll recheck that. Thanks for looking into this!

**Comment by mperrier** [comment]
pswvg,  Did you ever find a solution to your problem?  I appear to have the same issue right now with 2.2.0.

My service:
![image](https://cloud.githubusercontent.com/assets/7179728/12927027/95f6fcb2-cf2b-11e5-94a7-43dd066f4b69.png)

My parameter class:
![image](https://cloud.githubusercontent.com/assets/7179728/12927063/b4454ea8-cf2b-11e5-8f09-5c4e56aa567d.png)

The resulting documentation:
![image](https://cloud.githubusercontent.com/assets/7179728/12927080/ca725824-cf2b-11e5-9f28-d5f1ce3e5c30.png)

**Comment by vguna** [comment]
@mperrier: nope. Re-checked this with 2.3.0 and still the same result. Did you find the cause?

**Comment by mperrier** [comment]
@vguna I have not investigated the issue but it is still a problem.

**Comment by stoicflame** [comment]
As reported by @vguna at #393, his problem was a misconfiguration issue.

If this is still a problem, I'm interested in any details that you can provide.

**Comment by mperrier** [comment]
@stoicflame Okay, I see that he referenced that issue now.  I'll investigate and report back if I have a different scenario.

Thanks!

**Comment by stoicflame** [comment]
FYI, I've updated the documentation to reflect what's needed to find the source files.

https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files

**Comment by stoicflame** [comment]
Enunciate 2.4.0 has been released.

**Comment by zcgandcomp** [comment]
Hello I has same problem.
I have several maven modules, one for Model classes - where my @BeanParam and one for REST API resource classes - where I have enunciate.xml. 
I was able to solve it with putting source plugin into my model project pom
`        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <executions>
                <execution>
                    <id>attach-sources</id>
                    <goals>
                        <goal>jar</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>`

**Comment by jdimeo** [comment]
On a related note, I want to make the description DRY by moving it to a constant. However, using Swagger `@Parameter` on a `@BeanParam` doesn't work (even with the Swagger module enabled), only a Javadoc seems to make it through the "flattening" process. Is this intentional?

Example where I'm trying to make a DRY parameter bean across CLI and REST.
```java
	private static final String VAR_NAME_DESC = "Whether or not to include variable names in the initialized project."; 
	@Option(names = {"--include-var-names", "-nv"}, description = VAR_NAME_DESC, defaultValue = DEF_TRUE)
	@QueryParam("includeVarNames") @Parameter(description = VAR_NAME_DESC, required = false)
	@DefaultValue(DEF_TRUE)
	private boolean includeVarNames = true;
```

**Comment by stoicflame** [comment]
> Is this intentional?

Nah probably just a feature gap.

You're welcome to capture this request as a separate issue. (A comment on an existing issue won't be enough to instigate action on it.)

**Comment by jdimeo** [comment]
Understood! But a comment on an existing issue is enough to instigate the creation of an issue :-) thank you!
