### ISSUE TITLE
Maybe read javadoc from fields, too?

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#226]
Currently I'm using 2.1.1 to generate the documentation for my REST endpoints.
I'm putting the javadoc for the documentation for my DTOs on the getters and this works as expected.

But If one uses the same DTO for GET and POSTs, the javadoc is strange to read.
So e.g. mention if a field is required - on a getter :).

Maybe it's just me and how one builds the sentence, but it would be better to read if I could omit the getter/setter and put the javadoc directly on the field. If I read something about "required" there, It makes more sense to me :).

About clashes getter/field, if both are documented, simply pick one per default (field?).

BTW: is it possible to mark fields as required with enunciate?

**Comment by stoicflame** [comment]
You can use fields if you want. Just configure [JAXB like this](https://docs.oracle.com/javaee/5/api/javax/xml/bind/annotation/XmlAccessorType.html) and/or [Jackson like this](http://fasterxml.github.io/jackson-annotations/javadoc/2.2.0/com/fasterxml/jackson/annotation/JsonAutoDetect.html) for field-based accessors.

Is that what you're looking for?

Re: possible to mark fields as required: JAXB can use `required` on `@XmlElement`, Jackson can use `required` on `@JsonProperty`.

**Comment by vguna** [comment]
Hm. Does that mean that enunciate will recognize that and take the javadoc from the fields as well?

I'll take a look at @JsonProperty. Thanks!
