### ISSUE TITLE
Data Types description for numeric types hide the real numeric java type

### ISSUE THREAD

**Issue by skombijohn** [stoicflame/enunciate#229]
Let's say I have a class Person:

```java
class Person {
  Long id;
  String name;
}
```

A resource now offers a GET for a Person. To declare the return type of that resource I use `@TypeHint(Person.class)`

In the generated documentation for the Data Type `Person` the property `id` will appear as the type `number` and in the generated json example as:
```json
{
  "name" : "...",
  "id" : 12345.0,
}
```

This is basically correct in terms of json type safety. 
But the above json will cause errors when (for example using jax.rs) a POST method is taking a `Person` as a argument and the parsing is done by Jackson automatically, so that Jackson will try to assign a `Double` to a `Long`.

It would be nice if the real type is preserved somehow.

**Comment by hskigithub** [comment]
I see the same issue with Java int, which is translated to an example JSON object with "12345.67", which is wrong and will be rejected by the REST API, because it is not int.

I think it is crucial to keep the type Long, Integer, long and int and not translate them to number.

**Comment by stoicflame** [comment]
Fixed at a23b0a9.

**Comment by hskigithub** [comment]
Thanks for fixing! Looking forward for the release. :-)

**Comment by stoicflame** [comment]
[Enunciate 2.2 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.2.0).
