### ISSUE TITLE
Support @Facet on enum values

### ISSUE THREAD

**Issue by sg-ad** [stoicflame/enunciate#235]
Since `@Facet` can already be applied to fields, it would be great if it could also be interpreted when it's applied on `enum` values.  For example:
```java
public enum PaymentMethod {
  CREDIT_CARD,
  DIRECT_DEBIT,
  @Facet("premium")
  PAYPAL
}
```
If the `premium` facet is included, `PAYPAL` would appear in the possible values for the constraint.  Similarly, if the facet is excluded, `PAYPAL` isn't shown as a possible value.

**Comment by stoicflame** [comment]
Fixed at e096e75.

**Comment by sg-ad** [comment]
You rock!  Thanks!

**Comment by stoicflame** [comment]
[Enunciate 2.2 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.2.0).
