### ISSUE TITLE
Javadoc on DataTypes

### ISSUE THREAD

**Issue by skombijohn** [stoicflame/enunciate#238]
I have very simple DTOs with loads of basic type fields (String, boolean, Number).
They are included as @TypeHint on the resources, so they appear in the "Data Types" section of the documentation.

However, no matter that I add javadoc to the fields and class, there is no description in the documentation rendered.

**Comment by stoicflame** [comment]
That was reported at #234, too, but I can't seem to reproduce it. If you can provide more information about how to reproduce it (perhaps tweak the sample app), will you report it at #234? In the meantime, I'll close this out as a duplicate.
