### ISSUE TITLE
Enable usage of custom serializers/deserializers in enunciate-jackson

### ISSUE THREAD

**Issue by XavierLahaut** [stoicflame/enunciate#239]
I have written a rest service using customs serializers/deseriaizers to handle dates in ISO8601 format with the Jackson provider. I'm using a specialization of the class _org.codehaus.jackson.map.module.SimpleModule_ to register these the serializers. This enables me to handle the ISO8601 format on all my API without adding any extra information on my data types.

Will it be possible to open more the code of the module _enunciate-jackson_ to enable this kind of customization ? Currently, the module considers the dates like numbers.

**Comment by stoicflame** [comment]
See #187. Use `@TypeHint`.

Also see #231; use `@DocumentationExample`.
