### ISSUE TITLE
Including @throws in generated documentation

### ISSUE THREAD

**Issue by bkalas** [stoicflame/enunciate#241]
Hi, 
is it somehow possible to include @throws section from javadoc into generated documentation of jax-rs rest methods?
Currently this section is ignored (at least in my project).
Thanks.

**Comment by stoicflame** [comment]
Enunciate has no way of knowing how you map the exceptions that get thrown to an HTTP response. So, no, the "throws" section of the javadoc is not included in the generated documentation.

There are, however, some [enhancment annotations](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#enhancements-to-jax-rs) that Enunciate provides that allow you to describe the HTTP status codes and conditions for each method.
