### ISSUE TITLE
javax.validation.constraints integration

### ISSUE THREAD

**Issue by mrgmatthews** [stoicflame/enunciate#242]
So on the JSON objects can have constraints
Pulls in validation defined in annotations into the documentation.

@Size @NotNull etc

**Comment by stoicflame** [comment]
Tagged as an enhancement; not assigned to a release yet.

**Comment by mrgmatthews** [comment]
also support for org.hibernate.validator.constraints would also be cool :+1:

**Comment by vguna** [comment]
javax.validation.constraints should now be available with 2.6.0.
