### ISSUE TITLE
Excluding classes doesn't work

### ISSUE THREAD

**Issue by nuevedientes** [stoicflame/enunciate#247]
I followed the instructions here to exclude classes from the JSON and XML documentation.
https://github.com/stoicflame/enunciate/wiki/Excluding-Classes
Specifically I am trying to exclude an abstract class and InputStream:

```xml
<api-classes>
    <exclude pattern="com.mycompany.api.MyAbstractClass"/>
    <exclude pattern="java.io.InputStream"/>
 </api-classes>
```

The above is having no effect.

**Comment by stoicflame** [comment]
Yes, if the class is "part" of API classes that are _not_ excluded, it will get pulled in even if excluded.

In this case, you'll probably want to use `@XmlTransient` for XML and `@JsonIgnore` for JSON.

**Comment by nuevedientes** [comment]
Thanks, is there a way to exclude java.io.InputStream as well?

**Comment by stoicflame** [comment]
You need to figure out where `InputStream` is being used in your API classes and (again) apply `@XmlTransient` and `@JsonIgnore`.
