### ISSUE TITLE
Add examples to Enunciate Specific Annotations wiki page 

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#250]
I would recommend to add some examples to the Enunciate Specific Annotations wiki page e.g. '@TypeHint(PersonBean.class) or @TypeHint(PersonBean[].class)'. Same to the other annotations. 

I would also link to this wiki page from Getting Started page and maybe main page.

**Comment by stoicflame** [comment]
Fixed.

**Comment by hskigithub** [comment]
Great! Thank you very much! Very useful!

**Comment by stoicflame** [comment]
[Enunciate 2.2 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.2.0).
