### ISSUE TITLE
CSS multi-row-description should not have border

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#251]
It would look more similar to other layout, if a description would not have a left border as defined per
.multi-row-description {
 border-left: 1px solid #DDD;
}

**Comment by stoicflame** [comment]
Fixed at d3b43e0.

**Comment by stoicflame** [comment]
[Enunciate 2.2 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.2.0).
