### ISSUE TITLE
Improve layout of REST URL in generated HTML page

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#252]
Current layout for REST URLs is in \<h3>, which is okay, but actual URL is then surrounded by \<small>. 

From visualization perspective this looks as URL would be less important information, which is actually not the case. :-)

You should remove this \<small>. If you want maybe later do different styling of GET and URL, then surround both of them with a <span> and a CSS class e.g. \<span class="httpmethod">GET\</span> \<span class="resturl">/customfield/{projectkey}/{customfieldid}\</span>

**Comment by stoicflame** [comment]
Fixed at af0f42a.

**Comment by stoicflame** [comment]
[Enunciate 2.2 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.2.0).
