### ISSUE TITLE
@XmlElement(name = "...") is not taking into account for property name

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#253]
If I use `@XmlElement(name = "id")` to rename a propery in JSON or XML, this is not taking into account in enunciate e.g.
 
    @DocumentationExample("customfield_10400")
    @XmlElement(name = "id")
    private String customFieldId;

This creates in REST documentation a property customFieldId, but should use id. Same in JSON example customFieldId, but should be id.

**Comment by stoicflame** [comment]
If that's accurate, that's a pretty significant bug.

Unfortunately, I'm not able to reproduce it. For example, if edit the [sample app](https://github.com/stoicflame/enunciate-sample) and annotate the `getId` method of `com.ifyouwannabecool.domain.persona.Persona` with `@javax.xml.bind.annotation.XmlElement(name = "customId")`, it gets documented as "customId" and not "id".

**Comment by hskigithub** [comment]
Here is my code.

```
package jira.plugin.projectspecificselectfield.bean;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.webcohesion.enunciate.metadata.DocumentationExample;

@XmlRootElement(name = "customfield")
@XmlAccessorType(XmlAccessType.FIELD)
public class ProjectSpecificCustomField {

	@DocumentationExample("customfield_10400")
    @XmlElement(name = "id")
    private String customFieldId;
	@DocumentationExample("Delivery Unit")
    @XmlElement(name = "name")
    private String customFieldName;
	@DocumentationExample("jira.plugin.projectspecificselectfield:multicftype")
    @XmlElement(name = "type")
    private String customFieldType;
    @XmlElement
    private Boolean editable;

    
	public String getCustomFieldId() {
		return customFieldId;
	}
	public void setCustomFieldId(String customFieldId) {
		this.customFieldId = customFieldId;
	}
	public String getCustomFieldName() {
		return customFieldName;
	}
	public void setCustomFieldName(String customFieldName) {
		this.customFieldName = customFieldName;
	}
	public Boolean isEditable() {
		return editable;
	}
	public void setEditable(Boolean editable) {
		this.editable = editable;
	}
	public String getCustomFieldType() {
		return customFieldType;
	}
	public void setCustomFieldType(String customFieldType) {
		this.customFieldType = customFieldType;
	}
	
}
```

**Comment by stoicflame** [comment]
Still no luck reproducing it.

I [pushed a new branch](https://github.com/stoicflame/enunciate-sample/tree/demo-custom-element-names) to the enunciate-sample application. I tried to [make the Persona](https://github.com/stoicflame/enunciate-sample/blob/demo-custom-element-names/src/main/java/com/ifyouwannabecool/domain/persona/Persona.java) look like your example above. The docs were generated correctly, as shown in the attached screenshot.

Can you check out that branch and confirm it's working for you?

![screenshot from 2016-01-14 11-56-31](https://cloud.githubusercontent.com/assets/145838/12334268/65d9de02-bab6-11e5-88fb-1c54fcd73346.png)

**Comment by hskigithub** [comment]
I am looking at JSON. Maybe that makes a difference?

**Comment by stoicflame** [comment]
Json is provided by Jackson, which is customized using Jackson annotations, not JAXB annotations:

```java
@JsonProperty("id")
private String customFieldId;
```

You can, however, configure Jackson to use JAXB annotations:

https://github.com/FasterXML/jackson-module-jaxb-annotations

**Comment by hskigithub** [comment]
How can I configure this as part of my enunciate config?

Here is what's being created as part of enunciate JSON doc for the class above. 

```
{
  "customFieldId" : "...",
  "customFieldName" : "...",
  "customFieldType" : "..."
}
```


Also that boolean field is not part of JSON. And `@DocumentationExample("New Moon Rocket Project")` doesn't have any effect on created JSON.

**Comment by stoicflame** [comment]
Are you using Jackson 1 or Jackson 2? Configuration will be different depending on which version of Jackson you're using.

**Comment by hskigithub** [comment]
I just followed Doc Goal Example as described in Wiki here https://github.com/stoicflame/enunciate/wiki/Executables.

**Comment by stoicflame** [comment]
The doc goal can be applied to a project that uses either Jackson 1 or Jackson 2. I need to know which one your project uses.

Maybe `mvn dependency:list` can provide you more details about which Jackson version you're using.

**Comment by hskigithub** [comment]
org.codehaus.jackson:jackson-mapper-asl:jar:1.9.1:provided
org.codehaus.jackson:jackson-core-asl:jar:1.9.1:provided
org.codehaus.jackson:jackson-asl:jar:0.9.4:provided

**Comment by stoicflame** [comment]
Jackson 1, then.

```xml
<enunciate>
  <modules>
    <jackson1 honorJaxb="true"/>
```

**Comment by hskigithub** [comment]
Works fine now. Thanks!
