### ISSUE TITLE
Swagger, Inheritance and 'allOf'

### ISSUE THREAD

**Issue by sg-ad** [stoicflame/enunciate#256]
Hi,

I'm using Swagger2Markup to process the Swagger output generated by Enunciate and create some Asciidoc output.  I've run into a problem, but I'm not sure what's at fault because I'm still not 100% clear on how Swagger wants us to handle inheritance.

Our API has some references to `com.fasterxml.jackson.databind.node.ArrayNode`.  `ArrayNode` is a child of `ContainerNode`, itself a child of `BaseJsonNode` which, in turn, is a child of `JsonNode` whose parent is `Base`.  The generated definition for `ArrayNode` in the `swagger.json` file is as follows:

```json
"json_arraynode" : {
      "type" : "object",
      "title" : "ArrayNode",
      "allOf" : [
        {
          "$ref" : "#/definitions/json_base"
        },
        {
          "$ref" : "#/definitions/json_jsonnode"
        },
        {
          "$ref" : "#/definitions/json_basejsonnode"
        },
        {
          "$ref" : "#/definitions/json_containernode"
        },
        {
        }
      ],
      "description" : ""
    }
    ...
    "json_containernode" : {
      "type" : "object",
      "title" : "ContainerNode",
      "allOf" : [
        {
          "$ref" : "#/definitions/json_base"
        },
        {
          "$ref" : "#/definitions/json_jsonnode"
        },
        {
          "$ref" : "#/definitions/json_basejsonnode"
        },
        {
        }
      ],
      "description" : ""
    }
```
From what I see, Swagger2Markup follows the `$ref` and accumulates the properties that it encounters in each parent so that it can generate the full list of properties for `ArrayNode`.  The problem is that it sees `#/definitions/json_basejsonnode` twice, once as a $ref in `json_arraynode`, and a second time as a $ref in `json_containernode`.  It adds the properties twice, or more if the definition is encountered more than this.  Ultimately this causes an exception in Swagger2Markup because property names are should not be duplicated.

I've read the Swagger specification section that discusses [Composition and Inheritance](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism) but it's not clear on how the parent of a parent should be documented.  I was able to have my swagger file process correctly by removing all `$ref` other than the immediate parent, but I don't know if that's the right solution, or if the Swagger2Markup parser should be improved.

Thoughts?

Thanks!

**Comment by sg-ad** [comment]
FYI, I've posted a [question](https://github.com/OAI/OpenAPI-Specification/issues/543) in the Swagger Spec project since that's possibly the more relevant forum for this "first step" question.

**Comment by stoicflame** [comment]
I think this is a bug in the Enunciate-generated swagger.json file. If you reference `ArrayNode` it should probably just be described as an array of objects.

I'll call this a bug and assign it to 2.3.

**Comment by sg-ad** [comment]
In the same vein, I wonder if there's a way I could address a similar problem.  We have a lot of APIs, written at different times by different people, with different levels of best practice in mind.  Here are a few troublesome signatures:

```java
@PATCH
@Path("/companies/{companyUuid}")
CompanyWS partialUpdateCompany(
		@PathParam("companyUuid") String companyUuid,
		JsonNode companyWS
);

@GET
@Path("/applications")
ArrayNode readApplications();

@PUT
@Path("/users/{userId}/credentials")
Response createOrUpdateCredentials(
		@PathParam("userId") String userId,
		ObjectNode credentials
);
```
Enunciate has to document `JsonNode`, `ArrayNode` and `ObjectNode`.  The reference to `JsonNode` is particularly bothersome.  It's an abstract class and is used in cases where the developer wanted to allow basically any chunk of JSON to be accepted.  Ideally, I'd like to prevent Enunciate from exploring the parent class(es) as there's nothing useful to document beyond that.  Is there a way to limit the depth to which Enunciate will explore the ancestors?  Any other way I might address this problem?

**Comment by stoicflame** [comment]
Enunciate really shouldn't be trying to interpret any instance of `JsonNode` as a POJO; these each have special data types already defined.

We'll get it fixed.

**Comment by sg-ad** [comment]
Ok, great!  Thanks!

**Comment by stoicflame** [comment]
Fixed at 65b865a.

**Comment by sg-ad** [comment]
Thanks on this one, too, @stoicflame!

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
