### ISSUE TITLE
TypeHint.NO_CONTENT results in rendered ResponseBody

### ISSUE THREAD

**Issue by qanik1307** [stoicflame/enunciate#261]
When using @TypeHint(TypeHint.NO_CONTENT.class) on a rest endpoint, the resulting documentation from the docs module includes a rendered "Response Body" section including a Media Type. Per definition there can be no Media Type if there is no content returned.

![no_content](https://cloud.githubusercontent.com/assets/16794203/12443910/b08d6c12-bf5b-11e5-8229-9876ee9315dc.PNG)

The empty NO_CONTENT inner class from the TypeHint annotation is also rendered as a Data Type.

![no_content_datatype](https://cloud.githubusercontent.com/assets/16794203/12443984/3ff94010-bf5c-11e5-8ee1-f072b4c607d5.PNG)

**Comment by stoicflame** [comment]
That's weird. Thanks for the report. We'll fix it for 2.3.

**Comment by stoicflame** [comment]
Fixed at 4494880.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
