### ISSUE TITLE
support for required fields for json content

### ISSUE THREAD

**Issue by tzebrowski** [stoicflame/enunciate#262]
I struggle with the issue about required fields description defined in model, issue is related to json messages.  For instance, jackson allows you to mark some fields in complex types as required by using `@JsonProperty` annotation. The thing is that this information is not visible in documentation in any place.

For instance when service as a output produces xml content, you can find then information about required fields, there is an another column which informs about that.

Is there any solution that allows to solve that problem?

**Comment by stoicflame** [comment]
Tracking this as an enhancement request, currently assigned to 2.3.

**Comment by tzebrowski** [comment]
Thx:)

**Comment by stoicflame** [comment]
Fixed at d3591e0.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
