### ISSUE TITLE
Custom content included to the document template.

### ISSUE THREAD

**Issue by tzebrowski** [stoicflame/enunciate#263]
Is there exists some mechanism which allows to add some custom content (plain html) to the document template. I mean  some predefined places like header, footer ?

**Comment by stoicflame** [comment]
These are currently the only mechanisms for supporting custom content like that:

https://github.com/stoicflame/enunciate/wiki/Custom-Skin

The tricky part is specifying _where_ you want the custom content. Do you have a specific place you'd like to put it?

**Comment by tjuchniewicz** [comment]
@stoicflame Is there a possibility to use `include` directive in template? I am trying this directive in FreeMarker template:

I have my own template `docs.fmt` (copy of build-in template) I can change template content and it works but  `include` seems not working. Any restrictions for this directive?

I've tried:
`
<#include "/introduction.ftl">
<#include "introduction.ftl">
`
file `introduction.ftl` is in the same directory as `docs.fmt` and also in the project root.

As a result I have FreeMarker directive `<#include "/introduction.ftl">` included in documentation as  text.

**Comment by stoicflame** [comment]
Trying using the square bracket instead of the angle bracket:

```
[#include "introduction.ftl"/]
```

**Comment by tjuchniewicz** [comment]
It works! Thanks. I was reading this documentation: http://freemarker.incubator.apache.org/docs/ref_directive_include.html were `<>` is used instead of `[]`.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
