### ISSUE TITLE
docs goal skips module from classpath that are not jar packaging

### ISSUE THREAD

**Issue by nfalco79** [stoicflame/enunciate#264]
As documentent *docs* goal should generate docs for modules that are not war. During tycho build it's skip all other modules than current

```
[DEBUG] [ENUNCIATE] Artifact com.example:com.example.core:eclipse-plugin:1.0.0-SNAPSHOT:provided will be removed from the enunciate classpath because it's of type 'eclipse-plugin' and not of type 'jar'.
```

This generate a lot of javac in Service that refer classes in the skipped module.
Is there a reason because filter classpath that comes from maven lifecycle (that has injection of other plugins)?

**Comment by stoicflame** [comment]
Sometimes there are dependencies that are there for purposes _other_ than including them on the classpath. An example is [Maven war overlays](http://maven.apache.org/plugins/maven-war-plugin/overlays.html). 

So Enunciate just uses "jar" packaging right now, but we can expand that if we need to.

Is "eclipse-plugin" packaging just treated as a "jar"?

**Comment by nfalco79** [comment]
Yes "eclipse-plugin" and "bundle" packaging are treates as jar. They come into classpath of dependecy project.
These jar could contains other jars. The unwrapping for the javac compiler (that do not support jar into jar) was done but tycho maven plugin.

**Comment by stoicflame** [comment]
So that means Enunciate will need to be aware of these packaging types and unwrap them.

Is that correct?

How does the tycho maven plugin interface with the javac compiler? Can we enable it to interface with the Enunciate compiler, too?

**Comment by nfalco79** [comment]
I post to you an example of 3 maven eclipse-plugin projects.
aggregate-parent
|-->jar-rs
|-->jaxb

jar-rs depends from jaxb.
Enunciate remove jaxb artifact from jar-rs classpath raising a compile failure.

launch mvn clean package in the aggregate-parent folder
You only need a maven 3.3 and a JDK 1.7 (my environment), buy I think that maven 3.2 and JDK 1.6 should be fine.
[aggregate-parent.zip](https://github.com/stoicflame/enunciate/files/98553/aggregate-parent.zip)

**Comment by nfalco79** [comment]
I do not know how tycho interface with javac compiler. The default compiler in tycho plugin is jdt (eclipse compiler). I know that tycho inject classpath, sources and others things into maven environment in each maven phase.

**Comment by stoicflame** [comment]
I'll track this as an enhancement request to support the Tycho plugin.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
