### ISSUE TITLE
Move org.codehaus.enunciate.contract.jaxrs.ResourceMethodSignature to enunciate-core-annotation jar

### ISSUE THREAD

**Issue by nfalco79** [stoicflame/enunciate#265]
We use org.codehaus.enunciate.contract.jaxrs.ResourceMethodSignature annotation on all DAO EMF generated classes, so we must have enunciate-core jar as dependency and redistribuite with all applications.
Please consider to move org.codehaus.enunciate.contract.jaxrs.ResourceMethodSignature annotation to the specific enunciate-core-annotation jar

**Comment by stoicflame** [comment]
Hi.

So `ResourceMethodSignature` is in the core-annotations jar already:

https://github.com/stoicflame/enunciate/blob/master/core-annotations/src/main/java/com/webcohesion/enunciate/metadata/rs/ResourceMethodSignature.java

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
