### ISSUE TITLE
Java8 Date/Time LocalDate Support

### ISSUE THREAD

**Issue by qanik1307** [stoicflame/enunciate#271]
Using Java8 Date/Time API type LocalDate results in wrong documentation. Correct serialization example for Jackson would be a simple string like "1970-01-01" and no complex object as seen on the attached screenshot for the field dateOfBirth.

![localdate](https://cloud.githubusercontent.com/assets/16794203/12512949/6b1ce560-c11b-11e5-9975-716e77364d44.PNG)

The above is probably also correct for other Java8 Date/Time API types.

**Comment by stoicflame** [comment]
Thanks for the report. Assigning to 2.3.

**Comment by oeystein** [comment]
Same issue with org.joda.time, it would be really great seeing a generalized solution, where for instance the @DocumentExample(String) annotation tag always overrides complex objects with an string? Currently i dont think @DocumentExample(String) does anything for non-compatible objects? But I might be wrong here though. 

From
`{
  "lastchanged" : { },
  "firstconnected" : {
    "millis" : 12345,
    "chronology" : {
      "zone" : { }
    },
    "hourOfDay" : 12345,
    "secondOfDay" : 12345,
    "minuteOfHour" : 12345,
    "secondOfMinute" : 12345,
    "dayOfMonth" : 12345,
    "year" : 12345,
    "weekyear" : 12345,
    "millisOfSecond" : 12345,
    "dayOfYear" : 12345,
    "weekOfWeekyear" : 12345,
    "millisOfDay" : 12345,
    "yearOfCentury" : 12345,
    "minuteOfDay" : 12345,
    "centuryOfEra" : 12345,
    "dayOfWeek" : 12345,
    "era" : 12345,
    "monthOfYear" : 12345,
    "yearOfEra" : 12345,
    "equalNow" : true,
    "zone" : {
      "provider" : { },
      "default" : { },
      "availableIDs" : [ "...", "..." ],
      "nameProvider" : { },
      "fixed" : true,
      "ID" : "..."
    },
    "afterNow" : true,
    "beforeNow" : true
  },
  ...
}`

To: 
`{
  "lastchanged" : { },
  "firstconnected" : "SomeStringOfYourOwnChosing"
  ...
}`

**Comment by stoicflame** [comment]
Support for Java 8 Date/Time API and Joda Date/Time API was added at c7c424a.

See [JSON Date Formatting](https://github.com/stoicflame/enunciate/wiki/JSON-Date-Formatting) for information about how to manage Enunciate's default date formatting. The annotations option should work with 2.2; the configuration option was added in 2.3 at c7c424a.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
