### ISSUE TITLE
Additional sorting and Jackson support for XmlElementWrapper 

### ISSUE THREAD

**Issue by davidlewis711** [stoicflame/enunciate#274]
I've started using enunciate to generate REST documentation over the past few weeks.  Awesome project!

As I've been playing with it, I've mode a few tweaks that I'd like to submit for consideration:
1. Added support for javax.xml.bind.annotation.XmlElementWrapper in jackson and jackson1 (Member.java).
2. Sort the list of PathSummary objects in annotation-based and class based resource groups.
3. Added config option to specify how to sort paths.  I called the two different options "breadth-first" and "depth-first".  Probably not the greatest names, but that's the best I could come up with.  The current sorting strategy orders paths by number of components first (this what I called breadth-first):
* a
* b
* c
* a/a
* a/b
* b/a
* a/a/a

The strategy I'm proposing (depth-first) sorts the same set of paths like this:
* a
* a/a
* a/a/a
* a/b
* b
* b/a
* c

I've attached a patch file for your review and consideration.  Thanks!

[Patch file](https://github.com/stoicflame/enunciate/files/103530/diff.txt)

**Comment by stoicflame** [comment]
Thanks for the patch. I'll take a look.

Assigning to 2.3.

**Comment by davidlewis711** [comment]
Here's a follow up patch file with one more proposed enhancement:

4. Sort Resources in AnnotationBasedResourceGroupImpl by path and method so they are sorted in the generated resource_*.html file.

[Follow up patch file](https://github.com/stoicflame/enunciate/files/161826/diff2.txt)

**Comment by stoicflame** [comment]
I'm supportive of the changes, but I can't seem to get the patch to apply:

```
$ git apply diff2.txt
error: core/src/main/java/com/webcohesion/enunciate/util/BreadthFirstResourcePathComparator.java: No such file or directory
error: core/src/main/java/com/webcohesion/enunciate/util/DepthFirstResourcePathComparator.java: No such file or directory
error: core/src/main/java/com/webcohesion/enunciate/util/PathSummaryComparator.java: No such file or directory
error: core/src/main/java/com/webcohesion/enunciate/util/ResourceComparator.java: No such file or directory
error: core/src/main/java/com/webcohesion/enunciate/util/SortedList.java: No such file or directory
```

Am I using the wrong command?

**Comment by stoicflame** [comment]
Maybe you could send a pull request instead of a patch?

https://help.github.com/articles/using-pull-requests/

**Comment by davidlewis711** [comment]
OK, I'll do that and get back to you.

**Comment by davidlewis711** [comment]
https://github.com/stoicflame/enunciate/pull/333

**Comment by stoicflame** [comment]
Lovely. Thanks for the great pull request. It's now merged, with the following adjustments:

* Minor code style adjustments at 5484f65.
* It turns out if there is _both_ an `@XmlElement` annotation _and_ an `@XmlElementWrapper` annotation, Jackson prefers the former over the latter, so I fixed the prioritization bug at 2a30318.
* I pushed the configuration of path-sort-strategy down to each individual API module instead of providing it globally at fc8ec15. It seemed a better place, since that's where the sorting was happening. So now the `path-sort-strategy` attribute goes on either the `jaxrs` configuration element or the `spring-web` configuration element instead of at the root of the Enunciate configuration file.

**Comment by davidlewis711** [comment]
Awesome.  Thanks!  

One thing, though.
> It turns out if there is both an @XmlElement annotation and an @XmlElementWrapper annotation, Jackson prefers the former over the latter

That's not the behavior that I see.  In my project, I map lists and arrays like this:

```
@XmlElementWrapper(name="allowed_processes")
@XmlElement(name="name")
public List<String> getAllowedProcesses() {
    return allowedProcesses;
}
```
The generated XML is
```
<allowed_processes>
  <name>a</name>
  <name>b</name>
</allowed_processes
```
and the corresponding JSON is:
```
"allowed_processes":["a","b"]
```
Did you find Jackson documentation describing it differently?  If you can provide me with that information, I'd like to spend some time trying to understand why the difference.

**Comment by stoicflame** [comment]
> Did you find Jackson documentation describing it differently?

No, it was actually one of the tests that failed.

If you revert 2a30318 and run "mvn clean install", you should see an NPE on `TestGeneratedJsonTypeSerialization` line 725 in the `java-json-client` module. I'll reopen and investigate further.

**Comment by davidlewis711** [comment]
I see.  I stepped through the failing unit tests and found the code in JaxbAnnotationIntrospector in jackson-module-jaxb-annotations-2.5.3.jar that behaves as you describe.  I need to dig into my project and figure out why it behaves differently.  I think jackson-module-jaxb-annotations-2.5.3.jar is wrong, but I need more information to back up that claim :).  Feel free to consider the issue resolved unless I can come back with a better case.

**Comment by davidlewis711** [comment]
Looks like it's a difference between Jackson 1 and 2:

[https://github.com/FasterXML/jackson-module-jaxb-annotations/issues/13](https://github.com/FasterXML/jackson-module-jaxb-annotations/issues/13)

Looks like there is a long discussion about it.  Maybe I just need to avoid the whole thing by adding Jackson annotations...

**Comment by stoicflame** [comment]
Okay, at 4fba5f1 I put the priority back on `@XmlElementWrapper` for Jackson 1, but not Jackson 2.

**Comment by davidlewis711** [comment]
Sounds good.  Thanks!

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
