### ISSUE TITLE
Update wiki that @DocumentationExample is used for JSON only with <jackson1 honorJaxb="true"/>

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#276]
Working with ```@DocumentationExample``` I found out in discussion for #253 that ```<jackson1 honorJaxb="true"/>``` configuration is needed. Otherwise ```@DocumentationExample```is ignored by enunciate for JSON objects.  

You should add this as a prerequesite for ```@DocumentationExample``` in the wiki describing the annotation here https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations.

**Comment by stoicflame** [comment]
Hi.

Thanks for the report. `@DocumentationExample` seems to be working for me even though Jackson isn't configured to honor JAXB annotations. Could you show me what you're seeing by editing the sample app and sending a patch?

**Comment by stoicflame** [comment]
I'm going to close this, since it appears to be working for me. I'd be happy to re-open if needed.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
