### ISSUE TITLE
Provide multiple examples for @DocumentationExample for arrays

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#277]
My REST API is returning quite often an object, which itself contains an arrays of objects. Using ```@DocumentationExample``` I am providing example data. 

If my object contains an array on another object, the example data of this other object is used twice, to show in the example, that this is an array. 

Example data for ```project```
```
{
  "name" : "New Moon Rocket Project",
  "key" : "FCTP"
}
```

Example data for ```project collection```, which contains an array of ```project```
```
{
  "name" : "...",
  "id" : 12345,
  "associatedprojets" : [ {
    "name" : "New Moon Rocket Project",
    "key" : "FCTP"
  }, {
    "name" : "New Moon Rocket Project",
    "key" : "FCTP"
  } ]
}
```
In general that is a good idea, but the problem is, that using the same example data twice might be a misleading example or even wrong in the context of the API (like in my case).

Is there a way to provide two sets of example data somehow? Or example data for that array as part of the DocumentationExample of the ```project collection``` as used above?

```
{
  "name" : "...",
  "id" : 12345,
  "associatedprojets" : [ {
    "name" : "New Moon Rocket Project",
    "key" : "FCTP"
  }, {
    "name" : "New Mars Rover Project",
    "key" : "MR"
  } ]
}
```

**Comment by stoicflame** [comment]
There's no way to do that right now, but I can look into it adding support for that.

I'll track this issue as an enhancement request.

**Comment by hskigithub** [comment]
Would be great to have this feature. Examples are very helpful to understand an API. 

Is there a config parameter or any other workaround to make enunciate to use only one example data set in arrays? This would limit the problem of misleading duplicate data (but of course with the drawback of showing only one object in an array in the example).

**Comment by stoicflame** [comment]
At c23159e, `@DocumentationExample` supports a `value2` element, e.g.:

```java
@DocumentationExample (
  value = "New Moon Rocket Project",
  value2 = "New Mars Rover Project"
)
```

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
