### ISSUE TITLE
How to exclude data types?

### ISSUE THREAD

**Issue by guyh-tointv** [stoicflame/enunciate#278]
HI,

I have an existing API which is not documented.
I want to take the "Step approach" to document this API, by documenting part of the API at each step.

I have used the @Facet("internal_api") annotation to exclude any resource which is not documented yet, but the generated files includes all datatype, even if they are not used by the included resources.

I have tried to use the @Facet("internal_api") annotation also on these datatypes, tried to use the exclude pattern (see below), but it looks like enunciate ignores this when dealing with data types.

I have also tried adding @com.webcohesion.enunciate.metadata.Ignore on my data types, with no luck.

Here is my enunciate.xml file:

````
<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://enunciate.codehaus.org/schemas/enunciate-1.27.xsd">

	<facets>
		<exclude name="internal_api" />
	</facets>

	<api-classes>
		<exclude pattern="org.jboss.**" />
		<exclude pattern="org.springframework.**" />
		<exclude pattern="com.company.media.facade.**" />
		<exclude pattern="com.company.media.facade.dto.**" />
		<include pattern="com.company.media.facade.web.rest.*" />
	</api-classes>


	<modules>
		<docs docsDir="target/docs" title="REST API"/>
	</modules>

</enunciate>
````
The generated HTML file includes all files under com.company.media.facade.dto.**

BTW: The URL [http://enunciate.codehaus.org/schemas/enunciate-1.27.xsd] is broken. What should I use instead?

Thanks
H Guy

**Comment by stoicflame** [comment]
Hi.

Thanks for the report. I'll take a look for 2.3.

One thing to note is that if your data types are being referenced by other data types that are _not_ excluded, Enunciate will pull them in whether you've annotated them or not. It would probably be a good idea to log a warning or something so users know when this is happening; I'll take care of that for 2.3, too.

The schemas are at enunciate.webcohesion.com instead of enunciate.codehaus.org. Here's the 1.27 schema:

http://enunciate.webcohesion.com/schemas/enunciate-1.27.xsd

**Comment by guyh-tointv** [comment]
Thanks.

Much appreciated.
H Guy

**Comment by stoicflame** [comment]
Finally getting around to looking at this, but I can't seem to reproduce the problem. I've applied the following patch to the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) and the `name` data type is excluded. It even breaks the links to it from the `persona` data type (file not found).

Can you provide a way for me to reproduce what you're seeing?

**Comment by stoicflame** [comment]
At a1ad887, I added a warning whenever a class was added that was supposed to be excluded according to configuration. I'm going to call this issue complete for now; I'd be happy to re-open if needed.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
