### ISSUE TITLE
Generate documentation for objects with the InjectParam annotation

### ISSUE THREAD

**Issue by mperrier** [stoicflame/enunciate#279]
One of the benefits of using InjectParam (Jersey library) is that you can accept a large number of query parameters as a POJO.  Without this, method signatures can get very lengthy and creating a criteria object to send to your business logic layer is a manual process.

I have a search service that has 40 parameters that a user can search on.  Here is a simplified version of what I have to to in order for Enunciate to generate the documentation correctly:
```java
/**
     Javadoc for the service...
*/
@GET
@Produces({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })
public SearchTicketsResponse findTickets (@QueryParam("id") String id, 
     @QueryParam("name") String name, @QueryParam("requestor") String requestor,
     @QueryParam("title") String title, @QueryParam("type") String type, 
     @QueryParam("priority") String priority, @QueryParam("owner") String owner
     // You get the idea, we have 40 different fields to search on and it gets nasty.
     ) {

     SearchCriteriaDO criteria = new SearchCriteriaDO();
     criteria.setId(id);
     criteria.setName(name);
     criteria.setRequestor(requestor);
     criteria.setTitle(title);
     criteria.setType(Type);
     criteria.setPriority(priority);
     criteria.setOwner(owner);

     if (isValid(criteria)) {
          return ticketBo.findTickets(criteria);
     } else {
          // Return exception
     }
}
```

With InjectParam, the above code is simplified to this:
```java
/**
     Javadoc for the service...
*/
@GET
@Produces({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON })
public SearchTicketsResponse findTickets (@InjectParam SearchCriteriaDO criteria) {

     if (isValid(criteria)) {
          return ticketBo.findTickets(criteria);
     } else {
          // Return exception
     }
}
```

With SearchCriteriaDO like this:
```java
public class SearchCriteriaDO {

     // These don't have to be public, I did this for brevity
     @QueryParam("id")
     public String id;

     @QueryParam("name")
     public String name;

     @QueryParam("requestor")
     public String requestor;

     @QueryParam("title")
     public String title;

     @QueryParam("type")
     public String type;

     @QueryParam("priority")
     public String priority;

     @QueryParam("owner")
     public String owner;
}
```

With the top example the documentation is generated correctly so that consumers see all query parameters available with documentation for each parameter.  With the InjectParam example this is all the consumer would see (there is no documentation for the request parameters):

![image](https://cloud.githubusercontent.com/assets/7179728/12590156/1780d5ba-c427-11e5-83b9-77f931fa2c04.png)

I request that Enunciate dives into the object with the InjectParam annotation to determine if documentation should be created for that object.

**Comment by stoicflame** [comment]
I didn't know you could use `@InjectParam` that way. I guess you learn something new every day, huh?

I can fix that pretty easily for 2.3.

Is there a reason you don't use `@BeanParam` instead of `@InjectParam`? Enunciate already supports `@BeanParam`.

**Comment by mperrier** [comment]
Thanks for the reply!

Right now we're stuck on Jersey 1.x and I believe BeanParam comes with 2.x.  I can look at what it would take for us to migrate to 2.x but until then we're stuck with InjectParam.

**Comment by stoicflame** [comment]
Fixed at f4b6433.

**Comment by mperrier** [comment]
Thanks Ryan!

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
