### ISSUE TITLE
Data Types are are generated without the description

### ISSUE THREAD

**Issue by guyh-tointv** [stoicflame/enunciate#281]
Hi,

Here is an example of my PersonDTO class:
````
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * This represents a person
 * 
 */
@XmlRootElement(name="person")
@XmlAccessorType(XmlAccessType.PUBLIC_MEMBER)
public class PersonDTO {
	
	
	/**
	 * First Name
	 */
	@XmlElement(name="firstName")
	private String _firstName;
	
	
	/**
	 * Last Name
	 */
	@XmlElement(name="lastName")
	private String _lastName;
	
	/**
	 * Email address
	 */
	@XmlElement(name="email")
	private String _email;
	
	

	public PersonDTO() {
		// TODO Auto-generated constructor stub
	}

	public String getFirstName() {
		return _firstName;
	}

	public void setFirstName(String firstName) {
		this._firstName = firstName;
	}

	public String getLastName() {
		return _lastName;
	}

	public void setLastName(String lastName) {
		this._lastName = lastName;
	}

	public String getEmail() {
		return _email;
	}

	public void setEmail(String email) {
		this._email = email;
	}	

}
````

Here is the generated output:

![image](https://cloud.githubusercontent.com/assets/14040293/12615753/3c13c7a4-c510-11e5-9c75-ea6a0d052da2.png)

As you can see, each attribute appears twice, and the description is empty of both the attributes, and the class itself. What is going on here?

Here is my enunciate.xml file:
````
<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-1.27.xsd">

	<facets>
		<exclude name="internal_api" />
	</facets>

	<api-classes>
		<include pattern="com.company.media.facade.web.rest.*" />
		<exclude pattern="org.jboss.**" />
		<exclude pattern="org.springframework.**" />
		<exclude pattern="com.jointv.media.facade.**" />
	</api-classes>


	<modules>
		<docs docsDir="target/docs" title="REST API"/>
		<jackson disabled="true"/>
	</modules>

</enunciate>
````

**Comment by stoicflame** [comment]
Are you using Maven?

Are the source jars included on the classpath/sourcepath?

**Comment by guyh-tointv** [comment]
Thank you for your quick support.

Yes I am using maven.

Here is the maven part:

````
	  	<plugin>
	  		<groupId>com.webcohesion.enunciate</groupId>
	  		<artifactId>enunciate-maven-plugin</artifactId>
	  		<version>2.2.0</version>
	  		<executions>
	  			<execution>
	  				<goals>
	  					<goal>assemble</goal>
	  				</goals>
	  			</execution>
	  		</executions>
            <configuration>
                <configFile>${project.basedir}/src/main/webapp/WEB-INF/enunciate.xml</configFile>
            </configuration>
	  	</plugin>  	
````

I don't think I include the source files. 
Which source files are you referring to? My source file? How do I know if it is included or not?

Thanks
H Guy

**Comment by stoicflame** [comment]
See:

https://github.com/stoicflame/enunciate/wiki/Multi-Module-Projects

**Comment by guyh-tointv** [comment]
Thank you for your reply.

Now I can see that the source JAR file is created. But the result remains the same.

Now my maven part looks like this:
````
<plugin>
	<groupId>com.webcohesion.enunciate</groupId>
	<artifactId>enunciate-maven-plugin</artifactId>
	<version>2.2.0</version>
	<executions>
		<execution>
			<goals>
				<goal>assemble</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<sourcepath-includes>
			<include>
				<groupId>com.jointv.media</groupId>
			</include>
		</sourcepath-includes>
		<configFile>${project.basedir}/src/main/webapp/WEB-INF/enunciate.xml</configFile>
	</configuration>
</plugin> 
````

Thanks
H Guy

**Comment by guyh-tointv** [comment]
One more thing I would like to add:

If I remove the @XmlElement, the attributes are not duplicated. Each one of them appear only once. But note that the _ (underscore) at the beginning of each attribute does not appear in the generated doc.

The description field of each attribute remains empty.

Any idea what am I doing wrong?

Thanks,
H Guy

**Comment by stoicflame** [comment]
I'll look closer at the duplicate property problem; it smells like a bug.

I have no idea why your docs aren't getting picked up. It's working for me, so I'll probably need you to show me out to reproduce the problem.

**Comment by nfalco79** [comment]
Hi, are you sure the @XmlElement annotation is correct on the field?
In teory the default is on the getter/setter (you should annotate the getter methods).
If you want use @XmlElement on field you must annotate class with @XmlAccessorType(XmlAccessType.FIELD)

**Comment by stoicflame** [comment]
> If you want use @XmlElement on field you must annotate class with XmlAccessorType(XmlAccessType.FIELD)

Oh yeah, that's the problem. You've said that all `PUBLIC_MEMBER`s are to be included, so the getters are added, then you've explicitly annotated the fields, so they're added, too.

Thanks @nfalco79.

**Comment by nfalco79** [comment]
The javadoc reports
> Every public getter/setter pair and every public field will be
> automatically bound to XML, unless annotated by {@link XmlTransient}.
> Fields or getter/setter pairs that are private, protected, or 
> defaulted to package-only access are bound to XML only when they are
> explicitly annotated by the appropriate JAXB annotations.
but never works for me (JSOn serialisation with MOXy/jackson1)

**Comment by guyh-tointv** [comment]
Thank you both for your help. This is highly appreciated.

I have managed to remove the duplication of the fields, once I have added the XmlAccessorType(XmlAccessType.FIELD).

But, the description field is still empty. 

Here is my java file:
````
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import com.webcohesion.enunciate.metadata.DocumentationExample;

/**
 * This represents a person
 * 
 */
@XmlRootElement(name = "customfield")
@XmlAccessorType(XmlAccessType.FIELD)
public class PersonDTO {
	
	
	/**
	 * First Name
	 */
	@DocumentationExample("My First Name")
	@XmlElement(name="firstName")
	private String _firstName;
	public String getFirstName() {
		return _firstName;
	}
	public void setFirstName(String firstName) {
		this._firstName = firstName;
	}
	
	
	/**
	 * Last Name
	 */
	@DocumentationExample("My Last Name")
	@XmlElement(name="lastName")
	private String _lastName;
	public String getLastName() {
		return _lastName;
	}
	public void setLastName(String lastName) {
		this._lastName = lastName;
	}
	
	/**
	 * Email address
	 */
	@DocumentationExample("my.email@address.com")
	@XmlElement(name="email")
	private String _email;
	public String getEmail() {
		return _email;
	}
	public void setEmail(String email) {
		this._email = email;
	}
	
	public PersonDTO() {
		// TODO Auto-generated constructor stub
	}
}
````


And here is the generated output:
![image](https://cloud.githubusercontent.com/assets/14040293/12639865/7193242a-c5af-11e5-9ac2-8145351b34bc.png)

As you can see the **_description_** element of each field is still empty.

My enunciate.xml is:
````
<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-1.30.xsd">

	<facets>
		<exclude name="internal_api" />
	</facets>

	<api-classes>
		<include pattern="com.company.media.facade.web.rest.*" />
		<exclude pattern="org.jboss.**" />
		<exclude pattern="org.springframework.**" />
		<exclude pattern="com.jointv.media.facade.**" />
	</api-classes>


	<modules>
		<docs docsDir="target/docs" title="REST API" />
		<jackson disabled="true" />
		<jackson1 honorJaxb="true"/>
		<swagger disabled="true" />
	</modules>

</enunciate>
````

**Comment by stoicflame** [comment]
Can I see your pom.xml file?

**Comment by guyh-tointv** [comment]
Do you want the whole file?

Here is the relevant part:
````
<plugin>
<groupId>com.webcohesion.enunciate</groupId>
<artifactId>enunciate-maven-plugin</artifactId>
<version>2.2.0</version>
<executions>
	<execution>
		<goals>
			<goal>assemble</goal>
		</goals>
	</execution>
</executions>
<configuration>
	<sourcepath-includes>
		<include>
			<groupId>com.company.media</groupId>
		</include>
	</sourcepath-includes>
	<configFile>${project.basedir}/src/main/webapp/WEB-INF/enunciate.xml</configFile>
	<docsDir>${project.build.directory}/media-web-${version}/resources/apiDocs</docsDir>
</configuration>
</plugin>  	
````

Let me know if this is not enough. I have several POM files, and they are very long files.

Thanks
H Guy

**Comment by guyh-tointv** [comment]
It looks like I have managed to solve this issue, by adding the following to the enunciate.xml file:
````
<include pattern="com.company.media.facade.dto.**"/>
````
What confused me was that without this line the DTO document was generated but without the description field. Now the file is generated correctly.

Thank you very much for your support. 

And thank you very much for this awesome tool.

Thanks
H Guy

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
