### ISSUE TITLE
Header-Parameter docs without @HeaderParam

### ISSUE THREAD

**Issue by qanik1307** [stoicflame/enunciate#284]
We are using a custom Jersey ContainerRequestFilter to handle authentication parameters send via custom headers. It would be great to have a custom enunciate Annotation like the existing @ResponseHeader(s) to add header params to the documentation.

**Comment by stoicflame** [comment]
Thanks for the request. We'll take a look for 2.3.

**Comment by stoicflame** [comment]
Fixed at 54a8705.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
