### ISSUE TITLE
JSON definition of Resource includes `class` as property

### ISSUE THREAD

**Issue by sg-ad** [stoicflame/enunciate#288]
If an operation returns a `org.springframework.hateoas.Resource`, there's a `class` attribute that is added to the definition. The generated JSON description is as follows (in the swagger.json file):
```json
"json_resource": {
"type": "object",
"title": "Resource",
"allOf": [
  {
	"$ref": "#/definitions/json_resourcesupport"
  },
  {
	"properties": {
	  "class": {
		"description": "",
		"$ref": "#/definitions/json_class"
	  }
	}
  }
],
"description": "A simple Resource wrapping a domain object and adding links to it."
}
```
and the example is as follows:
```json
{
  "class" : {
    "name" : "...",
    "protectionDomain" : {
      "permissions" : { },
      "principals" : [ { }, { } ],
      "classLoader" : { },
      "codeSource" : { }
    },
    "genericSuperclass" : { },
    ...
  },
  "links" : [ {
    "rel" : "...",
    "href" : "..."
  }, {
    "rel" : "...",
    "href" : "..."
  } ]
}
```
I think it's caused by the `@JsonUnwrapped` annotation that is on a getter for the `content` attribute:
```java
@JsonUnwrapped
@XmlAnyElement
public T getContent() {
  return content;
}
```
On the XML schema side of things it's correct. The example that is presented is this:
```xml
<resource>
  <link href="..." rel="..." xmlns="http://www.w3.org/2005/Atom"/>
  <extension1>...</extension1>
  <extension2>...</extension2>
</resource>
```
Similarly, the XML schema does have additional `<extension>` elements, which I also think are related to the `@XmlAnyElement` annotation.

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
Fixed at d89bdba.

**Comment by sg-ad** [comment]
Thanks, @stoicflame !

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
