### ISSUE TITLE
Not able to see swagger UI generated from enunciate

### ISSUE THREAD

**Issue by bpraveen02** [stoicflame/enunciate#289]
Hi,

I have generated enunciate documentation and when i click on the Swagger UI link there it is asking for api_key. 

Do i need to register in swagger site in order to get api_key ?

OR

Can you provide any default api_key that can be used to authenticate swagger request calls ?

Thanks,
Praveen

**Comment by stoicflame** [comment]
My experience is that the api key is a red herring. There's likely some other message about unable to read the swagger.json file.

Can you confirm?

**Comment by stoicflame** [comment]
Haven't heard back. Assuming this issue is resolved. I'd be happy to re-open as needed.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
