### ISSUE TITLE
Handling encapsulated query parameters

### ISSUE THREAD

**Issue by sg-ad** [stoicflame/enunciate#290]
With Spring it's possible to declare the following API:
```java
@GET
List<Order> readOrders(@QueryParam("") OrderFilter orderFilter);
```

where `OrderFilter` could be something like:

```java
@Data
public class OrderFilter implements Serializable {
	private static final long serialVersionUID = 4126330247659162216L;
	private String accountNumber;
	private String customerId;
	private String status;
}
```
Spring looks at the type of the `@QueryParam`, sees `OrderFilter` and automatically considers all of its properties as implicit query parameter declarations.  Therefore, for a request like `http://localhost/api/readOrders?accountNumber=1&customerId=2&status=COMPLETE`, Spring will correctly create and populate an `OrderFilter`.

Is there a way to tell Enunciate that it should resolve the properties of `OrderFilter` as valid query parameters?

**Comment by esfand-r** [comment]
I had a similar question. Any advise would be really appreciate. Thanks very much.

**Comment by stoicflame** [comment]
We'll track this issue as an enhancement request for 2.3.

**Comment by esfand-r** [comment]
Thanks very much @stoicflame .

**Comment by stoicflame** [comment]
Finally getting around to implementing this, but I need to know where this behavior in Spring is documented so I can make sure I get it implemented correctly. I don't see any mention of the use the `@QueryParam` in the [Web MVC Documentation](http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html).

I need to know how things are implemented to answer questions like:

* _Which_ members of the class get considered as query parameters? All members? Public fields? Public properties?). 
* Is the `@Data` annotation significant?
* Is the `@QueryParam` significant? (I've never heard of Spring honoring JAX-RS annotations.)

Please point me to where this is documented by the Spring folks.

Thanks!

**Comment by sg-ad** [comment]
Hi @stoicflame 

First, bad info on my part:  it's _not_ Spring but rather CXF (and Jersey) that supports exploding the query parameters into an object when the name of the query parameter is left empty: `@QueryParam("")`.  I'll research in Spring to see if they actually support something similar.

However, after digging, I find that this doesn't appear to be part of the JAX-RS specification.  I guess this complicates matters since it means that there are possibly frameworks that do not support it.

In CXF, the magic happens in `org.apache.cxf.jaxrs.utils.JAXRSUtils#readFromUriParam` where the blank parameter name is detected and triggers special handling.  From the code, they appear to consider setters and public fields.

For the `@Data` annotation, that's a Lombok annotation and is irrelevant.  It's only there to avoid having to create the getter/setters manually.

Hope that helps.  I'll let you know if I find anything in Spring.

**Comment by stoicflame** [comment]
Fixed at 74b0bb0.

**Comment by stoicflame** [comment]
Doh! Wrong issue....

**Comment by stoicflame** [comment]
Okay, so I've never read about the behavior of the empty `@QueryParam` annotation, so I'm a bit nervous about implementing it. 

JAX-RS 2.0 supports the [`@javax.ws.rs.BeanParam` annotation](http://docs.oracle.com/javaee/7/api/javax/ws/rs/BeanParam.html), and Jersey 1 supports the  `@com.sun.jersey.api.core.InjectParam` annotation (see #279). Can you use either of those instead?

**Comment by sg-ad** [comment]
Good question.  Let me take a look at it to see if we can use that approach instead...

**Comment by stoicflame** [comment]
Note that support for `@InjectParam` won't be included until release 2.3. Support for `@BeanParam` was included since 2.0.

**Comment by stoicflame** [comment]
I'm going to close this out for now since there is a more standard workaround available. I'd be happy to re-open if there's enough demand.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
