### ISSUE TITLE
Facet is ignored when creating a data type example (xml/json)

### ISSUE THREAD

**Issue by patvong** [stoicflame/enunciate#291]
I have a data type class in which I used a `@Facet` to exclude a field. Enunciate will properly ignore the field in the list of the object properties if the facet is excluded. However it will appear in the payload example in both xml and json.

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
Fixed at 01ebe8c.

**Comment by patvong** [comment]
Thanks!

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
