### ISSUE TITLE
Missing json type when found only inside List of List

### ISSUE THREAD

**Issue by iorlas1** [stoicflame/enunciate#295]
When generating documentation for a REST-api with enunciate version 2.2.0 I have a data type that only appears inside a List of List. This data type is missing from the documentation and is given only as "array of object". 

Here is file that gives an example of the behaviour. The documentation of Container states that "items - array of object". If a reference to the Item class is given somewhere else it is included, even in the Containers documentation. My guess is that all types are identified first and that it fails to look for new types in Lists. Giving the type in a TypeHint doesn't help either.

```
package se.test;

import com.webcohesion.enunciate.metadata.rs.TypeHint;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.core.Response;
import java.util.List;

@Path("/test/")
public class TestRest {

    @GET
    @Path("/somepath/")
    @TypeHint(Reply.class)
    public Response doStuff() {

        return Response.status(200).build();

    }

}

class Reply {

    private List<Containers> containers;

    public List<Containers> getContainers(){
        return containers;
    }

    public void setContainers(List<Containers> containers){
        this.containers = containers;
    }
}

class Containers {

    private List<Item> items;

    public List<Item> getItems(){
        return items;
    }

    public void setItems(List<Item> items){
        this.items = items;
    }
}

class Item {

    private String id;

    public String getId(){
        return id;
    }

    public void setId(String id){
        this.id = id;
    }
}
```

**Comment by stoicflame** [comment]
Sounds like a bug. Thanks for the report. Assigned to 2.3.

**Comment by nfalco79** [comment]
I'm surprise that works without specify annotate @XmlRoolElement on Replay, maybe it's a trick of TypeHint annotation.

I create an example workspace [issue295.zip](https://github.com/stoicflame/enunciate/files/118224/issue295.zip), I suppose your project it's a war.
In my case the generated docs (target/docs) show:
Replay (JSON) -> containers array of Containers -> items array of Item -> id string

Ensure that in your project you have in the classpath JAX-RS JAXB and a jackson-databind jar.

**Comment by nfalco79** [comment]
What is the difference between @TypeHint and @ResourceMethodSignature(output=...) in this case?
The documentation of annotation ResourceMethodSignature is missing in [wiki](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations)

**Comment by iorlas1** [comment]
Aha, more information needed to reproduce this. When running the zip I get the correct documentation. But when I apply the following enunciate.xml file that I use then it appear again. So if the default generation is used, then the documentation is correctly generated. This this is even more of a corner case than I realized. 

```
<?xml version="1.0"?>
<enunciate>
    <modules>
        <docs title="REST API" disabled="false"/>
        <c-xml-client disabled="true"/>
        <jaxb disabled="true"/>
        <jackson disabled="false"/>
        <jackson1 disabled="false"/>
        <csharp-xml-client disabled="true"/>
        <java-xml-client disabled="true"/>
        <java-json-client disabled="true"/>
        <spring-web disabled="true"/>
        <jaxws disabled="true"/>
        <gwt-json-overlay disabled="true"/>
        <obj-c-xml-client disabled="true"/>
        <php-xml-client disabled="true"/>
        <php-json-client disabled="true"/>
        <ruby-json-client disabled="true"/>
        <idl disabled="true"/>
        <swagger disabled="true"/>
    </modules>
</enunciate>
```

**Comment by nfalco79** [comment]
You disable both jackson and jackson1 module that produce JSON documentation. Without these documentation misses the JSON data type you are lookig for.

**Comment by iorlas1** [comment]
The opposite actually, I only include these (actually in my real code I only include one of them). disabled=false -> enabled

**Comment by guyh-tointv** [comment]
Not sure I understand the solution here.
I have the same problem.

Is it a bug?

Thanks
H Guy

**Comment by nfalco79** [comment]
No, if you want json appear in the documentazione a json Jackson libraries you must have in the classpath of your project and the  the enunciate modules Jackson active (true by defalt)

**Comment by iorlas1** [comment]
As I have pointed out before the jackson modules are active. <jackson disabled="false"/> and <jackson1 disabled="false"/> means that they are active. It is just that the configuration is stated in negative terms (disabled instead of enabled).

**Comment by nfalco79** [comment]
The enunciate.xml you post is not valid against 2.2.0 schema, the following one works and generates documentation as expected.
```
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.2.0.xsd">

	<title>REST API</title>
    <modules>
        <c-xml-client disabled="true"/>
        <csharp-xml-client disabled="true"/>
        <jaxb disabled="true" />
        <jackson disabled="false" />
        <jackson1 disabled="true" />
        <java-xml-client disabled="true"/>
        <java-json-client disabled="true"/>
        <spring-web disabled="true"/>
        <jaxws disabled="true"/>
        <gwt-json-overlay disabled="true"/>
        <obj-c-xml-client disabled="true"/>
        <php-xml-client disabled="true"/>
        <php-json-client disabled="true"/>
        <ruby-json-client disabled="true"/>
        <idl disabled="true"/>
        <swagger disabled="true"/>
    </modules>
</enunciate>
```

add `<configFile>${project.basedir}/enunciate.xml</configFile>` in the pom.xml and ermember to enable only one jackson module depending on jackson version in your classpath

**Comment by iorlas1** [comment]
So it does, thank you. Seems the problem is using jackson1 module when you should use jackson module. I was pretty sure I tested both variants but I must have made some mistake while switching back and forth.

**Comment by guyh-tointv** [comment]
Thanks. It is working for me too.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
