### ISSUE TITLE
TypeHint (NO_CONTENT) showing in object list

### ISSUE THREAD

**Issue by droche-cafex** [stoicflame/enunciate#301]
NO_CONTENT listed as an Object - This is due to the TypeHint annotation. Without it the docs will show "Object (JSON)" as a datatype.

When NO_CONTENT TypeHint is used perhaps there shold be no hyperlink and not be included in the list of objects in the generated API doc?

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
Duplicate of #261; fixed at 4494880.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
