### ISSUE TITLE
Swagger Authentication integration

### ISSUE THREAD

**Issue by mrgmatthews** [stoicflame/enunciate#303]
Might not be the right place for this.

Have a way that the headers for Authentication (just basic authentication) can be put into the swagger thats included.
So I guess this is more of a update the version of swagger being used and integrate with it request.
https://github.com/swagger-api/swagger-js/pull/639

**Comment by stoicflame** [comment]
So it this just a matter of updating the Swagger UI version?

**Comment by mrgmatthews** [comment]
Yes with some tweaking to the generated swagger page I believe

**Comment by stoicflame** [comment]
At f6771d4, Swagger UI has been updated to version 2.1.4.

Currently, Enunciate doesn't generate the swagger index page; it's a static copy. If you'd like to tweak the Swagger UI index page (and associated `SwaggerUI` javascript object), you can do so by configuring Enunciate to use a custom "base". For details, see [Swagger Module Documentation](https://github.com/stoicflame/enunciate/wiki/Module-Swagger#updating-or-configuring-swagger-ui).

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
