### ISSUE TITLE
Disable Swagger schema validation via Enunciate settings

### ISSUE THREAD

**Issue by egemenvardar** [stoicflame/enunciate#304]
Is it possible to disable validation against Swagger schema by using the Enunciate settings (xml) file?

I am getting validation errors from Swagger when I deploy my application, although everything else on Swagger UI works fine (including the "Try it out" option). The validation error messages include _"instance failed to match exactly one schema (matched 0 out of 2)"_ and _"object instance has properties which are not allowed by the schema: [\"type\"]"_. 

Remark: the solution described [here](https://github.com/swagger-api/swagger-ui/issues/630) works fine if I manually modify the index.html file. However, since this is overwritten after each build it is not a feasible solution for us. Therefore, having something like this in the enunciate.xml file would be perfect:

```
<modules>
		<swagger basePath="/rest" validatorUrl="" />
</modules>
```

Thanks in advance.

**Comment by stoicflame** [comment]
There's no way to do it now, but I'll track this as an enhancement request.

**Comment by stoicflame** [comment]
Okay, I was wrong. There _is_ a way to do it.

Currently, Enunciate doesn't generate the swagger index page; it's a static copy, and I'm reluctant to get into the business of surfacing every Swagger UI configuration option through Enunciate configuration.

If you'd like to tweak the Swagger UI index page (and associated `SwaggerUI` javascript object), you can do so by configuring Enunciate to use a custom "base". For details, see [Swagger Module Documentation](https://github.com/stoicflame/enunciate/wiki/Module-Swagger#updating-or-configuring-swagger-ui).

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
