### ISSUE TITLE
Question: Why Annotations and not custom Javadoc-Tags?

### ISSUE THREAD

**Issue by cheppsn** [stoicflame/enunciate#306]
Just a curious question (I read in the FAQ that an issue seems to be appropriate for this):

Enunciate solves the problem of "missing information" with custom annotations that can be added to the API code. We are currently in the process of evaluating Enunciate as an alternative to Spring-Fox for Swagger, which we want to dump, because no one can see the relevant code anymore due to way too many annotations.

Enunciate may help us solving many of those problems, especially with respect to method documentation, which can now be done with Javadoc instead of using an annotation. However, I wonder why the Enunciate-extensions were realized as custom annotations and not as custom Javadoc tags? If e.g. response-codes or labels were Javadoc-Tags, they would not lead to "stacks of annotations" above a method declaration and could be folded away easily in most IDEs.

I understand that annotations will end up in Javac's AST and are thus easy to process. But I've just had the experience with Springfox, that annotations which are not relevant for the execution lead both to confusion and irritation. If they were contained in the comment, it would be instantly clear, that they have only documentational value.

**Comment by stoicflame** [comment]
Decent question.

Enunciate JAX-RS module actually supports [JAX Doclets](http://fromage.github.io/jax-doclets/docs/0.10.0/html/#d0e463). We can add that support for Spring-WS module, too. I'll track this as a feature request.

Are there any other doclets that you'd like to see supported?

**Comment by cheppsn** [comment]
I looked around a bit, but didn't find anything else that I would suggest at the moment. The JAX-RS Javadoc Tags (especially @HTTP) would be very helpful.

**Comment by stoicflame** [comment]
Fixed at a50fe0f.

Documentation at https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations updated.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
