### ISSUE TITLE
Enunciate does not generate documentation for JAX-RS sub resources

### ISSUE THREAD

**Issue by nfalco79** [stoicflame/enunciate#307]
Hi, looking our documentation we notice that enunciate had not generated all documentation about JAX-RS sub resource. Specifications coulb be found [here](https://docs.oracle.com/javaee/6/tutorial/doc/gknav.html).
Some documentation examples could be found [on jersey doc](https://jersey.java.net/documentation/latest/jaxrs-resources.html#d0e2464) or [on reasteasy doc](https://docs.jboss.org/resteasy/docs/1.0.2.GA/userguide/html/JAX-RS_Resource_Locators_and_Sub_Resources.html).

This is an example project
[issue307.zip](https://github.com/stoicflame/enunciate/files/122880/issue307.zip)

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by nfalco79** [comment]
It fails when the subresource locator method return a Class<Subresource>, if method returns the instance of Subresource then documentation it's ok.
The Specifications permit both methods, the first one to have variables that comes from jax-rs context (by injection) in the contructor and/or fields. The second one when you need customise instance of Subresource class. In both cases the only way to have the correct implementation of Subresource is at runtime because I can return a subclass than declared as return type.
So, actually I think for the in case where subresource locator returns Class<Type> enunciate could parse the source (as already do for javadoc) to get the Generics type and/or provide other annotation to describe the all possible classes that subresource locator could returns.

What do you think?

**Comment by stoicflame** [comment]
Huh. I didn't know that was possible. But your suggestion seems like the right thing to do.

It seems quite complicated. And I'm also not sure what the HTML would look like in the case where there are multiple possibilities.

**Comment by stoicflame** [comment]
Fixed at 1abca19.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).

**Comment by SushmitaGoswami** [comment]
Is there any way to keep the javadoc of resource along with the javadoc of SubResource for the documentation?

**Comment by stoicflame** [comment]
@SushmitaGoswami I don't have a clear picture of what you're asking. Can you put together a sample project that illustrates the need and open up a separate issue?

**Comment by SushmitaGoswami** [comment]
Yeah sure @stoicflame i will open up a separate issue, for having some sample project i would need some time. Actually problem is i have a rest api in some resource which returns another resource(which has an api that returns performs the action) as a result using the JAX-RS subresource mechanism. Now any javadoc present in the subresource file is appearing in swagger and no javadoc from main called resource is appearing in swagger. I am using enunciate plugin to generate swagger from javadoc. How can i solve this?

**Comment by stoicflame** [comment]
Okay, I think I understand the request, but I guess I don't understand why you want that.

Anyway, my suggested workarounds:

* Copy the JavaDocs from the parent resource to the subresource.
* Group by path or annotation instead of by resource class.
