### ISSUE TITLE
All input parameters are shown as optional on Swagger UI

### ISSUE THREAD

**Issue by egemenvardar** [stoicflame/enunciate#310]
When I generate Swagger documentation by using Enunciate all input parameters (JSON) are shown as optional on the Swagger UI (please see the attachment). I see that Swagger has the "required" parameter to mark a field as mandatory. Is there a way to control this via Enunciate settings?

Note that I use @NotNull and @NotEmpty annotations for mandatory parameters. Would it be possible for Enunciate to look for those annotations in order to determine whether a parameter is optional or not?

Thanks in advance.

![swagger_all_params_optional](https://cloud.githubusercontent.com/assets/17125072/13044449/8caa7682-d3ce-11e5-8c5d-1e0da953d337.png)

**Comment by stoicflame** [comment]
Thanks for the report. I think we should be able to support the `@NotNull` and `@NotEmpty` annotations as you request.

**Comment by egemenvardar** [comment]
Great, thank you!

**Comment by stoicflame** [comment]
Fixed at 64c2c64.

I'm assuming the `@NotNull` annotation you're referring to is `@javax.validation.constraints.NotNull`. I couldn't find any standard `@NotEmpty` annotations. There's the hibernate one, but that's implementation-specific so I didn't implement support for it.

**Comment by egemenvardar** [comment]
Yes I was referring to `javax.validation.constraints.NotNull`. For `@NotEmpty` I meant the hibernate one yes - but ok fair enough. I will think of a workaround then.

Thanks for the fix.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).

**Comment by landonvg** [comment]
Does this change support any other `javax.validation.constraints` annotations, or just `@NotNull`?

**Comment by stoicflame** [comment]
Just `@NotNull` for now.
