### ISSUE TITLE
Enunicate dont recognize objects as as query parameters

### ISSUE THREAD

**Issue by oeystein** [stoicflame/enunciate#311]
For convenience purposes i have implemented some Getters which takes complete objects as query parameters. The methods i have commonly used this approach on is methods which got quite a few parameters and is easier described as a json object, rather then many individual query parameters. If this is good REST design is totally discussable, however i belive that quite a few bigger search engines have taken the same approach(such as elastic search). 

The problem with these query parameters, is that they don't appear to be recognized as the objects they represent, and just show as a type = "query" in the generated docs. I was wondering if it would be possible to do something about this? I've attempted to override the query parameter with the @TypeHint annotation, with no success. 

Example:

```
@NotNull
@Path("logs")
@GET
@RequirePermission(AccessRight.VIEW)
@StatusCodes({
   @ResponseCode(code = 200, condition = "Log entries returned"),
   @ResponseCode(code = 403, condition = "Not authorized"),
})
public List<LogEntry> getLogs(@Nullable @QueryParam("selector") LogSelector selector)
{
  .....
   return logs;
}
```

Would generate something like 

![screenshot from 2016-02-15 10 20 58](https://cloud.githubusercontent.com/assets/3736097/13044641/840c5f08-d3cf-11e5-8197-23ac7c8203d8.png)

**Comment by stoicflame** [comment]
So if I understand correctly, you're passing JSON as the value of the query parameter, correct?

So the API above would be invoked like:

```
GET /device/logs?selector={"prop1" : "value1","prop2" : "value2", "prop3" : "value3"}
```

Is that correct?

How does your JAX-RS implementation know that the query parameter is supposed to be parsed as JSON? Do you have to do some custom providers or something?

**Comment by oeystein** [comment]
That is correct yes, sorry for any confusion. 

And the way i solved it was by using a custom implementation of [ParamConverterProvider](https://docs.oracle.com/javaee/7/api/javax/ws/rs/ext/ParamConverterProvider.html). 

```
@Provider
public class CustomParamConverterProvider implements ParamConverterProvider {

    @Nullable
    @SuppressWarnings("unchecked")
    @Override
    public <T> ParamConverter<T> getConverter(@NotNull Class<T> type, Type genericType, Annotation[] annotations) {
        if (RestParameter.class.isAssignableFrom(type)) {
            return new RestParamConverter(type);
        }
        return null;
    }
}
```
Where RestParameter.class is just an empty interface that i implement all classes i wish to take in as a query parameters. And RestParamConverter<T>.class is a generic implementation of [ParamConverter](https://docs.oracle.com/javaee/7/api/javax/ws/rs/ext/ParamConverter.html), which simply uses FasterXml to translate the incoming query objects parameters from JSON and XML.

**Comment by stoicflame** [comment]
Okay, I understand.

Well, I'll take a look for 2.3. If there's an easy way to do it, we might be able to slip it in to the next release.

**Comment by stoicflame** [comment]
I spent some time looking at this, but until this technique becomes standardized (or until someone wants it enough to pay for commercial support) I don't see myself getting around to implementing support for it because it's such a customized mechanism. If we ever did implement it, it would need to be off by default and enabled via configuration because of the many other possible ways people may have implemented param converters.

I'll leave the issue open to allow for others to voice support for it, but it won't be assigned to any release for now.

**Comment by oeystein** [comment]
That is completely understandable, thanks for your support! I may see if i can find a workaround somehow.

**Comment by stoicflame** [comment]
This issue has been stale for a little less than a year now, and I'm comfortable with the choice to not implement it for now.

If support for this feature builds, I'd be happy to re-open.
