### ISSUE TITLE
Multi-module maven project doesn't get documented with jackson

### ISSUE THREAD

**Issue by patvong** [stoicflame/enunciate#317]
I have a multi module project and I followed this wiki https://github.com/stoicflame/enunciate/wiki/Multi-Module-Projects to make sure all the source jars are created for each modules.
I noticed that I need to use the @JsonProperty so that Enunciate can pick up the fields/properties of my data type classes.
However, for some reason, if I add this configuration:
```
<sourcepath-excludes>
          <exclude>
            <groupId>com.mycompany</groupId>
          </exclude>
</sourcepath-excludes>
```
Enunciate will pick up all the fields from all modules, but it will not generate the documentation that I added on the class or on the fields/properties.

**Comment by stoicflame** [comment]
So is the problem that you need to add `@JsonProperty` or is it that the documentation is missing?

**Comment by patvong** [comment]
1. The field were all present, but the documentation was missing
2. I added 
```
<sourcepath-excludes>
          <exclude>
            <groupId>com.mycompany</groupId>
          </exclude>
</sourcepath-excludes>
```
Then some documentation was present e.g. the class documentation, but not the field documentation. To be able to view the fields and their documentation I had to add @JsonProperty.

**Comment by patvong** [comment]
After further investigation, it seems related to the usage of Lombok's annotations.
I have this class annotated with lombok, except for the `activated` field where I manually create the getter and setter. The class is in a module A.
```
/**
 * Represents an active/inactive user
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Data @EqualsAndHashCode(callSuper = true) @NoArgsConstructor @AllArgsConstructor @Builder
public class InactiveUserWS extends ResourceSupport implements Serializable {
	private static final long serialVersionUID = 8510292065307561800L;

	/**
	 *  User email
	 */
	private String email;

	/**
	 *  User password
	 */
	private String password;

	/**
	 * Is user activated
	 */
	private boolean activated;

	/**
	 * Is user activated: GETTER
	 */
	public boolean isActivated() {
		return activated;
	}

	public void setActivated(boolean v) {
		this.activated = v;
	}
}
```
## 1. Excluded sources
I have another module B that includes module A with the class `InactiveUserWS`. From module B I run enunciate. This is what Enunciate will generate me if I exclude the source in the enunciate-maven-plugin configuration:
```
<sourcepath-excludes>
   <exclude>
      <groupId>com.appdirect</groupId>
   </exclude>
</sourcepath-excludes>
```
![screen shot 2016-02-17 at 4 56 19 pm](https://cloud.githubusercontent.com/assets/7417421/13126303/e0e32508-d597-11e5-9c52-b1af6018bca7.png)
Notice that the fields are detected, but not the documentation. Also the class documentation is not present.

## 2. Sources not excluded
Then I remove the previous exclusion from the enunciate-maven-plugin configuration:
```
<sourcepath-excludes>
   <exclude>
      <groupId>com.appdirect</groupId>
   </exclude>
</sourcepath-excludes>
```
This is what I get from Enunciate:
![screen shot 2016-02-17 at 6 26 43 pm](https://cloud.githubusercontent.com/assets/7417421/13128486/0805bf5e-d5a4-11e5-9e2e-b14bd7489605.png)
Notice that only the `activated` field was documented. The class documentation is present too.

That brings me to believe that when Enunciate looks at the source jar that contains my class it won't see the getter and setter provided by lombok thus eliminates the field from the documentation. I think that's fair and I might consider using https://projectlombok.org/features/delombok.html to package a source jar with the getter/setters from lombok. 

However, I don't understand how in the first case Enunciate was able to get all the fields?

## 3. Usage of JAXB annotations
Now if I add the class annotations:
```
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
```
Enunciate will generate the documentation as expected:
![screen shot 2016-02-17 at 8 00 30 pm](https://cloud.githubusercontent.com/assets/7417421/13130318/27c72bcc-d5b1-11e5-9019-09973ec2288a.png)
Note that the documentation will be taken from the field and not from the getter for the `activated` field.
It seems that if those annotations are present, Enunciate will scan through all the fields, even if they are private.
Is it possible to have this kind of support for Jackson?

## Possible solution/workaround
In descending order of preferences:
* Support something similar to `@XmlRootElement` and `@XmlAccessorType(XmlAccessType.FIELD)` for Jackson
* Possibility to detect the @Getter and @Setter lombok annotation on the class? If yes, then Enunciate should document all the fields even if private?
* Use delombok
* Use @JsonProperty on every field
* Other ideas?

**Comment by patvong** [comment]
I found out I could use `@JsonAutoDetect(getterVisibility = JsonAutoDetect.Visibility.ANY, fieldVisibility = JsonAutoDetect.Visibility.ANY)` to fix my problem. However I can't find a way to arbitrary ignore a field?
`@Ignore` and `@Facet("ignore")` won't work on fields. Any tips?

**Comment by stoicflame** [comment]
`@JsonIgnore`

See [Jackson-Annotations](https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations).

**Comment by stoicflame** [comment]
@patvong, thanks for the thread and the details. After reading through your observations above, I think you came to the right solution to use `@JsonAutoDetect` to specify the field visibility. Since Enunciate supports this annotation, I'm going to consider this issue closed. I'd be happy to re-open as needed.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
