### ISSUE TITLE
maven docs goal generates output in the top-level target directory when building a module in a multi-module build

### ISSUE THREAD

**Issue by stolp** [stoicflame/enunciate#319]
I have the following rather common maven multi-module setup:

```
<top-level module>
- <parent module>
- <api module>
- ...

```
`parent module` is the common parent of all sub modules.

If I build the enunciate documentation in `api module` all is well and the documentation gets generated in `<api module>/target/enunciate/docs` as expected.

If I build the` top-level module` the documentation is build in `<top-level module>/target/enunciate/docs` instead which looks like an error to me.

Here is my maven target from `api module`:

```
      <plugin>
        <groupId>com.webcohesion.enunciate</groupId>
        <artifactId>enunciate-slim-maven-plugin</artifactId>
        <configuration>
          <configFile>${project.basedir}/src/enunciate/enunciate-config.xml</configFile>
          <docsDir>${project.build.directory}/enunciate</docsDir>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>docs</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

```
I also tried changing or removing the docsDir parameter but to no avail.
I am using enunciate 2.2.0.

Am I missing something?

**Comment by stoicflame** [comment]
Enunciate needs a directory to use as a "build" directory; somewhere to temporarily put files that get copied or generated. By default, it's "${project.build.directory}/enunciate". You can change it with the `buildDir` configuration parameter.

**Comment by stolp** [comment]
This directory is getting generated in `api module` and contains a temporary enunciate xml file.
This is true for both kind of invocations.

Yet the initial symptom still holds, the generated docs are located in  `top level module/build/enunciate/docs` if I call `maven clean package` from the `top level module`.

If I call `maven clean package` from `api module` the docs are located in `top level module/api module/build/enunciate/docs.

There has to be a mismatch somewhere.

**Comment by stoicflame** [comment]
Isn't this just how Maven works? I'm not seeing the problem yet...

**Comment by stolp** [comment]
The `api module` is producing the enunciate docs alongside with the regular module jar as an artifact via the maven-assembly plugin. To produce this artifact the docs are expected to reside in the target directory of the module itself.

When I invoke a top level build the generated docs are suddenly  located in the top-level build directory instead and the maven assembly plugin will fail.

This is definitely not the way maven should work. My suspicion is, that the enunciate maven plugin has the wrong concept of where ${project.build.directory} is located when it is invoked via a sub module.

**Comment by stoicflame** [comment]
Oh, so you're reporting that when invoked via the top-level build, the docs are _not_ generated in the module's target directory, only in the parent's target directory?

I've never seen that. What does your enunciate.xml file look like?

**Comment by stolp** [comment]
Exactly, sorry for not being verbose enough.

Looking at the enunciate.xml I find the following:

`<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/stoicflame/enunciate/master/top/src/main/resources/META-INF/enunciate-2.0.0.xsd">

  <title>Klaros-Testmanagement REST Service API</title>
  <description>This document covers the HTTP/REST based API of Klaros-Testmanagement.</description>
  <contact name="verit Informationssysteme GmbH" email="support@verit.de" url="http://www.klaros-testmanagement.com"/>

  <api-classes>
    <include pattern="de.verit.klaros.api.**" />
    <exclude pattern="org.jboss.resteasy.**"/>
    <exclude pattern="org.jboss.seam.resteasy.**"/>
  </api-classes>

  <namespaces>
   <namespace uri="http://klaros-testmanagement.com/resources/" id="resources"/>
  </namespaces>
 
  <modules>
    <c-xml-client disabled="true"/>
    <csharp-xml-client disabled="true"/>
    <docs disabled="false" docsDir="target/enunciate/docs" /> 
    <gwt-json-overlay disabled="true" />
    <idl disabled="true" disableWadl="true"/>
    <jackson disabled="false" honorJaxb="true" datatype-detection="passive"/>
    <jackson1 disabled="true"/>
    <java-json-client disabled="true" />
    <java-xml-client disabled="true" />
    <jaxb disabled="false" datatype-detection="passive"/>
    <jaxrs groupBy="path" disabled="false" datatype-detection="local" />
    <obj-c-xml-client disabled="true" />
    <php-json-client disabled="true" />
    <php-xml-client disabled="true" />
    <ruby-json-client disabled="true" />
    <swagger disabled="true" />
  </modules>
</enunciate>
`
Thanks for the reminder about `enunciate.xml`, I lost track of the docs entry there. So the culprit may be the following entry:

`    <docs disabled="false" docsDir="target/enunciate/docs" /> 
`
Removing the `docsDir` attribute indeed fixed the problem as now the documentation is correctly generated in the module directory. So I think there  are actually two bugs present:

1. A relative docsDir entry in enunciate.xml is applied against the current directory of the initial maven invocation instead of the module directory the enunciate maven plugin is executed in.
2. A `docsDir` entry in the maven plugin configuration is not overriding an existing entry in `enunciate.xml`.

Thanks for your great support.

**Comment by stoicflame** [comment]
I took some time to look into this further.

As to how the `docsDir` attribute gets resolved, it's relative to the directory that contains the configuration file. It has been this way for awhile so I'm nervous about changing that because I think it will affect a significant number of people who are already expecting current behavior. I think the best solution here is to use the "${basedir}" maven property e.g.:

```xml
<docs docsDir="${basedir}/target/enunciate/docs"/>
```

Likewise, the settings in the configuration file have always overridden the settings in the maven plugin configuration, so (again) I'm nervous about changing that behavior because I think it will affect a significant number of people. I think the best solution here is to make sure the settings aren't conflicting.

**Comment by stolp** [comment]
Agreed, it is almost always a bad idea to change an existing behavior. IMHO it would be good if the maven plugin documentation would clearly state that the configuration values are overridden by values in the configuration file.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
