### ISSUE TITLE
Enunciate generated web page has bug in menu

### ISSUE THREAD

**Issue by Cymoud** [stoicflame/enunciate#322]
Generated web pages with Enunciate has a bug with the highlight of current element in the bootstrap menu on page resource_...html.
The bug is seen when a resource has sub ressource with the same HTTP method.
See the screenshot. But here in 2.1.1 and latest 2.2.0.
![2016-02-24 15_08_26-mobile server webservice_ userresource](https://cloud.githubusercontent.com/assets/5937797/13288297/a4aacf18-db0b-11e5-9d62-f2bcbed753ba.jpg)

**Comment by stoicflame** [comment]
Fixed at 3391f50.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
