### ISSUE TITLE
Unexpected Behavior on jaxws datatype-detection="aggressive" 

### ISSUE THREAD

**Issue by Matthias-Ni** [stoicflame/enunciate#323]
Hello, 

in my Current Project I have 2 Classes that are annotated with @Webservice. One is inside my multi module maven project in a JAR module. The other class is also in a JAR module but that module is not part of my Project. (referenced as Maven dependency in the WAR module)

I want to generate single documentation website with both services included. I have added the 
enunciate-maven-plugin to the War module of my current project and set jaxws datatype-detection="aggressive". (Without this option the Service in the other Project is not found)

I have 2 issues with the generated HTML: 

1. The Webservice that is inside my multi module project gets listed 2 times. 
2. The Webservice that is inside the other project is listed but the comments from the javadoc are missing. 

Is this a bug or do I have to configure something else?

**Comment by stoicflame** [comment]
The only explanation I have for the duplicate web service is that it's on your classpath twice. When you do a "mvn dependency:list" would the class show up in more than one of those entries?

The only explanation I have for missing javadoc is that you don't have the source path to that web service set up correctly. See [Providing a Source Path](https://github.com/stoicflame/enunciate/wiki/Multi-Module-Projects#providing-a-source-path).

**Comment by Matthias-Ni** [comment]
Thank you for your fast answer. 

After providing a correct source path the javadoc is now available in the documentation. :+1: 

However now both Webservices are listed 2 times. There is only one  HTML file for each of the services but in there are 2 entries in the table. 

mvn dependency:list shows only 1 entry for the libraries containing the @Webservice classes.

**Comment by Matthias-Ni** [comment]
Hello again! The problem still exists. Do you have any idea why? The methods are also duplicated in the generated wsdl file so I can't really use them...

**Comment by stoicflame** [comment]
I haven't had a chance to look deeper at the issue. It will take some effort to try to reproduce it. If you can provide a sample project or something that manifests the issue, it will expedite the process.

**Comment by stoicflame** [comment]
I never figured out how to reproduce the issue, but I believe that the fix at e401168 will address this issue.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
