### ISSUE TITLE
Documentation module: (relative) base folder

### ISSUE THREAD

**Issue by steinermatt** [stoicflame/enunciate#324]
Hi there,

trying to migrate from 1.x to 2.x and having a rough start. In my **enunciate.xml** file I have specified a base attribute pointing to the ZIP file as such:

`<docs splashPackage="xyz" title="Test"
			copyright="none" includeDefaultDownloads="false" includeExampleXml="false"
			includeExampleJson="true" groupRestResources="grouping" applyWsdlFilter="false"
			docsDir="docs" freemarkerXMLProcessingTemplate="docs.fmt" base="docs-base.zip">		`

That used to work just fine in 1.x as the **enunciate.xml** file was in the same folder as the base ZIP file. In 2.x I get an exception:

`
Execution default of goal com.webcohesion.enunciate:enunciate-maven-plugin:2.2.0:docs failed: com.webcohesion.enunciate.EnunciateException: java.io.FileNotFoundException: docs-base.zip (No such file or directory): OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]
`
Any pointers?

Thanks and Best regards,
Matthias

**Comment by stoicflame** [comment]
Seems like it _might_ be a bug, since the docs-base.zip should be resolved relative to the config file. I'll take a closer look for 2.3.

**Comment by marvinvs** [comment]
If it helps I've worked around this in my Maven project by adding the full path to the base (in my case, a directory rather than a ZIP file):

``
    <docs disableRestMountpoint="true" freemarkerTemplate="${basedir}/src/enunciate/docs.fmt" base="${basedir}/src/enunciate/base"/>
``

My project structure is:

``
src/
   enunciate/
      base/
         img/
      docs.fmt
``

**Comment by stoicflame** [comment]
Fixed at 79c30f4.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
