### ISSUE TITLE
How to force utf-8 encoding in wsdl files?

### ISSUE THREAD

**Issue by Matthias-Ni** [stoicflame/enunciate#325]
Hello. 
Is there any way to force the encoding of the generated wsdl documents to utf8? I already set the encoding option on the Maven Plugin to utf8 however the generated wsdl files are still encoded in ansi and all special characters are wrong. So I can't generate clients of them or use then with soapui.

**Comment by stoicflame** [comment]
I'm pretty sure the wsdl is getting written in utf8. Maybe the source code isn't getting read in utf8?

```xml
      <plugin>
        <groupId>com.webcohesion.enunciate</groupId>
        <artifactId>enunciate-maven-plugin</artifactId>
        <version>${enunciate.version}</version>
        <configuration>
          <encoding>utf-8</encoding>
        </configuration>
      </plugin>
```

**Comment by stoicflame** [comment]
I'm afraid I can't reproduce this issue. The special characters are getting correctly written for me.

I'm happy to re-open if you can provide a way to reproduce it.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
