### ISSUE TITLE
Enunciate fails on project that does not contains services

### ISSUE THREAD

**Issue by nfalco79** [stoicflame/enunciate#326]
Enunciate 2.x fail on project that does not contains services that differs with the previous version of Enunciate 1.x.

Projects are tipically structured with at least a parent pom that includes all modules needed to deliver a product (for example apache commons projects). By default parent project has packaging pom, then it will never contains services of any kind so it fails.
Personally I would configure enunciate in reporting section of the parent pom otherwise I should setup project by project which enable it or not for documentation. We have about 30/50 modules (bundles) for client and it's hard to keept documentation update.

I think that the previous version the default was more opened to complex scenarios, where people that does not want empty documentation page setup single projects. Maybe goal could be obtain adding a property similar to failOnNoDocumentation that could lead the behaviour.

**Comment by nfalco79** [comment]
Seems that maven build differs from programmatic and ant way where if no service was found than a dummy class `com.webcohesion.enunciate.Nothing` is added by default so compile does not fails.

**Comment by stoicflame** [comment]
So what's the error that causes the build to fail on empty projects?

**Comment by nfalco79** [comment]
mvn clean package site fails with
`com.webcohesion.enunciate.EnunciateException: There are no data types, services, or resources to document.`

**Comment by nfalco79** [comment]
Instead ant build
```
Buildfile: build.xml
default:
No JAXB XML data types: C XML client will not be generated.
No JAXB XML data types: C# XML client will not be generated.
No Jackson JSON data types: GWT JSON overlays will be generated.
No Jackson JSON data types: Java JSON client will not be generated.
No JAXB XML data types: Java XML client will not be generated.
No JAXB XML data types: Objective-C XML client will not be generated.
No Jackson JSON data types: PHP JSON client will not be generated.
No JAXB XML data types: PHP XML client will not be generated.
No Jackson JSON data types: Ruby JSON client will not be generated.
No resource APIs registered: Swagger UI will not be generated.
Skipping documentation source generation as everything appears up-to-date...
BUILD SUCCESSFUL
Total time: 1 second
```

**Comment by stoicflame** [comment]
Fixed at 65d8568.

**Comment by nfalco79** [comment]
With the commit now it produce a wsdocs folder with only a file css/style.css and the link of maven site in under Project Reports is broken.
Please fix the issue removing the return statement so the documentation generated is done correctly but "empty" (no resources, no model, no client).

**Comment by nfalco79** [comment]
Do you prefer I fill a new bug "report should not be executed if there are no data types, services, or resources to document"?

**Comment by stoicflame** [comment]
I implemented better logic for the `canGenerateReport` method at 146f120.

**Comment by nfalco79** [comment]
Works great!

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
