### ISSUE TITLE
javac-support doesn't compile

### ISSUE THREAD

**Issue by steinsag** [stoicflame/enunciate#328]
I forked the project and tried an initial compile with

    mvn clean package

Build fails in module javac-support:

> [INFO] ------------------------------------------------------------------------
> [INFO] Building Enunciate - Javac Support 2.3.0-SNAPSHOT
> [INFO] ------------------------------------------------------------------------
> [INFO]
> [INFO] --- maven-clean-plugin:2.5:clean (default-clean) @
> enunciate-javac-support ---
> [INFO] Deleting
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/target
> [INFO]
> [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @
> enunciate-javac-support ---
> [INFO] Using 'UTF-8' encoding to copy filtered resources.
> [INFO] skip non existing resourceDirectory
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/resources
> [INFO]
> [INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @
> enunciate-javac-support ---
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 35 source files to
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/target/classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/DecoratedElements.java:[19,8]
> com.webcohesion.enunciate.javac.decorations.DecoratedElements is not abstract
> and does not override abstract method
> isFunctionalInterface(javax.lang.model.element.TypeElement) in
> javax.lang.model.util.Elements
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedTypeMirror.java:[27,8]
> com.webcohesion.enunciate.javac.decorations.type.DecoratedTypeMirror is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/element/DecoratedElement.java:[33,8]
> com.webcohesion.enunciate.javac.decorations.element.DecoratedElement is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/element/DecoratedExecutableElement.java:[40,8]
> com.webcohesion.enunciate.javac.decorations.element.DecoratedExecutableElement
> is not abstract and does not override abstract method isDefault() in
> javax.lang.model.element.ExecutableElement
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedReferenceType.java:[24,8]
> com.webcohesion.enunciate.javac.decorations.type.DecoratedReferenceType is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedDeclaredType.java:[35,8]
> com.webcohesion.enunciate.javac.decorations.type.DecoratedDeclaredType is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedNoType.java:[25,8]
> com.webcohesion.enunciate.javac.decorations.type.DecoratedNoType is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/element/DecoratedPackageElement.java:[27,8]
> com.webcohesion.enunciate.javac.decorations.element.DecoratedPackageElement is
> not abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedNullType.java:[26,8]
> com.webcohesion.enunciate.javac.decorations.type.DecoratedNullType is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/element/DecoratedTypeParameterElement.java:[31,8]
> com.webcohesion.enunciate.javac.decorations.element.DecoratedTypeParameterElement
> is not abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedExecutableType.java:[33,8]
> com.webcohesion.enunciate.javac.decorations.type.DecoratedExecutableType is not
> abstract and does not override abstract method getReceiverType() in
> javax.lang.model.type.ExecutableType
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/element/DecoratedTypeElement.java:[41,8]
> com.webcohesion.enunciate.javac.decorations.element.DecoratedTypeElement is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedTypeVariable.java:[30,8]
> com.webcohesion.enunciate.javac.decorations.type.DecoratedTypeVariable is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedWildcardType.java:[28,8]
> com.webcohesion.enunciate.javac.decorations.type.DecoratedWildcardType is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedArrayType.java:[28,8]
> com.webcohesion.enunciate.javac.decorations.type.DecoratedArrayType is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedErrorType.java:[29,8]
> com.webcohesion.enunciate.javac.decorations.type.DecoratedErrorType is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/type/DecoratedPrimitiveType.java:[32,8]
> com.webcohesion.enunciate.javac.decorations.type.DecoratedPrimitiveType is not
> abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [ERROR]
> /home/steinchen/Work/programmierung/github/steinsag-enunciate/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/element/DecoratedVariableElement.java:[25,8]
> com.webcohesion.enunciate.javac.decorations.element.DecoratedVariableElement is
> not abstract and does not override abstract method
> <A>getAnnotationsByType(java.lang.Class<A>) in
> javax.lang.model.AnnotatedConstruct
> [INFO] 18 errors

I'm using javac 1.8.0_66-internal from OpenJDK on Ubuntu.

**Comment by stoicflame** [comment]
As you discovered at #329, Enunciate requires JDK 7.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
