### ISSUE TITLE
StatusCodes annotation should allow inheritance

### ISSUE THREAD

**Issue by steinsag** [stoicflame/enunciate#330]
Please allow inheriting StatusCodes annotation in JAX-RS. All my Resource classes (JAX-RS endpoints) inherit some base resource class, which is annotated with StatusCodes. However, those annotations are not seen by enunciate on the child classes and no status code section is generated. If I add the StatusCodes annotation directly to my child classes, everything works as expected.

I tried fixing that on my own by adding

    @Inherited

to StatusCodes and ResponseCode annotation classes, but for some reason it doesn't work. I can't really see where it fails, because in ResourceMethod class you are also querying the StatusCodes annotations of the parent, which is the Resource class.

**Comment by stoicflame** [comment]
Seems like a reasonable enhancement request.

**Comment by stoicflame** [comment]
Fixed at 0111955.

**Comment by steinsag** [comment]
Thank you very much, works perfectly, just tested it!

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
