### ISSUE TITLE
Detect array type in a query parameter

### ISSUE THREAD

**Issue by patvong** [stoicflame/enunciate#331]
Say I have an operation defined like this:
```
Response readData(
   @QueryParam("categoryIds") Set<Long> categoryIds,
   @QueryParam("productTypes") Set<ProductEnumType> productTypes,
   @QueryParam("statuses") List<StatusEnumType> statuses
);
```
Enunciate will correctly detect the constraint on `categoryIds` to `long` and on `productType` to an enum type constraint `"A" or "B" or "C"`. However it is missing the fact that the parameter is accepting a `List` or a `Set` of values.

I would need this information to improve the swagger json freemarker template and set the type to the following: 
````
"type" : "array",
"items" : {
   "type" : "integer"
}
``` 
Or 
````
"type" : "array",
"items" : {
   "enum" : ["A", "B", "C"]
}
``` 
Currently the freemarker template is always setting the parameter type to: `"type" : "string"`
Is that possible?

See:
* http://swagger.io/specification/#parameterObject
* http://swagger.io/specification/#itemsObject

**Comment by stoicflame** [comment]
I can take a look for 2.3.

**Comment by stoicflame** [comment]
Fixed at 6089c07.

**Comment by patvong** [comment]
Thanks!

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
