### ISSUE TITLE
ruby-json module isn't utilizing @XmlSeeAlso

### ISSUE THREAD

**Issue by darmbrust** [stoicflame/enunciate#336]
Another issue which we identified from the example in https://github.com/stoicflame/enunciate/issues/334 is that the ruby generator is ignoring the XmlSeeAlso annotations - and if there is no other reference to one of the classes in the XmlSeeAlso - it doesn't generate a ruby equivalent class for the classes in XmlSeeAlso.

I'm just starting to look into this issue - any hints on where I would need to tweak the code generator to inject the classes from the XmlSeeAlso into the ruby generator?  Is there an alternate annotation that I could add that would make it pick them up?

**Comment by stoicflame** [comment]
Yeah, so that was deliberate because `@XmlSeeAlso` is a JAXB (XML) annotation and Jackson (the JSON implementation) doesn't honor that annotation. Since the Ruby client code uses JSON, that annotation isn't considered when determining the data types.

I was looking for an equivalent annotation in the Jackson library, but couldn't find one exactly equivalent. There's the `@JsonSubTypes` annotation to use in the case of subtypes of a collection item type that need to be considered, but that's as close as I could get.

Any other suggestions?

In the

**Comment by stoicflame** [comment]
I'm open to adding an Enunciate-specific annotation if you'd like.

Does using the configuration not work for you?

```xml
<enunciate>
  <api-classes>
    <include pattern="com.mycompany.unreferenced.classes.*"/>
```

**Comment by darmbrust** [comment]
That would certainly work.  I was looking at your docs on the config stuff a bit, but I was only seeing excludes, not includes.

**Comment by cshupp1** [comment]
I like it too!

**Comment by darmbrust** [comment]
Hmm, I misread you comment above.  I hadn't tried the include pattern before... I tried it now - it doesn't seem to have any impact on the output of the ruby code - I've been debugging / poking at the processor, and it appears that when it reads the types from the jackson module, they aren't in there either.

So, I tried setting the jackson datatype-collection to "aggressive" - but then I broke because it found a bunch of stuff on the class path I don't want it to find.   I tried using api-classes exclude, but it doesn't seem to impact the jackson module.

**Comment by darmbrust** [comment]
The only workaround that we have found to guarantee that the proper classes get created is the following.




Add an (undocumented) method to your API:

```
	@GET
	@Produces({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
	@Path("/noop")
	@Facet ("ignore")  //prevent enunciate from documenting this method
	public Z noop() throws RestException
	{
		throw new RestException("These are not the droids you are looking for");
	}
```

Define the class Z as such:
```
	@XmlRootElement
	@Facet ("ignore")
	private class Z
	{
		//Put a reference here to any class that is only referenced by an @XmlSeeAlso
		@XmlElement RestConceptNode a1 = null;
		@XmlElement RestUntypedConnectorNode a2 = null;
		@XmlElement RestTypedConnectorNode a3 = null;
 	}
```

Finaly, do a facet exclude in the enunciate.xml file, so that this method isn't documented:
```
	<facets>
		<exclude name="ignore"/>
	</facets>
```

**Comment by stoicflame** [comment]
At bd7cc9b, I made sure that classes explicitly included in the config file will be added to the context. So you shouldn't need the above-mentioned workaround anymore.

[The documentation on the wiki](https://github.com/stoicflame/enunciate/wiki/Excluding-Including-Classes) was also updated.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).

**Comment by darmbrust** [comment]
I tried configuring 2.3.0 like so:
```
<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.2.0.xsd" >
	<api-classes>
		<!-- This makes sure we don't miss any classes only referenced by @SeeAlso -->
		<include pattern="gov.vha.isaac.rest.api1.data.sememe.*"/>
		<include pattern="gov.vha.isaac.rest.api1.data.sememe.dataTypes.*"/>
		<include pattern="gov.vha.isaac.rest.api1.data.logic.*"/>
		<include pattern="gov.vha.isaac.rest.api1.data.enumerations.*"/>
	</api-classes>
	<facets>
		<exclude name="ignore"/>
	</facets>
</enunciate>
```

But it still seems to miss my classes during the ruby client generation.  I also tried with a fully specified class name, rather than .* wildcards... didn't seem to make any difference.

The workaround above still works.

Am I missing a step?

**Comment by stoicflame** [comment]
I'll re-open for 2.4.

Does the output of "mvn -X" give any clues?

**Comment by stoicflame** [comment]
After digging deeper, I concluded the `api-classes` configuration element method mentioned above would be too aggressive; starting to pull in classes that weren't intended to be JSON classes. So I ended up providing support for the `@com.webcohesion.enunciate.metadata.json.JsonSeeAlso` annotation as a JSON-equivalent to `@XmlSeeAlso` at c275df0.

**Comment by darmbrust** [comment]
sounds good - sorry I never followed up with details on this, it has been on my todo list... just haven't gotten there yet.  I'll test out the new solution in the next few weeks.

**Comment by stoicflame** [comment]
Enunciate 2.4.0 has been released.

**Comment by darmbrust** [comment]
FYI, the new solution works perfectly.

Thanks!
