### ISSUE TITLE
@JsonValue is not considered in example 

### ISSUE THREAD

**Issue by jigarparekh80** [stoicflame/enunciate#337]
if i mark any property with @Jsonvalue then json example is not correct, this is properly honored in case of jaxb with @XMLValue.

Jackson annotation
```
public class User {
	private UserId id;
	private String firstName;
	private String lastName;
}

public class UserId  {
	@JsonValue   
	private String id;
}
```
Jackson example output 
```
{
  "id" : {
    "value" : "..."
  },
  "firstName" : "...",
  "lastName" : "..."
}
```
Jaxb annoation 
```
public class User {
	private UserId id;
	private String firstName;
	private String lastName;
}

public class UserId  {
	@XmlValue   
	private String id;
}
```

Jaxb Example 
```
<user>
  <id>...</id>
  <firstName>...</firstName>
  <lastName>...</lastName>
</user>
```

**Comment by stoicflame** [comment]
I'm afraid I can't reproduce the problem. I tried with both Jackson 1 and Jackson 2, and the example looks good to me; I don't get that extra "value".

[This patch](https://github.com/stoicflame/enunciate/files/176638/jsonvalue-test.txt) can be applied to [branch "step5" of the enunciate-sample](https://github.com/stoicflame/enunciate-sample/tree/step5) to validate what I'm seeing. 

Can you provide an alternate patch that would expose the problem?

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).

**Comment by jigarparekh80** [comment]
hmm.. i tried sample it is working indeed. also tried all possible combination of generics and interfaces i have in my project still working on sample. not able to figure why not working in my project. 
will send you patch if i am able to replicate on sample.
