### ISSUE TITLE
Custom annotations in Javadoc

### ISSUE THREAD

**Issue by marcomotta** [stoicflame/enunciate#339]
Hi,

  I´ve read some similar issues regarding custom tags in Javadoc but didn´t realize any solution.
  We´ve been using older versions of Enunciate documenting our REST API in our Open Data site. 

  We use custom tags in JavaDoc to show our users some real calls to the API. We had a modified freeMarker template do read those tags and display them accordingly on the documentation.

  We recently upgraded our project to the newest Enunciate API (2.2.0) and we aren´t able to read those tags any more. It seems that the "Method" interface doesn´t expose any getters to read the tags anymore.

  Below there´s one JavaDoc example that we use. Please disconsider the text that are in portuguese. We use the custom tag "callExample" to show real calls to the API.

  Does anybody know how to read and reat them in the freeMarker template?

Thanks,
Marco Souza.

    /**
     * Obtém a agenda de reunião das comissões de um período
     *
     * @param dataInicio data de início da agenda no formato AAAAMMDD
     * @param dataFim data de fim da agenda no formato AAAAMMDD
     * @param codParlamentar (opcional) código do parlamentar para mostrar sua participação
     * @param colegiado (opcional) sigla do colegiado
     * @param casa (opcional) sigla da casa
     * @callExample Agenda das comissões no mês de maio de 2013: /agenda/20130501/20130531
     * @callExample Participação do parlamentar de código 70 nas reuniões de comissões em maio de 2013: /agenda/20130501/20130531?parlamentar=70
     * @callExample Agenda das reuniões da CAE em maio de 2013: /agenda/20130501/20130531?colegiado=CAE
     * @callExample Agenda das reuniões de comissões do Congresso Nacional em março de 2015: /agenda/20150301/20150331?casa=CN
     * @return Retorna a agenda de reunião das comissões no período
     */
    @GET
    @Produces({ "application/xml", "text/xml" })
    @Path("{dataInicio:\\d+}/{dataFim:\\d+}")
    public String agendaReuniaoXml(@PathParam("dataInicio") ...

**Comment by stoicflame** [comment]
There's a mechanism to access the annotations, but not the JavaDoc tags. We can get those exposed, too.

**Comment by marcomotta** [comment]
I´ve managed to get some success with the annotations indeed. But there are some restrictions in which annotations we can use and repetitions for the same annotation (what I´ve got int the example above) on the same method.
And, of course, there are the some collateral effects in annotating the code too much, as already stated by other here in this thread.
It would be much appreciated exposing them in the next release.
Thanks for your reply,
Marco.

**Comment by stoicflame** [comment]
Fixed at 7c799a2.

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).
