### ISSUE TITLE
Customize Example body for a returned object

### ISSUE THREAD

**Issue by nemosharma6** [stoicflame/enunciate#343]
For exmaple , I have a function that returns a PAGE object.This object has two variable "page" and "size" both being integers. Now when i view this object(on its html page) it displays the name of its variables and any default value associated with it. Also there is an example PAGE object with it.
For e.g.

`{
  "page" : 12345,
  "size" : 12345
}`

Now i want to change this default value i.e. 12345 to my another appropriate value.
How to resolve this.

**Comment by stoicflame** [comment]
https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#cwemdocumentationexample

**Comment by nemosharma6** [comment]
I tried @DocumentationExample but its not working for me.

**Comment by stoicflame** [comment]
Works for me.

Can you tell me how to patch the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) to expose the problem you're seeing?

**Comment by nemosharma6** [comment]
I am using jackson2 and this is the configuration for my project. 

`<modules>
    <jaxb disabled="true"/>
    <jackson2 disabled="false" honorJaxb="true" datatype-detection="passive"/>
    <jaxws disabled="true"/>
</modules>`

I looked into #276 but was unable to resolve it.

**Comment by stoicflame** [comment]
Still works for me.

Maybe you're annotating the field when you should be annotating the property, or vice-versa.

**Comment by nemosharma6** [comment]
Could you suggest an example wherein @DocumentationExample is used.

**Comment by stoicflame** [comment]
Yeah, the annotation probably needs to be applied to the public member.

E.g. apply [this patch](https://github.com/stoicflame/enunciate/files/176587/documentation-example.txt) to [enunciate-sample](https://github.com/stoicflame/enunciate-sample).
[documentation-example.txt]

**Comment by stoicflame** [comment]
[Enunciate 2.3 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.3.0).

**Comment by nemosharma6** [comment]
Thanks.
