### ISSUE TITLE
Body of type byte[] is not correctly rendered by swagger-ui

### ISSUE THREAD

**Issue by javierestevez** [stoicflame/enunciate#346]
Hello,

I am using enunciate 2.3.0 to document my REST API and generate a swagger-ui client. One of my PUT-annotated methods has a byte[] argument as the request body.

`
@PUT
@Path("{personId}/profile/picture")
@Consumes({"image/png", "image/jpg"})
public void setPersonProfilePicture(@NotNull @PathParam("personId") PersonRef personRef, byte[] picture) {
    // implementation of the resource
}
`

Enunciate generates this operation within "paths" in the swagger.json file:

`
"put" : {
        "tags" : [ "PersonResource" ],
        "description" : "",
        "operationId" : "resource_PersonResource_setPersonProfilePicture_PUT",
        "consumes" : [ "image/jpg", "image/png" ],
        "produces" : [ "application/json" ],
        "parameters" : [
          {
            "name" : "Accept-Language",
            "in" : "header",
            "default" : "en",
            "type" : "string",
            "enum" : ["DUTCH", "ENGLISH", "FRENCH"],
            "description" : ""
          },
          {
            "name" : "personId",
            "in" : "path",
            "type" : "string",
            "description" : ""
          },
          {
            "name" : "body",
            "in" : "body",
            "schema" : {
              "type" : "object"
            },
            "description" : ""
          }
        ]
`

However, this is no correctly rendered by swagger-ui. I've had a look into their spec and it seems that using a body of type object is not correct. The type object should be used only for the definitions. The string type with binary or byte formats seems more appropriate and is correctly rendered. Or it could even be created using the type file depending on the media type.

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
Fixed at 8eded38.

**Comment by stoicflame** [comment]
Fixed at 8eded38.

**Comment by stoicflame** [comment]
Enunciate 2.4.0 has been released.
