### ISSUE TITLE
Missing slash in generated documentation

### ISSUE THREAD

**Issue by TheOnlyAl** [stoicflame/enunciate#347]
Hi.

we have a issue with a missing slash in the API Documentation generated by enunciate 2.3, but i believe the issue exists since 2.2.

I belive it is basically the same problem as in  #316, where when you have an `@ApplicationPath("api")` and resource `@Path("library")` the link in the generated documentation will be something like: 
`<a href="../apilibrary/resource" class="glyphicon glyphicon-new-window" target="_blank">`

It seems to me that the slash is missing in the [docs.fmt] (https://github.com/stoicflame/enunciate/blob/master/docs/src/main/resources/com/webcohesion/enunciate/modules/docs/docs.fmt#L517) between:  `${apiRelativePath}${resourceGroup.relativeContextPath}`

Thanks
Alex

**Comment by stolp** [comment]
I also stumbled upon this today.

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
Fixed at d5ac102.

**Comment by stoicflame** [comment]
Enunciate 2.4.0 has been released.
