### ISSUE TITLE
Ignore @jsonignore

### ISSUE THREAD

**Issue by jphv** [stoicflame/enunciate#349]
Hello,
I want to inform you about the fact that when I write @JsonIgnor on attribut in a class java, it is  included in documentation and I wouldn't like see it.. I see my attribut. 

Friendly.

**Comment by stoicflame** [comment]
Which `@JsonIgnore` annotation are you using? "org.codehaus" or "com.fasterxml"? What happens if you use the other one?

**Comment by stoicflame** [comment]
Bump. Anything to report?

The other issue is that you could have annotated your field when you should be annotating your getter.

**Comment by stoicflame** [comment]
Unable to reproduce, and haven't heard back with more details.
