### ISSUE TITLE
Encoding converter/configuration

### ISSUE THREAD

**Issue by Fival85** [stoicflame/enunciate#350]
Hello again,

we have a problem with enunciate 2.x. Our Source-Code is written in "latin1" and enunciate generates a utf-8 documentation. This will produces some errors with german letters like ö,ä and ü.

We see no possibility that enunciate convert the encoding correctly. We also see no possibility to set the encoding to latin1. 

As a workaround we change the hardcoded encoding settings in the enunciate-source to latin1. This will solve the problem for the moment.

So i will ask: Could you change enunciate, to give the possibility to set the output-encoding to user-setting or (better!) to convert any encoding to UTF-8.

Greetings
Dennis

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
I'm trying to reproduce the issue, but I'm having a hard time seeing the problem. Can you give me an example of some characters that come out corrupted? Also, I'd be interested to know how your pom.xml file looks... do you just have the `project.build.sourceEncoding` property set?

**Comment by Fival85** [comment]
Hello stoicflame,

you could reproduce it if you put the following class into the enuncia-jboss-example:
`package com.webcohesion.enunciate.examples.jboss.genealogy.services.impl;


import java.util.ArrayList;
import java.util.List;

import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;

import com.webcohesion.enunciate.metadata.rs.TypeHint;



/**
* öäöäöäöü?
**/
@Path("/")
public class TestServiceImpl
{

	/**
	* destroyed comment in german letters: äöpüü
	*/
	@GET
	@Path("/test/version")
	public String getVersion()
	{
		return "any version...";
	}
}
`
These class musst be created in enunciate\examples\jboss\src\main\java\com\webcohesion\enunciate\examples\jboss\genealogy\ser
vices\impl and then run mvn clean install.

It is important that the file has the encoding "latin1". If you have problem with this, you could use the attached file.

The pom-property 
` <project.build.sourceEncoding>latin1</project.build.sourceEncoding>`

of the example-project does not have any effect....

[TestServiceImpl.zip](https://github.com/stoicflame/enunciate/files/274338/TestServiceImpl.zip)

![Uploading testServiceImplDoku.JPG…]()

**Comment by stoicflame** [comment]
Thanks.

Fixed at b01ac9b.

**Comment by stoicflame** [comment]
Enunciate 2.4.0 has been released.
