### ISSUE TITLE
Provide example for artifact param in pom.xml

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#353]
If I understood correctly I can configure enunciate e.g. to just create docs and not any other artifacts using artifact param of configuration.

```xml
           <plugin>
                <groupId>com.webcohesion.enunciate</groupId>
                <artifactId>enunciate-maven-plugin</artifactId>
                <version>2.3.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>docs</goal>
                        </goals>
                        <configuration>
                            <!-- the directory where to put the docs -->
                            <docsDir>${basedir}</docsDir>
                            <configFile>${basedir}/enunciate.xml</configFile>
                            <artifacts>docs</artifacts>
                        </configuration>
                    </execution>
                </executions>
            </plugin>  
```
But I have problems to understand, what to put in artifacts param. Simply `<artifacts>docs</artifacts>` doesn't work. 

Configuring `<artifacts><artifact><enunciateArtifactId>docs</enunciateArtifactId></artifact></artifacts>` is accepted as valid configuration, but also PHP, GWT and other libs are created. 

Can you provide an example for this parameter? Maybe it is also helpful to put this example here https://github.com/stoicflame/enunciate/wiki/Artifacts or https://github.com/stoicflame/enunciate/wiki/Executables.

Best regards, Holger

**Comment by hskigithub** [comment]
Okay, I found out how to disable different client libs via enunciate.xml. 

```
<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.3.0.xsd">
	<api-classes>
		<exclude pattern="jira.plugin.projectspecificselectfield.rest.OptionValuesManagerRest"/>
	</api-classes>
	<modules>
		<jackson1 honorJaxb="true" />
		<php-json-client disabled="true" />
		<gwt-json-overlay disabled="true" />
		<java-json-client disabled="true" />
		<ruby-json-client disabled="true" />
	</modules>
</enunciate>
```

I think, it would be helpful to put a hint at https://github.com/stoicflame/enunciate/wiki/Artifacts how to configure different artifacts.

**Comment by stoicflame** [comment]
I updated the [Modules](https://github.com/stoicflame/enunciate/wiki/Modules) page with more explicit instructions on how to disable modules.
