### ISSUE TITLE
Documentation for enunciate.xml config file incl. XML schema reference

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#354]
It would be great to have a wiki page with a sample of an enunciate config file. Most important in that example is the reference to the XML schema, so that you know what parameters are possible.

**Comment by stoicflame** [comment]
There's one provided in the [getting started guide/sample app](https://github.com/stoicflame/enunciate-sample/blob/step5/enunciate.xml).

There are also [a bunch in the examples](https://github.com/stoicflame/enunciate/search?utf8=%E2%9C%93&q=in%3Apath+enunciate.xml).
