### ISSUE TITLE
Use relative paths to rest api

### ISSUE THREAD

**Issue by geraldglennon** [stoicflame/enunciate#355]
Hey,
So i've just been updating from older version to 2.3.0 as we have moved to java 8. Again I found the issue reported previously i.e. missing the "/". so I'm current using 2.1.0 until this is fixed. 

My problem is that the url does no use relative paths i.e. 
<a href="../server/api/projects" class="glyphicon glyphicon-new-window" target="_blank"></a>

the uri the docs are located are  _<hostname>/tm/docs_
with the generated urls it would bring you to _<hostname>/tm/server/api/projects_
But it should bring you to _<hostname>/server/api/projects_

This is because the uri generated only brings you up one level  i.e. "../**then the uri** and not use the relative path specified in enunciate.xml. 

```
<modules>
        <docs docsDir="docs"/>
        <jaxrs>
            <application path="/server/api/"/>
        </jaxrs>
   </modules>
```

Is there a way to do this or is this a bug?

**Comment by stoicflame** [comment]
What process puts the docs in "/tm"?

Have you tried using the `docsSubdir` attribute?

```xml
<enunciate>
  <modules>
    <docs docsDir="tm" docsSubdir="docs"/>
```

**Comment by geraldglennon** [comment]
Apologies its something unusual done to our test environment. Our test environment has 2 different versions of the UI deployed. Something that was implemented along time ago but forgotten about. I'll need fix that one myself. 

I deployed to our stage environment a moment ago and its working fine. Apologies.

Also I noticed that swagger is not adding the application path. Is there some extra config for that or should it follow application path that has been configured

**Comment by stoicflame** [comment]
Swagger should be using application root. You can provide custom Swagger base path, e.g.:

```xml
<modules>
  <swagger basePath="/server/api/"
```

**Comment by geraldglennon** [comment]
cool thanks

**Comment by stoicflame** [comment]
Enunciate 2.4.0 has been released.
