### ISSUE TITLE
What is the corresponding XML element for defaultrestsubcontext in enunciate2

### ISSUE THREAD

**Issue by murugaraja** [stoicflame/enunciate#356]
Hello,

We have "defaultrestsubcontext" tag to mention the "subcontext" in enunciate1.*.xml but I cant see the same in enunciate2.*.xml file. So, Is there a way to specify "subcontext" in enunciate2.*.xml file.

**sample in enunciate1.28.xml file**

```xml
<services>
  <rest defaultRestSubcontext="/v2" />
</services> 
```
expecting the same in enunciate2.2.0.xml file

Thanks in advance,
Raja.M

**Comment by stoicflame** [comment]
Since Enunciate 2 has moved away from packaging the web application, there is no more "rest subcontext".

There _are_ ways to apply an "application path", either by using the `@ApplicationPath` annotation or by explicitly specifying it in the config:

```xml
<enunciate>
  <modules>
    <jaxrs>
      <application path="/v2"/>
```

**Comment by murugaraja** [comment]
Thanks Stoicflame,

continue with this, I used the same in my project but it is **removing final slash** and calling the API.

<enunciate>
  <modules>
    <jaxrs>
      <application path="/v2/"/>

Displaying : http://site/project**/v2/**mypath
Expected : http://site/project**/v2**mypath

Thanks in advance.
Raja.M

**Comment by stoicflame** [comment]
Enunciate 2.4.0 has been released.
