### ISSUE TITLE
Does Enunciate support collectionFormat for array types?

### ISSUE THREAD

**Issue by egemenvardar** [stoicflame/enunciate#357]
A follow-up issue of #331.

Since version 2.3.0 Enunciate can generate array type for multi-valued query parameters. It looks like this on the Swagger UI:

![image](https://cloud.githubusercontent.com/assets/17125072/14170374/b6dcadd0-f72d-11e5-8dd4-e763150d1fd4.png)

This is correct, however providing values in new lines does not work. In my case, the query parameter is constructed as follows:
`group_ids=EPLangID%2CAddrTypeID`

I checked the generated `swagger.json` and found out that `"collectionFormat": "multi"` is missing for this parameter. If I add it manually the query parameter is constructed correctly.

Is this a bug or do I need to somehow tell Enunciate that the collectionFormat is multi for this parameter?

**Comment by stoicflame** [comment]
Thanks for the report. We'll address it for 2.4.

**Comment by stoicflame** [comment]
Fixed at 0f6d935.

**Comment by stoicflame** [comment]
Enunciate 2.4.0 has been released.
