### ISSUE TITLE
@XmlElementRef(required=true) not reflected to generated xsd

### ISSUE THREAD

**Issue by samion** [stoicflame/enunciate#361]
Why required=true setting is not reflected to generated xsd for XmlElementRef-annotated fields? This behaviour comes from the following code:

https://github.com/stoicflame/enunciate/blob/master/jaxb/src/main/java/com/webcohesion/enunciate/modules/jaxb/model/ElementRef.java

`
  @Override
  public boolean isRequired() {
    return false;
  }
`

**Comment by stoicflame** [comment]
It's used in calculating the `minOccurs`, e.g.:

```xml
  <xs:element minOccurs="1" ...>
```

**Comment by samion** [comment]
But why required=true generates xsd with minOccurs="0"?

**Comment by stoicflame** [comment]
Oh, I see.

Yes, that's probably a bug. I'll fix it for 2.4.

**Comment by stoicflame** [comment]
Fixed at 017cf28.

**Comment by stoicflame** [comment]
Doh. Had to revert at 08a8e79.

The reason `@XmlElement.required()` isn't getting used is because it's not available in Java 1.6, and Enunciate isn't ready (yet) to drop support for 1.6.

When Enunciate decides to drop support for 1.6, we can re-apply 017cf28.

**Comment by samion** [comment]
I suppose it means that this bug should not be closed then?

**Comment by stoicflame** [comment]
Sure.
