### ISSUE TITLE
Enunciate generated swagger specification file has errors

### ISSUE THREAD

**Issue by murugaraja** [stoicflame/enunciate#362]
Hello,

I am using Enunciate 2.2.0 to generate document, After uploading enunciate generated swagger.json in http://editor.swagger.io/, I am getting **Not a valid parameter definition** in swagger editor, I can see multiple error in swagger.json file in swagger editor. 

When try to download client library for any language I am getting **Unable to build target: Could not process model 'xml_ns0_category'** error.

Could you please let me know I am using it in a correct flow or not.

Thanks,
Raja.M

**Comment by stoicflame** [comment]
Thanks for the report.

I'm going to need the swagger.json file in order to debug it.

**Comment by murugaraja** [comment]
Hi Stoicflame,

Please find the attached sample swagger.json file. 
[swagger.zip](https://github.com/stoicflame/enunciate/files/209712/swagger.zip)

I uploaded the above swagger json in http://editor.swagger.io/ and fixed below three errors and it is processed with no error (with warnings).

1. Replaced a String instead of "{petId}" in line# 278.
2. Removed duplicate line # 286 **application/json**.
3. Changed the in value from **path** to **Query** in line# 301

After the above error fix all the errors are cleared, then when i tried to download the client library I got the below error.
![swagger error](https://cloud.githubusercontent.com/assets/5021444/14375995/6e1d242e-fd83-11e5-8c3f-1185c96bc7f2.png)

Thanks in advance,
Raja.M

**Comment by stoicflame** [comment]
The swagger validation errors are fixed at af17851.

Unfortunately, I have no way to explain the code generating errors, so I opened up [swagger-editor/#942](https://github.com/swagger-api/swagger-editor/issues/942) for those guys to take a look.

**Comment by stoicflame** [comment]
At swagger-api/swagger-codegen#2918, they explain that the codegen feature doesn't support the `allOf` construct. So you can configure Enunciate to "inline" the JSON data types to avoid using the `allOf` if you need. See #375 .
