### ISSUE TITLE
A way to provide a 'custom' response body

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#363]
I'm trying out enunciate for the first time, and it works great. Really easy to get started with!

Documentation is generated automatically, and (almost) everything works great. The only catch is that I can't use enunciate to automatically generate the "Request Body" and "Response Body" sections. Is there a way which somehow lets me define this section manually, and which enunciate would pull in when generating the documentation?

The reason why I can't use enunciate is that I'm not strictly working with entities which is marshalled/unmarshalled using e.g. JAXB. Instead, I feed entities into an XML builder (separate project) which then returns the XML to be responded with. The produced XML is consistent, but there is no way for me to have enunciate discover the structure automatically.

**Comment by stoicflame** [comment]
https://github.com/stoicflame/enunciate/wiki/Custom-Output-Type

https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations
