### ISSUE TITLE
Title from enunciate.xml not used for webpage Jumbotron headline

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#364]
If I add a <title> in the enunciate.xml this title is not used used in the webpage Jumbotron headline. Actually this problem appears, if you set a <description>. If the description is set in enunciate.xml, then no title appears in Jumbotron box.

**Comment by hskigithub** [comment]
![bildschirmfoto 2016-04-09 um 12 36 28](https://cloud.githubusercontent.com/assets/1921015/14403235/0f3d4178-fe50-11e5-81dc-ac75406a3834.png)

**Comment by stoicflame** [comment]
The description overrides the title. You can put HTML in the description, e.g.:

```xml
<description>&lt;h1>Version Manager for JIRA&lt;h1/>&lt;p>Manage versions without need for administer project permission&lt;/p></description>
```

**Comment by hskigithub** [comment]
Okay, have done a similar work around using CDATA in <description>.
