### ISSUE TITLE
Use label for GET, PUT, POST and Status codes 200, 404 etc.

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#365]
To improve layout of docs you could use Bootstrap labels http://getbootstrap.com/components/#labels for HTTP method and HTTP status codes. See attached screenshot for an example.
![bildschirmfoto 2016-04-09 um 23 25 38](https://cloud.githubusercontent.com/assets/1921015/14406560/9846e27a-feab-11e5-94dc-f1d66b556624.png)

**Comment by stoicflame** [comment]
I like that. I'll add it to 2.4.

**Comment by hskigithub** [comment]
:-)

**Comment by stoicflame** [comment]
Fixed at df27760.

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
