### ISSUE TITLE
Option to use Boostrap page-header instead of jumbotron

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#366]
I would like to have the option to use Bootstrap page-header http://getbootstrap.com/components/#page-header instead of jumbotron http://getbootstrap.com/components/#jumbotron. I think this is more suitable for technical documentation. See attached screenshot for a possble layout.

![bildschirmfoto 2016-04-10 um 08 19 07](https://cloud.githubusercontent.com/assets/1921015/14408763/695fa7de-ff01-11e5-9a16-e3d7fbc61544.png)

Currently it looks like this, which looks bulky.

![bildschirmfoto 2016-04-10 um 09 48 54](https://cloud.githubusercontent.com/assets/1921015/14408768/9426f454-ff01-11e5-857f-ebde5589ef70.png)

**Comment by stoicflame** [comment]
I changed to page-header at e22ce20; it's a better look.

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
