### ISSUE TITLE
Is there a way to indicate (in the resulting documentation) that the availability of a property depends on a security context?

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#368]
The resulting REST documentation produced by enunciate is great. However, the project I'm working on filters out some properties from entities in the data model depending on a security context. To examplify this, have a look at the picture below. The attributes "created" and "distribute" may not be returned if the client is not authorized to view these properties.

For my use case, this could simply be a matter of getting a custom CSS class onto these properties in the documentation which I could then use to style those properties with e.g. a lock symbol (or something else). 

![image](https://cloud.githubusercontent.com/assets/1845372/14455150/52e32b18-009e-11e6-9fb6-7d3f46a11a59.png)

Is this doable right now, or would this require new functionality?

**Comment by stoicflame** [comment]
Enunciate doesn't have any way of identifying those properties today. Can you suggest a mechanism for doing so? Are you thinking about some kind of custom annotation?

**Comment by sbrattla** [comment]
A custom annotation which would let me add one or more "labels" to a property would be great. Those labels could then be added as CSS classes (filtering out non-valid characters as described in http://stackoverflow.com/questions/448981/which-characters-are-valid-in-css-class-names-selectors).

**Comment by NonesuchRiver** [comment]
Consider the annotations supported by Apache Shiro for this.

**Comment by stoicflame** [comment]
Done at e7923e2.

As of 2.4, you can provide annotations to customize styles for a property:

```java
@com.webcohesion.enunciate.metadata.Style("secured")
public Date created
```

That will apply the "secured" CSS style to its name in the documentation:

```html
<tr>
  <td><span class="property-name secured">created</span></td>
  ...
</tr>
```

Or you can provide multiple styles:

```java
@com.webcohesion.enunciate.metadata.Styles(
  @com.webcohesion.enunciate.metadata.Style("secured"),
  @com.webcohesion.enunciate.metadata.Style("conditional")
)
public Date created
```

Or you can use JavaDoc:

```java
/**
 * @style secured
 * @style conditional
 */
public Date created
```

Or you can provide your own annotations:

```java
@Style("secured")
public @interface Secured {
}
```

Or you can configure custom annotations, like Apache Shiro:

```xml
<enunciate>
  <styles>
    <annotation name="org.apache.shiro.authz.annotation.RequiresAuthentication" style="secured"/>
```

See [Providing Custom Styles](https://github.com/stoicflame/enunciate/wiki/Custom-Skin#providing-custom-styles).

**Comment by sbrattla** [comment]
Nice! This is really useful, thanks for taking the time to implement this! This makes it possible to indicate to end users that some properties listed in the documentation may be available due to security restrictions.

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
