### ISSUE TITLE
Incorrect encoding of JavaDoc in WSDL and XSD files

### ISSUE THREAD

**Issue by Matthias-Ni** [stoicflame/enunciate#369]
Hello again, 

sorry that it took me so long. I've created a sample Project to show the problem. 
There are some special characters like Ä Ö Ü in the Javadoc. 

Build it with 
`mvn clean install`

The generated wsdl and xsd Files have illegal characters, the html files are correct. 

Oh and thank you again for fixing  #323! The issue is gone after updating to the latest enunciate
version.

[EncodingTest.zip](https://github.com/stoicflame/enunciate/files/214673/EncodingTest.zip)

**Comment by stoicflame** [comment]
So [here's the wsdl](https://github.com/stoicflame/enunciate/files/273581/ns0.wsdl.txt) that was generated, and [here's the schema](https://github.com/stoicflame/enunciate/files/273582/ns0.xsd.txt).

Am I missing something? It seems correct to me...

**Comment by stoicflame** [comment]
I think you might have run into the issue reported at #350, which was fixed at b01ac9b.

I can re-open as needed.

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
