### ISSUE TITLE
Custom (ServletHolder) context path (application path) not reflected in GUI

### ISSUE THREAD

**Issue by vegaasen** [stoicflame/enunciate#370]
Hia,

Configuring Enunciate when using Jersey/Jetty embedded works just as intended and expected, however, the URLs being listed within the documentation is relative to whatever is defined in the annotation "@Path". As this is ok for most cases, it leaves out a small important bit. If you define a context-root on the servletHolder-level for e.g Jersey, that context-root is being left out causing the documentation to be (seemingly) incorrect. Example:

`
applicationContext.addServlet(ServletContainer.class, "/whatever/*");
`

I know you can add 

`<application root="/whatever"/> `

to the configuration (within xml or code), however, this is not reflected in the actual page - which again causes confusion among the users :-).

A possible fix is just to include that Enunciate-config thing "application/@root"-param in the API documentation?

Example related to "@Path":

`@Path("/v1/user")
public class UserHandlerController {
}`

Whilst the context-root starts with "/whatever", turning all resources in to this URL: "/whatever/v1/user/foo/bar", however the GUI generated is showing "/v1/user" :-)

This might be a bit crappy explained - currently on the move.

Regards,
Vegard

**Comment by stoicflame** [comment]
At 76f6286 support was added to be able to configure the docs module to include the application path:

```xml
<enunciate>
  <modules>
    <docs includeApplicationPath="true"/>
```

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).

**Comment by bbarman4u** [comment]
Hi Stoicfame,
I recently started using the  Enunciate(latest version 2.5) and I must say I like it.  How ever I have similar question like this gentleman in the above thread. Example -
My Web Application Context Path is say "/webapp"
My Servlet path is say "rest"
My API base path annotated with @path is say "/path1"
My actual resource api path annotated with @path is say "/api1"
So my effective path of the rest api that gets excecuted and should reflect in documentation is -
"/webapp/rest/path1/api1"

Whereas when running the build(am using ant) with the configuration -
 <docs includeApplicationPath="true"/>
The generated docs end up like this  -
"//path1/api1" whereas if I remove the above config it just becomes "/path1/api1". The generated swagger definitions does not even have effect of the above includeApplicationPath configuration.
Note - I have a jersey and spring web application.

Would it be possible to define custom path in the enunciate.xml to at least append the base path like in my above example to what ever we define (if its difficult to derive from various configurations). This was the application document will be fully functional. without having to hand edit the generated docs to update the path every time.

Cheera and Thanks in Advance.
