### ISSUE TITLE
Maven docs should replace / update existing files in docsDir

### ISSUE THREAD

**Issue by hskigithub** [stoicflame/enunciate#371]
When calling the docs goal in maven, enunciate is not updating the content in the docsDir. I manually need to remove the folder and then next maven docs call it gets created. 

Is there a way to configure enunciate or maven to update existing content in docsDir resp. remove all  files and create them new?

**Comment by stoicflame** [comment]
There's no way to do that today, no. Is it hard to have your build system do it?

**Comment by hskigithub** [comment]
Sure, maven should be able to do that. Just I have no clue, how to configure maven pom.xml for that. Any idea?

**Comment by hskigithub** [comment]
Maybe like this https://maven.apache.org/plugins/maven-clean-plugin/examples/delete_additional_files.html.

**Comment by hskigithub** [comment]
I have done some more testing. If I change something in enunciate.xml e.g. `title`, then the `docsDir` content gets updated. That's as expected.

If I change something in the `docs.fmt`, I get `[INFO] [ENUNCIATE] Skipping documentation source generation as everything appears up-to-date...`. Okay, maybe. 

If I change JavaDoc in a Java REST class e.g. method description or `@param` I also get  `[INFO] [ENUNCIATE] Skipping documentation source generation as everything appears up-to-date...`. This is not, what I would expect. 

Maybe this is a bug?

**Comment by stoicflame** [comment]
Yep. Fixed at b96bd38.

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
