### ISSUE TITLE
Should @TypeHint work with interfaces?

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#373]
I'm trying to throw an interface at `@TypeHint`, but the resulting documentation just says `object(JSON) `and `anyType(XML)` when I do that. If I replace the interface with an implementation, the resulting documentation is correctly produced.

Should I be able to use an interface with `@TypeHint`?

**Comment by stoicflame** [comment]
So since both Jackson and JAXB don't consider interfaces (they only look at the runtime class), Enunciate has no way of knowing which _class_ will be used and therefore has to punt and just use object. So this is currently working as designed.
