### ISSUE TITLE
Missing descriptions for POJOs that don't have JSON or JAXB annotations

### ISSUE THREAD

**Issue by raner** [stoicflame/enunciate#385]
We are using MOXy for serialization, so none of our POJOs have any sort of annotations on them (and we'd like to keep it that way).
I'm trying to create an enunciate documentation of our REST API, but the description of the request and response bodies only says "(custom)", without further elaborating on the type's structure.
In the POM, I added <include> elements for the packages that contain the POJOs, but that doesn't seem to help.
Is there a way to configure enunciate to include full documentation of POJOs that don't have any annotations?

**Comment by stoicflame** [comment]
If there are no annotations, how does MOXy determine the name of the root element returned from your API? The JAXB spec requires an @XmlRootElement annotation...

**Comment by raner** [comment]
We're using JSON format...
For example, a class Person { String firstName, lastName; } is simply serialized as
`{"firstName":"Mirko", "lastName":"Raner"}`
There is no need store any type-information at the top level of the JSON object, since the parameter type and return type in the JAX-RS interface specify the type.

So, I interpret the enhancement tag to mean that there is no existing support for this. Thanks for considering this feature

**Comment by stoicflame** [comment]
Well, if you just want JSON documentation then Enunciate can handle those data types. You probably just have to make sure you've specified your JAX-RS methods as `@Produces` application/json. 

If you're wanting XML, then Enunciate won't know how those data types get serialized into XML without the `@XmlRootElement` annotation on them, so it will probably just say "custom".

**Comment by stoicflame** [comment]
Bump. Any update on this?

I believe your documentation should show up if you're specifying that your methods produce "application/json" or "application/something+json". Can you confirm?

**Comment by stoicflame** [comment]
Since I haven't heard back, I'm going to go ahead and close this assuming it's working as designed (described above). I'd be happy to re-open as needed.

**Comment by raner** [comment]
Sorry, completely dropped the ball on this...

Unfortunately, I cannot confirm that Enunciate works as expected for me in this case. But I think I can offer some additional clue: if I add Jackson's `@JsonSerialize` annotation to our domain classes, then the generated documentation does include the expected JSON documentation about the object structure. However, without `@JsonSerialize` it will just say "custom".

The problem is: we don't want to add `@JsonSerialize` annotations just for the purpose of generating proper documentation. In general, we don't want to annotate our domain classes in any way that ties them to a specific serialization format. Our current JSON serialization does not even use Jackson (it uses MOXy), so it makes little sense to add a dependency on Jackson to our project.

I'm probably missing something essential here (still very new to Enunciate)... is there a way to produce JSON documentation for domain classes that have no serialization annotations whatsoever?

**Comment by stoicflame** [comment]
You probably just need to "include" the classes:

https://github.com/stoicflame/enunciate/wiki/Excluding-Including-Classes#configuration

**Comment by esafzay** [comment]
Is this feature still not available in the new versions?

**Comment by stoicflame** [comment]
I'd be happy to revisit the issue if we can isolate the problem. As I understand it, the problem is that the request and response bodies just say "custom" when they should link to the JSON data types. But I can't reproduce the circumstances and therefore can't see the issue. I never did get confirmation that the request method produces `application/json` or `application/*+json`.

If I can get some additional context and ideally a way to reproduce the issue, I'm confident we can reach the solution.
