### ISSUE TITLE
abstract class modifier present in client json jar

### ISSUE THREAD

**Issue by dschraitle** [stoicflame/enunciate#386]
Our project uses abstract classes in @TypeHint annotations to provide documentation of the return types for some functions which normally return an Interface. When the client java-json-client jar is created, the abstract modifier persists in the generated class, even though the rest of the class is completely implemented with getters and setters. Is this expected behavior?

**Comment by stoicflame** [comment]
Probably a bug.

Can you provide an example for me?

**Comment by dschraitle** [comment]
Usage: 
```java
@TypeHint(value=AbstractInterfaceDocs.class)
public IMyInterface getSomething() {
    return new SomeImplementationClass;
}
```
original class:
```java
@XmlRootElement
public abstract class AbstractInterfaceDocs implements IMyInterface {
  /**
   * Gets Information about stuff
   */
  @Override
  @XmlElement
  public abstract String getInformation();
}
```
generated class with abstract modifier:
```java
@JsonInclude( JsonInclude.Include.NON_NULL )
@JsonIgnoreProperties( ignoreUnknown = true )
public abstract class AbstractInterfaceDocs implements java.io.Serializable {

  @JsonIgnore
  private java.lang.String _information;

  /**
   * Gets Information about stuff
   */
  @JsonProperty( value = "information", required = false )
  public java.lang.String getInformation() {
    return this._information;
  }

  /**
   * Gets Information about stuff
   */
  @JsonProperty( value = "information", required = false )
  public void setInformation(java.lang.String _information) {
    this._information = _information;
  }
}
```

**Comment by stoicflame** [comment]
I couldn't think of a reason why the client classes would need to preserve the `abstract` modifier, so I just removed it at 3523ce8.

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
