### ISSUE TITLE
Application path configuration doesn't taken into account.

### ISSUE THREAD

**Issue by TheMalloum** [stoicflame/enunciate#387]
Hi,

My config file enunciate.xml specify a application path, but it's doesn't taken into account.

my pom.xml
```xml
<build>
		<plugins>
		.....
			<plugin>
				<groupId>com.webcohesion.enunciate</groupId>
				<artifactId>enunciate-maven-plugin</artifactId>
				<version>2.3.0</version>
				<configuration>
					<configFile>enunciate.xml</configFile>
			              <docsDir>${project.build.directory}/${project.build.finalName}/apidocs/</docsDir>
				</configuration>
				<executions>
					<execution>
						<goals>
							<goal>assemble</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>
....
```

and the enunciate.xml

```xml
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.3.0.xsd">
	
	<description>
    	<![CDATA[
     	  My docs api
  		  ]]>
	</description>

	<modules>
		<jaxrs>
			<application path="./api" />
		</jaxrs>
	</modules>
</enunciate>
```

**Comment by stoicflame** [comment]
It seems to be working for me. Can you provide a patch to the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) that exposes the issue?

Note that the application path doesn't show up in the documentation; it's accounted for in the links to each resource.

**Comment by stoicflame** [comment]
Since I haven't heard back, I'm going to assume this is just a matter of the application path not showing up in the docs (duplicate of #370).

At 76f6286 support was added to be able to configure the docs module to include the application path:

```xml
<enunciate>
  <modules>
    <docs includeApplicationPath="true"/>
```

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
