### ISSUE TITLE
Wrong Path label for soap service

### ISSUE THREAD

**Issue by jigarparekh80** [stoicflame/enunciate#389]
Path /AuthenticationServiceService

is getting generated for service named "AuthenticationService"

**Comment by stoicflame** [comment]
Yes, that's Enunciate's best guess as to where the service is going to be located. It's based on the JAX-WS RI defaults. You have to use the `@WebService(serviceName="path")` annotation to customize it.

**Comment by jigarparekh80** [comment]
i have already marked serviceName = "AuthenticationService" in Impl class. still it shows wrong.

**Comment by stoicflame** [comment]
I'll take a closer look, then.

**Comment by stoicflame** [comment]
My bad.

Path can be configured by providing a `sun-jaxws.xml` file:

```xml
<enunciate>
  <modules>
    <jaxws sun-jaxws-xml-file="/path/to/sun-jaxws.xml"/>
```

By default, Enunciate will look in your `WEB-INF` directory for a file named `sun-jaxws.xml` and use it if it finds it. This case has been confirmed with the [full-api-edge-cases example](https://github.com/stoicflame/enunciate/tree/master/examples/full-api-edge-cases).
