### ISSUE TITLE
soap document does not show max occurs

### ISSUE THREAD

**Issue by jigarparekh80** [stoicflame/enunciate#390]
in soap document if service has return time List or Set then my wsdl shows correct sequence but in documentation it shows 0/1 instead of 0/unbounded.

**Comment by stoicflame** [comment]
Fixed at b828c1a.

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
