### ISSUE TITLE
add an option to ignore abstract superclasses

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#392]
Hi.

I'm using abstract superclasses for my DTOs (like for `id`). Currently these classes are also added to the json documentation. It would be nice, if these could be "hidden" from the documentation and simply added to the subclass documentation.

A first step was already taken here in that direction:

https://github.com/stoicflame/enunciate/issues/215

But using `@XmlTransient/@JsonIgnore` would ignore the whole superclass - including the id definition right?
Besides that, `@JsonIgnore` is only available on field level - AFAIK.

Thanks!

**Comment by stoicflame** [comment]
Fixed at 4129bd7649c0a2de1e8085b593f52590354a8591. See #375.

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).
