### ISSUE TITLE
Missing javadoc on @QueryParam nested in @BeanParam

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#393]
As already stated in https://github.com/stoicflame/enunciate/issues/225, I'm seeing the exact behavior with 2.3.0 :(.

No documentation shows up.

My interface method:
```java
	@GET
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	@Override
	PagedResultDto<CategoryDto> list(@BeanParam QueryParams queryParams);
```

My QueryParams:
```java

public class QueryParams {
	/**
	 * Queryfield.
	 */
	@QueryParam("q")
	private String query;

	/**
	 * Querymethod.
	 */
	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

...

}
```

Any idea what might causing this?

![screen shot 2016-05-18 at 15 11 20](https://cloud.githubusercontent.com/assets/3257311/15359785/3c770bf4-1d0b-11e6-8766-46bfd790558a.png)

**Comment by vguna** [comment]
Ok, I found the problem - and it was selfmade :(.

I have the rest interfaces in a different package than the models.
In `enunciate.xml` I had something like this:

```xml
	<api-classes>
		<include pattern="com.acme.rest.api.*" />
	</api-classes>
```
I thought, that it will pickup subpackages automatically. But I doesn't. It also doesn't complain about missing classes/sources during enunciate build, so I thought everything is ok.

The solution was to add the subpackage explicitly as well:

```xml
	<api-classes>
		<include pattern="com.acme.rest.api.*" />
		<include pattern="com.acme.rest.api.model.*" />
	</api-classes>
```

After that the documentation worked as advertised :).
Sorry for any inconvenience!

@stoicflame: does it make sense to add a check for missing classes to the maven plugin? So one is aware of possible (resulting) missing documentation? I think I already stumbled across this in the past....

**Comment by stoicflame** [comment]
FYI, the "pattern" is ant-style, so you'd achieve the same results with:

```xml
    <api-classes>
        <include pattern="com.acme.rest.api.**" />
    </api-classes>
```

Re: check for missing classes: so you're suggesting that it might be helpful for the plugin to warn you about classes for which it doesn't find source code?

**Comment by vguna** [comment]
Exactly. So it might reduce the number of issues about missing documentation here - at least for me ;).
Didn't know about the ant style. Thanks!

**Comment by stoicflame** [comment]
I'm still thinking through the implications of warning developers that the source code isn't found for a class. I'm worried about the developers who have a very large project that use a lot of classes... those warnings could be really noisy, and I'm reluctant to be that verbose.

We could do a debug-level warning or make the warning configurable, but then folks would have to know how to find the message, which kind of defeats the purpose...

Thoughts?

**Comment by vguna** [comment]
Hm. But isn't enunciate all about documentation (now) :)? So if classes aren't found, that are referenced explicitly or implicitly by the endpoints, why I would ignore that fact, that documentation is missing? I would look at the documentation and wonder why some documentation is missing.

So IMHO the default could be, that warnings are printed. But can be disabled by configuration?

Is there are a usecase, that enunciate would (theoretically) print a warning for a class, that _isn't_ part of the endpoint definition documentation? If that's the case, I can understand your concerns :).
Then one would have to start to define for what classes/packages warnings are ok, and for what they should be ignored... that isn't fun either, I guess?

**Comment by stoicflame** [comment]
Fixed at 7391d4c. I log a one-time warning message if _any_ classes without source files are found. The warning extends an invitation to turn on debug-level logging to see which specific source files weren't found. It also provides a link to the new [Discovering Source Files](https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files) page that provides details.

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).

**Comment by darmbrust** [comment]
How does one actually enable this feature?  Aka, enable debug-logging?  I'm using maven, and have tried -X, but that didn't seem to do it.  
The ant section over here, has a parameter: https://github.com/stoicflame/enunciate/wiki/Executables but I don't see anything similar in maven.  I'm probably missing something obvious...

**Comment by stoicflame** [comment]
You're right; it's `mvn -X`.

Are you saying you're not seeing all the noise? If you grep through the output, you should be seeing messages like "Unable to find source file for ...".

**Comment by darmbrust** [comment]
I get this [WARNING]
[WARNING] [ENUNCIATE] Some source files were not found for the Java classes that define the Web service API.
[WARNING] [ENUNCIATE] Enunciate will be unable to find the documentation for the classes that are missing source files. (For details, rebuild with debug-level logging.)
[WARNING] [ENUNCIATE] In order for Enunciate to find the source files for API classes that are not being compiled in the current project, the source file must be on the Enunciate sourcepath and the class must be explicitly included in the Enunciate configuration.
[WARNING] [ENUNCIATE] For more information, see https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files

but even with -X, I'm not seeing anything jump out at me that is wrong.  At least, not until you gave me that snippit to search on.  Now I'm finding some:
[DEBUG] [ENUNCIATE] Unable to find source file for java.time.Instant
I guess I assumed they would be WARNINGs or something, so I could find them.  -X mode is quite noisy with maven....
