### ISSUE TITLE
Add result entity class to @ResponseCode annotation

### ISSUE THREAD

**Issue by Thorndike** [stoicflame/enunciate#394]
We use Jersey for our REST api. In case of a failure a WebApplicationException is thrown. In that exception an entity is included which Jersey uses as a response entity for the REST call. It would be nice to be able to document that entity with enunciate per response code. I imagine somthing like extending
@ResponseCode(code = 500, condition = "Server Error")
to 
@ResponseCode(code = 500, condition = "Server Error", ErrorInfoEntity.class)

where enunciate can use that class to generate the JSON object definition for that respons entity like a ResponseCode specific @TypeHint.

**Comment by javacook** [comment]
Yes, I would enjoy this extension :-)

**Comment by stoicflame** [comment]
Fixed at 0bbc783.

```java
@ResponseCode (
  code=500,
  condition="Server Error",
  type=@TypeHint(ErrorInfoEntity.class)
)
```

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).

**Comment by Thorndike** [comment]
Works like a charm, thank you!

**Comment by ChThelen** [comment]
Great feature, thanks!
