### ISSUE TITLE
@NotNull not supported on fields

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#395]
Hi.

I'm using `@NotNull` to mark attributes as required. I tend to put these on the fields of a class. It seems that enunciate doesn't pick these up - unless they are specified on the getter. Could that be enhanced?

Another thing regarding this:

I've created my own annotation `@NotBlank`, that "inherits" `@NotNull` but also checks for empty strings using trim(). Would it make sense that enunciate also checks for any annotations on fields that "inherit" from `@NotNull`?

**Comment by stoicflame** [comment]
What do you mean when you say `@NotBlank` "inherits" `@NotNull`?

**Comment by vguna** [comment]
If you take a look at hibernate's `@NotBlank`, it defines behavior, that inherits from `@NotNull`. That means, if the field is only decorated with `@NotBlank`, it automatically checks for not null AND additionally if the string is empty.

For the client side documentation it would be nice, if it would be set to required if an annotation already "inherits" `@NotNull`. Otherwise one would always have to add the two annotations separately for each field.

But since this is a custom annotation anyway, maybe it's good enough to handle that with the freemarker templates and check explicitly for `@NotBlank` on my own?


```java
@Documented
@Constraint(validatedBy = { })
@Target({ METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER })
@Retention(RUNTIME)
@ReportAsSingleViolation
@NotNull
public @interface NotBlank {
	String message() default "{org.hibernate.validator.constraints.NotBlank.message}";

	Class<?>[] groups() default { };

	Class<? extends Payload>[] payload() default { };

	/**
	 * Defines several {@code @NotBlank} annotations on the same element.
	 */
	@Target({ METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER })
	@Retention(RUNTIME)
	@Documented
	public @interface List {
		NotBlank[] value();
	}
}
```

**Comment by stoicflame** [comment]
Fixed at defdba0.

Added support for detecting "inherited" `@NotNull` annotations (i.e. annotations that are themselves annotated with `@NotNull`).

**Comment by stoicflame** [comment]
[Enunciate 2.4 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.4.0).

**Comment by vgcookies** [comment]
Works, thanks! But this doesn't contain support for annotations on fields, as it seems, right :)?

**Comment by stoicflame** [comment]
The problem is that you're expecting Enunciate to use annotations that are on the fields for the properties (getters/setters).

If the _fields_ were getting used as accessors instead of the properties, Enunciate would pick up the `@NotNull` annotations. So you can either annotate the properties, or use `@JsonAutoDetect` to specify that the fields should be used for (de)serialization instead of the properties.

**Comment by vgcookies** [comment]
That means, that Enunciate is using jackson for reading annotations? Or does Enunciate evaluates the `@JsonAutodetect` itself and acts accordingly?

**Comment by stoicflame** [comment]
Enunciate evaluates the annotation itself.

**Comment by vgcookies** [comment]
Now I'm confused ;). Enunciate has its own mechanism for finding/reading annotations. Ok. And Enunciate evaluates `@JsonAutodetect` to decide where to expect the annotations - either on fields or properties - as specified by that annotation?

**Comment by stoicflame** [comment]
Correct.
