### ISSUE TITLE
@Label/@JsonRootElement not honored in swagger output

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#399]
Hi.

I'm using enunciate 2.3.0 and encountered some naming inconsistencies in the swagger output.
I annotated all my DTOs with `@JsonRootElement`. The "translation" seems to work for the enunciate own documentation without a problem. Also the swagger output looks ok for the root models.

But if a DTO references another DTO, e.g. in a collection or via inheritance, the original classname is used and not the translation. I also doublechecked with `@Label`.

See picture attached.
![screen shot 2016-05-19 at 12 24 48](https://cloud.githubusercontent.com/assets/3257311/15391018/46dd66c4-1dbf-11e6-8a4e-c2ec617a10ea.png)

**Comment by stoicflame** [comment]
The labels aren't designed to be unique, nor are they "scoped" to a specific serialization mechanism (JSON, XML). So Enunciate has to generate its own unique ids for the swagger docs to avoid conflicts and broken references.

Shouldn't Swagger use the "title" for the data type references? If so, it would address your issue. I'm thinking this is a Swagger issue...

**Comment by vguna** [comment]
Hm, to be honest, I haven't looked into the swagger json in detail yet. Just wondered why the output doesn't seem to respect the `@Label/@JsonRootElement` :). Let me have a look and I'll report back...

**Comment by stoicflame** [comment]
See swagger-api/swagger-ui#2029. It _used_ to be the label, then they changed it to be the unique id.

I'm going to close this issue; it belongs over in the swagger-ui project.
