### ISSUE TITLE
Handling generics in return types

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#400]
Hi.

I've got collection endpoints of a REST service that all return PagedResultDto<T> which contains paging information and the actual typed List<T>. Is it somehow possible to not just add the type PagedResultDto as return type, but also the generic type T to it? To be honest, I wonder how that could look like in the documentation :).

``` java
PagedResultDto<PetDto> query();
```

That would probably mean, that the PagedResultDto documentation must be generated multiple times - one for each generic type? So that the type documentation for PagedResultDto simply contains a link to the actual type documentation? Just thinking loud here ;).

Of course I could simply add a concrete PetPagedResult that extends PagedResultDto<PetDto>, but that would only exist due to documentation purposes.

**Comment by stoicflame** [comment]
Such an enhancement might be worth thinking about.

**Comment by MosheElisha** [comment]
This will be very useful

**Comment by bemisguided** [comment]
I too agree this would be very useful. Even if to start it really just extrapolated the full generic details and then the fancy multi-page documentation structure came later.

I would be willing to have a go at implementing. @stoicflame perhaps you have some ideas of where to start or have thought about how this would be implemented?

**Comment by stoicflame** [comment]
Yeah, so I think the implementation would look something like:

* For each of [jaxb, jackson, jackson1] modules:
  * Edit the `TypeDefinition` to accept a `TypeVariableContext` in its constructor so it can resolve the generic type variables and use the `TypeVariableContext` in all of its methods to resolve the type variables.
  * Likewise for the `Accessor` class.
* For each `ApiRegistryProviderModule`, make sure the `TypeVariableContext` is provided to each `TypeDefinition` being constructed.
* Somehow figure out how to resolve conflicts that might occur when `TypeDefinition` has multiple resolutions.

**Comment by aaronddickson** [comment]
I ran into a need for this today so would like to record that I too would find this feature very useful.

**Comment by stoicflame** [comment]
This enhancement is currently seeking a sponsor. If anybody is willing to sponsor the work, [reach out to me](http://webcohesion.com/#contact) and I'd be happy to pick it up.

**Comment by stoicflame** [comment]
I'm happy to report that this work has been sponsored and will be included in the 2.9 release.

At 34bb7d8, I've pushed a draft of the changes. I've still got some validation to do, but if anybody wants to try it out and post feedback, I'd be happy to take it.

**Comment by stoicflame** [comment]
Thanks to the support of a generous sponsor, this issue has been implemented and will be included in 2.9.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
