### ISSUE TITLE
Adding support for custom annotations

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#401]
Hi.

Recently Bean Validations `@NotNull` support was added to enunciate which is a great and generic way of specifying field level constraints! We hope that the other little guys like `@Size`, `@Min` etc. will also find their way to enunciate in the future - that would be great ;).

Besides that, there are always custom annotations when it comes to Bean Validation in real projects.
E.g. Hibernates `@NotBlank` which also checks for empty (string) values, not just not-null.
I understand, that enunciate can not support all of them - and shouldn't.

But is there currently a way to hook into the enunciate's generation process and add that kind of functionality for custom annotations?

I stumbled across the skinning functionality and the freemarker templates. Is this the way to add such additional documentation on a field level constraint basis?

if that works out, it would have to be added to the enunciate templates as well as the swagger UI templates, I guess?

**Comment by stoicflame** [comment]
Sure, we can entertain support for other annotations.

And, yes, you should be able to write your own custom templates that take advantage of such annotations.

**Comment by vguna** [comment]
Sounds great! That means I could add e.g. @NotBlank support with 2.3.0 just working with the template/skinning functionality?

**Comment by stoicflame** [comment]
I don't know why you couldn't.

**Comment by vguna** [comment]
Nice! Thanks, I will look into that...

**Comment by miguelchico** [comment]
Hi,

How can we do that? How can we access the annotations from the freemarker template?

**Comment by stoicflame** [comment]
For example, to print some stuff about your custom annotation `com.mycompany.annotations.MyAnnotation` (pseudocode; not tested yet):

```
[#if type.annotations["com.mycompany.annotations.MyAnnotation"]??]
  <div class="my-special-annotation">
    <dl class="dl-horizontal">
  [#list type.annotations["com.mycompany.annotations.MyAnnotation"].elementValues?keys as annotationElement]
      <dt>${annotationElement}</dt>
      <dd>${type.annotations["com.mycompany.annotations.MyAnnotation"].elementValues[annotationElement]}</dd>
  [/#list]
    </dl>
  </div>
[/#if]
```

**Comment by stoicflame** [comment]
Bug scrub.

This issue has been quiet for awhile now. Can I assume that provisions are adequate and this can be closed?

**Comment by vguna** [comment]
Sadly, there was no time yet to implement it. But we can close it.

**Comment by stoicflame** [comment]
Support for [Bean Validation Annotations](http://docs.oracle.com/javaee/6/tutorial/doc/gircz.html) added at 6207635f867f9a92ebb5029fe6bce4a05ddd39b8.

**Comment by vguna** [comment]
You're the best :)!

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)

**Comment by miguelchico** [comment]
Great!
Thank you very much!. I'll try it!
