### ISSUE TITLE
wadl files have ANSI encoding 

### ISSUE THREAD

**Issue by alexander00001** [stoicflame/enunciate#407]
Hi everybody,

I'm using enunciate to generate docs and idl for REST endpoints. All the files of the documentation are generated in UTF-8 but the wadl is generated in ANSI.

I tried to force utf-8 encoding with this maven configuration:

```xml
<plugin>
  <groupId>com.webcohesion.enunciate</groupId>
  <artifactId>enunciate-maven-plugin</artifactId>
	<version>2.3.0</version>
	<configuration>
		<configFile>enunciate.xml</configFile>
		<docsDir>${project.build.directory}/enunicate-docs</docsDir>
		<encoding>utf-8</encoding>
	</configuration>
  <executions>
	<execution>
	  <goals>
		<goal>docs</goal>
	  </goals>
	</execution>
  </executions>
</plugin>
```

but the wadl still is ANSI. All java code is UTF-8 encoded.

What am I doing wrong?

Thanks in advance.

Alex

**Comment by stoicflame** [comment]
I'm afraid I can't reproduce this issue; the wadl is UTF-8 encoded for me.

Are you seeing corrupted characters or something?
