### ISSUE TITLE
collapse-type-hierarchy without @Ignore

### ISSUE THREAD

**Issue by vgcookies** [stoicflame/enunciate#408]
Hi.

First, thanks for all the great improvements and fixes in 2.4.0! Great job!

While testdriving the new version, I tested the new `collapse-type-hierarchy` option.
As expected, the inherited attributes now show up in the upper block. But the attributes in the lower section (from superclass) are still shown :).

![collapse_without_ignore](https://cloud.githubusercontent.com/assets/17743523/15814862/90e4efcc-2bc9-11e6-804f-c669a13384c7.png)

Looking at the Commit for the PR shows, that `@Ignore` should do the job. Applied it to the superclass, and now everything looks as expected.

Now I'm wondering, why `@Ignore` is needed at all :). It _does_ make sense, when I have a hierarchy, where also the superclass is a "standalone" DTO. In my specific case, the superclass is an `abstract` class, which could be omitted completely when collapse is activated - without having to use `@Ignore` at all.

WDYT?

**Comment by vgcookies** [comment]
I also realized, that the ignored classes are still showing up on the overview "start" page under JSON.

**Comment by vgcookies** [comment]
Also I'm seeing a strange `Enum` type appearing in the overview. Setting `collapse-type-hierarchy` to true also produces some warning about not found source files during build, that normally won't appear.

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
Fixed at 1623b286b8dcdc7140d5f55ef5099a67dbb74b80.

**Comment by stoicflame** [comment]
[Enunciate 2.5.0 is now available.](https://github.com/stoicflame/enunciate/releases/tag/v2.5.0)
