### ISSUE TITLE
collapse-type-hierarchy and java-json-client breakage

### ISSUE THREAD

**Issue by vgcookies** [stoicflame/enunciate#409]
Hi.

I'm using the latest `collapse-type-hierarchy` option to suppress superclasses from documentation. If I set it to `true`, suddenly the `java-json-client` build breaks with the message:

```java
.../target/enunciate/java-json-client/src/com/acme/Role.java:14: error: constructor Enum in class Enum<E> cannot be applied to given types;
public enum Role {
       ^
  required: no arguments
  found: String,int
  reason: actual and formal argument lists differ in length
  where E is a type-variable:
    E extends Enum<E> declared in class Enum
.../target/enunciate/java-json-client/src/com/acme/Status.java:14: error: constructor Enum in class Enum<E> cannot be applied to given types;
public enum Status {
       ^
  required: no arguments
  found: String,int
  reason: actual and formal argument lists differ in length
  where E is a type-variable:
    E extends Enum<E> declared in class Enum
```

The enum:

```java
	@JsonRootName("role")
	public enum Role {
		ADMIN,
		MANAGER,
		EMPLOYEE,
		CUSTOMER
	}
```

Setting it to false, or removing the java-json-client seems to work.
Any idea what goes wrong? Hint: The enum is embedded into a DTO. I know that enunciate had its problems with this in the past. Maybe it has something todo with it as well?

**Comment by stoicflame** [comment]
Weird. I'm afraid I can't seem to reproduce it, even with enums as inner classes. 

Do you think you could put together a sample project that demonstrates the problem?

**Comment by stoicflame** [comment]
Never mind; I got it reproduced.

**Comment by stoicflame** [comment]
Fixed at 1623b286b8dcdc7140d5f55ef5099a67dbb74b80.

**Comment by vgcookies** [comment]
Great. Thanks for looking into this!

**Comment by stoicflame** [comment]
[Enunciate 2.5.0 is now available.](https://github.com/stoicflame/enunciate/releases/tag/v2.5.0)
