### ISSUE TITLE
Reusing annotations

### ISSUE THREAD

**Issue by narvik01** [stoicflame/enunciate#413]
Hi.
When I was dealing with #412 I figured I could `@Ignore` the wrongly generated parameter and define the headers myself. That would lead to a lot of repeated `@RequestHeader` annotations across the project. Would it be possible to create custom annotation which would group and reuse other annotations? Something like [@JacksonAnnotationsInside](http://fasterxml.github.io/jackson-annotations/javadoc/2.0.6/com/fasterxml/jackson/annotation/JacksonAnnotationsInside.html)

**Comment by stoicflame** [comment]
Have you tried annotating the package? Would that work for your case?

**Comment by narvik01** [comment]
Thanks for the idea, I tried it. The `@RequestHeaders` annotation cannot be applied to a package and a single `@RequestHeader` is not used in the generated docs.

**Comment by stoicflame** [comment]
At e287fcfd88274e6c327fa493a97a15de29d23970, I allowed those annotations to be applied to the package.

**Comment by stoicflame** [comment]
[Enunciate 2.5.0 is now available.](https://github.com/stoicflame/enunciate/releases/tag/v2.5.0)
