### ISSUE TITLE
JsonTypeInfo.As.PROPERTY exclude other attribute 

### ISSUE THREAD

**Issue by jigarparekh80** [stoicflame/enunciate#419]
```
	@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "class")
	@JsonSubTypes({ @Type(value = RestType1.class, name = "type1"), @Type(value = RestType2.class, name = "type2") })
public List<RestType> getRestType() {
		return types;
	}

```

this generates class in document but does not show attribute from RestType

**Comment by stoicflame** [comment]
So I think you're saying that the documentation for the `RestType` data type should include a property called "class"? Or are you just saying the generated example JSON should include that property?

**Comment by stoicflame** [comment]
Bump.

Any word on this? The request is unclear to me.

**Comment by stoicflame** [comment]
Haven't heard back. I'm happy to re-open if more details can be provided.
