### ISSUE TITLE
bean setters

### ISSUE THREAD

**Issue by jayenashar** [stoicflame/enunciate#420]
i've got a bean param (which works):

```
    public TopResponse getTop(@Context HttpServletRequest request, @Context HttpServletResponse response,
                              @BeanParam TopBean2 topBean) {
```

inside the bean i've got some matrixparams (field `term` works):

```
public class TopBean2 {
    @MatrixParam("term")
    private           Term                                       term;

    @MatrixParam("addresses")
    private void setAddresses(String addresses) throws IOException {
        this.addresses = MAPPER.readValue(addresses, Addresses.class);
    }

    @MatrixParam("checkboxes")
    private void setCheckboxes(String checkboxes) throws IOException {
        this.checkboxes = MAPPER.readValue(checkboxes, Checkboxes.class);
    }

    @MatrixParam("sliders")
    private void setSliders(String sliders) throws IOException {
        this.sliders = MAPPER.readValue(sliders, Sliders.class);
    }
}
```

but the setters don't work (as in the generated docs don't contain addresses, checkboxes, or sliders)

**Comment by stoicflame** [comment]
Enunciate is only considering "properties", which by JavaBean definition only include `public` setters. But if `private` setters are recognized by Jersey, then I'll take a look at supporting that for 2.6.

**Comment by jayenashar** [comment]
yeah, it works with my the version of jersey i'm using (2.0-m11).

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)

**Comment by jayenashar** [comment]
works for me, thanks!
