### ISSUE TITLE
Export documentation as xml

### ISSUE THREAD

**Issue by fcav1973** [stoicflame/enunciate#423]
Hi,
in version 1.28-RC2 was possible, using the <docs> module, to generate the documentation as pure xml file (docs.xml). Is it possible to obtain the same object with 2.5.0 version (we use that feature to generate documentation in docbook  format)  ?

**Comment by stoicflame** [comment]
I'm afraid not. That XML file was deemed to be an unneeded piece of complexity and was removed in Enunciate 2.

Could you provide your own custom freemarker template that generates the docbook? Alternatively, you could edit the freemarker template to have Enunciate produce a single-page HTML doc. See:

https://github.com/stoicflame/enunciate/wiki/Custom-Skin#custom-freemarker-transform
