### ISSUE TITLE
@JsonProperty breaks @NotNull

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#424]
Hi.

I'm using Enunciate 2.5.0 to generate REST documentation from my DTOs using Jackson.
Recently I had to rename a property on the DTO using `@JsonProperty`. After annotating
the getter with it, the required state marked using `@NotNull` is gone and won't
be reflected in the documentation anymore. Removing the `@JsonProperty` makes the required
state work again. I would expect, that using the json property annotation shouldn't
affect the required state. I'm missing something?

**Comment by stoicflame** [comment]
Confirmed.

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
