### ISSUE TITLE
swagger module and project rest services across multiple ports

### ISSUE THREAD

**Issue by javaworkinggirl** [stoicflame/enunciate#429]
Hi. I have an application that has REST services across 3 different ports.  I am using enunciate-maven-plugin to generate enunciate docs and swagger docs.  How do I get the swagger docs to generate with the proper port?
I tried having 3 config files in the maven plugin configuration, but that does not work (only the last config file gets used).  Any other ideas?

**Comment by stoicflame** [comment]
I'm afraid that's a use case that Enunciate doesn't know how to support. 

Does each port have a different application? Do you have each application in the same project? What does the deployment configuration look like on that?

Can you generate three different sets of documentation, one for each port?

**Comment by javaworkinggirl** [comment]
Darn I was afraid of that.  We have one application, that serves up different services on different ports.  When we deploy, we have 1 rpm containing our model classes jar, persistence classes jar, service (rest) classes jar and also all other 3rd party jars.

**Comment by javaworkinggirl** [comment]
hmm. can i run the enunciate-maven-plugin in 3 different maven profiles with 3 different enunciate.xml files that generate docs to 3 different locations?

**Comment by javaworkinggirl** [comment]
Using maven profiles worked.  I made 3 different enunciate.xml files that include the rest services for that particular port and exclude the others.  So then the main build will do the common docs.  If I run maven with `mvn install -Dmaven.skip.test=true -Ppurchase`, it will create the purchase docs.  I will post some of my pom.xml incase anyone else needs it.
`     <plugin>
            <groupId>com.webcohesion.enunciate</groupId>
            <artifactId>enunciate-maven-plugin</artifactId>
            <version>${enunciate-maven-plugin.version}</version>
            <executions>
               <execution>
                  <id>docs</id>
                  <goals>
                     <goal>docs</goal>
                  </goals>
                  <configuration>
                     <configFile>enunciate-common.xml</configFile>
                     
                     <docsDir>${project.build.directory}/common</docsDir>
                  </configuration>
               </execution>
            </executions>
         </plugin>
      </plugins>
   </build>
   <profiles>
      
      <profile>
         <id>research</id>
         <activation>
            <property>
               <name>env</name>
               <value>research</value>
            </property>
         </activation>
         <build>
            <plugins>
               <plugin>
                  <groupId>com.webcohesion.enunciate</groupId>
                  <artifactId>enunciate-maven-plugin</artifactId>
                  <version>${enunciate-maven-plugin.version}</version>
                  <executions>
                     <execution>
                        <id>docs</id>
                        <goals>
                           <goal>docs</goal>
                        </goals>
                        <configuration>
                           <configFile>enunciate-research.xml</configFile>
                           
                           <docsDir>${project.build.directory}/research</docsDir>
                        </configuration>
                     </execution>
                  </executions>
               </plugin>
            </plugins>
         </build>
      </profile>
      
      <profile>
         <id>purchase</id>
         <activation>
            <property>
               <name>env</name>
               <value>purchase</value>
            </property>
         </activation>
         <build>
            <plugins>
               <plugin>
                  <groupId>com.webcohesion.enunciate</groupId>
                  <artifactId>enunciate-maven-plugin</artifactId>
                  <version>${enunciate-maven-plugin.version}</version>
                  <executions>
                     <execution>
                        <id>docs</id>
                        <goals>
                           <goal>docs</goal>
                        </goals>
                        <configuration>
                           <configFile>enunciate-purchase.xml</configFile>
                           
                           <docsDir>${project.build.directory}/purchase</docsDir>
                        </configuration>
                     </execution>
                  </executions>
               </plugin>
            </plugins>
         </build>
      </profile>
   </profiles>`
