### ISSUE TITLE
java enum with Jackson JsonFormat.Shape.OBJECT and enunciate-maven-plugin -> error 

### ISSUE THREAD

**Issue by blueRay0** [stoicflame/enunciate#430]
java 8, jackson

I use a java enum(State) with following Jackson annotation:
`@JsonFormat(shape = JsonFormat.Shape.OBJECT)`

with enunciate-maven-plugin version 2.5.0 i get the following 
error:

```
classes cannot directly extend java.lang.Enum
public final class State extends java.lang.Enum<com.State> {
```

This wrong  class is generated by enunciate the original class is 

```
@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public enum State {
...
}

```

**Comment by stoicflame** [comment]
Okay, thanks for the report.

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
