### ISSUE TITLE
@Ignore on the field level

### ISSUE THREAD

**Issue by sivarajasekaran** [stoicflame/enunciate#431]
Hi,

1. Is there an option to Ignore Specific fields of the response generated ? Otherwise is there any way to specify a sample Json response? 
2. Is it possible for a Json request to specify optional / required ?

Something like this

```
@XmlRootElement
public class Persona {

  private String id;
  private String email;
 @Required
 private String alias;
  private String[] groups;
 @Ignore  
 private Name name;
 private javax.activation.DataHandler picture;

.....
```

**Comment by stoicflame** [comment]
> Is there an option to Ignore Specific fields of the response generated?

That's a question about how to use Jackson. See [`@JsonIgnore`](http://fasterxml.github.io/jackson-annotations/javadoc/2.0.2/com/fasterxml/jackson/annotation/JsonIgnore.html).

> Otherwise is there any way to specify a sample Json response?

See [`@DocumentationExample`](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#cwemdocumentationexample).

> Is it possible for a Json request to specify optional / required?

Again, a question about how to use Jackson. `@JsonProperty(required=true)`.

**Comment by sivarajasekaran** [comment]
@JsonIgnore is working from Jackson side of it, I mean it's not generating on the response. But documentation enunciate creates, it 's not ignoring on the generated documents. My question was related to Docs generated.

**Comment by stoicflame** [comment]
Enunciate honors `@JsonIgnore`, so you might be using the wrong annotation (`org.codehaus` instead of `com.fasterxml`) or you might be annotating the field when you should be annotating the property or vice-versa.

**Comment by bakku** [comment]
I came across this problem as well. 

When using `@JsonIgnore` on the field it does not work but when I used the annotation on the getter method of the field then enunciate ignored it.
