### ISSUE TITLE
Does enunciate/swagger recognize swagger annotations, i.e. @ApiResponse

### ISSUE THREAD

**Issue by javaworkinggirl** [stoicflame/enunciate#433]
Does enunciate/swagger recognize swagger annotations, i.e. @ApiResponses?
I am trying to get swagger docs that show different responses.   Using this in my code and included the swagger-core jar, but I don't see the @ApiResponses showing up in the swagger docs.  Or is there another way to accomplish showing different response codes/ response objects?

```java
@PUT
   @Path("/ppv")
   @ReturnType("java.util.List<com.twc.ctg.ecp.model.ViolationError>")
   @ApiResponses(value = {
      @ApiResponse(code = 200, message = "Success"),
      @ApiResponse(code = 400, message = "Bad Request"),
      @ApiResponse(code = 409, message = "Conflict"),
      @ApiResponse(code = 415, message = "Unsupported Media Type"),
      @ApiResponse(code = 422, message = "Violation Errors", response = ViolationError[].class),
      @ApiResponse(code = 500, message = "Internal Server Error")})
   @Valid
   public Response putPpv(@Context final HttpServletRequest request, @NotNull @Valid final PpvDto ppv) throws GenericRestException
  ````

**Comment by stoicflame** [comment]
See [Enunciate-Specific-Annotations](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations).

Enunciate doesn't currently honor swagger annotations, but I can look into what it would take to do so.

**Comment by dklotz** [comment]
This would make it much easier to switch between swagger-core and enunciate! 
👍

**Comment by stoicflame** [comment]
A lot of the Swagger annotations were very swagger-specific, but I've added limited support at 080dfee.

Includes partial support for:

* `ApiOperation`
* `ApiImplicitParams`
* `ApiResponses`

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
