### ISSUE TITLE
enunciate-2.5.0.xsd is invalid according to Eclipse XML Validator

### ISSUE THREAD

**Issue by steinermatt** [stoicflame/enunciate#434]
Looks like the [http://enunciate.webcohesion.com/schemas/enunciate-2.5.0.xsd](http://enunciate.webcohesion.com/schemas/enunciate-2.5.0.xsd) is invalid - at least according to Eclipse XML Validation: 

> Attribute 'path-sort-strategy" has both a 'type' attribute and and anonymous 'simpleType' child. Only one of these is allwoed for an attribute.

**Comment by stoicflame** [comment]
Should be fixed now.
