### ISSUE TITLE
DocumentationExample disappears?

### ISSUE THREAD

**Issue by jayenashar** [stoicflame/enunciate#436]
I'm trying to use `@DocumentationExample` but it's not appearing anywhere in the result.  I don't see a space for it either.  I have this in a `BeanParam`:

```
    @QueryParam("suburbs")
    @DocumentationExample(value = "CAMPSIE, NSW 2194", value2 = "ASHFIELD, NSW 2131")
    private String[]      suburbs;
```

and it appears like this:

![snapshot21](https://cloud.githubusercontent.com/assets/1137152/16170462/fae5440e-3596-11e6-90f8-f5030c910d33.png)
![snapshot21](https://cloud.githubusercontent.com/assets/1137152/16170468/062003c2-3597-11e6-80c4-27f5fb4fcef1.png)

**Comment by stoicflame** [comment]
The documentation example will show up in Enunciate's generated example, but not in the swagger docs. Can you confirm it's in the Enunciate-generated example json?

**Comment by jayenashar** [comment]
the only json file i can see is `swagger.json`.

here's my enunciate-maven config:

```
            <plugin>
                <groupId>com.webcohesion.enunciate</groupId>
                <artifactId>enunciate-slim-maven-plugin</artifactId>
                <version>${enunciate.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>assemble</goal>
                        </goals>
                        <configuration>
                            <docsSubdir>apidocs</docsSubdir>
                            <excludes>
                                <exclude>**</exclude>
                            </excludes>
                            <includes>
                                <include>chooser.rh.api.PropertiesResource</include>
                                <include>chooser.rh.api.PropertiesBean</include>
                                <include>chooser.rh.api.PropertiesResponse</include>
                            </includes>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <!-- http://mvnrepository.com/artifact/com.webcohesion.enunciate/enunciate-jaxrs -->
                    <dependency>
                        <groupId>com.webcohesion.enunciate</groupId>
                        <artifactId>enunciate-jaxrs</artifactId>
                        <version>${enunciate.version}</version>
                    </dependency>
                    <!-- http://mvnrepository.com/artifact/com.webcohesion.enunciate/enunciate-jackson -->
                    <dependency>
                        <groupId>com.webcohesion.enunciate</groupId>
                        <artifactId>enunciate-jackson</artifactId>
                        <version>${enunciate.version}</version>
                    </dependency>
                    <!-- http://mvnrepository.com/artifact/com.webcohesion.enunciate/enunciate-swagger -->
                    <!--doesn't support matrix parameters-->
                    <dependency>
                        <groupId>com.webcohesion.enunciate</groupId>
                        <artifactId>enunciate-swagger</artifactId>
                        <version>${enunciate.version}</version>
                    </dependency>
                    <!--got this from the maven -X output.  you need this or it generates NOTHING-->
                    <dependency>
                        <groupId>com.webcohesion.enunciate</groupId>
                        <artifactId>enunciate-docs</artifactId>
                        <version>${enunciate.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by stoicflame** [comment]
It's not the swagger.json. It's the JSON embedded in the Enunciate-generated documentation (the html pages).

**Comment by jayenashar** [comment]
JSON embedded in the html...?  I can't find what you're describing.  Do I need to add another dependency to the maven plugin to get it to appear?

**Comment by jayenashar** [comment]
another related question.  can i use `@DocumentationExample` on a field of a response?  having the same issue where the example doesn't appear anywhere (and i don't know where it should appear).

**Comment by jayenashar** [comment]
ok i think i see what you mean now.  i only see an example for the whole response, not for the `QueryParam`.  is this what you mean?  any way to show examples for `QueryParam` or fields of responses, rather than putting everything in the description?

**Comment by jayenashar** [comment]
although `@DocumentationExample` isn't working for me on my response.  it still shows a very barebones example response and not the one i put in the annotation:

```
{
  "html" : "...",
  "next_page" : "...",
  "markers" : [ { }, { } ]
}
```

**Comment by stoicflame** [comment]
Oh, I see what you're doing now.

So `@DocumentationExample` is for datatype fields, and isn't used for `@QueryParam`s. The issue suggests you'd like it to show up in the Swagger UI? I'm not sure that's possible, but I can take a look.

**Comment by jayenashar** [comment]
I'm not sure what a "datatype" field is.  I see two things called "data type" in the generated HTML: the Response class and the Response fields.

I have tried `@DocumentationExample` on [a BeanParam field annotated with `@QueryParam`](https://github.com/stoicflame/enunciate/issues/436#issue-161018758), [a Response class](https://github.com/stoicflame/enunciate/issues/436#issuecomment-226990920), and [a Response field](https://github.com/stoicflame/enunciate/issues/436#issuecomment-226987864).

I don't mind if it shows up in enunciate or the swagger UI, but I'm not seeing it in either.

What I do see is an example Response, but it's not the one I have annotated.

![snapshot21](https://cloud.githubusercontent.com/assets/1137152/16360744/08dba48a-3bb5-11e6-94bf-975d7de21162.png)

**Comment by stoicflame** [comment]
`PropertiesResponse` is an example of a data type. The `@DocumentationExample` is intended e.g. for the `html`, `next_page`, and `markers` properties.

**Comment by jayenashar** [comment]
ok thanks.  i must be doing something wrong on the `markers` field:

```
    @DocumentationExample("[\n" +
                          "    [\n" +
                          "        4,\n" +
                          "        1,\n" +
                          "        2,\n" +
                          "        \"$530 per week\",\n" +
                          "        \"active\",\n" +
                          "    ]\n" +
                          "]")
    public List<List<Object>> markers;
```

**Comment by stoicflame** [comment]
Yes, that's not going to work. The `@DocumentationExample` is used by Enunciate to fill in values when it needs them. Enunciate doesn't parse the `@DocumentationExample` as JSON, and Enunciate doesn't need an example for type `Object`, so `List<List<Object>>` isn't going to use the documentation examples.

**Comment by jayenashar** [comment]
So what can I do in this case?  In any event, the generated `[ { }, { } ]` should at least be `[ [ { }, { } ], [ { }, { } ] ]` and the "data type" column entry "array of object" should show "array of array of object"

**Comment by stoicflame** [comment]
Yes, that's probably a bug. I'll look at that, too.

**Comment by stoicflame** [comment]
I looked at the [swagger spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject), but could find no way to put the example in that text box. If anybody can find a way to do it, let me know.

I fixed the incorrect example at 17076fc.

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)

**Comment by jayenashar** [comment]
it looks a little better, as `[ [ ], [ ] ]`, but i really would like to be able to put an example in there.

**Comment by jayenashar** [comment]
with regards to the swagger, what i originally wanted on query params, i can't find anything in the swagger docs or the petstore example, but there is an example for POST body JSON property "name" with the value "doggie".

**Comment by stoicflame** [comment]
Can you point out that example for me?

**Comment by jayenashar** [comment]
sorry, should've included links:  http://petstore.swagger.io/#!/pet/addPet - if you click on the example value on the right, it fills in the body.  then in http://petstore.swagger.io/v2/swagger.json you can search for "doggie" though i can only find the one field having an example.  not sure what the swagger UI does to create the rest of that example body.

**Comment by stoicflame** [comment]
Okay, I can track that at #489.

Of course, that's only for schema (e.g. "model") objects. Do you see any swagger capabilities for example values for query parameters, like you were originally asking for when you opened this issue?

**Comment by jayenashar** [comment]
no, i can't find a swagger equivalent.  i'm not particularly attached to swagger.  if enunciate-html lets me put examples for query parameters, i'll be happy.
