### ISSUE TITLE
a way to put data in the constraints column of request parameters

### ISSUE THREAD

**Issue by jayenashar** [stoicflame/enunciate#437]
it looks like the constraints column is currently populated based on the type of the parameter.  i'd like to be able to specify this in the case that the type is a string.  preferably, an annotation that takes a vararg of strings as a parameter to display in the same manner as it displays an enum.  maybe another parameter/annotation of a raw string or regex pattern.

examples:

```
@DocumentationConstraintEnum("!", "@", "#", "$", "%", "^", "&", "*", "(", ")")
@DocumentationConstraintRaw("int >= 0")
@DocumentationConstraintRegex("0x[0-9a-fA-F]+")
```

apologies if this already exists in jax-rs or enunciate.  i could only find regex's for path parameters (though i don't have path parameters so i don't know where these would appear anyway).

right now i'm jamming a raw string in the javadoc description, but it's ugly

**Comment by stoicflame** [comment]
Support for [Bean Validation Annotations](http://docs.oracle.com/javaee/6/tutorial/doc/gircz.html) added at 6207635f867f9a92ebb5029fe6bce4a05ddd39b8.

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)

**Comment by jayenashar** [comment]
this isn't working for me:

```
    @QueryParam("surrounding_suburbs")
    @Min(0)
    @Max(1)
    private int           surrounding_suburbs;
```

it just shows `int`:

![snapshot21](https://cloud.githubusercontent.com/assets/1137152/17957255/7c49c012-6ad3-11e6-9280-b3ccc309c39e.png)

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)

**Comment by jayenashar** [comment]
Apologies for the delay in testing this.  The project's been cancelled.

It's working for me though I'm having a small problem with @Pattern .  I'll open another issue for it.
