### ISSUE TITLE
Error Response 200 description missing from swagger ui

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#440]
Hi.

I'm using enunciate 2.5.0 for generating the swagger ui from my REST endpoint interfaces.
It works so far except for the "Response Class (Status 200)" description on the top of a `@POST` method. It seems somehow lost.

Here's the interface:

```java
    /**
	 * Saves the given locations.
	 *
	 * @param locations
	 *            the locations to create.
	 *
	 * @HTTP 200 <code>OK</code>, if the locations were immediately saved successfully.
	 * @HTTP 202 <code>ACCEPTED</code>, if the save operation is performed asynchronously. 
	 * @HTTP 400 <code>BAD_REQUEST</code>, if the request body was malformed or validation of the location failed.
	 * @return empty body - just the appropriate status code set.
	 */
	@POST
	@Consumes(MediaType.APPLICATION_JSON)
	Response create(List<LocationDto> locations);
```

Here's the json swagger part:

```json
        "responses" : {
          "200" : {
            "schema" : {
"description" : "",
"type" : "file"
            },
            "headers" : {
            },
            "description" : "<code>OK<\/code>, if the locations where immediately saved successfully."
          },
          "202" : {
            "schema" : {
"description" : "",
"type" : "file"
            },
            "headers" : {
            },
            "description" : "<code>ACCEPTED<\/code>, if the save operation is performed asynchronously.
          },
          "400" : {
            "headers" : {
            },
            "description" : "<code>BAD_REQUEST<\/code>, if the request body was malformed or validation of the location failed."
          },
          "default" : {
            "description" : "Unexpected error."
          }
        }
```

I don't know why github marks it red, you can ignore it, I guess.

And the resulting swagger ui:

![screen shot 2016-06-21 at 18 40 46](https://cloud.githubusercontent.com/assets/3257311/16238133/9daa2cfa-37df-11e6-84a0-4c99435b1eb8.png)

The description of the 202 and 400 in the bottom part are ok though.

Any idea what's going wrong?

BTW: there's a "default" http status code in the bottom saying "unexpected error" as reason. What is it for and is there a way to remove/set it?

**Comment by stoicflame** [comment]
I'm afraid I can't reproduce this issue. I copied the JavaDoc as you described above and the swagger.json came out as expected.

I'd be happy to re-open if you can provide me a way to reproduce the issue.

**Comment by vguna** [comment]
Did you actually check the display of the swagger file in the browser? Not just the source? The json source looks ok as shown above...

**Comment by stoicflame** [comment]
Yes:

![response-messages](https://cloud.githubusercontent.com/assets/145838/17778431/3249d43c-6521-11e6-9d7b-f53a69b82756.png)

**Comment by vgcookies** [comment]
Hm, tried to reproduce without luck with 2.6.0. So thanks :)!

But what about the "Unexpected error." with status code "default"? What is this good for :)? It seems to be generated for every endpoint...
