### ISSUE TITLE
java client side code generation for server interfaces

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#441]
Hi.

I've taken a look at the java client side code generation. Currently it only offers the model for download.
Since I like using client side proxies using the server interfaces (either using JAX-RS or Apache CXF client), it would be great if server interfaces could also be extract to the download artifact. This way, writing a client will be a breeze. WDYT?

Besides that, I found a bug in the generated model class javadoc generation (missing asterisks):

```java
/**
 *  Represents a customer related order.

 @author J.Doe created 2016-05-18
 @since 0.0.1

 */
```

Maybe it's also a good idea to strip the `@author` :)?

**Comment by stoicflame** [comment]
Yes, adding client-side interfaces could happen. That's being tracked at #257, but it's not currently scheduled for a particular release.

I opened at new issue at #442 for the javadoc bug.
