### ISSUE TITLE
compiler Args stackoverflow use -J-Xss4m 

### ISSUE THREAD

**Issue by RyuTsuiSen** [stoicflame/enunciate#444]
Hi,

I need use compilerArgs with arg value : -J-Xss4m because I have a big java class and stack error enunciate produces an stackoverflow. But that doesn't work :( 
Can you help me please ? 
I made this : 
```

			<plugin>
				<groupId>com.webcohesion.enunciate</groupId>
				<artifactId>enunciate-slim-maven-plugin</artifactId>
				<version>2.3.0</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>docs</goal>
						</goals>
						<configuration>
							<configFile>${basedir}/descriptors/enunciate.xml</configFile>
							<compilerArgs>
								<arg>-nowarn</arg>
								<arg>-J-Xss4m</arg>
							</compilerArgs>
							<skipEnunciate>false</skipEnunciate>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>com.webcohesion.enunciate</groupId>
						<artifactId>enunciate-java-xml-client</artifactId>
						<version>2.3.0</version>
					</dependency>
					<dependency>
						<groupId>com.webcohesion.enunciate</groupId>
						<artifactId>enunciate-jaxrs</artifactId>
						<version>2.3.0</version>
					</dependency>
					<dependency>
						<groupId>com.webcohesion.enunciate</groupId>
						<artifactId>enunciate-java-json-client</artifactId>
						<version>2.3.0</version>
					</dependency>
					<dependency>
						<groupId>com.webcohesion.enunciate</groupId>
						<artifactId>enunciate-jackson</artifactId>
						<version>2.3.0</version>
					</dependency>
					<dependency>
						<groupId>com.webcohesion.enunciate</groupId>
						<artifactId>enunciate-docs</artifactId>
						<version>2.3.0</version>
					</dependency>
					<dependency>
						<groupId>com.webcohesion.enunciate</groupId>
						<artifactId>enunciate-idl</artifactId>
						<version>2.3.0</version>
					</dependency>
				</dependencies>
			</plugin>
```

Below the log from -X maven 

> [DEBUG] Configuring mojo com.webcohesion.enunciate:enunciate-slim-maven-plugin:2.3.0:docs from plugin realm ClassRealm[plugin>com.webcohesion.enunciate:enunciate-slim-maven-plugin:2.3.0, parent: sun.misc.Launcher$AppClassLoader@70dea4e]
> [DEBUG] Configuring mojo 'com.webcohesion.enunciate:enunciate-slim-maven-plugin:2.3.0:docs' with basic configurator -->
> [DEBUG]   (f) buildDir = D:\Git_Storage\myproject\build\enunciate
> [DEBUG]   (f) compilerArgs = [-nowarn, -J-Xss4m]
> [DEBUG]   (f) configFile = D:\Git_Storage\myproject\descriptors\enunciate.xml
> [DEBUG]   (f) disableSourcepath = false
> [DEBUG]   (f) docsDir = D:\Git_Storage\myproject\build\site
> [DEBUG]   (f) docsStagingDir = D:\Git_Storage\myproject\build/enunciate-docs-staging
> [DEBUG]   (f) encoding = UTF-8
> [DEBUG]   (f) exportsDir = D:\Git_Storage\myproject\build
> [DEBUG]   (f) localRepository =       id: local
> [DEBUG] [ENUNCIATE] Compiler args: [-source, 1.8, -target, 1.8, -encoding, UTF-8]

and partial stacktrace

> INFO] --- enunciate-slim-maven-plugin:2.3.0:docs (default) @ myproject ---
> [INFO] [ENUNCIATE] Using enunciate configuration at /applis/iced/git-local-repositories/myproject/descriptors/enunciate.xml
> [WARNING] [ENUNCIATE] [javac] 
> [WARNING] [ENUNCIATE] [javac] 
> [WARNING] [ENUNCIATE] [javac] The system is out of resources.
> [WARNING] [ENUNCIATE] [javac] Consult the following stack trace for details.
> [WARNING] [ENUNCIATE] [javac] java.lang.StackOverflowError
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.Scanner.ensureLookahead(Scanner.java:101)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.Scanner.token(Scanner.java:95)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.peekToken(JavacParser.java:310)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.peekToken(JavacParser.java:306)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.term3(JavacParser.java:1249)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.term2(JavacParser.java:909)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.term1(JavacParser.java:880)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.term(JavacParser.java:836)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.term(JavacParser.java:816)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.parseExpression(JavacParser.java:779)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.arguments(JavacParser.java:1818)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.arguments(JavacParser.java:1833)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.argumentsOpt(JavacParser.java:1805)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.term3Rest(JavacParser.java:1483)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.term3(JavacParser.java:1421)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.term2(JavacParser.java:909)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.term1(JavacParser.java:880)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.term(JavacParser.java:836)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.term(JavacParser.java:816)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.parseExpression(JavacParser.java:779)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.parExpression(JavacParser.java:2299)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.parseStatement(JavacParser.java:2483)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.blockStatement(JavacParser.java:2391)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.parseStatementAsBlock(JavacParser.java:2356)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.parseStatement(JavacParser.java:2488)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.blockStatement(JavacParser.java:2391)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.parseStatementAsBlock(JavacParser.java:2356)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.parseStatement(JavacParser.java:2488)
> [WARNING] [ENUNCIATE] [javac] 	at com.sun.tools.javac.parser.JavacParser.blockStatement(JavacParser.java:2391)

Thanks you

Regards,

**Comment by stoicflame** [comment]
I don't know why that didn't work. I'll take a closer look.

**Comment by RyuTsuiSen** [comment]
i am not sure because i have just read the source code
But it would seem that in com.webcohesion.enunciate.mojo.ConfigMojo class,  the property @paramater compilerArgs type String[] is never used. 
On the execute() method, this property is never used and a local property List<String> compilerArgs instead an array is used.
I hope it will solve this issue
thanks

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
