### ISSUE TITLE
Enunciate generated doc without internet connectivity: slow and unformatted

### ISSUE THREAD

**Issue by maecval** [stoicflame/enunciate#445]
Our application server where the enunciate-generated documentation is deployed does not have internet connectivity (i.e. behind firewalls).

Hence resources such as sytelsheets and javascripts, ... can not be loaded.
This results in 
- very long load time of the page
- unformatted pages (nearly unreadable)

Is there a solution to this?
Can these external resources be packaged at build time of the documentation?

**Comment by stoicflame** [comment]
See [Custom Skin](https://github.com/stoicflame/enunciate/wiki/Custom-Skin).

You'll need to use a combination of a custom freemarker transform and a custom documentation base. You'll put all the css, js in the documentation base, and the custom freemarker transform will reference each css, js file as a relative URI reference resolving to wherever you put them in the documentation base.
