### ISSUE TITLE
request body media type missing

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#446]
Hi.

I'm using Enunciate 2.5.0 to generate the REST documentation for my JAX-RS interfaces.
There exists one endpoint that `@Consume`s `MediaType.APPLICATION_FORM_URLENCODED`. If I look at the enunciate documentation, the request body media type is missing. Also in the swagger UI.
I'm missing something here?

<img width="798" alt="mediatype-missing" src="https://cloud.githubusercontent.com/assets/3257311/16480101/9a7e3bc2-3ea4-11e6-9103-013914928bec.png">

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
