### ISSUE TITLE
Enunciate ignoring Serialization Annotations

### ISSUE THREAD

**Issue by bmareal** [stoicflame/enunciate#448]
I'm trying to use enunciate to generate the documentation for a large REST API. 

Most of my getters and setters use serialization annotations like this:
 
```
@JsonSetter("fn")
public String setFirstName(String firstName) {
	return this.firstName;
}

@JsonSetter("ln")
public String setLastName(String lastName) {
	return this.lastName;
}

@JsonGetter("fn")
public String getFirstName() {
	return this.firstName;
}

@JsonGetter("ln")
public String getLastName() {
	return this.lastName;
}
```

However, enunciate is ignoring the `@JsonGetter` and `@JsonSetter` tags, and documenting my services properties and examples like this:
```
name       data type        description
firstName  string 	 
lastName   string 	 

Example:
{
  "firstName" : "...",
  "lastName" : "...",
}
```

Whichever configuration I try, the result seems to be always the same as described so... Is there a way to make enunciate to recognize serialization annotations?

**Comment by stoicflame** [comment]
I'll take a look for 2.6.

**Comment by bmareal** [comment]
Thank you! Let me know if you need some kind of beta testing

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
