### ISSUE TITLE
Resource URL in docs is incorrect

### ISSUE THREAD

**Issue by coryfin** [stoicflame/enunciate#449]
I have an app running at www.example.com/api/v1/. I have two resources:
www.example.com/api/v1/resource1
www.example.com/api/v1/resource2

Enunciate docs are located at:
www.example.com/api/v1/docs/resource1.html
www.example.com/api/v1/docs/resource2.html

The root is forwarded to the docs, so you don't have to include /docs in the URL:
www.example.com/api/v1/resource1.html
www.example.com/api/v1/resource2.html

But the sample resource URLs in the generated HTML pages are:
```
../resource1
../resource2
```

... which leaves out the /v1 and takes me to:
www.example.com/api/resource1
www.example.com/api/resource2

Is there a way to tell enunciate to use the following sample resource URLs in the generated HTML pages instead?
```
resource1
resource2
```

**Comment by stoicflame** [comment]
Enunciate calculates its relative paths according to the configured docs subdirectory.

Are you asking if there's a way to override that calculation?

**Comment by coryfin** [comment]
Yes, I think that's what I would need. My first thought was that I could change docsDir or docsSubdir, but that would just change where the docs are put after their generated, right?

**Comment by stoicflame** [comment]
At a6c0253:

```xml
<enunciate>
  <modules>
    <docs apiRelativePath="./"/>
```

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
