### ISSUE TITLE
Unknown type handling

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#451]
Hi.

I'm using enunciate 2.5.0 for generating JAX-RS documentation from my endpoint interfaces and DTOs.
One of my DTOs has a URL attribute, that is handled by jackson properly. If I take a look at the enunciate docs, the URL type is shown as a separate JSON type and all its properties (host, port etc.) are also taken into the swagger json file - which isn't desirable :). Is there a way to ignore or change the types (e.g. on DTOs) that enunciate sees? Otherwise I would have to switch URL to String instead.

**Comment by stoicflame** [comment]
I'll add URL as a known type.

You can use `@JsonFormat` or `@JsonSerialize` or `@TypeHint` to explicitly set the type to string for now.

**Comment by vguna** [comment]
Thanks for the quick feedback. Using `@TypeHint` works for the DTO. Then it prints `String` instead of `URL`, but:

- `@NotNull` seems to get lost then
- `URL` still appears in the overview of the JSON types

I tried the other two alternative annotations with the same effect.

Also trying to explicitly exclude `java.net.URL` via `enunciate.xml` `api-classes` exclude doesn't seem to help. So I have to go with the `String` for now, I guess :)?

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
