### ISSUE TITLE
generic List types are typed as "file" in swagger json

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#452]
Hi.

I'm using enunciate 2.5.0 to generate the swagger json from my JAX-RS interfaces/DTOs.
Pasting the generated swagger.json into the [swagger editor](http://editor.swagger.io) shows some errors and warnings.

One seems to come from a wrong type, declared as "file" as shown here:

```json
            },
            "result" : {
"description" : "The list with the actual results. The result contains json objects of the endpoint related type.",
"type" : "array",
"items" : {
  "type" : "file"
}
            },
```

The result is a `List` property contained in a generic typed DTO such as `PagedResultDto<T>`. The method signature for this looks like this:

```java
	public List<T> getResult() {
		return result;
	}

	public void setResult(List<T> result) {
		this.result = result;
	}
```

Changing the type from "file" to "object" seems to fix the the validation error.
Is this a known issue?

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
