### ISSUE TITLE
description warnings in swagger.json

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#453]
I'm using enunciate 2.5.0 to generate the swagger json from my JAX-RS interfaces/DTOs.
Pasting the generated swagger.json into the [swagger editor](http://editor.swagger.io) shows some validation warnings regarding descriptions:

![screen shot 2016-07-07 at 16 49 22](https://cloud.githubusercontent.com/assets/3257311/16657434/cd616f14-4462-11e6-91b3-604067f5f910.png)

It seems related to descriptions that are side-by-side with `$ref`s. Removing the description fixes the warning.

**Comment by stoicflame** [comment]
I've been looking at this, and I'm pretty confident that this is a validator problem or a deficiency in Swagger. Removing that "description" eliminates some interesting contextual documentation. So seeing as how this is a "warning", I'd rather leave it in there and push on the Swagger guys to adjust.
