### ISSUE TITLE
Maven plugin does not include artifacts of type ejb or ejb-client to classpath. 

### ISSUE THREAD

**Issue by kallemetria** [stoicflame/enunciate#454]
I have a maven project with multiple moduls. The module that I want to apply the enunciate maven plugin on has a dependency to another maven module of type "ejb", like this:
```
<dependency>
  <groupId>${project.groupId}</groupId>
  <artifactId>some-service</artifactId>
  <version>${project.version}</version>
  <type>ejb</type>
</dependency>
```
The dependant artifact some-service contains classes (JPA models) that the modul is dependent on. I have something like this in enunciate.xml:
```
<api-classes >
  <include pattern="com.metria.someproj.some-service.model.**"/>
  <include pattern="com.metria.someproj.web.**"/>
</api-classes >
```
Where the package com.metria.someproj.web is in the modul I have the enunciate maven plugin in and com.metria.someproj.some-service.model is in some-service. When I try to build with maven it fails with messages like this:

_[[WARNING] [ENUNCIATE] [javac] [ERROR] com.webcohesion.enunciate.Enunciate$URLFileObject[file:/C:/Projekt/vn4new/skotsel/server/uppf/uppf-web/src/main/java/com/metria/vn/sidos/uppf/
web/model/Atgard.java]:11:38 /C:/Projekt/vn4new/skotsel/server/uppf/uppf-web/src/main/java/com/metria/vn/sidos/uppf/web/model/Atgard.java:11: error: package com.metria.vn.sidos.upp
f.model does not exist_

and finally:

_ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.5.0:assemble (default) on project uppf-web: Enunciate compile failed. -> [Help 1]_

I changed the following line in ConfigMojo.java from:

```
/**
 * List of all supported packaging types
 */
private static final List<String> SUPPORTED_TYPES = Arrays.asList("jar", "bundle", "eclipse-plugin");

```
to:
```
  /**
   * List of all supported packaging types
   */
  private static final List<String> SUPPORTED_TYPES = Arrays.asList("jar", "bundle", "eclipse-plugin", "ejb", "ejb-client");

```
After that the plugin works as expected.

**Comment by stoicflame** [comment]
Thanks for the report. Assigned to 2.6.

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
