### ISSUE TITLE
@returnWrapped for a list of objects

### ISSUE THREAD

**Issue by jrodmier** [stoicflame/enunciate#455]
Hello, I try to use the annotation @returnWrapped and I need to specify a list of custom objects (List<Study>). How can I do it?

Thanks.

JR.

**Comment by stoicflame** [comment]
You can't right now. I'll look into enhancing it.

**Comment by stoicflame** [comment]
At d2eed2e, support for declaring array "[]" was added, e.g.:

```java
/**
 * @returnWrapped com.mycompany.MyObject[]
 */
```

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
