### ISSUE TITLE
endpoint description in the grouped resource overview missing

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#456]
Hi.

I'm using enunciate 2.5.0 to generate my documentation for my JAX-RS endpoint interfaces and DTOs.
I have descriptions on my interface classes as well as on their methods. When I take a look at the generated resource overview, it currently looks like this:

![screen shot 2016-07-11 at 08 46 47](https://cloud.githubusercontent.com/assets/3257311/16722071/85789328-4744-11e6-83aa-f97f0ece6223.png)

I think this is because enunciate groups all endpoint HTTP methods and doesn't know what to show then - because there is more than one description then. Instead it shows an empty description - which looks weird. I already tried to explain it here:

https://github.com/stoicflame/enunciate/issues/391

But that didn't seem to address my problem :).

I know that the grouping comes from my settings in `enunciate.xml`:

```xml
<jaxrs groupBy="path" />
```

Maybe enunciate could simply take the endpoint interface description which should be "generic" enough to be shown as description for the grouped endpoints instead? WDYT?

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)

**Comment by vguna** [comment]
Hi.

I just re-tested this with 2.6.0 with the same result.

![screen shot 2016-08-24 at 13 32 33](https://cloud.githubusercontent.com/assets/3257311/17929300/d9e70880-69ff-11e6-8700-2189d867babf.png)

Looking at the concrete endpoint documentation, it renders fine. All descriptions are there.
Here's a snippet from my `enunciate.xml` in case it helps to track it down:

```xml
	<modules>
		<!-- document java.util.Date as String instead of number (jackson default) -->
 		<jackson dateFormat="string" />
		<jaxws disabled="true" />
		<swagger basePath="/api/1" />
		<!-- "local" avoids that endpoints are occurring twice in the documentation -->
		<jaxrs groupBy="path" datatype-detection="local">
			<application path="/api/1" />
		</jaxrs>
	</modules>
```

Anything else I could try?

**Comment by stoicflame** [comment]
Yep. Missed a loop condition. Fixed at 63013c9.

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)

**Comment by vguna** [comment]
With 2.7 the interface descriptions now appear in the overview for the endpoints where there are multiple HTTP methods like PUT+POST+GET etc. Thanks for that :)!

But it seems that the description is now taken also for the "single" endpoints where there's only one HTTP method like GET.

That leads to the odd output, that e.g. on the `/orders/{orderId}/status` endpoint from the example above, the general description from the interface is displayed there. Although the endpoint description from `status` would be more precise.

So it would be nice, if there are multiple HTTP methods, take the interface description, if there's only one HTTP method, take the method description.

Does this make sense somehow :)?
