### ISSUE TITLE
add html file instead of adding description enunciate.xml

### ISSUE THREAD

**Issue by Sheshagiri** [stoicflame/enunciate#458]
Hi,
Is there a probability to add a html file(lets say description.html) in the description tag , in enunciate.xml ?

**Comment by stoicflame** [comment]
No, but I can probably add that pretty easily for 2.6.

**Comment by stoicflame** [comment]
```xml
<enunciate>
  <description file="description.html"/>
```

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
