### ISSUE TITLE
Provide summary in Swagger JSON

### ISSUE THREAD

**Issue by dklotz** [stoicflame/enunciate#462]
This is a feature request, at least if I haven't missed any way to currently do this: Currently the "summary" attribute of the operations in the generated swagger.json is empty/unset, which makes the default collapsed view in swagger-ui kind of empty:

![enunciate generated swagger](https://www.dropbox.com/s/qd4hxj9y4v8uc0p/Screenshot%202016-07-19%2015.38.15.png?dl=1)

When using the standard swagger-core annotations it used the value of the ApiOperation annotation to generate a short summary that is shown at the right side of the operations list like this:

![swagger-core generated swagger](https://www.dropbox.com/s/17ib7ljds9hzffs/Screenshot%202016-07-19%2015.43.42.png?dl=1)

It would be awesome if enunciate could allow for a way to automatically set this summary, e.g. from the first sentence of the Javadoc (which would be in line with the default Javadoc HTML processor).

**Comment by stoicflame** [comment]
Sounds like a reasonable request. I'll take a look.

**Comment by stoicflame** [comment]
Fixed at dcfa0d94.

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
