### ISSUE TITLE
IllegalArgumentException when tag contains an empty description

### ISSUE THREAD

**Issue by jlepage-appdirect** [stoicflame/enunciate#463]
I'm getting the following exception when running Swagger2markup with groupBy set to TAGS:

> Exception in thread "main" java.lang.IllegalArgumentException: text must not be blank
> 	at org.apache.commons.lang3.Validate.notBlank(Validate.java:451)
> 	at io.github.swagger2markup.markup.builder.internal.asciidoc.AsciiDocBuilder.paragraph(AsciiDocBuilder.java:91)
> 	at io.github.swagger2markup.markup.builder.internal.AbstractMarkupDocBuilder.paragraph(AbstractMarkupDocBuilder.java:215)
> 	at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.buildsPathsSection(PathsDocumentBuilder.java:162)
> 	at io.github.swagger2markup.internal.document.builder.PathsDocumentBuilder.build(PathsDocumentBuilder.java:140)
> 	at io.github.swagger2markup.Swagger2MarkupConverter.toFolder(Swagger2MarkupConverter.java:175)
> 
 
This seems to be caused by a discrepancy between how `io.github.swagger2markup.internal.utils.TagUtils#getTagDescription` determines what is a present description (based on null) and `io.github.swagger2markup.markup.builder.internal.asciidoc.AsciiDocBuilder#paragraph`, which rather uses `org.apache.commons.lang3.Validate#notBlank(T, java.lang.String, java.lang.Object...)` to determine what is a valid text. 

Swagger configuration:
```
		Swagger2MarkupConfig config = new Swagger2MarkupConfigBuilder()
				.withMarkupLanguage(MarkupLanguage.ASCIIDOC)
				.withPathsGroupedBy(GroupBy.TAGS)
				.withSeparatedDefinitions()
				.build();

```

Version used: 1.0.0

Thx!

**Comment by stoicflame** [comment]
So this issue might have been opened in the wrong project. I'm not seeing any Enunciate issues here...

**Comment by jlepage-appdirect** [comment]
Yes indeed my bad :( this is swager2markup...sorry about the noise!
