### ISSUE TITLE
Enabling Jackson JDK8 module

### ISSUE THREAD

**Issue by mohamnag** [stoicflame/enunciate#464]
We have some objects returned from our JAX-RS resources which have getters with Optional return types. Without [JDK8 module](https://github.com/FasterXML/jackson-datatype-jdk8) enabled, Jackson will not serialise the correct type for such fields. This seems to be the case as we get fields like:
```
{
  "enabled" : true,
  "endDate" : {
    "present" : true
  },
  "startDate" : {
    "present" : true
  }
}
```
in our docs where it should be:
```
{
  "enabled" : true,
  "endDate" : 1234,
  "startDate" : 1234
}
```

Is there a possibility to enable that module in the config XML file?

**Comment by stoicflame** [comment]
I'll look into providing that enhancement. Can you provide a list of classes that need to be supported?

**Comment by mohamnag** [comment]
That would be great. the only thing I'm aware of is the Optional in Java 8. But basically when you enable the JDK8 module as described on the link I gave above, the whole thing is activated.

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)

**Comment by mohamnag** [comment]
@stoicflame great, I just tested it out and it works. Now I have the final types instead of serialized Optional objects.

There is still a thing that could be considered as an improvement in this matter that I just discovered. It would make sense to somehow mark the optional fields. Maybe using a `*` or similar. I have no idea how easy that can be, but it would improve the readability. This can still be cleared in comments of the API and data structure.

**Comment by stoicflame** [comment]
The problem with marking fields as "optional" is that _everything_ would carry that mark because, by default, all JSON/XML fields are optional. Using the `java.util.Optional` is only for programming convenience and doesn't really make any statements about the API.

**Comment by mohamnag** [comment]
In JSON everything is optional, but this tool is generating documentation of a specific API where not everything is optional. Actually one of the base reasons of having `java.util.Optional` is to define on an API what is optional (may be null) and what not.

**Comment by mohamnag** [comment]
however this depends on the style of code that is being used. older code may not really benefit from optional and have simply null checks all over. so arguably not everybody uses (or can use) `java.util.Optional` as it is intended.
