### ISSUE TITLE
Need servlet context path and application server context path to be defined to generate correct api docs and swagger files

### ISSUE THREAD

**Issue by bbarman4u** [stoicflame/enunciate#465]
I have a problem with the servlet path and the application context path not reflecting in the API docs. Example -
* My Web Application Context Path is say "/webapp"
* My Servlet path is say "rest"
* My API base path annotated with @path is say "/path1"
* My actual resource api path annotated with @path is say "/api1"

So my effective path of the rest api that gets excecuted and should reflect in documentation is "/webapp/rest/path1/api1"

Whereas when running the build (am using ant) with the configuration -

The generated docs end up like this "//path1/api1" whereas if I remove the above config it just becomes "/path1/api1". The generated swagger definitions does not even have effect of the above includeApplicationPath configuration.

Note - I have a jersey and spring web application.

Would it be possible to define custom path in the enunciate.xml to at least append the base path like in my above example to what ever we define (if its difficult to derive from various configurations). This was the application document will be fully functional. without having to hand edit the generated docs to update the path every time.

**Comment by stoicflame** [comment]
The configuration you refer to didn't seem to make it into the issue, but this should work:

```xml
<enunciate>
  <application path="/webapp/rest"
</enunciate>
```

**Comment by bbarman4u** [comment]
Hi Sorry I should have copied the full xml file earlier. But as you can see with the below options its still not generating the required paths. Also would it be possible to provide in the documents section a sample enunciate.xml file with some sample configurations instead of the snippet lines so that we include the sections correctly instead of trying to derive the xml from the xsd. I just found out that even misplaced or misconfigured tags can lead to generating the docs recursively and filling up the entire disk space :( In this case it was the swagger tag. 
Please suggest where its going wrong.

<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.5.0.xsd">
	<title>Web Service API</title>
	<description package="">description</description>
	<copyright>copyright</copyright>
	<terms>terms</terms>
	<code-license file="" name="" url="">code-license</code-license>
	<api-license file="" name="" url="">api-license</api-license>
	<contact email="" name="" url="" />
	<application root="http://test.com" />
	<modules>
		
		<jaxrs disabled="false">
			<application path="/webapp/rest" />
		</jaxrs>

	<spring-web datatype-detection="passive" disabled="false"
		groupBy="class" path-sort-strategy="breadth_first">
		<application path="/webapp/rest" />
	</spring-web>

		
		<jackson1 disabled="true" />

	
		<c disabled="true" />
		<csharp disabled="true" />
		<obj-c disabled="true" />

		
		<c-xml-client disabled="true" />
		<csharp-xml-client disabled="true" />
		<java-xml-client disabled="true" />
		<java-json-client disabled="true" />
		<javascript-client disabled="true" />
		<gwt-json-overlay disabled="true" />
		<obj-c-xml-client disabled="true" />
		<php-xml-client disabled="true" />
		<php-json-client disabled="true" />
		<ruby-json-client disabled="true" />
	</modules>
</enunciate>

**Comment by bbarman4u** [comment]
Updating my own question after I identified that i need the above tags along with the includeApplicationPath=true. Also since this did not have any effect on the generated swagger file, for now did a work around by adding the full path name to the application root. Example below and attached.
`
[enunciate.xml.txt](https://github.com/stoicflame/enunciate/files/386875/enunciate.xml.txt)
`
So for now in the generated URL in the swagger try out section comes with the absolute path. Its not the perfect solution as now the path is hard coded and not relative to the application environment. But I hope that in future we would be able to figure out a way to get this handled. 

Also noticed that the try out section was now not executing the request correctly due to the hard coded path, which i need to figure out a way now to work.

**Comment by bbarman4u** [comment]
Further Update: I updated the application root to be a relative path only without the host name and the swagger definitions are now working by taking the relative path. 
Example - <application root="/webapp/rest"/>

**Comment by stoicflame** [comment]
Getting around to looking at this issue again. Is there anything left to be done in the Enunciate code?

**Comment by stoicflame** [comment]
Haven't heard back. I'm going to assume we're good. I'd be happy to re-open if needed.
