### ISSUE TITLE
Module swagger - extension of base param

### ISSUE THREAD

**Issue by luthionb** [stoicflame/enunciate#466]
Is it possible from the parameter base in module swagger to point to an external url resource (for example artifact on nexus)?

`<swagger base="http://nexus/path/to/artifact"/>`

Overriding swagger-ui.zip in a single project is easy, however when we want to use it in a multimodule project then there is no easy&clean solution.

**Comment by stoicflame** [comment]
So that value just gets passed directly to the generated swagger.json; I think the answer to your question depends on how Swagger behaves.

Have you tried it?

**Comment by luthionb** [comment]
Actually that's not the point. According to issue #304 you suggested that if we'd like to modify somehow the swagger files (for example disable external validation by swagger engine or modify css files) we should change that files and provide new archive in the base path of swagger module. If we don't fill the "base" attribute in swagger node the default zip archive generated during the build of enunciate project (you are using the maven-antrun-plugin) is used.

Everything is working fine but we always have to point to the file on local system where the build is performed. As the path is set in enunciate.xml configuration file it has to be somehow present in project we are building (otherwise we would have to point to the build directory what is wrong). And I don't want to keep zip archive or whole directory with modified swagger-ui data in repository for each subproject. That's why I've suggested to give possibility of using URL pointing to valid external resources.

**Comment by stoicflame** [comment]
Oh, I see. I misunderstood what you were talking about.

I'll track this issue as an enhancement request.

**Comment by stoicflame** [comment]
Getting around to addressing this issue.

Currently, if you package up your swagger base and add it to the Enunciate classpath at `/META-INF/enunciate/swagger-base.zip`, Enunciate will automatically pick it up. [Here's an example of a jar that if put on the enunciate classpath will apply a custom swagger base.](https://github.com/stoicflame/enunciate/files/427552/custom-swagger-base.zip)

So for example, if you're using Maven, you have a project that creates the jar described above, then you add that artifact to the Enunciate classpath, e.g.:

```xml
<plugin>
  <groupId>com.webcohesion.enunciate</groupId>
  <artifactId>enunciate-maven-plugin</artifactId>
  <version>${enunciate.version}</version>
  <executions>
    <execution>
      <id>assemble</id>
      <goals>
        <goal>assemble</goal>
      </goals>
    </execution>
  </executions>
  <dependencies>
    <dependency>
      <groupId>com.mycompany</groupId>
      <artifactId>custom-swagger-base</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
</plugin>
```
