### ISSUE TITLE
Ant task should allow setting bootstrapclasspath

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#469]
When "cross-compiling" from JDK8 to JDK7, the bootstrapclasspath needs to be specified, or javac complains.

The Ant enunciate task should allow the boostrapclasspath to be specified, and use it in its operation.

**Comment by stoicflame** [comment]
Thanks for capturing this. Assigned to 2.6.

**Comment by stoicflame** [comment]
Finally getting around to this. Does using the `javacArgument` element not work?

```xml
<enunciate>
  <javacArgument argument="-bootclasspath"/>
  <javacArgument argument="/path/to/rt.jar"/>
```

**Comment by jskovjyskebankdk** [comment]
I did not think of that. I'll try to make the gradle plugin use this for x-compilation.
Not sure I'll be for the 2.6 release, as I'm swamped. But maybe.

I guess we can close this issue. Thanks!
