### ISSUE TITLE
support for Jackson's mix-in annotations

### ISSUE THREAD

**Issue by stoicflame** [stoicflame/enunciate#472]

**Comment by stoicflame** [comment]
Added support at 7052d14:

```xml
<enunciate>
  <modules>
    <jackson>
      <mixin target="com.thirdparty.ExternalClass" source="com.mycompany.ExternalClassMixin"/>
```

Also works for `jackson1` module.

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)

**Comment by vincent-zurczak** [comment]
Great, thanks! :+1:

**Comment by thomasletsch** [comment]
Thanks for the MixIn support. We wanted to use it to tell enunciate that a MongoDB ObjectId (https://github.com/mongodb/mongo-java-driver/blob/master/bson/src/main/org/bson/types/ObjectId.java) with the following MixIn:
public abstract class ObjectIdMixIn {

    @JsonCreator
    public ObjectIdMixIn(String hexString) {
    }

    @JsonValue
    public abstract String toHexString();

}

enunciate.xml:
  <modules>
    <jackson>
      <mixin target="org.bson.types.ObjectId" source="de.kfc.server.api.jackson.mixins.ObjectIdMixIn" />
    </jackson>
</...>

It does unfortunately not recognize the infos in the MixIn. Do I miss something?

Thanks a lot,
Thomas

**Comment by stoicflame** [comment]
Looks like I didn't add include for `@JsonCreator` and `@JsonValue` in the mix-in functionality. Tracking at #490.
