### ISSUE TITLE
Generate operations summary for Swagger files

### ISSUE THREAD

**Issue by vincent-zurczak** [stoicflame/enunciate#476]
When reading generated swagger.json files with Swagger IO, there is no operation summary with what Enunciate generates.

![summary](https://cloud.githubusercontent.com/assets/1104790/17706477/7dc28f1c-63dc-11e6-8120-3e8ab13d3e69.png)

The fix is quite simple and I will submit a PR shortly.

**Comment by stoicflame** [comment]
Fixed with merge at #477.

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
