### ISSUE TITLE
 @XmlEnumValue annotation handling

### ISSUE THREAD

**Issue by gmtwc** [stoicflame/enunciate#478]
Not sure whether this is a bug but here is my question:

I am looking at how the  @XmlEnumValue annotation is handled in the resulting documentation.  The example to demonstrate this may be found in Enunciate source tree in Jackson 2 API Example in the class is GenderType.java and the annotation looks like
...
  @XmlEnumValue("m")
  MALE,
...

In compiled documentation in the JSON section the field is documented as value : "m"  Description: "Male gender"
In XML section it is documented as value: "MALE" Description: "Male gender"

I think the JSON documentation is correct and XML is not.  The @XmlEnumValue annotation forces the run time XML marshaller / demarshaller to honor the "m" value instead of default Enum string value "MALE".

**Comment by stoicflame** [comment]
You need to make sure JAXB annotations are honored:

```
<enunciate>
  <modules>
    <jackson honorJaxb="true"/>
    <jackson1 honorJaxb="true"/>
```

**Comment by gmtwc** [comment]
I just added the json configuration you suggested to the modules section and it did not make any difference.
The resulting JSON documentation is correct and XML is not -- it is still using the default Enum string value.

**Comment by stoicflame** [comment]
Ah. I see. I thought you were talking about the JSON docs.

Thanks for the report.

**Comment by stoicflame** [comment]
[Enunciate 2.6 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.6.0)
