### ISSUE TITLE
Client side code is generated only for one endpoint

### ISSUE THREAD

**Issue by Sheshagiri** [stoicflame/enunciate#479]
Hi,

I have 4 endpoints(JAXRS) and looks like the client side code(Only Java JSON Client is enabled in enunciate.xml) is being generated only for the first endpoint(in alphabetical order). Enunciate generates the client side code only for one endpoint or I'm missing something because of which the client side code is generated only for one endpoint ? Any help would be appreciated.

**Comment by stoicflame** [comment]
Enunciate doesn't generate client-side code for endpoints; it only generates the model classes for each of the endpoints you're exposing.

So are you saying that the model classes are only generated from one of multiple endpoints? I'm going to need some more details to see what's going on. What do the endpoints look like? What are you expecting to be generated that isn't being generated?

If you can provide a sample project that illustrates the problem, that will bring this to a quicker resolution.

**Comment by Sheshagiri** [comment]
Enunciate is generating model classes for all the end points I have.

But it seems to be generating the sample client side code(Java json) that
is available in files and libraries link, for one endpoint only(for first
one in alphabetical order).

I can provide a sample project if required.

**Comment by stoicflame** [comment]
Are you talking about the _documentation example_?

![enunciate-479-screenshot](https://cloud.githubusercontent.com/assets/145838/17863647/a9076f24-6857-11e6-81a3-1dd283160443.png)

Enunciate only generates one documentation example. It's intended to give the user an _example_ of how to use the client-side code. I know of no client-side code that is generated for the endpoint; only documentation.

**Comment by Sheshagiri** [comment]
Yes about the documentation example.

Is there a way to generate the documentation example for all the endpoints ?

**Comment by stoicflame** [comment]
No.

Again, it's just documentation; it's not "real" code.

At #257, there's a request to generate the client-side artifacts for the service interfaces, so you're welcome to track that. But it's quite a bit of work so until someone is willing to sponsor that project, it probably won't get much traction.
