### ISSUE TITLE
Ability to show capture expressions

### ISSUE THREAD

**Issue by plessbd** [stoicflame/enunciate#48]
In our REST api we are using capture expressions on the path

/resource/v2/user/{userBy: (id|name)}/

The capture regular expressions do not get translated into the documentation.  Is this by design or is there an option I am missing that will allow me to make this show up?

Or an annotation that would allow me to specify a valid list of options for some of these?

If this could be done then it would be useful to have the ability to put this into the swagger resource files with an enum type allowing for swagger to have a drop down of the possible options

**Comment by stoicflame** [comment]
Fixed at cf91670; will be included in 2.1.

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)
