### ISSUE TITLE
Using enunciate without packaging jackson-databind into my application

### ISSUE THREAD

**Issue by cbridi** [stoicflame/enunciate#482]
We're using enunciate to generate swagger documentation of our REST APIs, which are written using just the standard JAX-RS annotations. One of our methods is annotated with @GET (say, getUser) and returns a JavaBean (say, User) without any annotation (just properties, getters and setters). We have noticed that if our project misses the jackson-databind dependency, then the swagger documentation fails to document properly the return of getUser. If jackson-databind is present, it documents the returning JSON correctly. If it is missing, it states that the method returns a String, which doesn't sound right.

Everything works OK, but we would like our project to depend on jackson-databind, since it is not really a dependency of our project, and we just put it there to generate the swagger documentation properly. All the examples in the source code at which we looked do reference in some way the enunciate plugin in the project dependencies. We also have tried without success adding the jackson-databind dependency just for the enunciate plugin, but the JSON generated was incorrect as if we didn't place the jackson-databind reference. We also tried to add the enunciate-jackson dependency, without success either. We tried to pass the following project-extension configuration to the plugin:
```
<project-extensions>
    <extension>jackson</extension>
</project-extensions>
```
Also without success.

Is it possible to run the enunciate plugin without having our project reference any jackson dependency? After all those attempts, we've realized that we don't know this, and given all the documentation and code at which we looked, we could not say.

If it is not currently possible, is this an issue that could be addressed?

**Comment by stoicflame** [comment]
By default, the Jackson module only activates when the `jackson-databind` library is on the classpath. You can force-enable the Jackson module using Enunciate configuration:

```xml
<enunciate>
  <modules>
    <jackson disabled="false"/>
```

The `string` data type is Enunciate's best guess as to what Swagger wants when there's no object model and a text-based media type is used.

I'm curious: if you're using an object model to read/write JSON, how do you do that without the `jackson-databind` library?
