### ISSUE TITLE
Duplicate description on endpoint

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#483]
Hi.

I'm using 2.6.0 to generate documentation from my JAX-RS endpoint interfaces.
For some endpoints, it seems that it renders the description twice, like shown here:

![screen shot 2016-08-24 at 13 44 58](https://cloud.githubusercontent.com/assets/3257311/17929546/70ca472a-6a01-11e6-9f94-d671b5060cd2.png)

This is the interface definition:

```java
/**
 * This is the central entry point for the Pet-Store REST service. From here, all major endpoints are reachable.
 *
 * @author vguna
 */
@Path(PetStoreService.RESOURCE_PATH)
public interface PetStoreService {

	String RESOURCE_PATH = "/";
	String STATUS_PATH_PARAM = "status";

	/**
	 * Gets the status of the system.
	 *
	 * @return the status of the system.
	 */
	@GET
	@Produces(MediaType.APPLICATION_JSON)
	@Path(STATUS_PATH_PARAM)
	String getStatus();
...
```

This interface also contains other methods that are directly assigned to this resource path but their description is ok. Maybe the `@Path`on interface _and_ method triggers this effect?

BTW: this is not a regression. It also happened with the versions before - just didn't find time to report it.

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
