### ISSUE TITLE
swagger module support for bean validation annotations

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#484]
Hi.

I'm currently testing the new Java Bean Validation annotation support in 2.6.0. I really like it! A huge step forward in providing precise information to the clients.

But I encountered, that this information is missing from the swagger models :). I guess swagger supports displaying such information in general?

**Comment by stoicflame** [comment]
I can see that swagger supports the following constraints:

* maximum
* exclusiveMaximum
* minimum
* exclusiveMinimum
* maxLength
* minLength
* pattern
* maxItems
* minItems

Are there any others?

**Comment by vguna** [comment]
I think that's it...

**Comment by stoicflame** [comment]
I added support for it in the generated swagger.json, but Swagger's UI didn't seem to do anything with it other than document the constraints on the properties, so I'm not sure how much value it provided.

**Comment by vguna** [comment]
Sounds good to me. Thanks!

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
