### ISSUE TITLE
Support for new Spring Annotations

### ISSUE THREAD

**Issue by juergenzimmermann** [stoicflame/enunciate#486]
Since Spring 4.3.0-RC1 (April 2016) there are a few simplifying annotations in addition to e.g. `@RequestMapping(method = GET)`. Can you also support these annotations?

- `@GetMapping` matches `@RequestMapping(method = GET)`
- `@PostMapping` matches `@RequestMapping(method = POST)`
- `@PutMapping` matches `@RequestMapping(method = PUT)`
- `@PatchMapping` matches `@RequestMapping(method = PATCH)`
- `@DeleteMapping` matches `@RequestMapping(method = DELETE)`

These new annotations are also in the Java package `org.springframework.web.bind.annotation`

**Comment by stoicflame** [comment]
Okay.

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
