### ISSUE TITLE
Wrong encoding for generated .xsd-file (should be UTF-8)

### ISSUE THREAD

**Issue by schteff** [stoicflame/enunciate#488]
Hi!

The .xds-file in my /docs seems to be generated in ISO-8859-1 even though it says `<?xml version="1.0" encoding="UTF-8"?>` in the header. 

This makes my IDE (eclipse) flag the documentation CDATA text with `Invalid byte 2 of 3-byte UTF-8 sequence.` errors where åäö-characters should be (i'm Swedish). 

Hope it's a simple fix, maybe a filewriter with a missing encoding parameter or something :)

**Comment by stoicflame** [comment]
I'm afraid I can't reproduce this issue.

The current examples include some UTF-8 characters, e.g. [Name.java](https://github.com/stoicflame/enunciate/blob/master/examples/full-api-edge-cases/src/main/java/com/webcohesion/enunciate/examples/jaxwsrijersey/genealogy/data/Name.java). See the Japanese characters in the JavaDoc.

When generating the xsd, those characters are encoded correctly, and my file utilities all confirm that the xsd is utf-8:

```
$ file -bi ns0.xsd
application/xml; charset=utf-8
```
