### ISSUE TITLE
Swagger UI is not rendered correctly for endpoints with @Consumes(MediaType.APPLICATION_FORM_URLENCODED)

### ISSUE THREAD

**Issue by dariokures** [stoicflame/enunciate#492]
Hi,

I'm testing migration from Enunciate 2.3 to 2.6 for my jax-rs api.
It seems that Swagger UI is not generated correctly if REST resource consumes "application/x-www-form-urlencoded" request.
For example:
```java
@Path("test")
public class TestResource {    
    public enum MyEnum { VALUE1, VALUE2 }

    @POST
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    @Produces(MediaType.TEXT_PLAIN)
    public String test(
            @FormParam("string") String str, 
            @FormParam("int") Integer intg, 
            @FormParam("double") Double dbl,
            @FormParam("bigdecimal") BigDecimal bigdec,
            @FormParam("date") Date date, 
            @FormParam("bool") Boolean bool,
            @FormParam("enum") MyEnum myenum) {
        
        return "test";
    }
}
```
Generated UI:
![swagger](https://cloud.githubusercontent.com/assets/15244496/18173890/b947167a-706b-11e6-953a-e0ae591ea866.png)

Note that there is "Browse" button for "bigdecimal" and "date" parameters(in 2.3 they are rendered as text fields).
Also, there is additional "body" parameter which doesn't have any function.
And curl example contains wrong header (--header 'Content-Type: multipart/form-data').

Btw, is there any option to render parameters in Swagger UI in the same order as declared in java class?

Thanks

**Comment by stoicflame** [comment]
Okay, thanks for the report.

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
