### ISSUE TITLE
@XmlTransient, configuration and generated documentation

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#493]
I'm working on a REST API. One of the entities which the REST API accepts is the below `SerialCar`. The idea here is that `Car` comes from a project which I can not modify and I thus need to implement the corresponding shallow / unimplemented `SerialCar`  entity for the purpose of generating the REST API documentation. 

Why do I do this? I need to add annotations to the entity classes (hide some elements etc.) and the `Car` entity comes from a different project which I can not modify.

Now, since `SerialCar` implements `Car` it will also need to implement the `public Engine getEngine()` method. However, I'd like the users of this API to only know of a corresponding `public SerialEngine getEngine()`. The way I do this is by annotating `public Engine getEngine()` with `@XmlTransient`. Great, end users no longer have any concept of the `Engine` entity. Then, it's just a matter of adding the corresponding `public SerialEngine getSerialEngine()` method and annotate that method with `@XmlElement(name="engine")`. 

Done! Works great! Looking at the generated documentation for `SerialCar` produced by Enunicate it works as I'd like it to.

**However**! When I now generate the REST API documentation both `SerialCar` and `Car` will appear in the list of  Data Types. It appears that `@XmlTransient` have no effect upon the generation of this list.

The [Enunciate User Guide](https://github.com/stoicflame/enunciate/wiki/User-Guide) states that I can exclude certain classes by using the `api-classes > exclude` directive. However, where do I control these settings? The User Guide makes no mention of how I apply the configuration options described. 

Anyway, what I would like to achieve is to have Enunciate ignore the entity classes which comes from the other library, and only mention the shallow implementations I've made for the purpose of documentation.

```
public class SerialCar implements Car {
    
    @XmlTransient
    @Override
    public Engine getEngine() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @XmlTransient
    @Override
    public void setEngine(Engine engine) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @XmlElement(name="engine")
    public SerialEngine getSerialEngine() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @XmlElement(name="engine")
    public void serSerialEngine(SerialEngine engine) {
        throw new UnsupportedOperationException("Not supported yet.");
    }   

}
```

**Comment by stoicflame** [comment]
Thanks for the report. I'm not sure why `Car` appears in the data types. I'll take a closer look for 2.7.

**Comment by sbrattla** [comment]
Thanks!

**Comment by stoicflame** [comment]
I'm afraid I can't reproduce this problem; interfaces are totally ignored as JAXB data types. I'd be happy to re-open this if you can provide me with an example project that exposes the issue.

I can also suggest an alternative approach: I think you can use [`@XmlJavaTypeAdapters`](http://docs.oracle.com/javaee/5/api/javax/xml/bind/annotation/adapters/XmlJavaTypeAdapters.html) on the package to be able to "adapt" any interfaces to a class that binds them.

**Comment by sbrattla** [comment]
Turns out it was my fault. A resource class had `@TypeHint(Engine[].class)` instead of `@TypeHint(SerialEngine[].class)`. This, again, resulted in a rather large graph of classes to unintentionally be included in the documentation. Really sorry for wasting your time on this...
