### ISSUE TITLE
@RequestBody data type

### ISSUE THREAD

**Issue by Delwing** [stoicflame/enunciate#497]
Hey,

I am using Enunciate 2.6.0.
I've got problem with parameter using Spring Annotation `@RequestBody` and method is annotated with `@RequestMapping(value = "convert", method = RequestMethod.POST, consumes = "application/json", produces = "application/json")`
Documentation doesn't read its proper type. It says (custom type), even when I use `@TypeHint` annotation (which I would also like not to use, since model class is used and when I've used JaxRS it was working as it should).

Am I'm doing something wrong?

**Comment by stoicflame** [comment]
What does the method signature look like?

**Comment by Delwing** [comment]
`@RequestMapping(value = "convert", method = RequestMethod.POST, consumes = "application/json", produces = "application/json")`
`public String convert(@PathVariable("listingId") int listingId, @RequestBody ListingInfo listingInfo)`

**Comment by stoicflame** [comment]
I'm afraid I can't seem to reproduce the issue.

When I apply [this patch](https://github.com/stoicflame/enunciate/files/472525/enunciate-497.diff.txt) attempting to mirror when you're doing, I see the request body show up appropriately documented.

![enunciate-497](https://cloud.githubusercontent.com/assets/145838/18518582/cc1e0758-7a5d-11e6-9515-71a02d1ed607.png)

**Comment by stoicflame** [comment]
Bump. Any updates? Can you provide me a way to reproduce this issue?

**Comment by stoicflame** [comment]
Still haven't heard back. I'm going to close this for now; I'm happy to re-open when more information is provided.
