### ISSUE TITLE
Possible bug in PHP XML deserialization

### ISSUE THREAD

**Issue by justincy** [stoicflame/enunciate#500]
This originates from [gedcomx-php](https://github.com/FamilySearch/gedcomx-php/pull/61). I just realized the code fixed in the PR was generated by enunciate.

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
I'm not sure when it was fixed, but [I don't see the undefined static problem anymore](https://github.com/stoicflame/enunciate/blob/master/php-xml-client/src/main/resources/com/webcohesion/enunciate/modules/php_xml_client/client-complex-type.fmt#L358).

I'm happy to re-open this if I'm missing something.
