### ISSUE TITLE
Improve resources summary

### ISSUE THREAD

**Issue by nomisvai** [stoicflame/enunciate#503]
I think there are 2 improvements that might be interesting for our use case at least:

1) we have many very long resource names(depth+name) and when the summary is displayed this pushes the description column out of the screen, I think a simple css tweak to enable word wrap or truncate the resource name in the summary might make the summary more readable. Or maybe a wiki page suggesting how we might tweak our own css/template :).

2) Some of our resource descriptions have many lines, it would be cool if there was a "terseDescriptionSummary" option that would only add the first sentence of the description to the summary instead of the whole thing, when drilling down on the resource they could see the whole description.

**Comment by stoicflame** [comment]
I started looking into this, but it got a bit too messy for general applicability. I'm going to decline changing the default CSS for fear of browser inconsistencies and backwards-compatibility.

However, you should be able to apply some custom CSS to do what you want:

https://github.com/stoicflame/enunciate/wiki/Custom-Skin

You can use [this cool CSS trick](https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/) to truncate text (e.g. applied to the `resource-path` or `resource-description` classes), or to set a max-width for the `td`s of your `resources` table.
