### ISSUE TITLE
 rest defaultRestSubcontext is ignored if module xml is included in <modules>

### ISSUE THREAD

**Issue by echoAlexey** [stoicflame/enunciate#51]
Property:
`<services>`
`<rest defaultRestSubcontext="/whatever" />`
`</services>` 
will be ignored if, for example, module contains `<xml disabled="true"/>` 
Thus resulting mount points for API calls start with `./rest/...` instead of `./whatever/...`

Enunciate version: 1.29

**Comment by stoicflame** [comment]
Fixed at e4b6303.

**Comment by murugaraja** [comment]
In enunciate2 there is no "defaultRestSubcontext" tag element available in enunciate.2.3.0.xsd file, What is the alternate for  "defaultRestSubcontext" in enunciate2.3.0.xsd

**Comment by ronnyfm** [comment]
Same question, how can I configure the generated doc to have a custom prefix, for example, to add /services before each generated URL? Thanks.

**Comment by stoicflame** [comment]
https://github.com/stoicflame/enunciate/wiki/Application-Configuration
