### ISSUE TITLE
Unexpected HTTP status code in swagger output

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#515]
Hi.

I'm using enunciate 2.6.0 for generating swagger documentation from my JAX-RS service interfaces. I encountered a strange behavior with one of my endpoints:

```java
public interface RestaurantResource {

	String RESTAURANT_ID_PATH_PARAM = "restaurantId";
	String RESTAURANT_ID_PATH = "{" + RESTAURANT_ID_PATH_PARAM + "}";

	/**
	 * Gets the masterdata for the restaurant.
	 *
	 * @return the restaurant masterdata.
	 */
	@GET
	@Produces(MediaType.APPLICATION_JSON)
	RestaurantDto get();

	/**
	 * Deletes the specified restaurant.
	 */
	@DELETE
	void delete();

	/**
	 * Updates the restaurant with the specified data.
	 *
	 * @param account
	 *            the login with the updated values (complete, no partial updates!).
	 * @return the updated login.
	 */
	@PUT
	@Consumes(MediaType.APPLICATION_JSON)
	@Produces(MediaType.APPLICATION_JSON)
	RestaurantDto update(RestaurantDto restaurant);
}
```

This renders to the attached swagger output which contains a 201 error code, not defined by the resource at all :).

![screen shot 2016-10-06 at 16 35 23](https://cloud.githubusercontent.com/assets/3257311/19161054/a5a9f284-8bf2-11e6-88bf-59f864bc29aa.png)

Any clue where this might come from?

**Comment by stoicflame** [comment]
I think it should be a 204 instead of a 201, yes?

I'll fix it in 2.7.

**Comment by vguna** [comment]
Normally yes.  I'm a bit unsure whether enunciate should give a default at all :). Does it for other HTTP methods like GET 200, POST 201 etc.? BTW: What is meant with "Unexpected error." :)? It is also printed when custom error codes are defined.

**Comment by stoicflame** [comment]
> Normally yes. I'm a bit unsure whether enunciate should give a default at all :).

Well, the API _has_ to return _some_ status code, whether you implicitly document it or not...

> Does it for other HTTP methods like GET 200, POST 201 etc.?

Yes, it does.

> What is meant with "Unexpected error." :)? It is also printed when custom error codes are defined. 

Just the default catch-all. I'll try to remove it and see what happens.

**Comment by vguna** [comment]
Ah. I see. Ok then, sounds fine!

**Comment by selimok** [comment]
Unexpected error seems quite weird. I vote fore removing that line :)

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
