### ISSUE TITLE
Excluding a specific API from JAX-RS service documentation.

### ISSUE THREAD

**Issue by santhosh-pindi** [stoicflame/enunciate#516]
We are using the following version of enunciate plugin

```xml
  <artifactId>enunciate-slim-maven-plugin</artifactId>
  <version>2.4.0</version>
```

We want to exclude a specific API from JAX-RS service and we were using the facets annotation but it's not working.

## Enunciate XML Content

```xml
<enunciate>
  <modules>
    <docs includeApplicationPath="true"/>
    <jackson1 disabled="true"/>
  </modules>
  <facets>
    <exclude name="skip"/>
  </facets>
<enunciate>
```

## API is annotated with above facets as shown below.

```
@Facet("skip")
```

Please you help with annotation which will exclude specific API from the documentation. Let me know if you need additional information on the same.

**Comment by stoicflame** [comment]
Works for me.

What's the fully-qualified name of the `@Facet` annotation? Make sure you're using `com.webcohesion.enunciate.metadata.Facet` and not `org.codehaus.enunciate.Facet`.

**Comment by stoicflame** [comment]
No response for 2.5 weeks. I'm assuming there's nothing further to do on this issue. I'm happy to reopen as needed.
