### ISSUE TITLE
Problem with XmlAdapter on generic types

### ISSUE THREAD

**Issue by georgebuzoianu** [stoicflame/enunciate#517]
When trying to run the maven plugin I have the following error:

> [ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.6.0:assemble (default) on project myproject-common-ui-facade: payload: adapter com.myproject.ws.adapter.GenericPayloadAdapter does not adapt T: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]

```
@Controller
@RequestMapping(value = "/{language}")
public class ExternalRequestResource  {
...
@Security(...)
@RequestMapping(value = "/request/active/{clientId}", method = RequestMethod.GET, produces = { "application/json"})
public @ResponseBody Request getActiveRequest(@PathVariable("clientId") Long clientId, 
                                       HttpServletRequest httpRequest, 
                                       HttpServletResponse httpResponse)  {
...
Request request = externalRequestService.getActiveRequest(clientId);
...
return request;
}
```

```
public class Request<T extends Payload> {
...
@XmlJavaTypeAdapter(GenericPayloadAdapter.class)
private T payload;
...
}
```

**Comment by rbrn** [comment]
George, can you please add the version that you're using?

**Comment by georgebuzoianu** [comment]
As I said in my first comment is enunciate-maven-plugin:2.6.0

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
