### ISSUE TITLE
@RequestHeaders mapping into swagger json output

### ISSUE THREAD

**Issue by selimok** [stoicflame/enunciate#519]
I have a rest end point which expects a request header to authenticate the caller. To document this I used **@RequestHeaders** annotation as follows : 

![Swagger UI Screenshot](http://i.imgur.com/HNPVZmd.png)

but the request header misplaced in Swagger JSON output (see attached screenshot) and the description is overridden by methods javadoc comments. I expected here that request header **X-XSRF-TOKEN** placed under **Headers** section and not **Parameters**. And as description I expected the same text value as declared in **description** attribute of the **@RequestHeader** a annotation.

![Swagger UI Screenshot](http://i.imgur.com/LUmxjjA.png)

P.S.: The false description appears also on standard enunciate api docs output. 
![Enunciate Screenshot](http://i.imgur.com/mliSsmD.png)

Thank you.

**Comment by stoicflame** [comment]
Okay, so I think the "Headers" section might be for response headers, not request headers. If it's not, I have no idea how to get the request headers in there. But providing the request header as a parameter still gets used in the request, so it seems to be in the right place. If you find otherwise, I'd be happy to re-open this issue.

As for the description getting overwritten, I don't know how to reproduce that. It works for me. If you can provide me a way to reproduce what you're seeing, I'd be happy to re-open this issue.

![screen1](https://cloud.githubusercontent.com/assets/145838/19789292/d0d3b0ec-9c6b-11e6-8f19-43f6afe6cd89.png)

![screen2](https://cloud.githubusercontent.com/assets/145838/19789295/d5428dba-9c6b-11e6-9a87-a293dc46953d.png)

**Comment by selimok** [comment]
Interesting to see that works for you :) I will try it again with jersey and try to understand why it wasn't worked with my spring rest controller. 

Thanks.

**Comment by selimok** [comment]
Hi, 

so I understand that the Headers section is for response header. But this section should be actually showed only when any response header is defined. 

In json output there is a _empty_ headers section: 

```
"responses" : {
          "200" : {
            ...
                "headers" : {
                }
            ...
            }
        }
```

After removing this section no Headers section is shown. 

Should I report this in a new issue? 

Thanks.

**Comment by selimok** [comment]
I checked again the second problem which is works for you. Yes it's works for me too but only if I use standard JAX-RS annotations. 

The problem still exists with Spring Framework. To describe the problem exactly: the javadoc for method replaces headers' description value. 

Interestingly if I place the @RequestHeaders(...) annotation above the javadoc section all my javadoc texts are disappears.

**Comment by selimok** [comment]
Hi, 

actually the problem (spring related) is still there. Can you open this issue again? 

Thx.

**Comment by selimok** [comment]
I checked the implementation of com.webcohesion.enunciate.modules.spring_web.model.RequestMapping class. It seems correctly to map request headers.

**Comment by selimok** [comment]
I found the bug. I will create a pull request for it.

**Comment by selimok** [comment]
When do you plan to release 2.9.0 ? 

Thank you.

**Comment by selimok** [comment]
If 2.9.0 not planned in near future, can you please deploy 2.9.0-SNAPSHOT to oss.sonatype.org/content/repositories/snapshots repository or may be release a bugfix release 2.8.1 ?

**Comment by stoicflame** [comment]
Okay.

https://github.com/stoicflame/enunciate/releases/tag/v2.8.1

**Comment by selimok** [comment]
Thank you very much :)

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
