### ISSUE TITLE
Change the location for enunciate.xml via configFile is not working

### ISSUE THREAD

**Issue by mr678** [stoicflame/enunciate#523]
In my project setup, I tried to move the enunciate configuration file to /src/assembly/enunciate.xml. Without success...

    <plugin>
    	<groupId>com.webcohesion.enunciate</groupId>
	<artifactId>enunciate-maven-plugin</artifactId>
	<version>2.6.0</version>
	<executions>
		<execution>
			<goals>
				<goal>docs</goal>
			</goals>
			<configuration>
				<configFile>/src/assembly/enunciate.xml</configFile>
	
If the enunciate.xml file is located in project root folder, the file is used and the following msg is printed during execution:

    [INFO] [ENUNCIATE] Using enunciate configuration at D:\hero\scm\portfolio\enunciate.xml

For me it looks like that configFile configuration is not used in my setup? Only if a file enunciate.xml is present in root folder it's used all other locations are ignored. 

Do you see something I have to change?

Thanks,
Matthias

**Comment by stoicflame** [comment]
That seems like an absolute path. Do you mean "${basedir}/src/assembly/enunciate.xml"?

**Comment by mr678** [comment]
Hi Ryan (stoicflame),

works exactly as you have described 👍 

Thanks a million for your great support!
