### ISSUE TITLE
enunciate-maven-plugin 2.6.0 does not generate <wadl:param type="template">

### ISSUE THREAD

**Issue by mirvnillith** [stoicflame/enunciate#524]
When generating WADL from a JAX-RS annotated interface, Enunciate 2.6.0 does not generate relevant template parameters:

@Path("v2/courses")
public interface CoursesApi {
	@GET
	@Produces({ MediaType.APPLICATION_JSON })
	@Path("{id}")
	public ExistingCourse findCourseById(
			@PathParam("id") String id) throws Exception;
}

generates

    <wadl:resource path="v2/courses/{id}">
      <wadl:method name="GET">
        <wadl:doc><![CDATA[]]></wadl:doc>
        <wadl:request>
        </wadl:request>
        <wadl:response>
          <wadl:representation mediaType="application/json"/>
        </wadl:response>
      </wadl:method>
    </wadl:resource>

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
