### ISSUE TITLE
default values in generated java client

### ISSUE THREAD

**Issue by sfenollosa** [stoicflame/enunciate#526]
Hi,

@XmlElement(defaultValue="true") is ignored in generated java client. Then, instead of defaulting my boolean attribut to true, the generated object will have a false value.
Is there a way to define default values ?

Regards,

**Comment by sfenollosa** [comment]
Here is an example.
My original class :

@XmlRootElement
public class DefaultValPb {
	private boolean active = true;

	@XmlElement(defaultValue="true")
	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}
}

And the class generated for the java xml client :

@javax.xml.bind.annotation.XmlRootElement (
  name = "defaultValPb",
  namespace = ""
)
public class DefaultValPb implements java.io.Serializable {

  private boolean _active;

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "active",
    namespace = ""
  )
  public boolean getActive() {
    return this._active;
  }

  /**
   * (no documentation provided)
   */
  public void setActive(boolean _active) {
    this._active = _active;
  }

}

As you can see, default value is gone.

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
