### ISSUE TITLE
using @returnWrapped ignores @return text

### ISSUE THREAD

**Issue by saas2813** [stoicflame/enunciate#527]
When the API extract the returntype from the function declaration it includes the @return text as description.

When I include @returnWrapped there is no description included.

E.g.

``` java
    /** 
     * Example
     * @return Some Description
     * @returnWrapped my.own.path.ClassName
     */
```

**Comment by stoicflame** [comment]
I'm afraid I can't reproduce this problem. I apply [this patch](https://github.com/stoicflame/enunciate/files/558669/issue-527.patch.txt) to [enunciate-sample](https://github.com/stoicflame/enunciate-sample) and it works fine for me.

![screen1](https://cloud.githubusercontent.com/assets/145838/19810585/4ac66c80-9ceb-11e6-8996-63e6549a5866.png)

![screen2](https://cloud.githubusercontent.com/assets/145838/19810591/4fc7cd00-9ceb-11e6-9c40-ab999a49401e.png)

**Comment by ahmadshahwan** [comment]
I have the same problem.

Without `@returnWrapped` the comment "ignored" is shown.
With `@returnWrapped` it is indeed ignored. If I add text after `@returnWrapped`, as  the [original doclet](http://fromage.github.io/jax-doclets/docs/0.10.0/html/#d0e538) suggests, the whole doclet is ignored.

I can either have a type directive, or a description, but not both.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
