### ISSUE TITLE
File handle leaks

### ISSUE THREAD

**Issue by allenhadden** [stoicflame/enunciate#528]
I believe that I've found two places where Enunciate is not properly closing opened files.  In my project this causes some files to be opened (and not closed) 10 or more times.  The result for me is an intermittent "Too many files open" operating system error.

I used the "File Leak Detector" (http://file-leak-detector.kohsuke.org/) to help pin down where the problems are occurring.  It revealed the following methods:

Enunciate.java:
```
    @Override
    public CharSequence getCharContent(boolean ignoreEncodingErrors) throws IOException {
      StringBuilder content = new StringBuilder();
      InputStream in = openInputStream();
      byte[] bytes = new byte[2 * 1024];
      int len;
      while ((len = in.read(bytes)) >= 0) {
        content.append(new String(bytes, 0, len, this.encoding));
      }
      return content;
    }
```

The solution to the above issue is to use try-with-resources to close the InputStream (since it's never used outside the method).

and the following (BasicGeneratingModule.java):

```
  public long findSourceTimestamp(DecoratedProcessingEnvironment env, Element apiElement) {
    SourcePosition sp = env.findSourcePosition(apiElement);
    URI uri = sp == null ? null : sp.getPath() == null ? null : sp.getPath().getCompilationUnit() == null ? null : sp.getPath().getCompilationUnit().getSourceFile() == null ? null : sp.getPath().getCompilationUnit().getSourceFile().toUri();
    if (uri != null && "file".equalsIgnoreCase(uri.getScheme())) {
      //it's a file uri.
      try {
        return uri.toURL().openConnection().getLastModified();
      }
      catch (IOException e) {
        return 0;
      }
    }

    return 0;
  }
```

The issue here is a longstanding issue with Java and the use of the FileURLConnection, which is what openConnection() returns when the URL is a file-based one.  Basically, whenever FileURLConnection actually opens the file it uses a FileInputStream that it never closes.  You can see this in the following bug report from 1999 (which was closed as 'Not an Issue'):

http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4257700

The workaround described in that bug is to use knowledge of the inner workings of FileURLConnection and call urlConnection.getInputStream().close().  Because of the absurdity of this recommendation, I'd suggest abandoning the use of openConnection/URLConnection and instead use this code:

```
new File(uri.getPath()).lastModified()
```

**Comment by stoicflame** [comment]
Thanks for the report!

**Comment by stoicflame** [comment]
Thanks again for the report.

**Comment by stoicflame** [comment]
[Enunciate 2.7 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.7.0)
