### ISSUE TITLE
Deprecated fields excluded from Example XML and Example JSON

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#53]
We use the jaxws module of Enunciate. To prevent our API users to use deprecated fields, it would be nice if these fields were excluded from the Example XML and Example JSON outputs. Other parts of the documentation already show deprecated fields with a red background and our JavaDocs states the reason for the deprecation. But for the examples, it would be very nice to exclude them.

**Comment by anton-johansson** [comment]
Would be nice to fix this in v2 as well. Maybe even have this as the default-behaviour now?

**Comment by stoicflame** [comment]
Fixed in v2 at 4dadc50.
