### ISSUE TITLE
Excluding api-classes not working as expected

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#531]
Hi.

I'm trying to exclude a specific class from being added to the REST documentation. Since I only have the jar, I can't use `@Ignore` on it. That's what I have in my enunciate.xml:

```xml
	<api-classes>
		<include pattern="com.acme.service.rest.api.**" />
		<include pattern="com.acme.service.bootstrap.rest.api.**" />
		<!-- exclude explicitly what we don't use -->
  		<exclude pattern="com.acme.service.bootstrap.rest.api.model.MetadataDto" />
	</api-classes>
```

`MetadataDto` still pops up in the documentation. I checked my REST resources if any of them references it, but they don't. I also doublechecked the spelling and package names. `mvn -X` doesn't say anything about why it was included or not excluded.

Any clue what I'm missing?

**Comment by stoicflame** [comment]
What does the output of `mvn -X` say about that class?

**Comment by stoicflame** [comment]
I can't reproduce this issue. When I apply [this patch](https://github.com/stoicflame/enunciate/files/559315/issue-531.patch.txt) to [enunciate-sample](https://github.com/stoicflame/enunciate-sample) the `Blah` data type doesn't show up anywhere.

I'm happy to re-open if you can provide a way to reproduce the issue.
