### ISSUE TITLE
@BeanParam referenced classes aren't documented when exclude/include

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#532]
Hi.

I'm using `@BeanParam` in a resource method like so:

```java
	PagedResultDto<SomeDto> list(@BeanParam QueryParams queryParams);
```

QueryParams:
```java
....
	@QueryParam("q")
	private String query;

	@BeanParam
	private Sorting sorting = new Sorting();

	@BeanParam
	private Paging paging = new Paging();
...
```

When I exclude all classes explicitly via `api-classes` and include `QueryParams` explicitly, I get the documentation for `QueryParams` but not for the classes it references - which are in turn also `@BeanParam`s. I have to explicitly include these as well. 

The same seems to be true for inherited properties. If I explicitly include a subclass, I have to explicitly add the superclass as well.

Is this by design?

**Comment by stoicflame** [comment]
I spent quite a bit of time looking at this to see if we could auto-include sources for classes being _referenced_ by included classes, but in the end I concluded that the classpath/sourcepath scanner just doesn't have enough information to safely include those references automatically. :slightly_frowning_face:
