### ISSUE TITLE
Double quotes in paths for shortcut annotations in Spring

### ISSUE THREAD

**Issue by juergenzimmermann** [stoicflame/enunciate#533]
When I define a mapping with @RequestMapping , e.g. `@RequestMapping(value = "/{id}", method = DELETE)`, then the HTML page shows the path as expected, e.g. `/kunden/v1/{id}`.

However, when I define a mapping with a shortcut annotation, e.g. `@GetMapping("/{id:" + OBJECT_ID_PATTERN + '}')`, then the HTML page shows the path with double quotes, e.g. `/kunden/v1"/{id}"`. Please see the attached screenshot.

![enunciate-html](https://cloud.githubusercontent.com/assets/734334/19827530/a182f080-9dad-11e6-91e4-056ed7ff3ee2.png)

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
