### ISSUE TITLE
Swagger UI error with 2.7.0

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#534]
Hi.

Just took a look at 2.7.0 swagger UI. I am the only one getting:

```
Can't read from server. It may not have the appropriate access-control-origin settings.
```

when calling the swagger UI? Just changing back to 2.6.0 and it works again.

**Comment by vguna** [comment]
Mkay, seems to be the swagger.json. Put it to swagger editor for validation. Looked ok besides some warnings....

**Comment by vguna** [comment]
Ok, I tracked it down to examples containing german umlauts like `ß`. That seems to kill swagger.js with the mentioned error message. For now I can simply use another example. Enunciate own's documentation looks ok though. So should enunciate escape special characters somehow in swagger.json :)?

**Comment by stoicflame** [comment]
So JSON is all UTF-8 encoded. Those characters should be valid in the swagger.json.

Swagger UI bug?

**Comment by vguna** [comment]
Possibly. Tracking it here: https://github.com/swagger-api/swagger-ui/issues/2496

**Comment by stoicflame** [comment]
I can't find any errors on the Enunciate-side of things, so I'm going to close this for now. I'm happy to re-open if needed.
