### ISSUE TITLE
Swagger UI constraint popup disorder

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#538]
Hi.

I'm using Enunciate 2.7.0 to create swagger documentation from my endpoints. Looking at the generated constraint documentation, shows disordered popups like in the image below. Pointing the mouse e.g. to the last attribute of a model, shows all constraints at once, overlapping each other which looks messy. I would expect to show the popup only on the selected attribute to appear. Is this something enunciate specific or more like a swagger bug?

![swaggermess](https://cloud.githubusercontent.com/assets/3257311/20053258/02655eb6-a4d8-11e6-8ff3-76b1f381cfd9.png)

**Comment by stoicflame** [comment]
If this is an Enunciate problem, I can't figure out how to fix it. Any ideas? How does the swagger.json file need to change to fix this?

**Comment by stoicflame** [comment]
Again, I"m going to close this until it's proven to be an Enunciate issue. I'm happy to re-open as needed.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0). An update to the latest Swagger UI might fix this issue.
