### ISSUE TITLE
Is Enunciate compatible with newer swagger-ui versions (e.g. 2.2.6)?

### ISSUE THREAD

**Issue by egemenvardar** [stoicflame/enunciate#541]
I am currently using Enunciate 2.7.0 with a custom instance of Swagger UI, version 2.1.4. Everything works fine there. 

I need to integrate a bugfix in Swagger UI that was released with the 2.2.6 version. I took the whole dist folder from the master branch of swagger-ui project and ran the Enunciate plugin. However, generated  `swagger.json ` file cannot be parsed by the new version anymore:

![enunciate_swagger_incompatibility](https://cloud.githubusercontent.com/assets/17125072/20176285/5d74800e-a747-11e6-84f5-75ac81b5cf38.png)

I saw that Enunciate still uses the 2.1.4 release by default. Is there a compatibility problem with the newer Swagger UI versions? Or am I doing something wrong here?

**Comment by stoicflame** [comment]
Haven't tried it myself, but I can take a closer look for 2.8.

**Comment by stoicflame** [comment]
At 761eeaa I updated to the latest version and everything seemed to be fine.

**Comment by stoicflame** [comment]
Re-opening. I was able to reproduce this error.

**Comment by stoicflame** [comment]
Fixed for me at fbcf5891f997ae30f59efb7ad8982bf0a7598afd.

**Comment by egemenvardar** [comment]
I just tried this again: I downloaded the latest Swagger dist (2.2.8), and generated swagger.json via Enunciate (2.7.0). But I am still getting an error, though this time the error comes from somewhere else:
`cannot parse JSON/YAML content     helpers.js: 18`

Would it help if I attached my generated swagger.json?

**Comment by stoicflame** [comment]
Or just paste it into the [Swagger editor](http://editor.swagger.io/#/) and note what errors you get.

**Comment by egemenvardar** [comment]
Thanks for the tip. I am getting `Duplicated mapping key` error. I will investigate why our json is generated like that (and will create another issue if I find a bug).

**Comment by stoicflame** [comment]
Yes, I got that too. I fixed the duplicate mapping key for the next release.

**Comment by egemenvardar** [comment]
That's great, thank you.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
