### ISSUE TITLE
how to have enunciate request / response examples feature xml rather than json?

### ISSUE THREAD

**Issue by pbelbin** [stoicflame/enunciate#542]
the examples section of the enunciate site currently seems to focus more heavily towards showing json samples.

how do I tell enunciate to show xml examples instead?

thank you!

**Comment by stoicflame** [comment]
You can prefer XML if you want using the `qs` parameter on the media type:

```java
@Produces({"application/xml;qs=1.0", "application/json;qs=0.9"})
```

**Comment by pbelbin** [comment]
I tried your suggestion with 2.7.0, but it doesn't seem to work.  the enunciate examples are still showing json examples rather than xml.

**Comment by stoicflame** [comment]
Okay, I'll treat this as a bug report.

**Comment by pbelbin** [comment]
thank you!  keep up the good work.  I really appreciate your efforts.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
