### ISSUE TITLE
Feature: Ignore non-wanted resource method parameters in JAX-RS support

### ISSUE THREAD

**Issue by victornoel** [stoicflame/enunciate#545]
Hi, I have this kind of resources declared:
```java
@Path("/user")
public class UserSession {

    /**
     * Note: Security is covered by the global filter
     */
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public User getUserData(@Pac4JProfile CockpitProfile profile) {
        LOG.debug("Returning infos for {}", profile.getId());

        DbUser user = profile.getUser();

        return new User(user.username, user.name);
    }
}
```

And the thing is that `@Pac4JProfile CockpitProfile profile` is injected by Jersey into the method.
But since enunciate doesn't know that, it thinks that profile is the message body that should be sent by the client, while actually it should simply ignore it.

It would be great to have a way to state such ignore rules, either by saying `@Pac4JProfile` should always be ignored, or by marking every parameter that should be ignored.

Thanks!

**Comment by stoicflame** [comment]
What is `@Pac4JProfile`? Are there any annotations on that annotation class that indicates it's a specially-provided parameter? What actually provides that parameter when the method is invoked?

You can configure custom resource parameters like this:

```xml
<enunciate>
  <modules>
    <jaxrs>
      <custom-resource-parameter-annotation qualifiedName="com.mycompany.Pac4JProfile"/>
```

**Comment by victornoel** [comment]
@stoicflame ok thanks, will try that, sorry for the issue, I didn't find this information before.

For the record, `@Pac4JProfile` is a custom annotation provided by a jax-rs extension ([jax-rs-pac4j](https://github.com/pac4j/jax-rs-pac4j/)) that injects a security profile for the request

**Comment by victornoel** [comment]
@stoicflame I'm sorry but I don't get it: I added `custom-resource-parameter-annotation` element with the actual qualifiedName of the annotation I use and the parameter is not ignored in the documentation produced.

Are we talking about the same thing?
What I want is to ignore a parameter because it is NOT the request body of the resource method, it is injected by the container, like a `@Context` parameter.

**Comment by victornoel** [comment]
Here is the annotation definition: https://github.com/pac4j/jax-rs-pac4j/blob/master/src/main/java/org/pac4j/jax/rs/annotations/Pac4JProfile.java
It is injected by this: https://github.com/pac4j/jax-rs-pac4j/blob/master/src/main/java/org/pac4j/jax/rs/jersey/features/Pac4JValueFactoryProvider.java

**Comment by stoicflame** [comment]
Woops. Try `custom-system-parameter-annotation` instead of `custom-resource-parameter-annotation`.

**Comment by victornoel** [comment]
It doesn't work… once again, are we sure we are talking of the same thing? :)

From the Java input in the issue description, I get the following output with enunciate (with or without the option you gave me):
![output](https://cloud.githubusercontent.com/assets/160975/20478636/36af4322-afdb-11e6-8987-df83aed15d1d.png)

I am expecting the whole `Request Body` part to be empty.

This is my `enunciate.xml` file:
```
<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.7.0.xsd">
  <modules>
    <jaxrs>
      <custom-system-parameter-annotation qualifiedName="org.pac4j.jax.rs.annotations.Pac4JProfile" />
    </jaxrs>
  </modules>
</enunciate>
```

This is what Maven tells me:
```
[INFO] --- enunciate-slim-maven-plugin:2.7.0:docs (default-cli) @ petals-cockpit-server ---
[INFO] [ENUNCIATE] Using enunciate configuration at /home/vnoel/Linagora/Petals/dev/git/petals-cockpit-new/backend/enunciate.xml
[INFO] Reflections took 1642 ms to scan 136 urls, producing 338 keys and 338 values 
[WARNING] [ENUNCIATE] Some source files were not found for the Java classes that define the Web service API.
[WARNING] [ENUNCIATE] Enunciate will be unable to find the documentation for the classes that are missing source files. (For details, rebuild with debug-level logging.)
[WARNING] [ENUNCIATE] In order for Enunciate to find the source files for API classes that are not being compiled in the current project, the source file must be on the Enunciate sourcepath and the class must be explicitly included in the Enunciate configuration.
[WARNING] [ENUNCIATE] For more information, see https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files
```

(Note that `org.pac4j.jax.rs.annotations.Pac4JProfile` is one of those files that are not available as source file, if it makes any difference…

**Comment by stoicflame** [comment]
Confirmed. Bug.

Fixed at 036b8f5.

Thanks for the report.

**Comment by victornoel** [comment]
great, thanks! I will try to test the development version as soon as I can to confirm all is ok with respect to my use case :)

**Comment by victornoel** [comment]
@stoicflame is it deployed somewhere as a SNAPSHOT or do I need to compile it by hand?

**Comment by victornoel** [comment]
It seems to work well! Thanks :)

Any ETA for the next release?

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
