### ISSUE TITLE
content negotiation and Enunciate 2

### ISSUE THREAD

**Issue by fredespi** [stoicflame/enunciate#546]
Hi,

In https://github.com/stoicflame/enunciate/wiki/Module-Jersey there is a section about content negotiation and I have previously used this information to put something like

```
   <services>
        <rest defaultRestSubcontext="/">
            <content-types>
                <content-type type="application/json;charset=UTF-8" id="application/json;charset=UTF-8"/>
            </content-types>
        </rest>
    </services>
```

into my enunciate config file. Now I am switching to enunciate 2 and need to do something similar. My service consumes and produces content type like the above but the generated docs only mention application/json so interactive calls in Swagger won't work. Thanks.

**Comment by stoicflame** [comment]
The charset has never been needed in the generated documentation, but you're saying that it needs to be there for Swagger to work correctly?

How does Swagger fail if it's not there?

**Comment by fredespi** [comment]
Hi,

I have this in my code: 
```
	@ApiImplicitParams({
		@ApiImplicitParam(name = "apiKey", value = "User's api key", required = true, dataType = "string", paramType = "query"),
	})
	@GET
	@Path("languages")
	@Produces("application/json;charset=UTF-8")
	List<Language> getLanguages() throws Exception;
```
This is what I get in the swagger.json:
```
"\/languages" : {
      "get" : {
        "tags" : [ "GavagaiApi" ],
        "summary" : "This method returns all supported languages.",
        "description" : "This method returns all supported languages",
        "operationId" : "resource_GavagaiApi_getLanguages_GET",
        "produces" : [ "application/json" ],
        "parameters" : [
...
```
No matter what I do, I cannot get the generated swagger.json to change the "produces" value to include the charset. Consequently, when I do my call, I get this:

`curl -X GET --header 'Accept: application/json' 'https://localhost:8180/v3/languages'`

and my api responds with

`{"message":"Please use application/json;charset=UTF-8 for Accept header.","resultCode":"NOT_ACCEPTABLE"}`

Thanks.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
