### ISSUE TITLE
Support for @JsonSerialize @JsonDeserialize

### ISSUE THREAD

**Issue by Ahmed-Hussein** [stoicflame/enunciate#547]
I see that there's support for fasterxml @JsonIgnore and it is reflected in both documentation and client libraries. Is there any support for @JsonSerialize and @JsonDeserialize annotations?
I tried using these annotations to generate different request and response fields for the same bean but the annotations got Ignored. 

For example:
```
@JsonSerilalize
public String getFullName(){...}
```
The generated client lib would contain
```
@JsonDeserilalize
public String getFullName(){...}
```
The generated documentation would contain
> Request
> { 
> "..." : "..."
> }

> Response
> {
> "fullName" : "...",
> "..." : "..."
>}

**Comment by stoicflame** [comment]
Yes, there's support for `@JsonSerialize`, but it's used to configure Jackson with custom (de)serialization aspects. The way you're using it above is incorrect, AFAIK.

Do you mean `@JsonProperty`?
