### ISSUE TITLE
how to restrict generation of documentation to current maven module

### ISSUE THREAD

**Issue by nfalco79** [stoicflame/enunciate#548]
Hi Ryan, our project it's a maven multi module project.
Each module (plugin) has some REST services and could be distribuited separatly.
Actually I can not find a way to generated only documentation of current module excluding service from dependencies (also from same groupId).
I've try to use source-includes with no luck, maybe designed for different use cases. Use api-classes exclude/include directive it's very hard to manage different rules for each module.

Could you please put us on the right way?
Is there some not documentationed feature to enable documentation only for currect module excluding transitive dependencies?

Thank you

**Comment by stoicflame** [comment]
Try using the `datatype-detection` attribute:

```xml
<enunciate>
  <modules>
    <jaxrs datatype-detection="local"/>
```

**Comment by nfalco79** [comment]
The trick does not works alone

For the goal I have also have to configure enunciate sourcepath-exclude as the follow:
```xml
<plugin>
	<groupId>com.webcohesion.enunciate</groupId>
	<artifactId>enunciate-maven-plugin</artifactId>
	<configuration>
		<sourcepath-excludes>
			<sourcepath-exclude>
				<groupId>${project.groupId}</groupId>
			</sourcepath-exclude>
		</sourcepath-excludes>
	</configuration>
</plugin>
```
