### ISSUE TITLE
property sort order

### ISSUE THREAD

**Issue by haakoni** [stoicflame/enunciate#549]
Hi, 

I'm wondering if there is a way to sort the order of properties by source line position and not alphabetically? the example xml output follows the @XmlType(propOrder) if set, or source line position, but the name/description list of properties is always alphabetically:

![sort](https://cloud.githubusercontent.com/assets/23738215/20622606/f505995e-b303-11e6-8947-7a0dd01ae631.png)
    
from code
```java
    /**
    Object needed to authenticate access to the system
    */    
    @XmlAccessorType(XmlAccessType.PUBLIC_MEMBER)    
    @XmlType(propOrder = { "username", "password" } )
    public class User {
        
        /**
        Username for the user
        */
        @XmlElement(required=true)
        public String username;

        /**
        Password for the user
        */
        @XmlElement(required=true)
        public String password;
    }
```

I'm using enunciate 2.7.0

Also, thank you for creating this excellent project!

**Comment by stoicflame** [comment]
If you're using `propOrder`, it shouldn't be alphabetical. I'll take a look for 2.8.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
