### ISSUE TITLE
Can Enunciate take Java Interface as data types?

### ISSUE THREAD

**Issue by ahmadshahwan** [stoicflame/enunciate#551]
Enunciate seems to ignore Java interfaces when looking for potential data types, with the following message:
>[DEBUG] [ENUNCIATE] com.example.IAuthentication isn't a potential Jackson type because it's not a class or an enum.

An example JAX-RS annotated resource goes something like this:

```
@POST
@Produces({MediaType.APPLICATION_JSON, MediaType.TEXT_XML})
@Consumes({MediaType.APPLICATION_JSON, MediaType.TEXT_XML})
public IAuthentication login(CLogin aLogin) throws XException {
    return this.pManager.authenticate(aLogin);
}
```

IAuthentication is an interface, and it has to remain one. This is because I use injection, and I cannot predict the exact type returned by the method `authenticate()`. `CLogin` however is a class, and it is OK since it is a specialisation of the type that method `authenticate()` accepts as parameter.

Now my problem is that only **Request Body** is document in the Enunciate-generated documentation, and not the **Response Body**. 
My interfaces are annotated with JAXB annotations. They are accessible form the source path.

```
@XmlRootElement
public interface IAuthentication {
}
```

Is there a way to tell Enunciate that Java interfaces are OK as data types and must be taken into account.

**Comment by stoicflame** [comment]
No, but you can use the `@TypeHint` annotation to tell Enunciate what data type you want it to document as being returned from the `login` method.

https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations

**Comment by ahmadshahwan** [comment]
Thanks for the answer.
For the record, I use `@returnWrapped` doclet to avoid external dependancies.
