### ISSUE TITLE
TypeHint of Array not using Array notation in JSON

### ISSUE THREAD

**Issue by scottalanweber** [stoicflame/enunciate#552]
When an array of objects is included in the TypeHint annotation, the description is accurately being displayed as an array of the given object. However, in the JSON example the array notation is not noted, instead it's just single object. See the screenshot below.

<img width="1541" alt="screen shot 2016-11-28 at 11 42 18 pm" src="https://cloud.githubusercontent.com/assets/11204885/20732104/570fa7d6-b64a-11e6-965b-d20180b29934.png">

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
