### ISSUE TITLE
jaxws generation trying to generate Exception class, getting circular dependency

### ISSUE THREAD

**Issue by gregbarton** [stoicflame/enunciate#553]
enunciate-maven-plugin 2.7.0

I have a JAXB service definition method that throws java.lang.Exception, and when enunciate runs in maven I get the following error:

[INFO] [ENUNCIATE] No Jackson JSON data types: Java JSON client will not be generated.
/home/greg_barton/git/tier4/tier4-lash-api-1.0/target/enunciate/java-xml-client/src/java/lang/Exception.java:14: error: cyclic inheritance involving Exception
public class Exception extends Exception {
       ^
/home/greg_barton/git/tier4/tier4-lash-api-1.0/target/enunciate/java-xml-client/src/java/lang/Exception.java:15: error: modifier private not allowed here
  private java.lang.jaxws.ExceptionBean faultInfo;
                                        ^
/home/greg_barton/git/tier4/tier4-lash-api-1.0/target/enunciate/java-xml-client/src/java/lang/Exception.java:44: error: modifier private not allowed here
  private java.lang.String message;
                           ^
/home/greg_barton/git/tier4/tier4-lash-api-1.0/target/enunciate/java-xml-client/src/java/lang/Exception.java:11: error: annotation type not applicable to this kind of declaration
@javax.xml.ws.WebFault (
^
/home/greg_barton/git/tier4/tier4-lash-api-1.0/target/enunciate/java-xml-client/src/com/transengen/tier4/api/impl/Tier4LashAPIImpl.java:30: error: incompatible types: MalformedURLException cannot be converted to Throwable
    catch (java.net.MalformedURLException e) {
                   ^
/home/greg_barton/git/tier4/tier4-lash-api-1.0/target/enunciate/java-xml-client/src/com/transengen/tier4/api/impl/Tier4LashAPIImpl.java:31: error: no suitable constructor found for IllegalStateException(MalformedURLException)
      throw new IllegalStateException(e);
            ^
    constructor IllegalStateException.IllegalStateException(String) is not applicable
      (argument mismatch; MalformedURLException cannot be converted to String)
    constructor IllegalStateException.IllegalStateException(Throwable) is not applicable
      (argument mismatch; MalformedURLException cannot be converted to Throwable)
Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output

If I change java.lang.Exception to a custom exception class the error goes away, but unfortunately I can't do that. (Client can't change how they're calling the service.)  Is there some way I can get enunciate to not generate target/enunciate/java-xml-client/src/java/lang/Exception.java?

**Comment by gregbarton** [comment]
Here is the java code generated:

```
/**
 * 
 *
 * Generated by <a href="http://enunciate.webcohesion.com">Enunciate</a>.
 */
package java.lang;

/**
 * (no documentation provided)
 */
@javax.xml.ws.WebFault (
  faultBean = "java.lang.jaxws.ExceptionBean"
)
public class Exception extends Exception {
  private java.lang.jaxws.ExceptionBean faultInfo;

  public Exception(String message, java.lang.jaxws.ExceptionBean faultInfo) {
    super(message);
    init(faultInfo);
    if (message != null) {
      this.message = message;
    }
  }

  public Exception(String message, java.lang.jaxws.ExceptionBean faultInfo, Throwable cause) {
    super(message, cause);
    init(faultInfo);
    if (message != null) {
      this.message = message;
    }
  }

  protected void init(java.lang.jaxws.ExceptionBean faultInfo) {
    setMessage(faultInfo.getMessage());
  }

  /**
   * The fault info for this exception.
   */
  public java.lang.jaxws.ExceptionBean getFaultInfo() {
    return this.faultInfo;
  }

  private java.lang.String message;

  /**
   * (no documentation provided)
   */
  public java.lang.String getMessage() {
    return this.message;
  }

  /**
   * (no documentation provided)
   */
  public void setMessage(java.lang.String message) {
    this.message = message;
  }

}
```

And the problem line is 
```
public class Exception extends Exception
```

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by gregbarton** [comment]
I'm curious, wouldn't this prevent the bug?

https://github.com/stoicflame/enunciate/blob/master/jaxb/src/main/java/com/webcohesion/enunciate/modules/jaxb/JaxbModule.java#L167

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
