### ISSUE TITLE
Hide all possible enums

### ISSUE THREAD

**Issue by piotrboczkowski** [stoicflame/enunciate#555]
Hi,
In my rest interface all classes contain an enum field (resourceType) which describes a type of the resource in the application.
The generated model becomes a bit unreadable because there are more than 60 resources.
Please check:
<img width="980" alt="image" src="https://cloud.githubusercontent.com/assets/24410096/20924526/16ec584e-bbb2-11e6-8a3f-64e03b6102f6.png">

Is it possible to hide the actual available Enum values? I tried applying @Ignore on the field or enum but it's not working.

Or at least moving the available enum values to a separate place instead of putting it inline?

**Comment by stoicflame** [comment]
I agree that's kind of ugly.

Just thinking out loud: how much of this should be addressed by the Swagger UI guys? What if Swagger UI truncated the list or something?

I'll look into it.

**Comment by stoicflame** [comment]
I couldn't figure out how to tell Swagger to truncate the list.

The best I could come up with is to tell Enunciate to treat the field as a String by applying `@TypeHint(String.class)` to the field.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0). This issue may be fixed in the latest Swagger UI version.
