### ISSUE TITLE
Fix the bean validation popup

### ISSUE THREAD

**Issue by piotrboczkowski** [stoicflame/enunciate#556]
The bean validation popup seems to be displayed on any property even if not annotated with the bean validation annotations.

Please see:
<img width="226" alt="image" src="https://cloud.githubusercontent.com/assets/24410096/20925870/b16def66-bbb9-11e6-963a-630fd699f1e4.png">

The popup is displayed when hovering the mouse over each of the two bottom fields even though those are not annotated with the bean validation annotations. The only annotated field is the upper one ("name"). Additionally the two fields at the bottom are not even of type string.
This is the relevant part of the DTO implementation:
<img width="501" alt="image" src="https://cloud.githubusercontent.com/assets/24410096/20926465/aa58e66a-bbbc-11e6-9368-f15696a02570.png">

Is there any solution for this issue?

**Comment by stoicflame** [comment]
Will be fixed in 2.8 with update to Swagger 2.2.8.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
