### ISSUE TITLE
Add response codes to application.wadl

### ISSUE THREAD

**Issue by j-be** [stoicflame/enunciate#559]
Hi,

I noticed the `@StatusCodes` are not added to the generated application.wadl file, even though WADL would allow them.

We currently use Enunciate (and others) to generate the application.wadl files for our various APIs and include them in a single website as an API documentation. We use a heterogeneous system and WADL seems to be the way to integrate with multiple programming languages.

Apart from that: Great framework, keep up the good work.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
