### ISSUE TITLE
Add @documentationType annotation and doclet

### ISSUE THREAD

**Issue by lbndev** [stoicflame/enunciate#560]
Forked from #495 : Add documentationType doclet and annotation so writing : 
```java
@Path("/PetStore")
public interface IPetStore {
    /**
     * Adopt a new pet (Cat or Dog)
     * @returnWrapped Pet
     * @documentationType Cat
     */
    @GET @Path("/adopt")
    public Response adopt();
}
```
would lead to /PetStore/adopt documented with a Pet return type and a Cat as an example (of course Cat must extend Pet).

**Comment by lbndev** [comment]
Awesome, thank you very much ! :)

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
