### ISSUE TITLE
Missing JSON properties with @XmlType(propOrder = { .. }) and @XmlAttribute

### ISSUE THREAD

**Issue by sfussenegger** [stoicflame/enunciate#565]
I'm using JAXB and Jackson modules (`honorJaxb="true"`) and it seems that some - not all - properties with `@XmlAttribute` are missing from the example and properties thable in the documentation if `@XmlType(propOrder = { .. })` is specified

**Comment by stoicflame** [comment]
I'll take a look.

If you can provide more details about the circumstances, that would be helpful.

**Comment by sfussenegger** [comment]
see [molindo/enunciate-565-example](https://github.com/molindo/enunciate-565-example)

run `mvn package` and compare `target/docs/apidocs/json_Tweet.html` with `target/docs/apidocs/xml_ns0_tweet.html`

---

XML properties:

name | data type | type | namespace | min/max occurs | constraints | description
---|---|---|---|---|---|---
date | dateTime | attribute |  | 1/1 |   |  
id | string | attribute |  | 1/1 |   |  
user | string | attribute |  | 1/1 |   |  
message | string | element |  | 1/1 | required |  
url | URL | element |  | 0/1

JSON properties

name | data type | description
---|---|---
date | number | 
message | string | 
url | string |

Tweet class:

```
@XmlRootElement
@XmlType(propOrder = {"message", "url"})
public class Tweet {

    private String id;

    private String user;

    private Date date;

    private String message;
    
    private URL url;

    @XmlAttribute(required = true)
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @XmlAttribute(required = true)
    public String getUser() {
        return user;
    }

    @XmlAttribute
    public void setUser(String user) {
        this.user = user;
    }

    @XmlAttribute(required = true)
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @XmlElement(required = true)
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public URL getUrl() {
        return url;
    }

    public void setUrl(URL url) {
        this.url = url;
    }
}
```

**Comment by sfussenegger** [comment]
a viable workaround is to add all attributes to `propOrder`

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
