### ISSUE TITLE
Methods not sorted in detailed view

### ISSUE THREAD

**Issue by VaclavPokorny** [stoicflame/enunciate#568]
I use version 2.7.0 and methods do not appear to be sorted alphabetically (or in any way I can recognize) in HTML documentation. I would expect methods to be sorted the same way as on index page. Or is there any switch which controls this?

**Comment by stoicflame** [comment]
Which methods? Are you talking the REST docs or the SOAP docs?

**Comment by VaclavPokorny** [comment]
![snapshot1](https://cloud.githubusercontent.com/assets/16323477/21236246/8c18624e-c2fa-11e6-95e6-121963178fae.png)
![snapshot2](https://cloud.githubusercontent.com/assets/16323477/21236247/8c1a2a2a-c2fa-11e6-973b-1729c1b60446.png)

**Comment by stoicflame** [comment]
That's alphabetical.

Would you rather have it be "depth-first" alphabetical?

```xml
<enunciate>
  <modules>
    <jaxrs path-sort-strategy="depth_first"/>
```

Or would you rather group by path?

```xml
<enunciate>
  <modules>
    <jaxrs groupBy="path"/>
```

**Comment by VaclavPokorny** [comment]
Sure, on first image it is alphabetical. However it is not on the second, which is my point. I would expect it to have te same sorting as the first. Than the first method should be /api/v1/protected/demand/advancePaymentAmountChange/create and not actual /api/v1/protected/demand/submitted/list. That is surely not alphabetical order.

**Comment by stoicflame** [comment]
[Enunciate 2.8.0 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.8.0).
