### ISSUE TITLE
Cannot prepend context path

### ISSUE THREAD

**Issue by Umaaz** [stoicflame/enunciate#572]
Hi.
Firstly let me say I think this project is fantastic! Really useful for me!

However, I have been struggling to get the context path to be prepended to the paths. 

### Quick background.
I have a very simple REST Api using Jax-rs with Jersey/Grizzly. The build uses maven, with the enunciate-maven-plugin version 2.8.0. The plugin runs and produces the docs, I then fatjar this output into the build artifact into the folder /apidocs/. 
I then use the following to allow the jar to serve the docs from the path '/': 
```java
httpServer.getServerConfiguration().addHttpHandler( new CLStaticHttpHandler( getClass().getClassLoader(), "/apidocs/" ) )
```
The REST paths are on the path '/rest/' for example:
 - /rest/group/user/{userid}

### The Problem
So the problem I am faced with is that I am unable to get the docs generated by Enunciate to include the /rest/ part of the url. It seems no matter what I do I always get the urls in the docs to be /group/user/{userid}. 
I have tried several different configurations and seem unable to get it to work with any configuration.

Currently my configuration looks like this:
```xml
<application path="rest"/>

    <modules>
        <jaxrs/>
        <docs includeApplicationPath="true"/>
    </modules>
```

Please let me know if you need more information.

**Comment by lbndev** [comment]
I had the same problem.
My Application class is annotated with @ApplicationPath("/rest")
I don't use \<application path="..."/\> in enunciate.xml.
Instead, I'm doing this :
```xml
<modules>
    <docs apiRelativePath="../${project.name}/" />
    <swagger basePath="/${project.name}/rest" />
   ...
</modules>
```
(variable is replaced by maven resource filtering)
With this configuration I get the correct URLs in HTML pages generated by enunciate and I am able to call the services from the SwaggerUI.

**Comment by Umaaz** [comment]
I experimented a bit more with this, and it does work if you use the @ApplicationPath annotation. 

However it seems any combination of enunciate configuration will not add the application path, if this annotation is not present.

**Comment by stoicflame** [comment]
Sorry it took so long to respond.

The problem is the confusion that results in having multiple `application` elements in the Enunciate config. The application "root" is a global configuration item, defining where the entire application (war) will be hosted. The JAX-RS (and Spring-Web) application "path" is specific to the JAX-RS application and that element needs to be nested under the `jaxrs` configuration element:

```xml
    <modules>
        <jaxrs>
          <application path="rest"/>
        </jaxrs>
        <docs includeApplicationPath="true"/>
    </modules>
```
