### ISSUE TITLE
support for GFM in Enunciate description config

### ISSUE THREAD

**Issue by selimok** [stoicflame/enunciate#574]
Hi, 

i added following html description in enunciate.  

```
	<description>
	<![CDATA[
	<h2>Introduction</h2>
	<p>TODO:Some text here...</p>
	
	<h2>API Conventions</h2>
	<p>TODO:Some text here...</p>
	]]>
	</description>
```

It appears in enunciates default doc output correctly. But in swagger there are some problems: 

v.2.7.0
<img width="982" alt="swagger-description-2 7 0" src="https://cloud.githubusercontent.com/assets/1064818/21427233/a0529ce4-c853-11e6-9b0f-cced145d3c9c.png">

v.2.8.0
<img width="986" alt="swagger-description-2 8 0" src="https://cloud.githubusercontent.com/assets/1064818/21427250/c1376db8-c853-11e6-8322-f5dced275426.png">

If i remove the empty line everything works well in version 2.7.0 but incorrect in 2.8.0 (please see below):

```
	<description>
	<![CDATA[
	<h2>Introduction</h2>
	<p>TODO:Some text here...</p>
	<h2>API Conventions</h2>
	<p>TODO:Some text here...</p>
	]]>
	</description>
```
2.7.0
<img width="547" alt="swagger-description-2 7 0-2" src="https://cloud.githubusercontent.com/assets/1064818/21427394/a25b6844-c854-11e6-9c3e-470f2ad18d2d.png">

2.8.0
<img width="753" alt="swagger-description-2 8 0-2" src="https://cloud.githubusercontent.com/assets/1064818/21427395/a25be6c0-c854-11e6-8f6b-8fb4d1106bff.png">

Thanks.

**Comment by stoicflame** [comment]
Most likely a bug in the Swagger UI, but I can check it out.

**Comment by selimok** [comment]
Yes it is a bug of Swagger UI. I checked it works until (incl.) version v2.2.2. Starting from v2.2.3 most of the HTML tags are ignored.

**Comment by selimok** [comment]
Hmm it seems to be a feature more than a bug: https://github.com/swagger-api/swagger-ui/issues/830 Which solves a XSS vulnerability.

According to https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md description field may be enriched with [GFM syntax](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown).

**Comment by selimok** [comment]
@stoicflame can you consider to support markdown syntax also in native enunciate UI?

**Comment by stoicflame** [comment]
What do you mean by "support markdown syntax"? If you write your JavaDocs in Markdown, doesn't it get preserved?

Or are you suggesting some kind of conversion from HTML/JavaDoc to Markdown?

**Comment by selimok** [comment]
I mean support markdown syntax only for **description** field  in _enunciate.xml_ to achieve compatibility with swagger-ui.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)

```xml
<enunciate>
  <description format="markdown">
```
