### ISSUE TITLE
Headers section in swagger output must be only shown when there is any response header

### ISSUE THREAD

**Issue by selimok** [stoicflame/enunciate#575]
Hi, 

as described [here](https://github.com/stoicflame/enunciate/issues/519#issuecomment-268825418) in swagger UI appears a Headers section (for response header) when any response exists for a given end point, even if the response has no response headers.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
