### ISSUE TITLE
javax.validation.constraints only read from getter method

### ISSUE THREAD

**Issue by peter-janssen** [stoicflame/enunciate#578]
It seems that the validation constraints work beautifully for beans with validation annotations on the getter methods. Unfortunately it seems that if these are added to the fields this does not work. This might be by design in that case consider this as a feature request ;-)

**Comment by peter-janssen** [comment]
Thanks for the quick feedback, especially #317 was very informative. I'd never have figured that out from the documentation.

**Comment by stoicflame** [comment]
I'll re-open this and track is as a request for additional documentation. It's a pretty common issue.

**Comment by peter-janssen** [comment]
One addition. I ended up not using the `@XmlAccessorType(XmlAccessType.FIELD)` but the `@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)` annotation as mention by @patvong in this [comment](https://github.com/stoicflame/enunciate/issues/317#issuecomment-185801221).

**Comment by stoicflame** [comment]
https://github.com/stoicflame/enunciate/wiki/Annotation-Visibility
