### ISSUE TITLE
enunciate1.29 compilation issue with JDK7

### ISSUE THREAD

**Issue by balamanian** [stoicflame/enunciate#58]
HI,
   I am using enunciate 1.29 to generate the document. Below snippet is from ant and usig JDK 7.

i am getting getting below exception
C:\Users\Downloads\swagger\swagger-java-sample-app-master\swagger-java-sample-app-master\src\main\java>ant generate-document -Denunciate.javac.check=true
Buildfile: C:\Users\Downloads\swagger\swagger-java-sample-app-master\swagger-java-sample-app-master\src\main\java\build.xml
    [mkdir] Created dir: C:\Users\Downloads\swagger\swagger-java-sample-app-master\swagger-java-sample-app-master\src\main\java\lib
    [mkdir] Created dir: C:\Users\Downloads\swagger\swagger-java-sample-app-master\swagger-java-sample-app-master\src\main\java\lib\ext

generate-document:
Loading modules from the specified classpath....
Discovered module c
Discovered module csharp
Discovered module docs
Discovered module java-client
Discovered module jaxws-ri
Discovered module jaxws-support
Discovered module jersey
Discovered module obj-c
Discovered module php
Discovered module ruby
Discovered module xml
Loading config C:\Users\Downloads\swagger\swagger-java-sample-app-master\swagger-java-sample-app-master\src\main\java\enunciate-full.xml
initializing enunciate.
invoking enunciate:generate step...
[enunciate]
[enunciate] warning: The apt tool and its associated API are planned to be
[enunciate] removed in the next major JDK release.  These features have been
[enunciate] superseded by javac and the standardized annotation processing API,
[enunciate] javax.annotation.processing and javax.lang.model.  Users are
[enunciate] recommended to migrate to the annotation processing features of
[enunciate] javac; see the javac man page for more information.
[enunciate] An exception has occurred in apt (1.7.0_80-ea). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
[enunciate] java.lang.NullPointerException
[enunciate]     at com.sun.tools.apt.comp.Apt$AptTreeScanner.visitAnnotation(Apt.java:180)
[enunciate]     at com.sun.tools.javac.tree.JCTree$JCAnnotation.accept(JCTree.java:2004)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.visitNewArray(TreeScanner.java:212)
[enunciate]     at com.sun.tools.javac.tree.JCTree$JCNewArray.accept(JCTree.java:1412)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.visitAssign(TreeScanner.java:221)
[enunciate]     at com.sun.tools.javac.tree.JCTree$JCAssign.accept(JCTree.java:1466)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.visitAnnotation(TreeScanner.java:300)
[enunciate]     at com.sun.tools.apt.comp.Apt$AptTreeScanner.visitAnnotation(Apt.java:179)
[enunciate]     at com.sun.tools.javac.tree.JCTree$JCAnnotation.accept(JCTree.java:2004)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.visitModifiers(TreeScanner.java:295)
[enunciate]     at com.sun.tools.javac.tree.JCTree$JCModifiers.accept(JCTree.java:2029)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.visitMethodDef(TreeScanner.java:84)
[enunciate]     at com.sun.tools.apt.comp.Apt$AptTreeScanner.visitMethodDef(Apt.java:171)
[enunciate]     at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:669)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.visitClassDef(TreeScanner.java:80)
[enunciate]     at com.sun.tools.apt.comp.Apt$AptTreeScanner.visitClassDef(Apt.java:165)
[enunciate]     at com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:591)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
[enunciate]     at com.sun.tools.javac.tree.TreeScanner.visitTopLevel(TreeScanner.java:68)
[enunciate]     at com.sun.tools.apt.comp.Apt$AptTreeScanner.visitTopLevel(Apt.java:143)
[enunciate]     at com.sun.tools.javac.tree.JCTree$JCCompilationUnit.accept(JCTree.java:459)
[enunciate]     at com.sun.tools.apt.comp.Apt.main(Apt.java:232)
[enunciate]     at com.sun.tools.apt.main.AptJavaCompiler.compile(AptJavaCompiler.java:270)
[enunciate]     at com.sun.tools.apt.main.Main.compile(Main.java:1127)
[enunciate]     at com.sun.tools.apt.main.Main.compile(Main.java:989)
[enunciate]     at com.sun.tools.apt.Main.processing(Main.java:113)
[enunciate]     at com.sun.tools.apt.Main.process(Main.java:103)
[enunciate]     at com.sun.tools.apt.Main.process(Main.java:85)
[enunciate]     at org.codehaus.enunciate.main.Enunciate.invokeApt(Enunciate.java:817)
[enunciate]     at org.codehaus.enunciate.main.Enunciate.doGenerate(Enunciate.java:401)
[enunciate]     at org.codehaus.enunciate.main.Enunciate$Stepper.step(Enunciate.java:1799)
[enunciate]     at org.codehaus.enunciate.main.Enunciate$Stepper.stepTo(Enunciate.java:1831)
[enunciate]     at org.codehaus.enunciate.main.Enunciate.execute(Enunciate.java:181)
[enunciate]     at org.codehaus.enunciate.main.EnunciateTask.execute(EnunciateTask.java:170)
[enunciate]     at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[enunciate]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[enunciate]     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
[enunciate]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[enunciate]     at java.lang.reflect.Method.invoke(Method.java:606)
[enunciate]     at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[enunciate]     at org.apache.tools.ant.Task.perform(Task.java:348)
[enunciate]     at org.apache.tools.ant.Target.execute(Target.java:435)
[enunciate]     at org.apache.tools.ant.Target.performTasks(Target.java:456)
[enunciate]     at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
[enunciate]     at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
[enunciate]     at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
[enunciate]     at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
[enunciate]     at org.apache.tools.ant.Main.runBuild(Main.java:851)
[enunciate]     at org.apache.tools.ant.Main.startAnt(Main.java:235)
[enunciate]     at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
[enunciate]     at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

BUILD FAILED
C:\Users\Downloads\swagger\swagger-java-sample-app-master\swagger-java-sample-app-master\src\main\java\build.xml:129: org.codehaus.enunciate.EnunciateException: The invocation of APT has failed. See http://jira.codehaus.org/browse/ENUNCIATE-771 for a case where this has been seen. There is no explanation for this error.
        at org.codehaus.enunciate.main.Enunciate.invokeApt(Enunciate.java:819)
        at org.codehaus.enunciate.main.Enunciate.doGenerate(Enunciate.java:401)
        at org.codehaus.enunciate.main.Enunciate$Stepper.step(Enunciate.java:1799)
        at org.codehaus.enunciate.main.Enunciate$Stepper.stepTo(Enunciate.java:1831)
        at org.codehaus.enunciate.main.Enunciate.execute(Enunciate.java:181)
        at org.codehaus.enunciate.main.EnunciateTask.execute(EnunciateTask.java:170)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:435)
        at org.apache.tools.ant.Target.performTasks(Target.java:456)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
        at org.apache.tools.ant.Main.runBuild(Main.java:851)
        at org.apache.tools.ant.Main.startAnt(Main.java:235)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 2 seconds

Please guide me to solve this issue.

**Comment by balamanian** [comment]
Below is my ant code snippet
<target name="generate-document" description="Generating API Documentation">
	<enunciate basedir="./" verbose="true" configFile="./enunciate.xml" >
		<include name="**/*.java"/>
		<classpath refid="enunciate.classpath"/>
		<export artifactId="docs" destination="./docs.zip"/>  
		<javacArgument argument="-g"/>
		<javacArgument argument="-Denunciate.javac.check=true"/>			
	</enunciate>
</target>

**Comment by stoicflame** [comment]
Yeah... tricky. These kinds of errors are usually compilation failures. The Annotation Processing Tool doesn't do a good job of reporting errors. Try doing a "compile" with the same classpath and see if you come up with any compile failures.

**Comment by balamanian** [comment]
thanks for help me to solve this problem. the problem is, i have not include some dependency.
