### ISSUE TITLE
API Includes not working as expected

### ISSUE THREAD

**Issue by kerber** [stoicflame/enunciate#583]
I would expect that the API includes would be additive, adding new classes to what was already detected. 
EnunciateReflectionsScanner.java appears to agree, as it adds any 'include' matches to the detected source elements. The behavior is different in EnunciateAnnotationProcessor.java, however, where anything not explicitly included is removed from the detected API Elements.

Practically, what this means for us is that we are not able to easily use the API includes list to add one-off classes. Instead, using it to include one class means that we have to include ALL classes that we want to include.

**Comment by stoicflame** [comment]
That's correct.

The original idea was to match Ant-style expectations where there's a "default" set of includes (the local api elements), but if includes are explicit, it overrides the default. The `EnunciateReflectionsScanner` is just using the includes/excludes to determine how to set the sourcepath for the compiler, so it doesn't really have a "default" includes and it can afford to be inclusive.
