### ISSUE TITLE
Will @TypeHint work in combination with @FormDataParam?

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#585]
I've got a resource with a method which accepts multipart data. The method expects an XML representation of an entity (`data`) along with a `file`.

```
public Response create(@TypeHint(SerialAudioFile.class) @FormDataParam("data") String data, @FormDataParam("file") byte[] file) {
...
}
```

The generated documentation just specifies both as `formdata`. However, I would really like the documentation to recognise that `data` should be a representation a `SerialAudioFile`. Using `@TypeHint` in combination with `@FormDataParam` does not have any effect on this.

Is there any way to achieve this?

![image](https://cloud.githubusercontent.com/assets/1845372/21851512/a12fc4cc-d80f-11e6-8b21-60efdecd2a41.png)

**Comment by stoicflame** [comment]
There's not currently a way to do this. Currently only request/response entities can have a data type.

This issue is basically the same as #311 except that you'd like a data type applied to a formdata parameter instead of a query parameter. I'm going to close this with the same conditions as I closed #311.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)

**Comment by leforthomas** [comment]
I am having the same issue, does 2.9.0 solve the problem? if so, anything needs doing? I tried type hint but it didn't change anything.

**Comment by stoicflame** [comment]
No, there's currently no support for this feature.
