### ISSUE TITLE
Parameters specified by @RequestHeaders don't appear in documentation

### ISSUE THREAD

**Issue by alfechner** [stoicflame/enunciate#589]
I currently work on a SOAP service on which clients authenticate by setting appropriate HTTP header parameters.

I'd like to use the `@RequestHeaders` annotation included in [Enunciate Specific Annotations](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations) in order to explain what the parameters are used for in the generated documentation.

I try to archive this as follows without success.

```
@WebService(serviceName = "MyService")
@Stateless()
@RequestHeaders(
        @RequestHeader(name = "username", description = "Name of the user.")
)
public class Service {
// ...
}
```

What did I get wrong?

**Comment by stoicflame** [comment]
That annotation is currently only applicable to REST endpoints.

I'll look into adding to SOAP documentation, too.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
