### ISSUE TITLE
[Spring Rest] Missing slash in doc

### ISSUE THREAD

**Issue by rafikMeg** [stoicflame/enunciate#591]
With this class:
```
@RestController
@RequestMapping("resources/users")
public class UserController {
    
    …
    
    @PutMapping("{id}")
    @RolesAllowed({ "ROLE_USERS" })
    public void updateUser(@PathVariable final long id, @RequestBody final User user) {
           userService.updateUser(id, user);
    }
}
```
In the documentation, the url path  generated by the plugin is : **/resources/users{id}** therefore missing a slash.

Spring works correctly and exposes the url  **/resources/users/{id}** with the slash.

I am using the slim maven plugin 2.8.0 with the following dependencies:

- enunciate-spring-web
- enunciate-jackson
- enunciate-jackson1
- enunciate-swagger
- enunciate-docs

Thanks in advance.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
