### ISSUE TITLE
Support @since on fields and enums

### ISSUE THREAD

**Issue by bjoernmartin** [stoicflame/enunciate#592]
I documenting the version for which a field was introduced using the @since JavaDoc tag. However, Enunciate only respects that tag on the Resource / JSON object level (Enunciate-internal: DataType). Is there any support planned for @since being recognized for fields (Java: Enum constants and DTO getters) as well?

If not, would a pull request adding the feature be accepted? I had a quick look at the code and think it's doable with not too much effort. I'd be happy to give it a try.

**Comment by stoicflame** [comment]
I'll take a look. I'm surprised it's not there.

If you'd like to put together a pull request, I'd happily review and accept it.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
