### ISSUE TITLE
How can I access the name of the package a java class belongs to?

### ISSUE THREAD

**Issue by tschofen** [stoicflame/enunciate#596]
I tried to find a solution on the interwebs, but with my limited knowledge of enunciate and JAVA I'm stuck. 
We collect all SOAP XML definitions (data types) and output them with freemarker into an HTML page.
There are lots of them. Instead of just listing them, I'd like to group them by the package they belong to. An example of a class file:
```
package com.dental.core.command.member.pool;
import javax.validation.Valid;
public class AcceptDeclinePoolAdminPositionRequest extends CommandRequest {...
```
I scoured through the object exposed by enunciate, but I can't find any reference to the package name.
The vars exposed in the object:
`annotations, baseType, class, deprecated, description, equals, example, hashCode, javaDoc, label, namespace, properties, propertyMetadata, requiredProperties, since, slug, styles, supertypes, syntax, toString, values, version`
None of the vars mentions the package or it's name. So I dug into the class which has a package class in it, but that turns out to be the enunciate class used and not the package of the class I'm trying to document.

Is there a way to get to the package name of the class to document automatically? 
Do I have to add an annotation to every class instead?

Any help would be greatly appreciated.

**Comment by stoicflame** [comment]
I'm not sure where you got that list, but there's a `package` property on the data type.

**Comment by tschofen** [comment]
I just output the keys and stripped the getters out. 
Here's how I got that list:
```
[#list data as syntax]
   [#list syntax.namespaces as ns]
      [#list ns.types?sort_by("label") as type]
         [#list type?keys as key]
            ${key}, 
         [/#list]
      [/#list]
   [/#list]
[/#list]
```

When I try to get a package ${type.package} it errors with that it doesn't exist. Checking if it exists always returns nothing:
```
[#if type.package??]
  ${type.package}
[/#if]
``` 

I also checked if perhaps the parent (the namespace) contains it, but it doesn't have it either.

**Comment by stoicflame** [comment]
Must not be a data type, then:

https://github.com/stoicflame/enunciate/blob/master/javac-support/src/main/java/com/webcohesion/enunciate/javac/decorations/element/DecoratedTypeElement.java#L55

**Comment by tschofen** [comment]
Hmm...here's how it's added to the Freemarker template:
```
[#-- @ftlvariable name="data" type="java.util.List<com.webcohesion.enunciate.api.datatype.Syntax>" --]
```

**Comment by stoicflame** [comment]
Oh, I see what you're doing.

Yes, package isn't exposed via that interface. Shouldn't be too hard to do, though. I'll take a look for 2.9.

**Comment by tschofen** [comment]
Should I be doing it in a different way? I'm open to suggestions.

**Comment by stoicflame** [comment]
`javaElement` property will be exposed in 2.9.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
