### ISSUE TITLE
Swagger generation improvements

### ISSUE THREAD

**Issue by brenthale** [stoicflame/enunciate#597]
I was finally able to get Enunciate to work well with a Spring Boot application.  I'm noticing that the swagger.json generated file doesn't take advantage of all the information that it could.  For instance, here is one of the methods we have defined:

```java
 /**
   * This needs to return in under 2 seconds (per what Randall said).
   * We really can just return some generic text so that it returns quickly.
   *
   * @return returns the text "XXXX web application is Healthy and Happy!!!"
   */
  @Produces({ MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN })
  @RequestMapping(path = "/healthcheck/heartbeat", method = RequestMethod.GET)
  public String heartbeat() {
    return "XXXX web application is Healthy and Happy!!!";
  }
```

What I see in the generated swagger.json is the following:

```json
    "\/healthcheck/heartbeat" : {
      "get" : {
        "tags" : [ "GencatCheckController" ],
        "summary" : "This needs to return in under 2 seconds (per what Randall said).",
        "description" : "This needs to return in under 2 seconds (per what Randall said).\nWe really can just return some generic text so that it returns quickly.",
        "operationId" : "resource_GencatCheckController_heartbeat_GET",
        "produces" : [ "application/json" ],
        "parameters" : [
        ],
        "responses" : {
          "200" : {
            "schema" : {
"description" : "",
"type" : "string"
            },
            "headers" : {
            },
            "examples" : {
            },
            "description" : "Success"
          }
        }
      }
    }
```

Notice that

1. The "produces" array only includes "application/json" even though the code annotations defines 3 different types.

2. The responses' "schema.description" field should be able to pull in the text from the @return annotations of the code.

3. The "summary" and "description" fields could use some help as well.  Currently they both simply return the first line of the Javadoc'd description.  I think it would be nice if the "summary" could include the first line while the "description" should contain the full text.

I'm also having a hard time getting the 'Try it now' to work correctly in the generated swagger ui.  I think this is mostly a problem related to this known Swagger issue though: [https://github.com/swagger-api/swagger-ui/issues/2408](url)

**Comment by brenthale** [comment]
Actually only #2 above is seeming to be the problem.  I've adjusted my Javadocs on that method and it now sets the "produces" correctly.  I think that was due to the fact that I was trying to use jax-rs annotations instead of spring http annotations.  (i.e. shouldn't have been using @Produces when it also uses @RequestMapping)

#3 also appears to be working fine.

#2 still remains a problem.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
