### ISSUE TITLE
Unable to find source file for java.nio.ByteBuffer.

### ISSUE THREAD

**Issue by brenthale** [stoicflame/enunciate#599]
I am trying to get all Warnings cleaned up in my build and the only one I have left is one from Enunciate.  Here's the warning I get when running Maven with a -X:

[WARNING] [ENUNCIATE] Some source files were not found for the Java classes that define the Web service API.
[WARNING] [ENUNCIATE] Enunciate will be unable to find the documentation for the classes that are missing source files. (For details, rebuild with debug-level logging.)
[WARNING] [ENUNCIATE] In order for Enunciate to find the source files for API classes that are not being compiled in the current project, the source file must be on the Enunciate sourcepath and the class must be explicitly included in the Enunciate configuration.
[WARNING] [ENUNCIATE] For more information, see https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files
[DEBUG] [ENUNCIATE] Unable to find source file for java.nio.ByteBuffer.

Why is it complaining about a Java native class:  java.nio.ByteBuffer?   This has been a part of Java since Java 7 (I'm currently on 8).

Trying to add the class to <api-classes> in enunciate.xml doesn't help.  

I'm wondering if there is hard-coded path for java objects in Enunciate and "java.nio" just needs to be added to it.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)

**Comment by chamfamdad** [comment]
I believe I am having a similar problem.  (using 2.11.0 and Java 8)

`[DEBUG] [ENUNCIATE] Unable to find source file for java.lang.Void.
[DEBUG] [ENUNCIATE] Added java.lang.Void as a JAXB type definition.
`
