### ISSUE TITLE
Support for Spring WS Annotations

### ISSUE THREAD

**Issue by stoicflame** [stoicflame/enunciate#60]
Provide support for Spring WS annotations, e.g. `RequestMapping`, `ResponseBody`, etc.

**Comment by sg-ad** [comment]
Hi!  Just curious if/where this might be on the roadmap?  Thanks for the great work!

**Comment by stoicflame** [comment]
I'll have some initial support in version 2.2.

**Comment by stoicflame** [comment]
Initial support has been added and pushed to HEAD to be included in the next build.

**Comment by sg-ad** [comment]
Cool, I'll check it out over the weekend!

**Comment by stoicflame** [comment]
[Enunciate 2.2 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.2.0).
