### ISSUE TITLE
Add Disable Source Files Warnings Option to Enunciate 2

### ISSUE THREAD

**Issue by saverett** [stoicflame/enunciate#602]
Currently Enunciate 2 does not offer the ability to disable the following warning messages (generated as part of the Maven build process):

```
[WARNING] [ENUNCIATE] Some source files were not found for the Java classes that define the Web service API.
[WARNING] [ENUNCIATE] Enunciate will be unable to find the documentation for the classes that are missing source files. (For details, rebuild with debug-level logging.)
[WARNING] [ENUNCIATE] In order for Enunciate to find the source files for API classes that are not being compiled in the current project, the source file must be on the Enunciate sourcepath and the class must be explicitly included in the Enunciate configuration.
[WARNING] [ENUNCIATE] For more information, see https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files
```

For complex projects with many dependencies, it can be very cumbersome to correctly add all the necessary source files to the Enunciate sourcepath and ensure that they are correctly included in `enunciate.xml`.

It would be very helpful to have an Enunciate configuration option to disable these warnings when they aren't a concern.

**Comment by stoicflame** [comment]
As of 2.9:

```xml
<enunciate>
  <warnings>
    <disable name="source-files-not-found"/>
```

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
