### ISSUE TITLE
@DocumentationExample doesn't work for multi module projects 

### ISSUE THREAD

**Issue by selimok** [stoicflame/enunciate#606]
Hi,

@DocumentationExample annotation works very well for classes residing in main module, but it is not working for external modules. 

I'm not sure if I'm doing something wrong, but I guess it's a bug. 

Thanks.

**Comment by stoicflame** [comment]
Okay, I'll take a look for 2.9.

**Comment by selimok** [comment]
I think it was my mistake. So the problem was something different: 

My enunciate.xml was like this:

```
<api-classes>
		<include pattern="com.domain.**.rest.**" />
		<exclude pattern="**"/>
</api-classes>
```

All referenced models (e.g. com.domain.model.Something class) outside com.domain.**.rest.**   packages were collected and included into API docs but their Annotations & JavaDocs are not interpreted. So I can see this classes in API Docs UI but their documentations was not visible. 

After adding a new include statement, the problem is solved. 

```
<api-classes>
		<include pattern="com.domain.**.rest.**" />
		<include pattern="com.domain.model.**" />
		<exclude pattern="**"/>
</api-classes>
```

But I found it a bit weird behavior. Why enunciate doesn't interpret annotations and javadocs of any referenced classes but include them into API doc?

**Comment by stoicflame** [comment]
As stated [in the FAQ](https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files#configuring-enunciate-source-files):

> When compiling documentation, Enunciate has to be shy about which Java source files to include in the compilation. If Enunciate included every source file found on the sourcepath, the compilation would too often fail because the sourcepath often includes files that reference classes that aren't on the classpath.
>
> Therefore, Enunciate needs to be explicitly configured to include source files of classes that have already been compiled.

**Comment by selimok** [comment]
Thanks for quick response. I understand the reason, but enunciate includes already that referenced classes into API docs, but only not interprets their annotations and javadocs. Is it normal?

**Comment by stoicflame** [comment]
The annotations should always be interpreted.

In order to interpret javadocs, Enunciate needs to know which source files to try to read. It uses the algorithm described [in the FAQ](https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files) to do that. In your case, the source files for the classes in question weren't included because they weren't listed in the `include`, so Enunciate could see the classes, but not their sources.

**Comment by selimok** [comment]
OK thanks for explanation. 👍
