### ISSUE TITLE
Overriden property ignored by enunciate

### ISSUE THREAD

**Issue by learsix** [stoicflame/enunciate#607]
Hi,

enunciate seems to ignore JsonProperties (or XmlElement) declared through an overriden getter. There is a way to bypass this problem but this requires code modifications.

In our case, we use a generic TypesList to return pagination information and a list of object:

```java
public class TypesList<T> {
  [...]
  protected Integer total = null;
  @JsonProperty("total")
  public Integer getTotal() {return this.total; }

 protected Integer offset = null
 @JsonProperty("offset")
 public getOffset(à {return this.offset; }
 
 protected boolean last = true;
 @JsonProperty("last')
 public boolean isLast() {return this.last; }

 protected java.util.List<T> elements = null;
 protected java.util.List<T> getElements() { return this.elements; }
}
```

Then we override this class to define specific type list, for instance:

```java
public class StringList extends TypesList<String> {
  @JsonPoperty("mystrings")
  @Override
  public java.util.List<String> getElements() {return super.getElements(); }
}
```

For the StringList dataType, enunciate documents total, offset and last but ignores the mystrings property. I assume that it detects that mystrings is inherited from TypesList but does not find it in TypesList. 

If I declare elements as a JsonProperty in TypesList it will be document in StringList dataType, but mystrings will still be ignored.

Note that it's easy to bypass this problem, by declaring another getter:

```java
public class StringList extends TypesList<String> {
  @JsonPoperty("mystrings")
  public java.util.List<String> getMystrings() {return super.getElements(); }
}
```

**Comment by stoicflame** [comment]
Okay, I'll take a look for 2.9.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
