### ISSUE TITLE
swagger.json : double quotes not escaped in json examples

### ISSUE THREAD

**Issue by learsix** [stoicflame/enunciate#608]
Hi,

I use the documentationExample annotation to provide examples for properties. Some are string that includes double quotes : `@documentationExample myTab["example"]`

In swagger.json the double quotes are not escaped which results in a failure when the generated swagger.json is parsed. In swagger.fmt the jsonExampleFor function does not seem to escape double quotes.

To bypass this, I can escape double quotes `@documentationExample myTab[\"example\"]`. swagger.json will correctly be generated. However the examples in the html documentation are already escaped : here I end up with `myTab[\\\"example\\\"]`

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)

**Comment by offero** [comment]
This issue still happens for me

**Comment by stoicflame** [comment]
Okay. Please open a separate issue with the details.
