### ISSUE TITLE
including root element in json request/response examples

### ISSUE THREAD

**Issue by oliverfei** [stoicflame/enunciate#609]
Hi,

For json request/response examples, is it possible for enunciate to include the root element in the output?

For example from the sample project, the persona post request example looks like this
```json
{
  "id" : "...",
  "email" : "...",
  "alias" : "...",
  "name" : {
    "givenName" : "...",
    "surname" : "..."
  },
  "picture" : "..."
}
```

as opposed to this
```json
{
  "persona": {
    "id" : "...",
    "email" : "...",
    "alias" : "...",
    "name" : {
      "givenName" : "...",
      "surname" : "..."
    },
    "picture" : "..."
  }
}
```

**Comment by stoicflame** [comment]
When you talk about "root element", what terminology are you using?

Are you talking about the JAXB root element? Because JAXB doesn't really deal with JSON, right? Or are you talking about a different kind of "root element"?

**Comment by oliverfei** [comment]
Yes I am referring to the JAXB root element. For various reasons, we only use the "@XmlRootElement" annotation for our objects even though the api supports both JSON and XML.

Currently I'm using Freemarker to fetch the "@XmlRootElement" name (or the data type label if the name isn't available) and then add it to the request/response examples.

**Comment by stoicflame** [comment]
Okay, so how do you configure Jackson to honor the `@XmlRootElement` annotation? I didn't know what was a thing.

**Comment by oliverfei** [comment]
The ObjectMapper is configured with `SerializationFeature.WRAP_ROOT_VALUE` set to true.

From the Jackson docs:

`public static final SerializationFeature WRAP_ROOT_VALUE`

Feature that can be enabled to make root value (usually JSON Object but can be any type) wrapped within a single property JSON object, where key as the "root name", as determined by annotation introspector (esp. for JAXB that uses @XmlRootElement.name) or fallback (non-qualified class name).

**Comment by stoicflame** [comment]
Okay.

I'll turn this issue into an enhancement request, then.

**Comment by stoicflame** [comment]
With 2.9:

```xml
<enunciate>
  <modules>
    <jackson wrapRootValue="true"/>
    <jackson1 wrapRootValue="true"/>
```

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)

**Comment by oliverfei** [comment]
Hey,

Thanks for adding the feature in!
Would it be possible to also include the wrapped value in the generated client library objects?

**Comment by stoicflame** [comment]
Probably. Go ahead an open up another issue.

**Comment by KishoreGGK** [comment]
Thanks. I have a tried that it works. 
In this regard I have a question. I see that this feature works if the java file is annotated using @XmlRootElement. However if a Java file is annotated with @XMLType and @XmlAccessType though the root element is generated but its not capitalized.

Example 
@XMlRootElement (name = "TestCustomer")
public class TestCustomer {
...
}
Generated document is "testCustomer"

@XmlAccessorType(XmlAccessType.FIELD)
@XMlType (name = "TestCustomer")
public class TestCustomer {
...
}

Generated document is "TestCustomer"
