### ISSUE TITLE
Native first-class support for JSON

### ISSUE THREAD

**Issue by stoicflame** [stoicflame/enunciate#61]
Revamp the JSON support. Don't make it a second-class citizen. Use the Jackson annotations.

**Comment by landonvg** [comment]
What's the status on this?

**Comment by stoicflame** [comment]
Coming with Enunciate 2.0.

**Comment by landonvg** [comment]
Thanks.  And when will that be, approximately?

**Comment by stoicflame** [comment]
#68

**Comment by landonvg** [comment]
@stoicflame how close are we to enunciate 2.0 release now?

**Comment by stoicflame** [comment]
https://github.com/stoicflame/enunciate/wiki/Enunciate-2

**Comment by stoicflame** [comment]
[Enunciate 2 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0)
