### ISSUE TITLE
 Failed at: ${choice.baseType.qname.namespaceURI}

### ISSUE THREAD

**Issue by WilliamHua2016** [stoicflame/enunciate#610]
i use  enunciate-maven-plugin 2.6.0 (com.webcohesion.enunciate) in my SpringBoot project ,when i execute the command "mvn clean package" in terminal ,i got the error as below:
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.6.0:docs (default) on project web: freemarker.core.InvalidReferenceException: The following has eva
luated to null or missing:
[ERROR] ==> choice.baseType.qname  [in template "jar:file:/E:/maven_jar_geerong/com/webcohesion/enunciate/enunciate-c-xml-client/2.6.0/enunciate-c-xml-client-2.6.0.jar!/com/webcohes
ion/enunciate/modules/c_client/client-complex-type.fmt" at line 546, column 177]
[ERROR]
[ERROR] ----
[ERROR] Tip: It's the step after the last dot that caused this error, not those before it.
[ERROR] ----
[ERROR] Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or us
e [#if myOptionalVar??]when-present[#else]when-missing[/#if]. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!
myDefault, (myOptionalVar.foo)??

**Comment by WilliamHua2016** [comment]
by the way,my application can work normally.

**Comment by stoicflame** [comment]
Looks like a bug. I'll look at it for 2.9, but anything you can provide to help me reproduce it would be helpful.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
