### ISSUE TITLE
Using LocalDate does not result in an appropriate description

### ISSUE THREAD

**Issue by twothe** [stoicflame/enunciate#612]
In my (Spring Boot REST) API using Enunicate 2.8.1 on Java 8 I have a parameter (Java 8 LocalDate) annotated as follows:

    @RequestParam(name = "startDate", required = true) @DateTimeFormat(iso = ISO.DATE) 
    final LocalDate dateStart

In the resulting documentation is only mentioned that this paremeter exists, but not the constraints nor that ISO-date is used:

    startDate 	query 	(description) 

I had expected something like:

    startDate 	query 	(description) 	ISO-date (yyyy-mm-dd)

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
