### ISSUE TITLE
AMF Support

### ISSUE THREAD

**Issue by dylanjsa** [stoicflame/enunciate#614]
Hi stoicflame,

First and foremost, thanks for the library!

I'm in the process of migrating and old app from Enunciate 1.x -> 2.8.1 and I'm not having any luck whatsoever.
I was using it to generate client side code for my Flex app.

I've followed the documentation here: https://github.com/stoicflame/enunciate/wiki/Module-AMF
and my enunciate.xml looks like this:
```
 <modules>
      <amf swcName="sn-client-api.swc" swcDownloadable="true" flexHome="/opt/flex/apache-flex-sdk-4.16.0-bin">
      </amf>
   </modules>
```

I've tried to run `gradle enunciate` and it generates docs and client libraries for everything except for AMF.

I've also tried to look for the petclinic/addressbook sample in the download but there's nothing there.

Has support been silently dropped, or am I missing something?

**Comment by stoicflame** [comment]
Yes, I'm afraid there wasn't enough demand for AMF support to justify the effort (and maintenance cost) to port it over to 2.0.

There was one other person asking about it, but I can't seem to find that thread at the moment. He ended up just taking the source files that Enunciate 1.x generated and putting them into his own source tree.

**Comment by dylanjsa** [comment]
Thanks for the quick reply, I've updated the doc at https://github.com/stoicflame/enunciate/wiki/Module-AMF to note that it's Enunciate 1.x only - I hope you don't mind.
