### ISSUE TITLE
package-info.java and @since

### ISSUE THREAD

**Issue by lbndev** [stoicflame/enunciate#615]
Putting "@since" in thez javadoc for a class leads to "Available since:" to be displayed in this class' page.

If "@since" is put in package-info.java, it is ignored.
It would be nice if, instead, it would be applied to all classes of this package (and subpackages).

Other tags (like @http) are properly handled when placed in package-info.java (= in this case, the associated http code is properly documented for all classes of this package).

Thanks

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
