### ISSUE TITLE
Enunciate describes Currency as complex object, while JSON actually returns a String.

### ISSUE THREAD

**Issue by twothe** [stoicflame/enunciate#616]
In my POJO that is later transformed into JSON I return a value of class Currency (the standard Java class). Enunciate describes this value as follows:

    "currency" : {
      "symbol" : "...",
      "displayName" : "...",
      "numericCode" : 12345,
      "currencyCode" : "...",
      "defaultFractionDigits" : 12345,
      "availableCurrencies" : [ { }, { } ]
    },

What Jackson actually returns is however just the ISO currency code:

    currency": "CHF",

I am runing Spring Boot with Enunciate 2.8.1. No additional transformers are used to produce this output.

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
