### ISSUE TITLE
JsonProperty in a Mixin create a nulll pointer exception

### ISSUE THREAD

**Issue by cedric75005** [stoicflame/enunciate#617]
Hello,

With enunciate 2.8.1, I try to create a mixin to parse HATEOAS link (javax.ws.rs.core.Link). For that, I've created the following  mixing :
```
public interface  JacksonLinkMixin {
    
    @JsonIgnore
    abstract Builder getUriBuilder();
    
    @JsonIgnore
    abstract Map<QName, Object> getParams();
    
    @JsonIgnore
    abstract List<String> getRels();
    
    @JsonIgnore
    abstract String getTitle();
    
    @JsonProperty("href")
    abstract URI getUri();
    
        
}
```

When I add the two last line to have a href properties, I have a nullPointer exception (please check the stactktrace in attachment).

Regards

[stacktrace.txt](https://github.com/stoicflame/enunciate/files/870726/stacktrace.txt)

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
