### ISSUE TITLE
Swagger UI broken in 2.8.1?

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#618]
Hi.

I gave 2.8.1 a testdrive and have the strange behavior, that Swagger UI seems broken. It lists the endpoints etc. without a problem. But clicking on the actual endpoint to show the request form etc. doesn't work. Just nothing happens. Using `Expand Operations` on the right works though.

Is it just me or does somebody have the same issue?

When I reload the swagger page, this is printed into the browser console:

`Error: Syntax error, unrecognized expression: #%2Fauthentication%2Flogin_resource_authentication_login_AuthenticationResource_login_POST_content     	jquery-....min.js (Zeile 2, Spalte 56624)`

**Comment by stoicflame** [comment]
[Enunciate 2.9.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.9.0)
