### ISSUE TITLE
Security roles in generated documentation

### ISSUE THREAD

**Issue by guusdk** [stoicflame/enunciate#62]
It would be handy to have the documentation include JSR 250-defined security roles references (@RolesAllowed, @PermitAll, @DenyAll) that are used to annotate the corresponding web services.

(This is a copy of the soon-to-be-unavailable https://jira.codehaus.org/browse/ENUNCIATE-618 )

**Comment by defnull** [comment]
+1

**Comment by stoicflame** [comment]
Added at 1ec31f8; will be included in 2.1.

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)
