### ISSUE TITLE
Support JavaDoc @link tag

### ISSUE THREAD

**Issue by masm22** [stoicflame/enunciate#625]
A standard approach when documenting getters and setters is to document the fiels with a JavaDoc and then propagate the value using JavaDoc's @link tag: `{@link Class#field}`. This allows to avoid copy/paste operations which improves the process of maintaining the documentation. It would be nice to have enunciate automatically replace the links on getters with original comments taken from backing fields.

**Comment by stoicflame** [comment]
Duplicate of #174 .
