### ISSUE TITLE
Support "type replacement" in Jackson module

### ISSUE THREAD

**Issue by xkacer** [stoicflame/enunciate#626]
Some classes may have custom JSON handling, including registered special serializers and/or deserializers. It is generally not possible to understand how they work and what JSON they produce/consume. As a result, when such custom handling is in effect, the documentation generated by Enunciate does not correspond with reality.

A relatively easy and (imho) elegant solution would be to introduce general "type replacement". What I mean is that in enunciate.xml, it would be possible to say something like:
```xml
<jackson disabled="false" ...>
<type-replacement>
	<replace source="com.test.MyWeirdClassSerializedAsString" target="java.lang.String"/>
	<replace source="com.test.mydomain.MyMoreComplexSpecialClass" target="com.test.doc.enunciate.DocumentationOfMyClass"/>
</type-replacement>
</jackson>
```
which would replace all references to _source type_ as if there was _target type_. The target type may then be a documentation-only class, not used in the real application and providing any extra documentation that should be necessary, including some fake (example?) properties or @documentationExample.

I am talking about documentation here, because this is my current situation, but I can imagine this could be handy also when generating some client code in other languages, and so on.

What do you think? In fact, this is something I currently need. So I am volunteering to implement it and contribute to Enunciate, if you approve that and tell me what exact configuration XML elements should be used. Of course, if you have any idea how to do that and point me to some place in the code, it would be highly appreciated.

**Comment by stoicflame** [comment]
I believe you can use support for mixins as provided at #472 for this.

Let me know if that falls short and we can re-open this with more refined requirements.

**Comment by xkacer** [comment]
Well, originally I did not think using mixins could help, as mixins add annotations to existing properties, while I want to replace the whole type. However, after implementing #490, it seems that similar functionality can be achieved by using mixin to add a new method with `@JsonValue`, which basically does what I want.

This approach has some limitations but it's worth examining. I may come back with some other suggestion to overcome them.
Thanks!

**Comment by xkacer** [comment]
Ok, I tried using mixins combined with the `@JsonValue` annotation. Although I think mixins are not intended for such purpose, it is possible to achieve the desired effect.

There is at least one limitation, however:
Mixins do not work for "known types", such as dates, currency, etc.

I have a small patch prepared that will remove a type from `knownTypes` if it has a registered mixin. I believe it should be safe: If someone defines a mixin, they should know what they're doing and why.
