### ISSUE TITLE
Allow to configure Jackson ObjectMapper defaults

### ISSUE THREAD

**Issue by xkacer** [stoicflame/enunciate#627]
Enunciate does a great job following various JSON annotations and trying to mimic JSON parser/generator behavior as closely as possible. However, annotations are not the only way to affect processing in Jackson. Many features may be configured via `ObjectMapper` and such configuration is then invisible to Enunciate.

Typically, for all the features, there is some default that may be changed in `ObjectMapper` and then again specialized in individual classes by annotations. I am talking about the possibility of changing the defaults by Enunciate configuration to match the settings of `ObjectMapper`.

In my particular scenario, this mainly includes "field visibility", as discussed some time ago in #191 comments. However, I did a little research and identified other features that may be configured this way:

1. **Visibility Checker** (property and field visibility, set by `ObjectMapper.setVisibility` and `@JsonAutoDetect`). Enunciate obeys the annotation but uses system defaults for other classes.\
_Proposed solution:_ Add configuration elements to change the default visibility.

2. **Property Inclusion** (what property values - such as _null_ - to skip in JSON, set by `ObjectMapper.setSerializationInclusion` and `@JsonInclude`).\
_Proposed solution:_ Ignore, as this is a sort-of implementational decision and well-behaved APIs should not be dependent on that.

3. **Type Resolver** - I have to admit I do not have any experience with that, mainly because I do not think inheritance should be abused in JSON-based APIs. So, let's ignore this in this issue. Feel free to come with a different opinion.

4. **Date/Time Format** - influenced by several `SerializationFeature`s and `ObjectMapper` methods, including time zone and locale.\
_Proposed solution:_ Already partially handled by `dateFormat` configuration attribute. Probably sufficient for most APIs. If necessary, the documentation may be improved by using type replacement (update: or mixins), as described in #626.

5. **Locale Settings** (specified by `ObjectMapper.setLocale`) - may affect formatting of numbers, and so on.\
_Proposed solution:_ Ignore, as it is probably too fine-tuning to be covered.

6. **Root Value Wrapping** - `SerializationFeature.WRAP_ROOT_VALUE`\
**Char Array Handling** - `SerializationFeature.WRITE_CHAR_ARRAYS_AS_JSON_ARRAYS`\
**Enum Handling** - `SerializationFeature.WRITE_ENUMS_USING_TO_STRING` and `SerializationFeature.WRITE_ENUMS_USING_INDEX`\
_Proposed solution:_ May be included into configuration but I tend to ignore those as I do not think many people use them. (update: I just noticed that "wrap root value" is supported since 2.9)

7. **Custom Serializers and Deserializers** - this is a much more complicated matter, so I created a separate issue here as #626.

8. Update: **Jackson Mix-ins** - already supported since 2.6.

I'd like to implement nr. 1 and I volunteer to do it myself if you agree.
Also, opinions on other items are welcome.

**Comment by stoicflame** [comment]
Sure, we can add a configuration option for setting default accessor visibility. And you're welcome to put together a pull request if you'd like to do the work yourself.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
