### ISSUE TITLE
Is there a way to reference sourcepath from maven dependency?

### ISSUE THREAD

**Issue by masm22** [stoicflame/enunciate#633]
My REST API (Spring MVC project) dependes on an external maven package. All the JavaDoc for types from external package are missing. The referenced package has the .sources and .javadoc jars published within the package. The project is build with gradle (com.webcohesion.enunciate plugin is used).

I understand that this is a sourcepath issue described in  [Discovering Source Files](https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files). But I did not succeed getting the JavaDoc from the package while playing with `sourcepath` property.

So I've got two questions that will help me to move forward (because I came to the point where I got stuck).

1. I've took the files package.jar, package-sources.jar and package-javadoc.jar from gradle cache and put them inside a subdirectory 'sp' in the root of my project. I included the root namespace of the referenced package to `api-classes` section of `enunciate.xml`. Then I added the following to my gradle script:

```
enunciate {
	sourcepath "sp"
}
```
The javadocs did not appear. So my question is: am I wrong with configuration or this is not supported and won't work anyway?

2. When referencing maven dependencies it is kind of problematic to define the sourcepath inside gradle cache. Are there any recommendations how this should be handled? It would be superb to reference the dependency URL, not the local path. Something like:

```
dependencies {
    enunciateCompile "group:package:version"
}
```

Thanks.

**Comment by stoicflame** [comment]
I'm pretty sure `sourcepath` needs to list the jars; you can't just list a directory that _contains_ the jars. If you want to use a directory on the sourcepath, you have to expand the jars _into_ the directory.

As for your second question, I'm not a gradle user so I don't have much input. Maybe @jskovjyskebankdk could chime in with some input?

**Comment by masm22** [comment]
@stoicflame, thanks for the hint. Specifying jar with sources explicitly extracts the comments out of referenced package. Thus, question 1 is resolved. Interesting observation: specifying the jar with javadoc is not sufficient, it has to be precisely sources.

**Comment by masm22** [comment]
Question 2 was resolved this way (in case someone else needs this):

```
configurations{
    enunciateCompile {
	}
} 

dependencies {
	enunciateCompile "group:spackage:version:sources"
}

enunciate {
	sourcepath {
	    configurations.enunciateCompile
	}
}
```
