### ISSUE TITLE
Exception creation compile error

### ISSUE THREAD

**Issue by chen8002014** [stoicflame/enunciate#635]
I am creating an exception using code below. But compile error "constructor Exception in class Exception cannot be applied to given types;)" in java-xml-client. 

```java
@WebFault(...)
public class SOAPException extends Exception {
    public SOAPException(String message) {
        super(message);
    } }
```

java.lang.Exception should support constructor with String parameter. The root cause is that Enunciate rewrite java.lang.Exception which does not support Exception with String parameters. 
java.lang.Exception class need to be modified to support Exception(String), Exception(String, Throwable)

**Comment by stoicflame** [comment]
You're probably using exceptions as a data type somewhere in your API. Perhaps there's some kind of getter method that returns an exception from one of your data types?

**Comment by chen8002014** [comment]
Yes. You are right. Hopefully, it will be fixed soon. Currently, I am using a work around to put java.lang.Exception file to source folder before compile. The work around works for me. Thanks for your quick response.

**Comment by stoicflame** [comment]
You could also configure Enunciate to convert `java.lang.Exception` to a different client classname:

```xml
<enunciate>
  <modules>
    <java-xml-client>
      <package-conversions>
        <convert from="java.lang" to="client.java.lang"/>
```

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
