### ISSUE TITLE
Document for data type json not created

### ISSUE THREAD

**Issue by chen8002014** [stoicflame/enunciate#640]
I am using ant task to generate document. XML data type and resources are generated successfully. However, JSON data type is not generated. Is it a bug or my settings is wrong?
Ant task to generate document:

```xml
<enunciate basedir="..." buildDir="...">
    <export artifactId="docs" destination="..."/>
</enunciate>
```

Java class for data type:

```java
@XmlRootElement(name = "...")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "...", propOrder = {"..."})
public class ...{...}
```

Java class for request handling:

```java
@Path("...")
@Produces({"application/xml", "application/json"})
public class ... {...}
```

I assume that if XmlRootElement is added to data type class, both XML data type and JSON data type should be shown in document. If not how could I do that?

Strange thing is that if I only add XmlRootElement annotation in data type class, JSON data type can be generated.

**Comment by stoicflame** [comment]
JSON is supported by the `jackson` or `jackson1` modules. If Enunciate doesn't detect Jackson on your classpath, those modules won't activate automatically and JSON data types won't be included.

You can also "force-enable" the module via config:

```xml
<enunciate>
  <modules>
    <jackson disabled="false"/>
```

**Comment by chen8002014** [comment]
Hi stoicflame,
Thanks for your support. I successfully created JSON using config below:
<enunciate">
  <api-classes>
    <include pattern="..."/>
  </api-classes>
  <modules>
    <jackson disabled="false"/>
    <jackson1 disabled="true"/>
  </modules>
</enunciate>
