### ISSUE TITLE
Mandatory and Optional query parameters

### ISSUE THREAD

**Issue by sumanrajagopal** [stoicflame/enunciate#641]
I have used @NotNull in POJO classes to mark the attributes required or not. It is working. But, when I used @NotNull for query parameters in REST API, it is not considered while documenting and does not reflect in Swagger UI. 

I use Enunciate 2.9.1 with the configuration as below

```xml
<modules>
   <jaxrs>
            <application path="/rest/service"/>
    </jaxrs>
    <swagger basePath="/rest/service"/>
    <obj-c disabled="true"/>
    <csharp disabled="true"/>
    <java-client disabled="true" />
    <java-xml-client disabled="true"/>
    <c disabled="true"/>
    <php disabled="true"/>
    <ruby disabled="true"/>
    <xml disabled="true"/> 
    <java-json-client disabled="true"/>
    <idl disabled="true"/>
    <jackson disabled="true"/>
    <jaxws disabled="true"/>
    <csharp-xml-client disabled="true"/>
  </modules>
```

**Comment by stoicflame** [comment]
I'm not able to reproduce the problem. When I annotate a query parameter with `@javax.validation.constraints.NotNull`, Enunciate correctly documents it as `required`.
