### ISSUE TITLE
Resources description error

### ISSUE THREAD

**Issue by chen8002014** [stoicflame/enunciate#642]
I have a resource handling class which contains several rest interfaces. I have the following settings to sort resource items by path in index.html. When I am using ANT EnunciateTask to create document, I am facing the problem that all descriptions for resources in index.html are using description from that resource handling class(parent), not from each interface (child).
Resource handling class:

```java
/**
 * Parent description.
 */
@Path("parentPath")
public class MyResource{
  /**
   * Child 1 description.
   */
  @GET
  @Path("/childPath1")
  public Response func1(...) { ... }
  /**
   * Child 2 description.
   */
  @GET
  @Path("/childPath2")
  public Response func2(...) { ... } }
```

Settings:

```xml
<jaxrs groupBy="path" datatype-detection="aggressive"/>
```

In generated index.html, description is wrong:

Path                                     Method    Description
/parentPath/ChildPath1         GET         Parent description
/parentPath/ChildPath2         GET         Parent description

I think the corrent index.html should be:

Path                                     Method    Description
/parentPath/ChildPath1         GET         Child 1 description
/parentPath/ChildPath2         GET         Child 2 description

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
