### ISSUE TITLE
Hide body param for multipart request

### ISSUE THREAD

**Issue by pstryq** [stoicflame/enunciate#646]
Hi,

is there any way to hide 'body' param within Swagger documentation?
Suppose I want to expose API method which consumes multipart form. I want to upload file along with other params therefore all of those are annotated with @FormDataParam. As a result of performed enunciate task, I get docs saying that my method accepts mentioned params along with 'body' param.

**Comment by stoicflame** [comment]
There's not an easy way to do that today, no. I'll add something for 2.10

**Comment by stoicflame** [comment]
You should be able to use `@Ignore` annotation or `@ignore` JavaDoc tag with 2.10.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
