### ISSUE TITLE
Request/Question - Can the enunciate library be available as a single fat executable jar ?

### ISSUE THREAD

**Issue by bbarman4u** [stoicflame/enunciate#650]
Request/Question - Can the enunciate library be available as a single fat executable jar ? Right now there are 56 libraries that are in the lib folder and the entire lib folder and its jars has to be added as a compile time dependency to the project instead of a single jar ?

**Comment by stoicflame** [comment]
Are you using Ant to build? Does [Ivy](http://ant.apache.org/ivy/) or something like it not work for your use case?

**Comment by bbarman4u** [comment]
Yes we are using Ant to build right now, but we want to move towards Maven. What I wanted to confirm is that if we move to Maven, will just pointing to Maven Central as my remote repository to pull the Enunciate libraries work or do I have to add any of these files to my local hosted Nexus repository for resolution?

**Comment by stoicflame** [comment]
Everything is in Maven Central.
