### ISSUE TITLE
Support @JsonValue on enums, @JsonProperty on enum values

### ISSUE THREAD

**Issue by sdcuike** [stoicflame/enunciate#653]

**Comment by stoicflame** [comment]
Yes, it can.

**Comment by sdcuike** [comment]
But，in interface ，it don't works。like：

public interface IEnumValueType {
    @JsonValue
    int getValue();
    
    public static <T extends IEnumValueType> T of(Class<T> type, int value) {
        T[] constants = type.getEnumConstants();
        for (T t : constants) {
            if (t.getValue() == value) {
                return t;
            }
        }
        
        return null;
    }
}


```
@Getter
@ToString
public enum CompanyType implements IEnumValueType {
    /**
     * 1, "类型1"
     */
    A(1, "类型1"),
    /**
     * 2, "类型2"
     */
    B(2, "类型2");
    
    private int code;
    private String description;
    
    CompanyType(int code, String description) {
        this.code = code;
        this.description = description;
    }
    
    @Override
    public int getValue() {
        return code;
    }
    
    @JsonCreator
    public static CompanyType ofValue(int value) {
        return IEnumValueType.of(CompanyType.class, value);
    }
}

```

result is:
 "companyType" : "A",

**Comment by sdcuike** [comment]
```

package com.sdcuike.practice.domain;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sdcuike.mybatis.type.IEnumValueType;
import lombok.Getter;
import lombok.ToString;

/**
 * Created by beaver on 2017/4/19.
 */

@Getter
@ToString
public enum CompanyType implements IEnumValueType {
    /**
     * 1, "类型1"
     */
    A(1, "类型1"),
    /**
     * 2, "类型2"
     */
    B(2, "类型2");
    
    private int code;
    private String description;
    
    CompanyType(int code, String description) {
        this.code = code;
        this.description = description;
    }
    
    @Override
    @JsonValue
    public int getValue() {
        return code;
    }
    
    @JsonCreator
    public static CompanyType ofValue(int value) {
        return IEnumValueType.of(CompanyType.class, value);
    }
}

```

don't works

**Comment by sdcuike** [comment]
CompanyType Data Type

Created by beaver on 2017/4/19.

Values
value	description
A	1, "类型1"
B	2, "类型2"

**Comment by sdcuike** [comment]
thank you

**Comment by M0rfic** [comment]
Hi,

Just ran into this issue myself. Could you please let me know if there is any way to work around this limitation until the fix is released?

Kind regards

**Comment by stoicflame** [comment]
At e5542ac I added support for the `@JsonProperty` annotation to specify enum values, so that will have to do for now. As for the `@JsonValue`, there's no way for enunciate to deterministically make the association between the constructor parameter and the enum value.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).

**Comment by vghero** [comment]
Hm. Just stumbled across this today. We have the same issue. We want to return the given `@JsonValue` - which is an int - instead of the "string" enums. Isn't it as simple as for checking on  `@JsonValue` on enums and using the defined type+value instead? Why is scanning of the `@JsonCreator`/ctor needed at all for documentation :)?

**Comment by stoicflame** [comment]
I can take another look at it.

**Comment by vghero** [comment]
Thanks!

**Comment by panchenko** [comment]
The simplest approach would be introducing a new annotation like this:

```java
public enum CompanyType {
  @JsonIntValue(1)
  A,

  @JsonIntValue(2)
  B
}
```
WDYT?

**Comment by simonDeHero** [comment]
`@DocumentedAs(value = "87", type = DocumentedAs.Type.NUMBER)` would be more flexible and as it not starts with `Json`, there would be no misunderstanding, that this annotation does not come from jackson.
but on the other hand, there is https://github.com/FasterXML/jackson-databind/issues/1850. depending on how it is fixed, these proposed enunciate-specific annotations may become obsolete, as enunicate could maybe adapt to their fix?

**Comment by panchenko** [comment]
The referenced Jackson issue is not related, as for documentation purposes it does not matter if deserialization works directly or via `@JsonCreator`.
The type can be inferred from the method, but providing serialized value manually via annotation would still be the simplest option.

**Comment by vghero** [comment]
Sweet, thanks Ryan!

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
