### ISSUE TITLE
JAXB drops collection type information for field

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#654]
We have code like this:

````
@XmlRootElement(name="applicationdomains")
@XmlAccessorType(XmlAccessType.NONE)
public class ApplicationDomainListResultDTO {
	
  @XmlElement(name="applicationdomain")
  private List<ApplicationDomainDTO> applicationDomains;
}
````

Which gets output in swagger form as:

````
    "xml_ns0_applicationDomainListResultDTO" : {
      "type" : "object",
      "title" : "applicationDomainListResultDTO",
      "allOf" : [
        {
          "properties" : {
            "applicationdomain" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
"$ref" : "#/definitions/xml_ns0_applicationDomainDTO"
            }
          }
        }
      ],
      "description" : ""
    }
````

This lacks the information about the List.

I think it should look like this instead:

````
    "xml_ns0_applicationDomainListResultDTO" : {
      "type" : "object",
      "title" : "applicationDomainListResultDTO",
      "allOf" : [
        {
          "properties" : {
            "applicationdomain" : {
              "xml" : {
                "namespace" : ""
              },
"description" : "",
              "type" : "array",
              "items" : {
"$ref" : "#/definitions/xml_ns0_applicationDomainDTO"
              }
            }
          }
        }
      ],
      "description" : ""
    }

````

I have been looking in the JAXB ComplexDataTypeImpl/PropertyImpl code, but as far as I can tell, the information about the field's list nature is already lost.
The type information available in those classes looks like it is just ApplicationDomainDTO, not  List-of-ApplicationDomainDTO.

Any suggestions to what I am missing? Or perhaps pointers to how I can fix it?

**Comment by stoicflame** [comment]
XML doesn't have a notion of a "list" or "array" like JSON does, so the abstraction hides the underlying implementation.

We'll have to figure out how to surface up that information so the swagger processing can expose it as such.

**Comment by jskovjyskebankdk** [comment]
Interesting.
An XSD schema can define that a valid XML document should contain a list. But it is implemented in the XML as any old repetition of elements, that may (or may not) be a list.

Not sure how to progress with this myself. But I will try to look closer at the JXB code if I get time.
I am working on a few other patches that are more important.

**Comment by jskovjyskebankdk** [comment]
@stoicflame do you have any idea about how this could be done?
In other words; is there an approach you would prefer to others?

I am swamped at work. But on some days, I have small gaps of time where I might be able to look at this.
But I really have no idea about how to approach it. Any hints appreciated.

**Comment by stoicflame** [comment]
There should be some property exposed on that element called "maxOccurs" or something that we can use to determine if it should be an array. I haven't taken the time to look at why that isn't happening already. It's probably just a bug that I'll eventually get around to scrubbing.

**Comment by jskovjyskebankdk** [comment]
Awesome!
Looking forward to testing it.

Thanks!

**Comment by jskovjyskebankdk** [comment]
Yes, does work. Thanks again.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
