### ISSUE TITLE
Exclude files not work

### ISSUE THREAD

**Issue by chen8002014** [stoicflame/enunciate#658]
I am using the config below to exclude rest interfaces. However, the excluded APIs are still shown in document.
```xml 
 <api-classes>
    <exclude pattern="aaa.bbb.**"/>
    <include pattern="aaa.**"/>
  </api-classes>
```
If I put it in ant configuration, it works.
```xml 
<enunciate ...>
      <include name="**/*.java"/>
      <exclude name="**/ExcludedClass.java"/>
      ...
    </enunciate>

**Comment by stoicflame** [comment]
I'll take a closer look for 2.10.

If you can send me a sample project or a patch for the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) that illustrates the problem, that would expedite things significantly.

**Comment by chen8002014** [comment]
Both ant task and configuration work if I follow rule for "However, if an excluded class is explicitly referenced by an included class, Enunciate will automatically include it (regardless of configuration) in order to avoid broken references." Thank you for your help.
