### ISSUE TITLE
How to exclude model files

### ISSUE THREAD

**Issue by chen8002014** [stoicflame/enunciate#659]
I am using ant task to generate document. How does enunciate detect models such as xml or json? How to exclude model classes?
I find that document for some models are generated not from "basedir" in ant task. They are from "classpath" defined in ant task. The "classpath" I specified is used to build the project. The "classpath" includes many classes that I do not want to add to document. I want to exclude model classes (API classes can be excluded) in ant task. Is there a way to exclude model classes in ant task or some work around?
``` xml
<enunciate basedir="src" buildDir="..." configFile="...">
      <include name="**/*.java"/>
      <exclude name="**/ExcludeModel.java"/>
      <classpath refid="project.build.classpath"/>
      <export artifactId="docs" destination="..."/>
</enunciate>

**Comment by stoicflame** [comment]
https://github.com/stoicflame/enunciate/wiki/Excluding-Including-Classes

**Comment by chen8002014** [comment]
Thank you so much. I forget to read one line for configuration: "However, if an excluded class is explicitly referenced by an included class, Enunciate will automatically include it (regardless of configuration) in order to avoid broken references." After modifying configuration with this rule, every thing works.
