### ISSUE TITLE
@requestExample tag support for Swagger

### ISSUE THREAD

**Issue by tpredey** [stoicflame/enunciate#660]
I am trying to populate the Swagger interactive request example JSON with a realistic simulation. I see that the @requestExample and @responseExample JavaDoc tags are new in version 2.9.1, so I am wondering if I am just doing something incorrectly or if the Swagger support is not out yet.

**Comment by stoicflame** [comment]
Those should work. What does your code look like?

**Comment by stoicflame** [comment]
Bump.

Any updates on this? I need some more info if I'm going to look deeper.

**Comment by stoicflame** [comment]
I'm closing this for now. I'm happy to reopen if I can get more information.
