### ISSUE TITLE
Swagger tag grouping support

### ISSUE THREAD

**Issue by nomisvai** [stoicflame/enunciate#664]
When generating the swagger.json file, is it possible to group rest resources using the swagger tags? Currently the behavoir seems to be that one tag is created per resource using the resource name as the tag.  

Could the ResourceGroup annotation be supproted for swagger? Or another type of specific swagger annotation?

**Comment by stoicflame** [comment]
I'll take a look for 2.10

**Comment by stoicflame** [comment]
Taking a closer look, the `@ResourceGroup` annotation can be used. Just make sure grouping is by annotation:

```xml
<enunciate>
  <modules>
    <jaxrs groupBy="annotation"/>
```
