### ISSUE TITLE
Description in ResourceGroup should be able to specify

### ISSUE THREAD

**Issue by chen8002014** [stoicflame/enunciate#666]
I am using @ResourceGroup annotation in API handling class and use the following configuration:
```xml
<jaxrs groupBy="annotation">
```
My problem is that in document, the description of that ResourceGroup is the description of the API handling class. If several API handling classes use same ResourceGroup, the description is got from one of these classes. This is not correct. Each ResourceGroup should have a description and it should not be got from one of the API handling class description. In other words, customer should be able to add name and description to ResourceGroup annotation.

**Comment by stoicflame** [comment]
You just want to be able to override the description in the annotation?

I can probably include that enhancement in 2.10.

**Comment by vghero** [comment]
Sounds nice!

**Comment by stoicflame** [comment]
At 962cbf5 I added a description element to the annotation.

If more than one class specifies a description, it'll be random which description gets selected.

**Comment by vghero** [comment]
Thanks Ryan!

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
