### ISSUE TITLE
Repeated Accept headers in document

### ISSUE THREAD

**Issue by chen8002014** [stoicflame/enunciate#668]
If I use the code below to generate document, 2 "Accept" headers will be shown in Request example in document.
The root cause of this is that when using @HeaderParam annotation, a new header will be added in Request example and a default Accept header will be added all the time.
Enunciate should not add repeated headers to Request example in document.
```
  @GET
  @Produces({MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML})
  public Response myFunction(
    @HeaderParam("Accept") String acceptHeader) { ... }
```

**Comment by stoicflame** [comment]
I'll take a look for 2.10.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
