### ISSUE TITLE
Is there a way to entirely remove JSON from the generated documentation?

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#669]
I'm working on an API which supports XML only. That is, it accepts and returns XML.

The generated API documentation comes with both JSON and XML examples. Is there a way to entirely disable JSON, so that all examples are XML only and all mentions of JSON goes away?

**Comment by stoicflame** [comment]
Disable to JSON provider modules (jackson, jackson1):

```xml
<enunciate>
  <modules>
    <jackson disabled="true"/>
    <jackson1 disabled="true"/>
```

**Comment by sbrattla** [comment]
Thanks for your example. Unfortunately, it has no effect on the generated documentation. I'm using version **2.9.0**. I still see JSON appearing the generated documentation.

![image](https://user-images.githubusercontent.com/1845372/27321896-58e53642-559c-11e7-8c09-321868d6c4df.png)

**Comment by stoicflame** [comment]
Works for me on the [sample app](https://github.com/stoicflame/enunciate-sample) with [this diff](https://gist.github.com/stoicflame/186d5f0d00b223801b113c6d6c603af0).

Before patch:

![before](https://user-images.githubusercontent.com/145838/27355451-4c205f50-55c8-11e7-83df-2fcb1bce35fe.png)

After patch:

![after](https://user-images.githubusercontent.com/145838/27355470-58f343f0-55c8-11e7-9028-0a86db52ee0f.png)
