### ISSUE TITLE
where did the XSLT support go?

### ISSUE THREAD

**Issue by abstratt** [stoicflame/enunciate#671]
I was looking into upgrading our API documentation artifact from Enunciate 1.21 (I know, I know...) to Enunciate 2.x. One thing I can't figure out how to do in Enunciate 2.x is how to use a XSLT transformation. Was support for that feature actually dropped, Freemarker template being the only way now?

**Comment by stoicflame** [comment]
Yeah, it's gone. The XSLT was determined to be a superfluous step. A custom freemarker template is the only way to customize 2.x.
