### ISSUE TITLE
Javadoc Tags and Swagger Annotation

### ISSUE THREAD

**Issue by psin102** [stoicflame/enunciate#672]
Hi All,

I have been using enunciate and so far it has worked very well. 

I wanted to enhance my documentation by adding some enunciate annotations and the Javadoc tags mentioned on the enunciate wiki page. 

So, I added the enunciate-core-annotations as compile time dependency.  Enunciate version 2.9.1.
I added jax-doclets jar compile time dependency so I can leverage some of the Javadoc Tags.

Couple of things which I wanted clarifications and help on :

- The @ResourceGroup("XYZ Group") annotation seem to be not read when i apply it on the ResourceClasses or even methods in ResourceClass. ResourceLabel works perfectly. Anything I am doing wrong here with it?

- The JavaDoc Tag are not getting auto complete in the IDE, neither are they rendered or processed in UI. I was trying to use "responseExample" and "requestExample" tag but it doesn't seem to work. Am I missing some additional dependency or some other config step here to making it work?

- I tried using swagger annotations as well and see if Enunciate processes them but it doesn't seem to be happening. Can you please confirm on this if the support is there for it or no?

**Comment by stoicflame** [comment]
> The @resourcegroup("XYZ Group") annotation seem to be not read when i apply it on the ResourceClasses or even methods in ResourceClass.

You have to make sure you specify you want grouping by annotation:

```xml
<enunciate>
  <modules>
    <jaxrs groupBy="annotation"/>
```

> The JavaDoc Tag are not getting auto complete in the IDE, neither are they rendered or processed in UI. I was trying to use "responseExample" and "requestExample" tag but it doesn't seem to work.

How is it supposed to work? I don't even know how to "register" javadoc annotations with the IDE... can you enlighten me?

> I tried using swagger annotations as well and see if Enunciate processes them but it doesn't seem to be happening. Can you please confirm on this if the support is there for it or no?

See #433.

**Comment by stoicflame** [comment]
Picking this up again.

After some research, I can find no way to add metadata to dependencies so that IDEs will pick up JavaDoc tags. Until some official support is added, there's nothing else to do on this issue.

I'd be happy to re-open if there are any other open issues that need to be discussed.
