### ISSUE TITLE
Generate securityDefinitions/security sections in swagger.json

### ISSUE THREAD

**Issue by qmunke** [stoicflame/enunciate#673]
Similar to #468 - would be great if the generated swagger.json file could include the authentication sections (see http://swagger.io/docs/specification/authentication/)

I would envision this would need to be configured via the enunciate.xml and then maybe pick up on the presence of specified annotations (similar to the way custom styles are applied)

**Comment by stoicflame** [comment]
See also #670.

I'll take a look for 2.10.

**Comment by stoicflame** [comment]
Finally picking this up.

So the security "schemes" would probably need to be defined via config. How would the schemes be referenced from the API methods? Another annotation or something?

**Comment by kkwansj** [comment]
[schemes referenced by another annotation]  Sounds reasonable to me.

**Comment by stoicflame** [comment]
This enhancement is currently seeking a sponsor. If anybody is willing to sponsor the work, [reach out to me](http://webcohesion.com/#contact) and I'd be happy to pick it up.

**Comment by fhm84** [comment]
I think in https://github.com/stoicflame/enunciate-openapi it's already present ... I created this PR https://github.com/stoicflame/enunciate-openapi/pull/44. What about just doing the same in here? Using this _enunciate-openapi_ module/plugin, we at tech11 currently just define it this way:
`<openapi disabled="false" basePath="..." securitySchemes="basicAuth,bearerAuth"/>`

**Comment by fhm84** [comment]
To get something like this in swaggerUI 
![grafik](https://github.com/stoicflame/enunciate/assets/4021301/40e67833-9fb3-453c-b350-3ad5437205c8)
 we could e.g. configure it in encunciate.xml. Like this:
![grafik](https://github.com/stoicflame/enunciate/assets/4021301/01ef0ed2-1231-4e0d-9166-8d64b2cecd3d)
What do you think @stoicflame ?

**Comment by stoicflame** [comment]
I like @fhm84's suggestion. It seems like now we're fully migrated onto OpenAPI 3.x we're in a good position to implement this feature.

**Comment by stoicflame** [comment]
Fixed with @fhm84 's PR #1191 .

**Comment by stoicflame** [comment]
[Enunciate 2.18.0](https://github.com/stoicflame/enunciate/releases/tag/v2.18.0) has been released.
