### ISSUE TITLE
support for responseExample/requestExample on custom data types

### ISSUE THREAD

**Issue by nbartels** [stoicflame/enunciate#674]
I added enunciate to our project and started to enhance a class with the custom Javadoc annotation. `@HTTP` worked fine and it looks overall rather good, but somehow the `@responseExample` and the `@requestExample` JavaDoc tags are ignored.

Although in the method's javadoc a line like this was added:
```
@responseExample application/json <valid json>
```

it evaluates to:

```
HTTP/1.1 200 OK
Content-Type: application/json
                
...
```

I changed the method signature so it returns a `Response` instead of the `Object`, but this makes no difference. Even moving to a file example is not working. I have not tested the classpath examples, yet.

This issue seems to be a part of #672. If there is more information needed (used jars, example method signature or something, just ask :wink: )

I'm using the jax-rs module.

**Comment by nbartels** [comment]
I'm not 100% sure, but somehow the `JaxrsApiRegistry` returns an empty set instead of set of  `Syntax` objects. Therefore the inner for-loop in `ResponseEntityImpl#getMediaTypes` don't adds a new `MediaTypeDescriptorImpl`. So no example is added, because the `CustomMediaTypeDescriptor` that is used instead returns null on getExample. 

I'll try to investigate this further ... but perhaps you can already correct my thoughts :wink:

**Comment by stoicflame** [comment]
Yeah, so the `@responseExample` doesn't get applied to custom data types.

Do you have a specific Java object that defines the JSON that is returned?

**Comment by nbartels** [comment]
No. Because I return a `Response` object or an `JSONObject`, I use `Response` or `Object` as return type in the signature. But imho this is the most interesting case for a custom `@responseExample`. So, what can I do?

**Comment by stoicflame** [comment]
I'll look into adding `@responseExample` support to custom data types for 2.10.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).

**Comment by lehoaitam** [comment]
hi @stoicflame,
currently i could use responseExample and requestExample javadoc tag, but what i could use is make directly the value of example in source code like 
	 _* @responseExample application/json;charset=UTF-8 { "result": [ {
	 *                  "studentId": "1",
	 *                  "courseId": [11,22], "Age": 25}]}_
When i put that response sample json content into seperate file like resources/studentServiceResponseSample.json in project. Then use classpath as
	 _* @responseExample application/json;charset=UTF-8
	 *                 classpath:/responseExample.json_
 i got 
**[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.10.1:docs (docs) on project analysis-webapp: Error invoking Enunciate. java.lang.NullPointerException: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class** 
Could you please help with some hint?
