### ISSUE TITLE
allow generating swagger.json avoiding allOf syntax

### ISSUE THREAD

**Issue by zjedi** [stoicflame/enunciate#675]
Is is possible to configure the swagger.json generator in a way that would avoid the `allOf` syntax? The client system I need to integrate with doesn't support this and I haven't found any configuration option to get around this. The closes I am is to do some post-processing using JOLT.

**Comment by stoicflame** [comment]
There's no option for this, no.

What would be used instead?

**Comment by zjedi** [comment]
I imagine that we could merge all the properties of the objects references via `allOf` and make it a flat, single object. It might cause some redundancy, but that's acceptable. That's what implementation from swagger.io does anyway. I'd like enunciate module to behave the same way.

**Comment by stoicflame** [comment]
There's an option to `collapse-type-hierarchy` if you want. See #375 and #408.

**Comment by zjedi** [comment]
But that's option of `<jackson` and `<jackson1`. I have those disabled since I am only interested in the swagger file. Are you saying that configuration of these influence also behaviour of the `<swagger` module?

**Comment by stoicflame** [comment]
Those modules are the JSON provider modules. They read your objects and describe the JSON your objects define. If you want Swagger to know how your API produces JSON, you have to enable those modules so that your JSON can be described. The `collapse-type-hierarchy` option will tell the Jackson modules to describe the JSON as if there is no type hierarchy.

**Comment by zjedi** [comment]
I was not successful with enunciate. Decided for swagger-maven-plugin and customize it the way we need.

**Comment by jyotirmoym** [comment]
Hi @zjedi - I am also facing the same problem and trying to avoid allOf syntax. Please could you suggest how did you configure/customize swagger-maven-plugin to achieve this?

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
