### ISSUE TITLE
Documentation isn't inherited

### ISSUE THREAD

**Issue by amberream** [stoicflame/enunciate#677]
I have an abstract service that is the parent of a few other services.  It contains fields that are shared with it's children, for example:

```
class AbstractService {
	/**
	 * The document's password.
	 */
	@HeaderParam("X-DocumentPassword")
	private String documentPassword;

	/**
	 * Path to the file to operate on.
	 */
	@PathParam("filePath")
	private String filePath;
}

class ChildService {
...
}

```
In the generated documentation for ChildService, filePath correctly shows up in the request parameters, but the description is empty.  Same case for header params.

**Comment by stoicflame** [comment]
I can't reproduce the problem, because those docs show up for me.

Tell me about `AbstractService`. Is it in another jar? If so, you need to make sure it's source file is discoverable according to [Discovering Source Files](https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files).

**Comment by amberream** [comment]
You're right, it was a configuration problem...
I had my abstract class in xxx.service and the child class in xxx.service.concrete and in my configuration I had xxx.service.concrete as the basedir.  When I changed the basedir to xxx.service it picks it up.
Would you consider this the correct behavior for my previous configuration?

**Comment by stoicflame** [comment]
Yes, it's the best Enunciate can do given the current constraints imposed by the JDK.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
