### ISSUE TITLE
HTML in parameter description

### ISSUE THREAD

**Issue by amberream** [stoicflame/enunciate#678]
It would be nice to be able to put a link in a parameter description. i.e. My java docs are marked up like this:

@param pageAction The PageAction.  One of OCRAction, TextStampAction, ImageStampAction, NewPageAction, InsertUploadedPagesAction, and InsertAttachedPagesAction.

This shows up fine under the request parameters of the documentation, but I'd really like to link to the models. i.e. something like this instead:

@param pageAction The PageAction.  One of <a href="json_OCRActionModel.html">OCRAction</a>, <a href="json_TextStampActionModel.html">TextStampAction</a>, etc...

**Comment by stoicflame** [comment]
See #174.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
