### ISSUE TITLE
Client API function names changed from v2.3

### ISSUE THREAD

**Issue by dschraitle** [stoicflame/enunciate#679]
Hello,
I just upgraded from Enunciate version 2.3 to 2.9.1, and I noticed that some of my projects using the JSON client API failed to compile due to the getters and setters changing their names. 

As an example, one of my getters for a field named `HARole`(the name hasn't changed) used to be: `getHARole()` in v2.3, but now it is: `getHarole()`. 

I realize I jumped quite a few versions, so I scanned through the release notes, but did not see anything that would indicate why this change was made. Was it intentional?

**Comment by dschraitle** [comment]
I narrowed it down to version 2.7 where this is introduced

**Comment by stoicflame** [comment]
I'm afraid I can't reproduce the problem.

When I apply this diff to the [enunciate-sample](https://github.com/stoicflame/enunciate-sample), the getter/setter is `getHARole()` in both 2.3.0 and 2.9.1.

Can you adjust my diff in a way that will expose the problem for me?

```diff
diff --git a/src/main/java/com/ifyouwannabecool/domain/persona/Name.java b/src/main/java/com/ifyouwannabecool/domain/persona/Name.java
index ac37d26..30de1f6 100644
--- a/src/main/java/com/ifyouwannabecool/domain/persona/Name.java
+++ b/src/main/java/com/ifyouwannabecool/domain/persona/Name.java
@@ -16,6 +16,8 @@
 
 package com.ifyouwannabecool.domain.persona;
 
+import com.fasterxml.jackson.annotation.JsonProperty;
+
 /**
  * A name of a persona.
  *
@@ -25,6 +27,8 @@ public class Name {
 
   private String givenName;
   private String surname;
+  @JsonProperty
+  private String HARole;
 
   /**
    * The given name.
```

**Comment by dschraitle** [comment]
Seems I was setting the json field name to lowercase using `@JsonProperty` on the getter in my original class. This diff reproduces it for me.

```diff
diff --git a/src/main/java/com/ifyouwannabecool/domain/persona/Name.java b/src/main/java/com/ifyouwannabecool/domain/persona/Name.java
index ac37d26..c104db0 100644
--- a/src/main/java/com/ifyouwannabecool/domain/persona/Name.java
+++ b/src/main/java/com/ifyouwannabecool/domain/persona/Name.java
@@ -16,6 +16,8 @@
 
 package com.ifyouwannabecool.domain.persona;
 
+import com.fasterxml.jackson.annotation.JsonProperty;
+
 /**
  * A name of a persona.
  *
@@ -25,6 +27,16 @@ public class Name {
 
   private String givenName;
   private String surname;
+  private String HARole;
+  
+  @JsonProperty(value="harole")
+  public String getHARole() {
+      return HARole;
+  }
+  
+  public void setHARole(String HARole) {
+      this.HARole = HARole;
+  }
 
   /**
    * The given name.
```

If instead, I put `@JsonProperty(value="harole")` on the field declaration, the generated getters/setters come out as before.

**Comment by stoicflame** [comment]
My best guess is that the change happened in association with cf36638cebaabe09df5b2eac18b867620622b9ab, which better aligns the property names with how Jackson was actually working.

I'll treat this as a bug for now and take a look for 2.10.

**Comment by stoicflame** [comment]
Okay, after looking more closely here, I think this is another case of confused property visibility (see [Property Visibility in the FAQ](https://github.com/stoicflame/enunciate/wiki/Property-Visibility). The adjustment at 2.7 was to align the property visibility with what Jackson is using.

Unfortunately, Enunciate was doing the wrong thing before and now it's doing the right thing. In this particular case, it resulted in a breakage of the generated client-side code.

I think you've got two choices:

1. Deal with the breakage.
2. Wait for 2.10 to be released and configure Enunciate to use a different visibility. (See #631)

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
