### ISSUE TITLE
Metadata annotations, retention

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#680]
I've just started using the metadata annotations (`@Label`, etc), and they work nice! I just have one question about the design of them. I see that the `@Retention` is `RetentionPolicy.RUNTIME`. Why is this? I would personally prefer if it was `RetentionPolicy.SOURCE`, so I could exclude `enunciate-core-annotations` from my container.

I'm just curious about the reason of this choice, that's all. :) Is there a specific reason?

**Comment by stoicflame** [comment]
I'll take a look into changing the retention policy for 2.10.

**Comment by leonard84** [comment]
@anton-johansson what kind of exception are you getting? Missing annotations should not cause any Exceptions unless they are explicitly used by other code. https://stackoverflow.com/questions/3567413/why-doesnt-a-missing-annotation-cause-a-classnotfoundexception-at-runtime

**Comment by anton-johansson** [comment]
Hmm, that is stange. But good to know!

I'm getting OSGi exceptions when running this in Karaf. I assume this is because `maven-bundle-plugin` sees the annotation packages and requires them as dependencies.

The exceptions I am getting is:
```
org.osgi.framework.BundleException: Unresolved constraint in bundle com.company.app.ui [278]: Unable to resolve 278.0: missing requirement [278.0] osgi.wiring.package; (&(osgi.wiring.package=com.company.app.auth)(version>=0.0.0)(!(version>=1.0.0))) [caused by: Unable to resolve 231.0: missing requirement [231.0] osgi.wiring.package; (&(osgi.wiring.package=com.company.app.domain)(version>=0.0.0)(!(version>=1.0.0))) [caused by: Unable to resolve 226.0: missing requirement [226.0] osgi.wiring.package; (&(osgi.wiring.package=com.company.app.domain)(version>=0.0.0)(!(version>=1.0.0))) [caused by: Unable to resolve 213.0: missing requirement [213.0] osgi.wiring.package; (&(osgi.wiring.package=com.webcohesion.enunciate.metadata)(version>=2.9.0)(!(version>=3.0.0)))]]]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4002)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2045)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1299)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Thread.java:745)
```

Part of `MANIFEST.MF` generated by `maven-bundle-plugin`:
```
Import-Package: com.company.app.commons;version="[0.0,1)",com.webcohesio
 n.enunciate.metadata;version="[2.9,3)"
```

Actually, I'm not sure if changing to `SOURCE` fixes this, it feels like an issue in the `maven-bundle-plugin`. @stoicflame, you might want to hold up on this issue then!

Feel free to close it.

**Comment by stoicflame** [comment]
Closing for now; I'm happy to re-open if any action is determined to be needed.
