### ISSUE TITLE
Missing Page or Bad Link for REST API 

### ISSUE THREAD

**Issue by nhhandyman** [stoicflame/enunciate#683]
The link on the upper corner of the screenshot image takes me to:
href="./EventSubscription" 

which does not exist.

I have a:
json_EventSubscription.Html

I am only generating docs (export artifactId="docs") and     

The modules part of my config is (I had to take the leading less-than off otherwise the text didn't show up).
	modules>
          c-xml-client disabled="true"/>
          csharp-xml-client disabled="true"/>
          gwt-json-overlay disabled="true"/>
          obj-c-xml-clent disabled="true"/>
          php-xml-client  disabled="true"/>
          php-json-client disabled="true"/>
          ruby-json-client disabled="true"/>
          idl disabled="true"/>
          swagger disabled="true"/>
          obj-c-xml-client disabled="true"/>
          java-xml-client      disableCompile="true"/>
	  docs
	       splashPackage="my.test.ws"
	       title="My Test API"
	       indexPageName="index.html"
	       javadocTagHandling="off"
	       copyright="Moe,Larry,Curley and Shemp." />
	/modules>

![screenshot from 2017-06-29 14 27 23](https://user-images.githubusercontent.com/29782888/27704075-4fe6960c-5cd7-11e7-9768-daff822b2a7a.png)

Thanks

**Comment by stoicflame** [comment]
So where does the `/EventSubscription` resource get mounted?

You need to adjust your application path to align with where your resources are mounted.

```xml
<enunciate>
  <modules>
    <jaxrs>
      <application path="/path/to/my/application"/>
```

Or something like that.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
