### ISSUE TITLE
Invalid Schema URL

### ISSUE THREAD

**Issue by leonard84** [stoicflame/enunciate#684]
The Schema URL (https://enunciate.webcohesion.com/schemas/enunciate-2.9.1.xsd) referenced here https://github.com/stoicflame/enunciate/wiki/User-Guide is invalid.

The SSL cert used is only valid for ` www.github.com, *.github.com, github.com, *.github.io, github.io, *.githubusercontent.com, githubusercontent.com`

The non-https variant (http://enunciate.webcohesion.com/schemas/enunciate-2.9.1.xsd) also doesn't work.

The `gh-pages` branch https://github.com/stoicflame/enunciate/tree/gh-pages/schemas is also missing the enunciate-2.9.1.xsd

**Comment by stoicflame** [comment]
Invalid reference. 2.9.1 uses the 2.9.0 schema. Fixed by updating the wiki.

http://enunciate.webcohesion.com/schemas/enunciate-2.9.0.xsd
