### ISSUE TITLE
Add disabledByDefault to modules tag in enunciate.xml

### ISSUE THREAD

**Issue by leonard84** [stoicflame/enunciate#688]
Currently `enunciate.xml`s often look like this (taken from #687 ):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.9.1.xsd">
	<api-classes>
		<include pattern="com.anachron.implementation.vit.rest.**" />
		<exclude pattern="com.anachron.implementation.vit.landing.**" />
	</api-classes>
	<modules>
		<!-- provider modules -->
		<jaxb disabled="true" />
		<jackson disabled="false" />
		<jackson1 disabled="true" />
		<jaxws disabled="true" />
		<jaxrs disabled="false" />
		<spring-web disabled="true" />
		<!-- non provider modules -->
		<c-xml-client disabled="true" />
		<csharp-xml-client disabled="true" />
		<docs disabled="false" />
		<java-xml-client disabled="true" />
		<java-json-client disabled="true" />
		<javascript-client disabled="false" />
		<gwt-json-overlay disabled="true" />
		<obj-c-xml-client disabled="true" />
		<php-xml-client disabled="true" />
		<php-json-client disabled="true" />
		<ruby-json-client disabled="false" />
		<idl disabled="true" />
		<swagger disabled="true" />
	</modules>
</enunciate>
```

As you can see only 5 modules are wanted and everything else needs to be disabled. It would be nice to have the option to invert this behavior by adding `disabledByDefault`, e.g. 

```xml
	<modules disabledByDefault="true">
		<!-- provider modules -->
		<jackson disabled="false" />
		<jaxrs disabled="false" />
		<!-- non provider modules -->
		<docs disabled="false" />
		<javascript-client disabled="false" />
		<ruby-json-client disabled="false" />
	</modules>
```

This reduces the amount of noise and also is future proof since only explicitly enabled modules are picked up. One thing that would read nicer but is not really required would be to add a `enabled` attribute, could be used instead of the `disabled` attribute to avoid the double negative.

I know that there is the slim plugin, but it is not convenient to use since you need to manually add the required dependencies. A common usecase is to use a maven profile in a common parent pom that activates on the existence of the `enunciate.xml` in the concrete project. Using the slim plugin is not flexible enough since, all subprojects would be constrained to the dependencies added in the parent pom and couldn't add another one without reconfiguring everything.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
