### ISSUE TITLE
Allow comments in json examples

### ISSUE THREAD

**Issue by wvlancke** [stoicflame/enunciate#689]
It would be nice to be able to include comments in the json examples for either @responseExample or @requestExample.

Currently an exception is thrown with the ALLOW_COMMENT directive:
Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)

**Comment by stoicflame** [comment]
After looking into this, it was determined that there was no way to implement this enhancement because the Jackson `JsonGenerator` doesn't support writing comments yet.

I'm happy to reopen if that feature is ever supported in Jackson.
