### ISSUE TITLE
Starting Enunciate out of Eclipse

### ISSUE THREAD

**Issue by Fival85** [stoicflame/enunciate#69]
Hello together,

I want to customize some parts of enunciate, but therefore I must debug enunciate to find the right way. I checked out the source. But if I start enunciate out of Eclipse to document your sample project "wannabecool" it doesn't generate a API. It will be generated a war file without any html files inside only. If I start enunciate out of maven (mvn clean install the "wannabecool" project), the API-Html files will be generated. I do not really know, what I did wrong....  

I am using following configuration to start enunciate out of eclipse:
-vv 
-f C:\temp\enunciate\enunciate-1.30-RC1\enunciate-1.30-RC1\samples\wannabecool\src\conf\enunciate.xml 
-g C:\temp\enunciate\work\generated 
-c C:\temp\enunciate\work\compiled 
-b C:\temp\enunciate\work\build 
-p C:\temp\enunciate\work\package  
C:\temp\enunciate\enunciate-1.30-RC1\enunciate-1.30-RC1\samples\wannabecool\src\main\java\org\codehaus\enunciate\api\ExclusiveGroupException.java
C:\temp\enunciate\enunciate-1.30-RC1\enunciate-1.30-RC1\samples\wannabecool\src\main\java\org\codehaus\enunciate\api\PermissionDeniedException.java
C:\temp\enunciate\enunciate-1.30-RC1\enunciate-1.30-RC1\samples\wannabecool\src\main\java\org\codehaus\enunciate\api\PersonaService.java
C:\temp\enunciate\enunciate-1.30-RC1\enunciate-1.30-RC1\samples\wannabecool\src\main\java\org\codehaus\enunciate\api\SocialGroupService.java
C:\temp\enunciate\enunciate-1.30-RC1\enunciate-1.30-RC1\samples\wannabecool\src\main\java\org\codehaus\enunciate\domain\link\Link.java
C:\temp\enunciate\enunciate-1.30-RC1\enunciate-1.30-RC1\samples\wannabecool\src\main\java\org\codehaus\enunciate\domain\link\SocialGroup.java
C:\temp\enunciate\enunciate-1.30-RC1\enunciate-1.30-RC1\samples\wannabecool\src\main\java\org\codehaus\enunciate\domain\persona\Name.java
C:\temp\enunciate\enunciate-1.30-RC1\enunciate-1.30-RC1\samples\wannabecool\src\main\java\org\codehaus\enunciate\domain\persona\Persona.java
C:\temp\enunciate\enunciate-1.30-RC1\enunciate-1.30-RC1\samples\wannabecool\src\main\java\org\codehaus\enunciate\impl\PersonaServiceImpl.java
C:\temp\enunciate\enunciate-1.30-RC1\enunciate-1.30-RC1\samples\wannabecool\src\main\java\org\codehaus\enunciate\impl\SocialGroupServiceImpl.java

Eclipse starts the enunciate project, but the produced war file hasn't any html files inside. There are no errors in the log.

Could anybody helps me?

Greetings
Fival

**Comment by Fival85** [comment]
I am using enunciate-1.3-RC1 but the generated war file "wannabecool.war"  has only following content inside:
- WEB-INF
 * lib -> all libs
 * classes -> the wannabecool project and some other (for me) unknown classes
 * web.xml
- META-INF

But if I build the wannabecool with maven:
- WEB-INF
 * lib -> many more libs than with eclipse
 * classes -> only the wannabecool project and some .list and .properties files
 * web.xml
 * sun-jaxws.xml
- META-INF like before
- js (missing in eclipse)
- css (missing in eclipse)
- some html files... the docu (missing in eclipse)

**Comment by stoicflame** [comment]
Hi.

I'm not an Eclipse user, so I'm afraid I'm not going to be very helpful, but I'll help where I can. Are you trying to run the command-line script from Eclipse? Have you tried it from the command line to see if it works?

**Comment by Fival85** [comment]
Thank you very much. I started enunciate out of a run-configuration (calling the main class with the arguments). I am not using the script. But the script helps, because I see that I forget to set the classpath correct. Now I could use it :)
