### ISSUE TITLE
How to fail maven build?

### ISSUE THREAD

**Issue by Thorndike** [stoicflame/enunciate#690]
More often then not enunciate refuses to generate a report at all due to some problem with the parsed data. This is fine, usually it does not understand something and it's our fault. The problem is that our jenkins build job does not fail during the maven site build which usually leaves the missing enunciate report undetected.

Is there a way to have the maven build fail if the enunciate report could not be generated?

Using enunciate-maven-plugin:2.9.1

**Comment by stoicflame** [comment]
I didn't know it worked that way.

So this is in the Maven report plugin?

**Comment by Thorndike** [comment]
I don't know how it is rated internally but the output goes to the report section so in my understanding it is a report plugin. The last error I encountered with a successfull maven build but without any enunciat doc was this:
`[WARNING] [ENUNCIATE] Some source files were not found for the Java classes that define the Web service API.
12:01:59 [WARNING] [ENUNCIATE] Enunciate will be unable to find the documentation for the classes that are missing source files. (For details, rebuild with debug-level logging.)
12:01:59 [WARNING] [ENUNCIATE] In order for Enunciate to find the source files for API classes that are not being compiled in the current project, the source file must be on the Enunciate sourcepath and the class must be explicitly included in the Enunciate configuration.
12:01:59 [WARNING] [ENUNCIATE] For more information, see https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files
12:02:02 [WARNING] [ENUNCIATE] Error processing /home/jenkins/jenkins/workspace/ApplicationServices/ASK_AUSKUNFT_SITE_DEV/api/target/enunciate-docs-staging/webservicedocs/ui/swagger.json.
12:02:02 [ERROR] Error invoking Enunciate.
12:02:02 org.apache.maven.plugin.MojoExecutionException: com.fasterxml.jackson.core.JsonParseException: Invalid numeric value: Leading zeroes not allowed
12:02:02  at [Source: java.io.FileReader@12f30953; line: 1912, column: 26]
12:02:02 	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:406)
12:02:02 	at com.webcohesion.enunciate.mojo.DocsBaseMojo.canGenerateReport(DocsBaseMojo.java:172)
12:02:02 	at org.apache.maven.reporting.exec.MavenReportExecution.canGenerateReport(MavenReportExecution.java:89)
12:02:02 	at org.apache.maven.plugins.site.render.AbstractSiteRenderingMojo.getReports(AbstractSiteRenderingMojo.java:267)
12:02:02 	at org.apache.maven.plugins.site.render.SiteMojo.execute(SiteMojo.java:115)
12:02:02 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
12:02:02 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
12:02:02 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
12:02:02 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
12:02:02 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
12:02:02 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
12:02:02 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
12:02:02 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
12:02:02 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
12:02:02 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
12:02:02 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
12:02:02 	at org.jvnet.hudson.maven3.launcher.Maven33Launcher.main(Maven33Launcher.java:129)
12:02:02 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:02:02 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:02:02 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:02:02 	at java.lang.reflect.Method.invoke(Method.java:498)
12:02:02 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
12:02:02 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
12:02:02 	at jenkins.maven3.agent.Maven33Main.launch(Maven33Main.java:176)
12:02:02 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
12:02:02 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
12:02:02 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
12:02:02 	at java.lang.reflect.Method.invoke(Method.java:498)
12:02:02 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
12:02:02 	at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
12:02:02 	at hudson.remoting.UserRequest.perform(UserRequest.java:153)
12:02:02 	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
12:02:02 	at hudson.remoting.Request$2.run(Request.java:336)
12:02:02 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
12:02:02 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12:02:02 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
12:02:02 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
12:02:02 	at java.lang.Thread.run(Thread.java:748)
12:02:02 Caused by: com.webcohesion.enunciate.EnunciateException: com.fasterxml.jackson.core.JsonParseException: Invalid numeric value: Leading zeroes not allowed
12:02:02  at [Source: java.io.FileReader@12f30953; line: 1912, column: 26]
12:02:02 	at com.webcohesion.enunciate.modules.docs.DocsModule.call(DocsModule.java:336)
12:02:02 	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:46)
12:02:02 	at com.webcohesion.enunciate.io.InvokeEnunciateModule.onNext(InvokeEnunciateModule.java:25)
12:02:02 	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:80)
12:02:02 	at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
12:02:02 	at rx.Subscriber.setProducer(Subscriber.java:209)
12:02:02 	at rx.Subscriber.setProducer(Subscriber.java:205)
12:02:02 	at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:111)
12:02:02 	at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.emit(OperatorTakeLastOne.java:175)
12:02:02 	at rx.internal.operators.OperatorTakeLastOne$ParentSubscriber.onCompleted(OperatorTakeLastOne.java:141)
12:02:02 	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:648)
12:02:02 	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:560)
12:02:02 	at rx.internal.operators.OperatorMerge$MergeSubscriber.onCompleted(OperatorMerge.java:281)
12:02:02 	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:82)
12:02:02 	at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
12:02:02 	at rx.Subscriber.setProducer(Subscriber.java:211)
12:02:02 	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
12:02:02 	at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
12:02:02 	at rx.Observable.unsafeSubscribe(Observable.java:8460)
12:02:02 	at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
12:02:02 	at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
12:02:02 	at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
12:02:02 	at rx.Observable.unsafeSubscribe(Observable.java:8460)
12:02:02 	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
12:02:02 	at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
12:02:02 	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastpath(OnSubscribeFromIterable.java:172)
12:02:02 	at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:85)
12:02:02 	at rx.Subscriber.setProducer(Subscriber.java:211)
12:02:02 	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:62)
12:02:02 	at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
12:02:02 	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
12:02:02 	at rx.Observable.subscribe(Observable.java:8553)
12:02:02 	at rx.Observable.subscribe(Observable.java:8520)
12:02:02 	at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:433)
12:02:02 	at rx.observables.BlockingObservable.single(BlockingObservable.java:332)
12:02:02 	at com.webcohesion.enunciate.EnunciateAnnotationProcessor.process(EnunciateAnnotationProcessor.java:122)
12:02:02 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
12:02:02 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
12:02:02 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
12:02:02 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
12:02:02 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
12:02:02 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
12:02:02 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
12:02:02 	at com.sun.tools.javac.main.Main.compile(Main.java:523)
12:02:02 	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
12:02:02 	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
12:02:02 	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:674)
12:02:02 	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:401)
12:02:02 	... 37 more
12:02:02 Caused by: com.fasterxml.jackson.core.JsonParseException: Invalid numeric value: Leading zeroes not allowed
12:02:02  at [Source: java.io.FileReader@12f30953; line: 1912, column: 26]
12:02:02 	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
12:02:02 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
12:02:02 	at com.fasterxml.jackson.core.base.ParserBase.reportInvalidNumber(ParserBase.java:995)
12:02:02 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._verifyNLZ2(ReaderBasedJsonParser.java:1163)
12:02:02 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._verifyNoLeadingZeroes(ReaderBasedJsonParser.java:1150)
12:02:02 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseNumber2(ReaderBasedJsonParser.java:1027)
12:02:02 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parsePosNumber(ReaderBasedJsonParser.java:853)
12:02:02 	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:680)
12:02:02 	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:216)
12:02:02 	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
12:02:02 	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
12:02:02 	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeArray(JsonNodeDeserializer.java:267)
12:02:02 	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:227)
12:02:02 	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
12:02:02 	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
12:02:02 	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:62)
12:02:02 	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:14)
12:02:02 	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
12:02:02 	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2106)
12:02:02 	at com.webcohesion.enunciate.modules.swagger.SwaggerDeploymentModule$SwaggerInterfaceDescription.writeTo(SwaggerDeploymentModule.java:199)
12:02:02 	at com.webcohesion.enunciate.modules.docs.DocsModule.call(DocsModule.java:303)
12:02:02 	... 97 more
12:02:02 Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
12:02:02 	at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
12:02:02 	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:192)
12:02:02 	at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:82)
12:02:02 	... 94 more
12:02:02 [WARNING] No project URL defined - decoration links will not be relativized!`

**Comment by stoicflame** [comment]
I've started looking into this, but I'm going to need more information about how your `pom.xml` is set up.

Is there any way you could put together a patch or pull request for the [Enunciate Sample](https://github.com/stoicflame/enunciate-sample) app that demonstrates the problem.

**Comment by stoicflame** [comment]
Moving to 2.11.

**Comment by Thorndike** [comment]
We have a simple enunciate configuration as part of the reporting section.

`  <reporting>
    <outputDirectory>****/target/site</outputDirectory>
    <plugins>
      <plugin>
        <artifactId>maven-jxr-plugin</artifactId>
        <version>2.5</version>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>jdepend-maven-plugin</artifactId>
        <version>2.0</version>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>cobertura-maven-plugin</artifactId>
        <version>2.7</version>
      </plugin>
      <plugin>
        <artifactId>maven-pmd-plugin</artifactId>
        <version>3.6</version>
        <configuration>
          <targetJdk>1.8</targetJdk>
          <rulesets>
            <ruleset>***/../favorite-pmd.xml</ruleset>
          </rulesets>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>findbugs-maven-plugin</artifactId>
        <version>3.0.4</version>
      </plugin>
      <plugin>
        <artifactId>maven-javadoc-plugin</artifactId>
        <reportSets>
          <reportSet>
            <id>non-aggregate</id>
            <reports>
              <report>javadoc</report>
              <report>test-javadoc</report>
            </reports>
            <configuration></configuration>
          </reportSet>
          <reportSet>
            <id>aggregate</id>
            <reports>
              <report>aggregate</report>
              <report>test-aggregate</report>
            </reports>
            <configuration></configuration>
          </reportSet>
        </reportSets>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-report-plugin</artifactId>
        <version>2.19.1</version>
      </plugin>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <reportSets>
          <reportSet>
            <reports>
              <report>report</report>
            </reports>
            <configuration>
              <dataFile>***/target/coverage-reports/jacoco-ut.exec</dataFile>
              <outputDirectory>***/target/site/jacoco-ut</outputDirectory>
            </configuration>
          </reportSet>
        </reportSets>
        <configuration>
          <dataFile>****/target/coverage-reports/jacoco-ut.exec</dataFile>
          <outputDirectory>***/target/site/jacoco-ut</outputDirectory>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-changes-plugin</artifactId>
        <reportSets>
          <reportSet>
            <reports>
              <report>changes-report</report>
            </reports>
          </reportSet>
        </reportSets>
      </plugin>
      <plugin>
        <groupId>com.webcohesion.enunciate</groupId>
        <artifactId>enunciate-maven-plugin</artifactId>
        <version>2.9.1</version>
        <configuration>
          <docsSubdir>webservicedocs</docsSubdir>
          <indexPageName>index.html</indexPageName>
          <sourcepath-includes>
            <include>
              <groupId>de.creditreform.ask.auskunft</groupId>
            </include>
            <include>
              <groupId>de.creditreform.ask.base</groupId>
            </include>
            <include>
              <groupId>de.creditreform.cr.base</groupId>
            </include>
          </sourcepath-includes>
          <sourcepath-excludes>
            <exclude>
              <groupId>de.creditreform.cr.base</groupId>
              <artifactId>service</artifactId>
            </exclude>
          </sourcepath-excludes>
        </configuration>
      </plugin>
    </plugins>
  </reporting>
`

Our problem is that the report section is generated without any obvious problems but the resulting site is missing the enunciate part due to the errors (those are just an example from the last failure) listed in the first post.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
