### ISSUE TITLE
JSON Data Types are missing documentation

### ISSUE THREAD

**Issue by amberream** [stoicflame/enunciate#691]
My java classes for JSON objects have javadocs on the class and on the fields.  For example:

```
/**
 * This action contains information to place a text stamp on one or more pages.
 */
@XmlType(name="TextStampAction")
@XmlRootElement(name="TextStampAction")
public class TextStampActionModel extends StampActionModel
{
	/**
	 * Text to write.
	 */
	public String text = "";
	
	/**
	 * Text color.
	 */
	public String color = "#000000";
	... 
}
```
The resulting Enunciate documentation doesn't display anything in the description column for each property or anything about the model as in general (I'd expect to see the javadocs for the class).

**Comment by stoicflame** [comment]
What about that class makes you expect it to be in the documentation? Is it an input or output to a JAX-RS method? Is it referenced by other classes?

**Comment by amberream** [comment]
The class is in the documentation under JSON as expected.  I have some objects that are used as inputs to a JAX-RS method and some are outputs to JAX-RS methods.  They all have documentation in the java code but none of them have descriptions in the Enunciate docs.

**Comment by stoicflame** [comment]
I see.

Have you read through the [FAQ entry on this issue](https://github.com/stoicflame/enunciate/wiki/Discovering-Source-Files)? Are you sure the jar is on the classpath and that it's included in the `api-classes` configuration element?

**Comment by amberream** [comment]
Sorry for the delay... I read the FAQ and added the source path to my ant build file, but still not having any luck with seeing the descriptions in the documentation.  Here's what my build file looks like.  All my source lives in subdirectories of 'com'.  I've tried several variations of this, none of which seem to work...  Do you have an sample that works?

		<path id="enunciate.sourcepath">
			<fileset dir="com" includes="**/*"/>
		</path>

		<enunciate2 basedir="com/qoppa/jaxrs/service" buildDir="build-output/enunciate" configFile="build/enunciate-qoppapdf.xml">
			<include name="**/*.java" />
			<classpath refid="compile.classpath" />
			<sourcepath refid="enunciate.sourcepath"/>
			<javacArgument argument="-g" />
		</enunciate2>

**Comment by stoicflame** [comment]
Sure, the [sample app](https://github.com/stoicflame/enunciate-sample) works.

Can you provide a patch to the sample app that reproduces the problem?

**Comment by amberream** [comment]
I finally got this working.  
My project is set up with the json models in ...jaxrs.models and the services are in ...jaxrs.service. It seems the configuration I tried in my previous comment didn't work because the basedir was set to jaxrs.service rather than jaxrs even though the sourcepath started at a higher parent dir.  The working config looks like this:

    <path id="enunciate.sourcepath">
        <fileset dir="com/qoppa/jaxrs">
        <include name="**/*.java" />
        </fileset>
    </path>

    <enunciate2 basedir="com/qoppa/jaxrs" buildDir="build-output/enunciate" configFile="build/enunciate-qoppapdf.xml">
        <include name="**/*.java" />
        <classpath refid="compile.classpath" />
        <sourcepath refid="enunciate.sourcepath"/>
        <javacArgument argument="-g" />
    </enunciate2>

**Comment by stoicflame** [comment]
Thanks for the report!
