### ISSUE TITLE
Ignore more JAX-RS Method Parameter

### ISSUE THREAD

**Issue by thomasletsch** [stoicflame/enunciate#693]
I have a dropwizard application with jax-rs support. 
Dropwizard has an @io.dropwizard.auth.Auth annotation for user principals. This param should not be documented as request param by enunciate. It gets populated by dropwizard auth modules and should not send by the user.

It would be great to have these parameters excluded automatically or being able to use the @Ignore annotation on Method parameters as well.

**Comment by stoicflame** [comment]
Use the [`custom-system-parameter-annotation`](https://github.com/stoicflame/enunciate/wiki/Module-JAXRS#custom-system-parameter-annotation) configuration element.

```xml
<enunciate>
  <modules>
    <jaxrs>
      <custom-system-parameter-annotation qualifiedName="io.dropwizard.auth.Auth"/>
```

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
