### ISSUE TITLE
Support for ignoring class / method based on javadoc tag

### ISSUE THREAD

**Issue by glb** [stoicflame/enunciate#694]
You have great support in a bunch of places for using _either_ a javadoc tag or an annotation to control  Enunciate's behaviour.

Would you consider an `@ignore` javadoc tag to tell Enunciate to skip a class or method similar to the `@Ignore` annotation described in [Excluding Including Classes](https://github.com/stoicflame/enunciate/wiki/Excluding-Including-Classes)? 

I've found `IgnoreUtils#isIgnored(Element)` and will see what I can figure out.

**Comment by stoicflame** [comment]
Sure, we can consider that for 2.10.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).

**Comment by glb** [comment]
Thanks @stoicflame !
