### ISSUE TITLE
@Produces with additional parameters dont show up if they have different values

### ISSUE THREAD

**Issue by mwalden** [stoicflame/enunciate#696]
# Example
```
@Produces({ MediaType.APPLICATION_JSON, "application/vnd.company+json;version=3.1","application/vnd.company+json;version=3.2","application/vnd.company+json;version=3.3"})
```

This will produce application/json and only one application/vnd.company+json;version=3.1. The other versions will not show up as an option in the drop down. 

I believe this is because in JaxrsUtil.java, you are passing a map with the param as the key and the paramValue. However, it would be ideal if it were a list so you could have all three versions show up as an option. 

The only way I can get the different values to show up is if I change it to 
```
@Produces({ MediaType.APPLICATION_JSON, "application/vnd.company+json;version1=3.1","application/vnd.company+json;version2=3.2","application/vnd.company+json;version3=3.3"}).
```
This is because "version" would be the key in the map that JaxrsUtil returns in MediaType.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
