### ISSUE TITLE
WADL representation of JSON elements

### ISSUE THREAD

**Issue by karlDallas** [stoicflame/enunciate#697]
Hi!

I've run into the same problem as described in issue [Incorrect WADL representation for requests and responses](https://github.com/stoicflame/enunciate/issues/47).

Is there somekind of workaround to link the wadl-representation to the appropriate xsd element, eventhough the mediatype is JSON?

**Comment by stoicflame** [comment]
What would an XSD element for a JSON data type look like?

**Comment by karlDallas** [comment]
I'd gladly take the XSD elements that are being generated by the idl module as it is.
I know that the two technologies don't mix, but it would atleast be _some_ description of the transfer objetcts, rather than none.
The Jersey wadl generator for example simply uses the same representation element for both XML and JSON.

**Comment by stoicflame** [comment]
As of 7a9f985:

```xml
<enunciate>
  <modules>
    <idl linkJsonToXml="true"/>
```

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
