### ISSUE TITLE
Include in <api-classes> not working as (I would) expect

### ISSUE THREAD

**Issue by leforthomas** [stoicflame/enunciate#698]
I have a class which I would like to include in my exported jackson jar but it is not directly used by my API, so it is not caught at the moment of generating the doc etc... from the API.
I saw the api-classes element and the ability to specify which classes should be included or excluded, which is great. So I added my class as follows

```
    <api-classes>
        <include pattern="com.geocento.webapps.earthimages.productdownloader.api.ProductDownloaderResource"></include>
        <include pattern="com.geocento.webapps.earthimages.productdownloader.api.dtos.DownloadStatus"></include>
    </api-classes>


```

The ProductDownloaderResource is the API class and the DownloadStatus is the class I would like to include in the jar.

Problem: it doesn't get included. Do I need to specify something else?

Thanks!

**Comment by stoicflame** [comment]
You could try an aggressive datatype detection strategy:

```xml
<enunciate>
  <modules>
    <jackson datatype-detection="aggressive"/>
    <jackson1 datatype-detection="aggressive"/>
```

Or using the `@JsonSeeAlso` annotation on a class or resource method that _is_ getting included.

**Comment by leforthomas** [comment]
Brilliant, the JsonSeeAlso did the trick. The aggressive attribute did a bit too much for my needs ;-)

Many thanks!
