### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by Ingwersaft** [stoicflame/enunciate#707]
Hi!

I love Enunciate and use it extensively, really awesome tool!
I was wondering if you plan on supporting Kotlin (or maybe is it already possible?) in the future?
Only way to make it work currently is if the classes are in bytecode form, e.g. from another module, but it would be really cool if the actual (JAX-RS) API can be written in Kotlin and parsed by Enunciate aswell.

Thanks in advance for your time! :)

**Comment by stoicflame** [comment]
Cool idea. I've done a bit of research and sadly I can't find any compiler API for Kotlin. [This guy asked the question and there is still no response](https://discuss.kotlinlang.org/t/kotlin-compiler-api/3478).

Without a compiler API, Enunciate has no way of parsing the object structures, annotations, or documentation from source code. So for now, I'm going to have to close this as not feasible. I'm happy to reopen and reconsider if Kotlin ever provides a compiler API.

As you mention, there's always the possibility that Enunciate could consume Kotlin's compiled bytecode and generate some documentation from it, but it would be without the benefits of the full source code.

**Comment by Ingwersaft** [comment]
I only found this [antlr grammar](https://github.com/antlr/grammars-v4/tree/master/kotlin), but I had some problems getting the antlr setup working when playing around with this, but there's nothing official (yet), you're right.

**Comment by thomasletsch** [comment]
Perhaps there is a different approach possible:
There is the project Dokka which is the Kotlin version of Javadoc. It uses something which they call Kotlin as a service to parse the Kotlin Structure:
https://github.com/Kotlin/dokka#documentation-model

Apparently this is the main Class for that:
https://github.com/Kotlin/dokka/blob/master/core/src/main/kotlin/Analysis/AnalysisEnvironment.kt

Don't know if this is a way to go, but I really would love to have Kotlin support in enunciate.

**Comment by stoicflame** [comment]
I appreciate the pointer.

Unfortunately, I can't find any documentation on how to use "Kotlin as a service" to parse the documentation model, which is what Enunciate is going to need.

Do you see anything I don't?
