### ISSUE TITLE
Milestone for v2.0

### ISSUE THREAD

**Issue by stokito** [stoicflame/enunciate#71]
As I see, started work on migration to version 2.0
The main improvement of this version should be using of JSR 269 Annotation processing and JSR 166 Compiler API instead of deprecated and removed in JDK8 Sun APT tool.

Currently migrated modules are:
```xml
  <modules>
    <module>core-annotations</module>
    <module>models</module>
    <module>core</module>
    <module>jaxb</module>
  </modules>
```

I don't know are they completely migrated or not. If yes, could you release them to RC version?
Also I'm interested in `maven-enunciate-slim-plugin` and `maven-enunciate-plugin` bit as I see work wasn't started yet.

To track all work on this it would be great to create milestone in Github issues tracker

**Comment by stoicflame** [comment]
See [the comment at #68](https://github.com/stoicflame/enunciate/issues/68#issuecomment-88619434). The v2 work hasn't reached the maven plugins yet.

I like your suggestions about breaking down the issues into GH milestones. I've added #68 to the new milestone. I'll try to get the time to scrub through the issues to assign them labels and milestones.
