### ISSUE TITLE
Access annotations in fmt. I saw #401  . Not tested pseudocode is not work

### ISSUE THREAD

**Issue by janmaslik** [stoicflame/enunciate#710]
Hi , 
i have 2 issues i would like to share:

**1/**
**Description of my issue :** 

Definition of my  DTO class:
```
@XmlRootElement(name = "deviceProperty" )
@XmlAccessorType(XmlAccessType.NONE)
public class PropertyDTO {}
```

example looks correct:

```
{
  "deviceProperty" : {}
}

```

however in swagger.json is property name defined as "json_PropertyDTO" ( ${dataype.slug} ).
Im generating clients from that file, therefore is important for me.
Another ,probably best solution:  freemarker has access to value which is used in example.

**2/** access to class&method names of annotated resources would be also nice
**Description of my issue :** 
Resource methods are defined in swagger.json as operationId attribute. Enunciate generated that id to be unique, but its not good as method name on client side.  I was able to change that by @ResourceLabel annotation. However it would be nice if i can decide what to use in freemarker template. All i need is access to method name.

Im using 2.91 version from maven central  repository

**Comment by janmaslik** [comment]
This example from #401 not work.

[#list type.annotations["com.mycompany.annotations.MyAnnotation"].elementValues?keys as annotationElement]
${type.annotations["com.mycompany.annotations.MyAnnotation"].elementValues[annotationElement]}[/#list]

freemarker converts keys to some hash, Key have to be string to make it work for 2.3.23 version of freemarker.

**Comment by janmaslik** [comment]
point 1 i was able to make work. 
The issue was wrapping of root name in swagger.json . I created another "wrap" definition for each definition annotated by @XmlRootElement and connect it to original one by @XmlRootElement.value()  .  "Wrap" definitions are used as property and responses of operations. Now swagger codegen generate proper client code.

If there is a cleaner way ,  please let me know.
`
"${dataType.slug}" : {
.....
}
[#if dataType.annotations["javax.xml.bind.annotation.XmlRootElement"]?? && syntaxIsJson ]
	,
	"${dataType.slug}Wrap" : {  
	  "type" : "object",
      "title" : "${dataType.label?json_string}",
      "description": "Wrapper of ${dataType.label?json_string}"  ,	
          	[#assign nameIndex=-1/]	
          	[#assign index=-1/]	
	   "properties": {
	      	[#list dataType.annotations["javax.xml.bind.annotation.XmlRootElement"].elementValues?keys as annotationElement]
	      		[#assign index++]
	      		[#if annotationElement.simpleName == "name" ]
	      			[#assign nameIndex=index]
	      			[#break]
	        	[/#if]
	  	  	[/#list]
	  	  	[#assign index=-1/]	
	      	[#list dataType.annotations["javax.xml.bind.annotation.XmlRootElement"].elementValues?values as annotationElement]
	      		[#assign index++]
	      		[#if index == nameIndex ]
			"${ annotationElement.value }" :{
		   		"$ref" : "#/definitions/${dataType.slug}"  		
			} 
	      			[#break]
	      		[/#if]
			[/#list]
	   	}   		
	}
		[/#if]
`
//set _${dataType.slug}Wrap_  to response&property $ref

**Comment by stoicflame** [comment]
I can't quite tell, but it looks like you're interested in supporting the JSON "root name". If that's the case, see #609.

At 8209877 I added another support method to make getting annotation values by name easier. So now you should be able to just do something like:

```
dataType.annotations["javax.xml.bind.annotation.XmlRootElement"].elementValuesByName["name"].value
```

rather than iterating through the element values.
