### ISSUE TITLE
2.9.1: list with generic parameter transform as object in swagger.json

### ISSUE THREAD

**Issue by janmaslik** [stoicflame/enunciate#713]
Hi, 

This example : 
```
@XmlRootElement(name = "pagedData" )
@XmlAccessorType(XmlAccessType.NONE)
public class PagedData<T> 
{
	
	@XmlElements({
		@XmlElement(name="string", type=String.class),
		@XmlElement(name="shop", type=ShopDTO.class),
	})
	@XmlElement(name="shop")
	protected List<ShopDTO> records;
	
	@XmlElement
	protected Long totalElements;
....
}
```
transform to:
```
              properties:
                     string:
                       description: ''
                       type: string
                     shop:
                       description: ''
                       $ref: '#/definitions/json_ShopDTO'
                     totalElements:
                       description: ''
                       type: number
```

missing array type for shop and string property.

Also creates definition json_PagedData + definition for each generic param:  json_PagedDataOfShopDTO , json_PagedDataOfString . All of this generic -definitions contains all generic-properties. I expects that  json_PagedDataOfShopDTO would contain only shop + totalElements properties.

**Comment by stoicflame** [comment]
Fixed the array type problem at 30db7f0.

As for the generic definition problem, I don't understand the basis for asserting that `json_PagedDataOfShopDTO` would only contain "shop + totalElements" properties.  Why would it _not_ be able to contain "string" properties?

I think what you're saying is that your business logic dictates that PagedData<ShopDTO> will _only_ contain `ShopDTO` elements. But there's no way for Enunciate to determine that at compile-time.

**Comment by janmaslik** [comment]
Hi, thanks for response and fix my friend.

To answer second part:
Enunciate already creates PagedData for each generic type. In this example called  json_PagedDataOfShopDTO and json_PagedDataOfString . 

I expected
json_PagedDataOfShopDTO  { shop, totalElements } 
json_PagedDataOfString (string,totalElements}

Instead i got:
json_PagedDataOfShopDTO  { shop,string, totalElements } 
json_PagedDataOfString (shop, string,totalElements}

So they are just duplicates contains all possibilities.
This logic is transfered to swagger.json and then into generated client. Which may be confusing for people who using it.

**Comment by stoicflame** [comment]
I understand. 

Unfortunately, there's no way for Enunciate to determine that you'd like the `string` property to disappear in the context of the `json_PagedDataOfShopDTO` and the `shop` property to disappear in the context of the `json_PagedDataOfStringDTO`. The fact that those properties "disappear" is determined entirely at runtime.

**Comment by stoicflame** [comment]
On second thought, there might be a way to exclude those choices in the context of a parameterized synthetic type. It would be complex and tricky, but if you'd like to open a separate enhancement request, we could track that work.

I guess it depends on how much you care about it.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
