### ISSUE TITLE
"Description" not compiled  for DO if member is "private"

### ISSUE THREAD

**Issue by tierox** [stoicflame/enunciate#715]
enunciate version 2.9.1
build tool: Maven
Hi I have experimented the following behaviour:

My POJO:
public class DocumentDO
{
    /**
     * Document's id
     */
    private Long id;
    /**
     * Document's size
     */    
    private Long size;
    /**
     * Related Track id
     */    
    private Long trackId;
    /**
     * Document's File Path
     */      
    private String filePath;
    /**
     * Document's start date
     */       
    @DocumentationExample(type=@TypeHint(String.class), value="04/04/2017 14:51:36")    
    private Date startDate;
    /**
     * Document's sequence number
     */    
    private Long documentSequenceNumber;

    public Date getStartDate()
    {
        return startDate;
    }

    public void setStartDate(Date startDate)
    {
        this.startDate = startDate;
    }

and so on....
If and only if member is "public" ,"description" field is present elsewhere it is empty.
I've experimented the same behavior whit 
@DocumentationExample(type=@TypeHint(String.class), value="04/04/2017 14:51:36")  annotation.

Is it a configuration Issue or is it a Bug?
Thanks in advance.

**Comment by stoicflame** [comment]
See ["Property Visibility"](https://github.com/stoicflame/enunciate/wiki/Property-Visibility) in the FAQ.

**Comment by tierox** [comment]
Thank you very much for ultra fast answer. Moving JavaDOC to getter it seems to work.
