### ISSUE TITLE
jackson polymorphism

### ISSUE THREAD

**Issue by janmaslik** [stoicflame/enunciate#716]
Hi ,

i have definition :
![code](https://user-images.githubusercontent.com/30992729/29887967-7a28c444-8dbf-11e7-8076-03f22efe6834.png)

Problem : jackson2 wraps implementation classes into 'criteria' property (example part of the last screenshot) . 
However enunciate put them to root level in documentation and also in swagger.json .

![enunciate](https://user-images.githubusercontent.com/30992729/29887765-cdd73162-8dbe-11e7-9639-77963b37ceb7.png)

**Comment by janmaslik** [comment]
Is there something i have to setup or ?

**Comment by janmaslik** [comment]
I tried to move @JsontypeInfo & @JsonSubTypes at abstract class declaration 'ExpressionPrime'.
In that case 'criteria' property appears. However enunciate and swagger are not able to see mappings. Generated client code expects 'ExpressionPrime' class and other fields are lost during serialization.

There are few ways how process polymorphism in jackson. I dont have prefered json output. I just need make this work : 
1/ correct documentation reflects json output
2/ correct swagger.json reflects json output

**Comment by stoicflame** [comment]
Yes, JSON polymorphism is ugly.

What you see is the best I've been able to figure out without losing significant documentation information. When `JsonTypeInfo.As` is `WRAPPER_ARRAY` or `WRAPPER_OBJECT`, I can't think of a better way to describe the property choices. If the documentation were completely accurate, there would only be a single property (in this case `criteria`) that is of a type `object` (in the case of `WRAPPER_OBJECT`) or `array` (in case of `WRAPPER_ARRAY`). That `object` (or `array`) would have to be somehow described as an object that has only one property named and typed differently depending on the context.

I just don't know how to describe that better than what you see there today. And I certainly don't know how to describe that in Swagger JSON.

I'd be happy to re-open this issue if you can provide me with a reasonable way to represent this kind of polymorphism in both HTML and Swagger JSON.
