### ISSUE TITLE
2.9.1 swagger model example contains media type

### ISSUE THREAD

**Issue by vghero** [stoicflame/enunciate#717]
I'm using 2.9.1 to generate the documentation from my JAX-RS resource interfaces and models.
Looking at the swagger UI shows, that the first example (directly under "Response Class") suddenly contains the media type like so:

```
{
  "application/json": {
    "featureFlags": {
      "property1": {},
      "property2": {}
    }
  }
}
```

The enunciate documentation is correct though. Also the swagger UI model further below, e.g. when POSTing seems correct.

**Comment by vghero** [comment]
I also encountered that using `{@link AvailabilityState#CLOSED_UNTIL}` (enum value) in the e.g. class javadoc won't be converted to `<code>CLOSED_UNTIL</code>` or similar but just to a link to the json enum. That somehow reads strange since in the javadoc it is normally rendered as `Availability.CLOSED_UNTIL` :).

**Comment by stoicflame** [comment]
As for the strange-reading link, there's currently no support for linking to anything more granular than the data type. If the text reads weird, override it in the JavaDoc tag:

```
{@link AvailabilityState#CLOSED_UNTIL CLOSED_UNTIL}
```

**Comment by vghero** [comment]
Thanks! What I mean with "weird" is this when I usually document in code like this:

```
* This is the {@link AvailabilityState#OPEN} state. This is the manually highlighted <code>OPEN</code> state.
```

It is rendered like this:

![screen shot 2017-10-11 at 10 04 57](https://user-images.githubusercontent.com/26437329/31428625-b9934dbc-ae6b-11e7-8ab7-ce5a633d11cc.png)

Which is from a "user" perspective unexpected - I guess. So I have to always remember that I have to use the override, when I'm in the REST API module. But I didn't even know, that this is possible - thanks for pointing that out :)!

So question here is, if it makes sense to render enums as link using their enum value (here: `OPEN`) instead of the enum class name.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
