### ISSUE TITLE
Documentation examples for Maps

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#720]
I'm wondering whether it is possible to provide `@documentationExample` for a `Map<String,Boolean>` for example. Currently it renders it as a "map of booleans" like this:

``` 
{
  "featureFlags" : {
    "property1" : true,
    "property2" : true
  }
}
```

Does it make sense to be able to provide `@documentationExample MY_KEY`? Or for non-boolean values like Object or similar `@documentationExample MY_KEY myvalue`?

When I try to set it using `MY_KEY`, it complains it's not a boolean :).

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
