### ISSUE TITLE
Get Response Example to show object type within an object

### ISSUE THREAD

**Issue by LittleBarn** [stoicflame/enunciate#724]
So in my code I take a class type lets say for example its called MyObject and wrap it in a ListResult class. Currently we have an
@TypeHint(ListResult.class) above our method to get the response example in our documentation to show what a ListResult looks like. This is what it shows:

{
  "resultInfo" : {
    "nextId" : 12345,
    "outOf" : 12345
  },
  "object" : [ { }, { } ],
  "ids" : "..."
}

What I would like to do is have the response example in my documentation show MyObject inside the ListResult where it says "object" : [ { }, { } ], but I want to do this on a case by case basis because we have other methods that return a ListResult that is wrapping a completely different object. I don't know how to do this, or if it is even possible.

**Comment by stoicflame** [comment]
The only thing I can think of is to use generics.

See #400.

**Comment by LittleBarn** [comment]
I have read #400 and it doesn't quite make sense to me. Could you maybe explain it based on my example?

**Comment by stoicflame** [comment]
```java
public class ListResult<T> {
  public List<T> object;
}
```

```java
@Path("/myresource")
public class MyResource {
  @GET
  public ListResult<MyObject> getMyObjects() { return new ListResult() }
}
```
