### ISSUE TITLE
Date language in "Files and libraries" page

### ISSUE THREAD

**Issue by raul-geocento** [stoicflame/enunciate#725]
Hello:

When I generate my project documentation using enunciate 2.9.1 all the pages are written in English but in "Files and libraries" page the dates appear in Spanish. I suppose this happens because is my laptop OS language. You can find an example [here](https://geobrowser.satapps.org/docs/downloads.html)

I have tried to change the java compiler language setting these parameters in my ant file:

<javacargument argument="-J-Duser.language=en"></javacargument>
<javacargument argument="-J-Duser.country=GB"></javacargument>

But then I get a "java.lang.IllegalArgumentException: invalid flag: -J-Duser.language=en". Anyway I do not know if this would correct the date language.

Is there another workaround?

Thanks

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
