### ISSUE TITLE
no documentation provided on parameters for subresource locators

### ISSUE THREAD

**Issue by pswvg** [stoicflame/enunciate#73]
Hi.
 
I'm using enunciate 1.30 for generating documentation for my REST api.
Somehow parameters on my subresource locators aren't found for documentation:
 
public interface SubResource {
    /**
     * Gets the sub sub resource.
     *
     * @param myId the id of the sub sub resource to get.
     * @return the sub sub resource.
     */
    @Path("{myId}")
    SubSubResource getSubSubResource(@PathParam("myId") String myId);
}
 
When I look at the generated documentation for the SubSubResource, myId states (no documentation provided).
I am missing something?
 
Thanks.
Veit

**Comment by stoicflame** [comment]
Probably a bug. We'll track it here.

**Comment by stoicflame** [comment]
Tested and proven to work at 1373460.

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)
