### ISSUE TITLE
Allow for specifying enum values

### ISSUE THREAD

**Issue by ncoe** [stoicflame/enunciate#730]
I have a project with an enumeration that is serialized with a value different from the name of the constant. What would I modify for a PR show this in the end documentation?

e.g.
```
@JsonSerialize(using = MySerializer.class)
enum Type {
  FIRST,
  SECOND,
}
```

Would write "1st" or "2nd", or anything else that could be thought of.

My thought initially would be to allow @DocumentationExample to handle this.

**Comment by stoicflame** [comment]
See #653.
