### ISSUE TITLE
Javadoc links do not handle enum references correctly

### ISSUE THREAD

**Issue by ncoe** [stoicflame/enunciate#732]
When attempting to link to a particular enum value with `{@link MyEnum#VALUE1}`, enunciate will simply link to the documentation for the entire enum. It would be nicer if each value on the enumeration page had an anchor for such a link to land on.

**Comment by stoicflame** [comment]
Confirmed. Enunciate doesn't resolve links to that level of granularity yet.

See also #717 where this was also mentioned.

**Comment by stoicflame** [comment]
This enhancement is currently seeking a sponsor. If anybody is willing to sponsor the work, [reach out to me](http://webcohesion.com/#contact) and I'd be happy to pick it up.

**Comment by ncoe** [comment]
I don't know when this was fixed, but at least as of https://github.com/stoicflame/enunciate/commit/6ae0f8b411d645468d658bc5a2e614a2033a5e85 the links to enum members are working as desired.
