### ISSUE TITLE
Resource linked under two other resources is only documented once.

### ISSUE THREAD

**Issue by mscookies** [stoicflame/enunciate#734]
Hi there,
first of all thanks for the great documentation generator.

I'm using v2.9.1 and I'm facing an issue as not all defined/implemented paths are visible in generated enunciate documenation and related swagger UI.

Imagine following paths in a REST service
/elements
/elements/{elementId}
/elements/{elementId}/buckets						<- first occurence of buckets resource
/categories
/categories/{categoryId}
/categories/{categoryId}/items
/categories/{categoryId}/items/{itemId}
/categories/{categoryId}/items/{itemId}/buckets 	<- second occurence of buckets resource

For all path parts there are resource interfaces defined e.g. `ElementsResource`, `ElementResource`, a.s.o. 
Also for the `buckets` path there is a `BucketsResource` interface defined that is referenced by `ElementResource` and `ItemResource`.
Unfortunately the latter resource is displayed neither in the REST documenation nor in swagger UI, even though it is callable on the server.

I tried to tweak the JAX-RS module datatype-detection attribute, but without luck. Even with aggressive the resource in question was only displayed once in the documentation even though other (non local and unwanted) classes showed up in the docs.

As a work around I've defined another interface `ItemBucketsResource` that only extends the `BucketsResource` and afterwards both paths were documented as expected.

Anyway, is there a better solution to get the second occurence of the buckets resource documented as to add another interface just for documentation purposes?

Best and thanks, Michael

**Comment by stoicflame** [comment]
I'm having a hard time understanding all the resources and interfaces. Is there a project somewhere that I can reference to see what you're talking about?

**Comment by stoicflame** [comment]
Since I haven't heard back, I'm going to close this issue for now. If you're interested in picking it up again, I'd be happy to re-open.
