### ISSUE TITLE
Changing default text at top of Request Example

### ISSUE THREAD

**Issue by LittleBarn** [stoicflame/enunciate#735]
So I was wondering if there was a way to customize the text for example in the picture below I want it to change the "GET /system/customaddresses/test" to look like this: 
"GET /system/customaddresses/test?testAddress=youremail@yourdomain.com"

![untitled](https://user-images.githubusercontent.com/31744122/30386156-5cd42cd8-9866-11e7-9ac1-9da59bb95adc.png)

**Comment by stoicflame** [comment]
No, there's no way to do that right now.

**Comment by stoicflame** [comment]
As of f10b590, e.g.:

```java
/**
 * @pathExample /persons?id=12345
 */
@GET
Person getPerson(@QueryParam("id") String id);
```

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
