### ISSUE TITLE
Allow DocumentationExample to be used with query parameters and headers

### ISSUE THREAD

**Issue by ncoe** [stoicflame/enunciate#736]
I would like to be able to provide an example to use for the generated request/response for headers. This would also be nice for query parameters.

Neither has a field in the annotation to support this, and the restrictions for the `@DocumentationExample` attribute do not even let it get placed on a parameter. Allowing for repeats of the annotation instead of capping it at two values would also be appreciated.

**Comment by stoicflame** [comment]
At 645e557 added support for `@DocumentationExample` on request parameters (query, header, etc.).

I have no idea how to provide the means to specify response example values.

I also don't understand how to use "repeats"... how does using more than one value help?

**Comment by ncoe** [comment]
The DocumentationExample annotation already has capacity for "value" and "value2", generalizing it for arbitrary examples seemed like a natural extension.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
