### ISSUE TITLE
The disableExamples attribute does not disable all examples

### ISSUE THREAD

**Issue by ncoe** [stoicflame/enunciate#737]
In my enunciate.xml file I have disabled examples. `<jackson disabled="false" disableExamples="true"/>`.
For JSON documentation, this does what is expected. For the Resources section, examples are still generated. This is using version 2.9.1.

**Comment by stoicflame** [comment]
You have to disable JAX-RS examples and JAXB example, too, if you want those disabled:

```xml
<enunciate>
  <modules>
    <jaxrs disableExamples="true"/>
    <jaxb disableExamples="true"/>
```
