### ISSUE TITLE
Setting Swagger docsSubdir to the root level removes sidebar data type links and makes <h1> header elements very large.

### ISSUE THREAD

**Issue by tpredey** [stoicflame/enunciate#738]
This is something of an edge-case, but it might be worth posting in case somebody else encounters a similar issue. 

The problem stems from my wanting to add navigation buttons on the Swagger UI page back to the main documentation page. The most straightforward way to do this appears to be setting the Swagger module field docsSubdir="", which opens up the swagger-ui/endpoints.html* page to relative URL path hrefs that point back to the main docs pages.

In practice, this change had unexpected consequences to the main documentation page. My system has JSON Data Types that are handled by the main docs.fmt FreeMarker Template file. When the Swagger docsSubdir is the default "ui" or another custom string, this works just fine and a clickable JSON link comes up in the sidebar. However, when the docsSubdir field is set to "", the clickable link does not show up in the sidebar and the \<h1> header elements (i.e., "Resources" and "Data Types") are rendered much larger than usual. The JSON data is loaded exactly like before and the user can still navigate to the Data Types page from the top navbar. 

Any information about what is happening here would be appreciated. I surmise there must be some interaction between the various root level pages, and the presence of a swagger page is throwing things off. However, at this time it is unclear to me what that connection is. 

\* I renamed "index.html" to "endpoints.html" to avoid a page name conflict at the root level.

**Comment by stoicflame** [comment]
It was just that the swagger `style.css` was overwriting Enunciate's css (named the same).

At 18f3c6a I renamed Enunciate's to `enunciate.css` and it looks good.
