### ISSUE TITLE
namespace for JAX-RS endpoints

### ISSUE THREAD

**Issue by pswvg** [stoicflame/enunciate#74]
Hi.

I'm trying to get rid of the generic ns0 namespace (and so ns0.xsd) that is used during the documentation generation. Like described here:

http://docs.codehaus.org/display/ENUNCIATE/Customizing+Namespace+Prefixes

This should work for @Webservice. But I'm using REST with JSON only. How do I specify a namespace in REST so enunciate will pick it up?

I tried to define the @XmlSchema in a package-info.java in the package of the JAX-RS interfaces - like described in the docs. But this doesn't seem to be taken into account (except for the splash documentation provided as javadoc there). I also put the <namespace> tags into enunciate.xml like described.

Any idea what I'm missing?

Thanks!
Veit

**Comment by pswvg** [comment]
Ok, figured it out. I have the interfaces and the models in separate packages.
It worked when I put the package-info.java containing @XmlSchema(namespace = "http://example.org")
into the model package. But I don't know why. Maybe someone could shed some light on this, please :)?

**Comment by stoicflame** [comment]
> It worked when I put the package-info.java into the model package.

`package-info.java` is for applying metadata to the package. So if your classes are in another package, they'll need a separate package-info.

**Comment by pswvg** [comment]
Hi.

Please define "your classes" :). As I wrote before, REST interfaces are in one package, models (entites, DTOs whatever you call it) are in another package. If I put package-info into REST interface package, it doesn't work, in the model package it works. So my question is, why it has to be in the model package?

Background: I simply wanted to change the "default" namespaces enunciate uses when not specifying a namespace. So I thought, I set the namespace on the REST interface package - which isn't taken into account.

**Comment by stoicflame** [comment]
Well, REST endpoints, by definition, don't have a "namespace".

As for the objects (the JSON data), those don't really have a namespace either, but Enunciate's weird because it's JSON support is a byproduct of its XML support, so Enunciate puts the JSON objects in a namespace. This will change with Enunciate 2.

**Comment by pswvg** [comment]
Ah, I see. Thanks for the explanation!
