### ISSUE TITLE
Path and query parameters have no description

### ISSUE THREAD

**Issue by ncoe** [stoicflame/enunciate#740]
In the section on Request Parameters, you can associate a description for header values.
A desired enhancement would be have descriptions for path parameters and query parameters.
Right now, both of those just have a blank space for the description.

**Comment by ncoe** [comment]
A related issue to this is that the description of a download link is not transferred from the enunciate.xml file to the generated documentation. I am not sure whether I would call this a bug or enhancement at this time.

**Comment by stoicflame** [comment]
I'm afraid I'm not seeing what you see; I can provide descriptions for the path and query parameters via the JavaDocs.

**Comment by ncoe** [comment]
I do have javadocs. They are attached to the interface that my endpoint is implemented.
Could this be an issue where the javadoc handling you made does not link to the super documentation?

**Comment by ncoe** [comment]
Found it. I have specific includes in the config file, and the interfaces were not part of the include.
