### ISSUE TITLE
Support for @code

### ISSUE THREAD

**Issue by vghero** [stoicflame/enunciate#743]
Currently I have to put `<code>MyCode</code>` in my javadoc to highlight code fragments or similar. That works well. But sometimes forget about it and use {@code MyCode} instead, which isn't rendered by enunciate. It simply outputs `MyCode` then - without highlighting. It would be great if enunciate could also support @code properly. Maybe it's just a search replace thingy with regex sugar :)?

**Comment by vghero** [comment]
Nice, thanks :)!

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
