### ISSUE TITLE
Multiple @RequestHeader for @RequestHeaders

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#746]
I'm trying to document multiple request headers for a method. My hope was to use `@RequestHeaders` to wrap multiple `@RequestHeader`. The example on https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations says :

```
@GET
@RequestHeaders (
  @RequestHeader( name = "X-Auth-Token", description = "The authentication token.")
)
Person getPerson(@PathParam("id") String id);
```

This is a single `@RequestHeader`. How do I specify multiple `@RequestHeader`?

**Comment by sbrattla** [comment]
OK, so this is how it's done :

```
@GET
@RequestHeaders ({
  @RequestHeader( name = "X-Auth-Token", description = "The authentication token."),
  @RequestHeader( name = "X-Auth-Method", description = "The authentication method.")
})
Person getPerson(@PathParam("id") String id);

```
Maybe the documentation could be updated to show how you would define multiple `@RequestHeader.`

On thing more, the example below for `@RequestHeader `(just below the example for `@RequestHeaders`) is showing an example for `@ResponseHeader`. This could probably be fixed as well.

**Comment by stoicflame** [comment]
Done.
