### ISSUE TITLE
Support for OpenAPI3 swagger.json output

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#747]
Swagger version 3 (aka OpenAPI version 3) is quite different than the v2 format Enunciate can output today.

The new spec is here https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md

I might be able to use some time to look into this. But it will be of the very lowest priority, so I cannot commit to a timescale or anything like that.

If I start on it, I will leave information here about fork/branch so others can join/observe.

**Comment by jskovjyskebankdk** [comment]
I have started working on this.

**Comment by xeagle2** [comment]
Hi @jskovjyskebankdk, do you have any idea when the feature is going to be released? I'm so excited to give it a try.

**Comment by jskovjyskebankdk** [comment]
I have decided to release it as a standalone project.

With some luck, I will find some time to do it this week.

**Comment by xeagle2** [comment]
Would be really great, looking forward to try it.

**Comment by jskovjyskebankdk** [comment]
I have made an initial release here:

https://github.com/Jyskebank/enunciate-openapi/releases/tag/1.0.1
