### ISSUE TITLE
Regression in header description generation.

### ISSUE THREAD

**Issue by ncoe** [stoicflame/enunciate#748]
Reference body

```java
/** Some description of the method in general. */
@RequestHeaders({
    @RequestHeader(name = "myParam", description = "My parameter description.")
}
public void someMethod() {
    ....
}
````

In 2.9.1, the method Javadoc would be put before the table of headers, path and query parameters. The path and query parameters would pull from `@param` annotations for the description to use in the table, and the header values would pull from the description field of the header value annotation.

With the current state of 2.10.0, the Javadoc for the method is being used as the description of all header parameters.

Before:
Some description of the method in general.
header    myParam    My Parameter description.

After:
Some description of the method in general.
header    myParam    Some description of the method in general.

**Comment by ncoe** [comment]
Git bisection points at 6f5a3ef18d9277f08e7ace14d9b743aaa293c729

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
