### ISSUE TITLE
Methods not marked deprecated when grouped by annotation

### ISSUE THREAD

**Issue by ncoe** [stoicflame/enunciate#749]
I have a class that is annotated as deprecated. When I have enunciate generate documentation by class, the methods are shown as deprecated. If I mark the methods with a resource group and group by annotation instead, the methods are not marked deprecated unless each method individually is marked deprecated.

This would be a good enhancement if the deprecated annotation propagated to the methods no matter how they are grouped.

**Comment by ncoe** [comment]
Seems to be caused by https://github.com/stoicflame/enunciate/blob/962cbf558bb8919252b1d2a567cfbe3432483548/jaxrs/src/main/java/com/webcohesion/enunciate/modules/jaxrs/api/impl/AnnotationBasedResourceGroupImpl.java#L118

Is there a way to have context to see if the class the resource is contained in is deprecated?

**Comment by stoicflame** [comment]
When grouping by annotation, you have multiple resources that are included in the same "resource group". So the solution is to make sure that all resources in the same group are marked as deprecated.

**Comment by ncoe** [comment]
Allow me just to confirm with an example (some details omitted for terseness):
`@Deprecated
public class A {
    @ResourceGroup("one")
    public void alpha() {
        ...
    }

    @ResourceGroup("one")
    public void beta() {
        ...
    }

    @ResourceGroup("two")
    @Deprecated
    public void san() {
        ...
    }
}`

The only resources marked with _one_ and _two_ are shown. The 'san' resource obviously should be marked deprecated, because the method itself is marked deprecated. I would argue that 'alpha' and 'beta' should also be marked deprecated, or at least considered as deprecated for the calculation in the link shown because the class containing all of these has been marked deprecated.
So then is it deliberate that when resource grouping is requested by attribute, that only the attributes on the method itself are considered?

**Comment by stoicflame** [comment]
So you're not asking for the resource group to be deprecated, just the methods. And that because the class the defines the methods is deprecated. Yes?

**Comment by ncoe** [comment]
Yes, I think it would be a good enhancement if annotations were applied transitively, where and for what it makes sense for. 

A workaround for this it to mark all methods deprecated that are selected for a group, which I am using currently.

**Comment by ncoe** [comment]
Thanks, I will check this out soon.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
