### ISSUE TITLE
ability to group resources in swagger module

### ISSUE THREAD

**Issue by pswvg** [stoicflame/enunciate#75]
Hi.

I'm using enunciate 1.30 for generating documentation-only for my REST services. I'm using the default documentation plus the swagger module.

Per default, enunciate groups the endpoints per endpoint/interface class name. I wanted the "url-look" and set groupRestResources to "false". Voila - grouping was done by path. Then I wanted the same for the swagger output and set it also to false. Result: no swagger output at all.

Then I searched for the groupRestResource parameter documentation and found several answers. One says, that it can be "byPath" or "byDocumentation". One says, that it must be the name of a facet. Within the XSD it is only a string. So I'm wondering, what I have to put in there to get "Paths only"?
Using "false" seems to work for the default documentation - per accident :)? So what makes the swagger module list them by path?

Thanks
Veit

**Comment by stoicflame** [comment]
You found a bug. There's currently no way to group rest resources by path in the Swagger module. The only workaround I can see is to annotate each separate resource with a different facet value, so that's sub-optimal.

I'll track the work for the fix here.

**Comment by pswvg** [comment]
Ok, thanks!

**Comment by stoicflame** [comment]
Fixed in Enunciate 2.0.0.
