### ISSUE TITLE
new release request

### ISSUE THREAD

**Issue by keradus** [stoicflame/enunciate#752]
Hi !
great package here !

Sadly, last release is half year old, and there are plenty of new shiny things on main branch already!
Are there any chances to release them? Or maybe there is some release plan?

**Comment by stoicflame** [comment]
Yes, some time this week.

**Comment by stoicflame** [comment]
[Enunciate 2.10 is now available](https://github.com/stoicflame/enunciate/releases/tag/v2.10.0).
