### ISSUE TITLE
Incorrect items type generated in swagger.json for List<? extends @interface>

### ISSUE THREAD

**Issue by Ga2nibal** [stoicflame/enunciate#753]
I use enunciate 2.9.1.

in one of the models:

```java
  List<? extends MyInterface> filters
```

where :

```java
public interface MyInterface {
}
```

enunciate produced:

```json
 "filters" : {
"type" : "array",
"items" : {
  "type" : "object"
}
```

and enunciate doesn't produce models of MyInterface and classes which implements MyInterface

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
