### ISSUE TITLE
Enunciate 2.10.0 can not be loaded from https://plugins.gradle.org/m2/

### ISSUE THREAD

**Issue by Ga2nibal** [stoicflame/enunciate#755]
when i try to update enunciate to 2.10.0 i get:
```
Error:Could not find gradle.plugin.com.webcohesion.enunciate:enunciate-gradle:2.10.0.
Searched in the following locations:
    https://repo1.maven.org/maven2/gradle/plugin/com/webcohesion/enunciate/enunciate-gradle/2.10.0/enunciate-gradle-2.10.0.pom
    https://repo1.maven.org/maven2/gradle/plugin/com/webcohesion/enunciate/enunciate-gradle/2.10.0/enunciate-gradle-2.10.0.jar
    https://plugins.gradle.org/m2/gradle/plugin/com/webcohesion/enunciate/enunciate-gradle/2.10.0/enunciate-gradle-2.10.0.pom
    https://plugins.gradle.org/m2/gradle/plugin/com/webcohesion/enunciate/enunciate-gradle/2.10.0/enunciate-gradle-2.10.0.jar
    
```

**Comment by stoicflame** [comment]
I'm not very familiar with gradle, but I can't tell the difference between 2.10.0:

https://plugins.gradle.org/m2/com/webcohesion/enunciate/com.webcohesion.enunciate.gradle.plugin/2.10.0/

and 2.9.1:

https://plugins.gradle.org/m2/com/webcohesion/enunciate/com.webcohesion.enunciate.gradle.plugin/2.9.1/

@jskovjyskebankdk, any thoughts about what's going on?

**Comment by jskovjyskebankdk** [comment]
The artifacts are bad, for some reason.

I have posted https://discuss.gradle.org/t/weird-fail-on-plugins-gradle-org-enunciate-2-10-0/24573

Let us see what they have to say.

**Comment by jskovjyskebankdk** [comment]
A fix has been posted on the gradle forum. Will you have a look at it @stoicflame ?

**Comment by stoicflame** [comment]
2.10.1 has been published.

**Comment by jskovjyskebankdk** [comment]
Yes, better. Thanks!
