### ISSUE TITLE
error in navigation 

### ISSUE THREAD

**Issue by darkstarSH** [stoicflame/enunciate#757]
Looks like version 2.10.0 introduced a regression error:
Navigation items show (random?) enums

Steps to reproduce:
- Build enunciate-examples-jx-rs-jackson
- open generated docs
- navigate to 'Home'/'JSON'/'PageOfPerson' (other pages show similar behavior) 
- navigation on the left shows elements of enum GenderType (which doesn't make sense in any way)

**Comment by stoicflame** [comment]
Confirmed. Regression at 4e06ebcf4919f286571507c0c7da3e7bbf716bd6.

**Comment by stoicflame** [comment]
Patched at [2.10.1](https://github.com/stoicflame/enunciate/releases/tag/v2.10.1).
