### ISSUE TITLE
How to display more information about the method on the index page?

### ISSUE THREAD

**Issue by wf2311** [stoicflame/enunciate#758]
I want to show more information about interface methods besides `path`,such as `method description` and `version` on index-page ,just as:
![a](https://user-images.githubusercontent.com/6166719/32163341-f8040e62-bd96-11e7-9b03-0e7bd15315ee.png)

But it seems like that these informations can just shows on sub-page，if I want to show them on index-page,is it possible?

**Comment by stoicflame** [comment]
Have you tried grouping by path instead of class?

```xml
<enunciate>
  <modules>
    <jaxrs groupBy="path"/>
    <spring groupBy="path"/>
```
