### ISSUE TITLE
Duplicate parameter documentation on SubResourceLocators

### ISSUE THREAD

**Issue by pswvg** [stoicflame/enunciate#76]
Hi.

I'm using Enunciate 1.30 for generating my REST documentation. I encountered
a possible problem with duplicate parameters when using subresource locators.

I have a path like this:

api/subresource/{myId}/subsubsubresource

When I look at the documentation for subsubsubresource, I see the parameter myId documented twice:

name 	description 	type 	default
myId 	(no documentation provided) 	path
myId 	(no documentation provided) 	path

I think that comes from the fact, that subsubsubresource also needs myId for instantiation that it
gets injected via @PathParam by JAX-RS. Maybe it's as easy as simply dropping duplicate path parameters
from the documentation?

Please find attached the test project that demonstrates the problem.

Thanks
Veit

**Comment by pswvg** [comment]
Hm. No files allowed? Where should I send test project?

**Comment by stoicflame** [comment]
Hi. Thanks for the report.

I haven't thought about attachments yet. What about [creating a gist](https://gist.github.com/)? You can [push and pull gists](http://stackoverflow.com/questions/5299526/github-commiting-push-gist), so it seems like it should work....

**Comment by pswvg** [comment]
Ok. Here's the project, If you want to take a look:

https://gist.github.com/pswvg/a69fc4c1faf67da4193f#file-test-zip

**Comment by stoicflame** [comment]
Fixed at 51f0716.

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)
