### ISSUE TITLE
`@Typehint` for Response makes `@RequestHeader` value `multivalued`

### ISSUE THREAD

**Issue by simonDeHero** [stoicflame/enunciate#761]
Hi,
i have this endpoint:
```
    /**
     * some javdoc
     *
     * @RequestHeader Authorization the auth header.
     *
     * @HTTP 200 ....
     */
    @ETag
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("foo/bar")
    @ResourceGroup("the fooBars")
    @TypeHint(FooBar[].class)
    Response getFooBar();
```

The rendered documentation then contains `Response Body - data type - array of fooBar (JSON)` (correct), but also `Request Parameters - name Authorization - multivalued yes`. (wrong).

It is expected, that the `@TypeHint` for the Response does not affect header params.

My current workaround is to use `@returnWrapped com.example.FooBar[]` instead of the `@TypeHint`, then the request parameter is not rendered with `multivalued`.

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
