### ISSUE TITLE
How to build Java 7 (or even Java 8) modules with the rest of the enunciate complex

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#762]
Hi Ryan,

The new OpenAPI module I am writing is written in Java 7.
https://github.com/jskovjyskebankdk/enunciate/tree/swagger3

But it fails to build with the rest of the modules, because of the animal-sniffer-manual-plugin.

I admit to having zero knowledge of Maven.

But the project splash page says enunciate gets built with Java 7, so I assumed that was the default?!

FWIW I would have been much happier to write the plugin in Java 8. Java 7 is a real PITA to use, after being used to Java 8. Any chance of a general update to Java 8?

Thanks,
Jesper

**Comment by stoicflame** [comment]
What errors does the animal-sniffer plugin output?

I expect that the next release of Enunciate (2.11) will finally drop support for Java 7 and move to Java 8.

**Comment by jskovjyskebankdk** [comment]
It just does not like that I have set Java 7 for the openapi module:

````
[ERROR] Failed to execute goal org.codehaus.mojo:animal-sniffer-maven-plugin:1.14:check (enforce-java-6) on project enunciate-openapi: Signature errors found. Verify them and ignore them with the proper annotation if needed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :enunciate-openapi
````


Sounds good about the switch for Java 8! :)

I need to build the openapi module internally, so we can start using it.
But I will keep my swagger3 branch up to date and send you a pull request once I get it working properly.

I am assuming you want the module to be included with enunciate?
I am happy to also maintain it as a stand-alone project, but then it needs to be included manually as a dependency by users, which some may see as a hassle
Either way works for me. Your pick.

**Comment by stoicflame** [comment]
I'd like to see it included into the main Enunciate project, but it sounds like we ought to wait until maybe after to 2.11 release when we update to Java 8 and support for Java 9.

As for the animal-sniffer plugin, I updated at 4b5432e so it should work better now.

**Comment by jskovjyskebankdk** [comment]
Thanks!
