### ISSUE TITLE
Including Parent tag in JSON output after Enuntiation.

### ISSUE THREAD

**Issue by KishoreGGK** [stoicflame/enunciate#768]
For the following XML Root element class,

public class Persona {

  private String id;
  private String email;
  private String alias;
  private Name name;
  private javax.activation.DataHandler picture;
....
}
Following JSON is generated
{
  "id" : "...",
  "email" : "...",
  "alias" : "...",
  "name" : {
    "givenName" : "...",
    "surname" : "..."
  },
  "picture" : "..."
}

Is it possible to generate  i.e with the Persona entity  (Using some simple customization ) ? 
See below 

{
"Persona":{
  "id" : "...",
  "email" : "...",
  "alias" : "...",
  "name" : {
    "givenName" : "...",
    "surname" : "..."
  },
  "picture" : "..."
}
}

**Comment by stoicflame** [comment]
See #609.
