### ISSUE TITLE
Is whitespace in <pre> supported in package-info.java?

### ISSUE THREAD

**Issue by bitsandbytes** [stoicflame/enunciate#77]
Hi, I have begun using enunciate to document my project's REST endpoints and it's been great. No major issues or requests from me because it provides what I need.

So here's my question. I'm using the maven plugin, v1.29. I put the following in my package-info.java:

```
 * blah blah blah
<pre>
 {
     "maxResults": 100,
     "pageNum": 0,
     "pageSize: 10,
     "terms": [
         {
            ...more and more JSON...
 }
</pre>
 * blah blah blah
```

The indentation is important to making the JSON readable, but when I generate the docs there are no spaces at all.

By the time the above gets written to the enunciate/generate/docs/docs.xml file the &lt;pre> tag is still in the CDATA, but the spaces have been stripped. Javadoc says it will respect whitespace inside of &lt;pre>, so I was expecting enunciate would as well.

Am I doing something wrong?

**Comment by stoicflame** [comment]
There might be a bug. Have you tried putting the "*" on every line to see if it makes a difference?

```
* blah blah blah
* <pre>
*  {
*      "maxResults": 100,
*      "pageNum": 0,
*      "pageSize: 10,
*      "terms": [
*          {
*             ...more and more JSON...
*  }
* </pre>
* blah blah blah
```

**Comment by bitsandbytes** [comment]
Thanks - I just tried regenerating with "*" on every line now but got the same result and the whitespace is removed.

**Comment by stoicflame** [comment]
Weird.

Maybe it's something specific to the `package-info.java` file, because I get my whitespace preserved if I have it on a method or resource. Can you confirm?

I'll take a closer look. Thanks for the report.

**Comment by bitsandbytes** [comment]
I have also tried it on a resource and the whitespace is still stripped.

I'm including my enunciate.xml in case there's some difference in how we configure it that causes this.

```
<?xml version="1.0"?>
<enunciate excludeUnreferencedClasses="true">
    <api-classes>
        <include pattern="com.tao.rest.*"/>
        <include pattern="javax.ws.rs.core.Resource"/>
    </api-classes>
    <services>
        <rest defaultRestSubcontext="/tao"/>
    </services>
    <facets>
        <exclude name="tao#admin"/>
    </facets>
    <modules>
        <csharp disabled=true"/>
        <c disabled=true"/>
        <obj-c disabled=true"/>
        <php disabled=true"/>
        <java-client disabled=true"/>
        <ruby disabled=true"/>
        <xml disabled="false"/>
        <docs title="TAO"
                splashPackage="com.tao.rest"
                includeDefaultDownloads="false"
                includeExampleXml="false"/>
    </modules>
</enunciate>
```

**Comment by johangronvall** [comment]
I've got the same problem. Looking at the XML files in the build directory, I can see that the whitespace is gone.

**Comment by stoicflame** [comment]
Assigning this issue to v2.1.0.

**Comment by stoicflame** [comment]
Okay, [the JavaDoc API says](http://docs.oracle.com/javase/7/docs/technotes/tools/solaris/javadoc.html#leadingasterisks):

> When javadoc parses a doc comment, leading asterisk (*) characters on each line are discarded; blanks and tabs preceding the initial asterisk (*) characters are also discarded. Starting with 1.4, if you omit the leading asterisk on a line, the leading white space is no longer removed. This enables you to paste code examples directly into a doc comment inside a \<PRE\> tag, and its indentation will be honored. Spaces are generally interpreted by browsers more uniformly than tabs. Indentation is relative to the left margin (rather than the separator /** or \<PRE\> tag).

So whitespace should be preserved only if there is _not_ leading asterisks.

Unfortunately, [the API for reading the doc comment using the Javac Tool](http://docs.oracle.com/javase/7/docs/api/javax/lang/model/util/Elements.html#getDocComment%28javax.lang.model.element.Element%29) automatically strips the leading asterisks, so there's no way for me to tell whether whitespace should be preserved.

However, at e8ef6a3, I implemented a hack that will preserve whitespace if a `<pre>` tag is detected. That's the best I can do for now.

The hack will be included in version 2.1.

**Comment by bitsandbytes** [comment]
Great, thanks for your help!

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)
