### ISSUE TITLE
Success status codes are not listed in application.wadl

### ISSUE THREAD

**Issue by j-be** [stoicflame/enunciate#770]
I noticed, that the HTTP success status (i.e. 2XX) are not listed in the application.wadl file. In detail:

    @StatusCodes({
      @ResponseCode( code = 204, condition = "All good"),
      @ResponseCode( code = 500, condition = "An error occured, including parameter validation fails.")
    })

leads to:

    <wadl:method name="PUT">
      <wadl:doc> ... </wadl:doc>
      <wadl:request>
        ...
      </wadl:request>
      <wadl:response status="500">
        <wadl:doc><![CDATA[An error occured, including parameter validation fails.]]></wadl:doc>
      </wadl:response>
    </wadl:method>

In the HTML doc they are listed though:
![204-response-code](https://user-images.githubusercontent.com/8503582/32837615-7ea3c0ce-ca0e-11e7-811f-e5c8686e1e9e.png)

Is this on purpose?

**Comment by stoicflame** [comment]
Finally picking this up, but I wasn't able to reproduce when I apply these changes to the [enunciate-sample-app](https://github.com/stoicflame/enunciate-sample):

```diff
diff --git a/src/main/java/com/ifyouwannabecool/api/PersonaService.java b/src/main/java/com/ifyouwannabecool/api/PersonaService.java
index a1b238d..977de0d 100644
--- a/src/main/java/com/ifyouwannabecool/api/PersonaService.java
+++ b/src/main/java/com/ifyouwannabecool/api/PersonaService.java
@@ -15,6 +15,8 @@ import javax.ws.rs.PathParam;
 import javax.ws.rs.Produces;
 
 import com.ifyouwannabecool.domain.persona.Persona;
+import com.webcohesion.enunciate.metadata.rs.ResponseCode;
+import com.webcohesion.enunciate.metadata.rs.StatusCodes;
 
 /**
  * The persona services is used to perform actions on the data associated with a persona.
@@ -31,6 +33,10 @@ public interface PersonaService
      */
     @Path("/{id}")
     @GET
+    @StatusCodes({
+      @ResponseCode( code = 204, condition = "All good"),
+      @ResponseCode( code = 500, condition = "An error occurred.")
+    })
     Persona readPersona(@PathParam("id") String personaId);
 
     @Path("/{id}.json")
```

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
