### ISSUE TITLE
support for "name" in XmlType annotation as root element

### ISSUE THREAD

**Issue by KishoreGGK** [stoicflame/enunciate#772]
If I have annotated a class with @XMLRootElement or @XmlType with name can the value in name be used to generate. Example

```java
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testCust", propOrder = { "test" })
public class TestCustomer implements Serializable {
.
.
..
}
```

So can we force Enunciate to generate "testCust" instead of "TestCustomer"

Thanks in advance.

**Comment by andrejusc** [comment]
@stoicflame - may you have any preliminary date for 2.11.0 milestone to be released? May you point to which part of current Enunciate 2.10.x code could be changed if we need to have this issue working for our needs at the moment?

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
