### ISSUE TITLE
Unable to make request example that references classpath resource

### ISSUE THREAD

**Issue by evanmanning** [stoicflame/enunciate#773]
Using Enunciate 2.10.1, I'm trying to create a custom request example in a Spring Boot project by referencing a file on the classpath, as per the [documentation](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#requestexample-javadoc-tag).

I have a `/src/main/resources/doc/foo.json` resource, which, with Maven, should get on the classpath at `/doc/foo.json`, if I'm not mistaken.

In the javadoc of the resource method in the rest controller, I have

```
@requestExample application/json classpath:/doc/foo.json
```

When I do the Maven build, I get

```
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.10.1:assemble (default) on project tem-api-gateway-app: Error invoking Enunciate. java.lang.NullPointerException: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class -> [Help 1]
```

I get this result with or without the leading slash after `classpath:`.

I wonder if I'm just doing something wrong, or if it's a bug?

**Comment by stoicflame** [comment]
If it's in the src/main/resources directory of the same Enunciate project, it won't be on the classpath because it hasn't been compiled yet. You'll probably need to use the `file:` option instead.

**Comment by evanmanning** [comment]
Ah, quite true. The file one worked. Thanks!

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0). You should be able to use classpath.
