### ISSUE TITLE
@TypeHint and @returnWrapped not working after update to 2.10.0

### ISSUE THREAD

**Issue by markusreichel** [stoicflame/enunciate#777]
I'm new using enunciate, so took me a while to put `@returnWrapped` to work.
Using the lastest version 2.10.1 it always shows data type as (custom), I tried everything. I was givinig up, so my last resource was try to downgrade.
So, I tried 2.8.0 and 2.9.0 and both works fine, but when I tried version 2.10.0 and 2.10.1 it just doesn't work, not sure if something changed, but I did use the same code to generate de docs in all versions.

I'm using standard configuration in my enunciate.xml 
`<api-classes><include pattern="org.enunciatetest.**"/></api-classes>`

It's possible to support @returnWrapped with generics? Something like:

`@returnWrapped org.test.Paginated<org.test.MyType>`

Regards,

Markus Reichel

**Comment by markusreichel** [comment]
BTW I'm using enunciate-maven-plugin.

Regards,

Markus Reichel

**Comment by Mart-Bogdan** [comment]
code seems in place
/jaxrs/src/main/java/com/webcohesion/enunciate/modules/jaxrs/model/ResourceMethod.java:391
```java
    JavaDoc localDoc = new JavaDoc(getDocComment(), null, null, this.env);
    if (localDoc.get("returnWrapped") != null) { //support jax-doclets. see http://jira.codehaus.org/browse/ENUNCIATE-690
      String returnWrapped = localDoc.get("returnWrapped").get(0);
      String fqn = returnWrapped.substring(0, JavaDoc.indexOfFirstWhitespace(returnWrapped)).trim();

      boolean array = false;
      if (fqn.endsWith("[]")) {
        array = true;
        fqn = fqn.substring(0, fqn.length() - 2);
      }

      TypeElement type = env.getElementUtils().getTypeElement(fqn);
      if (type != null) {
        returnType = (DecoratedTypeMirror) TypeMirrorDecorator.decorate(env.getTypeUtils().getDeclaredType(type), this.env);

        if (array) {
          returnType = (DecoratedTypeMirror) TypeMirrorDecorator.decorate(env.getTypeUtils().getArrayType(returnType), this.env);
        }

        returnType.setDeferredDocComment(new ReturnWrappedDocComment(this));
      }
      else {
        getContext().getContext().getLogger().info("Invalid @returnWrapped type: \"%s\" (doesn't resolve to a type).", fqn);
      }
    }
```

**Comment by Mart-Bogdan** [comment]
perhaps this change
```diff
- returnType.setDocComment(new ReturnDocComment(this));
+ returnType.setDeferredDocComment(new ReturnDocComment(this));
```

**Comment by stoicflame** [comment]
Finally getting around to looking at this, but I'm afraid I'm not able to reproduce. This patch:

```diff
diff --git a/src/main/java/com/ifyouwannabecool/api/SocialGroupService.java b/src/main/java/com/ifyouwannabecool/api/SocialGroupService.java
index 44b50e7..1bec211 100644
--- a/src/main/java/com/ifyouwannabecool/api/SocialGroupService.java
+++ b/src/main/java/com/ifyouwannabecool/api/SocialGroupService.java
@@ -61,6 +61,7 @@ public interface SocialGroupService {
    * @param personaId The id of the persona to add to the group.
    * @return Whether the persona was successfully added.
    * @throws ExclusiveGroupException If the group is exclusive.
+   * @returnWrapped com.ifyouwannabecool.domain.link.SocialGroup
    */
   @Path("/{groupId}")
   @POST
```

applied to the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) app successfully generates documentation as if the method returned `SocialGroup`. Without the patch, the documentation states `boolean`.

There must be additional issues with your build. Can you provide a patch to the `enunciate-sample` app that exposes the problem for me?

**Comment by sbrattla** [comment]
I had this issue as well, but that happened because my resource methods has `@Produces("application/xml;charset=utf-8")`. The charset broke the return example.

When i removed the explicit `charset` the examples worked fine again.
