### ISSUE TITLE
Set application root in System properties

### ISSUE THREAD

**Issue by markusreichel** [stoicflame/enunciate#778]
Is there any way to configure in system properties the application root?
I would like to override the default configuration (enunciate.xml), using something like: -Dapplication.root=http://server1/myContext/myApi
I mean, if it is defined in system properties use it, otherwise use the information available in enunciate.xml.

Regards,

Markus Reichel

**Comment by stoicflame** [comment]
The configuration file (e.g. `enunciate.xml`) is filtered for maven properties. So you should just be able to do:

```xml
<enunciate> 
  <application root="${application.root}"/>
```

**Comment by markusreichel** [comment]
Thank you for your support!

Regards,

Markus Reichel
