### ISSUE TITLE
Can't open Swagger UI: "fetching resource list path/index.html/../swagger.json; Please wait." hangs

### ISSUE THREAD

**Issue by hosswald** [stoicflame/enunciate#779]
Enunciate seems to generate a faulty Swagger index.html (might as well be a Swagger problem):
![image](https://user-images.githubusercontent.com/32925139/33262898-1fe71078-d368-11e7-9c93-1837d9678754.png)

It hangs, nothing loads.
The source code of the index.html says the following:

```
if (url && url.length > 1) {
   url = decodeURIComponent(url[1]);
} else if (document.location.href.substring(0, 5) === "file:") {
   url = "../swagger.json";
} else {
   var baseUrl = document.location.href;
   //this removes the anchor at the end, if there is one
   baseUrl = baseUrl.substring(0, (baseUrl.indexOf("#") == -1) ? baseUrl.length : baseUrl.indexOf("#"));
   //this removes the query after the file name, if there is one
   baseUrl = baseUrl.substring(0, (baseUrl.indexOf("?") == -1) ? baseUrl.length : baseUrl.indexOf("?"));
   //this removes everything after the last slash in the path
   baseUrl = baseUrl.substring(0, (baseUrl.lastIndexOf("/") == -1) ? baseUrl.length : baseUrl.lastIndexOf("/"));
    
   url = baseUrl + "/swagger.json";
}
```

The problem could be that Chrome (64.0.3269.3 64bit) can't resolve `index.html/../swagger.json` since `index.html` is not a directory. It could also be the duplicate `file://`. I'm unsure what the cause for this is. I use `./swagger/` as the output folder, but the same happens with the default `./ui/`.

**Comment by stoicflame** [comment]
What _should_ it look like? Can you find a URL that works?

**Comment by Mart-Bogdan** [comment]
Hello, @hosswald , are you opening swagger from local Disk?
Browsers has restricvtion policy, regarding ajax for local files!

use some kind of web serve, i'm using [node-web-server](https://www.npmjs.com/package/nws), for example

**Comment by stoicflame** [comment]
Since we haven't heard back, I'm going to close this issue for now. I really don't know of any solution that allows a `swagger.json` loaded from the local filesystem, since it violates the browser's cross-domain policy. If someone can provide me a `file:///` url that works, I'd be happy to apply a workaround for that case.
