### ISSUE TITLE
Is it possible to generate Rest Resources with context root to be prepended

### ISSUE THREAD

**Issue by KishoreGGK** [stoicflame/enunciate#780]
We have Rest endpoints annotated using @path annotation in Java file for Jaxrs resources. However the context root of the web application where these JAX-RS resource reside is not part of path annotation.

Is there any option to pass any string to start these resources are prep-ended with this context root so that enunciate generated documentation has full path.

**Comment by stoicflame** [comment]
```xml
<enunciate>
  <application path="/mycontext"/>
```
