### ISSUE TITLE
XML generated docs is appened by ----- after first letter Root Element

### ISSUE THREAD

**Issue by KishoreGGK** [stoicflame/enunciate#781]
In XML generated document the ----- is appended after the first letter of the Root Element.

Example:

```xml
<t----->
<testname>.... </testname>
<t----->
```

Expected:

```xml
<test>
<testname>.... </testname>
<test>
```

Is possible to display correct string ?

**Comment by KishoreGGK** [comment]
Unsure why my xml example is not displayed.

<t---->
<testname>...</testname>
<t---->

Explected
<test>
<testname>... </testname>
</test>

**Comment by stoicflame** [comment]
Full element names will be included in the example if the `@XmlRootElement` annotation is present. Otherwise, it's documenting the _data type_, which doesn't have an element name.
