### ISSUE TITLE
Not producing Json model with depth greater than 3

### ISSUE THREAD

**Issue by ashtondavvo** [stoicflame/enunciate#782]
When using enunciate to produce example Json models, objects which are children of a object at depth 3 aren't documented but instead just empty {}.

Is there a hard coded depth on example Json models?

```json
{
  "object1": {
    "id": "object_1_id",
    "object2": [
      {
        "id": "object_2_id",
        "name": "Object_2_Name",
        "address": {
          "number": "161",
          "street": "Unkown Street",
        },
        "groups": [
          "F44187B0-AD96-4975-B54A-752ED30DCB29",
          "4A76B6FA-A22C-4361-A4A0-5B6596511480"
        ],
        "object3": [
          {
            "id": "object_3_id",
            "object4": {}
          }
        ],
      }
    ]
  }
}
```

'object4' is an object documented exactly the same as object 1, 2 & 3.

I am using @DocumentationExample(), @JsonProperty & @JsonSeeAlso() however non of these annotations make a difference.

Is this a bug or is enunciate only intended to handle documenting Json objects to a certain depth?

**Comment by stoicflame** [comment]
This is by design. See #139.
