### ISSUE TITLE
Referenced JSON data types are not included in the documentation

### ISSUE THREAD

**Issue by cboehme** [stoicflame/enunciate#783]
Since updating the Enunciate maven plugin from version 2.9.1 to 2.10.1 it fails to find the data types referenced by the resources in my project. When generating the documentation with version 2.9.1 everything works as expected.

The debug output contains the following message  for each data type when building with 2.10.1. These messages to not appear when building with version 2.9.1:
```
[DEBUG] [ENUNCIATE] Element de.dnb.resolvingdienste.urnadministration.admin.restapi.model.RESTCreateAdminRequest is NOT to be added as a Jackson data type because [application/json;charset=UTF-8] doesn't seem to include JSON.
```

The project uses only the jaxrs and jackson modules. All other modules are disabled:
```
        <jaxrs disabled="false"
               groupBy="annotation"
               path-sort-strategy="depth_first"/>
        <jackson disabled="false"
                 honorJaxb="true"
                 dateFormat="string"
                 collapse-type-hierarchy="true"/>
        <docs disableResourceLinks="true"/>
```

My resources are defined as interfaces that look like this:
```
@Path("/admins")
public interface AdminResource {

    @POST
    @Consumes(MediaType.APPLICATION_JSON_VALUE)
    @Produces(MediaType.APPLICATION_JSON_VALUE)
    @TypeHint(RESTAdminRepresentation.class)
    @ResourceGroup(ApiGroup.SYSTEM_ADMIN_API)
    Response createAdmin(@QueryParam("runas") String runAs,
                         RESTCreateAdminRequest createAdminRequest);

}
```
The value of `MediaType.APPLICATION_JSON_VALUE` is "application/json;charset=UTF-8".

The `RESTCreateAdminRequest` data type a POJO without any annotations:
```
public class RESTUpdateAdminRequest {
	private String login;

	public String getLogin() {
		return this.login;
	}
	public void setLogin(final String login) {
		this.login = login;
	}
}
```

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).

**Comment by cboehme** [comment]
Thanks a lot for fixing this!
