### ISSUE TITLE
SOAP Service's path is preceding with additional slash

### ISSUE THREAD

**Issue by Sasi-Kat** [stoicflame/enunciate#784]
Soap Services documentation has been generated just fine as per sun-jaxws.xml . But, when I click the path to access service, there is an addition slash(/) within path which is blocking me access the service. I had to edit the path manually every time I want to access the service. I tried fixing this by changing soap service uri path, It led to service not getting register. 
Please let me know if there is anyway I can fix it at my side, or is it a bug with enunciate?

In the attached image, "/core" is my base path and "/soap/PresentationServiceResourceService" is my soap url path/pattern!
![enunciate soap path issue](https://user-images.githubusercontent.com/34354151/33741344-1f431666-db61-11e7-8629-f3ead7b271f1.png)

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
