### ISSUE TITLE
Make Enunciate Maven plugin Toolchain-aware 

### ISSUE THREAD

**Issue by stokito** [stoicflame/enunciate#79]
As temporary solution #68 we can compile modules that exposed with Enunciate with JDK6 but all others compile and run with JDK8.

But in Maven we can run plugin with different JDK only using a [Toolchain](https://maven.apache.org/guides/mini/guide-using-toolchains.html) and plugin should be toolchain compatible.

Would it be a good enough workaround?

**Comment by stoicflame** [comment]
Good idea. Thanks for the tip.

**Comment by stoicflame** [comment]
I'm going to claim this is fixed in Enunciate 2.0.0.
