### ISSUE TITLE
Spring's `@RestController` is not registered as meta-annotation

### ISSUE THREAD

**Issue by simonDeHero** [stoicflame/enunciate#790]
Following situation:
```
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@RestController // is meta-annotation
public @interface MetaAnnotated {
}
```
```
@MetaAnnotated
@RequestMapping(value = "/api")
public class ApiController {
...
```

Then when i run `mvn enunciate:docs` with the enunciate-maven-plugin, the docu is not generated. 

But somehow the ApiController is part of the found API elements according to output with `-X`:

[DEBUG] [ENUNCIATE] API Elements: [
...
com.example.ApiController
....

[DEBUG] [ENUNCIATE] Local API Elements: [
...
com.example.ApiController
...

[WARNING] [ENUNCIATE] No documentation generated: there are no data types, services, or resources to document.

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
