### ISSUE TITLE
Response codes are documented twice with Spring MVC

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#796]
Hi.

I'm currently using `2.11.0-SNAPSHOT` and encountered a problem when using SpringMVC's `ResponseStatus` annotation _and_ documenting using javadoc wrt response codes:

```
    /**
     * Deletes a user.
     *
     * @param userId
     *            The user identifier.
     * @HTTP 204 If the deletion is successful.
     * @HTTP 401 If authentication fails.
     * @HTTP 404 If the user is not found.
     * @HTTP 500 If an internal server error occurred.
     */
    @DeleteMapping(path = "/{user_id}")
    @ResponseStatus(code = HttpStatus.NO_CONTENT)
    public void delete(@PathVariable("user_id") String userId) {
```

Results in duplicate documentation of `204`:

![screen shot 2017-12-20 at 10 40 59](https://user-images.githubusercontent.com/3257311/34200745-7936ec2c-e572-11e7-9390-014dbdd7e817.png)

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
