### ISSUE TITLE
Make config xml schema available from web 

### ISSUE THREAD

**Issue by stokito** [stoicflame/enunciate#80]
I would like to have autocompleting in IDE when editing config xml
```xml
<enunciate label="tcp_integration" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="http://enunciate.codehaus.org/schemas/enunciate-1.20.xsd">
```

But http://enunciate.codehaus.org/schemas/enunciate-1.20.xsd is not available by URL.

![fetch-xsd](https://cloud.githubusercontent.com/assets/415502/7248770/2648177e-e81e-11e4-8590-43cf3cf823b2.png)

**Comment by stoicflame** [comment]
Thanks for the report. Fixed now.

**Comment by stokito** [comment]
Thanks you :-)
