### ISSUE TITLE
@link not working on @deprecated

### ISSUE THREAD

**Issue by brenthale** [stoicflame/enunciate#801]
I am trying to link to a different endpoint from a deprecated endpoint like this:
some 

```
/**
  * @deprecated Use {@link #imageSearch(ImageSearchSpec)} instead.
  */
public String someEndpoint() {
}

```
When the docs get generated, the link is not generated and simple text is inserted.  

`This method has been deprecated. Use #imageSearch(ImageSearchSpec) instead.`

I think this is similar to the following issues: 

- [@link doesn't generate hyperlinks when added in certain locations #703](https://github.com/stoicflame/enunciate/issues/703)
- [Why doesn't @link work in certain settings #728](https://github.com/stoicflame/enunciate/issues/728)

**Comment by stoicflame** [comment]
Thanks for the report.

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
