### ISSUE TITLE
cannot access com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable

### ISSUE THREAD

**Issue by nspalem** [stoicflame/enunciate#802]
I am getting the following error during 'mvn clean install' 
My pugin conf

```xml
				<plugin>
					<groupId>com.webcohesion.enunciate</groupId>
					<artifactId>enunciate-maven-plugin</artifactId>
					<version>2.10.1</version>
					<executions>
						<execution>
							<id>generate-service-docs</id>
							<phase>generate-resources</phase>
							<goals>
								<goal>docs</goal>
							</goals>
							<configuration>
								<docsDir>${asp.home}/html</docsDir>
								<configFile>enunciate.xml</configFile>
							</configuration>
						</execution>
					</executions>
				</plugin>
```

My enunciate.xml is like this

```xml
    <enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <application root="/asp" />
 		<modules>
			<jackson disabled="true"/> 		
			<jackson1 disabled="true"/>
			<jaxrs>
				<application path="/asp"/>
			</jaxrs>
		</modules>	 
    </enunciate>
```

and warning/errors are here.

```
[WARNING] [ENUNCIATE] [javac] [ERROR] null:-1:-1 error: cannot access com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable
[WARNING] [ENUNCIATE] [javac] error: cannot access com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable
[WARNING] [ENUNCIATE] [javac]   class file for com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable not found
[WARNING] [ENUNCIATE] [javac]   Consult the following stack trace for details.
[WARNING] [ENUNCIATE] [javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable not found
```

**Comment by nspalem** [comment]
Here is more info with 'mvn -X clean install'

Enunciate compile failed. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.10.1:docs (generate-service-docs) on project com.lgc.dist.core.msp.example.helloservice: Enunciate compile failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Enunciate compile failed.
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:406)
	at com.webcohesion.enunciate.mojo.DocsBaseMojo.execute(DocsBaseMojo.java:98)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: com.webcohesion.enunciate.EnunciateException: Enunciate compile failed.
	at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:726)
	at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:401)
	... 23 more
[ERROR] 
[ERROR]

**Comment by nspalem** [comment]
is this related to Jersey1 issue?

**Comment by stoicflame** [comment]
Finally getting around to looking at this. I'm afraid I still don't have enough information to debug the issue. Your API is referencing some class that is referencing `AbstractHttpContextInjectable`. You need to look at the debug output and include the lines before the `null:-1:-1 error: cannot access com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable` error to see what classes are being added to your API.

**Comment by stoicflame** [comment]
Since I haven't heard back, I'm going to close this for now. I'd be happy to re-open when I get more information.

**Comment by DerekParks** [comment]
I'm getting this same error. I can try to give you some info. Just let me know what you need. This is error I'm seeing:

```Reflections took 13995 ms to scan 412 urls, producing 728 keys and 728 values 
[javac] [ERROR] null:-1:-1 error: cannot access com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable
[javac] error: cannot access com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable
[javac]   class file for com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable not found
[javac]   Consult the following stack trace for details.
[javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable not found
```
Google is telling me `AbstractHttpContextInjectable` comes from Jersery 1-x. I'm only have jersey 2.27 in my deps:

```
    compile 'org.slf4j:slf4j-api:1.8.0-alpha2'
    compile 'org.slf4j:slf4j-simple:1.8.0-alpha2'

    compile 'commons-cli:commons-cli:1.4'
    compile 'org.glassfish.jersey.media:jersey-media-json-jackson:2.27'
    compile 'org.glassfish.jersey.containers:jersey-container-grizzly2-http:2.27'
    compile 'org.glassfish.jersey.media:jersey-media-moxy:2.27'
    
    compile group: 'org.codehaus.enunciate', name: 'enunciate-core-annotations', version: '1.31'
    
    compile group: 'org.glassfish.jersey.inject', name: 'jersey-hk2', version: '2.27'
    compile group: 'org.glassfish.jersey.containers', name: 'jersey-container-servlet-core', version: '2.27'

    testCompile 'junit:junit:4.10'
```

`gradle dependencies` doesn't show jersey 1-x getting pulled in as far as I can tell. 

```
$ /opt/gradle-4.8/bin/gradle dependencies | grep jersey | grep :1 | wc -l
0
```

```
$ gradle dependencies | grep jersey | grep :2.27 | wc -l
171
```
I love enunciate in my maven projects. I'd like to get it working with this graddle project. 
Maybe this is a gradle plugin issue?

**Comment by stoicflame** [comment]
Is there any way you could put together a simple sample project that manifests the error?

**Comment by stoicflame** [comment]
I've come across this issue on my own now.

**Comment by stoicflame** [comment]
In my case, the engine blew up when `org.apache.hadoop.hdfs.web.resources.UserProvider` was on the classpath.

**Comment by stoicflame** [comment]
This error appears when Enunciate picks up a class on the classpath that depends on Jersey 1. (In my case, it was `org.apache.hadoop.hdfs.web.resources.UserProvider`.)

The workaround is to explicitly exclude that class in the `enunciate.xml` config file.

I'll keep this issue open to see if I can think of a more robust solution.

**Comment by Wihiss** [comment]
Hello.

I face the same error:

[javac] [ERROR] null:-1:-1 error: cannot access com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable
[javac] error: cannot access com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable
[javac]   class file for com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable not found
[javac]   Consult the following stack trace for details.
[javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable not found

My enunciate.xml config looks like:

<?xml version="1.0"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.codehaus.org/schemas/enunciate-1.25.xsd">
    <api-classes>
        <include pattern="sctp.tms.utils.rest.UtilsController"/>
    </api-classes>
    <modules>
        <docs docsDir="restapi" title="REST API"/>		
    </modules>
</enunciate>

Probably that is a silly question, but how can I find out which my class depends on "Jersey 1" (technically there is no any explicit dependency in my project)?

Thank you.

**Comment by stoicflame** [comment]
It wasn't easy to find the endpoint that depended on Jersey 1. When you build with debug output, Enunciate will spit out a list of "API Elements" that it's going to consider as candidates for documentation. I had to exclude sets of these in my `enunciate.xml` config file until I narrowed it down to the endpoint that caused the problem.

**Comment by Wihiss** [comment]
Thank you for your answer. I tried to play with enunciate.xml. The latest version looks like

```
<?xml version="1.0"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.codehaus.org/schemas/enunciate-1.25.xsd">
    <api-classes>
        <include pattern="sctp.tms.utils.rest.UtilsController"/>
    </api-classes>
<modules>
        <spring-web />        
	<jackson datatype-detection="aggressive"/>

        <jaxb disabled="true"/>
        <jaxws disabled="true"/>
        <jaxrs disabled="true"/>
        <jackson1 disabled="true"/>

        <docs />
        <swagger />

        <c-xml-client disabled="true" />
        <csharp-xml-client disabled="true" />
        <java-xml-client disabled="true" />
        <java-json-client disabled="true" />
        <javascript-client disabled="true" />
        <gwt-json-overlay disabled="true" />
        <obj-c-xml-client disabled="true" />
        <php-xml-client disabled="true" />
        <php-json-client disabled="true" />
        <ruby-json-client disabled="true" />
        <idl disabled="true" />
    </modules>
</enunciate>
```

No luck ;-(

Now it gives something like:

[javac] [ERROR] null:-1:-1 error: cannot access org.codehaus.jackson.jaxrs.JacksonJaxbJsonProvider
[javac] error: cannot access org.codehaus.jackson.jaxrs.JacksonJaxbJsonProvider
[javac]   class file for org.codehaus.jackson.jaxrs.JacksonJaxbJsonProvider not found
[javac]   Consult the following stack trace for details.
[javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.codehaus.jackson.jaxrs.JacksonJaxbJsonProvider not found

**Comment by stoicflame** [comment]
Now it looks like you've got a class that depends on `JacksonJaxbJsonProvider`, but you don't have the class on your classpath.

**Comment by Wihiss** [comment]
In fact it throws either

cannot access org.codehaus.jackson.jaxrs.JacksonJaxbJsonProvider

or

cannot access com.sun.jersey.server.impl.inject.AbstractHttpContextInjectable

randomly (without any changes in source/config files).

Probably there is any specific for multi-modules projects (I have N modules in my project and a target one depends on several others)?

gradlew enunciate --debug prints something like this:

17:12:21.498 [DEBUG] [org.gradle.api.Task] Compiler sourcepath: [
]
17:12:21.498 [DEBUG] [org.gradle.api.Task] Compiler args: [-source, 1.8, -target, 1.8, -encoding, UTF-8]
17:12:21.498 [DEBUG] [org.gradle.api.Task] Compiler sources: [
... In fact here it prints path to all java files in the module
]
17:12:22.006 [WARN] [org.gradle.api.Task] [javac] [ERROR] null:-1:-1 error: cannot access org.codehaus.jackson.jaxrs.JacksonJaxbJsonProvider
17:12:22.006 [WARN] [org.gradle.api.Task] [javac] error: cannot access org.codehaus.jackson.jaxrs.JacksonJaxbJsonProvider
17:12:22.007 [WARN] [org.gradle.api.Task] [javac]   class file for org.codehaus.jackson.jaxrs.JacksonJaxbJsonProvider not found
17:12:22.007 [WARN] [org.gradle.api.Task] [javac]   Consult the following stack trace for details.
17:12:22.007 [WARN] [org.gradle.api.Task] [javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.codehaus.jackson.jaxrs.JacksonJaxbJsonProvider not found
17:12:22.007 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':java:tms:enunciate'
17:12:22.007 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :java:tms:enunciate FAILED
17:12:22.007 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :java:tms:enunciate (Thread[Daemon worker Thread 8,5,main]) completed. Took 4.856 secs.
17:12:22.007 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationWorkerRegistry] Worker root.12 completed (0 in use)
17:12:22.007 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 8,5,main]] finished, busy: 12.908 secs, idle: 0.002 secs
17:12:22.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:12:22.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:12:22.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:12:22.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
17:12:22.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':java:tms:enunciate'.
17:12:22.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Enunciate compile failed.
17:12:22.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
17:12:22.008 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
17:12:22.009 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
17:12:22.009 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
17:12:22.009 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] BUILD FAILED
17:12:22.009 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger]
17:12:22.009 [LIFECYCLE] [org.gradle.internal.buildevents.BuildResultLogger] Total time: 17.583 secs

**Comment by stoicflame** [comment]
At 8436787a8 I've significantly enhanced the error reporting for this problem. It won't stop the failure, but it will make it much easier to address it.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
