### ISSUE TITLE
Duplicate fields in Json example when field is annotated with @JsonUnwrapped

### ISSUE THREAD

**Issue by dellekappa** [stoicflame/enunciate#806]
When using the @JsonUnwrapped annotation on a field, the documentation generates correctly the inner fields but repeats the unwrapped field also.
e.g.
```java
public class JsonClass {
   @JsonUnwrapped
   private Foo foo;
   public Foo getFoo(){
      return this.foo;
   }
   public void setFoo(Foo foo){
      this.foo = foo;
   }
}

public class Foo {
   public String bar;
}
```
will produce this output

```json
{
  "bar" : "...",
  "foo" : {
      "bar" : "..."
  }
}
```

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
