### ISSUE TITLE
@JsonSubTypes and @JsonTypeName not kept in the generated jars

### ISSUE THREAD

**Issue by leforthomas** [stoicflame/enunciate#811]
I have some classes using polymorphism. The child classes have an @JsonTypeName annotation. This annotation is removed in the generated jar files, eg xxx-json-client.jar.
Likewise all the JsonSubTypes annotation is removed.
The project's generated class files are fine, ie the annotations are still there. My issue is with the jar files generated by enunciates.

This is some code to illustrate:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "@class")
@JsonSubTypes({
        @JsonSubTypes.Type(value = ChoiceOrderParameter.class, name = "choice"),
        @JsonSubTypes.Type(value = DoubleOrderParameter.class, name = "double"),
        @JsonSubTypes.Type(value = IntegerOrderParameter.class, name = "integer"),
        @JsonSubTypes.Type(value = TextOrderParameter.class, name = "text")
})
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class OrderParameter {

xxx

}
```

And then for the child classes

```
@JsonSerialize(include = JsonSerialize.Inclusion.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@JsonTypeName("choice")
public class ChoiceOrderParameter extends OrderParameter {

xxx

}
```

In the enunciate generated jar (xxx-json-client.jar), the class has removed all the sub types information. Therefore when attempting to deserialisize a message with ChoicOrderParameter for instance, it fails.

Do I need some "extra" annotations to make it work?

I am using enunciate 2.9.1, jersey 2.7.

**Comment by leforthomas** [comment]
Ouch I noticed enunciate uses the org/codehaus annotations, I use the fastxml ones, could that be the issue?

**Comment by stoicflame** [comment]
I'll add support for `JsonTypeName` as an enhancement.

The issue WRT embedded classes is a known issue; currently Enunciate doesn't generate any embedded child classes and puts everything at the package-level. It turns out that preserving the parent-child class hierarchy is tricky when you translate from java to JSON types and back.

**Comment by leforthomas** [comment]
OK, thanks for letting me know. Is there a work around to this?

Just to be clear, I don't want the generated classes to be embedded, quite contrary in fact. The issue I have is that the JsonSubTypes annotation is removed from the parent class. Is this normal?

**Comment by stoicflame** [comment]
I understand. It's normal; support for class-level `JsonSubTypes` isn't supported yet.

**Comment by leforthomas** [comment]
OK, would be easy to tweak? say if I decided to implement this enhancement myself?

**Comment by stoicflame** [comment]
My initial summary of work:

1. Edit `com.webcohesion.enunciate.modules.jackson1.model.TypeDefinition` and `com.webcohesion.enunciate.modules.jackson.model.TypeDefinition` to expose a property (e.g. `subtypes`) that exposes the subtype information.
2. Edit `java-json-client/src/main/resources/com/webcohesion/enunciate/modules/java_json_client/client-complex-type.fmt` to leverage this property at the class-level like it does at the member-level (e.g. line 111).

**Comment by leforthomas** [comment]
Great! I will take a look. Thanks.

**Comment by leforthomas** [comment]
I am having a look this morning but struggling to understand what the issue is.
I can live with the subtypes declared at member level as in TypeDefinition@111, and this seems already implemented in the freemarker template file client-complex-type.fmt@111. I can also see the annotations handled in Member@71, so all seems fine. However, the problem remains in the generated code, even with the subtypes annotation at the member level. Am I missing something?

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
