### ISSUE TITLE
When return type is `Response` then swagger.json response schema contains `"type": "file"`

### ISSUE THREAD

**Issue by simonDeHero** [stoicflame/enunciate#820]
My endpoint is annotated like this:
```
    /**
     * some docu
     *
     * @deprecated use other endpoint
     *
     * @RequestHeader Authorization "Basic ..."
     *
     * @HTTP 401 Authorization Header missing or not valid
     * @HTTP 500 Internal Server Error
     *
     * @return a JSON
     */
    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @Path("foo")
    @Deprecated
    Response getFoo();
```

the generated swagger.json then contains in the responses example section:
```
          "401": {
            "examples": {
            },
            "description": "Authorization Header missing or not valid"
          },
          "500": {
            "examples": {
            },
            "description": "Internal Server Error"
          },
          "200": {
            "schema": {
              "description": "a JSON",
              "type": "file"
            },
            "examples": {
            },
            "description": "a JSON"
          }
```

the problem now is, in the example for `200` there is a `"type": "file"`, which is wrong, it should be e.g. a `"$ref" : "..."` or so and examples should contain the content-type (at least my swagger-client-generator complains)

i tried to circumvent this problem by using `@documentationExample` or `@responseExample`, but this did not have any effect on the swagger.json - still there was `"type": "file"` and also **without** the specified example and content-type.

the only solution which worked, was using `@TypeHint(SomeClass.class)`, then the outcome was as expected:
```
          "200": {
            "schema": {
              "description": "a JSON",
              "$ref": "#/definitions/json_SomeClass"
            },
            "examples": {
              "application/json": {
                "dummy": "foo"
              }
            },
            "description": "a JSON"
          }
```

i am using enunciate version 2.9.1.

**Comment by panchenko** [comment]
From [Open API 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types)

> An additional primitive data type "file" is used by the Parameter Object and the Response Object to set the parameter type or the response as being a file.

I think that's an acceptable default where no specific type information is provided.

**Comment by simonDeHero** [comment]
as there exists `@Produces(MediaType.APPLICATION_JSON)` on the method, there is type information provided. therefore i don't expect "file" as type for this endpoint in the swagger.json (also not in the examples section).

**Comment by stoicflame** [comment]
Finally getting around to addressing this.

So what should the default be if not file? object? string? And why is it better than file? And what should be the algorithm for determining the right type?

**Comment by simonDeHero** [comment]
i understand, that without java type, enunciate cannot determine the json type here, so it needs a little help e.g. via `@TypeHint`. the only thing, which bothers me a little here is, that both `@documentationExample` or `@responseExample` did not work, so i had to add a real java annotation instead of such a nice, lightweight docu-annotation. 

so my expectation here would be, that for a return type `Response` also those 2 docu-annotations can be used as a hint for the returned value, and the swagger.json reflects it accordingly.

**Comment by stoicflame** [comment]
So is this just about using a JavaDoc tag instead of `@TypeHint`? Have you tried `@returnWrapped`?

**Comment by simonDeHero** [comment]
`@returnWrapped` did the trick, thank you very much!

now i am not sure about, whether `@documentationExample` or `@responseExample` are supposed to have an effect, when there is no type information given...
i leave it up to you to decide, whether they should be adopted or not. maybe a little hint in the documentation would be nice, that they only have an effect, in case the return type is not `Response`.

thx!

**Comment by stoicflame** [comment]
So when I use `@responseExample` (even without `@returnWrapped`), I still get the correct example, even though the data type isn't resolved to a type.

Here's a diff I applied to [enunciate-sample](https://github.com/stoicflame/enunciate-sample):

```diff
diff --git a/src/main/java/com/ifyouwannabecool/api/PersonaService.java b/src/main/java/com/ifyouwannabecool/api/PersonaService.java
index a1b238d..812e002 100644
--- a/src/main/java/com/ifyouwannabecool/api/PersonaService.java
+++ b/src/main/java/com/ifyouwannabecool/api/PersonaService.java
@@ -13,6 +13,7 @@ import javax.ws.rs.POST;
 import javax.ws.rs.Path;
 import javax.ws.rs.PathParam;
 import javax.ws.rs.Produces;
+import javax.ws.rs.core.Response;
 
 import com.ifyouwannabecool.domain.persona.Persona;
 
@@ -28,10 +29,11 @@ public interface PersonaService
      * Reads a persona.
      * @param personaId The id of the persona to read.
      * @return The persona.
+     * @responseExample application/json {"hello":"world"}
      */
     @Path("/{id}")
     @GET
-    Persona readPersona(@PathParam("id") String personaId);
+    Response readPersona(@PathParam("id") String personaId);
 
     @Path("/{id}.json")
     @GET
diff --git a/src/main/java/com/ifyouwannabecool/impl/PersonaServiceImpl.java b/src/main/java/com/ifyouwannabecool/impl/PersonaServiceImpl.java
index 72b8b7a..2b19a07 100644
--- a/src/main/java/com/ifyouwannabecool/impl/PersonaServiceImpl.java
+++ b/src/main/java/com/ifyouwannabecool/impl/PersonaServiceImpl.java
@@ -8,6 +8,7 @@ package com.ifyouwannabecool.impl;
 
 import javax.jws.WebService;
 import javax.ws.rs.Path;
+import javax.ws.rs.core.Response;
 
 import com.ifyouwannabecool.api.PermissionDeniedException;
 import com.ifyouwannabecool.api.PersonaService;
@@ -21,11 +22,9 @@ import com.ifyouwannabecool.domain.persona.Persona;
 public class PersonaServiceImpl implements PersonaService
 {
 
-    public Persona readPersona(final String personaId)
+    public Response readPersona(final String personaId)
     {
-        final Persona persona = new Persona();
-        // ...load the persona from the db, etc...
-        return persona;
+        return null;
     }
 
     public Persona readPersonaJson()
```

And here's the resulting documentation:

![image](https://user-images.githubusercontent.com/145838/39546431-9ff9f3b0-4e11-11e8-8cd9-a02d7a6d279a.png)

**Comment by simonDeHero** [comment]
sorry to continue discussing that (i actually also do not want to press things here, as i think, you know best, how the annotations should behave), but we are focusing on the `swagger.json`, not on the HTML. and in the `swagger.json` it still is:
```
          "200": {
            "schema": {
              "description": "a JSON",
              "type": "file"
            }
           ...
```
when i use `@responseExample application/json {}`. i tried with enunciate 2.9.1 and 2.10.1.
