### ISSUE TITLE
JSON example, sort properties by name

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#822]
When returning data from our API, we sort the JSON by keys, with this code:
```java
mapper.configure(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS, true);
mapper.configure(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY, true);
```

Is it possible to get the example JSON generated by Enunciate to do the same, so it matches?

**Comment by stoicflame** [comment]
Enunciate currently honors `@JsonPropertyOrder(alphabetic=true)`, but not a global config option.

**Comment by stoicflame** [comment]
At 215cb24:

```xml
<enunciate>
  <modules>
    <jackson propertiesAlphabetical="true"/>
```

**Comment by anton-johansson** [comment]
Awesome, thanks!

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
