### ISSUE TITLE
Support for generating documentation for Map key values?

### ISSUE THREAD

**Issue by foxdk** [stoicflame/enunciate#825]
Hi, we're using enunciate to generate documentation for our project. We're using JSON and defining our schema using Java. We use Java maps in parts of the schema, e.g.

public class Person {
  private EnumMap<NameFormTypeMapKey, NameForm> nameForms;

It would be nice if enunciate could generate documentation telling me what the valid values are for map keys in this case, that is, if if could show me that the key is of type NameFormTypeMapKey, and also tell me the values of that enum. I've looked at examples, etc. but I can't find anything like this. Is it currently supported by enunciate?

**Comment by stoicflame** [comment]
No, that's not supported yet. I'll track this as an enhancement request.

**Comment by stoicflame** [comment]
At #1011 support for json example overrides was added. I think that's as close as we're going to get for this issue for now.
