### ISSUE TITLE
Broken link in resource html file

### ISSUE THREAD

**Issue by nhhandyman** [stoicflame/enunciate#826]
I'm looking to generate docs only.

I started here: https://github.com/stoicflame/enunciate/wiki/User-Guide and looked at multiple examples (some of which seem to mix 1.n and 2.n syntax) without any luck on fixing the link to the generated class html file.
I am using ant and version 2.10 of enunciate.

A cut down config.xml:

```xml
<enunciate label="Web Services API"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.10.0.xsd">
    <api-classes>
      <include pattern="foo.bar.ws.**"/>
    </api-classes>
    <modules>
      <docs
        includeExampleJson="true"
        indexPageName="index.html"
      <docs/>
    </modules>
</enunicate>
```

The ant task:

```xml
    <enunciate
      configFile="${enu.temp.dir}/enunciate_config.xml"
      buildDir="${enu.build.dir}"
      basedir="${enu.base.dir}"
      >
      <classpath refid="enunciate.compile.class.path"/>
      <sourcepath refid="enunciate.source.class.path"/>
      <export artifactId="docs" destination="${Enunciate-Zip}"/>
    </enunciate>
```

The generated Resources page (index.html) is generated correctly (lists the resources correctly) but visiting the resource page shows a problem with the links to the class html files.

```html
<div id="resource_WsRestApiImpl_getAllAssociatedIdx_GET">
        <h3><span class="label label-default resource-method">GET</span> <span class="resource-path">/AssociatedIdx <a href="**./AssociatedIdx**" class="glyphicon glyphicon-new-window" target="_blank"></a></span></h3>
```

There is no "./AssociatedIdx" (or "./AssociatedIdx.html")  at the top level of the docs

It would seem that the href link comes from the Api java source file:

```java
    @Path("/AssociatedIdx")
```

Is that correct?

Is the problem that I have both json and xml specified in the produces annotation?

Enunicate does generate a `json_AssociatedIdx.html`

which seems to be where it should be pointing.

-------------------------------------------------------------------------

For reference:

WsRestApi.java

```java
    /**
    * Returns all {@link AssociatedIdx} objects.
    * @return A list of all {@link AssociatedIdx} objects.
    * @throws FooException on error.
    */
    @GET
    @Produces(
    {
        MediaType.APPLICATION_XML, MediaType.APPLICATION_JSON
    })
    @Path("/AssociatedIdx")
    public Response getAllAssociatedIdx() throws FooException;
```

WsRestApiImpl.java

```java
    @Override
    public Response getAllAssociatedIdx() throws FooException
    {
         ...
    };
```

If it matters, the annotations in the AssociatedIdx.java file are:

```java
@JsonIgnoreProperties(ignoreUnknown = true)
@XmlRootElement
public class AssociatedIdx extends ScaledIdx<AssociatedIdx> implements java.io.Serializable {
```

Thanks for any help.

**Comment by stoicflame** [comment]
Enunciate assumes these docs will be deployed in the same webapp in which all your resources are deployed. So it's trying to provide a link to the actual deployed resource that is being documented.

If the docs aren't being deployed in the same context as the resources, you may want to consider disabling the generation of that link altogether:

```xml
<enunciate>
  <modules>
    <docs includeApplicationPath="false"/>
```

If it _is_ deployed in the same context, you may need to provide an additional path to the resource:

```xml
<enunciate>
  <modules>
    <docs apiRelativePath="/mycontext"/>
```
