### ISSUE TITLE
Swagger UI: operation Response Content Type list order does not match that of @Produces annotation

### ISSUE THREAD

**Issue by nikb0yd** [stoicflame/enunciate#827]
... or should default to **application/json** for services configured with **jaxrs** enabled. At present, all methods default to **application/xml** in the Swagger UI. Am I missing something? Is there any way to alter the order of these lists absent a fix?

**Comment by stoicflame** [comment]
I didn't think the order was relevant. We'll need to provide a fix.

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
