### ISSUE TITLE
Override enumeration value

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#830]
I have an enuneration (`Language`) with a bunch of values, such as:
* `SWEDISH`
* `ENGLISH`

I have a custom serializer and deserializer for these, that outputs `sv` and `en` for example. But the generated docs won't see this of course. Is there a way to indicate the actual values? I couldn't find any appropriate annotation for it.

**Comment by panchenko** [comment]
It'ss possible in Jackson with the standard `@JsonProperty` annotation, please see [this](https://github.com/stoicflame/enunciate/blob/master/docs/src/test/samples/com/webcohesion/enunciate/samples/docs/CountEnum.java) example.

**Comment by anton-johansson** [comment]
Hmm, can't get it working. Maybe I'm missing some setting, or too old version. I'm using `2.9.1`.

Another thing is that I would like to sort the values alphabetically.

**Comment by stoicflame** [comment]
See #653.

Included in 2.10.

**Comment by anton-johansson** [comment]
Cool, thanks! Will try updating tomorrow.

**Comment by anton-johansson** [comment]
Worked great!
