### ISSUE TITLE
Enunciate compile failed - missing reference to org.springframework.hateoas.ResourceSupport

### ISSUE THREAD

**Issue by wombling** [stoicflame/enunciate#831]
Hi,

using enunciate version 2.10.1 (updating from 2.7.0) I find that when trying to compile I am missing a reference to org.springframework.hateoas.ResourceSupport

> [ENUNCIATE] [javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.springframework.hateoas.ResourceSupport not found

Is there a dependency that I should be adding to my pom.xml that I am missing?

I note adding:

```
<dependency>
    <groupId>org.springframework.hateoas</groupId>
    <artifactId>spring-hateoas</artifactId>
    <version>0.24.0.RELEASE</version>
</dependency>
```

did resolve this problem.

Thanks.

**Comment by wombling** [comment]
Ok - I switched to a different machine and error has gone away - (even without the additional dependency) so closing this.

Been one of those days...

**Comment by stoicflame** [comment]
Also, duplicate of #766.
