### ISSUE TITLE
Duplicate JSON Object Definitions

### ISSUE THREAD

**Issue by kkwansj** [stoicflame/enunciate#835]
I've come to discover a bizarre side effect of having both Jackson and Swagger modules enabled:
```
<modules>
  <jackson disabled="false"/>
  <swagger disabled="false" docsSubdir="ui"/>
</modules>
```
The `swagger.json` file generated ends up with duplicate definitions for JSON objects referenced by the API:
```
$ grep "\"json_.*\" : {" swagger.json | sort | uniq -c | sort -r
   2     "json_Foo" : {
   2     "json_Bar" : {
   ...
$ 
```
But if Jackson module is disabled in like:
```
<modules>
  <jackson disabled="true"/>
  <swagger disabled="false" docsSubdir="ui"/>
</modules>
```
or
```
<modules>
  <jackson disabled="false"/>
  <jackson1 disabled="true"/>
  <swagger disabled="false" docsSubdir="ui"/>
</modules>
```
Then, there are only unique definitions.
```
$ grep "\"json_.*\" : {" swagger.json | sort | uniq -c | sort -r
   1     "json_Foo" : {
   1     "json_Bar" : {
   ...
$ 
```
Is there a particular reason for this?

**Comment by stoicflame** [comment]
I'm guessing that the `jackson1` module is auto-enabled and when you force-enable the `jackson` module, then both the jackson 1 and jackson 2 data types are added to the model.

**Comment by stoicflame** [comment]
Haven't heard back; closing for now.
