### ISSUE TITLE
Spring web : Pageable and HttpServletRequest documentation problem

### ISSUE THREAD

**Issue by melbichon** [stoicflame/enunciate#837]
2.10.0 version has introduced support for Pageable spring web parameter (#711) and documentation for HttpServletRequest only when used with @RequestBody or @TypeInt (#701)

This is not working for me.

My code 

```java
@RequestMapping(value = "/{idUser}/{produit}", method = RequestMethod.GET)
public BibliothequeResponse getBibliotheque(
                  @PathVariable String idUser, 
                  @PathVariable  String produit,             
                  Pageable pageRequest,  
                  HttpServletRequest httpRequest) {...}
```

is rendered without pageable parameters and with a request body in documentation. 

![image](https://user-images.githubusercontent.com/6087602/37455198-d3172c9a-283c-11e8-9de8-f79705a8f76a.png)

Any idea ?

I'm using 2.10.1 and spring boot 1.5.9 version and my enunicate.xml is 

```xml
<description>Gestion des consommations numériques</description>
	<api-classes>
		<exclude pattern="org.springframework.**" />
	</api-classes>

	<modules disabledByDefault="true">
		<docs disabled="false" docsDir="${project.build.directory}" docsSubdir="docs" />
		<spring-web disabled="false"  />
		<swagger  basePath="/ccpcln" base="${basedir}/swagger-ui" />
		<jackson disabled="false" honorJaxb="true" dateFormat="string"
			collapse-type-hierarchy="true">
			<accessor-visibility type="field" visibility="any" />
		</jackson>
	</modules>
```

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
