### ISSUE TITLE
@link works only in the same package or by using fqn class names

### ISSUE THREAD

**Issue by mr678** [stoicflame/enunciate#838]
I'm very happy that enunciate supports in the meanwhile @link :-)

All the links are resolved fine for all classes inside the same package.

If I'm linking to classes (resources or data types) from other packages the link will not resolved.

It's working, if I use the fqn class name of the linked class. But unfortunately, I usually forget this because the IDE put the package part as import statement.

Is there a chance to consider the import statements during resolving the links?

**Comment by stoicflame** [comment]
Yes, this is a known issue.

Unfortunately,  the `javac` tool that Enunciate uses doesn't provide access to the import statements. There's just no way for Enunciate to resolve that class without the full package reference.

**Comment by mr678** [comment]
Hi Ryan,
thanks for your fast response and feedback. After checking the sources I already expected such an answer...
Bye Matthias
