### ISSUE TITLE
Since version 2.8.0, anonymous types are not supported

### ISSUE THREAD

**Issue by robjay** [stoicflame/enunciate#839]
I have a XSD with anonymous complex types which is converted to Java using xjc.

E.G

```xml
<xsd:complexType>
    <xsd:sequence>
        <xsd:element name="test">
             <xsd:complexType>

etc..
```

The xjc uses a @XmlType with an empty name parameter to indicate an anonymous type. In Enunciate version 2.7, this would have been outputted as Type (anonymous). Since version 2.8, due to the code in EnunciateJaxbContext.java (add function - JAXB XML type definition %s named %s conflicts with %s of the same name.") and the use of typeDef.getQname() in the map, since the name is empty, this just returns the namespace (which is the same for all anonymous types within the xsd). Consequently, there is a conflict, causing the types to be discarded.

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
