### ISSUE TITLE
@Consumes annotation (javax) may not set header content-type (on documentation generation) 

### ISSUE THREAD

**Issue by MarioMatosBraga** [stoicflame/enunciate#841]
_Javax Resource method_ 
```
    @POST
    @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
    public Response ValidateUserName(@FormParam(Constants.USERNAME))
```
**ENUNCIATE WILL PRODUCE THE FOLLOWING**: 

```
POST /test
Accept: application/json
```

**MY Expectation**:

```
POST /test
Accept: application/json
Content-Type: application/x-www-form-urlencoded 
```

**What i think is going on**: Enunciate fails to understand that there is a input for method test. As so, it ignores @Consume annotation. 

Thanks for any reply.

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
