### ISSUE TITLE
source exclusions are ignored

### ISSUE THREAD

**Issue by Thorndike** [stoicflame/enunciate#842]
I am currently using enunciate 2.10.1. In my maven debug log there are many lines like:

```
[WARNING] [ENUNCIATE] JAXB XML type definition de.creditreform.crefoteam.ctocrefoportal.ctoproductfactory.domain.v1.XmlProductAdressHistorieData.AdressHistorieEintraege named {http://www.creditreform.de/crefoteam/ctocrefoportal/ctoproductfactory/domain/v1} conflicts with de.creditreform.crefoteam.ctocrefoportal.ctoproductfactory.domain.v1.XmlProductAuskunftData.Onlineauskunftkapitels of the same name.
[WARNING] [ENUNCIATE] This will cause bugs in the generated documentation: all references to de.creditreform.crefoteam.ctocrefoportal.ctoproductfactory.domain.v1.XmlProductAuskunftData.Onlineauskunftkapitels will be resolved to de.creditreform.crefoteam.ctocrefoportal.ctoproductfactory.domain.v1.XmlProductAdressHistorieData.AdressHistorieEintraege.
[WARNING] [ENUNCIATE] It's recommended that you customize the name of one of these types using the @XmlType annotation.
```

My problem ist that those classes are used only for the connection to the backend and should not be in my generated API documentation. What I have tried so far:

- exclude packages in enunciate.xml (with /** at the end)
- exclude the artifact in pom configuration
- exclude the artifact that contains the transitive dependency to the classes

Nothing worked so far.

**Comment by stoicflame** [comment]
So [here's the guide on excluding classes](https://github.com/stoicflame/enunciate/wiki/Excluding-Including-Classes), but it looks like you've already seen it and are wondering why your classes are still included. 

As stated in that guide:

> However, if an excluded class is explicitly referenced by an included class, Enunciate will automatically include it (regardless of configuration) in order to avoid broken references.

So I'm guessing that some part of your API is exposing those backend classes. You might find a hint about which API is exposing those in the debug output; look to where it logs those classes being included and note the nearest neighbors.

**Comment by stoicflame** [comment]
Bump.

Any word on this?

**Comment by stoicflame** [comment]
Okay, since I don't have any means to debug the issue, I'll close this for now.

If you are explicitly excluding those classes in the config, and they're being added anyway, you should see a message in the debug output that says something like this:

```
Added de.creditreform.crefoteam.ctocrefoportal.ctoproductfactory.domain.v1.XmlProductAdressHistorieData.AdressHistorieEintraege as a JAXB type definition even though it was supposed to be excluded according to the configuration. It was referenced from ...
```

So unless this reporting mechanism is broken, you should have information on how those classes are being referenced.
