### ISSUE TITLE
Replace CDN loaded Bootstrap css

### ISSUE THREAD

**Issue by imousmoutis** [stoicflame/enunciate#844]
I need to load the generated documentation pages in an offline mode.

I would like to know if there is a solution to loading the bootstrap library from my resources and to replace the the CDN loaded bootstrap that is set by default.

I tried adding a bootrstrap file to enunciate.xml but it still is making a request to maxcdn which makes the documentation pages very slow.

**Comment by stoicflame** [comment]
See https://github.com/stoicflame/enunciate/wiki/Custom-Skin.

You might need a custom documentation base.

**Comment by imousmoutis** [comment]
I tried doing so following the steps below:
1. I edited the https://github.com/stoicflame/enunciate/tree/master/docs and made the templates the way i needed.
2. I added the js and css files.
3. I zipped it and then I started getting errors when I tried to generate the documentation concerning the format of the zip.

So it wasn't very clear to me how the custom templates should be structured.

**Comment by stoicflame** [comment]
What were the errors?

**Comment by imousmoutis** [comment]
The error that comes up is: 
`[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:2.4.0:bundle (default-bundle) on project wapis-web: Internal error in maven-bundle-plugin: 
Problem writing resource custom-docs.zip: Opening resource: Illegal/unsupported escape sequence near index 10
[ERROR] ??_Zql???\E?hni?☻??I???☺??Zrf|?[↔?-Q2+?n?}??☺???2f?K%U/♦?♣?Y§=i[??<???=????3??l?`&}???d`
I didn't change anything in the code. I just zipped the contents of the template folder in the docs directory.

**Comment by stoicflame** [comment]
So that error is happening in the maven-bundle-plugin, correct? It seems like the maven-bundle-plugin is incorrectly configured. Can you confirm?

**Comment by imousmoutis** [comment]
Yes the error takes place when I compile the project.
If you are referring to the enunciate.xml file, I added the following line: 
`<docs disabled="false" base="./custom-docs.zip"/>`
I will attach the zip file so you can see the structure.
[custom-docs.zip](https://github.com/stoicflame/enunciate/files/1897465/custom-docs.zip)

Other than that I don't do anything else for the custom template.

**Comment by imousmoutis** [comment]
@stoicflame do you have any update on this?

**Comment by stoicflame** [comment]
Sorry for the response delay. That custom base works for me. There must be something in your environment that's weird.

Here's a diff I applied to [enunciate-sample](https://github.com/stoicflame/enunciate-sample):

```diff
diff --git a/enunciate.xml b/enunciate.xml
index 070bc89..c064f97 100644
--- a/enunciate.xml
+++ b/enunciate.xml
@@ -13,7 +13,7 @@
   </namespaces>
 
   <modules>
-    <docs>
+    <docs base="/tmp/custom-docs.zip">
       <download file="LICENSE" name="Apache II" description="The license governing this API" showLink="true"/>
     </docs>
     <java-xml-client>
@@ -23,4 +23,4 @@
     </java-xml-client>
   </modules>
 
-</enunciate>
\ No newline at end of file
+</enunciate>
```

Can you modify that diff in such a way that it exposes the problem you're seeing?

**Comment by imousmoutis** [comment]
I cloned your enunciate-sample repo, then added the base URI to the docs element in enunciate.xml. 
The project doesn't take the changes I've made into consideration and keeps on loading the the bootstrap library through the CDN.
I can see in the target directory that the template is copied in the project but the index page still loads the same things.

**Comment by stoicflame** [comment]
The index page is hard-coded into the freemarker transform, so you'll need to provide a custom freemarker transform. See [section "Custom Freemarker Transform" in Custom Skin](https://github.com/stoicflame/enunciate/wiki/Custom-Skin#custom-freemarker-transform).
