### ISSUE TITLE
JsonTypeInfo property missing in sub-types

### ISSUE THREAD

**Issue by simonDeHero** [stoicflame/enunciate#850]
Hi,
i have the following type hierarchy:

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type(value = Dog.class, name = "dog"),
        @JsonSubTypes.Type(value = Cat.class, name = "cat")
})
public abstract class Animal {
}
```

```
public class Cat extends Animal {
}
```

```
public class Dog extends Animal {
}
```

In this case, enunciate 2.10.1 renders the `type` **only** for `Animal` but **not** the sub-classes `Cat` or `Dog`. Neither in HTML docu, nor in swagger.json.

This is related to #636

**Comment by simonDeHero** [comment]
to be more more specific, i use `<jackson collapse-type-hierarchy="true" />`, see https://github.com/stoicflame/enunciate/pull/851

**Comment by stoicflame** [comment]
[Enunciate 2.11 has been released](https://github.com/stoicflame/enunciate/releases/tag/v2.11.0).
