### ISSUE TITLE
Generating a hierarchical api catalog 

### ISSUE THREAD

**Issue by shahamit** [stoicflame/enunciate#855]
Hi,
With the latest version of enunciate, we are trying to generate documentation in a multi-module gradle project. We use jax-rs annotations for our rest api's. Each module in the project does generate a bunch of rest api's. My questions is how can I group them in hierarchical fashion that shows first the module-name then the class or any custom name. I understand the jax-rs module does have a @ResourceGroup annotation that allows you to configure a custom value but I didn't follow how can I make it hierarchical with at least two levels. 

Kindly share your thoughts. Thanks!

**Comment by shahamit** [comment]
I am not referring to build configuration for merging any artifacts. I am
trying to see how we can *display* the list of all APIs in an hierarchical
fashion.

Kindly let me know your thoughts. Thanks

**Comment by stoicflame** [comment]
I see.

Well, I haven't given it much thought, but I'm open to suggestions. If you'd like to make a proposal, I'd be happy to hear it.
