### ISSUE TITLE
Is it possible to control the example request/response body values?

### ISSUE THREAD

**Issue by shahamit** [stoicflame/enunciate#859]
I am using the latest enunciate version to generate documentation for our rest api's that are based on jax-rs annotations. Enunciate does recognize the java types and generates sample values for the request and response objects. I have a couple of questions

1. Is it possible to control the values of the properties of the java types that are generated for the example request/response body? Sometimes the default values are not appropriate for the business object 
For e.g. Assuming the api returns an array of tables where each table has id and a name. The id value is supposed to be unique but since the values are default, we see two array objects have the same value '12345'. Is it possible to add some annotations to control these values?

2. For an api that returns a Long object (shown as number) there is no default value generated. The example response body just shows ... Can we show some number here?

Thanks.

**Comment by panchenko** [comment]
Yes, it's possible, please check the [documentation](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations).

**Comment by stoicflame** [comment]
As noted by @panchenko, please see the documentation.

Note the use of `@DocumentationExample` annotation, `@documentationExample` JavaDoc tag, `@requestExample`, `@responseExample`, etc.
