### ISSUE TITLE
enunciate.xml xsi:noNamespaceSchemaLocation URL

### ISSUE THREAD

**Issue by dcarr99** [stoicflame/enunciate#86]
xsi:noNamespaceSchemaLocation in the sample enunciate.xml files is set to 

http://enunciate.codehaus.org/schemas/enunciate-x.yy.xsd

where x.yy is the version number.  Codehaus.org no longer hosts those XSD files.  

* Is there a new location for those?
* can the documentation and sample code be updated?

Thanks again for the tool - another happy user,
Doug.

**Comment by stoicflame** [comment]
Thanks for the report. Examples have been updated. New location is:

http://enunciate.webcohesion.com/schemas/enunciate-x.yy.xsd

**Comment by dcarr99** [comment]
Thanks!
