### ISSUE TITLE
More Organized Documentation for Versioned API's

### ISSUE THREAD

**Issue by shahamit** [stoicflame/enunciate#861]
We plan to use the latest version of enunciate for generating documentation for our jax-rs based rest api's. We have decided to use header based versioning (as opposed to url based versioning) where the version number is specified as part of the media/content type. 

Currently enunicate creates a new api for every different media type it parses in the java file. The api's are though organized inside the same web page. I would like to understand if this organization can be changed.

To get better clarity to the readers of the api documents, I visualize to have different web pages for different versions of the api. This will help to get a clear picture of what api's are newly added or removed or updated in a particular version.

Is that something possible with enunciate? Some pointers as to what code changes would be involved in making this happen or directions to make this work through some work arounds would be appreciated.

Thanks

**Comment by panchenko** [comment]
Looks like you could use the [Facets](https://github.com/stoicflame/enunciate/wiki/Facets) feature.

**Comment by panchenko** [comment]
Would could theoretically work:
* define your facet annotations, like `@Version1`, `@Version2` etc
* annotate the code accordingly
* invoke enunciate **multiple times** to generate documentation, with different configuration each time

**Comment by stoicflame** [comment]
I agree that the existing facet mechanism is the best that we currently provide, but I also think support for media-type-based versioning could be integrated as a first-class concept into Enunciate core. I'd probably start by looking at adding each media type as a different "Syntax" (see `com.webcohesion.enunciate.api.datatype.Syntax`) and have the XML, JSON modules provide multiple syntaxes instead of just a general one.

Again, this is something I probably wouldn't pick up myself without more demand or without a sponsor. I'll keep the issue open for upvotes and tag it as "seeking sponsor".

**Comment by shahamit** [comment]
One related question - With facets I am able to generate different documentation for different versions. Is it possible to generate a "latest" version of the documentation for different modules. Taking an example to explain what I meant by "latest" For e.g. If module1 exposes two versions of their api - v1 and v2 but module2 has just one version for their api - v1, how can I generate a single documentation that contains the api's for both the modules include v2 for api from module2 and v1 (since thats the latest for this module) for api from module1?

**Comment by panchenko** [comment]
For example, you can  define another facet `@LatestVersion` and annotate code with it

**Comment by shahamit** [comment]
Another test I was trying was to add 
```
<modules>
<api-classes> 
        <exclude pattern="module2" /> 
</api-classes> 
</modules>
```
but that didn't exclude the classes that had `@Path` annotation (jax-rs). Did I miss something?

**Comment by panchenko** [comment]
I guess it would be nice if specifying the **included** facets.
Without that a possible idea is defining versions per module, then it would be quite fine-grained.

**Comment by shahamit** [comment]
@stoicflame  - Thinking through it more, it seems that api versioning would be at the method level and not at the class level. Consider a case where one of the methods requires a need to version the api. Assuming there are already tens of methods in that api, marking all of them with `@DeprecatedVersion` may not be practical while marking the newly added/updated methods with `@LatestVersion` also doesn't sound practical. 

@panchenko - I didn't follow how would `<include>` facets help. 

Another approach could be to create the documentation per module per version. So the drilldowns in the web page would be 
Level 1 – List of all modules, 
Level 2 – Individual versions of that module api
Level 3 – API Documentation

My goal with adding` <api-classes>` tag was to include/exclude modules such that documentation gets generated only for one module at a time. This is not working out though. 

Let me know your thoughts.

**Comment by shahamit** [comment]
> What's not working out? You get an error? Or is it just the classes aren't getting excluded.

Yes, the classes aren't getting excluded. I do reference them as java package names exactly as you state in the example "com.mycomany.module2.**". I am not sure what's going wrong. Any suggestions?

**Comment by shahamit** [comment]
> So what is practical? Somehow you've got to distinguish the "v1" API from the "v2" API.

I tried out again to generate the latest version of the documentation and it worked by adding the annotation called @LatestVersion in addition to the annotation for version number i.e. @Version1, @Version2.

> What's not working out? You get an error? Or is it just the classes aren't getting excluded.

Yes initially I added the `<api-classes>` tag inside `<modules>` because the schema validator complained about adding it to the root element but despite the compiler error if I add it to the root element, the classes indeed got included/excluded. Something wrong with the xsd.

One related question - can we modify this config programmatically? i.e. including/excluding a java pacakge at run time?

**Comment by stoicflame** [comment]
I can't explain the schema validation error; my validator doesn't complain. What's the message you get from your validator?

Yes, you can add includes/excludes programmatically. See the `com.webcohesion.enunciate.Enunciate.addInclude(String)` and `com.webcohesion.enunciate.Enunciate.addExclude(String)` methods.

**Comment by shahamit** [comment]
Here's the error that i see when `<api-classes>` is added to the root element - https://pasteboard.co/HnFDiyD.png

Here's the xsd that i import - http://enunciate.webcohesion.com/schemas/enunciate-2.10.0.xsd

**Comment by panchenko** [comment]
I guess you have this element after`facets`, worth trying before?
