### ISSUE TITLE
(Jackson module) Generics fails at depth > 1

### ISSUE THREAD

**Issue by hosswald** [stoicflame/enunciate#864]
The data types in enunciate lack type information below depth 1. 
My REST API returns everything wrapped in a `ResponseContainer<T>`. Assume there are two endpoints, one returning `ResponseContainer<List<Type1>>`, one returning `ResponseContainer<List<Type2>>`.
Enunciate generates only one data type:
`ResponseContainerOfList`
To increase the confusion even further, the propertiy information for the type declares that the field `data`, which is of type `T`, has type `array of Type1`. Since there is only one `ResponseContainerOfList`, the endpoint returning `ResponseContainer<List<Type2>>` is thus documented incorrectly.

I debugged a bit and found that the first time the breakpoint holds [here](https://github.com/stoicflame/enunciate/blob/master/jackson/src/main/java/com/webcohesion/enunciate/modules/jackson/javac/ParameterizedJacksonTypeElement.java#L45), `root` is `ResponseContainer<List<Type1>>` (correct),  `element` is `ResponseContainer` (lacks verbosity), `typeArg` is `List<Type1>` (correct), but `argType` is only `List` (incorrect). That looks like where the incomplete name `ResponseContainerOfList` is coming from.
Then, it seems like the resulting type information is stored for `element == ResponseContainer` where it should be stored for the full generic type. That looks like where the singular nature of the type is coming from.

**Comment by stevenschlansker** [comment]
Candidate fix available in #955, please let me know if this fixes your problem 😸

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
