### ISSUE TITLE
Generate only swagger file

### ISSUE THREAD

**Issue by felzan** [stoicflame/enunciate#866]
Hi,
There is a way to just generate a swagger file?
I would like to use another UI (like Redoc). And i just need to generate a swagger file from my REST API.

**Comment by stoicflame** [comment]
The swagger file is there in the output; just copy it where you need it and delete the rest of the files.

**Comment by atkawa7** [comment]
@stoicflame @felzan Checkout https://github.com/atkawa7/httpsnippet for generating code snippets with springfox and redoc
