### ISSUE TITLE
Primitives should be marked as "required" automatically

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#875]
Currently generated documentation won't make primitive return types of models required automatically. Instead one has to provide e.g. `@NotNull` for primitives - which looks strange :).
Example:

```
...
@NotNull
public boolean isSupported() {
...
}
...
```
It would be nice if required would automagically appear for primitives.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
