### ISSUE TITLE
Support for composite annotations

### ISSUE THREAD

**Issue by dve** [stoicflame/enunciate#877]
I want to apply the same annotations to a method again and again, for example:
```
@RequestHeaders({
         @RequestHeader(name = "Authorization", description = "The auth token") })
@StatusCodes({
         @ResponseCode(code = 403, condition = "The user has not enough rights") })
@GET
...
```

To not duplicate the strings all the time I would like to use:
```
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.TYPE, ElementType.METHOD, ElementType.PACKAGE })
@RequestHeaders({
      @RequestHeader(name = "Authorization", description = "The auth token") })
@StatusCodes({
      @ResponseCode(code = 403, condition = "The user has not enough rights") })
public @interface Auth
{}
```

and
 ```
@Auth
@GET
...
```

But the annotation processor seems to ignore the annotations at the annotation. Is there a differen way to achieve my goal or do I have to provide a PR?

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
