### ISSUE TITLE
Wrong encoding of generated files + Solution

### ISSUE THREAD

**Issue by GFriedrich** [stoicflame/enunciate#878]
Hi,

just stumbled into trouble with some encoding errors in a generated WSDL.
I also saw that some people before me had the same problem - there #488 and there #325

As you said you were never able to reproduce the problem, so I decided to step through the whole stuff and found the reason: In [line 70 of the BaseXMLInterfaceDescriptionFile](https://github.com/stoicflame/enunciate/blob/master/idl/src/main/java/com/webcohesion/enunciate/modules/idl/BaseXMLInterfaceDescriptionFile.java#L70) class you're using a FileWriter. Unfortunately this writer will use the default encoding of the operating system (which for some operating system might be != UTF-8). If you would be using something like a OutputStreamWriter here, with a configurable CharSet, all the trouble should be gone. :sunglasses: 

Looking forward to a fix.
Thanks for taking care.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
