### ISSUE TITLE
Add annotation to mark a field as password

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#880]
OpenApi has the ability to mark a type as a password.

It would be neat, if a field in a DTO could be marked with "@Password" (or similar) to collect this information from source.

See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#dataTypes

(I see there is BaseTypeFormat.PASSWORD, but no way to trigger it)

**Comment by stoicflame** [comment]
Fixed at 3ae7619. See [docs](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#cwempassword).

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.

**Comment by joprice** [comment]
Can this annotation be used for `FormParam`s as well? I tried it and it seems to not have an effect. Is the solution to use this together with the `@BeanParam` annotation?

**Comment by stoicflame** [comment]
It really only has an effect on Swagger documentation.

Did you have any thoughts on how it can show up in the Enunciate docs?
