### ISSUE TITLE
EnunciateJaxbContext should map java.time types to their equivalent XML type

### ISSUE THREAD

**Issue by jskovjyskebankdk** [stoicflame/enunciate#881]
Something like the below (and possibly for more types):

  knownTypes.put(java.time.LocalDate.class.getName(), KnownXmlType.DATE);
  knownTypes.put(java.time.LocalTime.class.getName(), KnownXmlType.TIME);
  knownTypes.put(java.time.LocalDateTime.class.getName(), KnownXmlType.DATE_TIME);
  knownTypes.put(java.time.OffsetDateTime.class.getName(), KnownXmlType.DATE_TIME);
  knownTypes.put(java.time.ZonedDateTime.class.getName(), KnownXmlType.DATE_TIME);

Or am I misunderstanding the code?

**Comment by stoicflame** [comment]
Yep. Tracking as an enhancement request.

**Comment by foxdk** [comment]
@stoicflame I'm not sure if my problem is related--I find that @DocumentationExample doesn't work right (and causes the build to crash) if I do something like this:

  @DocumentationExample("2018-11-28T16:12:03.082Z")
  public OffsetDateTime getSubmittedOffsetDateTime() {
    return submittedOffsetDateTime;
  }

The build crashes with:
[WARNING] [ENUNCIATE] "2018-11-28T16:12:03.082Z" was provided as a documentation example, but it is not a valid JSON whole number, so it will be ignored.
...
[ERROR] Failed to execute goal com.webcohesion.enunciate:enunciate-maven-plugin:2.11.1:assemble (default) on project tem-temple: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('-' (code 45)): was expecting comma to separate OBJECT entries
[ERROR] at [Source: java.io.FileReader@4803b73f; line: 1085, column: 30]: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class

Enunciate seems to want this field to parse as a number. Is this a known problem, or should I create a new ticket for it?
