### ISSUE TITLE
editor.swagger.io throws error on reading Enunciate generated swagger.json

### ISSUE THREAD

**Issue by sakthisunda** [stoicflame/enunciate#884]
Data: Enunciate (2.11.1) generated swagger.json 

Error Infomation:
Schema error at paths['/admin/amqp'].put.parameters[0]
should NOT have additional properties
additionalProperty: schema, name, in, description
Jump to line 35286
Schema error at paths['/admin/amqp'].put.parameters[0].in
should be equal to one of the allowed values
allowedValues: header, formData, query, path
Jump to line 35288

The lines contain the following data (swagger.json)

        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "description": "",
              "type": "file"
            },
            "description": ""
          }
        ]

**Comment by stoicflame** [comment]
Please report the version of the editor you're attempting to use.

**Comment by sakthisunda** [comment]
This is the public url online editor.swagger.io.

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 26, 2018 at 8:12 AM, Ryan Heaton<notifications@github.com> wrote:   
Please report the version of the editor you're attempting to use.

**Comment by stoicflame** [comment]
Yes. Enunciate doesn't support Swagger 2 and OpenApi 3 yet. See #856.

You'll need to use Swagger 1.0 for now, or use the OpenApi Enunciate module provided at https://github.com/Jyskebank/enunciate-openapi.

**Comment by sakthisunda** [comment]
Any expected upcoming Enunciate release that supports Swagger 2 and openApi 3 ?

**Comment by sakthisunda** [comment]
If I enable openApi3, should I also disable swagger module since it does not support swagger 2. ?
