### ISSUE TITLE
Enunciate generated swagger.json has same method definition recorded multiple times

### ISSUE THREAD

**Issue by sakthisunda** [stoicflame/enunciate#886]
Enunciate 11.x
Same JAX-RS signature got recorded multiple times just with "operationId"  changed with numbered 1,2,3 etc. Some signatures are recorded three times.  Sample below.

```json
"get" : {
        "tags" : [ "\/admin/extension/service" ],
        "summary" : "Retrieves a list of extension service operations.",
        "description" : "Retrieves a list of extension service operations.",
        **"operationId" : "getExtensionServices",**
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [
        ],
        "responses" : {
          "200" : {
            "schema" : {
               "description" : "Representation of extension service operations.",
               "type" : "file"
            },
                    "description" : "Representation of extension service operations."
          }
        }
      }
```

```json
"get" : {
        "tags" : [ "\/admin/extension/service" ],
        "summary" : "Retrieves a list of extension service operations.",
        "description" : "Retrieves a list of extension service operations.",
        **"operationId" : "getExtensionServices2",**
        "produces" : [ "application/json", "application/xml" ],
        "parameters" : [
        ],
        "responses" : {
          "200" : {
            "schema" : {
"description" : "Representation of extension service operations.",
"type" : "file"
            },
            "description" : "Representation of extension service operations."
          }
        }
      }
    }
```

My enunciate.xml

```xml
<?xml version="1.0"?>
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.9.0.xsd">    
    <modules>
         
        <jackson1 disabled="true" />
        <jaxws disabled="true" />


        <c-xml-client disabled="true" />
        <csharp-xml-client disabled="true" />
        <java-xml-client disabled="true" />
        <java-json-client disabled="true" />
        <gwt-json-overlay disabled="true" />
        <obj-c-xml-client disabled="true" />
        <php-xml-client disabled="true" />
        <php-json-client disabled="true" />
        <ruby-json-client disabled="true" />



        <!-- Enabled modules -->
        <jaxrs disabled="false" groupBy="path" path-sort-strategy="depth_first" />
        <jaxb disabled="false" disableExamples="true" datatype-detection="aggressive" />
        <jackson disabled="false" disableExamples="true" datatype-detection="aggressive" />
        <spring-web disabled="false" />
        <docs disabled="false" />
        <swagger disabled="false" basePath="/api" />
        <idl disabled="false" />
    </modules>
</enunciate>
```

**Comment by stoicflame** [comment]
I'm going to need some way to reproduce the problem. I'm pretty sure if Enunciate's generating multiple methods, it means you've got multiple methods defined for that path.

Can you confirm?

**Comment by sakthisunda** [comment]
I guess, **multiple methods for same path is not allowed in JAX-RS.**

I double checked the code and verified code does not have mulitple methods. The method appears only once. Even if I have different method, I should see that method name. Here they are appearing as follows.

getExtensionServices
getExtensionServices2
getExtensionServices3

My only signature appears like this:


@Path( "/admin/extension/service" )
public class SubClass extends BaseClass {

    @GET
    @Produces({ "application/xml", "application/json"})
    public JAXBElement<ExtensionServicesType> getExtensionServices(final @Context UriInfo uriInfo) {

   }
}

**Comment by stoicflame** [comment]
Fair enough. I just can't reproduce it on my end; I don't know how those duplicate methods are getting generated.

Can you modify the [enunciate-sample](https://github.com/stoicflame/enunciate-sample) app in such a way that the problem is manifest? If so, can you send me the diff?

The output of `mvn -X` might also help. Look for where Enunciate adds `SubClass` to the project.

**Comment by sakthisunda** [comment]
In debug file with mvn -X I found following entries with SubClass

[DEBUG] [ENUNCIATE] SubClass isn't a potential Jackson type because of annotation javax.ws.rs.Path.
 
[DEBUG] [ENUNCIATE] SubClass isn't a potential Jackson type because of annotation javax.ws.rs.Path.
[DEBUG] [ENUNCIATE] SubClass isn't a potential JAXB type because of annotation javax.ws.rs.Path.
[DEBUG] [ENUNCIATE] SubClass isn't a potential JAXB type because of annotation javax.ws.rs.Path.
[DEBUG] [ENUNCIATE] Added SubClass as a JAX-RS root resource.

[DEBUG] [ENUNCIATE] SubClass was identified as a JAX-RS root resource, but will be ignored because root resource SubClass implements it.
[DEBUG] [ENUNCIATE] SubClass was identified as a JAX-RS root resource, but will be ignored because root resource SubClass implements it.
[DEBUG] [ENUNCIATE] Added SubClass as a JAX-RS root resource.

**Comment by sakthisunda** [comment]
In the above debug file, I noticed repeated statements. I am not sure if that has any clue.

**Comment by sakthisunda** [comment]
**@Path( "/admin/extension/service" )**
public class **SubClass** extends BaseClass {

    @GET
    @Produces({ "application/xml", "application/json"})
    public JAXBElement<ExtensionServicesType> getExtensionServices(final @Context UriInfo uriInfo) {

   }
}

---------------------------------------------------------------------------------------------------

**@Path( "/admin/extension/" )**
public class AnotherClass {

    @GET 
   **@Path ("/services")**
    @Produces({ "application/xml", "application/json"})
    public JAXBElement<ExtensionServicesType> getAnotherService(final @Context UriInfo uriInfo) {
               return new **SubClass ();**
   }
}

The above code snippets caused the duplicate swagger.json method. I had one direct call and indirect call to same resource path ( /admin/extension/services ). Now I know that why Enunciate generated two times. In case, any enunciate setting can help only one setting, please let me know.  thanks .

For me, this caused swagger.json throwing error when reading from swagger ui ( duplicated keys : two GETs).

**Comment by stoicflame** [comment]
Okay, I'll take a look.

But how does that even work? What method does JAX-RS actually call when a `GET` is invoked on `/admin/extension/services`?

**Comment by sakthisunda** [comment]
JAX-RS chooses the the most specific match possible is used. In this case, the path match at the root level ( I mean Class Level )

@Path( "/admin/extension/services" )
public class **SubClass** extends BaseClass {

    @GET
    @Produces({ "application/xml", "application/json"})
    public JAXBElement<ExtensionServicesType> getExtensionServices(final @Context UriInfo uriInfo) {

   }
}

**Comment by stoicflame** [comment]
Okay, but I'm trying to figure out what Enunciate should do in this case. I guess since the non-class-level path will never actually get invoked, then Enunciate should just ignore it as if it doesn't exist as part of the API?

**Comment by sakthisunda** [comment]
This is only regarding swagger.json picking up all the different routes to same path. So, change at Swagger module is required to skip duplicates either overwriting/ignore if the same path with same method appears again.

Since neither overwriting nor ignore happens, we have invalid swagger.json, which does not even pass a valid Json validator. Some validators does removing the duplicates. But swagger ui or editor does not. thanks

**Comment by sakthisunda** [comment]
I noticed the same duplicates as explained above in openapi.yml generated with enunciate-openapi module.  openapi.yml does not pass swagger editor (swagger.editor.io)

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
