### ISSUE TITLE
Enunciate openapi module support for JAXBElement 

### ISSUE THREAD

**Issue by sakthisunda** [stoicflame/enunciate#888]
Enunciate version 11.x
JAX-RS web api
enunciate-openapi

When I run enunciate on my Java package JAXBElements are not parsed correctly.

Method signature: **public JAXBElement<SelectorExtensionsType>** getSelectorExtensions(

For the above signature, the wrong response model is returned. 
Response Model: String

Screenshot attached ( from Swagger editor )

![jaxbelement support](https://user-images.githubusercontent.com/5530442/43348231-e80cfdc0-91ad-11e8-95e8-7774416e4953.png)

**Comment by stoicflame** [comment]
Please move this issue over to https://github.com/Jyskebank/enunciate-openapi
