### ISSUE TITLE
Support for @resourceGroup javadoc tag

### ISSUE THREAD

**Issue by vguna** [stoicflame/enunciate#889]
Hi.

I like the idea of using the javadoc tags that enunciate provides for documenting. It works for me so far, except for resource grouping. There I still have to use the annotation - since no javadoc counterpart seems to exist. It would be nice having such so I can get rid of the compile dependency.

**Comment by stoicflame** [comment]
Fixed at b71b76ab6. See [docs](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#resourcegroup-javadoc-tag).

**Comment by vguna** [comment]
Thanks again!

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
