### ISSUE TITLE
Kotlin Support

### ISSUE THREAD

**Issue by glockbender** [stoicflame/enunciate#890]
Greetings. Is there any information about Kotlin support?

**Comment by stoicflame** [comment]
What kind of tools are available for parsing/compiling/processing Kotlin source files?

**Comment by MiguelAngelLV** [comment]
Maybe you can use some parsers of Dokka

https://github.com/Kotlin/dokka

**Comment by dsw88** [comment]
How about using Kotlin's annotation processor? https://kotlinlang.org/docs/reference/kapt.html. I have not used it myself, so I'm not much help there.

**Comment by stoicflame** [comment]
This enhancement is currently seeking a sponsor. If anybody is willing to sponsor the work, [reach out to me](http://webcohesion.com/#contact) and I'd be happy to pick it up.
