### ISSUE TITLE
Add support for Gson's SerializedName annotation on enum constants (or more generic approach)

### ISSUE THREAD

**Issue by f24-gklein** [stoicflame/enunciate#896]
For creation of the swagger.json from our jaxrs based rest api we are using the jackson module, although internally we are using Gson for json de/serialization of our api data classes. This works quite fine except that enunciate's jackson module - logically - does not support Gson's SerializedName annotation (we need it for enums). As we can't migrate to jackson and jackson module has some jaxb support (com.webcohesion.enunciate.modules.jackson.model.EnumTypeDefinition) we added @XmlEnumValue wherever @SerializedName is used, which results in some redundancy, e.g.:
```
public enum MarkdownType {
  @SerializedName("asciidoc")
  @XmlEnumValue("asciidoc")
  ASCIIDOC,
  @SerializedName("confluence")
  @XmlEnumValue("confluence")
  CONFLUENCE
}
```
So it would be nice if jackson module supported SerializedName. If that direct dependency is not desirable a generic/pluggable approach would also be OK for us (e.g. like mixins)

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
