### ISSUE TITLE
JaxRs and required request parameters

### ISSUE THREAD

**Issue by f24-gklein** [stoicflame/enunciate#897]
We use enunicate's swagger module to create api documentation for our jaxrs based rest backend. One (minor) issue is that request parameter are always marked as optional/non required although we added @NotNull bean annotations to it, e.g.:
```
@POST
@Produces(APPLICATION_JSON)
@Consumes(APPLICATION_JSON)
public Response someRestEndpoint(@Valid @NotNull SomeRequest request) {
//impl
}
```
As a workaround we use a custom freemarker template, where we set `"required" : true` for all request entities. This however is not perfect, as there might be optional requests. For our api's data classes NotNull annotations are considered correctly and result in required=true. 
So please add support for @NotNull detection on request entities.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
