### ISSUE TITLE
Using enunciate to generate doc of module maven

### ISSUE THREAD

**Issue by nicearma** [stoicflame/enunciate#90]
I'm trying to use enunciate for generate the documentation, but i have one problem, seem like is not getting the code from the module maven.

I getting all the time:
Unable to load type definition for imported API class *****Name class******

But in the pom i have the dependency of the class, i dont know it is possible to this with enunciate?

Or maybe i have to put some other configuration in the pom?

PD: If i put the code in the java folder of the enunciate module maven, work fine.

**Comment by stoicflame** [comment]
Enunciate effectively "recompiles" those classes. It might be failing to load the class because it's missing an upstream dependency or something.

Do you have a way for me to reproduce it?

**Comment by nicearma** [comment]
Is a little hard to reproduce the bug, because is a big project with cdi, jpa and a lots of java library, but i came with one solution, make one profil in the same maven project of the code, and is "working".

I can't deploy the .war because i get some concurrence problem, so i want to ask if it's possible to make configure enunciate for only get the html (without the meta-inf and java stuff)

**Comment by stoicflame** [comment]
See [this document](https://github.com/stoicflame/enunciate/wiki/Documentation-Only) as referenced in the [FAQ](https://github.com/stoicflame/enunciate/wiki/FAQ).
