### ISSUE TITLE
Why does the php-xml-client generate function names based on return type?

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#900]
I'm looking at the generated code for the php-xml-client, and I see that PHP getters and setters are based on the name of the return type, and not based on the names of the XML elements. 

Looking at the below image, I'd expect the function names to be `getAlbum()` and `setAlbum()`.

Is there a way to control this? I've carefully ensured that the API does name XML elements properly, and I would like this apply all the way throughout the clients as well to ensure consistency.

I don't really care what the (private) class variables are named, it's just the function names.

![image](https://user-images.githubusercontent.com/1845372/45158241-b6f4f700-b1e3-11e8-97dd-6e485311a1fb.png)

**Comment by stoicflame** [comment]
So they're actually based on the _Java_ method name; it doesn't have anything to do with the return type or the XML name.

**Comment by sbrattla** [comment]
Ah, I see. That explains it well then. For most people out there, this is probably desired behaviour.

**Comment by sbrattla** [comment]
Crickey! 

@stoicflame - this is indeed possible! I digged into the `PHPXMLClientModule` and it turns out that `Accessor` (super class of `Element`) pulls in the value from `@ClientName` through a delegate in `getClientSimpleName()`.

This is great news! Thanks for implementing that, although you'd forgotten :-)

![image](https://user-images.githubusercontent.com/1845372/45178783-ecff9e80-b216-11e8-8b07-6565537f88ad.png)
