### ISSUE TITLE
@returnWrapped should support "no content" semantics

### ISSUE THREAD

**Issue by f24-gklein** [stoicflame/enunciate#904]
Is there a way to signify via @returnWrapped that a JAX-RS resource method returns 'no content'? I tried different variants:
```
@returnWrapped com.webcohesion.enunciate.metadata.rs.TypeHint$NO_CONTENT
@returnWrapped com.webcohesion.enunciate.metadata.rs.TypeHint.NO_CONTENT
@returnWrapped java.lang.Void
```
but none of them actually worked (we create swagger definition). 
If i resort to `@TypeHint(TypeHint.NO_CONTENT.class)` it works as expected. However we want to rely on javadoc tags as much as possible (consistency, etc.). Is this possible or is it a bug?

**Comment by stoicflame** [comment]
I'll track this as an enhancement request for now.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
