### ISSUE TITLE
Request Body being generated for a @GET endpoint

### ISSUE THREAD

**Issue by greggalbreath** [stoicflame/enunciate#905]
With the following endpoint:

`@GET`
`@Path("authUser")`
`@Produces(MediaType.APPLICATION_JSON)`
`public Response getAuthUser(@Ignore @HeaderParam("X-Authentication-username") String userName) {`
`        User user = UserService.getAuthUser(userName);`
`        return makeCORS(Response.ok(gson.toJson(new PortalResponse("User found", user))));`
`}`

Enunciate generates a "Request Body" section because of the userName argument. It seems that since the HeaderParam is being ignored that userName is assumed to be a JSON body.

Is there any way to tell Enunciate to not generate a "Request Body" section?
Thanks.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
