### ISSUE TITLE
Disable inheritence in generated documentation

### ISSUE THREAD

**Issue by anton-johansson** [stoicflame/enunciate#91]
Hi!

If you have POJO's that extend other POJO's, the documentation will show this inheritence. For example, say we have class A and class B extends A. If you then look at class B, you will only see class B's properties. To see class A's properties you'd have to click the link "Extends: blabla". This might be useful, I guess, but in my opinion, people that use our API does not need to know this. If they look up documentation of a POJO, I want them to see all the properties of that POJO directly.

Any way to add a setting to disable this? I haven't checked the code on this yet, so I'm not sure how much work it might be.

**Comment by stoicflame** [comment]
Yes, things are changing with Enunciate 2.0. This issue will be fixed.

**Comment by anton-johansson** [comment]
Ahh cool. Where can I find information about Enunciate 2.0? For example, changes from 1.x and any planned release date, etc?

**Comment by stoicflame** [comment]
At #68.

**Comment by anton-johansson** [comment]
Yep, it has all the information I need. Thanks a lot!
