### ISSUE TITLE
support for Lombok onX

### ISSUE THREAD

**Issue by ronnyfm** [stoicflame/enunciate#911]
Enunciate 2.11.1
Lombok 1.16.6
JDK: 1.8.0_121
Maven: 3.5.4

I am getting this in the output:

`[ENUNCIATE] [javac] error: cannot find symbol:   method onMethod_()`

Example source code:

```
@Getter(onMethod_=@JsonProperty("Address1"))
    private String address1;
```

Any ideas?

**Comment by stoicflame** [comment]
Is `onMethod` a new Lombok method on that annotation? Do you need to update the Lombok version Enunciate is using?

**Comment by ronnyfm** [comment]
Thanks, @stoicflame. No, the onMethod_ (note the underscore) is a workaround for Java 8, you can read about it here: https://projectlombok.org/features/experimental/onX

Specially note this:

> On javac8 and up, you add an underscore after `onMethod`, `onParam`, or `onConstructor`. 

I do not need to update Lombok version, unless that be required to fix this issue.

**Comment by ronnyfm** [comment]
By the way, what Lombok version Enunciate uses? The version I put above is the one being used in the project.

**Comment by ronnyfm** [comment]
Sorry, just curious about this issue, since the way for Java 8 for onX is using the underscore, I wonder that this haven't been reported before.

**Comment by ronnyfm** [comment]
I used the generated sources in the meantime, instead of the Lombok plugin.

**Comment by stoicflame** [comment]
I've turned this into an enhancement request to support Lombok `onX`

**Comment by stoicflame** [comment]
This enhancement is currently seeking a sponsor. If anybody is willing to sponsor the work, [reach out to me](http://webcohesion.com/#contact) and I'd be happy to pick it up.

**Comment by garethmatthews-cc** [comment]
https://gist.github.com/garethmatthews-cc/abb61395f7ffaff8f9272bc6eecc71f8

`@Getter(onMethod_ = @JsonProperty("Address1"))
  private Person owner;`

Got it working in this jist. 

<img width="988" alt="Screenshot 2020-05-11 at 18 14 21" src="https://user-images.githubusercontent.com/62597813/81590853-6455e000-93b3-11ea-9174-1013f7f1589f.png">
