### ISSUE TITLE
How to get a link to the WSDL within the docs?

### ISSUE THREAD

**Issue by watery** [stoicflame/enunciate#914]
Is there a way to show a link to the WSDL (single or many as there can be) in the docs?
In my Spring Boot application that document is autogenerated, so probably auto&ndash;discovery won't work.

**Comment by stoicflame** [comment]
There _is_ a link, right there in the "Services" section next to the Namespace:

![image](https://user-images.githubusercontent.com/145838/46305978-328e5d80-c570-11e8-9fbf-c8821143a025.png)

**Comment by watery** [comment]
@stoicflame Sight's lowering with age, but non that much yet  :sweat_smile:

![enunciate-docs-home](https://user-images.githubusercontent.com/3211180/46334919-1a791580-c626-11e8-9c80-6fd9e5e79622.png)

I've forgot to add that this is a Spring Boot application and that the WSDL is generated at runtime from several XSD files, maybe that's influencing the documentation generation somehow.

**Comment by watery** [comment]
A-ha! I've started out with `<modules disabledByDefault="true">` and forgot to enable it.

Links are there now; I see they come from the docs folder though: any chance to have them point to the real WSDLs? It would be fine if I have to manually provide the paths of course.

**Comment by stoicflame** [comment]
See the [docs for the IDL module](https://github.com/stoicflame/enunciate/wiki/Module-IDL), `useFile` attribute of the `wsdl` element.
