### ISSUE TITLE
Schema xsd xs:documentation tag support

### ISSUE THREAD

**Issue by watery** [stoicflame/enunciate#915]
If I'm not mistaken, certain information about a type is extracted from the schema, i.e. `min/max occurs`. 

Are `<xs:documentation>` tags processed too? I've tried putting them around my schema, but none seem to arrive to the docs.

This is how I placed one:

```
<xs:element name="customerId" type="xs:string">
    <xs:annotation>
        <xs:documentation>Doc for customerId</xs:documentation>
    </xs:annotation>
```

**Comment by stoicflame** [comment]
Enunciate only works of the Java source files. min/max occurs is derived from the annotations and the data type of the property (whether it's a collection, etc.)
