### ISSUE TITLE
Request for authors of themes to be put in Markdown/Readme

### ISSUE THREAD

**Issue by terrancesnyder** [stoicflame/enunciate#92]
I've spent some time on projects and am open-sourcing themes created for JAX-RS services. Below is the theme for anyone to use (MIT license).

It would be nice to have links to other themes for people to use and inject into their projects...

https://github.com/terrancesnyder/enunciate-bootstrap-theme
![screenshot](https://cloud.githubusercontent.com/assets/379950/8640944/6f113432-28d7-11e5-9b8c-ed0cdc557a47.png)

**Comment by stoicflame** [comment]
Ooo!! I like it.

I might just lift it for Enunciate 2.0.

Either way, we should have a place for people to provide links to their themes. I'll track that work here at this issue.

Thanks!

**Comment by terrancesnyder** [comment]
No problem. We have another for SOAP/XML. The template provided in the git link does REST very well but I'll be adding "required" and "optional" and adding some responsive HTML improvements.

What would be "nice" is the ability to include additional navigation elements to the template, we have multiple WARs that collectively make up one platform. Similar to maven site XML allowing customized navigational elements.

What we were hoping to either (a) ask, or (b) implement and create a pull request allowing people to modify there enunciate.xml to have extra links. (Contact Us, Homepage, Additional Services, etc).

Something like...

<....>
   <nav>
      <link name="Extra Links">
           <link name="Home" href="https://...."/>
           <link name="Comments" href="https://...."/>
           <link name="Help" href="https://...."/>
      </link>
   </nav>
<...>

**Comment by stoicflame** [comment]
Yeah. That sounds like a great feature. Will you open up another issue so we can track that work separately?

BTW, [Enunciate 2 Milestone 1](https://github.com/stoicflame/enunciate/releases/tag/v2.0.0-M.1) was released today. The new generated documentation uses Bootstrap, although it's mostly just the default styles.

**Comment by stoicflame** [comment]
Okay, I finally got around to providing a [directory of custom themes](https://github.com/stoicflame/enunciate/wiki/Custom-Themes). Anyone is invited to edit that page to provide a link to their custom themes.

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)

**Comment by terrancesnyder** [comment]
Hey just cracking this open, plan on working on this while on a long haul flight to Tokyo. My problem is with enunciate 2.x I can't find the "input document" so I can examine the available properties to data bind against, also I can't just simply take my input doc and just debug / run through freemarker. My preferred flow would be [input XML/doc] ---> [freemarker] ---> [html].. Rather than having to have maven compile every couple of seconds.

Hints?
