### ISSUE TITLE
Spring REST annotations not registered on interfaces

### ISSUE THREAD

**Issue by simonDeHero** [stoicflame/enunciate#921]
Hi,
i have a separation of my Spring controllers into interfaces and implementations (The reason for this is to auto-generate a REST client using e.g. Feign), e.g.
```
@ResourceGroup("Foo")
@RequestMapping(FooController.PATH)
public interface FooController {

    String PATH = "foo";

    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
    Foo getFoo();
}

//duplicate annotations needed for correct generation of docu
//@ResourceGroup("Foo")
//@RequestMapping(FooController.PATH)
@RestController
public class FooControllerImpl implements FooController {

    @Override
    public Foo getFoo() {
        return new Foo();
    }
}
```

The problem is now, that without those duplicated annotations in the impl (`@ResourceGroup` and `@RequestMapping`), in the generated docu the controller is under the path `/`, not the expected `/foo`, and in the section "Other", not "Foo".

I have this behaviour with Spring 5 and Spring Boot 2, Java 10.0.2 and enunciate 2.11.1.

thx for having a look!

**Comment by stoicflame** [comment]
Probably just need an enhancement to account for annotations on interfaces. Thanks for the report.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
