### ISSUE TITLE
swagger module configuration

### ISSUE THREAD

**Issue by BrianOHalloran** [stoicflame/enunciate#922]
Can someone point me to an example of the configuration needed to get the swagger module to work?  Any thread I've found here so far has outdated links where pages no longer exist.

I'm using version enunciate 1.31.  My current enunciate.xml has:

_<swagger groupRestResources="publicAPI">
	<facets>
		<exclude name="privateAPI"/>
	</facets>
</swagger>

<docs groupRestResources="publicAPI" docsDir="docs" title="my title" copyright="my copyright" disableRestMountpoint="true">
	<facets>
		<exclude name="privateAPI"/>
	</facets>
</docs>_

Docs are getting produced but no swagger.

Thanks,

Brian

**Comment by BrianOHalloran** [comment]
<swagger groupRestResources="publicAPI">
	<facets>
		<exclude name="privateAPI"/>
	</facets>
</swagger>

<docs groupRestResources="publicAPI" docsDir="docs" title="my title" copyright="my copyright" disableRestMountpoint="true">
	<facets>
		<exclude name="privateAPI"/>
	</facets>
</docs>

**Comment by BrianOHalloran** [comment]
enunciate.xml... replace - with corresponding < or >

-swagger groupRestResources="publicAPI"-
	-facets-
		-exclude name="privateAPI"/-
	-/facets-
-/swagger-

-docs groupRestResources="publicAPI" docsDir="docs" title="my title" copyright="my copyright" disableRestMountpoint="true"-
	-facets-
		-exclude name="privateAPI"/-
	-/facets-
-/docs-

**Comment by stoicflame** [comment]
So Enunciate 1.31 is pretty outdated, as is the swagger UI that it will generate.

Have you considered updated to 2.11.0? I think you'll have a better experience with the tool.

Or do you just want to figure out how to make 1.31 work?

**Comment by BrianOHalloran** [comment]
Hi Ryan,

I was considering upgrading to 2.11.1 but when trying it, I noticed the @Facet now only has properties for value() and documentation() whereas the older one also had name().  The way our endpoint resource files are written, we use both the name and the value for documentation.  The name is used for including or excluding and the value is a kind of section sorting in the HTML.

Can you advise how to get around this, as I'd happily move to 2.11.1.  And if this produced a richer swagger UI, all the better 👍 

Thanks,

Brian

**Comment by stoicflame** [comment]
Can you use [`@ResourceGroup`](https://github.com/stoicflame/enunciate/wiki/Enunciate-Specific-Annotations#cwemrsresourcegroup) for your section sorting?

**Comment by BrianOHalloran** [comment]
Hi Ryan,

I'll look at 2.11.1 and get up to what I have at the moment and then try back with the swagger piece.

Thanks,

Brian

**Comment by stoicflame** [comment]
This issue has been stagnant for awhile. Closing for now, to be re-opened as needed.
