### ISSUE TITLE
Missing PHP JSON Client Library

### ISSUE THREAD

**Issue by amberream** [stoicflame/enunciate#924]
This is in v2.11.1

Steps to see issues:
1. Generate documentation
2. Go to "Files and Libraries" tab in the upper right
3. Click on "PHP JSON Client Library" on left

Problems:
a. When I click on api-php.zip instead of downloading it opens the zip file in the browser as a text file (only tested on Chrome).  In fact, ALL the client library links have this issue.
b. When I open api-php.zip from the file system it actually contains the PHP XML Client Library, not the JSON library.  This is the only php library on the file system, so the JSON library seems to be missing.
c. When I click on "PHP XML Client Library" it links to the same api-php.zip file that has the same issue as in part a.

**Comment by stoicflame** [comment]
Thanks for the report. I'll take a look.

**Comment by amberream** [comment]
The issue with the zip/jar files opening as text in the browser may actually be related to how I am serving the files.  I have already fixed that on my end by setting the content type when I return them from the server. So this may or may not be a general problem.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
