### ISSUE TITLE
How to restrict to store the source codes in generated api documentation?

### ISSUE THREAD

**Issue by KhlaponinIO** [stoicflame/enunciate#925]
Hi Ryan,
I'm working with enunciate-maven-plugin v2.11.1.
Let's assume, that I have a simple POJO class, e.g. Person, and I want it to show in the swagger api. So I marked some fields with next javadoc tags, e.g.
![image](https://user-images.githubusercontent.com/14966979/47663405-9757ca80-dba5-11e8-8970-f7c2c7ed71f6.png)

and got the next result:
![image](https://user-images.githubusercontent.com/14966979/47663316-5fe91e00-dba5-11e8-86dc-8d6cb1f87366.png)
And it is pretty good for me.
But when I look into the generated api doc folder, I found a lot of jar files with the code sources of that POJOs.
![image](https://user-images.githubusercontent.com/14966979/47663536-f0bff980-dba5-11e8-833f-96f8967f4f74.png)

Do I need them to show everything properly on the swagger UI? If not, is there is a way to forbid that source codes jars creation? 

UPD:
Here is my configuration:
```
<plugin>
	<groupId>com.webcohesion.enunciate</groupId>
	<artifactId>enunciate-maven-plugin</artifactId>
	<version>${enunciate-plugin.version}</version>
	<executions>
		<execution>
			<id>generate-service-docs</id>
			<phase>generate-resources</phase>
			<goals>
				<goal>docs</goal>
			</goals>
			<configuration>
				<docsDir>${msp.home}/html</docsDir>
				<configFile>${enunciate.file}</configFile>
			</configuration>
		</execution>
	</executions>
</plugin>
```

Regards,
Igor

**Comment by KhlaponinIO** [comment]
Hi @panchenko , the `enabledByDefault="false"` flag doesn't work, but manual disabling of every module works as expected. So I used the next config, and it solved the problem

```
<modules>
    <jackson1 disabled="true" />
    <gwt-json-overlay disabled="true" />
    <java-json-client disabled="true" />
    <java-xml-client disabled="true" />
    <php-xml-client disabled="true" />
    <php-json-client disabled="true" />
    <c-xml-client disabled="true" />
    <csharp-xml-client disabled="true" />
    <javascript-client disabled="true" />
    <obj-c-xml-client disabled="true" />
    <ruby-json-client disabled="true" />
    <docs enabled="true" />
    <swagger enabled="true" />
    <jaxrs enabled="true"/>
</modules>
```

Thanks for your help!

P.S. I think, we still need to solve the issue with that  `enabledByDefault="false"` flag. Do I need to create a separate issue for it?

**Comment by panchenko** [comment]
@KhlaponinIO sorry, my typo `disabledByDefault` and `disabled`

**Comment by KhlaponinIO** [comment]
Got it. Thank you for quick response!
