### ISSUE TITLE
Exclude files config doesn't work

### ISSUE THREAD

**Issue by darthlynx** [stoicflame/enunciate#927]
First of all, I saw the same issue #658 but seems like its still doesn't work.

Let's assume, I have the next project structure:
![image](https://user-images.githubusercontent.com/14966979/47996376-fe730300-e100-11e8-97f4-c1ec6216dd92.png)

And I want to exclude the Garbage class from my documentation, so that I'm using the next config:
```
<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <title></title>
    <description></description>
    <application root="/msp" />
    <api-classes>
        <include pattern="com.foo.test.testswaggerissue.**" />
        <exclude pattern="com.foo.test.testswaggerissue.client.Garbage" />
    </api-classes>
    <modules disabledByDefault="true">
        <docs disabled="false" />
        <jaxb disabled="false" />
        <jackson disabled="false" />
        <swagger disabled="false" />
        <jaxrs disabled="false">
            <application path="/msp" />
        </jaxrs>
    </modules>
</enunciate>
```
But I still can see it in the documentation:
![image](https://user-images.githubusercontent.com/14966979/47996470-57db3200-e101-11e8-9ee3-b6b050e956c0.png)

Any ideas, what is wrong? Thanks!

**Comment by KhlaponinIO** [comment]
Hello Ryan,

Here is a part of the mvn output with all Garbage instances mentioned in it:
![enunciate_issue](https://user-images.githubusercontent.com/14966979/48055626-b0b9d180-e1b8-11e8-8e02-3a4d5bfef28f.png)

If you need something else, please let me know

Regards,
Ihor

**Comment by stoicflame** [comment]
So the reason it's not getting excluded is because the `api-classes` configuration prioritizes the `include` over the `exclude`. It's not a very sophisticated mechanism.

You'll either need to narrow your `include` configuration or think about using [Facets](https://github.com/stoicflame/enunciate/wiki/Facets) to exclude the class. Here's a diff I applied to [enunciate-sample](https://github.com/stoicflame/enunciate-sample) to verify that the facet mechanism works:

```diff
diff --git a/enunciate.xml b/enunciate.xml
index 070bc89..a102ac1 100644
--- a/enunciate.xml
+++ b/enunciate.xml
@@ -6,6 +6,14 @@
 
   <application root="http://www.ifyouwannabecool.com/api"/>
 
+  <api-classes>
+    <facet name="garbage" pattern="com.ifyouwannabecool.api.client.Garbage"/>
+  </api-classes>
+
+  <facets>
+    <exclude name="garbage"/>
+  </facets>
+
   <namespaces>
     <namespace id="api" uri="http://api.ifyouwannabecool.com/"/>
     <namespace id="link" uri="http://api.ifyouwannabecool.com/link"/>
diff --git a/src/main/java/com/ifyouwannabecool/api/client/Garbage.java b/src/main/java/com/ifyouwannabecool/api/client/Garbage.java
new file mode 100644
index 0000000..a11980c
--- /dev/null
+++ b/src/main/java/com/ifyouwannabecool/api/client/Garbage.java
@@ -0,0 +1,16 @@
+/*
+ * © 2019 by Intellectual Reserve, Inc. All rights reserved.
+ */
+package com.ifyouwannabecool.api.client;
+
+import javax.ws.rs.GET;
+import javax.ws.rs.Path;
+
+@Path("/garbage")
+public class Garbage {
+
+  @GET
+  public String get() {
+    return "";
+  }
+}
```

**Comment by darthlynx** [comment]
Hello @stoicflame!
Thank you for proposed solution. I will try it
