### ISSUE TITLE
PathParam appear as required=false in swagger.json

### ISSUE THREAD

**Issue by StephaneWeber** [stoicflame/enunciate#928]
When we generate the swagger files for our resources, somehow all PathParam annotated parameters end up generated with a required flag set to false, which the swagger editor complains about.

Is this a known bug ?

Example:

`    @GET
    @Path("{bankuseridentification}")
    @Produces("application/vnd.siren+json;charset=UTF-8")
    public Response getInternetBankingUser(@PathParam("bankuseridentification") String bankUserIdentification) {
... }
`

Generates:

`
 "paths": {
    "\/{bankuseridentification}" : {
      "get" : {
        "tags" : [ "InternetBankingUserResource" ],
        "description" : "",
        "operationId" : "getInternetBankingUser",
        "produces" : [ "application/vnd.siren+json;charset=UTF-8" ],
        "parameters" : [
          {
            "name" : "bankuseridentification",
            "in" : "path",
            "required" : false,
            "type" : "string",
            "description" : ""
          }
        ],
        "responses" : {
          "200" : {
            "description" : ""
          }
        }
      }
    }
`

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
