### ISSUE TITLE
Swagger Response Example should be Examples

### ISSUE THREAD

**Issue by andDecarlo** [stoicflame/enunciate#931]
I am using enunciate version 2.11.1 to produce swagger JSON. I have imported it into swagger editor to take a look and immediately ran into several errors, all of them indicating that the response element "should NOT have additional properties". The generated path looks like this:
``` 
/api/data/mapping/definition/target/group:
    get:
      tags:
        - MappingController
      description: ''
      operationId: createTargetMappingGroupDefinition
      produces:
        - application/json
        - application/xml
      parameters: []
      responses:
        '200':
          schema:
            $ref: '#/definitions/json_TargetMappingGroup'
          example:
            ...
          description: ''
```
I believe when an example is part of the responses it should be examples (plural) where as the examples in the definitions sections should be example (singular) as described [here](https://swagger.io/docs/specification/2-0/adding-examples/) in the Whole Schema Examples and Response Examples sections.

**Comment by stoicflame** [comment]
The `example` works for me in the Swagger UI, so it seems correct. You might be validating the `swagger.json` against the new Swagger UI spe?. Enunciate is still generating the old version. See #856.

**Comment by stoicflame** [comment]
Never mind; you were right. It should be `examples`.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
