### ISSUE TITLE
'cannot find symbol' when using Generics and Inheritance

### ISSUE THREAD

**Issue by amoscatelli** [stoicflame/enunciate#933]
A soap WebService inheriting a WebMethod with generics in its signature from an Abstract class with generics makes Enunciate unable to compile.

@WebService
public class AddressSoap extends AbstractModifiableService<Address, AddressDTO, AddressController>

`AddressSoap.java:137: error: cannot find symbol
  java.util.Collection<D> edit(@javax.jws.WebParam( name = "arg0", targetNamespace="", mode = javax.jws.WebParam.Mode.IN , header = false, partName = "arg0" ) java.util.Collection<D> resource) ;
                       ^
  symbol:   class D
  location: interface AddressSoap`

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
