### ISSUE TITLE
Javadoc tags @responseExample, @requestExample output missing in Swagger

### ISSUE THREAD

**Issue by adwylie** [stoicflame/enunciate#934]
This is probably a duplicate of #660. I'm using version `2.11.1` via the Gradle plugin, and have included the `com.webcohesion.enunciate:enunciate-core-annotations:2.11.1` compile group.

I can confirm that output is as expected in the enunciate-generated documentation, however the output from `@requestExample` and `@responseExample` tags are not included in the generated Swagger documentation. Is this an actual bug, or something that doesn't fit into how/what data Swagger should be displaying?

The Jersey/JAX-RS annotated methods using `@responseExample` are returning a `Response` object consisting of a custom-built JSON String object (eg. `return Response.ok("{...}").build();`). I'm using a `@TypeHint(Object.class)`, though not sure if this has an effect either way.

There's also some other missing/inconsistent information in the Swagger documentation, namely 'Response Body' data type and description. This data is shown correctly in the enunciate-generated documentation, however the Swagger documentation simply shows something like `Response Class (Status 200) file`. My apologies if this should be submitted as a separate issue.

Let me know if you require any additional information. I can't really copy/paste code as it's proprietary, though could write up something that conveys the overall configuration.

Thanks!

**Comment by stoicflame** [comment]
Thanks for the report. I'll take a closer look.

**Comment by stoicflame** [comment]
I fixed the `@responseExample` problem at b7247635c.

As far as I know, there's no way for Swagger to provide a custom request example. If you can point out a way to do it in Swagger 2, I'd be happy to implement the new feature.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
