### ISSUE TITLE
Null value when getting default visbility in Jackson Module

### ISSUE THREAD

**Issue by kristofdepypere** [stoicflame/enunciate#935]
Hi,

I have problems when enabling the jackson module.

Line 24 in com.webcohesion.enunciate.modules.jackson.model.AccessorVisibilityChecker
`public static final JsonAutoDetect DEFAULT_VISIBILITY = VisibilityChecker.Std.class.getAnnotation(JsonAutoDetect.class);`

Always resolves to null causing a stacktrace. 

`Caused by: java.lang.NullPointerException
        at com.webcohesion.enunciate.modules.jackson.model.AccessorVisibilityChecker.<init>(AccessorVisibilityChecker.java:32)
        at com.webcohesion.enunciate.modules.jackson.model.AccessorVisibilityChecker.<clinit>(AccessorVisibilityChecker.java:25)
        ... 148 more`

All classes are present (which was the first issue I needed to solve by putting them explicitly on the classpath or by trying to use the enunciate configuration at this point).

What is wrong here ?

using gradle plugin and enunciate version 2.11.1

**Comment by panchenko** [comment]
In jackson 2.9 there is no `@JsonAutoDetect` annotation on `VisibilityChecker.Std`, so current version works only with 2.8

**Comment by kristofdepypere** [comment]
Ok, then that is the problem... We use 2.9.7 and had to bump it for security reasons..

Would it make sense to use 2.8.x version of jackson by using the enunciate configuration in gradle ? Is this a good option ? Or do we simply wait until 2.9.x is supported by enunciate ?

**Comment by panchenko** [comment]
The support for 2.9 has been added in #865, so can either build enunciate from sources or wait for the next release.

**Comment by kristofdepypere** [comment]
ok thx
