### ISSUE TITLE
Disabling documentation on Production

### ISSUE THREAD

**Issue by brienze** [stoicflame/enunciate#936]
Hello,

I am trying to find information about how to disable documentation programmatically. 
The context would be to build the WAR package with the documentation and for some reason disable it on the fly (in runtime).
Is that possible ?
Thanks.

**Comment by panchenko** [comment]
It depends on how you make it exposed to the outside world. 
If files are placed under document root then you can implement a servlet filter.
If files are are placed on classpath, then they exposed programmatically in some way, e.g. via the {{addResourceHandler()}} call in Spring Framework. In this case don't expose them conditionally.

**Comment by stoicflame** [comment]
Yes, this issue is outside the scope of Enunciate.

Enunciate generates the docs. It's up to you (and your framework/environment/container of choice) to figure out how to display it.
