### ISSUE TITLE
Enunciate with lombok

### ISSUE THREAD

**Issue by joaquim1995** [stoicflame/enunciate#937]
Hi,

I'am trying to generate swagger with enunciate 2.11.1, and also use lombok and i don't have any problem, in a multi module project.

My problem is, when i deploy i' am oppening the swagger UI  on http://localhost:8080/osit-ecom-webservices/apidocs/ui/index.html
and file simply is not found.

I must be doing something very wrong, and probably is nothing about enunciate plugin, can you help me understand what is it ?

My webservices pom.xml

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>com.app</groupId>
        <artifactId>app-ecom</artifactId>
	<version>1.153.0-SNAPSHOT</version>
    </parent>
    <artifactId>app-ecom-webservices</artifactId>
    <packaging>war</packaging>
    <name>app-ecom-webservices</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <timestamp>${maven.build.timestamp}</timestamp>
        <maven.build.timestamp.format>yyyy-MM-dd HH:mm:ss</maven.build.timestamp.format>
    </properties>

    <dependencies>
        

        
        <dependency>
            <groupId>com.app</groupId>
            <artifactId>app-base-common</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.app</groupId>
            <artifactId>app-base-webservices-impl</artifactId>
        </dependency>
        

        
        <dependency>
            <groupId>com.app</groupId>
            <artifactId>app-ecom-business-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.app</groupId>
            <artifactId>app-ecom-client-api</artifactId>
        </dependency>

    </dependencies>

    <profiles>
        <profile>
            <id>default</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>

            <build>
                <plugins>

                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-war-plugin</artifactId>
                        <configuration>
                            <archive>
                                <manifestEntries>
                                    <Logging-Profile>APP_Ecom</Logging-Profile>
                                    <project-name>${project.name}</project-name>
                                    <project-version>${project.version}</project-version>
                                    <compiler-jdk-version>${jdk.version}</compiler-jdk-version>
                                    <build-timestamp>${timestamp}</build-timestamp>
                                </manifestEntries>
                            </archive>

                        </configuration>
                    </plugin>

                    <plugin>
                        <groupId>com.webcohesion.enunciate</groupId>
                        <artifactId>enunciate-maven-plugin</artifactId>
                        <version>${enunciate.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>docs</goal>
                                </goals>
                                <configuration>
                                    <sourcepath-includes>
                                        <sourcepath-include>
                                            <groupId>com.app</groupId>
                                            <artifactId>app-ecom-webservices</artifactId>
                                        </sourcepath-include>

                                        <sourcepath-include>
                                            <groupId>com.app</groupId>
                                            <artifactId>app-ecom-client-api</artifactId>
                                        </sourcepath-include>

                                        <sourcepath-include>
                                            <groupId>com.app</groupId>
                                            <artifactId>app-ecom-common-api</artifactId>
                                        </sourcepath-include>
                                    </sourcepath-includes>

                                    <sourcepath-excludes>
                                        <sourcepath-exclude>
                                            <groupId>com.app</groupId>
                                            <artifactId>app-ecom-data</artifactId>
                                        </sourcepath-exclude>

                                        <sourcepath-exclude>
                                            <groupId>com.app</groupId>
                                            <artifactId>app-ecom-business-api</artifactId>
                                        </sourcepath-exclude>

                                        <sourcepath-exclude>
                                            <groupId>com.app</groupId>
                                            <artifactId>app-ecom-business</artifactId>
                                        </sourcepath-exclude>

                                        <sourcepath-exclude>
                                            <groupId>com.app</groupId>
                                            <artifactId>app-ecom-app-ecom-integration</artifactId>
                                        </sourcepath-exclude>
                                    </sourcepath-excludes>
                                    <docsDir>${project.build.directory}/docs</docsDir>
                                </configuration>
                            </execution>
                        </executions>
                        <dependencies>
                            <dependency>
                                <groupId>com.webcohesion.enunciate</groupId>
                                <artifactId>enunciate-lombok</artifactId>
                                <version>${enunciate.version}</version>
                            </dependency>
                        </dependencies>
                    </plugin>

                </plugins>
            </build>
        </profile>
        <profile>
            <id>disable-enunciate-docs-swagger-api</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-war-plugin</artifactId>
                        <configuration>
                            <archive>
                                <manifestEntries>
                                    <Logging-Profile>APP_Ecom</Logging-Profile>
                                    <project-name>${project.name}</project-name>
                                    <project-version>${project.version}</project-version>
                                    <compiler-jdk-version>${jdk.version}</compiler-jdk-version>
                                    <build-timestamp>${timestamp}</build-timestamp>
                                </manifestEntries>
                            </archive>
                        </configuration>
                    </plugin>

                </plugins>
            </build>
        </profile>
    </profiles>

</project>

My enunciate.xml

<enunciate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.11.0.xsd">

    <api-classes>

        <exclude pattern="org.jboss.**"/>
        <exclude pattern="com.app.**"/>

        <include pattern="com.app.ecom.webservices.**"/>
        <include pattern="com.app.ecom.entities.**"/>
    </api-classes>

    <modules>
        <swagger basePath="/${project.name}/rest" />

        <disable-rule id="csharp.warnings"/>
        <disable-rule id="c-warnings"/>
        <disable-rule id="obj-c.warnings"/>

        
        <jaxrs disabled="false" groupBy="annotation"/>
        <jackson disabled="false" collapse-type-hierarchy="true" />
        <jaxb disabled="true"/>
        <jackson1 disabled="true" collapse-type-hierarchy="true"/>
        <jaxws disabled="true"/>
        <spring-web disabled="true"/>
        

        
        <docs disabled="false"/>
        <swagger disabled="false"/>
        <c-xml-client disabled="true"/>
        <csharp-xml-client disabled="true"/>
        <java-xml-client disabled="true"/>
        <java-json-client disabled="true"/>
        <javascript-client disabled="true"/>
        <gwt-json-overlay disabled="true"/>
        <obj-c-xml-client disabled="true"/>
        <php-xml-client disabled="true"/>
        <php-json-client disabled="true"/>
        <ruby-json-client disabled="true"/>
        <idl disabled="true"/>
    </modules>
</enunciate>

**Comment by stoicflame** [comment]
Does the file `ui/index.html` get generated?

**Comment by joaquim1995** [comment]
Yes, is generated, resources and json files are also generated.

```
docs
└───apidocs
    ├───css
    └───ui
        ├───css
        ├───fonts
        ├───images
        ├───lang
        └───lib
```

**Comment by panchenko** [comment]
The next step should be checking if these generated files are included into the artifacts being deployed.

**Comment by stoicflame** [comment]
Right.

I'm happy to help as needed, but the issue seems to be outside the scope of this project. If the docs are getting generated, then Enunciate seems to be doing it's job. How to get those docs to show up in your app depends on your framework, container and environment and isn't the concern of this project.
