### ISSUE TITLE
"error: cannot access org.codehaus.jackson.annotate.JsonValue" when using Jackson 2

### ISSUE THREAD

**Issue by epabst** [stoicflame/enunciate#938]
When running the enunciate plugin, I got this strange error.  It goes away if I disable the jackson, jaxb, and jaxws modules.  I already had jackson1 disabled.  I believe it's related to some of the classes having Jackson 1 annotations on them, but with an optional dependency that is not on the classpath.

[WARNING] [ENUNCIATE] [javac] error: cannot access org.codehaus.jackson.annotate.JsonValue
[WARNING] [ENUNCIATE] [javac]   class file for org.codehaus.jackson.annotate.JsonValue not found
[WARNING] [ENUNCIATE] [javac]   Consult the following stack trace for details.
[WARNING] [ENUNCIATE] [javac]   com.sun.tools.javac.code.Symbol$CompletionFailure: class file for org.codehaus.jackson.annotate.JsonValue not found
[WARNING] [ENUNCIATE] [javac]   Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: com.webcohesion.enunciate.EnunciateContext.class
[WARNING] [ENUNCIATE] [javac]           at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:109)
[WARNING] [ENUNCIATE] [javac]           at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:192)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorDoOnEach$1.onNext(OperatorDoOnEach.java:82)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.util.ScalarSynchronousObservable$ScalarAsyncProducer.call(ScalarSynchronousObservable.java:192)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.util.ScalarSynchronousObservable$3$1.call(ScalarSynchronousObservable.java:120)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.schedulers.ImmediateScheduler$InnerImmediateScheduler.schedule(ImmediateScheduler.java:57)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:116)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.util.ScalarSynchronousObservable$3.call(ScalarSynchronousObservable.java:112)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.util.ScalarSynchronousObservable$ScalarAsyncProducer.request(ScalarSynchronousObservable.java:180)
[WARNING] [ENUNCIATE] [javac]           at rx.Subscriber.setProducer(Subscriber.java:209)
[WARNING] [ENUNCIATE] [javac]           at rx.Subscriber.setProducer(Subscriber.java:205)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.util.ScalarSynchronousObservable$ScalarAsyncOnSubscribe.call(ScalarSynchronousObservable.java:151)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.util.ScalarSynchronousObservable$ScalarAsyncOnSubscribe.call(ScalarSynchronousObservable.java:140)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[WARNING] [ENUNCIATE] [javac]           at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[WARNING] [ENUNCIATE] [javac]           at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[WARNING] [ENUNCIATE] [javac]           at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[WARNING] [ENUNCIATE] [javac]           at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[WARNING] [ENUNCIATE] [javac]           at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[WARNING] [ENUNCIATE] [javac]           at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[WARNING] [ENUNCIATE] [javac]           at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.fastPath(OnSubscribeFromArray.java:76)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray$FromArrayProducer.request(OnSubscribeFromArray.java:58)
[WARNING] [ENUNCIATE] [javac]           at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:32)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromArray.call(OnSubscribeFromArray.java:24)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CacheState.connect(CachedObservable.java:183)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.CachedObservable$CachedSubscribe.call(CachedObservable.java:230)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.unsafeSubscribe(Observable.java:8460)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:248)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:145)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.fastpath(OnSubscribeFromIterable.java:172)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromIterable$IterableProducer.request(OnSubscribeFromIterable.java:85)
[WARNING] [ENUNCIATE] [javac]           at rx.Subscriber.setProducer(Subscriber.java:211)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:62)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeFromIterable.call(OnSubscribeFromIterable.java:33)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:50)
[WARNING] [ENUNCIATE] [javac]           at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.subscribe(Observable.java:8553)
[WARNING] [ENUNCIATE] [javac]           at rx.Observable.subscribe(Observable.java:8520)
[WARNING] [ENUNCIATE] [javac]           at rx.observables.BlockingObservable.blockForSingle(BlockingObservable.java:433)
[WARNING] [ENUNCIATE] [javac]           at rx.observables.BlockingObservable.single(BlockingObservable.java:332)
[WARNING] [ENUNCIATE] [javac]           at com.webcohesion.enunciate.EnunciateAnnotationProcessor.process(EnunciateAnnotationProcessor.java:123)
[WARNING] [ENUNCIATE] [javac]           at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
[WARNING] [ENUNCIATE] [javac]           at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
[WARNING] [ENUNCIATE] [javac]           at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
[WARNING] [ENUNCIATE] [javac]           at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
[WARNING] [ENUNCIATE] [javac]           at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
[WARNING] [ENUNCIATE] [javac]           at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
[WARNING] [ENUNCIATE] [javac]           at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
[WARNING] [ENUNCIATE] [javac]           at com.sun.tools.javac.main.Main.compile(Main.java:523)
[WARNING] [ENUNCIATE] [javac]           at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[WARNING] [ENUNCIATE] [javac]           at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[WARNING] [ENUNCIATE] [javac]           at com.webcohesion.enunciate.Enunciate.run(Enunciate.java:674)
[WARNING] [ENUNCIATE] [javac]           at com.webcohesion.enunciate.mojo.ConfigMojo.execute(ConfigMojo.java:436)
[WARNING] [ENUNCIATE] [javac]           at com.webcohesion.enunciate.mojo.AssembleBaseMojo.execute(AssembleBaseMojo.java:102)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
[WARNING] [ENUNCIATE] [javac]           at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
[WARNING] [ENUNCIATE] [javac]           at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[WARNING] [ENUNCIATE] [javac]           at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[WARNING] [ENUNCIATE] [javac]           at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[WARNING] [ENUNCIATE] [javac]           at java.lang.reflect.Method.invoke(Method.java:498)
[WARNING] [ENUNCIATE] [javac]           at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[WARNING] [ENUNCIATE] [javac]           at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[WARNING] [ENUNCIATE] [javac]           at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[WARNING] [ENUNCIATE] [javac]           at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------

**Comment by stoicflame** [comment]
My best guess is that there's some class being detected by Enunciate that depends on Jackson 1. That class needs to be excluded or Jackson 1 needs to be added to the classpath.

**Comment by epabst** [comment]
The JVM ignores annotations that are not on the classpath, why not have enunciate follow suit?

**Comment by stoicflame** [comment]
Note that it's not Enunciate that's failing; it's the `javac` compiler that Enunciate uses. The point of failure is outside the hands of Enunciate. If there's some option that can be passed to avoid the crash, I don't know about it. I can look again, though.

**Comment by epabst** [comment]
With your help, and looking, I have a work-around which is to pin gedcomx to 2.3.0 which is before I re-added Jackson 1 annotations to it.

**Comment by stoicflame** [comment]
I believe this issue has been fixed at 37f51ff. I'm happy to reopen if it resurfaces.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
