### ISSUE TITLE
@XmlTransient not working

### ISSUE THREAD

**Issue by nicearma** [stoicflame/enunciate#94]
Hello, i have a lots of @XmlId in variables Short, Integer, etc. The problem is when i try to compile the code, i get  "An xml id must be a string". So i tried the https://github.com/stoicflame/enunciate/wiki/Excluding-Classes, but the @org.codehaus.enunciate.XmlTransient seem not work, but if i put @javax.xml.bind.annotation.XmlTransient work fine.

Is possible to disable the verification of An xml id must be a string?

**Comment by nicearma** [comment]
Ex: 

import nicearma.PeDTO;

import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlTransient;

@XmlTransient
public class urDTO implements PeDTO{

    @XmlID
    private Short idr;
    private String lib;

    public Short getId() {
        return id;
    }

    public void setId(Short id) {
        this.id= id;
    }

    public String getLib() {
        return lib;
    }

    public void setLib(String lib) {
        this.lib = lib;
    }


}

**Comment by stoicflame** [comment]
Thanks for the report. The validation message is invalid. This is fixed at 74e313c.

**Comment by stoicflame** [comment]
Has been fixed in 2.0.0.
