### ISSUE TITLE
@label not honored, when no endpoint is existing

### ISSUE THREAD

**Issue by simonDeHero** [stoicflame/enunciate#940]
Hi,
i want to only create documentation for some models/DTOs, but i don't have a REST endpoint. When i annotate those models with `@Label(...)` or javadoc `@label`, enunciate-maven-plugin tells me, that no resources to document are found. Only when i annotate my models with `@JsonRootName`, the docu generation works and includes these models.

So my issue is, that i would expect, that docu generation in that case also works, when i use on of enunciates label annotations.

I use enunciate-slim-maven-plugin 2.11.1 and OpenJdk 10.

Thx again for having a look!
bye
Simon

**Comment by stoicflame** [comment]
Finally getting around to this issue. I'm afraid using `@Label` to identify JSON data types isn't going to work because that annotation is too generic. It's used to also label root resources, XML types, service endpoints, etc.

**Comment by simonDeHero** [comment]
ok, thx anyway for looking into it @stoicflame !
