### ISSUE TITLE
XmlAttribute constraints are not documented

### ISSUE THREAD

**Issue by samion** [stoicflame/enunciate#945]
The following bean validation annotations are not correctly handled in generated documentation:

`
@XmlAttribute(required = true) 
@Size(min = 5, max = 10) 
private String name;
`

After looking at the code, it seems that those would only work for `@XmlElement`, but not for `@XmlAttribute`.

Similar comments found here:
[xml schema support for bean validation annotations #540](https://github.com/stoicflame/enunciate/issues/540#issuecomment-344202466)

**Comment by samion** [comment]
Here is a pull request of a commit that tries to fix the issue: https://github.com/stoicflame/enunciate/pull/946.

**Comment by stoicflame** [comment]
Fixed at 73d1028.
