### ISSUE TITLE
Unable to parse @requestExample/@responseExample

### ISSUE THREAD

**Issue by Umaaz** [stoicflame/enunciate#947]
I have a few projects that use enunciate, one of these builds is reporting:
```
[WARNING] [ENUNCIATE] Unable to parse @responseExample tag at null: Unrecognized token 'classpath': was expecting ('true', 'false' or 'null')
 at [Source: java.io.StringReader@306465c8; line: 1, column: 10]
[WARNING] [ENUNCIATE] Unable to parse @requestExample tag at null: Unrecognized token 'classpath': was expecting ('true', 'false' or 'null')
 at [Source: java.io.StringReader@227c178e; line: 1, column: 10]
```

There does not seem to be any information about what is causing this issue. As far as i can see the usage of the tag is correct in this project, and is the same in the other projects.

We are using:
```
<enunciate.version>2.11.1</enunciate.version>
```

Any help would be appreciated.

**Comment by Umaaz** [comment]
We have found the problem, seems a '/' was missing on one of the usages.

Is it possible to improve the log message here?

**Comment by stoicflame** [comment]
Sure, I'll track that work here with this issue.
