### ISSUE TITLE
A java source file generated by enunciate 2.11.1 got an error during Jacoco 0.8.3 compile

### ISSUE THREAD

**Issue by sksmith5788** [stoicflame/enunciate#948]
We recently updated the Enunciate and Jacoco versions on a number of projects. One project failed rebuild during the jacoco part of the build, in an enunciate file.

ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project std-ws-name-seg-acceptance: Compilation failure: Compilation failure:
[ERROR] /builds/workspace/std-ws-name-seg-build-248/checkout/seg-acceptance/src/main/java/org/familysearch/standards/name/segmentation/acceptance/legacyTests.java:[170,46] cannot find symbol
[ERROR] symbol:   method getFullName()
[ERROR] location: class org.familysearch.standards.name.segmentation.ws.model.NameModel

I know you will need more information, but I thought you ought to know, in case someone else had already reported it. We had to fall back to Enunciate 2.5.0 before the Jacoco compile worked.

**Comment by stoicflame** [comment]
Is there a different method that it got renamed to?

**Comment by sksmith5788** [comment]
Good question. I will try to duplicate it again and take a look.

**Comment by daveyse** [comment]
I was able to duplicate the problem when attempting to debug the acceptance tests on my local machine (in IntelliJ). I quickly discovered *why* it failed:
When the Enunciated-generated client builds the models, the camel-casing changed for one of the fields and its beans.

In my NameModel class, I have a `private String fullName`, with getter `getFullName()`. 
In the generated class for Enunciate, the field is `_fullname` with getter `getFullname()`.

So, in the acceptance tests that use the Enunciate-generated JSON client, the call to `NameModel.getFullName()` is not found. I can change the acceptance tests to call `NameModel.getFullname()` and it works.

Versions:
Enunciate 2.11.1
