### ISSUE TITLE
Cannot generate SOAP 1.2 WSDL with Enunciate

### ISSUE THREAD

**Issue by michaeljmcd** [stoicflame/enunciate#95]
When using the Enunciate Maven plugin 1.2, I cannot seem to get a SOAP 1.2 WSDL generated. My brief perusal of some of Enunciate's classes would seem to suggest that SOAP 1.2 is supported, but I always get a SOAP 1.1 WSDL in my final project.

I added a `@BindingType(value=javax.xml.ws.soap.SOAPBinding.SOAP12HTTP_BINDING)`
annotation to my implementation and interface classes alike, but it does not appear to be respected. Is there something else I need to be doing to switch to a SOAP 1.2 WSDL and binding?

**Comment by michaeljmcd** [comment]
I have been doing a little more digging and I see that the WSDL is generated through the `wsdl.fmt` and that it has the SOAP 1.1 namespaces and such hard-coded and that it doesn't account for the annotation or invoke CXF.

Obviously, I can invoke CXF to generate SOAP 1.2 WSDLs and can use Enunciate to re-use this through the `useFile` attribute on the `wsdl` element. Is there any way to include this WSDL file in the Enunciate client jar? Without it, the proxy generation seems to fail.

**Comment by stoicflame** [comment]
Thanks for the report. We'll get this fixed, tracking here.

From what I can tell, the WSDL for the SOAP 1.2 binding looks just like the WSDL for the SOAP 1.1 binding, exception the namespace is "http://schemas.xmlsoap.org/wsdl/soap12/" instead of "http://schemas.xmlsoap.org/wsdl/soap/". Does that sound right to you?

**Comment by michaeljmcd** [comment]
That is all I know of offhand, but I do not profess any deep knowledge. I have usually let automated tools handle that ;)

**Comment by stoicflame** [comment]
Assigning this work to version 2.1.0.

**Comment by stoicflame** [comment]
Fixed at a922899. Will be included in 2.1.

**Comment by stoicflame** [comment]
[Enunciate 2.1 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.1.0)

**Comment by tekknow** [comment]
I'm trying to convert an old web service from soap1.1 to 1.2.  I used maven-enunciate-plugin-1.25.jar and org.codehaus.enunciate.enunciate-rt.jar.  Which of the 44 jars I see in the new Enunciate-2.1.0.zip do I replace these with?

**Comment by stoicflame** [comment]
`maven-enunciate-plugin` is now `enunciate-maven-plugin`. `enunciate-rt` isn't needed anymore; Enunciate got out of the runtime business, although it still provides some optional runtime utilities.

See the [Migration Guide](https://github.com/stoicflame/enunciate/wiki/Migration-Guide).

**Comment by tekknow** [comment]
I don't see enunciate-maven-plugin among the jars in enunciate-2.1.0.zip.  Is it located somewhere else?

**Comment by stoicflame** [comment]
It's in the central Maven repo... why do you need it in the zip bundle? If you're using Maven, it will be downloaded automatically.
