### ISSUE TITLE
Viewing API generated by examples

### ISSUE THREAD

**Issue by git-cambridge** [stoicflame/enunciate#950]
Sorry, this is a very newbie question.
I am trying to view the API generated by the examples in enunciate-master/examples/jboss. I have built the project, and I cd to that directory and  do a mvn cargo:run .

How do I navigate to the page which has the API documentation? I tried 
http://localhost:8080/enunciate-examples-jboss-full, but that gave me a 404 NOT found error.
(I got enunciate-examples-jboss-full, from the pom file)

I made it work for the spring-petclinic

**Comment by stoicflame** [comment]
http://localhost:8080/full/index.html

It's the same for all the examples.

**Comment by git-cambridge** [comment]
Thank you so much for the prompt response ! If I ran cargo in the jboss directory, http://localhost:8080/full/index.html worked. But for the spring-petclinic directory, I had to use http://localhost:8080/enunciate-examples-spring-petclinic.

At any rate, PersonService - it looks like it has SOAP methods, but they actually also have a path? So it ends up looking like REST? I was confused - I am trying to view the API documentation for a SOAP method, where should I look please?

**Comment by git-cambridge** [comment]
So it looks like the methods are annotated in the source code with @POST, @PUT etc. That is why it shows up in swagger? I have simple SOAP methods which are just annotated by @WebMethod - they do not have @GET, or path parameters. I guess those will probably not show in the Swagger type UI?

**Comment by stoicflame** [comment]
Correct. Swagger is only an HTTP/REST API tool. Not SOAP.
