### ISSUE TITLE
apiaryio - freemarker

### ISSUE THREAD

**Issue by terrancesnyder** [stoicflame/enunciate#952]
Hi all, I'm going to be making a REST only apairy freemarker template. This ticket is for me to track. Anybody have suggestions after its complete where I can put it?

**Comment by stoicflame** [comment]
If you want to put together a separate module, I'd be happy to review and merge a pull request.

Or, if you'd rather keep control of the project, you can just create your own GH project like [this one over here](https://github.com/Jyskebank/enunciate-openapi).

**Comment by terrancesnyder** [comment]
I got a rough cut here https://gist.github.com/terrancesnyder/b5e564a8cf4a5f9afb75038f1f3a2034

It generated this docs

https://catalinahubapi.docs.apiary.io/

**Comment by stoicflame** [comment]
Super cool.

I'll re-open this issue to track the work to integrate it into main.

**Comment by terrancesnyder** [comment]
I got a couple of other things I want to verify, I'd like to add:

- polymorphic support
- array[x] support

I'll be using...

https://github.com/apiaryio/mson#example-1

**Comment by terrancesnyder** [comment]
Other things that would make apiary nicer:

- ability to define general project/api description in enunicate.xml
- ability to define URLs for sqa, uat, production in enunicate.xml so that we can include them in apiary

**Comment by terrancesnyder** [comment]
Still working on this when time allows, I'll update as I move forward.

**Comment by terrancesnyder** [comment]
Ive updated, and fixed some issues. Basically this is cut #1. The main issue I have, of course, is something with API Blueprint for nested polymorphic types. I find more complex APIs documentation could be better.

https://gist.github.com/terrancesnyder/b5e564a8cf4a5f9afb75038f1f3a2034

That being said, for some, this might prove useful.

**Comment by terrancesnyder** [comment]
Note also including a new template design.

![image](https://user-images.githubusercontent.com/379950/57141159-9160d180-6df4-11e9-978a-454678294d7d.png)

**Comment by stoicflame** [comment]
Thanks again for your work. I've added this thread and the template to the [Community Extensions](https://github.com/stoicflame/enunciate/wiki/Community-Extensions) page.
