### ISSUE TITLE
Does Enunciate support Swagger annotations

### ISSUE THREAD

**Issue by yaminidhamija** [stoicflame/enunciate#953]
Problem detail

https://stackoverflow.com/questions/55832967/swagger-annotations-with-enunciate

**Comment by stoicflame** [comment]
See #433.

**Comment by yaminidhamija** [comment]
But as you mentioned in 433 that partial support has been added for few annotations, I tried those and it is not working as well. Is there any specific thing we need to take care of apart from configurations I mentioned in problem statement.

**Comment by stoicflame** [comment]
Please share what your endpoints look like and how they're annotated.

**Comment by yaminidhamija** [comment]
@POST
    @Path("/placeorder")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(
        value = "Place Order",
        notes = "Places an order.",
        response = PlaceOrder.class
    )
    @ApiResponses({
        @ApiResponse(code = 200, message = "Successful Place Order Response", response = PlaceOrder.class),
        @ApiResponse(code = 401, message = "Unauthorized")
    })
    @ApiImplicitParams({
        @ApiImplicitParam(name = "loginTicket", value = "login ticket", required = false, dataType = "string", paramType = "header"),
        @ApiImplicitParam(name = "async", value = "Flag to check for async call", required = true, dataType = "long", paramType = "query")
    })
    PlaceOrder placeOrder(
            @HeaderParam(TICKET) String loginTicket,
            @QueryParam("async") boolean async,
            Order order);

ApiResponse worked for me but ApiOperation and ApiImplicitParams are not working.

**Comment by stoicflame** [comment]
I'll reopen and treat this as a bug report.

**Comment by stoicflame** [comment]
At 01e07f3 I added support for the `value()` and `notes()` values of `@ApiOperation`.

The `@ApiImplicitParam` annotation only applies to parameters that are *not* defined in the method signature, according to the definition of the annotation, so that's working as designed.

There could be more room to add some additional support for these annotations. If desired, please open a separate issue with details about what support is specifically needed.

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
