### ISSUE TITLE
application.wadl not generated

### ISSUE THREAD

**Issue by irbian** [stoicflame/enunciate#958]
Hi!

Maybe I´m missunderstanding something but... my problem is that enunciate doesn´t generate a WADL file. It generates a Swagger properly, and using external tools, I can convert it to WADL, so, why I can´t generate it directly with enunciate?

**Comment by stoicflame** [comment]
Enunciate configuration?

Any hints in the build output (disabled modules, etc.)?

**Comment by stoicflame** [comment]
No response; closing for now. I'm happy to re-open if you'd like to provide additional details.
