### ISSUE TITLE
Is there a way to export / generate documentation only for certain resources and/or methods?

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#962]
Is enunciate capable of generating documentation only for certain resources and/or methods, by filtering on e.g. a tag, via Maven profile or the like? 

The ultimate goal would be to build a "reduced" / "limited" version of the documentation (for instance : internal vs. external documentation)

**Comment by stoicflame** [comment]
See [Facets](https://github.com/stoicflame/enunciate/wiki/Facets).
