### ISSUE TITLE
Support for @DocumentationExample on lists(or array)

### ISSUE THREAD

**Issue by iorlas1** [stoicflame/enunciate#966]
In general the functionality that example entries for arrays is automatically generated is great, but I have a class where the arrays represents different type of changes that will be applied. By definition these cannot contain the same entries (one list are additions that will be made, another deletions). I would like to override the json example of the list with specific data. I tried to do this with @DocumentationExample but it was ignored. Is there some other way that I have missed? Otherwise I suggest that for a property of type List or array if @DocumentationExample is present it overrides the default example generation. This means that it falls on the user of library to correctly form the output. I suspect that when the library is used to create different types of output this might be problematic. We use the library to create documentation for our rest api which produces json, so for us that isn't an issue.

**Comment by stoicflame** [comment]
Is the difference based on the request being made? Have you seen the `@requestExample` JavaDoc tag?

**Comment by iorlas1** [comment]
No have not. Will check it out, perhaps it does what I want.

**Comment by iorlas1** [comment]
@responseExample could be used  (We use 2.9.0 - probably why I missed this), but not ideal for my use-case. This would move the documentation away from the data carrying object to the service. I love that the examples are generate automatically from the code and thus the risk of them being outdated is very slim, which I guess would not be the case with @responseExample.

**Comment by stoicflame** [comment]
So maybe I'm not understanding your use case. My best understanding is that you've got some object like this:

```java
public class MyAction {
  public Action[] actions;
}
```

Sometimes those "actions" are additions and sometimes they're deletions. You want the generated documentation so sometimes show the additions and sometimes show the deletions.

What kind of annotation or enhancement are you proposing?

**Comment by stoicflame** [comment]
No response. I'm going to close this for now. I'm happy to re-open if additional clarification is provided.
