### ISSUE TITLE
Support for generics in @returnWrapped, @inputWrapped, etc.

### ISSUE THREAD

**Issue by lordkada** [stoicflame/enunciate#968]
Dealing with generics, I am struggling with the @returnWrapped annotation and how to use it.

For example, I have a class like this:
```

public class PaginatedResponse<T> {

    List<T> results;

    public List<T> getResults() {
        return results;
    }

    public PaginatedResponse<T> setResults(List<T> results) {
        this.results = results;
        return this;
    }

}
```

If I use it like here below, it works (I get a PaginatedResponseOfPersonas):

```
    /**
     * Returns a paginated list of personas.
     * @return The persona.
     */
    @GET
    @Path("/ex0")
    PaginatedResponse<Persona> readPersonasWithGenerics();
```
 
**otherwise** if I use the annotation (I need the annotation because I am working with async responses), it doesn't produce any useful return type doc.

```
    /**
     * Returns a paginated list of personas.
     * @return The persona.
     * @returnWrapped com.ifyouwannabecool.domain.PaginatedResponse<com.ifyouwannabecool.domain.persona.Persona>
     */
    @GET
    @Path("/ex1")
    void readPersonasWithWrappedResponse();
```

Any suggestion? Am I wrong writing the annotation?

EDIT: if you want to try my code, go here: https://github.com/lordkada/enunciate-sample/tree/generics

**Comment by stoicflame** [comment]
It's just that `@returnWrapped` doesn't support generics yet.

I'll track this issue as an enhancement request and adjust the title to reflect the request.

**Comment by Honatas** [comment]
I'm looking forward to this feature. It will be extremely useful.

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
