### ISSUE TITLE
java-json-client to insert build version into MANIFEST

### ISSUE THREAD

**Issue by c-a-m** [stoicflame/enunciate#969]
I would love to have the version set for java-json-client to make it into the `MANIFEST` of the jar under `Implementation-Version`

**Comment by c-a-m** [comment]
I'm poking around the code to see if I could create a pull request.   I'm guessing it isn't in the `java-json-client` subproject.  Any pointers?

**Comment by stoicflame** [comment]
Tracking as an enhancement request.

Yes, you're in the right place. `packageArtifacts` would be a good place to implement this enhancement.

**Comment by stoicflame** [comment]
As of 2.13, you'll be able to add a `<manifest>` configuration element in the `enunciate.xml`:

```xml
<java-json-client>
  <manifest>
    <entry name="..." value="..."/>
```

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
