### ISSUE TITLE
format/type information in swagger file

### ISSUE THREAD

**Issue by vghero** [stoicflame/enunciate#970]
We're using e.g. `Instant`s in our REST models which are rendered as strings in the enunciate documentation and the swagger file. Now we have the problem, that in our clients, that we generate from the swagger file, we only have strings as date's and not the actual type. 

According to the swagger spec https://docs.swagger.io/spec.html#433-data-type-fields there exists something like `format` which allows to specify more detailed types like `date` or `date-time`. Now I'm wondering if there's support for such things in the swagger module.

I already saw the `dateFormat` attribute of the jackson module, but I guess this only helps with the generated jackson examples, no?

**Comment by stoicflame** [comment]
Tracking as an enhancement for now.

Can you provide an example of your REST models that use `Instant`s? And can you provide an example if how you'd like the `swagger.json` to look for these?

**Comment by vghero** [comment]
Thanks for taking your time looking into this.

So the model looks like this:

```
public class Timings {

    private Instant estimatedDeliverAt;

    public Instant getEstimatedDeliverAt() {
        return estimatedDeliverAt;
    }
    public void setEstimatedDeliverAt(Instant estimatedDeliverAt) {
        this.estimatedDeliverAt = estimatedDeliverAt;
    }
}
```

And the Swagger looks like this:

```
...
"Timings":{
   "type":"object",
   "title":"Timings",
   "properties":{
      "estimatedDeliverAt":{
         "readOnly":false,
         "description":"",
         "type":"string"
      }
   }
}
...
```
Preferably Swagger should look like this (see `date-time`):
```
...
"Timings":{
   "type":"object",
   "title":"Timings",
   "properties":{
      "estimatedDeliverAt":{
         "readOnly":false,
         "format":"date-time",
         "description":"",
         "type":"string"
      }
   }
}
...
```

I made this work by providing a custom `swagger.fmt` and adding a hardcoded "type" hack into it like this :):

```
...
            "readOnly" : ${property.readOnly?c},
            [#list dataType.javaElement.enclosedElements as element]
                [#if element == property.name && element.asType() == 'java.time.Instant']
            "format": "date-time",
                [/#if]
            [/#list]
            [@referenceDataType dataType=property.dataType description=(property.description!"") defaultType="object"/]
...
```

Sadly I had to make this loop through all properties again - per property, since I wasn't able to find any existing method, that provides the simple java type of a `property` :). It would have been even nicer, to have access to those abstract "types" I saw somewhere like "DATE_TIME" (IIRC) and not having to check for the concrete java type here.

Maybe this "format" finds a way into the enunciate core code base somehow :).

**Comment by vghero** [comment]
Thank you so much!

**Comment by stoicflame** [comment]
[Enunciate 2.12](https://github.com/stoicflame/enunciate/releases/tag/v2.12.0) has been released.
