### ISSUE TITLE
Module IDL - useFile sample

### ISSUE THREAD

**Issue by gpr7700** [stoicflame/enunciate#975]
Hello

I'm using the last version of enunciate and I am interested by the useFile feature.

My project is a contract-first project where all the schemas (xsd/wsdl) are documented using xsd:documentation elements 

What I a m looking for is :
- enunciate makes use of the description (xsd:documentation)
- enunciate makes reference  to the existing xsd files (keep the name)

My questions regarding the useFile attribute are
- do we have to provide a relative path ? absolute path ? 
- can we provide a maven path such as in Jaxb XML catalog (<systemSuffix systemIdSuffix="JustX-GEKO_InvoiceDomain.xsd" uri="maven:be.fgov.ejustice.justx.geko:geko-model:jar::!/JustX-GEKO_InvoiceDomain.xsd"/>) - would be nice in the catalog could be used directly :-)

Regards

Gregory

**Comment by stoicflame** [comment]
Either relative path or absolute path should work.

You can also provide a maven property reference in the `enunciate.xml` file, e.g.:

```xml
<enunciate>
  <modules>
    <idl>
      <schema namespace="..." useFile="${project.build.outputDirectory}/file.xsd"/>
```

**Comment by gpr7700** [comment]
Hello

Thanks for your answser.

I tried the following configurations without any success (enunciate-maven-plugin 2.11.1)

`<schema namespace="http://ejustice.fgov.be/justx/internal/geko/invoice/v2_0/messages" useFile="**${project.build.directory}/classes**/InvoiceMessages.xsd"/>`

`<schema namespace="http://ejustice.fgov.be/justx/internal/geko/invoice/v2_0/messages" useFile="**${project.build.outputDirectory}/classes**/InvoiceMessages.xsd"/>`

The schema is always generated and therefore 
- the original name is lost (ns8.xsd)
- the xsd:documentation tag is not used by the enunciate plugin.

Our projects are "contract-first" projects where wsdl/xsd files are 
- documented by a dedicated team
- split amongst several dependencies (use of catalog file with maven path such as  `<systemSuffix systemIdSuffix="JustX-GEKO_InvoiceDomain.xsd" uri="maven:be.fgov.ejustice.justx.geko:geko-model:jar::!/JustX-GEKO_InvoiceDomain.xsd"/>`)

Am I missing something ?

Regards

**Comment by stoicflame** [comment]
With your latest example, I'm better able to understand your use case.

So Enunciate is designed to work from Java source files, so the only way you're going to get documentation from your schemas is to use something like XJC to generate the Java objects first, then invoke Enunciate on those Java source files.

As for pattern-based IDL file usage, it seems like Enunciate could provide that feature but it doesn't exist today.

**Comment by gpr7700** [comment]
yes you are correct, we are working as follow

1./ wsdl/xsd are designed and documented
2./ maven-jaxb2-plugin is used to generate all the classes (+ catalog file for referencing xsd located within dependencies)
3./ enunciate-maven-plugin is used to generate the documentation

My issue is that the documentation generated by enunciate does not include the xsd:documentation elements that are specficied with the wsd/wsdl files hence my original question about the attibute useFile.

But I guess that I must first have to investigate the jaxb plugin in order to know if that's possible to import the xsd:documentation within the Java objects

**Comment by stoicflame** [comment]
We could add a feature to Enunciate to be able use all schema files in a folder. If you'd like to track that work, you're welcome to open a separate issue as an enhancement request.
