### ISSUE TITLE
Ignoring fields from documentation (only)

### ISSUE THREAD

**Issue by vghero** [stoicflame/enunciate#983]
We have a REST API where we want to rename fields. To be able to be backwards compatible, we simply introduced the new field and keep support for the old one as well. Since it might be confusing in the docs, we would like to just exclude the old fields from the documentation (only) - so new clients will directly use the new field. But _not_ from the JSON payload using @JsonIgnore. It would be nice, if that would be supported.

**Comment by panchenko** [comment]
@vghero have you tried the `com.webcohesion.enunciate.metadata.Ignore` annotation?

**Comment by stoicflame** [comment]
Or the `@ignore` JavaDoc.

**Comment by vghero** [comment]
Works like a charm! Although one has to take care with the javadoc version. `@Ignore != @ignore` :). Thanks guys!

**Comment by vghero** [comment]
Ah, just forgot to mention, that the wiki page only mentions that those can be put on a class. Not on other places like fields, methods etc. Thanks again anyway!

**Comment by stoicflame** [comment]
Fix has been included in Enunciate 2.12.1.

**Comment by vghero** [comment]
Sweet, thx!
