### ISSUE TITLE
Recognize JSON data types even if jackson is not on classpath

### ISSUE THREAD

**Issue by Oliveiras** [stoicflame/enunciate#990]
I've spent hours trying to understand why, in this simple Java EE project, Enunciate didn't generate the data type JSON for my returned DTO.

pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test.enunciate</groupId>
    <artifactId>test-enunciate-json</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <packaging>war</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <failOnMissingWebXml>false</failOnMissingWebXml>
        <javaee.version>7.0</javaee.version>
        <enunciate.version>2.12.1</enunciate.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>javax</groupId>
            <artifactId>javaee-api</artifactId>
            <version>${javaee.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.webcohesion.enunciate</groupId>
            <artifactId>enunciate-core-annotations</artifactId>
            <version>${enunciate.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.webcohesion.enunciate</groupId>
                <artifactId>enunciate-maven-plugin</artifactId>
                <version>${enunciate.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>assemble</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```

Resource.java
```java
package test.enunciate.json;

import com.webcohesion.enunciate.metadata.rs.TypeHint;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Application;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;

@ApplicationPath("api")
@Path("/test")
public class Resource extends Application {

    @GET
    @Produces(MediaType.APPLICATION_JSON)
    @TypeHint(Dto.class)
    public Response get() {
        return Response.ok(new Dto(1)).build();
    }

}
```

Dto.java
```java
package test.enunciate.json;

public class Dto {

    private int number;

    public Dto(int number) {
        this.number = number;
    }

    public int getNumber() {
        return number;
    }

    public void setNumber(int number) {
        this.number = number;
    }
}
```

This application just works. Just deploy it to any Java EE Application Server.
But Enunciate doesn't recognize that my return type is JSON, besides the Produces annotation.

After much time, I've found this issues, which made me think this difficult is not only mine:
 - https://github.com/stoicflame/enunciate/issues/167
 - https://github.com/stoicflame/enunciate/issues/640

The problem is exacerbated by the fact that the Getting Started and the enunciate-sample (https://github.com/stoicflame/enunciate-sample) uses only XML and don't exibhits the issue (because you have the annotation XmlRootElement).
I don't think this is a good choice for the Getting Started, since nowadays most applications uses JSON.

Also, I couldn't easily find this information on the User Guide. Not even on the Jackson module documentation.

In my opinion, it would be very intuitive if the maven plugin brings the necessary jackson dependencies himself, not requiring the user to mess with his classpath.
If this is not possible, at least the documentation should make it super clear that the jackson classes should be on the classpath (probably with a warning about the scope, instead of suggesting compile scope and risking conflict with a different version provided by the web container).

**Comment by stoicflame** [comment]
So I think you'd like to see the following:

1. Update the enunciate-sample to focus on JSON.
2. Assume Jackson for JSON, even if it's not on the classpath, or add extra documentation to make sure it's clear why JSON docs aren't getting generated.

Anything else?

**Comment by Oliveiras** [comment]
> Anything else?

That's it.

Regarding number one, can I help with that (pull request)?
I can "convert" the enunciate-sample to JSON. Just tell me where do you want the code to be placed:
 - Replace XML with JSON and only
 - Replace, but move old XML example to new location
 - Don't replace, instead create new location for new JSON example

**Comment by stoicflame** [comment]
I haven't really thought about it. What would be most clear?

It seems like maybe we should split out these three things?

1. SOAP interface
2. REST (XML) interface
3. REST (JSON) interface

**Comment by Oliveiras** [comment]
Maybe create 3 repositories for examples (or 3 branches) and on the section Getting Started, on the Wiki, provide the 3 links.

**Comment by stoicflame** [comment]
Finally getting around to looking at this, and it's turning out to be harder and more unclear than expected. A few notes:

1. Enunciate uses the classpath to determine which flavor of JSON is being used. Currently, Enunciate can support documentation for Jackson 1 and for Jackson 2. Enunciate doesn't "activate" its documentation for either one unless it finds one of those on the classpath. The idea is that whatever is on the classpath of the application is what will be documented. I can't think of a better way to do it.
2. You can "force-enable" via config one of the modules to tell Enunciate to activate regardless of what's on the classpath.
3. If both Jackson 1 and Jackson 2 are enabled, Enunciate provides a warning.
4. The JSON is already active in the Enunciate sample, so I'm not sure what's needed there.

**Comment by stoicflame** [comment]
Okay, I've refactored the [Enunciate sample app](https://github.com/stoicflame/enunciate-sample) to be more clear now.

I think that's all that remains of this issue, so I'm going to close it. I'm happy to re-open as needed.
