### ISSUE TITLE
Enunciate v2.12.* cannot process enums in endpoints

### ISSUE THREAD

**Issue by darthlynx** [stoicflame/enunciate#995]
I have an endpoint in my API which has the enum return statement, e.g.:
```
@Path("stuff")
@GET
@Produces({ MediaType.APPLICATION_JSON })
public Stuff getStuff() {
    return stuffService.getStuff();
}
```
where:
```
public enum Stuff {
    FOO, BAR
}
```

**Expected behavior**
Endpoint should return the [standard enum representation](https://www.baeldung.com/jackson-serialize-enums#1-default-enum-representation) (either "FOO" or "BAR")

**Actual behavior**
I'm getting the error below, if I use Enunciate v2.12.*, but enum is deserializing fine if I'm using v2.11.1.

![image](https://user-images.githubusercontent.com/14966979/70052876-e8be5e80-15dc-11ea-9517-e9c4d3e7c974.png)

![image](https://user-images.githubusercontent.com/14966979/70052719-8ebd9900-15dc-11ea-8aa9-ac659738ce10.png)

**Environment:**
- Enunciate v.2.12.1 and v.2.12.0
- openjdk version "11.0.5" 2019-10-15 LTS
- maven 3.6.0
- OS: CentOS 7

**Comment by darthlynx** [comment]
Thank you @stoicflame! Could you tell me which release will include this fix?

**Comment by darthlynx** [comment]
Found the milestone 2.13. Thanks again!

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
