### ISSUE TITLE
Is there a way to customize the "list" wrapper in response example?

### ISSUE THREAD

**Issue by sbrattla** [stoicflame/enunciate#996]
I'm using the `@TypeHint` annotation on resource methods. For methods that returns multiple items, I use e.g. `@TypeHint(value = Territory[].class)`.

In the response example, the `<territory>` gets wrapped with `<list>`. Is there a way to replace this `<list>` with e.g. `<territories>`? 

![image](https://user-images.githubusercontent.com/1845372/70800023-75220b80-1dab-11ea-90c8-2607bd9eda0e.png)

**Comment by stoicflame** [comment]
The only way I know how to do that in line with spec is to implement a "wrapper" object. Something like this:

```java
@XmlRootElement
public class Territories {
  @XmlElement(name="territory")
  public Territory[] territories;
}
```
