### ISSUE TITLE
How to exclude the XML category in Enunciate 2.12 ?

### ISSUE THREAD

**Issue by Piskel** [stoicflame/enunciate#997]
So I use enunciate 2.12 with Spring boot and I'm trying to get rid of the XML category in the documentation.

![Screenshot_2019-12-18 Web Service API](https://user-images.githubusercontent.com/16492833/71090506-74bab380-21a3-11ea-8ca6-aec553ff285f.png)

Here is my enunciate.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<enunciate
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://enunciate.webcohesion.com/schemas/enunciate-2.12.0.xsd">
    <modules>
        <java-xml-client disabled="true" />
        <xml disabled="true"/>
        <jaxws disabled="true" />
        <jaxws-client disabled="true" />
        <jaxws-ri disabled="true" />
        <docs includeExampleXml="false"/>
    </modules>
    <api-classes>
        <include pattern="path.**"/>
    </api-classes>
</enunciate>
```
I found [this question](https://stackoverflow.com/questions/22763669/deactivate-xml-examples-and-xml-documentation-in-enunciate) on SO but it doesn't work for me.

I also tried various things I found on the Web but most of them were for version 1.+ and they didn't work.

I don't understand how to do this or if it's possible. Any answer is appreciated ! Thank you.

**Comment by stoicflame** [comment]
That question on SO was just about how to disable the example XML in the docs, no about how to disable XML entirely  from the docs. If you'd like to try disabling XML entirely, I'd suggest:

```xml
<enunciate>
    <modules>
        <jaxb disabled="true"/>
        <jaxws disabled="true" />
    </modules>
</enunciate>
```

**Comment by Piskel** [comment]
Thank you very much ! this works
