### ISSUE TITLE
JSON Documentation for Subclasses

### ISSUE THREAD

**Issue by amberream** [stoicflame/enunciate#999]
I have an abstract superclass, PageActionModel which has several subclasses such as ResizePageActionModel.
When I send a ResizePageActionModel via POST/PUT the json needs to look like this:
{
    "ResizePageActionModel": {
        "pageIndex": 0
        ...
    }
}

But the generated docs only show the inner part:
{
        "pageIndex": 0
        ...
}

Would be nice if the docs showed that when using a subclass, that you must specify the subclass in the json.

```
@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, include=JsonTypeInfo.As.WRAPPER_OBJECT)
@XmlSeeAlso({OCRActionModel.class, ImageStampActionModel.class, TextStampActionModel.class, InsertAttachedPagesActionModel.class, InsertUploadedPagesActionModel.class, NewPageActionModel.class, RotatePageActionModel.class, PageOrderActionModel.class, AddImageActionModel.class, AddTextActionModel.class, ResizePageActionModel.class})
public abstract class PageActionModel
{
	
}
```
```
@XmlType(name="ResizePageAction")
@XmlRootElement(name="ResizePageAction")
public class ResizePageActionModel extends PageActionModel
{
	/**
	 * The index of the page to resize.  If not supplied all pages will be resized.
	 */
	public int pageIndex = -1;
	
	/**
	 * The new page width, in points (72 DPI).  IF not supplied, the width of the page will not be changed.
	 */
	public int newPageWidth = -1;
	
	/**
	 * The new page height, in points (72 DPI).  If not supplied, the height of the page will not be changed.
	 */
	public int newPageHeight = -1;
	
	/**
	 * Resize the existing content, in percent.  If not supplied, the content will remain at the same scale.
	 */
	public int scaleContent = 100;
}
```
```
@POST
@Consumes(MediaType.MULTIPART_FORM_DATA)
public PagesModel post(@FormDataParam("pageAction") PageActionModel pageAction, @FormDataParam("file") InputStream file, @FormDataParam("file") FormDataContentDisposition fileDisposition)
{
    ....
}
```

**Comment by stoicflame** [comment]
I'll need some more information to pursue this one.

What does the Java code look like?

It looks like you're using "wrapper object" polymorphic type handling in Jackson. How are you configuring that? Is it with a custom object mapper or via annotations?

**Comment by amberream** [comment]
I'm using annotations, added code to the original description.

**Comment by stoicflame** [comment]
What does the POST/PUT method look like?

**Comment by amberream** [comment]
Added POST method to original description.

**Comment by stoicflame** [comment]
Okay, so next question:

Do you have any suggestions on how Enunciate is supposed to look at that `POST` method and figure out that it needs to document the `ResizePageActionModel` as the request?

**Comment by amberream** [comment]
The docs for the POST method are fine since any subclass of PageActionModel can be used, I was more concerned with the Example section for the ResizePageActionModel, where the example that's generated should specify that the json needs to be surrounded with the name of the subclass. If you have a way of seeing that the class you're generating json for is a subclass I would assume the subclass needs to be specified (at least it does the way that we're using it).

![image](https://user-images.githubusercontent.com/1459928/72289902-16ee7f80-361a-11ea-99a3-12a81e356c5b.png)

**Comment by stoicflame** [comment]
[Enunciate 2.13.0 has been released.](https://github.com/stoicflame/enunciate/releases/tag/v2.13.0)
